- mods/gennext/abilities.js
Changing Swift Swim, Sand Rush, Chlorophyll to give a 1.5x speed boost to nerf weather in NEXT.
> NEXT: Tweaks to Swift Swim, Sand Rush, Chlorophyll

- tournaments/index.js
Allow changes to the player cap and send a message to the user if
changes were successful
> Tournaments: update /tour settype

- chat-plugins/wifi.js
- currently supports 2 formats: question and lottery.
> Add wi-fi chat plugin: giveaways

- commands.js
Screwed up a rebase in the last pullreq and deleted the branch by mistake
> Update /invite, fix /me and /announce in PM

- chat-plugins/wifi.js
- modified help command
- Send error messages if commands are used on other rooms.
> WiFi plugin: fix grammatical errors, slighly modify giveaway object

- chat-plugins/wifi.js
Codelegend's previous commit broke one of the commands when tested, making the /ga command unreconized when trying to answer a question, This commit fixes that
> Wifi Plugin: Fixing a command

- data/formats-data.js
- data/scripts.js
Just for variety. This might make it worse than whatever items it'd end up with normally, though; it's level scaled high enough as it is.
Also debating whether Slash is actually a good replacement for Return or not. Since it always crits, it has a higher effective Base Power compared to Return (105 BP vs 102! omg!) but Return still has that 50% chance of critting and that factor might make it better overall.
Also note the stealth-edit which only changes some minor comment expressing doubt about a joke long dead
> Give Farfetch'd the Stick item in randbats

- data/scripts.js
Pokemon such as Butterfree receive the Compound Eyes ability even when they do not have any inaccurate moves.
> Change Compoundeyes to Compound Eyes

- commands.js
Hides messages from locked and banned users
> Support new |unlink| message

- chat-plugins/wifi.js
Allows global staff have the ability to use the script in the room; if they wish to do so, any % or higher should have the ability to start a giveaway. Furthermore updating help commands to make them more convenient to type and use.
> Wi-Fi Plugin: allow global staff to use script

- chat-plugins/wifi.js
Increase the answer field limit for answers; does not break the answer mechanics when I tested, also increasing the number of winners in lottos from 5 to 10. After a few days of having the script in the chat I feel these changes would be more suitable for it.
> Wifi Plugin: Make questions less restrictive

- mods/gen1/moves.js
Haze was broken by 3bbc9cca1e70745a3449a3095b32a10258404bc3 (thanks, `git bisect`).
> Gen 1: Fix Haze's target.

- data/aliases.js
- data/formats-data.js
Mostly just for Seasonals purposes, really.
Made "Eternal Floette" and "Floette-Eternal" aliases for
Floette-Eternal-Flower, which is a mouthful.
(Do we need to add "Eternal Flower Floette" as well? Unsure)
> Add Eternal Floette Random Battle Movesets and Aliases

- protocol-doc.md
Did I seriously forget to document these earlier? For shame...
> Document |win| and |tie| messages

- chat-plugins/trivia.js
If a chat plugin exports anything besides commands, it is cached in
``CommandParser.plugins``. If the state of anything needs to be kept when
/hotpatch chat is used, the plugin can export what needs to be kept
and reassign once one of its commands is used for the first time.
> /hotpatch chat preserves chat plugin exports

- data/aliases.js
Just some terms I've seen thrown around. (Quick additions before I leave work)
> Add some new aliases

- chat-plugins/wifi.js
Export the giveaway object to `wifiRoom.plugin`
> wifi plugin: export plugin data

- chat-plugins/jeopardy.js
- chat-plugins/scavengers.js
- chat-plugins/thehappyplace.js
(Scavengers variables) --> Rooms.get('scavengers').plugin
Jeopardy jeopardies --> Rooms.get('academics').plugin.jeopardies
The The Happy Place plugin now saves the quote of the day in
Rooms.get('thehappyplace').chatRoomData.
> Chat plugins: finish exporting plugin states

- chat-plugins/trivia.js
I really need to stop being bad with operator precedence
> Trivia plugin: fix /trivia add permissions

- chat-plugins/tcg.js
Made a command searching the yugioh wiki for yugioh cards. This does require a new library for XMLHttpRequest.
> TCG yugioh search

- LICENSE
> License: Update copyright year to include 2015

- chat-plugins/tcg.js
A lot of duplicate code though, but I don't see a way to do it better.
> Implemented a mtg search function as well, together with fixing concerns

- chat-plugins/trivia.js
> Trivia plugin: actually fix /trivia add permissions

- chat-plugins/wifi.js
following morfents commit but updating it for the wi-fi plugin aswell, to avoid issues after hotpatching
> Wi-fi Plugin: Finish Exporting states

- chat-plugins/wifi.js
This is unnecessary. ( #1476 comment 10)
> Revert "Wi-fi Plugin: Finish Exporting states"

- data/formats-data.js
- Regular Charizard shouldn't have Solar Beam.
- Mega Charizard Y gets Focus Blast.
> Random Battle: Update Charizard Random Battle Moves

- data/scripts.js
Rock Slide was mentioned twice. The second one was meant to be Rock Blast
(I can't even believe I missed this)
> Random Double Battle: Fix Stone Edge Typo

- data/formats-data.js
- data/scripts.js
- Reject Quick Attack with Feint
- Remove Return, Quick Attack, Feint from regular Pinsir
- Remove Feint from Hitmonchan, Hitmonlee
- Add Fire Punch to Hitmonchan
- Replace Stone Edge with Rock Slide for Doubles
> Random Battle Updates

- data/scripts.js
They prefer Natural Cure.
(( Now actually implemented correctly! The last time I tried this it was implemented backwards and they would always have Serene Grace ))
> Random Battle: Reject Serene Grace on Blissey and Chansey

- data/formats-data.js
- data/scripts.js
(( There are so many Pokemon, I stopped the moveset updates at Gen 4 Pokemon. ))
> Random Battle: Many Moveset Changes

- data/formats-data.js
- data/scripts.js
~~Xerneas has no business running Thunder in a non-Ubers format since Drizzle is rather uncommon.~~
~~NO I'M NOT MAD THAT I NEARLY LOST A RANDBATS GAME DUE TO XERNEAS MISSING THUNDER TWICE IN A ROW AND LETTING THE OPPONENT SET UP, WHY DO YOU ASK~~
Xerneas is a good Pokemon, but there are sets it can run that don't require Geomancy. Might as well give it some variety.
> Random Battle: Diversify Xerneas' Moveset

- chat-plugins/tcg.js
It took a while, but it should be better now.
> Fixed up the TCG search functions

- chat-plugins/tcg.js
> Fix some problems in the TCG searcher

- data/scripts.js
The current variables in place to check for STAB do not work as intended.
If a Pokemon has two STAB moves of the same type, and one of them is set
as a move that shouldn't be counted as STAB, the Pokemon will be counted
as not having STAB. Since nothing in the code checks for Pokemon having
STAB of a specific type, it is refactored to be a boolean instead.
In order to avoid a situation where a move like Infestation sets the STAB
variable to true when it doesn't count as a damaging move, these kinds of
moves no longer increment counters for abilities that boost damage, like
Adaptability.
> Random Battle: Refactor STAB Move Checks

- data/scripts.js
This fixes for real the issue of Pokémon with multiple viable Hidden Powers getting less than four moves sometimes.
> Randbats: fix incomplete movesets

- test/simulator/items/flameorb.js
Killing Focus Sash Magikarps with one attack is so amazing.
> Create Flame Orb test

- test/simulator/moves/haze.js
Thunder Wave has a small chance to miss, setting seed to value that I know doesn't fail the test fixes the problem. Fixes #1548.
> Initialize Haze test with values that don't fail.

- data/scripts.js
- Prevent Focus Sash and Life Orb with Multiscale.
- Add Custap Berry as a low-priority item for Sturdy + Explosion
> Random Battle: Item Updates

- battle-engine.js
- data/abilities.js
- data/items.js
- data/moves.js
- test/simulator/abilities/pickup.js
- test/simulator/abilities/unburden.js
- test/simulator/items/mail.js
- Unburden was not triggering with Natural Gift and Fling.
- Mail that was Knocked Off was recyclable.
- Fix Pickup to work properly.
Tagging @Marty-D so he can verify that I'm implementing these correctly.
This should fix everything in #591.
> Item Removal Fixes

- test/simulator/abilities/unburden.js
Using Leaf Storm gave the test a 10% chance to fail if it missed.
> Update Unburden test

- README.md
add badges:
- build (travis CI)
- dependencies (david-dm)
- devDependencies (david-dm)
> readme: add build and dependency badges

- commands.js
``/topic``
Sorry for shelving the other one, I just screwed that one up too much to go back :(
> Add alias for /roomintro

- chat-plugins/thestudio.js
The plugin can now manage nominations on its own instead of not doing
much more than broadcasting HTML, and the Artist of the Day survives
hotpatching and server restarts.
> The Studio plugin: overhaul nomination commands

- config/commands.js
in the given description of ``/cap``, it even says "An introduction to the Create-A-Pokemon project"
> add alias for /cap

- config/commands.js
``/repostitory`` and ``/repo`` because that is what **this** is! A repository!
> add 2 aliases for /opensource

- data/scripts.js
It now uses the same rules as Random Battle (Singles).
> Random Doubles Battle: Improve move rejection with one attacking move

- chat-plugins/trivia.js
``/trivia ranking`` is pretty much like /ranking on the ladder
``/trivia create`` is just like when using ``/tour create``
> Add aliases for trivia

- chat-plugins/wifi.js
Make it O(n) from O(n^2).
I will try to make it O(1) by storing IPs, but that needed a lot of changes. So, till I finish that, i suppose we can afford something better.
> wifi plugin: improve performance of alt checking

- data/scripts.js
It would not reject Baton Pass if the Pokemon did not have Speed Boost.
**I'm so ashamed of myself for messing up this check**
> Random Battle: Fix Baton Pass check

- formats.js
- scripts.js
Style based on current gulpfile.
Two issues to be resolved:
- `randomSeasonalTeam`: both **Seasoning's Greetings** and **Thankless Thanksgiving** use the same name. Scripts at lines 9 and 546
- `randomSeasonalFFTeam`: both **Fools Festival** and **Fabulous February** use it. Scripts at lines 173 and 600
> [branch] old-seasonals: fix all syntax and style errors

- formats.js
The inverse mod has been removed, and instead coded into the format. So add it here for consistency.
(code copied from OM inverse battle)
> [branch] old-seasonals: update inverse mod

- config/formats.js
This was requested by Formerhope.
> Seasonal: Prevent Formerhope's signature from copying abilities

- chat-plugins/wifi.js
Added an exception in the ip check so that the original user isn't recognized as an alt.
http://prntscr.com/6eyje8
> Added an exception in IP check.

- config/formats.js
he goes by ``LegitimateUsername`` not ``Legitimate Username``
> Remove spaces from LegitimateUsername's text

- data/scripts.js
> fix rekeri

- data/formats-data.js
- data/scripts.js
Although, perhaps we should discuss whether Meloetta should even be allowed to run a Step Forme set.
> Random Battle: Update Meloetta

- config/formats.js
Even though they may be a part of that line for a reason, they can appear as
on smaller screens.
Or they may look awkward next to the brick walls.
> Move the text on Genesect's messages to separate lines

- data/scripts.js
same reasoning as the other PR that got merged
> Seasonal: Fix spacing errors 2.0

- data/scripts.js
There is no item called Brick Mail.
> Make &Sweep hold Mail instead of Brick Mail

- data/scripts.js
> Random Battle: Force Unburden with Acrobatics

- data/scripts.js
Prevents Sub+DD+Outrage from receiving Leftovers.
> Random Battle: Increase priority of Outrage+Setup item check

- data/scripts.js
Affects Lucario. It should prefer Crunch unless it is a Nasty Plot set.
> Random Battle: Reject Crunch and Dark Pulse together

- rooms.js
Code ostensibly works, but I'm worried about race conditions and non-default clients. Is that something we need to worry about?
> Add option to automatically send replays in config

- data/formats-data.js
It doesn't want Super Fang since it usually gets Guts anyways.
> Random Double Battle: Update Raticate

- config/commands.js
Please let me know if there are any grammatical errors, or better ways to write the doc.
> document namespace like functionality of commands

- data/scripts.js
The second case includes the first case.
> remove redundant code in get team

- config/formats.js
lol i forget that there's two files
also changed
``			if (name === 'Test2017') {``
to
``			if (name === 'test2017') {``
(I lowercased the 't' in the code)
> Seasonal: Lowercase antemortem v2

- config/formats.js
> Seasonal: Move hollywood

- app.js
- config/config-example.js
- users.js
also removed `Config.groupsranking`, and assigned it while caching.
> cache config groups: optimize user permission checks

- config/formats.js
This is probably the true cause of the crash that was happening.
> Seasonals: Clear flags objects instead of deleting them

- battle-engine.js
- Split it off from `runDecision` to `parseChoice`
- Internally, `decision.team` is now an array of zero-based positions.
- Guard against slot duplicates.
> Improve validation of team order decisions

- chat-plugins/trivia.js
Currently facedesking liberally.
> Trivia plugin: fix crash in /trivia accept and /trivia reject

- mods/stadium/moves.js
In Stadium, Effect chance for Acid is 51/256, Effect chance for Aurora Beam is 77/256, and Effect chance for Bubblebeam is 77/256.
> Acid, Aurora Beam, Bubblebeam Effect chances

- config/commands.js
This seems like a lazy solution, but it's functional as far as my testing has found. If there is a better way to check for ally targeting just let me know.
> Use "Ignores Protect" instead of "Blocked by Protect"

- mods/gen1/formats-data.js
Just got a recover/twave/stoss/reflect kadabra in randbats -_-
> Psychic>Recover for essential move on Kadabra/Zam

- battle-engine.js
- data/moves.js
- data/scripts.js
- mods/gen4/abilities.js
Some ModifyBoost refactoring was needed to do this but it's ok
Implementation is probably sloppy and could be improved.
> Fix Foresight and Miracle Eye to use ModifyBoost

- battle-engine.js
- mods/gen3/items.js
- mods/gen4/items.js
- mods/gen4/rulesets.js
- test/simulator/moves/transform.js
Causes Dittos transforming into Giratina-O without Griseous Orb to revert
to Giratina-A in Generation 4, etc.
> Generation 4: Fix Transform's interaction with items

- battle-engine.js
- data/abilities.js
- data/scripts.js
Cleans up the code quite a bit because it no longer needs the hardcoding
option that it was having.
> Refactor Unaware to use ModifyBoost

- command-parser.js
Include characters that are important to the function of commands.
> Fix broadcast cooldown message checking.

- battle-engine.js
It doesn't use the Pokemon's boosts.
> Fix ModifyBoost in calculateStat

- data/formats-data.js
It was just the singles one with Protect added so it had some really bad moves that I removed.
> Fixed Avalugg's Random Doubles Moveset

- data/abilities.js
What does `hasType('ironball')` mean anyways?
> Arena Trap Typo Fix

- data/formats-data.js
- data/scripts.js
Reject Seed Bomb with Giga Drain.
Switch Cacturne's Doubles set to fully Physical.
> Random Battle: Update Cradily, Cacturne

- data/scripts.js
There is no reason for Flygon to run both, and having two fire moves restricts Flygon a bit.
> Reject Fire Blast with Fire Punch

- chat-plugins/wifi.js
Fixes a case where /showanswer was not working correctly due to incorrect operators.
Also fixing spacing of the sentence from The answer is/are[answer] to The answer is/are [answer]
> Wifi Plugin: fix /showanswer

- config/config-example.js
- tournaments/index.js
When tournaments are created in the specified rooms, they will be
announced in the server's main tournament room
http://i.imgur.com/2DuTRUt.png
> Add config option to announce tournaments

- data/abilities.js
While I'm here, @Marty-D, does Slow Start display a message if it's active and the ability gets removed?
> Change Slow Start to listen to End events

- mods/gen2/formats-data.js
Nidoran-m doesn't learn Earthquake / Fire Blast / Ice Beam. Not sure which moves to use instead.
> Nidoran-m fix

- chat-plugins/wifi.js
Log the user that the giveaway was done for in the modlog ontop of roomauth who did it
> Wifi Plugin: Log what user have done giveaways

- data/formats-data.js
- data/scripts.js
Also implement fix for Meloetta starting out in Pirouette Forme in Random
Doubles Battles.
> Random Battle: Split Castform into Sunny and Rainy Formes

- chat-plugins/trivia.js
- /trivia rank now shows the user's rank for each of the three score
types
- Add /trivia ladder
- Fix crash in timer mode scoring
- Fix /trivia submit excluding all but the first answer in certain cases
- Fix /trivia accept and reject
- More consistent object notation
> Trivia plugin: score ladder and ranking, bug fixes

- data/scripts.js
Seems a bit redundant to have both together. Affects articuno.
> Random battles: Reject ice beam & freeze dry together

- data/statuses.js
- mods/gen2/statuses.js
- mods/gen3/statuses.js
- mods/gen4/statuses.js
- Gen 5-6: Thaw check is skipped when using a self-thaw move
- Gen 3-4: Thaw check happens before a move is used
- Gen 2: Self-thawing does not happen if the move misses
> Fix thaw mechanics in all gens

- chat-plugins/wifi.js
Fix giveaways becoming frozen/endless from hotpatching, fix possible
crash in lottery giveaways, simplify lottery drawings, and improve
wording in multiple statements.
> Wi-Fi Plugin: various fixes/improvements

- data/formats-data.js
- data/scripts.js
Single Battle: Replace Rock Climb with Return if Tauros does not have
Sheer Force (1/3 chance of getting Intimidate)
Double Battle: Remove Rock Climb for Return and add Stone Edge, since
Tauros always has Intimidate in Random Double Battles
> Random Battle: Update Tauros

- config/formats.js
- data/scripts.js
fixed casing on bean, barton, and haunter
fixed `@Timbuktu`'s rank
added MattL and shaymin to voices since they 'retired/resigned'
> Seasonal: Adjust a lot

- config/commands.js
Though operationally not the best way to check for this, I don't think this particular feature will get used often enough that it needs to have a larger portion of code dedicated to it.
> add = operator to ranges in /ds and /ms

- config/formats.js
- data/scripts.js
Added `%QuoteCS`'s Pok&eacute;mon, move, and entering/dying phrases (I
talked with him on PS! for info on what he wanted, you can ask him if you don't believe me).
Fixed casing on `%Birkal`, `%DTC`, and `%raseri`.
Moved `@rekeri`'s and `@Timbuktu`'s moves to the correct places.
> Seasonal: Adjust a lot more

- config/commands.js
Doesn't change functionality at all, I just find it easier to read this way.
> Minor style changes to /ds and /ms

- data/scripts.js
> Random Battle: Reject Leaf Blade with Giga Drain and no Setup

- commands.js
Fix showing public auth in the private auth list and remove the second
loop through rooms
> Fix /userauth

- config/formats.js
it was giving the foe the boosts
> Seasonal: Fix QuoteCS's move

- config/commands.js
removed unnecessary uses of ```Tools.getMove()``` and ```Tools.getTemplate()```
Average search time currently reduced to around 20ms. (excluding recovery search)
> Improve performance with /ds

- config/commands.js
Added a parameter to /movesearch that only searches moves from a target pokemon's learnset.
> Add learnset targeting to /movesearch

- commands.js
We have that on IRC and im lazy
> Added /j as an alias for /join

- config/commands.js
Combines the learnsets to then search against later.
> include learnsets from prevos in /ms

- tools.js
They have been officially recommended against for a long time
> Remove all `fs.existsSync` calls

- chat-plugins/trivia.js
- the ladder is now saved in triviadata.json, and gets updated at the
same time ranks do instead of needing to loop through the leaderboard
once more
- the inactivity mode clears properly on answer
- number and timer modes accept multiple answers again
- added question and intermission timeout consts
- Trivia property names are more specific
> /Trivia plugin: optimize ladder updates, bug fixes

- config/formats.js
- data/scripts.js
Needs Joim's approval, but I figured I would put it here now (for Joim to merge after approving this set), because I have to go away now.
> Super Staff Bros.: Add %galbia.

- config/commands.js
CH is the abbreviation of Classic Hackmons, and it's easier to do !om with.
> Add alias "ch" to /om classichackmons

- config/formats.js
- data/scripts.js
(and to think I was a voice when this seasonal began... thank you all)
> Super Staff Bros.: Promote @xfix

- chat-plugins/trivia.js
Binary searches are now used instead of linear ones when splicing
questions in and slicing all the questions in a category from the
questions arrays.
Also stopped using backwards loops where it wasn't necessary and
used double quotes where applicable.
> Trivia plugin: optimize question handling

- config/formats.js
Fix TMTRAINER by removing code, great plan.
(not surprised Gen1 was full of bugs)
> Super Staff Bros.: Repair TMTRAINER.

- config/commands.js
Creates "priority" parameter for `/dexsearch` which searches for Pokemon that learn offensive moves with greater than zero priority. 
To prevent this added parameter from greatly slowing the command, full learnsets from prevos are now cached before searching against the learnsets. While this makes searching for only one move slightly slower, it greatly improves speed for searching multiple moves.
The slowest possible search (`/ds !magikarpsrevenge, !struggle, !chatter, !sketch, recovery, priority`) takes about 50ms, which is still faster than the current slowest possible search.
> add "priority" to /dexsearch

- config/config-example.js
- sockets.js
The issues Heroku had with SockJS have been fixed for a while since
https://github.com/sockjs/sockjs-node/issues/57, now that it supports
long polling and WebSockets.
> Remove Heroku hack

- config/commands.js
New thread: http://www.smogon.com/forums/threads/ou-theorymon.3536615/.
> Changes OU Theorymon thread

- data/abilities.js
- test/simulator/abilities/deltastream.js
- test/simulator/abilities/desolateland.js
- test/simulator/abilities/primordialsea.js
This was going to be an Air Lock fixing pullreq, but while writing regressions I discovered that Cherrim was causing my tests to fail, plus #1801 was already underway.
> Fix Flower Gift to properly use formeChange

- config/commands.js
New thread was posted: http://www.smogon.com/forums/threads/tier-shift-viability-ranking-v2.3536719/#post-6183334
> Changes /om ts's Viability Rankings thread link

- config/formats.js
- data/scripts.js
I also moved %Hugendugen's entry quote because it wasn't in the right
place and I changed the double quotes to single quotes.
> Super Staff Bros.: Add %Kayo

- config/formats.js
- data/scripts.js
- Promoted Acedia and Audiosurfer.
- Fixed one of Diatom's ranks.
- Moved shaymin's and MattL's moves to the correct areas, as well as
Acedia's and Audiosurfer's.
> Seasonal: Rank Changes

- chat-plugins/info.js
For consistency with `/coverage`. Plus it just looks nicer.
> Grey font for 'None' with /weak

- chat-plugins/trivia.js
- Fix style on multiline strings
- Use double quotes for HTML
- Fix remaining bugs in trivia submission from bee3a73
> Trivia plugin: add /help docs, more style fixes

- test/simulator/abilities/desolateland.js
- test/simulator/abilities/primordialsea.js
aka: I got home late and for some reason decided I want to keep up my pointless Github streak
> Fix up Desolate Land/Primordial Sea tests

- config/formats.js
http://3ds.pokemon-gl.com/information/39ba0f38-a88f-4d02-b0f4-82536fda0107
> Add Little Cup [PGL] battle competition

- battle-engine.js
- data/abilities.js
Moved them from AnyModifyPokemon to AnySwitchIn based on information in
https://github.com/Zarel/Pokemon-Showdown/issues/1789 from @gamut-was-taken
> Fix Air Lock and Cloud Nine

- chat-plugins/info.js
These help entries are becoming quite a wall of text.
> update help entries: /ds and /ms

- chat-plugins/info.js
- config/formats.js
- mods/seasonal/moves.js
- add an alias for /seasonaldata
- add a check in /seasonaldata if there is no target
- change quotes in formats.js and add the same alias
- fix some missed instances of followe
> Seasonal: Changes

- data/items.js
- test/simulator/moves/followme.js
- test/simulator/moves/ragepowder.js
This fixes Rage Powder's interaction with Safety Goggles.
> Fix Rage Powder's interaction with Safety Goggles

- config/formats.js
- mods/seasonal/moves.js
- add the new /seasonaldata alias to the beginning message
- change all single quotes surrounding the move animations into double
quotes (just because it was like that in the Mar+Apr Seasonal)
> Seasonal: More changes.

- data/scripts.js
Prevents things like Shell Smash + Toxic Spikes.
> Random Battle: Reject Toxic Spikes where Spikes is rejected

- data/scripts.js
not really necessary, but "more proper"
> Battle Factory: EV Fix

- data/scripts.js
- test/simulator/misc/statusmoves.js
- test/simulator/moves/stealthrock.js
- Improve the wording on tests for status moves to be more clear
- Add a test for Stealth Rocks
> Upgrade tests

- data/aliases.js
> Add new Alias for Primal Groudon

- data/moves.js
- test/simulator/moves/imprison.js
Imprison was not blocking moves the turn it was used.
> Fix Imprison bugs

- config/formats.js
http://3ds.pokemon-gl.com/battle/oras/110/regulation/
> Update Battle Spot Special 10

- chat-plugins/info.js
With more and more people playing older gen formats I've seen a few people request this lately.
Gen information for Pokemon, moves, and items
> /details: gen information

- chat-plugins/thestudio.js
- chat-plugins/trivia.js
- Remove question sorting on loading the Trivia plugin, since it is no
longer required
- Trivia game winners are chosen based on who answers first, not who
signs up first
- The Artist of the Day is no longer always the first artist to be
submitted
- Replace instances of foo > -1 with foo >= 0
> Chat plugins: AotD and Trivia bug fixes

- app.js
- battle-engine.js
- chat-plugins/info.js
- chat-plugins/scavengers.js
- chat-plugins/trivia.js
- commands.js
- data/moves.js
- data/rulesets.js
- data/scripts.js
- mods/gen1/moves.js
- mods/gen1/scripts.js
- mods/gen2/moves.js
- mods/gen4/moves.js
- mods/hiddentype/scripts.js
- team-validator.js
- tools.js
- users.js
See https://github.com/Zarel/Pokemon-Showdown/pull/1765#discussion_r28191226
grep search seems to indicate I got them all.
> Style fix: indexOf() comparisons

- PROTOCOL.md
- battle-engine.js
It's not a rule clause or part of a custom metagame,
> Add -center message type for Triples Automatic Center

- data/scripts.js
Refactor set generation function to use a new parameter `teamDetails` to
keep track of more than just whether there shouldn't be a Mega Evolution.
---
aka: The Revenge of the `teamDetails`
triple SR setters is seriously dumb though
> Restrict Stealth Rocks on Random Battle Teams to 2

- battle-engine.js
- data/moves.js
- test/simulator/moves/belch.js
https://www.youtube.com/watch?v=paMtFIVWRkQ&t=6m33s
> Belch cannot be selected if the Pokemon has not eaten a berry

- commands.js
Adding the Room Owner (#) on Broadcasting requires. On the Broadcasting requires appears all ranks except the #.
> Adding '#' on Broadcasting requires.

- chat-plugins/jeopardy.js
the only commands that regular people can't use are /end /create and /start so I specified that in the /jeopardy help
> Add what requirements are needed to use some jeopardy commands

- PROTOCOL.md
I don't remember if it was @ascriptmaster or @Slayer95 who recommended this, but I took a shot at it. This definitely isn't the most succinct way to explain what's happening, but I figured this would be enough of an outline that I could take corrections from those who understand this better then I do.
> Battle request commands documentation

- mods/gennext/statuses.js
An examination of the commit history seems to indicate that it was
intended to be bypassed by Mold Breaker variants, and not be affected
by Gastro Acid.
> Gen-NEXT: Fix Intrinsic Levitate

- commands.js
Adding /unafk as a alias of /back, because i see now that if there is "/afk" there must be "/unafk".
> Add /unafk as a alias of /back

- data/formats-data.js
70.2% of the voting for the nu suspect have voted ban.
> Ban Magneton from NU

- config/formats.js
If you want me to implement `[Gen 4] Doubles` I'll do that too.
I mostly need this to run the correct oldgen tests involving Pressure before I can consider how to fix it.
> Implement [Gen 4] Doubles Custom Game

- chat-plugins/info.js
- commands.js
This is a replace of pull request #1930.
> Add "#" on requires

- config/formats.js
Not sure if there's more to edit, but can RBY Ubers be added to Showdown for an RBY Ubers tournament in the Smogon Tournaments forum?
> Added RBY Ubers

- chat-plugins/info.js
> Fixing smogintro link

- chat-plugins/info.js
Add a reply in /invite command if there is no target.
> Add "this.parse" in /invite command

- command-parser.js
- commands.js
- rooms.js
- users.js
Move muting to `rooms.js` and run only one timer per room instead of one timer per room-user pair. Users are queued to use the unmute timer.
> Mute refactor

- data/aliases.js
this is used heavily by most if not all UU players
> Add gatr as an alias for Feraligatr  

- commands.js
- Fix /hourmute command, because when someone use the command without a target, mute help comes and not hourmute help. 
- Add (!this.canBroadcast()) in /roomalias command.
> Fix some commands

- data/moves.js
- test/simulator/abilities/contrary.js
At least, that's what Bulbapedia claims. Can @Marty-D verify?
> Belly Drum's boost is inverted by Contrary

- battle-engine.js
- data/moves.js
This allows for a clean, non-hardcoded interaction with Contrary.
----
Basically what @Marty-D was talking about in #1983.
> Use Battle#boost in Belly Drum's Hit handler

- mods/gen1/moves.js
Gen 1: Mimic can copy Transform.
Tested in Link Battle
> Gen 1: Mimic can copy Transform.

- chat-plugins/info.js
- commands.js
- Send a help reply if there is no target in /roomowner and /roomdeowner command.
- Add 2 new aliases for pm faq.
> Improve help provided by commands

- commands.js
- Add /hourmute and /modnote in Driver (%) Help. 
- Add /modchat in Moderator (@) Help.
> Add new commands in /help

- chat-plugins/trivia.js
Made it so you can join trivia games midgame. I also made it so they can't join if unable to talk. The last change was showing who submitted the question in QW.
> trivia games joinable midgame + show who submits qs

- chat-plugins/info.js
- Updated various Viability Ranking links
- Added a new alias for Doubles OU (which is frequently used by the Doubles OU community and when people are referring to it)
- Updated the url for Tiering FAQ to make it consistent with the other links
> /tier updates

- chat-plugins/info.js
- Add "chall" as a alias of "Challenge" in Faq, so people can do /faq chall, I add this because in challenge command they have a alias named "chall".
> Add "chall" as a alias of "Challenge" in Faq

- data/scripts.js
Also remove its Cosplay Pikachu formes since those don't register as
having evolutions.
`;-;7`
> Random Battle: Pikachu is no longer an allowed NFE

- chat-plugins/info.js
Because items are based mostly in function callback it seemed mostly impractical to try to search with anything other than the descriptions. This is obviously not ideal, but it seems to work _okay_ at least.
This is probably most useful for berries in particular because the names don't do a good job describing what they do and there are a lot of berries to try to remember then all. As such I focused mostly on getting it to work well for berries which I find it correctly returns what I'm searching for most of the time.
I'm sure this can greatly be improved and am open to suggestions (even if it means scrapping this entirely and taking a different approach). Small details like the ratio of needed matched words are easy to adjust and more testing will help fine tune it to make it feel right.
> Add /itemsearch

- chat-plugins/info.js
For custom configuration purposes I think it makes more sense to only make people change 1 number rather than 3. I know `const` in .js is pretty weird so I'm not sure if it should be a variable instead, though.
> Use single constant for search outputs: /ds, /ms, /itemsearch

- app.js
- battle-engine.js
- chat-plugins/info.js
- chat-plugins/traditionalgames.js
- gulpfile.js
- team-validator.js
- tools.js
- users.js
- Requires discussion: <strike>Usage of ``Tools.getId`` vs ``this.getId`` / ``this.battle.getId`` in ``battle-engine.js``, ``data/*.js``, ``mods/**/*.js`` files.</strike>. Scrapped ``Tools.getId``.
- <strike>Also requires discussion: ``toName`` in ``team-validator.js``.</strike> Straightforwardly fixed.
> Move globals toName|toString to Tools: Tools.[getName|getString]

- chat-plugins/info.js
If you're searching a lot of things, it can become hard to keep track which search was which, so this is supposed to help make it easier to look back through the searches you have done.
> Output command used in search result: /ds, /ms, and /itemsearch

- data/aliases.js
Add mega pokemon aliases: maero and mray.
> Add mega pokemon aliases.

- mods/gen1/moves.js
Haze removes the volatiles from both players.
> Gen 1: Haze fix

- mods/gen1/statuses.js
https://github.com/iimarckus/pokered/blob/master/engine/battle/core.asm#L3504
> Gen 1: Full paralysis chance is 63/256

- mods/stadium/statuses.js
http://datacrystal.romhacking.net/wiki/Pok%C3%A9mon_Stadium:ROM_map#Full_Paralysis_check
> Stadium: Full paralysis chance is 63/256

- commands.js
1) Only display popups to users who are currently in the room. This prevents abuse.
2) Allow warns to be used in private rooms with own authorities.
3) Display a button to list room staff in the roomban popup.
Requires https://github.com/Zarel/Pokemon-Showdown-Client/pull/419 for (3)
> Improve room punishments

- tools.js
- tournaments/index.js
By setting ``tournamentShow: true`` or ``tournamentShow: false``
> Support toggling format availability for tournaments

- battle-engine.js
- test/simulator/abilities/battlearmor.js
- test/simulator/abilities/clearbody.js
- test/simulator/abilities/damp.js
- test/simulator/abilities/dryskin.js
- test/simulator/abilities/flashfire.js
- test/simulator/abilities/immunity.js
- test/simulator/abilities/levitate.js
- test/simulator/abilities/lightningrod.js
- test/simulator/abilities/magicguard.js
- test/simulator/abilities/multiscale.js
- test/simulator/abilities/shellarmor.js
- test/simulator/abilities/stickyhold.js
- test/simulator/abilities/stormdrain.js
- test/simulator/abilities/sturdy.js
- test/simulator/abilities/suctioncups.js
- test/simulator/abilities/thickfat.js
- test/simulator/abilities/unaware.js
- test/simulator/abilities/wonderguard.js
Damp should be suppressed by Mold Breaker.
> Fix Mold Breaker interaction with Damp

- data/scripts.js
Nobody likes the current Pyroar set. :c
> Randoms: Enable Lilligant to get Own Tempo

- chat-plugins/info.js
Somebody complained about this in the bug report thread.
I personally find that somebody even tried this absurd but if you want a fix, here you go.
> /coverage: Struggle is typeless

- package.json
- rooms.js
Client-side: https://github.com/Zarel/Pokemon-Showdown-Client/pull/429
> Update formats list protocol to support tournament-only formats

- data/abilities.js
- test/simulator/abilities/flowergift.js
[10:32:54] &xfix: (and fix Flower Gift... I should have done this long time)
Basically just doing this for xfix since he hasn't done it yet.
> Fix Flower Gift

- data/abilities.js
- data/moves.js
- test/simulator/moves/rollout.js
Instead, it now doubles BP after each complete execution of the move.
> Ice Ball and Rollout do not double BP when hitting multiple times/turn

- app.js
- chat-plugins/traditionalgames.js
- command-parser.js
- dev-tools/users-utils.js
- gulpfile.js
- loginserver.js
- package.json
- test/simulator/abilities/simple.js
- users.js
- All dependencies are optional except for `sockjs` and `sugar`.
- Fixes global variable leaks in `cloud-env` and `node-static`.
- JSCS: various rule additions regarding spacing; also yoda conditions banned.
> Update dependencies and JSCS rules

- config/formats.js
- data/scripts.js
Rainbow Road is a Mario Kart and color themed seasonal.
Every few turns, a player can get an item that changes the course of the
battle, such as a Mushroom to increase speed.
Pokemon also get color moves that are super-effective on certain other
colors.
----
Something something. Most of this should be tested but I can't be sure about things like the Blooper lowering accuracy or whatever.
Messages at the start of the battle could be improved.
@Zarel @Slayer95
> Implement August/September Seasonal, Rainbow Road

- chat-plugins/info.js
- data/aliases.js
/analysis Meowstic and /analysis Meowstic-M now link correctly.
> Fix behavior with /analysis Meowstic

- config/formats.js
- The OMotM link lead to last month's OM
- http://www.smogon.com/forums/threads/monsjustmons-lcotm-august.3514696/page-3#post-6358892 Archeops is banned from MonsJustMons, the LCotM
> Formats: Fix OMotM link and Ban Archeops from LCotM

- commands.js
> Specify return message if there's no global auth

- data/abilities.js
- mods/gen4/abilities.js
Related: https://github.com/Zarel/Pokemon-Showdown-Client/pull/435
> Replace -activate tags on Anticipate/Forewarn with -ability

- chat-plugins/info.js
I see it asked a in a lot of rooms when suspect tests happen, this should help
> Add /faq coil

- config/formats.js
> Seasonals: Delta Stream does not affect Color Moves

- app.js
- battle-engine.js
- chat-plugins/info.js
- commands.js
- team-validator.js
- tools.js
> Split tools load: structure before most files; data from plugin requiring it

- data/formats-data.js
They have the same BP in Gen 6, so Ancient Power is the better STAB.
> Random Battle: Replace HP-Rock with Ancient Power on Lunatone

- data/formats-data.js
- data/scripts.js
Replaced Psyshock with Hyperspace Hole in Singles.
Reject Psychic with Hyperspace Hole in Doubles.
> Random Battle: Slightly tweak Hoopa, fix chance of Hoopa forme appearing

- data/scripts.js
It is given to Pokemon within a certain speed tier with 3 Special attacks
and also U-Turn.
> Random Battle: Add extra scenario for Choice Scarf distribution

- data/formats-data.js
- data/scripts.js
Give it Dazzling Gleam as an attack option, and reject Unburden on it if
it doesn't have setup moves.
> Random Battle: Update Slurpuff

- config/formats.js
- data/rulesets.js
- mods/gen1/rulesets.js
- mods/gen2/rulesets.js
- mods/gen4/rulesets.js
- mods/stadium/rulesets.js
- team-validator.js
[Didn't mean to branch here but whatever]
> Better support for formats' customizing team validation; update STABmons

- chat-plugins/info.js
Now Veekun provides ORAS data.
> Add /veekun command for checking Veekun Pokedex

- commands.js
- Rename ``chat-commands.js`` to ``commands.js and the chat-plugins``.
- Add /host in Leader (&) help.
> Improve help in commands

- tournaments/index.js
Allow reasons and send popups
Screenshot: http://i.imgur.com/MatBLTE.png
> Tournaments: improve disqualifying users

- rooms.js
Use room ranks when applicable
> Update user stats logging

- chat-plugins/trivia.js
- Add a reply if a "Trivia" or "Question Workshop"  command is used in other room.
> Improve trivia plugin

- battle-engine.js
- data/statuses.js
- test/simulator/abilities/desolateland.js
- test/simulator/abilities/primordialsea.js
- test/simulator/misc/weather.js
Closing this TODO: http://git.io/vZKZ5
This PR also contains a small refactoring for damage randomization, to allow more resilient testing of damage calculations.
> Weather modifies baseDamage instead of basePower

- battle-engine.js
- data/abilities.js
This allows it to send a proper [from] tag to the client.
> Add a source parameter to BattlePokemon#transformInto

- chat-plugins/thestudio.js
Requested by The Studio owners
> The Studio plugin: add /aotd quote

- chat-plugins/info.js
> added a /statcalc command

- static/404.html
- static/index.html
- Add a guide of how to enable JS in your browser.
- Add ``&eacute;``.
> Improve static files

- data/scripts.js
Affects Charizard.
---
A point of discussion that came up was whether or not we can increase Sheer Force's rating or lower Mold Breaker's such that Rampardos won't get Mold Breaker. Alternatively, we could hardcode it onto Rampardos.
> Random Battle: Ability and Move Updates

- commands.js
I've been having trouble testing this because I only have one IP, though... I need to figure out port forwarding at my new place
> Implement /hidetext command

- chat-plugins/poll.js
- rooms.js
Haven't been able to fix the broadcasting above the command yet.
> Some bugfixes to /poll

- commands.js
currently if the command results in access denied you get "/hidetexthidetext - Access denied."
> remove double instance of hidetext in the error reply

- data/formats-data.js
- data/scripts.js
Also, allow Pumpkaboo/Gourgeist formes in Seasonals and add a nickname for
Espurr.
> Update NFE Random Battle sets being used in Seasonals

- chat-plugins/info.js
> Fix some mistakes in the banned rooms feature

- battle-engine.js
- data/abilities.js
Note: Ideally this will be merged before a restart, along with the related client PR (https://github.com/Zarel/Pokemon-Showdown-Client/pull/517) + client update.
> Improve support for Ability activation

- tournaments/index.js
- allow autodq to be set before a tournament starts
- set a timer for Tournament.runAutoDisqualify instead of waiting for
another function to call it or the runautodq command to be used
> Tournaments: improve autodq

- data/statuses.js
**Do not merge** before a client update!
[Drought & Drizzle](http://i.imgur.com/fJGxAlG.gif) | [Drought & Primordial Sea](http://i.imgur.com/2YBDSBV.gif)
> Update weather Ability activation

- tournaments/generator-elimination.js
- tournaments/index.js
Generate the bracket when the tournament starts rather than during
signups to randomize seeds
> Tournaments: randomize seeds in elimination

- data/formats-data.js
- data/scripts.js
Remove Endeavor.
Force Guts on Pokemon with the ability and have Protect (but not Wish, for
the occasional Flareon)
> Random Battle: Update Swellow, Flareon

- repl.js
No idea why it happened, but `unlinkSync` returned without actually unlinking the file, so it sent repl into an infinite loop
> Fix repl not being able to unlinkSync files under mocha

- config/formats.js
- data/aliases.js
- data/scripts.js
I'm dead
I'll create a few more custom sets later (maybe after the work week is over)
> Implement November Seasonal, Super Squad Showdown

- commands.js
Sorry to have to make this again.
Once again, not completely sure this is the best way to do this, but it works.
> Unlink target username on punishment

- rooms.js
- tournaments/index.js
Not sure if this is the most efficient check, I couldn't find another check similar to this to use as reference.
> Remove user from a tournament when room banned

- commands.js
These checks check if the room is or is not official before proceeding with /officialroom
> Check official room status in /officialroom

- chat-plugins/hangman.js
- chat-plugins/poll.js
- chat-plugins/thestudio.js
- chat-plugins/trivia.js
And add checks in for hangmans and polls if the user can talk or not while we're at it.
> Standardize canTalk() permission in chat-plugins

- data/scripts.js
Gligar always gets Immunity.
Solar Power is rejected on Mega Charizards.
Improve move selection with Drought to ensure a Fire move or Solar Beam on
Pokemon with the ability.
> Random Battle: Update Gligar and Mega Charizards

- chat-plugins/info.js
Hoopa-Unbound's smogdex link led to a non-existent page.
> Fix smogdex for Hoopa-Unbound

- chat-plugins/thestudio.js
> The Studio plugin: show number of noms in viewnoms

- commands.js
- monitor.js
Allows developers to turn off the use of hotpatch.
> hotpatch: implement /hotpatch disable

- commands.js
this.errorReply instead of this.sendReply to keep with the style of the rest of the commands specially /blockchallenges and /unblockchallenges.
> change to errorReply in /(un)blockpms

- chat-plugins/thestudio.js
And also state the number of prenoms as well
> The Studio plugin: list nominations alphabetically

- chat-plugins/mafia-data.js
- chat-plugins/mafia.js
This is still very unpolished and incomplete, but it'd be very nice to be able to test this more on the main server.
> Add a chat plugin for Mafia

- chat-plugins/trivia.js
- /trivia kick did not update responder indices if a player that
answered correctly was kicked, which timer mode depends on for scoring
- /trivia qs no longer lists random and undefined as categories
> Fix /trivia kick and /trivia qs

- chat-plugins/mafia.js
> Mafia: fix a stupid copypasting mistake causing the plugin to not work

- tournaments/index.js
I personally really like the current auto start command but more often than not I feel like having it start when the player cap is reached would be more useful so having the option to do that would be nice, especially in bigger rooms. Not sure if this is the best way to do it though. (And not so sure about the name of it either.)
> Add an auto start at player cap option for tours

- chat-plugins/mafia-data.js
- chat-plugins/mafia.js
Thanks to the people who helped me with this (amazing failure of a) first test run.
> Mafia updates

- chat-plugins/mafia.js
fuck man I feel so dumb for messing up function scopes.
> Mafia fixes and updates

- tournaments/index.js
Add the ability to check if the timer for the current tournament has been set and what it's been set to.
Change timeout to timer in the modlog message.
> Change setautodq messages

- tournaments/index.js
The function requires an "output" argument.
> Fix tournament auto disqualify error

- commands.js
> Sorting roomauth correctly

- chat-plugins/mafia.js
And trying not to crash PS this time.
> Mafia: bugfixes

- commands.js
Updated required rank shown in makechatroomhelp, as well as added the "confirmed user" requirement for /makegroupchat.
> Update messages for some help entries

- chat-plugins/hangman.js
Tagging @bumbadadabum because I don't know why the `<small>` is needed; it looks the same to me either way. Alternatively, we can remove the spaces entirely and fiddle with the CSS e.g. `letter-spacing:0.333ch`.
> Simplify generating the HTML for the word so far

- mods/gennext/abilities.js
- mods/gennext/formats-data.js
- Unban the listed Mega Evolutions under the new tiering system
- Fix issues with modified abilities being treated as invalid
---
Maybe I should write up all-new descriptions for all the modified abilities.
> Fix Gen-NEXT Team Validation Errors

- config/formats.js
http://www.smogon.com/forums/threads/sand-veil-in-dpp.3558511/page-3#post-6603062
> Ban evasion abilities in DPP OU

- config/formats.js
https://www.smogon.com/forums/threads/3545230/page-8#post-6603059
Please merge ASAP because this widely impacts the meta
> Ban Mega Rayquaza from OMotM: Gods and Followers

- config/formats.js
- data/aliases.js
- data/scripts.js
> Implement January Seasonal, Polar Opposites

- .eslintrc
- battle-engine.js
- chat-plugins/info.js
- chat-plugins/jeopardy.js
- chat-plugins/poll.js
- chat-plugins/wifi.js
- cidr.js
- commands.js
- ladders-remote.js
- rooms.js
- simulator.js
- team-validator.js
- tools.js
- tournaments/generator-elimination.js
- tournaments/index.js
- users.js
> Remove explicit decimal radix from parseInt

- .eslintrc
- battle-engine.js
- chat-plugins/info.js
- chat-plugins/jeopardy.js
- chat-plugins/poll.js
- chat-plugins/wifi.js
- cidr.js
- commands.js
- ladders-remote.js
- rooms.js
- simulator.js
- team-validator.js
- tools.js
- tournaments/generator-elimination.js
- tournaments/index.js
- users.js
Reverts Zarel/Pokemon-Showdown#2359
> Revert "Remove explicit decimal radix from parseInt"

- data/formats-data.js
Changed everything with 3.4% or lower usage according to these usage stats: http://www.smogon.com/stats/2015-12/pu-1630.txt
> Change FU pokemon from "PU" to "(PU)"

- config/formats.js
http://www.smogon.com/forums/threads/stabmons-see-post-101-for-update.3547279/page-9#post-6608163
> STABmons: Ban Altarianite

- config/formats.js
http://www.smogon.com/forums/threads/gods-and-followers-omotm-january.3545230/page-11#post-6616771
> Ban Geomancy from OMotM: Gods and Followers

- data/scripts.js
> Simplify sampleNoReplace function

- chat-plugins/info.js
/statcalc 252+ speed heatran
/statcalc 252+ev speed heatran.
The 2nd always worked, but the 1st should too. Now it does.
(Also fixed a typo in the command description.)
> changed /statcalc command to accept argument "252+"

- commands.js
Instantly seeing who set it would make things easier (e.g. if you wanna ask why it was set).
> Use privateModCommand for modchat

- mods/gennext/README.md
- mods/gennext/scripts.js
- mods/gennext/statuses.js
I'll get to the rest eventually.
> Gen-NEXT: Apply Intrinsic Levitate to Rotom formes

- data/pokedex.js
http://www.smogon.com/forums/threads/cap-21-part-13-flavour-ability-poll-2.3563252/page-2#post-6645382
> Add Crucibelle's flavor ability

- config/formats.js
- mods/mixandmega/scripts.js
~~Mix and Mega is most likely going to be temporary until Partners in Crime is coded.~~
Nevermind, Mix and Mega is now officially OM of the Month, so it's permanent.
Done by request of @TheImmortal.
> Add new OMs of the Month

- chat-plugins/trivia.js
- commands.js
This replaces old instances like <code>"User [user] does not exist."</code> with instances like <code>"User [user] not found."</code>.
> Standardize "User [user] not found." in commands

- config/formats.js
The CAP 21 Playtest Tournament finished earlier today.
http://www.smogon.com/forums/threads/cap-21-playtest.3561537/page-2#post-6656465
> CAP 21 Playtest is over

- commands.js
The keyword search doesn't always find all relevant entries, because
users have different ways of formatting their username.
With this change, there will be two ways to do a keyword search:
/modlog n - ignores non-word characters (\W*) in between letters. Edit: For example, /modlog ausername will also bring up matches like "a username" or "a user-name".
/modlog "n" - strictly matches only the given formatting of n. (This is
how /modlog worked before.)
I also changed /modlog [number] to sort matches newest-to-oldest, like
the keyword search does.
These changes don't apply to PS servers running on windows. modlog will
behave the same as before for them
> Change /modlog to match on IDs

- tournaments/index.js
As per the comments on https://github.com/Zarel/Pokemon-Showdown/commit/04fe908b22998c445c1dd52c9a4375f87ffe9cee
> Change permissions for tournament start/end

- config/formats.js
- data/aliases.js
- data/scripts.js
Putting the PR so @TheImmortal and @ascriptmaster can say what they think. It's for March, can be added anytime between today and the fifth (but preferably the sooner the better). Also @Zarel opinions.
> Implement March Seasonal, Dimension Doom

- data/scripts.js
Based of what was said in https://github.com/Zarel/Pokemon-Showdown-Client/pull/662#discussion_r54695369 you were looking for something like this.
> Notify client when a move is a spread move

- app.js
- battle-engine.js
- chat-plugins/dexsearch.js
- chat-plugins/info.js
- chat-plugins/tcgtabletop.js
- chat-plugins/trivia.js
- command-parser.js
- commands.js
- data/moves.js
- data/rulesets.js
- data/scripts.js
- loginserver.js
- mods/gen1/scripts.js
- mods/gen2/scripts.js
- mods/gen5/moves.js
- monitor.js
- package.json
- rooms.js
- team-validator.js
- tools.js
- tournaments/generator-elimination.js
- tournaments/index.js
- users.js
> Remove Sugar.js

- mods/gen1/pokedex.js
Horsea's SpA and SpD should be the same base stat of 70.
> Gen 1: Change Horsea's SpD from 79 to 70

- config/config-example.js
- tournaments/index.js
- change the config option to room-specific options
- update rooms after adding announcements
> Tournaments: update tournament announcements

- chat-plugins/poll.js
"The poll timer was turned on: the poll will end in 1 minutes"
> minute(s) not minutes [poll.js]

- data/abilities.js
All other abilities use '[from] ability:'
> Pickup: make -item message consistent with others

- app.js
- chat-plugins/dexsearch.js
- chat-plugins/info.js
- commands.js
- process-manager.js
- simulator.js
- team-validator.js
- verifier.js
- Creating multiprocess tasks easier than ever.
- ``Tools.dexsearchProcess`` mess cleaned.
- Processes for signed messages verification and dexsearch are now fully optional.
> Enhance process management via PM API

- config/formats.js
spydreigon is global +, mcmeghan is &, jdarden is @, etc
> updated staff ranks on this.add('whatever message')

- config/formats.js
I updated ranks that I noticed I missed out Phable requested for his name to be changed to Paradise~.
> update ranks and names in seasonal (everyone should be done till someone gets promotion)

- mods/seasonal/moves.js
It says badly poisons in the description, but it regularly poisons in game
> Seasonal: Make Eevee General's move match desc

- config/formats.js
- mods/seasonal/README.md
- mods/seasonal/abilities.js
- mods/seasonal/moves.js
- mods/seasonal/statuses.js
- Balance update for SpaceBass, RosieTheVenusaur, SpecsMegaBeedrill, Innovamania, Halite
- Add missing prompt for Skitty
- Update documentation
- Increase visibility of documentation link
- Fix style for consistency
> Seasonal: Balance Update

- mods/seasonal/README.md
- mods/seasonal/moves.js
- Change category
- Change effect from secondary to primary
- Tentatively fix target to circumvent client crash caused by logic oddities in useMove
> Seasonal: Fix and update bludz move

- chat-plugins/scavengers.js
(requested by Scavengers room staff)
> Scavengers plugin: show finishing times

- config/formats.js
His faint message had already been updated.
> Super Staff Bros: Update jdarden to global mod

- tournaments/generator-elimination.js
- tournaments/generator-round-robin.js
- tournaments/index.js
Also:
- remove Tournament#purgeGhostUsers as it's no longer needed
- update Tournament#challenge and Tournament#disqualifyUser to use
userids to work in cases where user objects have expired
> Refactor tournaments to use the RoomGamePlayer API

- config/formats.js
- mods/seasonal/README.md
- mods/seasonal/moves.js
- mods/seasonal/scripts.js
- Fix Rage effect in Bondie signature move
- Nerf Bondie signature move
- Change target selection of shrang signature move to agree with documentation
- Adjust animations
> Seasonal: Fix Bondie and shrang signature moves

- config/formats.js
- mods/seasonal/README.md
- mods/seasonal/moves.js
- mods/seasonal/pokedex.js
- mods/seasonal/scripts.js
- Buff Bondie
- Nerf Marshmallon
- Nerf Mizuhime
- Fix qtrx signature move animation glitches
- Other minor changes
> Seasonal: Bugfix and Balance Update

- data/moves.js
> Add Contest Spectacular types to all moves

- tournaments/generator-elimination.js
- tournaments/generator-round-robin.js
Update users' roomgame lists once they are disqualified, eliminated from
an elimination tournament, or finish all of their pending matches in a
round robin tournament
> Tournaments: update roomgame lists during tours

- config/formats.js
> Seasonal: Update Zero Lux Given

- chat-plugins/wifi.js
> Wifi: Prevent muted/locked users joining giveaways

- commands.js
Someone in some room or other suggested that the userauth command should also show any battles where the user has auth.
> Include battles in output of userauth command

- battle-engine.js
- config/config-example.js
- test/main.js
Cut down a useless config option
> Remove config option for the crash guard

- chat-plugins/datasearch.js
I added this to [rom.psim.us](http://rom.psim.us/) when I added the OM "Got Talent?".
> Add contest conditions to move searches

- commands.js
> Remove ' ' case from /modchat

- tournaments/index.js
> [tournaments.js] grammar & minute(s) not minutes

- data/scripts.js
> Random Battle: Explosion should not be the only STAB

- mods/gen2/formats-data.js
Reference (the same list in two places): 
http://mount-silver.proboards.com/thread/9/gsc-tiers
http://pokemon-online.eu/threads/gsc-tier-list.5260/
> Add GSC NU tier list

- commands.js
Lockdowns are about server restarts, not server shutdowns
> endlockdown: Better phrase declared message

- data/scripts.js
Save Swords Dance if Sun-less Growth is on the set.
Remove Weather Ball entirely if Sunny Day is rejected.
> Random Battle: Various sun-related fixes

- commands.js
- users.js
Namelock locks a user into the unreachable name 'Pokemon Trainer #nnnnnn', the ns being a number.
This user cannot change name unless they are force renamed.
> Implement namelock

- chat-plugins/mafia.js
- room-game.js
- rooms.js
- simulator.js
- tournaments/index.js
- users.js
Fixes various crashes caused by roomgame players changing names outside
of the room
> Follow all player renames in roomgames

- chat-plugins/datasearch.js
I didn't recreate the whole fork - should I do that?
> Minor wording fixes in /movesearch

- battle-engine.js
The other callers pass a Format object, which has different behaviour, in particular, it uses the format's actual `mod` instead of guessing that it's the same as the format.
I'm wondering whether the `battleProtoCache` should be keyed off `mod` rather than `format` but I'm not going to touch it with all of those prototypes flying around. (Or maybe I should convert it to a Map?)
> Don't pass the id of a format to Tools.mod

- team-validator.js
I apparently lost this part when rebasing #2262 yesterday :|
> Support event Vivillons in team-validator

- config/formats.js
Also add a warning message about Delibird fainting.
> Seasonal: Minor prose/grammar fixes

- data/scripts.js
Affects Roserade and ensures that it does not receive Chesto Berry.
> Random Battle: Reject Technician with Natural Cure + Rest

- data/abilities.js
http://replay.pokemonshowdown.com/nususpecttest-388681198 (turn 1).
> Surely it can't be right for Protean to activate on a move bounced by Magic Coat?

- test/simulator/abilities/deltastream.js
- test/simulator/abilities/desolateland.js
- test/simulator/abilities/primordialsea.js
- test/simulator/misc/weather.js
Updated remaining Primal Weathers to the new APIs.
Updated misleading test cases relating to base power of moves in
Desolate Land / Primordial Sea.
Increased coverage on weather tests.
> Tests: Update Weather tests for clarity and readability

- chat-plugins/info.js
Lists the rooms that a user is muted in: http://i.imgur.com/xaO8sCx.png
Similar to "banned from", this can be useful to determine if a user is
hitting multiple rooms.
> Add "muted in" to /whoare

- mods/enchanteditems/scripts.js
Maybe Analytic was forgotten while writing the EI script.
> Add Analytic as a held ability to Enchanted Items

- config/formats.js
- data/aliases.js
- data/scripts.js
Sky Battle with Fire-type "hail" in the form of fireworks sparks.
@Joimer please review the seasonal before merging
> Implement July Seasonal: Fireworks Frenzy

- data/aliases.js
This makes it easier when doing broadcasting commands in a discussion.
> Add Ampharos and gyarados alias

- mods/enchanteditems/rulesets.js
Thanks @urkerab for pointing out
Copied from http://www.smogon.com/forums/threads/general-thread-for-om-code.3517025/page-3#post-6877561
> Update Baton Pass Clause for Enchanted Items

- config/formats.js
- mods/enchanteditems/scripts.js
> Ban Manaphy
> Link Nomel Berry to Levitate
> Update Enchanted Items

- chat-plugins/info.js
> Show the contest condition as one of the move's details

- commands.js
Having two if statements on one line is strange, and we don't do that anywhere else that I can think of, so why make an exception here?
> chatdeclare: combine two if statements into one

- commands.js
http://i.imgur.com/X0KehCO.png
This gives a point of reference, to know how the modlog's timestamps
translate to your own timezone.
> Display current server time in /modlog

- data/abilities.js
Clear Body, White Smoke and Mist (Move) already do this.
> Fix other abilities that prevent boosts

- commands.js
- rooms.js
Also, let's set modjoin to ``false`` by default like we do with modchat in rooms.js
> Modjoin: using no target shows current modjoin

- README.md
These commands now have the "global" prefix
> README: update promote commands

- chat-plugins/trivia.js
- test/chat-plugins/trivia.js
Part 1 of the rewrite for the entire plugin
This is the rewrite of the classes and commands that handle running
trivia games. Several bugs that happened when running trivia games were
fixed, and unit tests were added to help keep them gone.
> Trivia: game management code rewrite

- commands.js
#Zarel: we should have a /battle! command
#Zarel: complete with exclamation point
#Zarel: have it chastise you if you leave off the "!"
> Implement /battle! command

- commands.js
I guess I forgot to update a couple of lines from the pull request before it got merged.
> Fix bugs in stretching/caps commands

- chat-plugins/roomsettings.js
Fix a typo, and remove old required ranks.
> Roomsettings: Update help command

- dev-tools/users-utils.js
- test/application/users.js
- test/chat-plugins/trivia.js
Worker mocks now have proper ids. Trivia tests now dispose of user objects
rather than letting them stay in memory for the rest of the tests.
> Tests: tweak user mocks, add Connection tests, fix Trivia tests

- chat-plugins/trivia.js
- rooms.js
...even though the results are pretty entertaining for a couple of them.
> Commands: guard against constructor being the target in those that don't

- command-parser.js
Fix mistake from https://github.com/Zarel/Pokemon-Showdown/commit/bbe17f7316dd29b4d4e08d773cb85c54dbbfc76a
> Remove unused variable in checkFormat

- commands.js
The default is no longer 15, it was changed to 20.
> Modlog: Update help command

- data/items.js
Which is what the bug report seems to suggest should happen, so it's just a case of adapting the Mega Evolving changes from #2638 to Primal Reversion.
> Make Primal Evolution affect Illusion in the same way as Mega Evolving

- chat-plugins/trivia.js
- rooms.js
The writer functions held circular references to themselves due to their
finishWriting closure. Because the bug that required making an exception
for how files are written on Windows was fixed 4 years ago now (https://github.com/nodejs/node-v0.x-archive/commit/41f2725639dd10378cb0a5a57fe29157d7b926e9), it's perfectly safe to remove the closure and break the reference.
> Rooms: fix memory leak in safe file writer functions

- chat-plugins/wifi.js
- command-parser.js
- rooms.js
- test/main.js
- tournaments/index.js
This allows chat plugins (such as the wifi giveaway plugin) to modnote things, which was previously quite a large limitation.
> Move modlog writing to Room.prototype

- tournaments/index.js
- users.js
Sparked from https://github.com/Zarel/Pokemon-Showdown/commit/d105beeacdb719f7093b23dca2191bbd9016fe7b discussion.
> Simplify high load game number checks

- commands.js
> Bold rank headers in /auth

- chat-plugins/trivia.js
Drivers can no longer accept/reject questions, that now being the
responsibility of mods.
> Trivia: adjust question database command permissions

- test/chat-plugins/trivia.js
> Trivia: properly dispose of trivia games in mode unit tests

- commands.js
- https://github.com/Zarel/Pokemon-Showdown/pull/2620#discussion-diff-72349137R606
> Fix some unnecessary errorReply usage

- commands.js
> Allow users to use /roomauth in private rooms with modjoin with permission

- chat-plugins/trivia.js
- test/chat-plugins/trivia.js
Unit tests were still not destroying a few users.
> Trivia: modlog kicks and wins, clean up unit tests

- process-manager.js
This method would leak its arguments object before. The changes here saved
~30KB of memory from being leaked when running /itemsearch atk, for example.
> Fix memory leak in ProcessManager#prototype#send

- chat-plugins/roomsettings.js
I believe these few instances were left out from https://github.com/Zarel/Pokemon-Showdown/commit/505d68923b36b1fadb112f622bdca5a3a265d359
> Roomsettings: Standardize 'off' in UI

- chat-plugins/info.js
- commands.js
- punishments.js
- rooms.js
- users.js
Still WIP and extremely simple but this works. Please leave suggestions and comments.
> Add a blacklists feature for rooms

- chat-plugins/info.js
This won't happen again I now know GitHub auto squash witch is pretty neat.
> /htmlboxhelp: Update requirements

- .eslintrc
- app.js
- command-parser.js
- commands.js
I don't think this should have it's own global... Besides, this makes it hotpatchable with /hotpatch chat
> Make Messages submodule of CommandParser

- chat-plugins/roomsettings.js
BEFORE:
(well, that's what it looked like for me, at least.)
AFTER:
> Roomsettings: Use 'button' class in UI

- chat-plugins/roomsettings.js
The main reason I think this should be added is that a lot of people don't know this command, and so having it in the roomsettings should make it better-known to the relevant users that it's actually a thing.
> Roomsettings: Add enabling/disabling tournaments

- chat-plugins/roomsettings.js
This update timing kind of got messed up with the timing of using button class buttons in roomsettings.
> Roomsettings: Use button class for tour setting

- chat-plugins/poll.js
> Polls: add "button" class to the button

- chat-plugins/roomsettings.js
https://github.com/Zarel/Pokemon-Showdown/commit/b9e33af1c071b2620d517f1b917986107be15bd0#diff-97371680ff383ff965897845c2fb6bf3R113 didn't update all cases of the tour settings
> Roomsettings: Make tour settings consistent

- tournaments/index.js
This allows client in future update to display titles.
> Include room title in tournaments information

- package.json
This is the latest stable version of SockJS
> Update to newest SockJS

- team-validator.js
- users.js
To be used in a new tournament feature and potentially in challenges.
> Validator: support supplementary banlists

- team-validator.js
- tournaments/index.js
Tournament creators can now specify a supplementary banlist.
Also fixes a related validator bug.
> Tournaments: implement banlist feature

- battle-engine.js
- data/moves.js
Actually how it works in game: https://youtu.be/h8aB0f03-do?t=3m15s
Appears to solve everything #2790 points out related toEntrainment.
> Reveal old ability with Entrainment and Role Play

- chat-commands.js
[15:07] %Crestfall: is it possible to make /topic an alias for /roomintro for ROs without having it show the code every time?
[15:07] %Crestfall: bc i want a way to see my intro w/o having the code flood my chat
> Allow ROs to use /topic to not see source

- chat-plugins/info.js
Apparently, a lot of people still don't know this is a thing, so this might be a good way of making people know it's actually a thing.
> Add Dex repository to /opensource

- data/aliases.js
Requested http://prntscr.com/cpbmoo
> Add Zong -> Bronzong alias

- chat-commands.js
A lot of users have been asking for a userlists command, may it be for bot purposes or for battle room usage.
PREVIEW:
> Add userlist command

- battle-engine.js
- chat-plugins/jeopardy.js
- chat.js
- mods/gen2/rulesets.js
- process-manager.js
- punishments.js
- room-game.js
- simulator.js
- test/assert.js
- test/simulator/moves/ragepowder.js
- test/simulator/moves/roost.js
Replacing direct references to the arguments object of functions with rest
parametres prevents the function from being deoptimized while still allowing
use of arbitrary arguments. This may also fix some minor memory leaks related
to mishandling the arguments object.
> Performance: replace direct references to arguments with rest parametres

- chat-commands.js
Mirrors functionality of /topic for roomintros, requested in Dev room
> Allow mods to use /stafftopic to not see source

- chat-plugins/trivia.js
Now users can search for questions/submissions without having to rummage
through the entire list of questions. Trivia data and its writer are exported
once more so edits can be made to it with /eval if necessary.
> Trivia: implement /trivia search command

- chat-commands.js
By default, only global auth see links to the roomlogs in the modlog.
If Config.roomauthModlogLink is set, this commit extends that to roomauth from public rooms.
Also escaping "←" to \u2190. This character seems to break when committing with git on windows, and is replaced with "?".
> refactor /modlog to use template strings, and support roomlog links for public room auth

- punishments.js
- should use ``Punishments.saveRoomPunishments()`` instead of the global version at the end of the ``Punishments.roomUnblacklistAll``
- add an extra ignoreWrite argument to be passed to ``roomUnblacklist`` => ``roomUnpunish``.  That way, it doesn't try to write to the tsv file for each loop of the ``forEach`` called in ``roomUnblacklistAll``
> Punishments: Fix Punishments.roomUnblacklistAll

- config/formats.js
http://www.smogon.com/forums/threads/gifts-of-the-gods-omotm-october-eviolite-suspect.3579610/page-11#post-7041915
Eviolite is being suspected
> OMotM: Unban Eviolite

- team-validator.js
Adresses #2815 
I hereby license all my contributions to Pokémon Showdown, past and future, under the MIT license.
> Team Validation: Validate Natures

- chat-plugins/thestudio.js
> Studio: Add Song of the Day functionality

- test/application/team-validator.js
I think this is how to add tests? It might not be strictly necessary, but since there's tests for most other things this seems fitting to have as well.
> Tests: Update TeamValidator tests and add new ones

- chat-plugins/info.js
This makes it more streamlined to how `/whois` looks
> Checkpunishment: Don't use target id in UI

- chat-commands.js
Reported in http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/page-287#7164
> Fix broadcast help functions called from !help <cmd>

- punishments.js
- update confirmed => trusted with the users refactor
> Fix confirmed => trusted change

- chat-plugins/info.js
> add room rank and global rank on /groups

- config/config-example.js
- tournaments/index.js
These are used within the tournament code, but they aren't documented...
> Add undocumented tournament Config options

- chat-plugins/info.js
This is kind of a standard throughout PS commands - the help commands don't skip a new line from the command that they're the help command to.
> Update various help commands

- chat-plugins/roomsettings.js
This removes a lot of repeated HTML and also makes it more readable
> Roomsettings: Change way of generating button HTML

- chat-plugins/datasearch.js
- data/pokedex.js
This:
- Adds gen 7 to /dexsearch
- Fixes an issue with drampa not being capitalized.
> A few fixes

- data/moves.js
https://www.smogon.com/forums/posts/7080490
> Update terrain-sensitive moves for Psychic terrain

- data/abilities.js
> Add Emergency Exit and Wimp Out

- chat-plugins/roomsettings.js
These were just a few typos that messed up roomsettings a little bit.
> Roomsettings: Fix a couple of bugs

- data/abilities.js
- mods/gen6/abilities.js
Assuming https://www.smogon.com/forums/posts/7080164 turns out to be accurate.
> Tentative damage modifier changes on -ate and -ize abilities

- data/formats-data.js
Add an event for obtaining Zygarde 50% forme in gen 7.
[Video proof](https://www.youtube.com/watch?v=flv2Z41AMlQ) (Credit to fel for the video!)
> Add Zygrade event

- data/moves.js
That is, assuming the client should display the volatile at all...
> Throat Chop should set its volatile silently

- battle-engine.js
- data/moves.js
Pure Fire types become `???` type, while Moltres becomes Flying type, even if it roosts, although it is still grounded. Feel free to remove my comment. https://www.smogon.com/forums/posts/7083044
> Burn Up should change the user's type to ??? if it can

- data/formats-data.js
This fixes an issue mentioned in #2922 properly.
[proof](http://imgur.com/RjGMDhU) Credits to Fel (again) for the proof.
> Type: Null is event only

- chat-commands.js
http://prnt.sc/d9q0hs is what I'm trying to go for. I figured trying this since roombans uses the room title as well. Please tell me if this isn't needed thanks
> Using room title in /hidetext

- data/abilities.js
This was triggering some people apparently.
> Fix typo in prankster description

- chat-plugins/info.js
I think the way it was before kind of confusing, especially with the not rank part, hopefully this helps?
> Reword htmlbox help

- chat-plugins/roomsettings.js
minor syntaxic change "atuh" → "auth"
> Editing minor syntaxic typo

- data/aliases.js
Aliases for 10 abilities to begin with
> Add Ability Aliases

- battle-engine.js
- data/moves.js
- data/scripts.js
- data/statuses.js
This is the server-side part for the following messages:
- [PKNICK] surrounded itself with its Z-Power!
- [PKNICK] became the center of attention using its Z-Power!
- [PKNICK] boosted its critical-hit ratio using its Z-Power!
- [PKNICK] boosted its [STAT] using its Z-Power!
- [PKNICK] restored its HP using its Z-Power!
- [PKNICK] unleashes its full-force Z-Move!
> Add various Z-move messages (server part)

- config/formats.js
I have seen multiple requests for a custom game format with gen 7 mechanics, so I thought I would add one.
If were not ready for gen 7 custom game, feel free to close this / leave it.
> Add gen 7 custom game

- data/scripts.js
I forgot to `git add` my last change for PR #2947 so it's sending the wrong minor.
> Actually send correct -zpower minor

- chat-plugins/info.js
This will tell a user who the battle is against (if it's a battle room) by hovering over it, kind of like how user-popups work.
> Whois: Add hover room title to battle rooms

- chat-plugins/info.js
- chat.js
- punishments.js
- rooms.js
> Refactor /whois and /checkpunishment

- data/moves.js
https://www.smogon.com/forums/posts/7108602
> Defog should also remove Aurora Veil

- tournaments/index.js
This still requires a small client change, waiting with that until this is merged.
> Implement tournament bans

- chat-commands.js
I accidentally typed /ip as /pi, and I thought this would be a pretty humorous response.
Yay for meme commands!
> Add pi command

- chat-plugins/info.js
- chat.js
This renames 'limit' -> 'precision'.
> Rename unclear variable in Chat#toDurationString

- data/abilities.js
https://www.smogon.com/forums/posts/7111364/
> Stamina shouldn't trigger for self-confused damage

- team-validator.js
As reported here: https://www.smogon.com/forums/posts/7115032
> Sketch itself should count towards Necturna's single Sketch limit

- chat-plugins/info.js
It was checking the punishments of the user of the command, not necessarily the target user.
> Fix room punishment checking

- battle-engine.js
This is the server code for Zarel/Pokemon-Showdown-Client#828.
> Send residual upkeep message so that pseudo weather updates correctly

- data/formats-data.js
http://www.smogon.com/forums/threads/metagame-discussion-thread-cutiefly-is-banned-see-post-133.3587196/page-6#post-7131003
> Move Cutiefly to LC Uber

- chat-plugins/info.js
(and unbold ranks symbols like /auth
> Add /tour banlist in /roomhelp

- config/formats.js
http://www.smogon.com/forums/threads/sun-moon-uu-speculation-and-discussion-thread-see-post-85-for-uu-alpha.3587419/page-4#post-7126546
> Unban Zygarde-10% from [Gen 7] Pokebank UU (alpha)

- chat-plugins/trivia.js
The timeout for Trivia#askQuestion has the chance of ending after someone has
won the game or after forcing it to end.
> Trivia: fix race condition in Trivia#destroy

- chat-plugins/datasearch.js
This also hopefully makes /dexsearch a bit less messy: there's no more on-the-fly learnset modifiying and filtering through moves is not done in two locations anymore.
> Fix crash in /dexsearch

- data/scripts.js
- data/statuses.js
(Client-side changes to follow.)
> Z-Memento and Z-Parting Shot should not heal the replacement if they fail

- battle-engine.js
https://www.smogon.com/forums/posts/7141596
Note that eating an item already has this check.
> Fainted Pokemon shouldn't be able to use an item

- config/formats.js
Also makes any potential future Baton Pass ban easier.
> Simplify the PU format

- chat-commands.js
> Use gen 7 anything goes for default validation

- chat-commands.js
- chat-plugins/info.js
- chat.js
- punishments.js
- users.js
This is a work in progress, mostly want to know "amidoinitrite" and things I still need to implement and all that stuff.
> Implement /sharedip

- data/formats-data.js
- data/scripts.js
> Random Battle: Update Tapu Guardians, Araquanid, Vanilluxe

- config/formats.js
> Add Gen 7 tag to Pokebilities

- config/formats.js
- mods/pokebilities/scripts.js
- mods/pokebilities/statuses.js
@Spandamn thought it might be better than his code... take your pick.
> ROM's version of the Pokebilities code

- data/scripts.js
Affects Escavalier and Scizor.
> Random Battle: Reject Pursuit with Knock Off on non-Dark Pokemon

- test/application/sockets.js
These tests are just sanity checks for sockets.js' exported methods.
Tests for bugs will come later when those for related users.js methods
have been written.
> Implement sockets.js unit tests

- chat-plugins/datasearch.js
> Add Support for Z-Status Move Effects

- README.md
> Gens 1 through 7

- data/formats-data.js
- data/scripts.js
Also add the possibility of Z-Parting Shot.
> Random Battle: Update some Alolan Forme Pokemon

- data/scripts.js
With the Gale Wings nerf, it appreciates being able to use one additional
super-heavy priority attack before Brave Bird takes it below Gale Wings
range.
> Random Battle: Add possibility of Flyinium Z to Talonflame

- data/scripts.js
EV generation is incredibly lopsided in random doubles and should be more
balanced.
> Random Doubles: Switch to 84-all EV system like Random Singles

- data/scripts.js
Most ability checks are up to date with Random Singles, as are some of the
item checks.
> Random Doubles: Preliminary Overhaul

- chat-plugins/roomsettings.js
For some reason my builds are all failing because of these braces, but only on my fork? It might be because I have a newer version of Travis CI...
> Fix Brace alignment

- data/moves.js
Reporter double-checked this on the cart: https://www.smogon.com/forums/posts/7218890
> Counter and Mirror Coat should honour Z-powered special moves

- config/formats.js
> Update Almost Any Ability

- chat-plugins/info.js
(http://www.smogon.com/badge_faq)
> Add badge faq

- config/formats.js
I dont have add the banlist thread for doubles OU, lc and UU because there are no threads yet
> add some link in the /tier gen7

- app.js
- pokemon-showdown
Will be needed for dealing with Go's dependencies in the sockets.js
rewrite.
> Make the launch script compatible with Windows

- chat-commands.js
Since /help is PS' equivalent to `man` and I keep doing this by accident all the time
> Add /man alias for /help

- chat-commands.js
And also add a missing quote mark for one of the "Did you mean "/globalrank" type replies.
> Promote: String standards

- data/scripts.js
Are there any other Pokemon that would need similar treatment, like Zen Mode Darmanitan?
> Challenge Cup: Fix Wishiwashi's level

- mods/gen6/pokedex.js
> Gen 6: Keep old pokedex colors

- data/scripts.js
Was reminded to do this by #3246
> Random Doubles: Use Wishiwashi-School for calculating Wishiwashi level

- data/formats-data.js
Banning Victini and dropping down Staraptor as per this post: http://www.smogon.com/forums/threads/np-sumo-uu-stage-1-feels-like-we-only-go-backwards.3595341/page-2#post-7241566
> UU Changes

- chat-plugins/info.js
Switch the HTML to unicode so the é displays correctly
> Fix /caphelp

- data/scripts.js
Sheer Force only boosting one of its moves is rather mediocre compared to
Iron Fist boosting most of its moves, or Guts for even more raw power.
> Random Battle: Reject Sheer Force Conkeldurr

- test/simulator/moves/bellydrum.js
- test/simulator/moves/taunt.js
- test/simulator/moves/trick.js
- test/simulator/moves/zmove.js
Verifies behavior for some unchecked items in #2949.
> Add various Z-Status Move tests

- chat-commands.js
- chat-plugins/roomsettings.js
- config/config-example.js
- room-battle.js
There is a client-side counterpart to this.
> Change Player rank from ★ to ☆

- chat-plugins/info.js
Greninja and Ash-Greninja have separate dex pages now.
> info.js: add Ash-Greninja exception

- data/scripts.js
http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/page-334#post-7247567
> Battle Factory: Fix issue with sides having different tiered teams

- chat-commands.js
> Markshared: Return help command on no target

- config/formats.js
This is a worse hack, but it will prevent locked users from cheating by getting their nicknames suppressed.
I also wanna know: What would be the problems that this could possibly face? I've tested this and it works fine (But I dont yet know about any problems)
> Update Inheritance Hack

- data/scripts.js
Since we no longer use the PRNG the second time around, there's no point cloning it.
> Simplify the way the factory tier is chosen

- config/formats.js
[Pokemon's newest online competition](https://3ds.pokemon-gl.com/information/65b18aaf-bbe2-47fb-97c5-89034f8bd8d5)
> Add Kanto X Alola Regional Rumble

- config/formats.js
http://www.smogon.com/forums/threads/full-potential-om-of-the-month.3596777/page-3#post-7255135
> OMotM: Ban Dugtrio-Base

- mods/fullpotential/abilities.js
- mods/fullpotential/scripts.js
Prolly should've done this in my last PR, but I didnt have an idea of how that'd work.
@TheImmortal
> Unaware Should Also Ignore Speed Stat

- data/items.js
- mods/gen6/items.js
I think this enough proof: https://twitter.com/SerebiiNet/status/837595612887597056
> Release Mewtwonite X and Mewtwonite Y

- data/formats-data.js
It can learn the move in Gen 7.
> Random Battle: Add Head Smash to Sudowoodo

- chat-plugins/datasearch.js
Added generations to movesearch, similar to /ds (i.e. /ms gen3 works).
> Movesearch: Add Generations

- mods/gen6/statuses.js
Accidentally broken by @Marty-D in 7f96110.
> Gen 6 choicelock status needs inherit flag

- config/formats.js
http://www.smogon.com/forums/threads/full-potential-om-of-the-month.3596777/page-6#post-7264445
> OMotM: Ban Unburden and implement Item Clause

- config/formats.js
I'm assuming this is going to get a ladder, and not just be challenge only. Banlist from [here](http://www.smogon.com/forums/threads/usage-based-tier-updates-for-march-hello-ru.3598011/#post-7265548).
> Add Doubles UU

- chat-plugins/datasearch.js
> Add Weight as a parameter for dexsearch

- chat-plugins/othermetas.js
This is WORK IN PROGRESS.
I'm gonna add some more commands (/crossevo later) and maybe move /om to this file (later again)
> Add Other Metas Chatplugin

- chat-commands.js
> Commands: prevent unintentionally adding/removing aliases to the wrong room

- config/formats.js
Alolan Raichu and Speed-doubling abilities have been banned: http://www.smogon.com/forums/threads/full-potential-om-of-the-month.3596777/page-7#post-7273360
> Full Potential: Update banlist

- chat-commands.js
- ladders-matchmaker.js
- rooms.js
- test/application/ladders-matchmaker.js
- test/application/rooms.js
- test/application/simulator.js
- users.js
This abstracts matchmaking logic from the global room away to its own
module, allowing the two to be decoupled from each other entirely with
some refactoring.
Related to #3361
> Rooms: move matchmaking logic to ladders-matchmaker.js

- config/formats.js
- data/formats-data.js
http://www.smogon.com/forums/threads/sm-lc-vulpix-voting.3598711/page-3#post-7278691
> Ban Vulpix from LC

- chat-plugins/uno.js
- uses the room-game API
- should pass Travis (I swear I tested 3 times http://prntscr.com/ea22as)
- uses Fisher-Yates shuffle for the cards
- cards display will keep same dimensions and fit to most screen sizes.
(sample display of card selection screen http://prntscr.com/ea2114)
(fixed the main things talked about from one year ago in https://github.com/Zarel/Pokemon-Showdown/pull/2374)
> Create UNO game for PS

- config/formats.js
http://www.smogon.com/forums/threads/bh7-suspect-vote-2-innards-out.3598631/
> Ban Innards Out from BH

- chat-plugins/uno.js
If a user gets disqualified while it's in the "colour" state, then nothing switches back to the "play" state.
EDIT: Do note the Canadian spelling used in the comments ;)
> UNO: Fix being stuck in colour state

- chat-plugins/uno.js
> Add Join button to UNO declaration

- config/formats.js
- data/formats-data.js
Banning Alakazam and unbanning Mewnium Z: http://www.smogon.com/forums/threads/np-sumo-uu-stage-1-feels-like-we-only-go-backwards.3595341/page-8#post-7281023
> Changes to UU

- config/formats.js
http://www.smogon.com/forums/threads/mix-and-mega.3587740/page-19#post-7283760
> Remove Mix and Mega Suspect test

- chat-plugins/info.js
This is useful for several rooms on main.
> Implement /checkchallenges

- config/formats.js
Add searchable-only OU suspect test tier where Pheromosa is banned, and make regular OU challenge only.
> Formats: Add OU suspect test

- chat-plugins/othermetas.js
> Fix another error in /mixandmega's error checking

- config/formats.js
As per request of an OU Tier Leader
> Hide classic OU ladder from showing

- chat-plugins/uno.js
- forgot to check for changed colour with the last fix regarding references
> UNO: fix +4 verification

- data/aliases.js
- data/pokedex.js
+a mistake of mine in aliases.js
> Fix Pokestar cosmetic forms

- chat-plugins/scavengers.js
-Don't console.log if the file doesn't exist because it will later be automatically created
-There shouldn't be invalid JSON where this try catch statement is necessary, and if the JSON is bad, it should crash so that we know about it instead of silently failing to load
> Scavengers: Refactor ladder load function

- chat-plugins/scavengers.js
I may or may not have accidentally deleted too much when going through add applying escapeHTML to everything...  oops, sorry!
> Scavengers: fix /scavengerstatus

- chat-plugins/wifi.js
Seems like this is the only case that uses "his" throughout the entire codebase
> Wifi: GTS giveaway - use a gender neutral pronoun

- chat-plugins/datasearch.js
Brought up by user ``Eeveelution Army`` on PS
> Movesearch: Add `gen` into help entry

- users.js
(1) oops, forgot that battles were roomgames as well, so they needed to update for dc's (guest => player) and send the requests accordingly
(2) I'm so bad
> Users#mergeConnection - run room.game.onUpdateConneciton for battles

- data/formats-data.js
http://www.smogon.com/forums/threads/np-sm-ou-suspect-process-round-3-beauty-and-the-boost-pheromosa-is-now-banned.3599206/page-7#post-7306604
> OU: Ban Pheromosa

- data/formats-data.js
http://www.smogon.com/forums/threads/np-sumo-uu-stage-1-feels-like-we-only-go-backwards.3595341/page-9#post-7309750
> Unban Terrakion from UU

- config/formats.js
http://www.smogon.com/forums/threads/sm-dou-stage-2-suspect-voting.3600792/page-2#post-7311067
> Ban Kangaskhanite from Doubles OU

- data/formats-data.js
Removed Substitute, added Super Fang. This mostly puts it in line with its
XY standard sets.
> Random Battle: Update Walrein

- chat-plugins/scavengers.js
Fixes
-----
- space after comma to join the consolation prizes
- take the first element after splicing to correctly display the owner of the hunt in ``/scav dequeue``.
Additions/Changes
------------------
- make add ``/scav setblitz`` and ``/scav setpoints`` to allow RO's to change the points awarded during official hunts for events/monthly themes.
- require an extra field to specify the host/author to create/queue hunt
- Allow voiced and up to edit hunts that are created for them
- Allow all hunt authors to view their own hunts
- Both the staff host and the actual host of the hunt will not be able to join.
- reset hunts (and keep results secret) that are ended automatically by timer if there are no finishers so the hunt can be recycled
- make queue write to chatRoomData to keep the queue …
> Scavengers: Changes requested by scavenger staff

- config/formats.js
Now that we have more resources this should be updated
> Update Gen 7 BSS format description

- data/abilities.js
- data/scripts.js
Affects Linoone. Gluttony currently has a rating far too low to be chosen.
> Random Battle: Allow Belly Drum Gluttony

- pokemon-showdown
> Fix dependency installation on Windows

- chat-commands.js
- tac isn't installed by default on OS X and flavours of BSD, which would
cause /modlog to fail in certain cases, so awk is used instead for them
- running /modlog all or /modlog public with a number of lines to
return rather than a string to query with now replies with an error
instead of treating "all" or "public" as literal rooms and trying to
read their modlog files
> Commands: make /modlog compatible with OS X/BSD, fix silent error

- data/scripts.js
Reported [here](https://www.smogon.com/forums/posts/7332064).
> Moves with no PP can't be turned into Z-moves

- config/formats.js
OU is suspecting Metagrossite: http://www.smogon.com/forums/threads/np-sm-ou-suspect-process-round-4-the-robots.3602385/
> Add OU suspect test

- data/abilities.js
Perish Song doesn't do this automatically any more as of #3483. http://replay.pokemonshowdown.com/gen7customgame-567963603
> Fix Perish Song + Soundproof

- config/formats.js
> Fix Last Will Bug

- config/formats.js
Well, maybe not so much clearer as less... uh... suggestive. Really, this is so people don't have to ask what "get off" means.
> Change Last Will hint to be clearer

- config/formats.js
* Only alter stats once
* Fix Arceus/Silvally related crash
> Update Cross Evolution

- config/formats.js
Just stop trying to guess the target, the battle scripts are much better at doing it.
> Fix for Heal Bell as a Last Will

- config/formats.js
In case you are still having problems. Note that this still isn't exactly the same as ROM's code because
- ROM's code doesn't use template strings yet
- ROM's code hardcodes the banlists
- ROM's code has a slightly different move validator
- ROM has some extra code to handle its custom `!dt` command
> Transplant some of ROM's code for Cross Evolution

- config/formats.js
http://www.smogon.com/forums/threads/last-will-om-of-the-month.3601362/page-5#post-7340908
@TheImmortal
> Update Last Will

- chat-plugins/poll.js
- make all poll options align left
> Poll: Fix display

- room-battle.js
Each player has their own cooldown. The point is to prevent spamming timer on/off to timerstall indefinitely.
This is my attempt of a server-side approach to the same problem as https://github.com/Zarel/Pokemon-Showdown-Client/pull/910
Should I add a type annotation for the ``lastDisabled`` object? Like "Object<string, number>"?
> Add cooldown to re-enabling timer after disabling it

- chat-plugins/scavengers.js
- Add a new leaderboard for hunt creation.
- Add a new mode: practice
- refactor ``ScavengerGame#isOfficial`` to ``ScavengerGame#gameType`` to accomodate practice hunts
- Only users who can talk (not locked/muted in that room) will be able to join the scavenger hunt.
> Scavengers: add new mode, and statistic logging

- sim/dex.js
I was wondering why my `/dt oricorio-balie` was failing. It turns out that we don't search aliases, so it couldn't tell me that I had mistyped `Oricorio-Baile`.
In order to search aliases I changed the code to search the dex keys; hopefully this doesn't change anything significantly.
> Include aliases when searching the dex

- chat-plugins/info.js
> Add /damagecalc as alias of /calc

- chat-plugins/scavengers.js
- show the rank of the user (grayed out for globals) in the ladder for logs.
- limit certain commands to the scavenger room only.
> Scavengers: Display user rank, limit commands

- config/formats.js
Any opinions on what the error message can be changed to?
> Fix Last Will Crash(es)

- config/formats.js
- sim/dex.js
- team-validator.js
- test/common.js
- test/simulator/misc/random-teams.js
Finish renaming various variables that haven't been changed yet.
I skipped sim/* because it seemed like it would conflict with the Dex global.
> Finish renaming tools to dex

- tournaments/index.js
Client-side: https://github.com/Zarel/Pokemon-Showdown-Client/pull/896
> Tournaments: add /tour setname

- data/scripts.js
http://replay.pokemonshowdown.com/gen7challengecup1v1-580473544
> CC1v1: Smeargle cannot sketch Z-moves

- sim/dex.js
Affects things such as healing from ~grassyterrain~ Grassy Terrain.
> Move, Ability and Item effects should inherit the name

- data/rulesets.js
Even though it doesn't have -ate it does function like the rest
> Rulesets: Remove -ate clause

- chat-plugins/scavengers.js
- chat.js
- add /leavehunt
- add chat filter to prevent leeks
- make /scavenge automatically join the hunt if the user has not joined yet
- fix some awful grammar on my part
> Scavengers: Add leak block, fix grammar, autojoining, /leavehunt

- chat-plugins/scavengers.js
Remove logging from testing/debugging status
-embarrassing-
> Remove logging

- chat-commands.js
"/forcepromote [user], #" would promote someone to Global Room Owner otherwise. Works with Player as well
> /forcepromote: Prevent from promoting to Global Room Owner

- data/scripts.js
At the moment everything gets rolled as Male
> Fix Gender randomisation in Battle Factory

- config/formats.js
Baton Pass is now banned from SM OU as per http://www.smogon.com/forums/threads/baton-pass-in-sm-ou.3604290/page-2#post-7370590
> OU: Ban Baton Pass

- sim/battle.js
- sim/pokemon.js
By not calling the last will until after move recoil. Discussion in #3546.
> Fix Last Will crash

- chat-plugins/scavengers.js
- only bold non-auth in the top 5 of the leaderboard, rather than top 3 non-auth overall
> Scavengers: Update leaderboard formatting

- data/pokedex.js
Brattler's typing and ability slots should be consistent with Malaconda's.
> Fix Brattler's data

- config/formats.js
- mods/dancerability/abilities.js
- mods/dancerability/scripts.js
Hopefully the banlist for Godly Gift is correct; ROM doesn't have to worry about banning megas, let alone stones, that give banned abilities.
> Other Metagames of the Month June 2017

- chat-plugins/scavengers.js
- filter by IPs to avoid false positives
> Scavengers: improve multiple connection check

- chat-plugins/datasearch.js
Add height to dexsearch (so things like `/ds ht>5` work), also make `/ds all` not work.
> Dexsearch: Add height

- chat-plugins/scavengers.js
- match msgId to the ``toId()`` form of the answer.
> Scavengers: update leak guard

- chat-plugins/datasearch.js
When comparing a stat with an inequality (`<` or `>`), dexsearch currently changes it to `<=` or `>=` and adjusts the comparison value by 1. This happens to work for stats because they're only integers, but it's terrible for weight and height because they can easily be less than one and if you write `/ds weight < 1` you actually get `/ds weight <= 0` which is nonsensical.
This PR reverses the behaviour so that `<=` and `>=` are defined in terms of `<`, `=` and `>`, removing the need for adjustments.
> Dexsearch should use exact inequalities instead of fudging the comparison value

- config/formats.js
http://www.smogon.com/forums/threads/baton-pass-is-banned-from-sm-ubers.3605747/
> Ban Baton Pass from Ubers

- data/formats-data.js
http://www.smogon.com/forums/threads/usage-based-tier-updates-for-june.3606072/
> June tier updates

- mods/gen4/scripts.js
> Require minimum IVs for Hidden Power 70 in Gen 4

- chat.js
My bad missed a word in the commit description.
Feel free to close this if its planned to move this to chatfilter.
> Apply spam filter to the help room

- chat-plugins/modlog.js
This was not included in the recent modlog refactor
> Modlog: Add permission checking back

- config/formats.js
- data/formats-data.js
http://www.smogon.com/forums/threads/metagame-np-sm-nu-stage-0-beta-bring-the-noize-post-38-for-bans.3606077/page-2#post-7390115
> Update NU Banlist

- chat-plugins/info.js
- Don't send double errorReply for when trying to set a room's rules in PMs
- Allow a way to delete a room's rules link
> Enhance the rules command

- chat-plugins/datasearch.js
Works essentially the same way as /randpoke
> Add randmove command

- data/statuses.js
This is my first time working with actual battle code and writing a test, so if something is wrong let me know.
> Fix Unaware Confusion interaction

- chat-commands.js
- chat.js
Client pull request: Zarel/Pokemon-Showdown-Client#873
Check the client pull request for details on these changes.
---
Previous Pull Request was closed because I managed to screw up my repo, these are the same changes as before.
> Notify users when a declare is used

- chat-plugins/roomsettings.js
Also changed a comment to be slightly more informative.
> Roomsettings: don't show modjoin + button to everyone in groupchats

- chat-commands.js
- rooms.js
And also slightly change the behavior of Rooms.global.notifyRooms
> Hotpatch: Use Rooms.global.notifyRooms to notify

- chat-plugins/modlog.js
Also don't unnecessarily create RegExp objects if we're not using them anyway (which has the advantage of not automatically escaping all the forward slashes).
> Modlog: don't escape characters unnecessarily

- sockets.js
If the connections aren't destroyed when the worker is disconnected,
its process will not exit until the remaining connections have closed.
This cleans them up manually so using Sockets.killWorker or
Sockets.killPid does not force any users connected over that worker to
refresh twice in order to reconnect to the server.
This also makes workers respawn automatically after being killed, which
they weren't doing before.
> Sockets: make killing workers clean up connections properly

- chat-plugins/scavenger-games.js
- chat-plugins/scavengers.js
- chat.js
- add the remaining 3 scavenger games
- fix KO Games
- add multiple answers and hosts
- add /nexthunt
I swear I tested and double tested everything to the point where there shouldn't be crashes this time!
(Approval without any vetos from majority of RO's [as per room policy], as well as support from the room staff)
>(#pspl #beatuppesp #scavengers)
> Scavengers: add games, multiple hosts and answers

- config/config-example.js
- crashlogger.js
- package.json
- sockets.js
`nonDefaultDependencies` doesn't seem to be a standard package.json field
anymore. This version of `ofe` fixes a crash when attempting to build the
package on Windows.
npm v5 complains about `package-lock.json` not existing.
> Add Config.ofe, refactor optional dependency usage

- chat-plugins/scavenger-games.js
> Scavenger Games: Jump Start -  actually set wait to 1 minute

- chat-commands.js
- Allow /expiringblacklists to show the list of blacklists that are expiring within 3 months or less
- Add /nameblacklist as an alias to /blacklistname and document it
- Change /blacklist and /blacklistname modlog text to say "from room title" to mirror roombans modlog UI
> Some blacklist command changes

- config/config-example.js
- rooms.js
- users.js
- support side servers that have their own custom ranks
In tandem with https://github.com/Zarel/Pokemon-Showdown-Client/pull/918
> Rooms: send a |customgroups| message on connect

- mods/gen1/formats-data.js
Reverts #3592 (not a bug), and also I took the opportunity to tweak Beedrill's moveset.
> Gen 1 Randbats: Minor moveset updates

- chat-commands.js
I don't know what I was thinking with this line
> Fix lock/ban messages without a reason but proof

- chat-plugins/othermetas.js
The display would be like the one in /data.
> Update Other Metas Commands

- data/formats-data.js
http://www.smogon.com/forums/threads/np-sumo-uu-stage-2-countdown.3606088/page-4#post-7400433 Unban Weavile and ban Mega Houndoom from UU as per this post
> UU tier updates

- sim/dex-data.js
- sim/dex.js
Also document unbanlist and supplementaryBanlist
> Show correct rulesets in custom format battles

- chat-plugins/room-events.js
Depends on Zarel/Pokemon-Showdown-Client#950, but won't cause problems without it.
> Locale aware time in /roomevents

- data/learnsets.js
Reported [here](http://www.smogon.com/forums/posts/7401629/), and checked on veekun and serebii.
> Munchlax learns Superpower as a Tutor move in Gen 4

- chat-plugins/info.js
> Commands: fix /processes crash

- data/formats-data.js
- data/scripts.js
Armaldo is far too slow to utilize Swords Dance well, and only works on
dedicated Rain teams (which are very uncommon in Randoms).
Updated the item selection for when Substitute and Reversal are on the same set.
> Random Battle: Update Armaldo, A-Dugtrio

- chat-plugins/modlog.js
Since we're using a child process now, Rooms was no longer defined there.
> Fix crash in `/modlog public`

- room-battle.js
> Timer: use user.name and add period

- chat-plugins/othermetas.js
Add dragon ascent as a possible "Mega Stone", allowing pokemon to inherit Mega Rayquaza's properties (delta stream, its increased stats, etcetera). Also, at the request of Spandan, the banned stones check has been removed to let the command be less restrictive.
> Update OM plugin

- package.json
The change from v0.10.x -> v0.11.0 was in November of 2016, and a lot has chanced since then
> v0.11.0 -> v0.11.1

- chat-plugins/othermetas.js
After some discussion with Chloe and Zarel, this was decided as the solution.
> Update /mnm errors and add warnings

- config/formats.js
http://www.smogon.com/forums/threads/stabmons-om-of-the-month.3587949/page-11#post-7411684
> STABmons: Ban Komala

- chat-plugins/uno.js
should fix #3713, which i broke with an earlier change
> Uno: fix playing 2 +4s in a row

- users.js
This makes these two parts slightly more readable
> Slightly refactor user#getIdentity

- data/formats-data.js
- data/scripts.js
Swanna has no use for Surf if it has Scald, even in Rain sets.
Triage and Draining Kiss should always be together. Also, give Triage a rejection condition.
> Random Battle: Update Swanna and Comfey

- chat-plugins/modlog.js
> Modlog: crash log uncaught exceptions

- chat-plugins/scavengers.js
- make viewhunt gradually show the answers, and show the question number as well
- some formatting things for hunt results
> Scavengers: enhance hunt viewing/management

- process-manager.js
- tsconfig.json
- verifier.js
Some refactoring to ProcessManager was needed. Please review before
merging.
> Typescript: process-manager.js, verifier.js

- chat-plugins/datasearch.js
> datasearch, add is as an itemsearch alias

- config/formats.js
http://www.smogon.com/forums/threads/stabmons-om-of-the-month.3587949/page-14#post-7419968
> STABmons: Ban Kyurem-Black and Silvally-Ghost

- chat-plugins/datasearch.js
Since LC Uber isn't part of the LC banlist any more.
> LC search should only use the banlist, not the LC Uber tier

- chat-plugins/info.js
Crucibellite is apparently Gen 6 and abilities don't have details anyway.
> Show Gen as CAP instead of 0 in detail output

- mods/gen3/scripts.js
See @xfix 's comment here https://github.com/Zarel/Pokemon-Showdown/pull/3760
> Gen 3 Randbats: Limit to 1 Wobbuffet per battle

- config/formats.js
Remove Battle Spot Special Season 4 and add Battle Spot Special Season 5
> Update Battle Spot Special ruleset

- chat-plugins/info.js
(I notice that `snatch` is an allowed parameter to `/ms` but `mirror` isn't...)
> Simplify coding for links to Snatchable and Mirrorable moves

- mods/gen3/scripts.js
> Gen3 randbats: Fix crash with Wobbuffet

- mods/gen3/formats-data.js
Fixes bug seen here: http://replay.pokemonshowdown.com/gen3randombattle-602638461
> Gen 3 Randbats: Fix Swords Dance Typo

- mods/gen3/formats-data.js
- mods/gen3/scripts.js
- Tons of movepool updates
- Removed Quick Claw / Bright Powder & increased choice band chance
- Prevent (most) redundant moves
- Other fixes
> Gen 3 Randbats: Updates

- data/formats-data.js
- data/scripts.js
This involves adding Fly to some Flying Pokemon without a good Flying
STAB. (This also makes sure Fly is not their only STAB.)
> Random Battle: Add possibility for Fly-Z or Bounce-Z

- mods/gen4/formats-data.js
Mainly updating some Ubers to be less specialized for the DPP Uber metagame, along with a couple of other changes for random Pokemon I encountered with bad sets.
> Gen 4 Random Battle improvements

- mods/gen2/formats-data.js
- Fixes Delibird moveset
- Tweaks Quagsire moveset
- Tweaks Jumpluff moveset
> Gen 2 Random Battles: minor moveset fixes and tweaks

- punishments.js
Based on the discussion stemmed from https://github.com/Zarel/Pokemon-Showdown/commit/1a513ed585f755200d2777c2e45439672ce16223
> Punishments#search: Use let for dynamic array dec

- chat-plugins/modlog.js
This makes it clearer here that there is more popup elements than just |popup|
> Modlog: Use connection.send for sending popup

- data/abilities.js
I noticed this mentioned online in a couple of places so I [got confirmation](http://www.smogon.com/forums/posts/7433386).
> Shields Down blocks Yawn when active and ignores Mold Breaker

- config/formats.js
As per this post: https://www.smogon.com/forums/threads/3608900/#post-7435126
> Battle Spot Special 5 requires pentagon

- room-battle.js
Requested by staff to help with timerstalling reports.
Tested and works though i'm wondering why https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/js/battle.js#L6367 is not causing a double post.
> Timer: log messages to the chat

- data/scripts.js
- mods/gen3/scripts.js
See comment in https://github.com/Zarel/Pokemon-Showdown/commit/54f957875ee7f2e2c4a6fb3db9da2ef5c96f72af
----
Ability validation is now handled by the set generators.
> Dont use Dex in mods

- chat-plugins/scavengers.js
Approved by 2 - 3 ROs, agreed on by staff.
> Scavengers: fix/enhance queue, hunt ending, status box

- chat-plugins/room-events.js
Follow up to https://github.com/Zarel/Pokemon-Showdown/pull/3669
> Room-Events: edit option

- data/formats-data.js
Also gave Voodoom it's new move Flash Cannon, which gave it much more viability
> Make CAP LC CAPmons show as CAP LC

- chat-plugins/info.js
- chat-plugins/othermetas.js
... and make other metagame commands available in PMs.
Sorry if anythings fucked i am using my old laptop
> Move /othermetas to othermetas.js

- chat-plugins/modlog.js
When dealing with reports, especially when in single panel mode, this can be useful
> Modlog: Enable command in private messages

- users.js
This is used in several parts of the sim where commands carryout potentially dangerous actions.  For this reason, it should be apart of a user's constructor.
> Users: Add lastCommand to constructor

- config/formats.js
http://www.smogon.com/forums/threads/np-dou-stage-2-mama-said-knock-you-out-kangaskhanite-is-banned-swagger-is-banned.3599122/page-4#post-7443646
[10:50:27] &kamikaze: can someone put Swagger Clause in SM Doubles OU
[10:50:33] &kamikaze: http://www.smogon.com/forums/threads/np-dou-stage-2-mama-said-knock-you-out-kangaskhanite-is-banned.3599122/page-4#post-7443646
[10:50:43] &kamikaze: it would be very much appreciated
> Gen 7 Doubles OU: Add Swagger Clause

- room-battle.js
This prevents an exploit that allows automatically winning when opponent has disconnected by disabling timer when opponent disconnects and reenabling it when opponent joins battle again.
> Reset disconnect timer when joining even when timer is disabled

- data/random-teams.js
Copied over from the Random Singles code, minus the Stealth Rocks check.
> Random Doubles: Implement EV fixing for Belly Drum, etc.

- chat-plugins/uno.js
this lets the pass button work again, since previously it was inside a style because of a missing "
> uno- add missing quote, fix buttons

- config/formats.js
I changed the sample team and metagame discussion threads to their current versions.
> Update [Gen 7] UU Tier Threads

- config/formats.js
Reasoning here http://www.smogon.com/forums/threads/stabmons.3587949/page-19#post-7452442
> STABmons: Ban Tapu Koko

- team-validator.js
Reasoning http://www.smogon.com/forums/threads/stabmons.3587949/page-19#post-7452442
> STABmons: Ban Lovely Kiss

- config/formats.js
> BW2 Doubles should use Swagger Clause

- chat-plugins/modlog.js
* Don't show "More..." button if the amount of results is already less than the max
* Properly pass on whether an exact search was performed to the prettifying function
* Improve phrasing in reaction to whether an exact search was performed
* Allow "More..." button to do an exact search instead of always doing a username search
* Reorder some lines pertaining to the line count so they're not needlessly scattered all over the place
> Modlog: fix various small issues

- data/items.js
Reported [here](https://www.smogon.com/forums/posts7461349/).
> Weakness Policy should activate before Thief or Magician

- data/abilities.js
According to Bulbapedia, Receiver and Power of Alchemy cannot be traced either, but I haven't been able to test these yet on cart
> Update the list of abilities Trace cannot trace

- data/pokedex.js
Mentioned in help https://media.discordapp.net/attachments/327903881843572747/344503740276932609/Snapchat-893046342.jpg?width=243&height=431
> Correct Lurantis's pokedex color

- data/abilities.js
The shortdesc still fits the 480px limit, albeit barely.
> Add ignoring Aurora Veil to Infiltrator's description

- mods/gen6/moves.js
I fixed up some descriptions on moves that I saw where missing descriptions.
> Gen 6: Fix up a few descriptions

- data/formats-data.js
- data/items.js
- mods/gen6/items.js
https://twitter.com/serebiinet/status/895524354917662721 (Latest Serebii Update)
Defaulted the format to OU
> Diancite unbanned

- users.js
As suggested by Joim, this is simpler and more readable, and less lines!
> Simplify user.hasConsoleAccess

- data/aliases.js
I don't know why this isn't an alias yet so I added it.
> Add Mega Ampharos Alias

- chat-plugins/datasearch.js
Fix `/randmove` and, not allowing `/ds darktypeasd`
> Dexsearch: Fix types, and randmove

- config/formats.js
> Doubles UU: Ban Ampharosite & Altarianite

- data/aliases.js
Should this have the [Gen 7] prefix?
> Aliases: Add 'uber' as an alias to 'Ubers'

- chat-plugins/info.js
This will tell a staff if the server considers a user to be autoconfirmed or not.
> Whois: Display if a user is autoconfirmed

- mods/gen6/abilities.js
> Fix typo in Gen 6 Parental Bond

- data/formats-data.js
http://www.smogon.com/forums/threads/sm-uu-stage-3-voting.3613280/page-3#post-7488377
> Ban Xurkitree from UU

- chat-plugins/info.js
- config/formats.js
- data/rulesets.js
This command is intended to be a quick-access option for checking banlists and rulesets for formats as well as descriptions of the rules that would get listed in case the user has questions.
> Add command /viewbanlist

- data/random-teams.js
This is mostly for Celesteela and Guzzlord so that Beast Boost doesn't increase a useless stat.
> Randubs: Minimize unused attacking stats

- data/formats-data.js
http://www.smogon.com/forums/threads/pu-tiering.3611938/#post-7498984
> Medicham was quickbanned from PU

- chat-commands.js
This isn't particularly urgent, but yeah, this fixes a typo.
> PSPL Winner: Fix typo in command

- sim/side.js
Mainly for Imposter/Transform. This is the server-side part of the fix.
> Reveal own Ability in Gen 7

- chat-plugins/trivia.js
So that things likr
don't happen again....
> Trivia: Fix error messages

- data/random-teams.js
- Reject Close Combat and High Jump Kick on all sets with special setup
- If both options for the ability would be rejected, default to the better one instead of the worse one
- Don't give Focus Sash to things with Leech Seed or with setup that doesn't boost speed (unless they have priority)
- Don't let Zygarde-10% with sub have leftovers
> Update Random Battle

- chat-plugins/info.js
https://github.com/Zarel/Pokemon-Showdown/pull/3914#pullrequestreview-61672679
> /formathelp: Fix near matches

- data/formats-data.js
Also, Power Gem as an additional attack option even though it isn't too common.
> Random Battle: Update Necrozma to its usage stats

- config/formats.js
http://www.smogon.com/forums/threads/core-metagames-policy.3615101/
@TheImmortal
> Monotype is now an official tier

- chat-plugins/trivia.js
> Trivia: Only voices can submit in QW

- config/formats.js
http://www.smogon.com/forums/threads/sm-ou-suspect-process-round-5-voting.3615232/page-5#post-7513063
@theimmortal
> Arena Trap was banned from OU

- mods/gen4/random-teams.js
* Ensure that Relicanth always gets Head Smash
* Ensure that Water Spout Wailord gets Specs/Scarf instead of LO, even with Self-Destruct
* Ensure that Body Slam Jirachi and Dunsparce don't get Band/Scarf
* Default to Leftovers instead of Life Orb on sets with Super Fang
> Gen 4 Random Battle: Minor updates

- data/aliases.js
OU Theorymon is no longer a format
> Aliases: Remove OU Theorymon

- data/moves.js
- mods/gen4/moves.js
- mods/gen6/moves.js
This is the Move version of PR #3905. The moves changed are Beat Up, Fell Stinger, Fling, Natural Gift, Relic Song and Triple Kick. Other moves still need to use volatiles for various reasons, but these don't misbehave with Instruct (or, as in the case of Me First, cannot conflict).
> Remove some move effects to improve compatibility with Instruct

- chat-plugins/modlog.js
Prevents crashes in the modlog child process when PS is configured not
to use ripgrep.
Specifically, this happens because [compiling a regex expression](https://github.com/v8/v8/blob/f2bd913cd459854894447f5422a953d23fa4e7ba/src/regexp/jsregexp.cc#L1138) with length greater than [a hard-coded cap in v8](https://github.com/v8/v8/blob/f2bd913cd459854894447f5422a953d23fa4e7ba/src/regexp/regexp-macro-assembler.h#L30) will throw, but not cause an `uncaughtException` event to be emitted.
> Modlog: cap search queries at 2500 characters

- chat-plugins/roomsettings.js
> Room Settings: fix potential RegExp crashes in banword checking

- data/abilities.js
- data/scripts.js
- test/simulator/abilities/dancer.js
I only added these particular tests so that I could make sure this code worked without having to run a server and do a mock battle 30 times, so if you want me to add more or remove any of them, I can.
P.S. I don't think anyone's checked whether or not Dancer has the same glitch as Trick Room with Pokemon over 1809 (1808?) speed.
> Fix Dancer order & add some Dancer tests

- punishments.js
same mistake as the one spotted in rooms.js
> Fix crash in getRoomPunishments

- chat-plugins/health-fitness.js
> Implement plugin for Health and Fitness room
