data/scripts.js

Reduce all speed IVs by 30 to the lowest possible values that conserve the
typing of Hidden Power (since it's based on odd vs even)

Fix Hidden Powers on Terminator Scenario

---

commands.js

Fix possible crash by checking that roomauth exists in a secret room
with modjoin on before checking if the target user has permission to
join. This also fixes a really, really stupid logic error in the last
commit that makes it impossible for anyone that can't bypassall to get
invited anywhere.

Fix logic error in private room check for /invite

---

config/formats.js

(why it's there, I don't know, it's not that any other doubles format has Sleep Clause Mod, and Dark Void cannot be generated for Random Doubles anyway)

Remove Sleep Clause from Random Doubles/Triples

---

data/formats-data.js

- Nasty Plot over Calm Mind
- Psyshock over Psychic in Singles
- Give Hoopa Unbound some Physical moves
- Hoopa Unbound has Dark Pulse over Shadow Ball because STAB
- Volcanion had no random battle sets originally

Modified Hoopa and Volcanion's random battle sets

---

data/moves.js

Sky Drop needs to occur before Stance Change and just about every other
ability, move, status, or volatile effect. Since Stance Change was
recently upgraded to BeforeMovePriority of 11, Sky Drop needs to be moved
up to 12.

Fix Sky Drop's BeforeMovePriority

---

data/formats-data.js
data/scripts.js

Except for no-costume ~~and PhD~~ , since Cosplay Pikachu's movepool has no
advantages over regular Pikachus bar the special move.

Add Cosplay Pikachu's Random Battle movepool

---

data/scripts.js

- Allow tiered NFE Pokemon
- Gourgeist formes have equal chance
- Pikachu formes have equal chance
Basically does the same as 23c830562a4754f18ee4eab4cd3068597d2f9c8e but for double battles.

Tweak Double Random Battles to include the same things as Random Battle

---

data/formats-data.js

Uses the approved changes in #1413:
- Remove Grassy Terrain from Serperior
- Give Dragon Pulse to Serperior
- Give Flash Cannon to Aegislash

Tweak Double Random Battle Movesets

---

package.json

The old version of gulp-replace began to cause build errors due to one
of the dependencies (istextorbinary), which was fixed in this newest
release

Update gulp-replace to 0.5.1

---

commands.js

Users who already have the roomauth required to join the room probably
shouldn't also need bypassall privileges to be able to be invited to it.

/invite: fix dumb error in private room auth check

---

mods/gen3/abilities.js

onStartAbilities tries to fix a bug later fixed in 065e293, but only
serves to prevent said abilities from being traced while still sending
messages that one was traced on each update.

Gen 3: fix Trace Intimidate bug

---

chat-plugins/trivia.js

Create new Trivia instances on signups, delete them on game end, and
keep a reference to them in their constructor so that ongoing games are
no longer considered "dead" during garbage collection now that they have
a reference to them in a "live" object.
Also make the question timeouts less overcomplicated, now that I know the broken looping wasn't caused by them.

Trivia plugin: instantiate Trivia for each game

---

data/abilities.js
data/moves.js
mods/gen4/abilities.js

~~Hidden Power is unaffected by Normalize.~~
~~Also a researcher should check if it's the case with Judgment and Techno Blast.~~
Fixed ability interactions with Hidden Power, Judgment, and other moves
that change their types.
Normalize > move's type change > -ate Ability > Ion Deluge/Electrify
For Gen 4, the order is: move's type change > Normalize

Fix Ability Activation Order for type changes

---

data/scripts.js

- Acrobatics Pokemon get ~~the same items as Unburden mons.~~ no item.
- Hawlucha no longer has Sky Attack in its random battle movepool, so we
remove references to that in the code.

Change items involved when a Pokemon has Acrobatics or Unburden

---

data/scripts.js

- Dedenne gets Petaya Berry, since it always has Cheek Pouch
- Dusclops no longer gets Eviolite, because it's covered elsewhere in code
I kinda want to introduce slightly more complicated Eviolite checks, since Scyther doesn't really like having Eviolite and would prefer an attacking item usually...

Random Battle Item Changes

---

data/scripts.js

- Serene Grace is automatically rejected for Chansey and Blissey, who
prefer Natural Cure.
- Serene Grace works best with secondaries that have a high chance of
activating, so a seperate counter is used to check those specifically.
- Sheer Force doesn't need a secondaries chance check; both branches of
the check would have allowed Sheer Force to be used.
Based on the hard-coded check, let's guess what caused Ascriptmaster to want this change! (Hint: Natural Cure is in the same ability priority bracket as Serene Grace for random battles, but neither deserves a demote in priority either)

Split the Randoms check for Sheer Force and Serene Grace

---

mods/gennext/README.md
mods/gennext/moves.js

~~Uses the same logic as Thousand Arrows - if Marowak somehow gets
Normalize (via Skill Swap) it shouldn't be able to hit Ghosts with
Bonemarang.~~
Bone Club is the last, forgotten Bone attack, so we let it ignore immunities
like Bonemerang and Bone Rush do.
Updated the README to have these changes.

NEXT: Bone Club ignores immunities

---

mods/gennext/abilities.js

The NEXT Readme says that Shadow Tag only lasts one turn, and this is
solved by applying a volatile to the Pokemon with Shadow Tag and removing
it when it attacks for the first time after switching in.
However, if the Pokemon with Shadow Tag is flinched, frozen, put to sleep,
or paralyzed, the effect of Shadow Tag will continue to later turns!
This is solved by giving Shadow Tag's BeforeMove event a higher priority
so that it can remove the volatile before flinching.

NEXT: Shadow Tag bug fix

---

data/formats-data.js

Added a lot of moves available to Pokemon in ORAS but for some reason
weren't added to their random battle movesets.
(( Why did I add moves to the pre-evos as well? Why not? Also, Seasonals. ))

Random Battle Moveset Additions

---

data/scripts.js

I'm not sure if these particular set generation policies are a good idea.
Maybe instead, remove the priority move if the Pokemon has Rock Polish/Agility, and not the other way around?

Random Battle: Priority vs. Choice Scarf and speed boosting moves

---

data/rulesets.js

Closes #1445
In addition to the issues described in #1445 that make its alternate silent implementation via <code>team-validator.js</code> buggy/sub-optimal, such an implementation would be weird, as the fallback name in case of duplication wouldn't be clear were Species Clause inactive.
Therefore, we tell the user that their team is invalid.
Note that, in order to prevent battle log clutter, Nickname Clause's being active isn't revealed in the battle log.

Ban Pokémon sharing nickname under Nickname Clause

---

data/moves.js

When Leech Seed targets an ally in Double Battles, it should heal the
Pokemon at the ally's position, not an enemy.

Fix Leech Seed on Allies

---

battle-engine.js
config/formats.js
data/rulesets.js
mods/gen1/rulesets.js
mods/gen2/rulesets.js

- Send `noCancel` property in the battle request object.
- Support for retraction of decision is now handled by the "Cancel Mod" ruleset. It's regarded as a mod as it provides the ability to profile the response times of the opponent and use this information -unavailable in-cartridge- as additional data for further decisions.
- Fixes https://github.com/Zarel/Pokemon-Showdown-Client/issues/316

Support disabling cancel and tell the client when cancelling is impossible

---

mods/gennext/README.md

Aegislash is already banned from OU, so there is no need to mention its
banning as one of the "differences from OU".

NEXT: Remove mention of Aegislash on NEXT banlist

---

data/scripts.js

Stone Edge somehow was a case three times in the switch statement, meaning
only the first one would have been checked. This fix merges the three
checks into one.

Random Doubles Battle: Fix Stone Edge Redundancy Check

---

battle-engine.js
data/moves.js
data/scripts.js

- Rename randbats helper function `canMegaEvo` to `hasMegaEvo`.
- Move duplicate mega evolution possibility checks from `runMegaEvo` and BattlePokemon constructor to `canMegaEvo` battle script.

Pokémon cannot megaevolve to themselves

---

data/scripts.js

Added a counter that tracks Normal damaging moves for purposes of -ate
Abilities, in case it becomes important later. This counter also
future-proofs Aurorus in case it receives other viable Normal attacks
later.

Random Battle: Reject Aurorus Snow Warning with Hyper Voice

---

package.json

The old version caused build errors due to one
of the dependencies (rcloader), which was fixed in this newest
release

Update gulp-jshint to 1.9.2

---

battle-engine.js
data/abilities.js
data/scripts.js

Unaware currently doesn't work because the ModifyMove event is fired on the move before each target is caculated in doubles and triples.
This means that the ModifyMove event should be fired for each target and the move not modified unless it fits the attacker-target.
It's easier and less expensive to use an ability property to check on attacker/target than to fire events.
This fixes Unaware in doubles/triples.

Fix Unaware in Doubles and refactor stat ignoring abilities

---

mods/gen1/formats-data.js

This fix makes Voltorb viable for selection for Gen 1 RandBats... for the one person that wanted it.

Gen 1: Fix typo in formats-data.js

---

config/formats.js
data/scripts.js

Mechanics Changes:
- Fire Rocket does less damage, cannot crit.
- Fire Rocket is no longer a bullet move (for Chesnaught)
- Only Li Shang can Train Recruits.
- Recruits start with lowered defenses as well.
- Edit Mushu's movepool.
Flavor Changes:
- Train Recruits now uses Bulk Up's animation.
- Fire Rocket now uses Eruption's animation. Backfires cause the animation
to strike the user instead!
- Use Searing Shot as Fire Rocket instead of Octazooka.

Seasonal: Nerf Han Chinese Side, Flavor Changes

---

data/abilities.js
mods/gen4/abilities.js

Moved Anger Point's check for critical from onCritical to onAfterDamage.
This not only allows it to avoid being suppressed by Mold Breaker, it
also results in the Anger Point message being displayed in the correct
order with respect to the other messages.

Fix Anger Point's Interaction with Mold Breaker

---

data/scripts.js

With the way the Han Chinese side's morale system works, Baton Pass is
broken at high morale.

Seasonal: Remove Baton Pass

---

data/formats-data.js
data/scripts.js

- Remove Feint from Pikachu/Raichu
- Replace Rock Blast with Rock Slide on Golem line
- Add Surf to Octillery
- Reject Strong Jaw without bite moves
- Update Iron Fist check to use the punch flag
- Give preference to Rock Slide over Head Smash
- Give preference to Discharge over Thunderbolt and Electroweb

Random Doubles Battle Update

---

data/scripts.js

- In accepting Shadow Ball + HP Fighting, ensure that it's HP Fighting
(relevant for Reuniclus, Chandelure, and Sylveon, which have Hidden
Power that aren't Fighting)
- If Hidden Power changes the IVs but is later removed by another
processing cycle, reset the IVs to 31 all

Random Battle: Improve Hidden Power checks

---

battle-engine.js
data/abilities.js
data/moves.js
data/statuses.js

Moved all checks for primal weather into setWeather() instead of
hard-coding the check into every effect attempting to change the weather.
Also to prevent hardcoding, the check now runs on the event system, and
the primal weathers themselves deny regular weathers from being set.

Weather Refactor: Regular weathers don't activate w/ Primal Weather set

---

data/formats-data.js
data/scripts.js

- Lumineon and Poliwrath have Storm Drain and Water Absorb respectively,
which is always chosen over Swift Swim, so Rain Dance is unneccessary.
- Give Pokemon with Endeavor a Focus Sash.
- Give Unburden mons with stat-lowering moves a White Herb (specifically
targets Unburden Sceptile)

Random Battle Updates

---

data/moves.js

Redirecting targets and multi-hit moves were giving incorrect behavior.

Fix Lock On and Telekinesis in Doubles

---

data/scripts.js

Super Luck + Scope Lens gives a 50% chance of crit, but isn't a very high
priority since a consistent damage boost from a Choice item can be a
better pick.

Random Battle: Add Scope Lens to Super Luck Pokemon (low-priority)

---

data/formats-data.js
data/scripts.js

- Force Super Luck on Unfezant (it has a 33% chance of getting Big Pecks)
- Force Scope Lens on Unfezants with enough attacking moves
- Give Unfezant Night Slash
- Replace Wish with Roost in Doubles
Reasons for changes (not included in the commit message):
- Super Luck is Unfezant's only decent ability, and Scope Lens is found on nearly 50% of Unfezants.
- Night Slash has 100% crit, and is seen on 68% of Unfezants in PU.
Maybe I should just remove Roost entirely from the Doubles set

Random Battle: Update Unfezant

---

data/moves.js

This will let me change Sky Drop's animation properly back to a flight-style animation when I introduce the next graphics patch.

(Minor) Add a [still] tag to Sky Drop's preparation turn

---

data/abilities.js

It gives a 30% boost, not 33%.

Fix Tough Claws

---

data/formats-data.js
data/scripts.js

Mostly Gen 1-2 Pokemon were changed.
Added Moonblast where the usage stats were indicating that it was as
commonly used than Dazzling Gleam in Doubles. Reject Moonblast with
Dazzling Gleam.
Reject Return with Double Hit, Acid Spray with Sludge Bomb, Power Split
with Guard Split.
Give Scope Lens to Pokemon with Focus Energy.
Aeroblast is now considered STAB.

Random Doubles Battle: Update Movesets

---

mods/gen2/scripts.js
test/simulator/items/leftovers.js

(the description was here, but was incorrect, in any case, residuals occur after faint switch in Gen2)

Leftovers heal after switching in in Gen2

---

data/scripts.js

- Reject Trick/Switcheroo with Acrobatics so that the Pokemon can properly
receive Flying Gem
- Reject Rapid Spin with setup
- Do not reject Knock Off with setup
As usual, introducing these changes because I'm salty about a randbats game.
Specifically, it was one where I received Acrobatics+Switcheroo Ambipom, and
Rapid Spin+Shell Smash Cloyster.

Random Battles: Move rejection updates

---

README.md
app.js

This doesn't pull dev dependencies, not forcing people to install git in order to install `gulp-jshint`.

Use --production flag for npm installation

---

data/scripts.js

Affects Hitmontop, since if its only Technician move is Rapid Spin it'd
much rather prefer Intimidate as an ability.

Random Battle: Don't count Rapid Spin as a Technician move

---

data/formats-data.js

Use Sludge Bomb over Sludge Wave since Sludge Wave hits allies.
Use Precipice Blades instead of Earthquake because it only hits foes.

Random Double Battle: Update Groudon, Volcanion, Seviper

---

data/scripts.js

Just like the recent change to make Protean count all moves as STAB, do
the same with -ate abilities and Normal moves.
Manually include Nature Power as a damaging move since it becomes Tri
Attack. Its placement lets it automatically increment the -ate counter as
well.

Random Battle: Count Normal moves as STAB for all -ate mons

---

commands.js
config/commands.js

/inv so that people don't need to do /invite
/weaknesses because some people are proper and like to use plural pronunciations for Pokemon (eg. "/weaknesses mamoswine").
It's a small commit, but it'd still be useful in some instances

Add aliases for /weakness and /invite

---

chat-plugins/wifi.js

Users weren't able to guess more than once in a question giveaway because their current name was in their list of previous names.
http://prntscr.com/6c5r4p
Added a line of code to fix that problem. Thanks to Cranham (and maybe a few others too) for pointing this out originally, btw.

Fixed problems with guessing in question giveaways.

---

package.json

In newest version of npm, this makes depreciation warnings.
See npm/npm#7171 for justification of removal of this feature from npm.

Disable deprecated engineStrict

---

data/scripts.js

8c62c585109182d192096e21c28f34b5daf2de68's check to not reject Rest and Sleep Talk with setup is pointless if the setup move itself is rejected.

Random Battle: Do not reject setup with Rest+Sleep Talk

---

data/formats-data.js
data/scripts.js

- Accept Baton Pass with Wish and Pokemon with Speed Boost.
- Removed Baton Pass from Glaceon in favor if Wish and Protect.
- Removed Agility from Emolga since it doesn't need it; added Encore.

Random Battle: Update Baton Pass conditions, modify movesets

---

data/scripts.js

Multiple Baton Pass users are banned in OU and thus should be limited in random team generation as well.

Prevent multiple Baton Passers in random team

---

data/scripts.js

Added a new variable hasAbility that keeps track of all available
abilities on a Pokemon, reducing the verbosity of ability checks
within the move rejection stage of the algorithm.
Also, do not reject Leaf Storm if the Pokemon has Contrary, and
change the Solarbeam check to look for Drought directly.

Random Battle: Improve readability of ability checks

---

data/scripts.js

Mostly affects Rotom formes.
Because seriously, who wants to be stuck with Trick / Wisp / Pain Split / Thunderbolt against like a Mega Evolution that doesn't get affected by Trick

Random Battle: Enforce two damaging moves with Trick/Switcheroo

---

chat-plugins/wifi.js

Well, ``lotto`` is an alias for ``lottery``, which is a wifi command, so it makes sense that ``join`` and ``leave`` have ``joinlotto`` and ``leavelotto`` as aliases in addition to ``joinlottery`` and ``leavelottery``.

Add aliases for wifi

---

data/formats-data.js
data/scripts.js

- Removed it from Pokemon that are too weak to use it.
- Reject Feint with Fake Out (for Persian).
- Update move checking to not count single hit moves with 30 base power as
damaging moves.

Random Double Battle: Update Feint usage on Pokemon

---

config/formats.js
data/abilities.js
data/moves.js

The 'EndAbility' event was initially introduced for the implementation of
new weathers in ORAS, like Desolate Land, but has since been depreciated
in favor of an 'End' singleEvent.

Remove depreciated EndAbility event

---

config/formats.js

`pokemon.name` is `'+Cathy'` and not `'cathy'`. So, search table for key `toId(pokemon.name)`

seasonal: properly check for custom renamed moves

---

config/formats.js

HYDRO IMPACT was listed as ``@HYDROIMPACT`` on his Pok&eacute;mon's nickname and whenever he spoke, when it should have been ``@HYDRO IMPACT`` because he has a space in his name.
LegitimateUsername's Shuckle was still nicknamed ``@Legitimate Username``, when it should have been ``@LegitimateUsername`` because he has no spaces in his name.

Seasonal: Fix spacing errors

---

mods/gen3/abilities.js
mods/gen4/abilities.js

They don't provide immunity or boosts in these Generations.

Generation 3-4: Fix Lightning Rod/Storm Drain

---

data/scripts.js

This will prevent Pokemon like Azumarill from being too powerful due to
their low base stats with an ability that boosts it to incredible levels.
Open for discussion: Do we need to scale for these items/abilities:
- Sheer Force
- -ate abilities
- Expert Belt
Please discuss a lot before merging!

Random Double Battle: Update level scales based on item/ability

---

mods/gen3/abilities.js
mods/gen4/abilities.js

Accidentally removed Gen 3's implementation, so it is reverted.
Set Gen 4 to inherit the redirection from Gen 5+.

Generation 3-4: Actually fix Lightning Rod/Storm Drain

---

battle-engine.js
data/scripts.js
mods/gen4/abilities.js
test/simulator/abilities/simple.js

In Generation 4, Simple did not double stat boosts as they changed.
Instead, it treated each stat boost as if it had twice the effect.
Reimplemented the deprecated ModifyBoost event, but with slightly
different functionality as before; it now modifies the live boosts so that
they work properly with Simple.

Generation 4: Fix Simple

---

config/formats.js

It does not need to be called at every ModifyPokemon instance.
(Just copied over code from the Rayquaza Mega Ban Mod)

Streamline Mega disabling in OU (no Mega)

---

data/formats-data.js

The Double Battle EV generator is different from that for Singles, and
makes it less beneficial to have mixed moves.
(Maybe it should keep Ice Beam and remove Hydro Pump instead)

Random Double Battle: Update Sharpedo

---

command-parser.js

`Room#add` and `GlobalRoom#add` only receive one argument.

remove unused argument in Room#add calls

---

mods/hiddentype/moves.js
mods/hiddentype/scripts.js

- Transform and Reflect Type will replace it by the source hidden type.
- Adds a flag `isCustom` to the type data.

Hidden Type: custom type can no longer be copied

---

data/abilities.js

Added onEnd event to Flash Fire (and Unburden) to check for when the
ability disappears.
Verified by @Marty-D, but should probably wait for his double-checking again

Flash Fire boost disappears when the ability is removed

---

battle-engine.js
data/abilities.js
data/items.js
data/moves.js
test/simulator/misc/weight.js

Added a new event, `ModifyWeight`, to deal with weight changes from items,
abilities, and moves. Add a function `getWeight` to call the event and
return a Pokemon's current weight.

Weight Refactor: Do not modify weight in ModifyPokemon

---

data/moves.js

Fixes behavior with Flash Fire/Unburden with Skill Swap.
@Marty-D

Skill Swap sends End events even if it's the same ability

---

data/rulesets.js

Anything Goes allows anything that is obtainable in-game, and only one
Kyurem-Black or Kyurem-White can exist on a game cartridge at a time.
This is a change I brought up ages ago but forgot to actually fix properly
until now, haha

Prevent multiple Kyurem-Black and Kyurem-White on AG teams

---

config/formats.js

Prevents battle from crashing when he is forced out by chaos, Blitzarmin,
or Astyanax, and then gets a residual move like Wish off the Metronome
effect while inactive.

Seasonals: Abort Super Glitch if xfix is forced out with Red Card

---

data/formats-data.js
data/scripts.js

With the EV generation policy in place for Doubles, it is detrimental
for Pokemon to run mixed sets, so some physical moves were removed
from Charizard and Dewgong.
Added Double-Edge to standard Pidgeot to give it extra damage output.
Removed RestTalk from Gyarados. (Discuss)

Random Battle: Update some sets

---

config/commands.js

Search based on the least costly parameter first to remove pokemon that doesn't match as early as possible, so the moves/recovery sections have less searching to do. Single parameter searches remains largely the same though.
I saw, at best, a 20% improvement when I used a search meant to be better on this one. Average improvements got anything from 0 to 10%, depending on how many different parameters were added. (This was using a pretty old computer as host, so these numbers might be much smaller)

Improve /dexsearch performance

---

config/commands.js

Like /dexsearch except for moves; returns a list of all of all moves that match the parameters given to it.
Following parameters exist:
- move typing; i.e. /ms normal type, fire type
- move category; i.e. /ms physical, status, special
- move flags; currently excludes flags whose names don't clearly explain what they are; i.e. /ms bullet, pulse
- moves which restore hp; includes draining moves; i.e. /ms recovery
- shorthand for priority; positive or negative priority; i.e. /ms priority +
- moves which inflict status; i.e. /ms burns
- moves which inflict volatile status; i.e. /ms flinch
- inequality ranges for numeric properties of moves; inequalities behave with equal-to-or quality; i.e. bp > 100
- moves which boost status; i.e. /ms boosts attack

Add /movesearch

---

data/scripts.js

If Ambipom doesn't have any Technician moves, give it Pickup instead of
Skill Link because Skill Link is useless on it and it might as well have
a slight chance of recovering an item if its item is lost because of Knock Off.
(I was considering having Acrobatics not count as a Technician move since
it's almost always a 110 BP move, but then I remembered that if it's Tricked
a Choice item or something then it'll drop back down to 55 BP and qualify
for the ability. Also, Pickup would mess Acrobatics up.)

Random Battle: Update Ambipom

---

data/scripts.js

Fixes the Bide crash, although Bide maybe should also have the flags object in its moveData when it unleashes.

Make sure the flags object always exists in moveData

---

data/scripts.js

ModifyBoost events called for accuracy and evasion were sending the wrong
object as the relay variable.
Fixes the Gen 4 Simple crash.

Fix ModifyBoost crashes

---

mods/stadium/moves.js

http://datacrystal.romhacking.net/wiki/Pokémon_Stadium:ROM_map#Acid.2C_Aurora_Beam.2C_Bubble.2C_Bubblebeam.2C_Psychic
Acid, Aurora Beam, Bubble and Bubblebeam have a 33.2% chance to lower the target's stat one level. My apologies for the previous commit.

Acid, Aurora Beam, Bubble and Bubblebeam effect chance fix

---

chat-plugins/trivia.js

Theoretically, it's possible to get over 5 points from answering if the
answer was sent before the current question's askedAt is reassigned.

Trivia plugin: fix crash in timer mode scoring

---

config/commands.js

Requested by multiple people for some reason.
Allows for searches such as ```/ms priority 2``` which  returns all moves which are in the priority bracket of 2. This doesn't add functionality, but it makes the syntax for exact priority searches more understandable.

Exact priority bracket targeting for /movesearch

---

data/abilities.js

Relevant for when the Pokemon with an active Flash Fire boost has its
ability changed or suppressed.

Send -end message when Flash Fire volatile disappears

---

data/items.js

Apparently the move data that stores PP doesn't have a "name" property.

Fix Leppa Berry protocol message

---

.gitignore
.travis.yml
gulpfile.js
package.json

This cache is quite awful (welcome to the world of Node.js, I guess), but at least it works. It has few flaws, like not being able to GC unused cache files. Still, has to work for now. Changes syntax test times from 10 minutes on my very slow laptop to 0.6 seconds.
(I wonder how this will work with Travis...)
Later I will try to figure out why JSHint is so unbelievably slow.

Introduce cache for syntax testing.

---

data/formats-data.js

It's not worth the low accuracy just to be able to hit both opponents. Better to stick to its Freeze-Dry for coverage, and Hurricane for the high power option.

Random Double Battle: Remove Blizzard from Articuno

---

commands.js

In general if a command `/X` can be "reversed", the name for reversing it should be `/unX` for consistency. This adds an alias `/unaway` for `/back`, and `/unrangelock` for `/rangeunlock`.

Add 'unaway' and 'unrangelock' aliases

---

chat-plugins/tcg.js

wasn't really needed, but it's 'more correct.'

TCG: fix spacing

---

config/commands.js

removes minor confusion with some status moves such as Confuse Ray returning with x0 effectiveness as well as the two special cases of Bide and Future Sight. This still does not fix moves which modify immunity from returning correctly such as Thousand Arrows, but all such moves state they remove immunity in their descriptions.

check affectedByImmunities in /eff

---

mods/gen1/formats-data.js

These two Pokémon have a rather low Attack stat, and are not able to compete without their STAB Fire move.

Fire Blast on Ninetales and Vulpix

---

config/commands.js

allows for /dexsearch to check a Pokemon's stats against the entered
arguments. inequalities are the equal-to variants because they are the
most used and easiest accessible.
I'm sure some things could be improved about this, but it's at the very least functional. The syntax is also very flexible, which I find to be a plus. If somebody can figure out a way to allow for => to be distinguished from > that could be a potential improvement, however I was unable to figure out a good way to do so. Also I chose to make > function as => by default because that makes it the most user friendly from my perspective, even if it might create mild confusion the first time people see it used.

Add stat ranges to Dexsearch

---

data/formats-data.js
data/scripts.js

The Doubles EV generator means it's more beneficial to give Huntail all
Physical moves (252 Atk Ice Fang outdamages 0 SpA Ice Beam, for example)
Remove Icy Wind/HP-Ice redundancy check because Keldeo no longer has
Hidden Power Ice on its random battle sets.

Random Double Battle: Update Huntail, Remove Icy Wind/HP-Ice check

---

data/formats-data.js
data/scripts.js

Reject Hydro Pump with Waterfall (affects Samurott and Kingdra).
Reduce the number of moves available to Porygon2 so it has a higher chance
of getting Recover.

Random Battle: Update Porygon2, improve Water redundancy checks

---

data/rulesets.js

Kyurem-White is now completely banned from Monotype. This removes
unused code from Same Type Clause.

Remove complex ban for Kyurem-White in Monotype

---

config/commands.js

Most of the time this message is showing up is because the command is being broadcasted making it irrelevant and just causing clutter.
http://puu.sh/h4nRL.png
This commit also contains another minor change wherein the two commands can output up to 5 additional matches (currently 15) if that is all the matches. This would make the output the same length, if not shorter, than the output if it were to limit it to 10.

Reduce /ds and /ms output clutter

---

data/formats-data.js

Random Doubles doesn't support mixed sets as well as Random Singles, so
this constrains both sets to Physical-only.

Random Double Battle: Update Cobalioin, Virizion

---

data/scripts.js

Remove hardcoded checks that give -ate Pokemon Normal moves, instead using
the Random Single Battle's code.

Random Double Battle: Update move rejection for -ate Pokemon

---

mods/gen2/rulesets.js

Unable to be on the same set. Gen 1 TM + Gen 2 Egg move.

Make Explosion + Rapid Spin illegal on Cloyster in GSC

---

tournaments/index.js

Infinity and -Infinity are no longer valid settings. The command now
uses 0 instead of Infinity to turn off the timer.

Add Infinity and 0 aliases for /tour autodq off

---

chat-plugins/scavengers.js

This frees "," to be used in hunt questions.

Change starthunt separator to |.

---

sockets.js

This is because io.js tries ipv6 first, which the rest of PS does not support very well. Using 0.0.0.0 forces ipv4.
It seems silly that the previous line checks for 0.0.0.0 and sets to undefined, but different default values are used in different contexts.
I'm applying this patch to main immediately, but I'd like a review before merging into the repo. Particularly, does the SSL case not need to bind on `Config.bindaddress`? This surprises me.

Use 0.0.0.0 if Config.bindaddress is missing.

---

mods/gen2/scripts.js

hasMove was not tracking moves properly, instead keeping all moves ever
added in the object even if they were rejected. Also, there was a line of
code that caused all moves to be flagged as rejected.

Gen 2 Random Battle: Fix Move Rejection Phase

---

data/moves.js

The relation is hard-coded because no other move changes based on the
user's type the way Curse does, and the alternative would require
refactoring some things with the event ordering.

Fix interaction between Curse and Protean

---

battle-engine.js
config/commands.js
config/formats.js
data/abilities.js
data/items.js
data/moves.js
data/scripts.js
data/statuses.js
mods/gen1/moves.js
mods/gen1/scripts.js
mods/gen1/statuses.js
mods/gen2/scripts.js
mods/gen3/moves.js
mods/gen5/moves.js
mods/gennext/abilities.js
mods/gennext/moves.js
mods/stadium/scripts.js
test/simulator/misc/statusmoves.js
test/simulator/moves/thousandarrows.js
tools.js

Frankly, this is such a huge refactor that I won't feel safe until like, @Zarel, @Marty-D and 2 other people [EDIT: with write access] have independently verified that this is a good idea and will work. It seems to work ostensibly, and a quick `grep` seems to point towards all `affectedByImmunities` properties from being removed, but I still need more opinions just to make sure. (15 files are being changed here!)

Move refactor: moves/items that ignore immunity/effectiveness

---

config/formats.js

Certain moves, such as Trolling Lobby, do not get properly disabled by Taunt (instead allowing the move to be "used," but displaying a message that the user can't use the base move due to the Taunt). This fixes that issue.

Super Staff Bros.: Fix Taunt

---

mods/gen1/scripts.js
mods/gen2/scripts.js
mods/stadium/scripts.js

Unlike battle-engine.js, old gens did not check if move.ignoreImmunity was
undefined/false in their getDamage functions, causing crashes when numbers
were passed in to the function.

Fix ignoreImmunity crashes in earlier gens

---

config/commands.js

Entering a type as the source instead of a move resulted in a crash as the
program attempted to read a nonexistent `ignoreImmunity` property.
No fix needed on L1283 because `souce.category` won't exist for pure type
effectiveness checks anyways and `Tools#getMove` always fills in `ignoreImmunity`.

Fix /effectiveness chat command crash

---

config/formats.js

That var was being used to show what `result` and `chance` were for.

Super Staff Bros.: Remove unneeded variable.

---

data/scripts.js

Removed Dragon Ascent so QuoteCS's signature move could allow him to
keep the SpD boost.

Super Staff Bros.: Remove a move from %QuoteCS

---

battle-engine.js

b922ae2f introduced possibility of using Pokemon over level 1000 in custom battles. However, this doesn't work in practice, because battle engine limits level to 1000. This commit fixes what b922ae2f should have done all along.

Allow level 9999 Pokemon in battles

---

test/simulator/moves/thousandarrows.js

Zygarde's Thousand Arrows will KO Eelektross if it gets a critical hit,
meaning that the Weakness Policy being used to check if the move was
super-effective will not activate. Fixed by initializing the battle with a
seed that does not result in a critical hit from Thousand Arrows.

Fix Thousand Arrows test

---

data/scripts.js

This will help reduce repetition, and also will allow for the move
tracking to easily update after the final moveset modification
(for example, allowing Choice Band/Scarf Mega Rayquaza if its last
Status move was overwritten by Dragon Ascent).
This has been discussed all the way back in #1557 but I hadn't gotten around to it yet.
Please code review this because I haven't had the opportunity to test it yet

Random Battle Refactor: Move Tracking split off as seperate function

---

data/scripts.js

HP EVs are completely useless on Shedinja.

Random Battle: Tweak Shedinja's EVs

---

commands.js

Fixes the problem with room alias "ghost rooms".

Send '|deinit' message when trying to hardlink to room aliases

---

data/scripts.js

There are a few Pokemon that set up but have very few viable moves and must
rely on Hidden Power for coverage, like Lilligant.
@TheImmortal, please discuss this with me, since there are also many Pokemon
that set up but don't appreciate having a STAB move plus a weak Hidden Power
as their only attacking moves (which is why you put this case in in the first place).
Is there a better criteria we can use to get this working? Lilligant almost always
has bad sets because of this line.

Random Battle: Improve Hidden Power rejection check

---

data/scripts.js

STAB Hidden Power without the Pokemon's other STAB can be bad. Instead,
check for EdgeQuake (Rock+Ground) as an acceptance criteria (for Lunatone)
As suggested by @TheImmortal in #1810

Random Battle: Slightly tweak Hidden Power rejection check

---

chat-plugins/info.js
command-parser.js
commands.js

```config/commands.js``` moved to ```chat-plugins/info.js```.
```/help``` and ```/a``` moved to ```commands.js```.
```/lobbychat``` removed entirely.
```/help``` refactored so that command help information can be written next to the commands themselves. This means that ```commands.js``` will not have to be modified at all for adding custom commands and can remain for core functionality online.
API documentation moved to ```chat-plugins/COMMANDS.md```.

Move config/commands.js to chat-plugins

---

chat-plugins/info.js

Accepts moves or types as parameters and returns the best-case effectiveness against every type.
Adding "table" or "all" as a parameter displays a table of all type combinations.
None-table: http://puu.sh/hqLKH.png
Table: http://puu.sh/hqyX3.png

add /coverage

---

chat-plugins/info.js

While snatch shows you all the moves it can steal with hovertext in battle, if you are the defending player it could be useful to check if your move is able to be stolen by snatch. Mirror flag for similar reason. Gravity flag is pretty rare and there is no reason not to show it.
Using "✗ Mirror Move" and "✗ Suppressed by Gravity"
Just to make sure we don't want any of the other flags to be returned with `/details`, here is a list of all flags that do not return information:
- charge
- distance
- heal
- recharge

Add snatch, gravity and mirror flag to /dt

---

chat-plugins/info.js

This makes it easier to put an entire moveset into a command without having to worry about status moves being counted as real moves.

Ignore status moves from /coverage

---

chat-plugins/info.js

If spaces aren't being used as the target split, remove them. This allows the syntax `/weak fire / grass` to work. Also checking for double typing because we don't know the full implications of what that would mean. (request by @Ridaz)

Improved /weak targeting

---

data/scripts.js

Add the "weakcoasta" set to randbats. These abilities give Carracoasta the potential to tank a super effective hit and be a dangerous +4 sweeper in just one turn.

add weakcoasta to randbats

---

data/abilities.js
data/statuses.js
test/simulator/abilities/cloudnine.js

Old implementation allowed Pokemon to use a standard weather move like
Rain Dance successfully against a primal weather like Harsh Sun if a
Pokemon with Cloud Nine or Air Lock was active.

Standard Weather always fails to activate when Primal Weather is active

---

chat-plugins/info.js

Murkrow, Swirlix, Yanma, and Meditite doesn't exist in any other category, so unless you allow searching for this, those four can't be found in a tier search.

Add LC Uber to /dexsearch categories

---

users.js

The quicker the queue can go, the better.

Use last message time for timeout on chat queue creation

---

battle-engine.js
data/items.js
data/moves.js
data/statuses.js
mods/gen1/moves.js
mods/gen2/moves.js
mods/gen3/moves.js
mods/gen4/moves.js
mods/gen5/moves.js
mods/gennext/abilities.js
test/simulator/items/assaultvest.js
test/simulator/moves/disable.js
test/simulator/moves/gravity.js
test/simulator/moves/healblock.js
test/simulator/moves/imprison.js
test/simulator/moves/taunt.js

The intention for this event is to remove the move disabling code away
from ModifyPokemon and to an event that can be run a fewer number of
times. Since the disabledMoves index is used to gray-out moves that cannot
be used, and not for any other purpose, there is no need for the related
code to be run at the ModifyPokemon timing, instead working better as a
once per turn event.
-----
This is another one of those giant refactors, so naturally I'll be nervous about
it no matter how well it seems to go.
Code ostensibly works, and passes the regressions I set up, but I don't have 
a full understanding of all the mechanics for moves, and the oldgens 
regressions are non-existent right now. Tagging @Joimer for his expertise
in all things oldgens. Also @Slayer95 for current gen stuff (especially …

Refactor disabling moves, other miscellaneous bug fixes

---

mods/seasonal/moves.js
mods/seasonal/scripts.js

Don't call the Damage event in getDamage -- it is already called in
Battle#damage and would therefore cause doubled events for Barkskin, etc.

Seasonal: Add move animations, bug fix

---

data/scripts.js

- Removed Trick/Gyro Ball checks as no Pokemon uses that combination.
- Reject Life Orb on Pokemon with 55 or less base Speed.
- Add a check for slow and strong Regenerator Pokemon to receive Assault
Vest, at slightly higher priority than Sitrus Berry.
-----
Fixes the three-week-old #1821.

Random Doubles Battle: Item Distribution Update

---

commands.js

Intended to prevent auth from unintentionally having their ranks removed by a tabfail.
I don't really think this is the best implementation, but `user.send("|popup|...")` can't use html so no convenient button to type `/forceban` for you. Since crisis situations are uncommon I'm not sure any edits to the client are necessary to make a better popup.

Implement /forceban and /forcelock

---

data/abilities.js
data/moves.js
data/scripts.js
mods/gen5/moves.js
mods/gennext/abilities.js
test/simulator/abilities/rockhead.js
test/simulator/abilities/sheerforce.js
test/simulator/moves/substitute.js

Instead of having a hardcode in scripts.js that people needed to
reference, it seemed more intuitive to take advantage of the Damage
event instead, and have Rock Head negate damage within the event.
Fixed a minor Gen-NEXT Rock Head bug that was basically the same
as our old Rock Head + Mummy bug.
Also, fixed up a Sheer Force test (the Sheer Force Pokemon didn't
have a Life Orb so the test checking for the negation of Life Orb recoil
would pass even if Sheer Force wasn't coded correctly.
---
This PR could also be titled "I'm bored at work"
I was planning to un-hardcode Sheer Force too but that one wasn't
being very cooperative.

Un-hardcode Rock Head in favor of an onDamage handler

---

battle-engine.js
data/abilities.js
data/moves.js
data/scripts.js
test/simulator/abilities/arenatrap.js
test/simulator/misc/inversebattle.js
test/simulator/moves/electricterrain.js
test/simulator/moves/grassyterrain.js
test/simulator/moves/mistyterrain.js

Added BattlePokemon#isGrounded to check for the grounded-ness of a
Pokemon. Also BattlePokemon#inSemiInvulnerableState for whether a Pokemon
is in the first turn of a two-turn move that makes them semi-invulnerable.
Fixed Terrain bugs involving Pokemon in a semi-invulnerable state.
Fixed Misty Terrain bug that was causing Rest and the effect of Yawn to
put Pokemon to sleep.
Fixed Misty Terrain bug that was causing Yawn to fail.
Fixed Electric Terrain bug that was causing Yawn to succeed.

Battle refactor: New function isGrounded(), bug fixes

---

battle-engine.js
data/abilities.js
data/items.js
data/moves.js
data/statuses.js
mods/gennext/statuses.js
test/simulator/abilities/klutz.js
test/simulator/moves/embargo.js
test/simulator/moves/magicroom.js

Instead, the relevant abilities that set ignore do so upon Start/End events.
---
It's worth noting that even though this passes the tests I set up, **it's not actually complete.**
Specifically, I don't know how to implement Baton Pass with Embargo/Gastro Acid and
would appreciate if someone had insight on the best way to manage that.
@Marty-D for move mechanic verification
@Zarel for NEXT verification since I don't know how you want the intrinsics working

Battle refactor: No longer reset ignore in Battle#update

---

battle-engine.js
test/simulator/abilities/sheerforce.js
test/simulator/items/leftovers.js

This system is problematic for people who enter games without having
filled out their EVs, as their stats will not reflect the stats shown
in the teambuilder and can influence damage calculations, resulting in
many erroneous bug reports.
---
@Zarel since he was the one who mentioned that it needed to be changed.

Battle Engine no longer sets EVs to 84 with blank EV sets

---

battle-engine.js
test/simulator/abilities/multiscale.js
test/simulator/abilities/thickfat.js
test/simulator/abilities/unaware.js
test/simulator/moves/electricterrain.js
test/simulator/moves/thousandarrows.js

It should compare this.activePokemon to "thing", which is the Pokemon that
is holding the Ability being processed, not "target".
Also fixed random typo where Mold Breaker might succeed even if the
ability were supressed.

Fix Mold Breaker's interaction with Unaware

---

data/formats-data.js

with the lower than 1.7% usage Gallade has dropped to NU

Bring Gallade to NU

---

data/moves.js

It would have halved damage from Dragon moves against semi-invulnerable
Pokemon if No Guard or Lock On was involved.

Slightly tweak Misty Terrain

---

data/moves.js

They were forcing the Pokemon to attempt to use Fly/Bounce again.

Fix Smack Down and Thousand Arrows' interaction with Fly/Bounce

---

battle-engine.js
test/simulator/abilities/levitate.js
test/simulator/abilities/magicguard.js
test/simulator/abilities/sturdy.js
test/simulator/items/focussash.js

- Process the 'runSwitch' decision directly in Battle#dragIn in gen
5 and up. This allows the Pokemon executing the phazing move to
remain as battle.activePokemon for the duration of the dragging
action. This fixes Mold Breaker's interaction when moves that drag
out Pokemon are used.
- Add a check for battle.activePokemon.isActive in the Mold Breaker
ability negation check to prevent glitches with Mold Breaker and
Red Card.
- Remove Damage/SubDamage from Mold Breaker's check and instead add
an additional check for the Damage event specifically to use extra
criteria. This fixes its interaction with Magic Guard.
====
Technically still waiting for @Marty-D to verify my assumption of the given scenario is correct: if a Pokemon with Mold Breaker hits a Red Card and a Levitate Pokemon is …

Fix some Mold Breaker bugs with drag-out moves

---

battle-engine.js
test/simulator/misc/eventemitter.js
test/simulator/misc/weight.js

Creates an option `battle.test` that Mocha tests can use to create their
own temporary event handlers that can get picked up.
At any rate, it's more efficient than hotpatching the getEvent function.
---
@Zarel @Slayer95 @TheImmortal 
I'm also very sleepy and this could be prone to tons of error.
`battle.getRelevantEventsInner` is set to "borrow" the format data when
resolving `battle.test` event handlers because like, it's part of this custom
one-use format??? idk if it's a good idea good night everybody

Add option for Mocha tests to use event handlers

---

test/simulator/items/ironball.js
test/simulator/items/ringtarget.js
test/simulator/moves/foresight.js
test/simulator/moves/miracleeye.js

I found these sitting around uncommitted on my computer today. I suspect I was planning to refactor `pokemon.negateImmunity` out of `ModifyPokemon` but that can come later.

Add tests for type-immunity negating moves and items

---

battle-engine.js
mods/gennext/statuses.js

The new function name makes it clear that the function doesn't actually
suppress attack events, only checks if they would be suppressed.

Style Change: suppressAttackEvents -> suppressingAttackEvents

---

chat-plugins/info.js

Parameter 'FE' is not used by the `/dexsearch` but it is mentioned in the help. 
Reported in [smogon](http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/page-215#post-6264308) thread.

Remove 'FE' parameter from dexsearch help

---

commands.js

This prevents sort from being ASCII-betical causing lowercase nicks to appear after uppercase nicks.

Sort authority in /auth by ID

---

mods/gen4/abilities.js
test/simulator/abilities/pressure.js

Also a quick fix for Gen 4 Pressure to count allies' moves as well for Pressure.
For an incoming Pressure refactor that will fix all the other Pressure-related bugs.

Add working and pending tests for Pressure

---

battle-engine.js
config/formats.js
data/abilities.js
data/items.js
data/moves.js
mods/gen4/items.js
test/simulator/abilities/wonderguard.js
test/simulator/items/ironball.js
test/simulator/moves/ingrain.js
test/simulator/moves/thousandarrows.js

Replace the pokemon.negateImmunity object with a new `NegateImmunity`
event that handles all the immunity negation.
Also deprecate 'IgnoreEffectiveness' in favor of having relevant moves
and items use `Effectiveness` event handlers instead.

Battle refactor: No longer reset negated immunity in pokemon.update()

---

mods/gen5/moves.js

Fixes glitches preventing it from working properly due to it inheriting
Gen 6's TryHit handler and effectively locking the users in a loop.

Move Gen 5 Sky Drop's Try handler to TryHit

---

data/moves.js
test/simulator/abilities/stickyhold.js
test/simulator/moves/knockoff.js

Knock Off's function call for target.takeItem was written in such a way
that Sticky Hold could not actively notice and trigger its TakeItem event.
This fixes the function to have the handler called properly.

Fix Mold Breaker Knock Off with Sticky Hold

---

test/simulator/misc/statusmoves.js
test/simulator/moves/glare.js
test/simulator/moves/thunderwave.js

I could have pushed this directly into the main code, but wanted to discuss part of the naming schema we use for our Mocha describe functions when testing oldgen behavior.
For a lot of the old tests, the describes have been in the format `describe('FEATURE - GEN')`, which means if the test fails, you get a message like so:
> Battle simulation Moves Chatter - BW should not pierce through substitutes
The positioning of the hyphen implies that "BW should not pierce through substitutes", which makes no sense. As seen in this pull request, I'm basically proposing that the generation that we're testing for be placed in parentheses instead of using a hyphen as the separator (I've already done this in a few earlier PRs as well, such as #1971).

Further upgrade status move tests

---

users.js

`this.can('lock')` was checking if the original username was able to lock rather than the username being switched to. putting after `this.forceRename()` seems to ensure that the user has the correct permissions when the checks if their PMs should be unblocked happens.

Bug fix: unblock PMs for staff on name change

---

loginserver.js
rooms.js
users.js

- Make sure that error parameters are all instances of `Error`.
- `parseJSON` now distinguishes `null` values from invalid syntax, by returning an object with relevant information.
- Request timeouts are now handled by node built-in `setTimeout` method, and use custom `TimeoutError` (exported from `LoginServer` for debugging).
This helped figure out the crash mentioned at https://github.com/Zarel/Pokemon-Showdown/pull/1910#issuecomment-109660338

Improve error handling for login server requests

---

chat-plugins/info.js
data/moves.js

this.runEvent doesn't exist when the function is run from chat commands,
where 'this' points towards Tools instead of an active battle.

Fix Thousand Arrows crash when used in chat commands

---

battle-engine.js

This line of code was emitting a lot of debug messages that are presented
without context and can be confusing to viewers of the battle log.

Cut down on debug messages emitted in runEvent

---

data/moves.js
test/simulator/moves/skydrop.js

@Marty-D can you verify the mechanics of how Pokemon can be freed from the Sky Drop glitch are indeed the ones that I mentioned? What happens when Power Herb is used with two-turn moves, or maybe if the two-turn move misses or is blocked by Protect?

Add Sky Drop tests and pending Sky Drop glitch tests (for Gen 5)

---

chat-plugins/info.js
command-parser.js
commands.js

- Now using prototype inheritance for contexts
- New APIs: `this.cmdToken` and `this.run()`.
- No docs yet, maybe we want different names?
Results
- op/s improvements ranging from 10% to 50% for commands in this benchmark:
http://hastebin.com/iwodelayuv.js
- I'd assume this improves memory usage and garbage collection as well.

Refactor command parser and add more APIs

---

chat-plugins/info.js

Calls `/dexsearch` and returns a random Pokemon that would have been included in the results. Without arguments it calls one random Pokemon, otherwise an integer is read as the number of random Pokemon desired (forces "gen" to be used if a gen parameter is desired) and all other parameters are assumed to be used in the dexsearch search.

/randompokemon mode for /dexsearch

---

chat-plugins/info.js

These default statements are unreachable anyways, but if anyone wants to mod /dexsearch or /movesearch on their own sever this is probably more useful error handling.

Proper error handling in /dexsearch and /movesearch

---

battle-engine.js
data/abilities.js
data/items.js
data/moves.js
test/simulator/abilities/klutz.js
test/simulator/abilities/unburden.js
test/simulator/items/drives.js
test/simulator/items/mail.js
test/simulator/items/plates.js

Knock Off no longer broadcasts the source so Arceus can knock off a Plate
from a non-Arceus, Genesect can knock off a Drive, etc. Updated Sticky
Hold to check for Knock Off specifically as a result.
TakeItem is no longer suppressed by Mold Breaker, fixing interaction with
Unburden. Updated Sticky Hold to check for Mold Breaker instead.
Items that prevent their own removal do not have that effect negated by
Klutz and other item-negating effects.
Thief and Covet can steal Mail.

Various item removal fixes

---

data/abilities.js
data/items.js
data/moves.js
data/scripts.js
mods/gennext/abilities.js
mods/gennext/items.js

Add a new event ModifyAccuracy that affects all moves other than OHKO
moves and switched many event handlers that originally used the Accuracy
event to ModifyAccuracy instead.
---
Based on a conversation with @Marty-D a few days back. I think I caught
all the relevant event cases after grepping `/on\w*Accuracy/`.
Will change the new event name if it doesn't fit.
@Zarel, about Gen-NEXT Substitute, is it supposed to give OHKO moves
the 100% accuracy as well, or no?

Fix OHKO moves' interaction with accuracy-changing abilities/effects

---

battle-engine.js
data/moves.js
test/simulator/moves/quash.js

Give the move demoted by Quash a negative priority when rearranging it in
the queue so that it does not get re-sorted to its original position when
self switch moves run.

Fix Quash interaction with self-switching moves

---

rooms.js
users.js

- Aborting ladder searches no longer cancels challenges …
- Handle each format independently
- Prevent ghost users from joining MM queues
- Periodically try to find a match for players waiting the most

Improve matchmaking

---

chat-plugins/info.js

- `/suggestions` is for whenever a user in lobby/help/another room says something like "I think x would be good to add" so someone can just do `!suggestions` or w/e
- `/bugs` is for when someone says "I found a bug that relates to x" (or something of the sort) and a voice can do `!bugs` or `!bugreport`

Add /suggestions and /bugs

---

chat-plugins/info.js

- "Show everyone that information" was inconsistent with all of the broadcasting parts of the other help commands and is grammatically incorrect.
- Changed the single quotes to double quotes for consistency
- escaped the "e" in Pokémon for /intro to make it consistent with all other instances of "Pokémon".

Info.js: Minor Changes

---

commands.js

Since lock and ban popups are modal, I see no reason why mute popups shouldn't be as well.

Make mute popups modal

---

battle-engine.js
test/simulator/abilities/desolateland.js
test/simulator/abilities/intimidate.js

Added a new check behavior in addQueue to insert a decision in the correct
position as needed. The 'insert' flag tells addQueue to put the decision
in the correct place, but not re-sort the queue.
----
It's a very temporary and quick fix for the bugs that I introduced in the earlier
Quash PR but it's the best I can do without getting a headache from refactoring
the entire queueing system.
@Zarel @Slayer95 @DanUgore

Fix behavior with Ability activation in double-KO scenarios

---

battle-engine.js
tools.js

Properties should now be searched in this order:
- Instance
- Scripts installed
- Battle.prototype properties
- <strike>Scripts installed (again)</strike>
- Tools properties
- Object properties

Shrink needlessly long prototype chains for battles

---

battle-engine.js

This allows the client to remove the weather when it expires, even if
there is a Cloud Nine Pokemon on the field.
-----
@Marty-D should confirm if `Residual` should be suppressed or not
because I'm unsure if messages that mention the weather is active
occur or not with Cloud Nine on the field.

Don't let Cloud Nine suppress Residual or End events from weathers

---

PROTOCOL.md

The info on action tags are now in the Major Actions section since the
|move protocol message uses them as well.

Update PROTOCOL.md to document [anim], move info on action tags

---

battle-engine.js
data/abilities.js
data/scripts.js
mods/gen4/abilities.js
test/simulator/abilities/pressure.js
test/simulator/moves/followme.js

Changed BattlePokemon#deductPP to accept multiple targets, and run the
DeductPP event on each one.
Moved the deductPP function call into useMove so it can accurately query
all targets for the move instead of just one.
---
It's an ugly solution, but it's the only one I could think of that would actually work...

Fix PP deduction interactions with Pressure

---

loginserver.js

- Client will no longer stop working when a callback crashes.
- Ensure login server callbacks are called once on errors.
This has as visible effect that prior error popups displaying ``"socket hang up"`` error messages will no longer be displayed, and users will now instead see ``"Response not received"`` errors, which are hopefully less cryptic.

More improvements to login server requests' error handling

---

battle-engine.js
test/simulator/abilities/intimidate.js

Switches and runSwitch were recently updated to priority 7 and 7.1, so
this part needs to be updated as well.

Update priority of switches when a player has no actives

---

battle-engine.js
data/abilities.js
data/items.js
data/moves.js
data/statuses.js
mods/gennext/abilities.js

The Modify(STAT) events can no longer get a floating-point modifier
because battle.runEvent already calls battle.modify, which rounds it.

Normalize ModifySpe calculations with the other Modify-Stat events

---

data/abilities.js

@Marty-D: please stop believing websites that aren't this one or UPC :/
The description for Defeatist is literally "While this Pokemon has 1/2
or less of its maximum HP, its Attack and Special Attack are halved."
I even looked in-game and it said it was half of lower, and even sites
we shouldn't trust say it's 1/2 or less of max HP.

Fix Defeatist's interaction with HP

---

data/formats-data.js
data/scripts.js

Removed Helping Hand and Heal Pulse from Pokemon with very low usage stats
for those moves.
Reject Trick Room with Icy Wind. (Affects Jirachi, Jellicent, Cresselia)
-----
@TheImmortal, TIBot in PS! when
I was noticing the heavy usage of Sludge Wave on Nidoqueen and Discharge on Jolteon, but proper Doubles teams would've probably been running Steel-types or Lightning Rod Pokemon to abuse them anyways so I won't change those for those Pokemon.

Random Doubles: Tweak Helping Hand, Heal Pulse, Trick Room distributions

---

commands.js

It is possible that an Administrator could attempt to make a room that an already existing room has as an alias.  This check will prevent this moving forward.

Check if a room exists as an alias before creating it

---

data/aliases.js

Previously Burnt Berry was an alias for Rawst Berry, even thought it should've been for Aspear and vice versa.

Fix Burnt Berry and Ice Berry

---

data/scripts.js

Many of the rules used in Random Singles Battles also apply to Doubles, so
many of them are transferred over to the Doubles set generation code.
@CrestfallPS

Random Doubles Battle: Synchronize Ability selection with Singles

---

data/abilities.js

If two Zen Mode Pokemon Skill Swap each other, Zen Mode will end.

Fix Zen Mode interaction with Skill Swap

---

data/scripts.js

This fixes a problem introduced by 77b6b666 causing certain Pokemon with mega stones (and base forme of Audino) to have level 90 in randbats.
This commit intentionally doesn't introduce any new levels for mons who have their tier in parenthesis. Looking over the list of mons who don't have hardcoded levels, most of them are barely improvement over their base forme, which is the issue in a standard tiers with its limit of one mega. However, because teams don't have to use a mega in randbats (because of how its generator works), getting just a slightly version of a Pokemon is not a big deal as it's still an improvement, even if minor.

Add support to randbats for mega stone banning

---

battle-engine.js
data/moves.js
test/simulator/abilities/pressure.js

They're treated as foeSide moves for Pressure, but officially target
themselves.

Fix Snatch and Imprison's interaction with Pressure

---

data/scripts.js

If both Physical and Special setup moves are present, and there are an
equal number of Physical and Special moves, simply choose Special instead
of randomizing it.

Random Battle: Don't randomly choose setupType in case of a tie

---

battle-engine.js
data/abilities.js
data/scripts.js
test/simulator/abilities/shielddust.js

Refactor TrySecondaryHit to become ModifySecondaries instead to allow for
proper behavior.

Shield Dust does not block self-boosting secondaries

---

tournaments/index.js
users.js

Tournaments room on main Showdown server has a rule that disallows scouting in a tournament. New users to a room don't often know about that rule, and they get disqualified, and as a result they complain about being disqualified claiming that "opponent hacked to cause them to forfeit".
This commmit enforces that rule when specified for a tournament (it's completely optional to specify it), so a new user wouldn't accidentally scout.
Depends on Zarel/Pokemon-Showdown-Client#459 to work.

Implement optional scouting protection for tournaments

---

data/abilities.js

The other option is to modify `transformInto` in such a way that it broadcasts `-transform` messages to use the correct `[from]` parameter, then add a client change to check for it.
Either way will allow Imposter to be properly tracked by the client.

Add -ability tag to Imposter activation

---

chat-plugins/info.js

Previously, something like !ds !recovery didn't work, because the existence search check assumed that the search cannot be called with parameter false. However, boolean searches like recovery and priority do simply use booleans.

Fix negation of boolean conditions in /ds

---

commands.js

The /validate command allows users to validate their team for its format as part
of the teambuilding experience. Currently, the only way to validate a team is to
actually try to battle with it, then go back and forth from the teambuilder
until the team is not rejected. User#validateTeam will be made accessible via a
new button in the teambuilder.
Screenshots: http://imgur.com/a/dVj3F

Add a "/vtm [format]" command for standalone team validation

---

commands.js

Now, escape HTML in room descriptions to prevent things like this from being possible: http://prntscr.com/8g0mjy

Escape HTML in room descriptions

---

data/moves.js
data/scripts.js

Since the basePower for Magnitude is set and displayed in onModifyMove, the magnitude value gets displayed before the move starts to execute (from the client's perspective). Moving the "-activate" message to onPrepareHit instead displays it correctly.
[Before](http://i.imgur.com/pLsjqgj.png)
[After](http://i.imgur.com/npx0F2C.png)
[For reference](http://cdn.bulbagarden.net/upload/1/14/Magnitude_V.png)

Display value of magnitude after move is used

---

app.js
commands.js
rooms.js

Personal rooms are temporary rooms that are neither stored nor logged.
The purpose of this kind of room is twofold:
First, it serves as a multiple user Private Message conversation.
Second, it serves as a private friend chat.
This eliminates the need to register private rooms for groups of friends.
Personal rooms are destroyed when no one is on them.
They are to be used with /invite only.
They can be created by anyone.
They require a name, but the creator name will be present on title.

Implement personal rooms

---

data/formats-data.js
data/scripts.js

- Remove Wake Up Slap because it's no longer Technician boosted.
- Change Technician to reject if a Pokemon has Skill Link and all their
Technician-boosted moves are Skill Link moves.
Miscellaneous changes:
- Placed Sheer Force within the counterAbilities section.
- Sorted the coutnerAbilities in the Random Doubles Battle code.

Random Battle: Update Cinccino

---

mods/gennext/README.md
mods/gennext/abilities.js
mods/gennext/formats-data.js

Improved the grammar on many parts of the README. Also, sorted the Pokemon
in the Intrinsic Levitate section and removed mention of released Hoopa.
Staying true to the Gen-NEXT OU banning philosophy, Hoopa-Unbound is now
banned. Landorus-I is now unbanned.
Removed ability modification in weather-setting abilities as they are no
longer needed.
----
I want to discuss unbanning Aegislash. I think if we changed Stance Change to activate at the beginning of the turn instead of right before attacking, it would be balanced.

Gen-NEXT: Update README.md

---

commands.js
rooms.js

- Optional second roomintro that can only be seen and set by drivers+ (useful for watchlists, getting a message to all staff, etc.)
- Refactor ChatRoom.getIntroMessage

Implement staffintro feature

---

chat-plugins/info.js

Room moderators now gain a new command (/staffintro), so we can list it in /roomhelp along with the others.

Add /staffintro to /roomhelp

---

mods/gen1/moves.js
mods/gen1/statuses.js
test/simulator/misc/statuses.js

Previously moves like Leech Seed incremented residualdmg when used by 1, but this doesn't actually happen in the game. Instead, an actual game uses a flag to store toxic poisoning flag, and when it's not specified, these statuses always dealt 1/16 of full HP.
This fixes the issue where the sequence of moves (Toxic followed by Leech Seed) was dealing 1/16, 3/16, and 4/16 of full HP in residual damage, instead of 1/16, 2/16, and 3/16.

Poison/burn/leech seed don't increment residualdmg in Gen1

---

data/formats-data.js
data/scripts.js

Reject Mach Punch as the only STAB move.
Reject Bullet Punch as the only STAB move if the Pokemon does not have
Technician. Affects Metagross and Mega Lucario.
Reject Sheer Force with Fake Out in Doubles. Affects Hariyama.
Reject Flash Cannon with Iron Head in Doubles to match the rule in
Singles. Affects Aegislash.
---
I want to discuss Cherrim. In Singles, since it is so frail, I don't think it has as much of a use for the sun if it doesn't have Weather Ball/Solarbeam (although I guess the Special Defense boost helps). I was thinking of adding other moves like Dazzling Gleam or Healing Wish to compensate. Maybe Giga Drain could also be added but Cherrim's low stats means it really might want Energy Ball in randbats for the raw power (as opposed to it wanting Giga Drain in PU)

Random Battle Move and Ability Updates

---

chat-plugins/info.js

Users no longer have to do /showimage url,, to show an image at its
default dimensions. They may also use whatever values they want for the
height and width styles so long as they're valid.

/showimage: optional dimensions, accept CSS height/width values

---

chat-plugins/poll.js

Some room staff or people looking in the modlog may get confused by the message "The timeout was set to...," so this specifies that it's referring to "The poll" as it does when a poll is started / ended.

Specifiy "poll" timeout in /poll timer

---

rooms.js

With the current autojoin system, the user has already joined rooms
before the login process is completed, making the checks for staff in
ChatRoom.getIntroMessage fail. This ensures that staffintros are seen
when first joining the server by also sending them in ChatRoom.onRename.
This is the simplest solution I could find other than refactoring autojoin.

Ensure staffintros are seen

---

battle-engine.js
config/formats.js
data/rulesets.js
team-validator.js

Formats now declare their team length requirements as `teamLength`
E.g., to enforce players to bring teams with 4-6 Pokémon to Team Preview,
and make them choose 2 of them there to battle with:
```
teamLength: {
validate: [4, 6],
battle: 2
}
```

Formats now declare their team length requirements as `teamLength`

---

data/formats-data.js
data/items.js
data/rulesets.js
tools.js

- Introduces `battleOnly` to Pokémon formats-data to flag which formes are forbidden on battle start.
- Adds back Secret Sword as Keldeo-Resolute's required move.
- Introduces `requiredAbility` to handle Darmanitan-Zen.
- Introduces `signatureSpecies` and `signatureForme` to items' data to flag the formes that some items enforce.

Consolidate Pokémon forme validation

---

battle-engine.js

<strike>- Crashlogger now reports more data of the last request. In particular, the moves available for active Pokémon will now be logged, so that meaningful knowledge can be gained from ``move 2`` etc choice logs.</strike>
- Replays will now log players decision, and starting battle seed. This should be extremely useful for handling bug reports. Requires https://github.com/Slayer95/Pokemon-Showdown-Client/blob/7cda6afcd2bc3dc991aa52bad36bf88ec7640ce7/js/battle.js

Detailed battle logs

---

data/scripts.js

Upgrade Flash Fire's rank to bypass Early Bird (for Houndoom).
Sucker Punch cannot be the only STAB move on Special attackers.
Fixed issues with incorrect setup.

Random Battle: Ability and STAB Changes

---

config/formats.js

#Arcticblast: do you definitely want evasion moves and abilities banned from DUbers?
@KyleCole: idc, but if you're running a tour with it and want it banned then im down
no longer allowed in singles Ubers iirc so why allow it here?

ban evasion from Doubles Ubers

---

tournaments/index.js

During signups in elimination tournaments, show users who have joined in
place of the empty bracket.
Please merge after the next client update.

Tournaments: show users who have joined

---

config/formats.js

It moved down and was added to the DNU banlist but not removed from the DUU one.
http://www.smogon.com/forums/threads/smogon-usage-based-tier-update-november-2015.3554723/#post-6504254

Unban Serperior from Doubles UU

---

mods/gen1/scripts.js

NU is worse than UU, so if UU pokemons will be skipped, NU should certainly be skipped as well.

[Gen 1] prevent getting >1 handicapMons

---

data/scripts.js

By checking the damagingMoves index length instead of the number of
Physical and Special moves, it not only ensures no Life Orb for Pokemon
with Rapid Spin, but also Nuzzle (such as Pachirisu) and any other
potential cases that have been missed.

Random Battle: Don't count weak moves for Life Orb item checks

---

chat-plugins/info.js

These are just the same aliases dexsearch has. I figured this was good for continuity sake, and I think someone requested this in suggestion thread somewhere.

Add isearch as alias for itemsearch

---

mods/gen1/scripts.js

You won't get more UU if you already have handicapMons, however if you get a lot UU first, you could still get handicapMons.
This fix make sure you wont get handicapMons once you have at least 2 NU/worse (which is already bad enough)

Gen 1: Reduce occurrence of extremely weak team

---

commands.js

this fixes a bypassal where users who are locked,and then become promoted cannot refresh and be able to talk in the room where they have roomrank

Disallow being able to be promoted to room rank while locked

---

commands.js
rooms.js

The second check in commands isn't optimal, but I wanted players to be able to set modchat if their opponent turns it off, and I couldn't see a way of doing that without a whole other function.

Disallow modchat wars in battles

---

commands.js
tournaments/index.js

This prevents users who don't want to be scouted in scoutable tournaments from gaining an unfair advantage by modjoining their battles.
If there is a better check for this, please let me know.

Disallow modjoin in scoutable tournaments

---

battle-engine.js
data/moves.js
test/simulator/moves/trickroom.js

Trick Room now uses a ModifyDecisionSpeed event to get its speed instead
of modifying the stat directly, since the Trick Room glitch would cause
calculations from Gyro Ball or Electro Ball to be inaccurate if the
Pokemon have speeds above and below the cutoff, respectively.

Refactor Trick Room and fix interactions with speed-based moves

---

data/scripts.js

Reverts Zarel/Pokemon-Showdown#2314
Lack of arrow functions causes the generator to break.
@Zarel please upgrade Node later

Revert "Random Battle: Fix dual STAB for Psychic-type Pokemon"

---

data/moves.js

Chance to confuse was incorrectly displayed as 10% in the in-battle description.

Fix incorrect Water Pulse chance in description.

---

commands.js

This allows people who want to appeal their roomban to be able to identify the users that are online in that room.   I hope this is the most efficient way of doing it.

Bold online users in Roomauth

---

data/scripts.js

Because of how moves are generated when a Pokemon has a setup move in its
move list, Seviper has a high chance of getting bad sets if Poison Jab is
rejected and Coil is added to its moves.

Random Battle: Favor Poison Jab over Sludge Wave on Seviper

---

chat-plugins/poll.js

"Timeout" is mostly a programming term; not something I want to show users. - Zarel

Poll: replies should say 'timer', not 'timeout'

---

config/formats.js

banning 'Salamence-Mega' allowed Salamencite to be used in Doubles OU leading to people Mega Evolving their Salamence and that is a Big No-No

[URGENT] Re-ban Salamencite from Doubles OU

---

battle-engine.js
test/simulator/items/leftovers.js

The client's tooltip (but not the teambuilder) correctly calculates a Gen1/2 Pokémon's speed using a (DV range of 0-15 equivalent) IV range of 0-30, however the battle engine allows odd IVs in Gen1/2 thus gaining an extra half DV. For example, a level 100 Zapdos can have a speed of 205 to 298 but in actual battle you will get 31 IVs for a speed of 299.

Prevent IV values that represent half of a DV

---

chat-plugins/mafia.js

I'll add the ability to export game setups as well at a later date.

Mafia: allow JSON game setups to be used instead of lists of roles

---

commands.js

I noticed the `.forEach`/`.push` usage in PR #2342 and it seems to me that `.map` would be a better fit. I spotted another case in `commands.js` so I updated that too, and I also found a similar case in `chat-plugins/trivia.js` where I can just use `Array.from` directly.

Replace some uses of forEach with map

---

battle-engine.js
data/abilities.js
data/moves.js
mods/gen3/abilities.js
test/simulator/abilities/lightningrod.js
test/simulator/abilities/stormdrain.js

Implemented a new priorityEvent function that is set to abort when any
event handler returns a non-undefined result, unlike runEvent which waits
until all event handlers have run. Set RedirectTarget to use this event.
Changed ability/move priorities for RedirectTarget handlers to fit under
this new paradigm.
Added new Lightning Rod and Storm Drain tests to ensure proper behavior.

Refactor move redirection

---

config/formats.js

Far too many low-ladder people get frustrated when they don't realize it's an inverse battle and get bopped by an opposing Ice Beam far too late.

Seasonal: Add message when beginning

---

chat-plugins/info.js
team-validator.js

This PR fixes [this][1] issue from the Bug Reports topic and employs @TheImmortal's suggested approach from #1877.
(Someone should attest that the refactor's execution speed is acceptable.)
[1]: http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/page-212#post-6214252

Refactor /ds to compile learnsets from prevos and certain baseSpecies

---

chat-plugins/info.js

This broke the team validator on event pokemon if it was running in the
same process as the commands
For example, the synchronous validators or if my single process hack was in use

Don't modify the original template when compiling learnsets for dexsearch

---

chat-plugins/wifi.js

People are often asking how to answer the GA. By adding in this small amount of text, it lessens the chance of them asking how to guess.

Wi-Fi plugin: remind users to use /ga to answer

---

data/moves.js

Turn 3 of http://replay.pokemonshowdown.com/aqua-tripleshackmonscup-1290
Heliolisk OKHO's Roggenrola so Mawile's Rototiller shouldn't have attempted to affect it. (I assume that Roggenrola had Levitate in order for the immunity to trigger.)
I checked the other moves that try to hit the field too (excluding pseudo weather of course).

Moves that hit the field should ignore Pokemon that have already fainted

---

chat-plugins/info.js

!statcalc gardevoir, spe 252+ scarf
Base 80 at level 100 with 31 IVs, 252+ EVs at +1: 427. (should be 426)
!statcalc gardevoir 252+ spe
Base 80 at level 100 with 31 IVs, 252+ EVs: 284.

Fix /statcalc to round between applying modifiers

---

commands.js

Sadly, no desktop notification will be created by user.popup().
Might add that, too, if I find a good way to do it.

Add popup for public room promotions and demotions

---

data/moves.js
test/simulator/moves/focuspunch.js

By setting a handler to listen for the Hit event, Pokemon will now lose
focus properly when attacked by multiple Pokemon or by Nature Power.
---
I'm still working on the Revenge etc. fixes and will submit that later, probably

Fix Focus Punch bugs

---

config/formats.js

As per [this post](www.smogon.com/forums/posts/6023381) which I missed earlier, Fake Out is limited to one user per team.

Implement "Fake Out Clause" for VoltTurn Mayhem

---

tournaments/index.js

This helps to avoid resetting various tour settings to what they already are.

Tournaments: prevent identical tour settings

---

rooms.js

This prevents the server from being able to make rooms with ids of: battles, teambuilder, rooms, ladder

Some roomnames shouldn't be allowed

---

data/abilities.js
data/moves.js

- Reverted 6603f97 (fixes interaction with Shield Dust)
- Moved Hit handler that changed the secondaries to ModifyMove for
proper interaction with Serene Grace when terrains are present
- Added a volatile that ensures that the first hit of Secret Power
under Parental Bond does not trigger its volatile
I need to verify that the secondaries that are set in certain terrains is indeed affected by Serene Grace, Is this true, @Marty-D?

Fix Secret Power interactions with various abilities

---

commands.js

Any search without results will currently give an empty popup.

fix /modlog popup for empty search results

---

data/scripts.js

Unsure if `targets[i].toString().substr(0, 3)` is the best way to get the target's location ID. 
This also has the side effect of also sending the pokemon on your side that gets hit from moves like Surf, Earthquake, etc. but I figured that's not a bad thing (they are targets of the attack, after all).

Pass list of hit targets with [spread]

---

battle-engine.js
data/abilities.js
data/moves.js

>The animation occurs on the user of Follow Me/Rage Powder, as if it was targeted. The user of redirection should not know which Pokemon was targeted initially, which is disclosed on PS due to the animation.
Not 100% sure if this is the best way to implement this, but it was the simplest idea I could think of. It's probably important enough for the doubles community to look at anyway.
Could possibly look to use this for https://github.com/Zarel/Pokemon-Showdown/pull/2438#issuecomment-192032470 too

Modify target sent when redirected

---

data/abilities.js
mods/gen4/abilities.js
test/simulator/abilities/normalize.js

Set all the moves that change type, such as Hidden Power,
Natural Gift, Judgment, and Technoblast, to change their
types within a volatile to guarantee proper interaction
with Normalize and all other effects.

Normalize overwrites moves that change type

---

battle-engine.js
data/abilities.js
test/simulator/abilities/angerpoint.js
test/simulator/moves/clearsmog.js

This fixes its interaction with Clear Smog because Hit handlers for
moves always activate before all other global event handlers.
Removed the Hit event from the list of events stopped by Mold Breaker
variants as there are no abilities that would be negated by it that
use that handler.

Refactor Anger Point to the Hit event handler

---

config/formats.js
mods/seasonal/moves.js

The switch-in and faint messages are last year's values, and Spectrum
Triplet Beam announces the three types used in the attack. (Also, the
three types used are now unique.)
http://www.smogon.com/forums/threads/super-staff-bros-melee-set-submissions.3566098/page-2#post-6690254 for the messages used. The signature move message was modified slightly.

Seasonal: Fix Ascriptmaster's messages and signature move

---

users.js

This wasn't actually the problem. Instead, they forgot to add their
reverse proxy to the config
This reverts commit d21ac1b76849bcd27410555774eb585b8eb156ea.

Revert "Workaround for unavailable IPs"

---

config/formats.js

Upon his request:
[14:54] #Eevee General: I moved it
[14:55] #Eevee General: why does my mon get muted when it dies lol
[14:55] NotRhythms L0LOLL: idk joim coded it
[14:55] NotRhythms L0LOLL: lol
[14:59] #Eevee General: how do I edit that
[15:00] #Eevee General: aka make a pull request
[15:00] NotRhythms L0LOLL: i can do it
[15:00] NotRhythms L0LOLL: if u want
[15:00] #Eevee General: "bye room" is supposed to be paird with "electrolyte is in charge"
[15:00] #Eevee General: 2 separate lines
[15:00] #Eevee General: inap! is it's own line
[15:01] #Eevee General: and is a separate occurrence
[15:01] NotRhythms L0LOLL: k
[15:01] #Eevee General: ty
[15:01] NotRhythms L0LOLL: and is it supposed to be muted
[15:01] #Eevee General: n
[15:01] NotRhythms L0LOLL: and when is it supposed to accure …

Seasonal: Fix Eevee General's faint messages

---

chat-plugins/poll.js

Before, if a button text spanned over one line, it would default to the OS buttons.
Using the button class with in-line CSS, this makes the buttons remain consistent regardless of how many lines the button spans for a poll question.

polls: Make button style remain consistent

---

chat-plugins/scavengers.js

The feature in question is for certain ladder gimmicks, and time should count from beginning of a hunt, rather than entering /joinhunt command.

Scavengers plugin: Time should be based on /starthunt time

---

battle-engine.js
data/abilities.js
data/items.js
data/moves.js

Changed `EatItem` to `TryEatItem` and adjusted calls in items.js
Cheek Pouch now triggers on the new `EatItem` event after `Eat`
Added the new `EatItem` event to Bug Bite, Pluck, and Fling so that Cheek Pouch will trigger
I agree to the MIT license.

Cheek pouch fix

---

data/abilities.js
data/moves.js
data/scripts.js

Any multi-strike move with the `multiaccuracy` property set to `true` will now check for accuracy before each hit.
I have no knowledge, however, of whether Triple Kick actually uses its accuracy for hits 2 & 3 (instead of hard-coded 90% chance of connecting the hit), and if it does, whether it uses the same accuracy for each hit instead of adjusting to current accuracy/evasion modifiers which may change between hits.
The latter concern also extends to other multi-strike moves. If the user of a contact-making multi-strike move was damaged by Rocky Helmet or other similar sources to the point where it ate its Lansat Berry, the critical bonus, which is applied in `onModifyMove`, will not apply to the remaining hits. I suspect that this is not the case on cartridge. There may be also other …

Implement Triple Kick multiple accuracy checks

---

battle-engine.js
data/abilities.js
data/items.js
data/moves.js
mods/gen2/items.js
mods/gen2/moves.js
mods/gen3/items.js
mods/gen4/items.js
mods/gennext/items.js
test/simulator/items/lansatberry.js

This allows for proper crit ratios when a Pokemon loses/gains an ability,
item, or other effect in the middle of a multi-hit attack.

Critical Hit Ratio refactor: Use an event to modify crit ratios

---

chat-plugins/datasearch.js

Right now the four pokemon classified as LC Uber appear in dexsearches with the parameter LC because they aren't manually entered into the banlist array.

Prevent LC Ubers being included in LC dexsearches

---

config/formats.js

Poking `typesData` was probably never the right thing to do anyway.

Fix ascriptmaster's type

---

commands.js

Useful for identifying poor users.
(PR in case there is a reason this is not already done)

Log IPs of locked users

---

data/scripts.js
mods/gen3/moves.js
mods/gen3/scripts.js
mods/gen4/moves.js
mods/gen4/scripts.js

The recoil of the 1/3 recoil moves in Gen 5-6 is 33% and rounded by ``Math.round``,
and the recoil in Gen 3-4 is 1/3 and rounded by ``Math.floor``.
(I don't know the recoil in Gen 1-2. Sorry.)
In Zarel/Pokemon-Showdown, the recoil was 1/3 long ago and changed into 33% about 3 years ago (See [this commit](https://github.com/Zarel/Pokemon-Showdown/commit/c195611628175c896076823a47a0b10accc00f72)), however the recoil in Gen 3-4 was changed into 33% at the same time.
So I changed ``moves.js`` and ``scripts.js`` to fix this bug.
Please check commits.

Fix recoil in Gen 3-4

---

data/formats-data.js
data/rulesets.js

Several shiny Pokemon are currently unobtainable in gen 6 games. Affects
formats with the requirePentagon flag

Check legality of shiny Pokemon obtained in gen 6

---

battle-engine.js
data/abilities.js
data/moves.js

<s>I should have done this from the start when Ascriptmaster proposed it</s>
Fixes the issue with animations playing on fainted targets in doubles/triples. Has no impact on any other targeting behavior that I can tell, or have found.
Example on turn 3: http://replay.pokemonshowdown.com/vgc2016-363124841

Alter |move| target on every target change

---

chat-plugins/info.js

The on-site FAQ and beginner's guide have been moved to a forum thread
to ease maintenance. This removes several entries from <code>/faq</code> because you
can't link to specific sections of a forum post. Unmatched targets now
link to the general FAQ post instead of giving error messages for
somewhat backwards compatibility with removed entries.

Update /faq and /intro

---

data/abilities.js
data/moves.js

Reference: http://www.smogon.com/forums/threads/3469932/page-265#post-6775149
It only mentioned Magic Bounce, but Magic Coat is doing the same thing.

Use the correct target when bouncing back moves

---

data/abilities.js
data/scripts.js
team-validator.js

The list of ability keys is still hardcoded in three places. The rest of the code already uses `Object.values`.

Always use Object.values(template.abilities)

---

team-validator.js

This simplifies validation for some OMs. As an example you could use it for *Head Start*:
validateSet: function (set, teamHas) {
let template = this.tools.getTemplate(Tools.getString(set.species));
template = Object.assign({}, template);
template.abilities = Object.assign({'G': 'Gale Wings'}, template.abilities);
return this.validateSet(set, teamHas, template);
}
or *Follow the Leader*:
validateSet: function (set, teamHas) {
if (!teamHas.leader) teamHas.leader = this.tools.getTemplate(Tools.getString(set.species));
let name = set.name;
let problems = this.validateSet(set, teamHas, teamHas.leader);
set.name = name;
return problems;
}
It could even be used for *Almost Any Ability* or *STABmons* (obviously the existing workarounds could then be remove from `team-validator.js`).

Allow validation against a custom template

---

commands.js

Before, if hotpatch was disabled it would still alert the staff room.  This commit moves that check up, allowing that to not happen and no longer checks for specific hotpatches.

hotpatch: make check if disabled faster

---

commands.js

To eliminate confusion, don't report private chatrooms where the user is
a player, such as in a tournament

Report private rooms separately in /query

---

data/formats-data.js

Reject Stone Edge with Rock Head + Head Smash
Reject Fire Fang with Head Smash
----
An alternate strategy for Fire Fang is to lock Tyrantrum to Rock Head if it has Head Smash, but I don't think that Fire Fang is useful enough without Strong Jaw. Maybe add Superpower (it's in its Scarfed set on Smogon) to its movepool as an option against Ferrothorn and maybe some other things the Fire coverage was dealing with.

Random Battle: Improve Tyrantrum

---

data/rulesets.js

Right now if your Pokemon has no nickname, this displays as undefined.

Fix Baton Pass Clause error message

---

battle-engine.js
data/abilities.js
data/scripts.js
mods/gen2/scripts.js
mods/gen3/abilities.js
mods/gennext/abilities.js

Originally this was regarding the following attack:
> The opposing Lapras used **Confuse Ray**!
> <sub>Lickitung doesn't become confused!</sub>
> <sub>But it failed!</sub>
The "But it failed" should not appear, since we already have the confusion immunity message. Additionally while looking into this I noticed that not only do most Ability immunities also simply cause the attack to fail, they don't even activate. I have therefore tried to add immunity activations for all of them. (This is untested as yet though.)

Show ability activation when it causes an immunity

---

command-parser.js

Modules compiled using node.js' addons API do not get added to
require.cache and will make /hotpatch crash if any of them happen to
have been required when it is called.

Fix crash in /hotpatch with compiled .node modules

---

data/moves.js

When trick, switcheroo, and bestow fail, their items are put back on the pokemon
they came from. However, the item object itself was being set, rather than its
id (as is done in thief).
This is causing request messages to be sent from server to client containing an extra object in the item field, instead of a string as expected.
For example (note Furret's item):
```
>battle-randombattle-47
|request|{"active":[{"moves":[{"move":"Trick","id":"trick","pp":15,"maxpp":16,"target":"normal","disabled":false},{"move":"Aqua Tail","id":"aquatail","pp":16,"maxpp":16,"target":"normal","disabled":true},{"move":"Knock Off","id":"knockoff","pp":32,"maxpp":32,"target":"normal","disabled":true},{"move":"Double-Edge","id":"doubleedge","pp":24,"maxpp":24,"target":"normal","disabled":true}]}],"side":{"name":" …
```

On failed takeItem, re-set item id instead of item object

---

chat-plugins/info.js

I was somewhat frustrated when I wanted to re-check room rank permissions while in lobby and was told I needed to go to a different room for that, despite not even trying to broadcast.
On the other hand, this will always let "+user123: !roomhelp" go through, instead of blocking the whole thing. As far as I can tell, this is not avoidable without non-trivially messing with the command parser. I think that is preferable to the way it is now, however.

Allow non-broadcasted use of /roomhelp in lobby/battles

---

data/scripts.js

Because it was available in `this.format`/`this.getFormat()` all along. (See the PotD code.)

Remove unnecessary format parameter to randomTeam

---

data/abilities.js
data/items.js
data/moves.js
data/scripts.js

- Oblivious now activates when you Attract the opponent
- Overcoat now activates when you use a Powder move (except Rage Powder, which is just silently ignored) unless the Pokémon has the Grass type
- Overcoat now activates when you have the Safety Goggles (previously Safety Goggles activated even for Grass types, but if that's correct behaviour (unlikely) then I can revert those changes)
- Own Tempo now activates when it cures you of confusion that you suffered while under the effect of Mold Breaker, or if your ability was changed into Own Tempo while confused
- Own Tempo doesn't activate for secondary confusion (including self-inflicted confusion)

Fix ability activation for Oblivious, Overcoat and Own Tempo

---

data/scripts.js

This fixes issues like getting Choice items on Pokemon with setup moves.
Also, paging @Marty-D to confirm that the use of `Object.merge` is correct since he dealt with it for the November Seasonal in 0d37b7946d38ae81c3e0c47020ad2ab0b18d90ac

Seasonal: Pass custom move sets into randomSet when generating teams

---

test/simulator/misc/decisions.js

+xfix: I'm too busy to update this, but if someone would be willing to fix https://github.com/Zarel/Pokemon-Showdown/blob/master/test/simulator/misc/decisions.js#L72 (should be j++, not i++), that would be neat.

Test: fix typo

---

data/formats-data.js

With balanced EVs, Landorus can still use its Physical movepool for
coverage thanks to its respectable base Attack, and Rock Slide is a
Rock-type move boosted by Sheer Force.

Random Battle: Add Rock Slide to Landorus-I

---

mods/enchanteditems/rulesets.js

Okay now Dusk Ball is recognized as an item which boosts speed. 
Thanks again to Quite Quiet

Fix Baton Pass Clause for Enchanted Items

---

commands.js
rooms.js
test/application/rooms.js
test/main.js

This allows room staff to perform moderation in tournament battles.
Build is failing for unrelated reasons.

Copy auth from tournament room to tournament battle

---

data/scripts.js

Due to the "each type combination only once" restriction, Normal-type teams had a non-negligible chance of having less than 6 members, as most of its type combinations are only used by a single mon which could easily be skipped due to tier restrictions or bad luck. The types were also not sorted before filtering, so it was entirely possible to have Fighting/Psychic and Psychic/Fighting on the same team, which undermines the whole thing.
So, this sorts before filtering, but raises the limit to 2 of each combination per team, which hasn't yielded any 5 mon teams across 10000 generated teams. Drought/Drizzle/Sand Stream are still limited to one.
For comparison, here's a bunch of Normal type teams from before http://hastebin.com/raw/menenijebi and here's after …

Make 5 mon monotype randbats teams way less likely

---

data/scripts.js

A variable that is increasing from zero should probably not be called "pokemonLeft". Since it's effectively referring to the current size of the team, might as well use `Array.length` (which was already being used over pokemonLeft in a few places anyway).

Replace confusing variable name

---

chat-plugins/datasearch.js

By having ``return`` here, the line ``room.update();`` never happens, so it gives the illusion that the server is lagging when it's probably not.

Datasearch: fix error reply lag

---

commands.js

(I admit to not having tested this: unfortunately I wasn't able to reproduce the situation on a local server :( )
Guest alts will always be unnamed and thus be put in square brackets, so this condition needs to be updated accordingly.

Fix collapsing guest alts in ban message

---

data/items.js

By setting `forceSwitchFlag` the switch doesn't happen until after all the damage is calculated, ensuring that all applicable boosts apply. There's an extra test in the case of two Red Cards (not that this would happen in VGC without some sort of Trick shenanigans).

Fix Red Card's interaction with spread moves

---

data/abilities.js

After 39ec460 Confuse Ray against Own Tempo started saying "But it failed!" again. By using `onTryAddVolatileStatus` the `null` return gets propagated back to `moveHit`; the `onHit` is still needed for the ability activation of course. Swagger (and presumably Flatter) still boosts and activates Own Tempo if it hits, assuming this is the desired result.

Fix Own Tempo's interaction with Confuse Ray again

---

commands.js

Many commands that add raw HTML to rooms don't use ``.update();``, which makes it look like they could be lagging or the server could be lagging.  By doing this, it makes sure that people will know right away when the server is entering lockdown mode, for example.

Make sure various commands don't appear to lag

---

mods/gen2/formats-data.js

I added Gen 2 Random Battle movesets for all fully-evolved Pokemon (plus Scyther), based on Smogon write-ups. This should seriously improve the quality of Gen 2 Random Battle mode, though of course it still needs some work.
Is "EssentialMove" a thing here the way it is for Gen 1 Random Battle? If so, I could go add essential moves for many Pokemon that could use them. If not, perhaps in the future I or someone else could look into programming it in. But that's for another day.
I hereby explicitly state that I agree to MIT license all of my submitted code.

Added Many Gen 2 Random Battle Movesets

---

data/scripts.js

Because `sort` modifies the array in-place, this breaks OMs such as Reliablemons or Cross Evolution that depend on having the types in the correct order.
While I was there I fixed a couple of cases that seem as if they should be sorting but weren't.

Slice template types before sorting

---

command-parser.js
commands.js
config/config-example.js
rooms.js

This is basically a system that allows for room moderators or higher to set a minimum time between a user's messages sent to the room.
This is especially helpful for times the server might be lagging or the chat is just moving much too fast.
Alternatively, this could also help to stop spammers in their tracks and give staff more time to handle them as well.
I got this idea from the suggestions thread:

Implement slowchat system

---

chat-plugins/trivia.js

- /trivia status no longer crashes if a username is provided as a target
- Timer mode no longer gives users scores of NaN
- /trivia start no longer displays that the game is starting in 30000 seconds, rather than 30
- Questions no longer appear as escaped html during games
- Corrected misleading documentation on why the noop methods of trivia exist.

Trivia: fix crash in /trivia status, fix other trivial bugs

---

command-parser.js
commands.js
rooms.js

Before, PS often relied on bots to handle moderating users who send messages that contained too many capitals or stretching.
This should be something that's preventative, not reactive, which is what this does.
Now, bots are no longer needed for these purposes as this allows stretching/caps punishments to be prevented, server-side.
edit; ALSO, I have implemented a roomsettings command in this PR.
editedit; jk that was a prank
(Special thanks to sparkychild for helping me come up with the stretching/caps checks!)

Implement stretching/caps checks

---

commands.js

Before, if a RO (not a global leader or up) tried setting modchat, it would say: "/modchat - Access denied for setting higher than +."
Now, this fixes that by checking what permission that user actually has in the room, as in if they're a roommod (up to +) or roomowner (up to #).

Modchat: Fix access denied reply

---

commands.js

Adding this command isn't a far step from the current permission global bots and roombots already have - it basically does what it says, allows bots to PM users HTML infoboxes.
If it's a roombot, then it can only do this to users who are actually in the room that the bot has a roombot rank in for additional precaution.  It checks if the user is ignoring PMs as well as if they're locked or not.
Overall, this could be a game changer for bot developers and this gives them *much* more possibility.
(Shout-out to SolarisFox for giving me this idea!)

Implement pminfobox command (for bots)

---

commands.js

There is a bug with these current checks that if a user object expires, and a user can talk, they can roomunban that user who has an expired user object.  This fixes those broken checks.

Fix broken roomunban permissions

---

battle-engine.js
simulator.js
test/main.js

This is my attempt at resolving #2655. Special thanks to Zarel for guiding me in the right direction.
This moves all the `process` stuff out of `battle-engine.js` and into `simulator.js`. It is worth pointing out that this includes `Battle.prototype.send` because it depends on `process`. I decided to make it an argument to construct. If there is a different preference, let me know.

Move IPC from battle-engine.js to simulator.js

---

chat-plugins/poll.js

I've experienced this problem before, and it's sometimes hard to replicate, but this should correct it.
The reason why this was a problem was that because of the ``return`` statement, the line ``this.updateTo(user);`` never actually happened, so it wasn't updating in one specific instance.
EXAMPLE OF BUG:

Polls: Fix not showing results on blank vote

---

users.js

Renaming from, say, Morfent❤ to Morfent used to add morfent to the user object's prevNames.

Users: don't add userids to user.prevNames on rename if it never changed

---

chat-plugins/info.js
commands.js

- The line that we're removing from pminfobox was checking a character limit, which isn't ideal when we're using HTML.
- The fact that bots can always use /addhtmlbox even when they aren't able to talk is a potential security issue, so we're adding a check to prevent that.

Fix issues with pminfobox & addhtmlbox commands

---

data/moves.js
data/statuses.js
mods/gen1/statuses.js
mods/gen2/statuses.js
mods/gennext/statuses.js

Interestingly @Zarel added the `TryAddVolatile` event when he originally added Confusion blocking to Safeguard in cdd3af0.

Prevent the Confusion status using TryAddVolatile rather than a custom event

---

chat-plugins/trivia.js
test/chat-plugins/trivia.js

This makes it possible to refer to globals normally defined in production in the
outermost scope of the trivia module without making unit tests throw.

Trivia: lazily load the trivia module in unit tests

---

chat-plugins/roomsettings.js

This command allows for all users to use /roomsettings.  If the user can actually change some of those settings, then they will have a button to do so; if not, it will tell them what the current settings are set to, though.
PREVIEW:

Implement /roomsettings plugin

---

config/formats.js

%kamikaze: http://www.smogon.com/forums/threads/np-doubles-ou-stage-4-infamous-jirachi-stays-in-dou-swagger-is-banned.3569913/page-10#post-6935868
%kamikaze: Swagger has been banned from Doubles OU
%kamikaze: so it would be great if someone can add Swagger Clause to it

Ban Swagger from Doubles OU

---

commands.js

/roomsettings apparently uses /slowchat false, and I guess that was never actually a thing...

Slowchat: Add false as an alias to disable

---

chat-plugins/roomsettings.js
command-parser.js
commands.js

This allows for better support to later add more formatting to this function.
Also, this fixes some mistakes with the stretching/caps commits as well as an oversight in the roomsettings plugin.

Refactor checkFormat check and fix various other stretching/caps mistakes

---

commands.js

A user might do ``/banword add  `` when trying to pull up the help command and accidentally end up banning spaces, this prevents that.

Banwords: Don't allow banning spaces

---

battle-engine.js
data/abilities.js
data/moves.js
data/scripts.js

Should probably work for Mega Evolving in Hackmons too.
The Gastro Acid change just changes the order of the messages; without it you would see
> Illusion's Ability was suppressed!
> Zoroark's Illusion wore off!
With it you see
> Zoroark's Illusion wore off!
> Zoroark's Ability was suppressed!
(No, I don't know which order they appear on in the cart, or even if you get both messages.)

Make Illusion wear off properly after Entrainment, Gastro Acid, Simple Beam or Worry Seed

---

commands.js

I'm not sure why these were here to begin with.

Remove tic marks from "memusage" alias

---

battle-engine.js
data/moves.js
mods/gen2/moves.js
mods/gen3/moves.js
mods/gen4/moves.js
mods/gen5/moves.js

Requires the client-side patches for `-activate` and `[silent]`.
* Gen5/6: Sends `-activate` instead of `-cureteam` so that the client only cures the individual advertised statuses.
* Gen3/4 Heal Bell: Sends `-activate`, and uses silent `-curestatus` because Soundproof Pokémon don't get cured, and cures aren't advertised.
* Gen3/4 Aromatherapy and Gen2 Heal Bell: Continues to use `-cureteam`.

Fix client-side activation of Aromatherapy and Heal Bell for all gens

---

users.js

This fixes a bug where if you lock a global ranked user, it looks as if they are still a global ranked user on the userlist and whatnot.

If CRISISDEMOTE is called, update user's identity

---

chat-plugins/info.js

In order to use ``/ipsearch``, the target must either be: a. A host, or b. An IP, or c. An IP range - all of which must include a period of some sorts... So, if the user doesn't use one, they're using the command wrong and should be displayed the help command instead of it searching anyways.

ipsearch: Specify no results found due to invalid search

---

chat-plugins/info.js

#Zarel: >No results found.
#Zarel: why is that red???
%panpawn: I don't know
%panpawn: it was red before that commit
#Zarel: Should probably be sendReply for "No results found"

ipsearch: Make "No results found." a sendReply

---

commands.js
users.js

This makes it so that when Users#setGroup is called, it looks slightly less hard-coded to be a whatever symbol a regular user is (should that symbol ever change)

When Users#setGroup is called, use Config ranks

---

commands.js

If there isn't a "development" room, then it will instead default to the "staff" room, if it exists.

Hotpatch: Inform development room on hotpatch use

---

data/abilities.js
data/items.js
mods/gen3/items.js

Rounding the priority also simplifies the code for Full Incense and Lagging Tail.

Quick Claw and Custap Berry should override Stall

---

chat-plugins/info.js

This lets regular users, or users who don't have permission to use !htmlbox to first test and validate HTML by using the same validation system PS uses across the sim for things like roomintros, for example.

Allow regular users to do /htmlbox

---

app.js
battle-engine.js
chat-plugins/datasearch.js
chat-plugins/mafia.js
command-parser.js
commands.js
data/scripts.js
mods/gen5/scripts.js
pokemon-showdown
repl.js
rooms.js
simulator.js
sockets.js
team-validator.js
test/application/rooms.js
test/application/simulator.js
test/application/users.js
test/chat-plugins/datasearch.js
test/chat-plugins/trivia.js
test/dev-tools/eslint/validate-conditionals.js
test/main.js
test/simulator/index.js
tools.js
tournaments/generator-elimination.js
tournaments/index.js
verifier.js

Resolves #2722
Motivation taken from #2722 
Suppose I want to use battle-engine.js in the browser and I have a webpack config that resolves es6 files with higher priority than js files. I can now override require('./crashlogger') in Battle.prototype.leave to my own implementation as I choose. I can use a similar method to create a tools.es6 that has all this.data built into it and define global.Tools for battle-engine.js to run in the browser.

Remove .js extension from requires

---

team-validator.js

Several OMs (e.g. VoltTurn Mayhem) want to limit the count of a particular property (e.g. Fake Out). They are forced to recalculate this every time, when in fact we're almost tracking this already.
In theory some sort of banlist syntax could then be created to handle this directly e.g. `banlist: ["Fake Out > 1"],` although I wouldn't want to start to write that without some consensus on what the syntax should be.

teamHas should keep count of how many of each property the team has

---

data/formats-data.js

Remove Healing Wish from Lilligant (useless) and Fire Punch from
Darmanitan (redundant and vastly inferior to Flare Blitz)
@TheImmortal

Random Battle: Minor moveset changes

---

chat-plugins/info.js

Before, if a user was perma locked or perma banned, it would show that their lock would expire in a negative time - this fixes that.
For consistency, I also added the check to the namelock check as well.

Whois: Don't display negative expire times

---

chat-plugins/datasearch.js
chat-plugins/info.js
process-manager.js
simulator.js
team-validator.js
test/application/process-manager.js
verifier.js

Before, an options object containing properties and values to be used
was how decorated instances of the class would be created. This meant
the constructor could assign anything you feel like to `this`. Rather
than that, the constructor now assigns a strict set of values, and
methods are redefined in subclasses.
Basic unit tests were added to test if they could be written for after
the final refactor to fix the other memory leak here.

ProcessManager: subclass to extend ProcessManager, unit tests setup

---

team-validator.js
tools.js

If your team fails to validate the Gravity + Lovely Kiss Doubles OU ban, the ban is actually reported as "Your team has the combination of gravity + lovelykiss, which is banned by Doubles OU."
I wrote this partly as a code simplification, but I suppose you might be worried by the potential run-time cost, in which case I have some ideas whereby I can implement a compromise approach.

Report complex bans using the original text

---

commands.js

It had the same message as a global unban; there was no way to tell the difference...

Fix typo in roomunban message

---

commands.js

Since the help lists /gb as an alias of globalban rather than /gban being the short alias..

Fix globalban help

---

messages.js

When this happens, the command acts like it gets sent twice... there's also no purpose when PMing yourself to have to broadcast the command.
EXAMPLE:

Don't allow users to PM broadcast themselves cmds

---

chat-plugins/info.js

This now makes it so that if a user can broadcast but cannot declare in that room, and they attempt to broadcast it, it will now send them the error reply themselves instead of broadcasting the error reply to the room.
Credits to Slayer95 for this fix!

Fix broken permission with /htmlbox

---

commands.js

This presents ghost guest nicks from appearing when logging out and renaming to
the user's guest nick and prevents being able to spam rename messages when
renaming to the user's current username.

Do not send rename messages when nicking to the user's current username

---

data/rulesets.js
team-validator.js
tools.js

As you can see, this can be used to simplify some of the rulesets, but OMs can also make use of this, for instance VoltTurn Mayhem could have `banlist: ['Fake Out > 1']`.

Allow the banlist to specify a numeric limit of team properties

---

chat-plugins/roomsettings.js

When this was converted to use template strings, this happened

Fix typo in /slowchat

---

team-validator.js

The line of code `if (toId(set.species) !== template.speciesid) template = tools.getTemplate(set.species);` was a bit of a hack because a ruleset could have changed the species after the default template had already been fetched. Fetching the default template later avoids this. (This is in fact only possible because of `Tools.getSpecies` which didn't exist at the time.)

Validate the template later once we know the real species

---

commands.js
punishments.js

This also introduces Punishments#roomUnblacklistAll to do the heavy lifting of this command.

Implement /unblacklistall command

---

chat.js

In one of the recent refactors, it dropped code like this that broke /reply to not work right

Chat: Fix /reply not working correctly

---

chat-plugins/info.js
chat.js
punishments.js

This also adds `Punishments#checkLockExpiration` - mostly for this, but also to remove some repetitive code in the whois command as well.

Chat: Tell locked users their lock duration

---

chat-commands.js

It would show access denied to those who can't mute in the room, and it would show nothing to say, drivers

Fix broken permission with /showblacklist

---

rooms.js

Personal rooms' log writing streams weren't being cleaned up properly.

Performance: fix memory leak in chatroom deletion

---

team-validator.js
tools.js

I'm probably using a sledgehammer to crack a nut here, but this allows formats to allow Pokémon, items, moves and abilities that have been banned or are unreleased. For instance, Itemize could add `overrides: ['Soul Dew'],` and otherwise remain an OU-based metagame, while Monotype could use the OU ruleset and override Deoxys-Defense, Deoxys-Speed and Landorus, as opposed to the complex banlist it currently enjoys.
I couldn't decide what to do about Genesect though; as written you need to override all five formes, as I didn't want to accidentally allow all Deoxys forms in Monotype for instance.

Allow formats to override inherited formats or rulesets

---

chat-plugins/roomsettings.js
tournaments/index.js

This was requested several times, as a lot of rooms have bots to allow drivers to run tournaments for them.
Note: current room settings for tournaments will not change by default; if you had your room set to allow mods and up before, that will still be the case unless you change it; same for if you had tournaments disabled all together.
This changes the command syntax for `/tournament enable` to be: `/tournament enable [%/@]`.  The command syntax for `/tournament disable` has not changed. (disabling a tournament will make it so only # and up can run tournaments.)
This also re-arranges the roomsettings rank order UI for tournaments; it only makes sense that the ranks go in order of power least to greatest (left to right).

Tournaments: Allow ROs to allow % and up to run tours

---

tournaments/index.js

The command syntax for the enable command has changed as of https://github.com/Zarel/Pokemon-Showdown/commit/8744e94a2d31c3947f7e053683b7c843c25a57e7 - this updates the help command to reflect those changes.

Tournaments: Update help command with new enable

---

chat-plugins/roomsettings.js

This makes it more consistent with the rest of the UI, specifically for the respected changes of filtering capitals / stretching.

Roomsettings: Don't use 'true' in UI

---

chat-commands.js
chat-plugins/hangman.js
chat-plugins/info.js
chat-plugins/mafia.js
chat-plugins/poll.js
chat-plugins/roomsettings.js
chat-plugins/thestudio.js
chat-plugins/trivia.js
chat-plugins/wifi.js

If a user was muted in a room, and then tried to do a command, it would send two replies: You are muted and cannot talk in this room. AND You cannot do this while unable to talk.
This makes it so that if you're using a command, it will use the specified reply, whereas if you're actually trying to talk, then it will use that reply.

Fix double errorReply while muted in some cases

---

team-validator.js

Addresses https://github.com/Zarel/Pokemon-Showdown/issues/2815#issuecomment-251421263
Happiness didn't exist in gen 1 as far as I know, so I assumed a set with happiness set would also be wrong for that generation as well.

Team Validator: Validate Happiness when set

---

data/rulesets.js
mods/gen1/rulesets.js
mods/gen2/rulesets.js
mods/gen4/rulesets.js
mods/stadium/rulesets.js

Banlists now refer to rules that affect validation and rule names are no
longer affected by Tools.getFormat input.
This is relevant to the supplementary banlist feature.

Rulesets: standardize types and names

---

data/abilities.js
data/items.js
data/scripts.js

- Ensure Sap Sipper runs before Safety Goggles (for non-Grass types)
- Overcoat and Safety Goggles should not trigger for Powder moves on Grass types
- Grass immunity to powder moves should run after Sap Sipper

Run Spore immunities in the correct order

---

chat-plugins/roomsettings.js

When setting modjoin to a setting higher than +, it says `Moderated join was set to ${target}! Only users of rank ${target} and higher can talk.`
I have changed this to `Moderated join was set to ${target}! Only users of rank ${target} and higher can join.`

Fix incorrect wording in modjoin

---

chat-commands.js

Before, `/mee` didn't used to allow for a target, as this could lead to impersonation.
Ex: `/mee 2 tests` - if you're name is bobbyuser, then it would appear as "bobbyuser2 tests" in the chat.

Mee: Filter out following text

---

chat-plugins/roomsettings.js

It doesn't make sense to me that drivers have access to /showbl but not for /banword list

Give drivers access to /banword list

---

team-validator.js
tools.js

As fb4066d showed, I made a right mess of extracting the unban code from my original override patch. Indeed, it misreports the error when you try to use a Mega forme which is in too high a tier. So, I thought I'd start over, in effect, via the following three commits:
1. Backout of fb4066d
2. Backout of 056e1a0
3. What I should have done in the first place, instead of trying to extricate the unban code from the override code.
Naturally the `tools.js` changes will disappear when the PR gets squashed together, as I did at least manage to get that bit right, but for the `team-validator.js` changes, the easiest way is just to look at 814f780.

Allow formats to unban inherited formats or rulesets

---

chat-plugins/info.js

In case of Trick-or-Treat or Forest's Curse, a pokémon can have three types. I updated the /weakness command to reflect that.

Added third type to /weakness

---

data/moves.js

Currently, PS will notify both players if Pursuit has been used regardless if it actually succeeds or not (like if something U-Turn and kill the pursuiter, you still get a message that shows they planned to use Pursuit). It's a somewhat minor information leak, but it should still be fixed.

Fix minor information leak with Pursuit

---

chat-commands.js

Before the semi-recent PM refactor, `/announce` /would/ work in private messages, this re-enables that functionality.

Enable announce command in PMs

---

config/config-example.js

The redirect command actually uses the 'warn' permission, and it seems as though this permission actually isn't a permission of any of the ranks currently.

Remove unused documented config-example perm

---

data/abilities.js

See http://replay.pokemonshowdown.com/rom-tripleshackmonscup-40052 (yeah I know it's not main but the code isn't *that* different...)
Turn 2, Emolga used Doom Desire on Klefki. Klefki fainted on move 4, so I brought in Volcarona. Emolga used Mega Kick on Volcarona because it knew it resisted Doom Desire, but it took the Doom Desire attack anyway. However Cursed Body then tried to disable Doom Desire, but ended up disabling Mega Kick instead.
I don't know what the cart mechanics are, so I'm assuming they're likely to be the same as Grudge and Destiny Bond which don't activate for future moves.

Don't let Cursed Body activate for Doom Desire or Future Sight

---

data/rulesets.js

Previous code had Aegislash complex banned from Steel teams hard-coded into the Same Type Clause. This complex ban hasn't been a part of Monotype for half a year and was conflicting with attempts to use "/tour banlist !aegislash" to allow Aegislash in Monotype battles. (I forgot to mention this in the commit, but Aegislash is appropriately globally banned, so this will still reflect the current banlist.)

Monotype Ruleset: Remove outdated Aegislash complex ban

---

chat-commands.js

This fixes a bug where it would show a blacklist infobox reply as if there were users blacklisted, even if there aren't.
Example screencap:

Showblacklist: Check size of room's blacklist

---

rooms.js

Much like we try to mirror the UI of modchat when it comes to slowchat, it should also be displayed upon joining a room, like modchat is.

Add slowchat message upon joining a room

---

data/abilities.js

Same crash occurred in Emergency Exit, but @TheImmortal fixed that one.

Fix crash in Wimp Out

---

config/formats.js

Eeevium Z was quietly banned from Little Cup the other day: http://www.smogon.com/forums/threads/plans-for-sumo-and-beyond.3586679/page-2#post-7089293
I think this is the first Z-move ban, but I'm assuming this is the optimal way to do it...

LC: Ban Eevium Z

---

data/scripts.js
test/simulator/moves/spectralthief.js

Merge only after https://github.com/Zarel/Pokemon-Showdown-Client/commit/c280c60671be767fe138a31026c3e0dbf13e4b78 is live

Spectral Thief should set boosts to zero on target despite abilities

---

chat-plugins/datasearch.js

Alternatively changing `oras` into `ora` works, but I thought this way was clearer.

Actually make /oraslearn work

---

data/scripts.js

`randomHCTeam` works by picking six random dex numbers, then a random legitimate forme for each number (so for instance it will only pick a mega in gen >= 6). Naturally, for past gens, some dex numbers have no legitimate formes, so we have to limit the maximum dex number somehow.

Allow Hackmons Cup for past gens

---

data/scripts.js

Z-Crystals don't affect Judgment's type, so an Arceus with Judgment as its
STAB should receive a plate only.

Random Battle: Fix Arceus item generation

---

chat-commands.js

-Doesn't assume regular rank is just a space
-Doesn't assume that the only room ranks that would give trusted status is driver-bot
-Uses more template strings
-Uses the new standard for a multiline help command format

Roompromote: Less hard coding & string standards

---

data/moves.js

Oops. (I can never remember which way around these go, and the fact that some of these handlers just use `pokemon` is even more confusing.)

Fix Burn Up's type test to work on the source, not the target

---

data/aliases.js

Un-breaks the teambuilder if someone decided to pick another version of either of these right now. Should maybe disable the option while there's no sprite for them, but if it's ever meant to work then this needs to be added either way.

Add Minior and Magearna form aliases

---

data/scripts.js

Because they can't get burned. Affects Flareon.

Random Battle: Give Fire-type Guts Pokemon a Toxic Orb

---

chat-plugins/datasearch.js

I don't think any of the other new `heal`-type moves count here.

Add Shore Up to the list of recovery moves searched by /dexsearch

---

data/moves.js

Encore should fail against Z-moves:
Encore will fail against a Pokemon that previously used a Z-move (LegoFigure11)

Fix Encore's interaction with Z-Moves

---

data/statuses.js

At least, it was added a09c011 in but not removed in 318ca6a (sadly this makes for some confusing diffs and the blame is now wrong).

Remove line of code that appears to be left over from Destiny Bond fix

---

chat-plugins/datasearch.js

This also seems to be the way /learn validates moves. 
Now I assume that "gen7ou" will just turn into "ou" at some point, would that break this? Or will we also switch to gen 7 as the base then, making this work just like /oraslearn works currently despite "gen6ou" not being a thing?

Fix /ds with 2+ moves as argument not working for gen 7 mons

---

data/rulesets.js

Monotype has extended the Baton Pass Clause and Evasion Clause to recognize and prohibit Z Moves that would violate them.
http://www.smogon.com/forums/threads/monotype.3587204/page-3#post-7105176
I'm assuming the name of the Monotype format will still be "Monotype" when the Gen 7 format is released.
Extended Baton Pass Clause Example: Disallow Z Celebrate + Baton Pass on Umbreon.
Extended Evasion Clause Example: Disallow Z Detect on Zapdos.

Monotype: Extend Baton Pass and Evasion Clauses

---

data/scripts.js

With the buffs to the healing berries that confuse if a Pokemon has a
conflicting nature, it is now possible for Linoone to use them as a
substitute for Sitrus Berry, if it has Gluttony as its ability.
In Random Battles, natures are always neutral, so the any of the berries
will serve this purpose.

Random Battle: Add possibility of Gluttony Linoone w/ Wiki Berry

---

data/moves.js

I checked and something using a slower contact move (e.g. Revenge) will not normally get burned, but if the move is Disabled earlier that turn then they will get burned, and shouldn't be, according to @Marty-D's comment on PR #2977, which sadly I don't seem to be able to reopen.

Don't burn attackers that hit after Beak Blast aborts

---

chat-commands.js

Only searches through the modlog of public rooms, excluding battles, groupchats, and the global modlog.
Since /modlog all should be avoided when possible, and most mods will probably only care about actions in public rooms, I think this is should suffice in most cases and it'll return way quicker. It will also not be cluttered up by people setting modchat in their battles and such, which can be a bit of an issue with /modlog all.

Support /modlog public

---

chat-commands.js
test/application/rooms.js

As per #2927. The test failed because the administrator was not named, which canTalk() checks for regardless of permissions.

Don't allow locked users to roompromote

---

chat-plugins/info.js

- It returns nothing in the case the user does not exist in the map, hence ``punishments.length`` crashes

checkpunishment: Fix checking for offline users

---

team-validator.js

Fixed move set for Skarmory, since they can't learn some moves through breeding until Pokebank is released.

Remove skarmory moves unavailable in gen 7

---

battle-engine.js
data/abilities.js

We have a shiny new `ignoreAbility` flag on a move. We can use this to simplify the code that tests for an active Mold Breaker clone, by getting the Ability to add the flag to the move, since then all we have to do is to check the flag. (Some moves already have the flag of course.)
As a bonus, this also simplifies the coding for several OMs, in particular Multibility, Partners in Crime and Pokébilities, as they no longer have to special case the Mold Breaker effect.

Simplify Mold Breaker clones by getting the move to ignore abilities

---

chat-plugins/info.js

The user object could of just not yet expired, but they also might not be online, which is why this is necessary

Checkpunishments: Mark truly offline users only

---

chat-plugins/datasearch.js

Also removed /g6learn, which is now made redundant by `/learn pentagon,gen6,...` and didn't work anymore anyway.

Expand help entry for /learn

---

team-validator.js

This is so that /learn5 rejects event moves that are only available from events with level >5.
Also, this would crash if template.eventPokemon[learned.substr(2)] doesn't actually exist, which I assume can only happen through inconsistent or malformed data. Is it worth calling the crashlogger in that case? I'm asking because the same is true for line 868 and there's no check there either.

Make learnset searching check for event levels

---

chat-plugins/room-faqs.js

And also indent them like the rest of the multi-line help commands across the repo

Roomfaqs: Remove trailing whitespace in help cmd

---

chat.js

This checks for if there are missing strong, marquee, or blink tags

Check for more missing tags in this.canHTML

---

CONTRIBUTING.md

Because squash-merge is a thing now, we probably don't have to enforce this as heavily as we used to.

CONTRIBUTING.md: Make squashing optional

---

chat-plugins/info.js

This makes it so that `/om mix` finds (e.g.) `Mix and Mega` while `/om gen` only finds (e.g.) Gen-Next OU. `/om gen1` still works of course.

Don't match against generation prefix if it wasn't provided

---

chat.js

Currently, it floors everything, so 47 hours turn out as "1 day", which is confusing for everyone. It was also inconsistent with Punishments#checkLockExpiration(), which does regular rounding. Locks showed up as "2 days" and roombans as "1 day" despite roombans lasting longer.

Make duration strings use rounding

---

chat-plugins/info.js

I made a former pull request with the same name however during code alterartions I made a mistake while rebasing, so here's the code that was in my last commit. Which had the following description: Added servertime chat command that shows the current server time.

Add servertime command

---

CONTRIBUTING.md

This statement kind of contradicted that rebasing was optional...
Also, I guess we never mentioned anything about duplicate pull requests specifically, and we probably should since this has happened a lot in the past.

CONTRIBUTING.md: Don't open duplicate PRs 

---

chat-plugins/wifi.js

Changes made to cause proper parsing for Alolan forms, allowing for the
giveaway to render the gif for the target form by using 'Pokemon-Alolan'
as well as 'Pokemon Alolan'
Without the change use of '/lg User, Pokemon-Alolan' and '/lg User, Pokemon Alolan' show:
With the change added, gif properly displays.

WiFi Room Giveaway: Fix Alolan Form GIF Display

---

battle-engine.js

This was mentioned on the bug reports thread somewhere - Focus Punch's effects were applying even when it was actually All-Out Pummelling. Presumably Beak Blast has a similar problem.

Z-Powered Focus Punch shouldn't have special Focus Punch behaviour

---

config/formats.js
data/formats-data.js

http://www.smogon.com/forums/threads/goons-and-balloons-suspect-gothita-banned-drifloon-still-banned.3589986/page-3#post-7165483

Banned Gothita and Drifloon from Gen 7 LC

---

mods/gen1/scripts.js

SpA and SpD use the same DV, and HP DV is calculated using the 4 other DVs.
In-game, the DV range is [0;15], each point giving 2 points in the stats, so to simulate that we make every DV a multiple of 2 in the [0;30] range.

[Gen 1] HP and SpD DVs

---

data/moves.js

It was unclear what it meant by "the target cannot use items for 5 turns". I thought it meant items like berries had no effect for 5 turns. I felt the need to clarify, so I thought we should change it to: "For 5 turns, the target's item has no effect."

Update embargo's short move description

---

data/scripts.js

Fix Mega Mewtwo levels.
Fix limits on the number of Ubers per team.

Random Battle: Fix Various Issues with Ubers

---

data/scripts.js

In case of boosts, the attacking animation would play 1st, stealing the
boosts last, instead of the other way around.
This approach was chosen since Spectral Thief is the only move that
steals boosts this way, for now

Properly animate Spectral Thief

---

chat.js

Added /addbannameword and /deletebannameword commands, which allow ROs to add phrases (e..g 'harambe') to the rooms list of banned name phrases. Users that have that phrase in their name (e.g. HarambeTheGreat, hiharambe, etc.) will not be able to join the room. Also prevents users from changing their nickname in a room, if their new name would contain such a phrase (e.g. changing from CheeseMuffin to harambeeeee).

Added room banned name phrases

---

chat-plugins/trivia.js
test/chat-plugins/trivia.js

This isn't very easy to reproduce, so I can't properly test any fixes yet.
Trivia#broadcast writes to debug monitor rather than throwing if called after
the game instance destroys itself.

Trivia: mitigate game end/question timeout race condition

---

data/scripts.js

At the moment, it doesn't properly account for Bank-Uber tiered Pokemon, resulting in matches like this : http://replay.pokemonshowdown.com/gen7randombattle-515699799
Also updated the comments to match the changes.

Random Battle: Prevent generating teams with too many Uber Pokemon

---

test/application/rooms.js

This left behind 7 users in Users.users before.

Tests: clear all users created during rooms.js tests

---

team-validator.js

When validating against a custom template based on Ash Greninja with added moves, the code was switching back to a stock Ash Greninja. (Note that the OMs with custom validation will still need work to get this right, but this at least makes it possible.)

Only switch to Ash Greninja if we're not already using a custom template

---

data/formats-data.js

- All Bugs that learn Leech Life and had X-Scissor on their sets have
X-Scissor replaced by Leech Life.
- Add Earthquake to Buzzwole and Armaldo.

Random Battle: Update Bug-type Pokemon

---

data/scripts.js

Reject Hex entirely if Will-o-Wisp is not present, to prevent it on the
same set as Shadow Ball.
Reject Fire Blast with Flare Blitz.

Random Battle: Improve move rejection for dual STAB issues

---

config/formats.js

This bans Metagrossite, Hoopa-Unbound, and Baton Pass.
[21:22] @scpinion: yo, do you ahve a minute?
[21:22] %panpawn: yes
[21:23] @scpinion: TI is away this week. Can I get you to PR the recent monotype bans?
[21:23] %panpawn: uh
[21:23] %panpawn: ok, i can try
[21:24] @scpinion: we banned metagrossite, hoopa-unbound, and baton pass
[21:24] %panpawn: ok

Update Monotype bans

---

data/abilities.js

Adding the [msg] kwarg actually prevents the proper message from
displaying.

Fix Minior Shields Down Message

---

data/moves.js
data/scripts.js
mods/gen6/moves.js

- Powder should not activate if Burn Up fails due to being the wrong type
- Powder should activate before Primordial Sea (according to a forum post I read somewhere)
While I was there I made Dark Void only fail once instead of once per hit (affects Doubles battles).

Fix interaction between Burn Up, Powder and Primordial Sea

---

data/abilities.js
data/moves.js

Bug in action: [Replay - Turn 4](http://replay.pokemonshowdown.com/gen7pokebankou-523522946)
Proof that is really a bug: [Other Mechanics - Bullet point 15](http://www.smogon.com/forums/threads/pokemon-sun-moon-battle-mechanics-research.3586701/)
Dark-type Pokemon are now immune to moves affected by Prankster that target them. (yeah wtf?) (UltiMario) This immunity does not extend to ally Dark-type Pokemon. (OmegaDonut) Prankster Spikes, hazards, weather moves, and Trick Room are not blocked (raikoo)but Prankster Defog is. (UltiMario) **Dark-type Pokemon with Prankster will be affected by status moves bounced back with Magic Bounce/Coat. This is the case even if the Magic Bounce/Coat user is Dark-type.** (UltiMario) Prankster Assists is blocked by Dark-types even if it calls an attacking …

Reflected moves shouldnt be boosted by Prankster

---

data/formats-data.js

Vullaby, Pawniard, and Ferroseed were listed as "new" which made them show up as Banned in the teambuilder for LC. If you want to add the "new" tag back in addition to LC that's fine, but this at least is a good fix atm that won't confuse people.

Changed Vullaby, Pawniard, and Ferroseed tiers

---

data/formats-data.js

It's a relatively weak move with no coverage and the measly 20% confusion isn't worth it at all.

Random Battle: Remove Rock Climb from Lycanroc-Midnight

---

data/moves.js
data/scripts.js

Sacrificial moves behave differently in terms of whether the user faints when the move fails, further complicated by the requirement that the user always faint first in case of damage-dealing moves. The current implementation of these behavior is confusing and prone to errors. 
- Moves that always cause the user to faint once the move is initiated (Explosion, Selfdestruct) are determined by checking targets, because they happen to be both spread moves. Therefore, spread sacrificial moves always behave this way, while single-target ones always behave like all other existing sacrificial moves. Move data has no control over this behavior. Furthermore, when a sacrificial, single-target damaging move fails due to lack of target, the battle crashes.
- Final Gambit fainting is hard-coded in …

Refactor fainting from sacrificial moves

---

chat-commands.js

Autojoin for side servers is failing because the user is in 2 rooms when the server gets its autojoin request `global` and `lobby`. I tried resolving this client side but could not get it to send the autojoin before adding the room lobby (also not sure if having lobby at the end of the room list is desirable). This is probably not enough because it dosen't restrict it to just global when on main, but i'm not sure how to check if the server is main from the server side. I opened this as-is so Zarel could take a look considering hes usually in PS dev room after I leave at night during the week.

Handle forced autojoin of lobby on side servers

---

config/formats.js

Extreme Evoboost is already included in the CFZ Clause code

formats.js: Remove redundant ban in BH

---

data/formats-data.js

Kingdra moved from OU to UU
Scolipede moved from BL to OU
Charizard-Mega-Y moved from BL to OU
Clefable moved from OU to UU
Mantine moved from OU to UU
Salamence moved from BL to OU
Volcarona moved from BL to OU
http://www.smogon.com/forums/threads/initial-gen-7-uu-banlists-updated-in-post-38.3591784/page-2#post-7219329

Usage-based tier updates

---

data/scripts.js

EV values are balanced now, so it's better to base it on the number of
attacks.

Random Doubles: Fix Level Scaling for Parental Bond and Protean

---

battle-engine.js

As reported here: http://www.smogon.com/forums/posts/7219391
Gale Wings Supersonic Skystrike still works of course, but this stops Z-moves from being affected by Triage if they were based on a draining move.

ModifyPriority should run on the Z move if relevant

---

data/rulesets.js

A Pokemon can only use 1 Z-Move in battle.

Fix Z-Move validation in Baton Pass Clause

---

.gitignore

I doubt this adds much value to anyone but myself but the omission of certain files (such as config/) is a pain to deal with if using showdown as an NPM dependency.
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

Adds .npmignore

---

mods/gen1/moves.js
mods/gen1/scripts.js

Another Gen 1 issue that I know of but I don't know how to fix right away is that Counter should be able to bounce back damage dealt to a Substitute. Right now, Counter is failing in these cases in PS.
A less important issue is the interaction between Substitute and partial-trapping moves. In particular, if the first of these moves breaks a Substitute, the damage of the following attacks should not be the damage dealt to knock out the Substitute, but the damage that the attack would've dealt had the target not had a Substitute up. This anomaly in the damage also applies to the interaction between Substitute and Counter.
Pointing those out in case someone wants to look into them.

Gen 1: Three minor bug fixes

---

test/application/sockets.js

Until the crashes and workers' flooding of stdout are resolved.

Sockets: temporarily skip unit tests

---

battle-engine.js
data/scripts.js
prng.js
test/common.js
test/main.js
test/mocks/Battle.js
test/mocks/Battle.spec.js
test/simulator/abilities/flashfire.js
test/simulator/abilities/multiscale.js
test/simulator/abilities/unaware.js
test/simulator/misc/random-teams.js
test/simulator/misc/statuses.js
test/simulator/moves/destinybond.js
test/simulator/moves/ragepowder.js
test/simulator/moves/roost.js

This PR does a few things.
- Extracts the pseudo-random number generator that was embedded within `Battle` to it's own class named `PRNG`.
- Removes the reliance on a global `BattleEngine` property in tests so we can add a reliable mock without causing action at a distance. This is only required in a couple of places and I was able to replace this with a `require` instead. I am unsure if this will cause side effects (action at a distance seems to be a running theme), but all tests pass.
- Removes the duck-punch that caused `test/main.js` to overwrite the `BattleEngine.init` method and forcibly set it's own `this.seed` and `this.startingSeed` properties (Which are no longer necessary due to the `PRNG` class).
- Adds a mock class called `Battle` inside `mocks/Battle.js` that is created by …

Refactor PRNG into its own class and clean up test usages of randomness

---

chat-plugins/scavengers.js

Changed "/scavenge <em>guess</em>" to "/scavenge _______" in the /scavengerhelp command. Especially considering UGM is beginning effective today-ish, helps make the command more clear to new users and get them acclimatized to the room. There has been recurring issue for a long time of new users believing that they need to type "/scavenge guess [their answer]" instead of "/scavenge [their answer]," the latter of which is correct.

Change to /scavengerhelp

---

dev-tools/users-utils.js
room-battle.js
rooms.js
sockets.js
test/application/rooms.js
test/application/simulator.js
test/application/sockets.js
test/application/users.js
test/chat-plugins/trivia.js

Should fix the problems with the tests that were brought up in #3215:
- Fix crash when constructing mock sockets in certain cases
- Properly prevent workers from writing to stdout
- Fix race conditions in workers-related tests that were causing false
positives

Sockets: fix unit tests

---

chat-plugins/room-events.js

This adds a room-managed room-specific events plugin that allows rooms to keep track of upcoming room events.
This is multipurpose and could be helpful to multiple rooms; may it be tournaments or upcoming sports games, this would be helpful in many use-case scenarios.

Implement room events plugin

---

data/scripts.js

Even if you don't like lower tiers banning things like Drizzle, I must insist on Power Construct, Shadow Tag, and passing speed + another stat being considered Uber, or at least above OU in some way. Level 83 Smashpass Gorebyss was just plain unfair last gen, and so is level 75 Zygarde-Complete this gen.
Also, while I was laddering to try and make sure that this was really a problem and I wasn't just imagining it, I noticed that unreleased megas are getting the levels of their weaker base formes in every case, such that Mawile-Mega is running around at level 79. If I'm not mistaken, these megas will be tiered as OU to start when they get released, and their Randbats level should reflect this.

Random Battle: Improve level balancing

---

chat-commands.js

- check the actual html only in ``this.canHTML()``;
>-  prevents false positives of broken HTML such as ``/pminfobox sparkych<i>ld, <em>oops! :^)</em>``
>- prevents HTML exploitation such as ``/pminfobox SAO full <div>e, </div>Time to think outside the box ;)`` from working
- use proper blockpm permissions - staff can bypass the pmblocks, and excepted users (``/blockpms`` allow a ``target`` for groups to be whitelisted)
- staff __should be__ able to send pminfobox's to locked users as well.
- template strings!

Fix permissions for pminfobox

---

chat-plugins/room-events.js
chat.js

This PR is more of an "update" to fix room-events.
In response to the new [roomevent plugin][1], I've noticed that it's specifically done to allow HTML in the field for the events, and uses ``this.canHTML()`` to check in the ``/roomevents add`` command.
- adds the new tags to be checked for in ``this.canHTML()`` to prevent people from breaking the table and inserting more interesting things outside of the table.  This could potentially create impersonation of staff (having Zarel say funny things can always be a fun pastime in groupchats [surprisingly roomevents is allowed in gorupchats too!])
Example:
- [] always exists. Join date with ``"|"`` before checking if it exists.
[1]: https://github.com/Zarel/Pokemon-Showdown/blob/master/chat-plugins/room-events.js

Fix HTML and date field check in room-events

---

mods/gen2/moves.js

- Don't use multi accuracy setting
- Set multihit between 1 and 3 randomly, as it has been mentioned in the issue https://github.com/Zarel/Pokemon-Showdown/issues/3239 (scripts __should__ automatically do a random distribution if the ratio is not between 2 and 5)

Fix Triple Hit mechanics in Gen 2

---

users.js

Prevents permalocked users from getting freed due to a previous trusted status.
- notifies side servers about newly permalocked users easier, and prevents further issues/crimes from being committed.
- doesn't free permalocked users anymore on side servers to commit more crimes.

Prevent permalocked users from getting unlocked

---

tools.js

When parsing happiness, (`Number(misc[0])`) if `misc[0]` is an empty string, (undefined, which normally points to 255) `Number` will parse that as `0`. This fixes that. This bug only occured when a pokemon had hidden power, and it was a set type (ex: Hidden Power Water not Hidden Power). And only really came up when the pokemon had return too.

Tools: Fix happiness parsing bug

---

data/moves.js

[Example](http://replay.pokemonshowdown.com/gen7anythinggoes-542021819) on turn 7

Fix Switcheroo not removing statbar item note when no item received

---

chat-plugins/scavengers.js

This extra space was introduced in https://github.com/Zarel/Pokemon-Showdown/commit/549c1f89f2b9d2f813ae7114fe489ba248fe106d when changing this line to use template strings.
Also, add a new line back to the end of the file.

Scavengers: Remove extra space in UI

---

mods/automagic/scripts.js

This should fix the substitute crashes in the automagic OM, by checking if the move does hit a substitute and avoiding several checks if it does.

Fixed substitute in automagic

---

data/formats-data.js

All Pokemon/formes not released at the beginning of a generation should be OU by default unless specified otherwise by the OU council.

Add tiers to Mega Beedrill and Mega Mawile

---

data/abilities.js

`runMove` marks the move as undancable, which is wrong for the original move.

Multiple Dancers should be able to copy Dance moves

---

punishments.js

Seems to have led to at least one case of accidental lock evasion.

Fix locks not locking logged out users by id

---

chat-commands.js

Before and after that change → https://puu.sh/uKnD3/0235163ed7.png (basically, the username of the invited person would be left blank)

Fix /invite on inviting a non-global auth to Staff

---

config/formats.js

In 7f7ac97 @TheImmortal removed Hidden Type's custom mod; unfortunately that meant that it switched to Gen 6 mechanics, so this switches it back to Gen 7 again.

Make Hidden Type a Gen 7 format again

---

chat-plugins/trivia.js
ladders-matchmaker.js
rooms.js
test/application/rooms.js

These are the last place process.nextTick should be used. Also fixes
BattleRoom's unit tests.

Prevent JSON writers from being able to block I/O

---

battle-engine.js
data/rulesets.js
package.json
room-battle.js
rooms.js
test/common.js
test/simulator/misc/choice-parser.js
test/simulator/misc/decisions.js

Hi, I'm making a pullreq for this change so everyone who works on the battle engine will see this.
Basically, the choice API is changing (again). This is relevant for test writing and other things.
Going forward, I'm thinking our tests should use a function like `makeChoices` which would look something like:
```js
battle.makeChoices(`pass, switch 5`, `move 2 mega, auto`);
```
which I think is much more readable than
```js
battle.p1.choosePass().chooseSwitch(5).foe.chooseMove(2, null, 'mega').chooseDefault();
```
So far, the changes are:
- `side.choose*` are no longer chainable, and no longer auto-commit (i.e. they will no longer auto-continue the battle if all choices have been made)
- `side.chooseSkip` has been merged into `side.choosePass`
- `side.chooseDefault` has been renamed …

Change choice API

---

test/application/ladders-matchmaker.js
users.js

Challenges and searches weren't being cleared properly after moving
them out of `GlobalRoom#onLeave`.

Matchmaking: fix crash on user disconnect/merge

---

battle-engine.js

The targetLoc validation was blocking the decision when the target type was "Adjacent Foes" and the targetLoc was 0, despite the decision being fine.
As far as I can tell, it's impossible for a targetLoc of 0 to be invalid, since (I assume) it picks one of the possible target locations by itself later in the code anyway.

Fix adjacent foe-targeted moves in singles

---

config/formats.js

This fix allows pokémon using the aforementioned moves/abilities (e.g. Ditto) to activate setup moves when triggering secondary effects.

Fix imposter/transform/mimic in Automagic

---

chat-plugins/uno.js

Makes the black text visible in dark mode.
Makes yellow easier to read in bright mode (second line is old, first line is new):
Makes blue easier to read in dark mode:

UNO: Improve colored text readability

---

chat-plugins/uno.js

- Forgot changing ``this.topCard`` affected the same card that was in the discard pile as well.
- Declare colour changes as something else.
- Better error messages to accommodate for this in terms of what you can and cannot play

Fix Wild cards taking on another colour in discard pile

---

chat-plugins/wifi.js

GTS Giveaways can take an hour or more. Removing ability for voice users to perform this style of Giveaways. Discussed with @bumbadadabum

Remove voice ability to host a GTS GA.

---

chat-plugins/wifi.js

Allow user to check number remaining in GTS giveaway by using the /left command with no arguments. 
Make broadcast capable so voices can easily answer the "how many" question.

Allow user to check # remaining in GTS GA

---

rooms.js

Before UNO, chat room roomgames never had players so running ``room.game.destroy()`` wasn't absolutely necessary.   This pull request does the same check to chat rooms that happens in roomgames for battle rooms, and destroys games, and removes them from the ``user.games`` map when a chatroom (or more specifically a groupchat that caused the crash on PS) is removed from the ``Rooms.rooms`` object.
Fixes the following crash:
```
CRASH: TypeError: Cannot read property 'game' of undefined
at User.rename (/home/ubuntu/workspace/memes/users.js:587:28)
at CommandContext.trn (/home/ubuntu/workspace/memes/chat-commands.js:3469:8)
at CommandContext.run (/home/ubuntu/workspace/memes/chat.js:292:28)
at CommandContext.parse (/home/ubuntu/workspace/memes/chat.js:138:19)
at Object.Chat.parse …
```

Rooms: Get rid of roomgames when destroyed

---

chat-plugins/scavengers.js

General
-------
- use RoomGame API for scavengers
- added queuing of games
- added a timer command for scavenger hunts
- allowed the hunt's host to view their hints/answers, and to edit them after the hunt has started
- display the hunt to users joining the room, if they're not already a player in the hunt
- checks IP and prevents users from joining and finishing a hunt several times simply by changing their userid
- support more than 3 questions for scavengers for potential events (approved [but not requested] by scavenger roomauth, although still with some debate)
Requested
---------
- split help command into 2 different sections that can be called independently 
- split the old /scavengerstatus into /scavengerstatus and /scavengerhint
Refactored
----------
- (Entire game system with …

Scavengers: Refactor and add new features

---

chat-plugins/uno.js

This allows for users to be highlighted on their turns (currently a big problem) and also allows users to know if it's their turn in cases of disconnections (the current code does not).

Add per turn highlighting to UNO

---

room-game.js

Right now, RoomGame.MakePlayer doesn't pass the current game to RoomGamePlayer, causing line 27 to cause a crash (all other room games [like Trivia, Scavengers, Uno, and Battles] currently have their own players/MakePlayer function, but one that does not have its own player would need this to be fixed).

Fix MakePlayer

---

chat-plugins/uno.js

- Add suppressing of game messages
- Default suppress game messages in rooms not named "game corner"
- Add additional commands to start public/private forced games
- Added command ``/uno suppress`` to toggle suppressing of games mid-game
- Added commands ``/uno spectate`` and ``/uno unspectate`` to allow people in the room to view the [private] game.
- Announce if a UNO game is public or private at start.
- General fixes
- Change default timer to 60 seconds
- Use ``'single quotes'`` in place of double quotes in a few places
- Put cards belonging to any eliminated player (through disqualification) into the discard pile to avoid cards being lost (for those who want to count cards)
- Clear the discard pile whenever shuffling the deck to prevent messing up the total count of the cards
- …

UNO: Add suppressing and general fixes

---

chat-plugins/scavengers.js

[No comment] Sorry about this
Fixes a previous (hasty) pull request.

Scavengers: join completed using a `,`

---

users.js

- prevents onConnect from being called twice in onUpdateConnection AND in joinRoom for autojoin.
Controlled crash stack showing ``onConnect`` being called twice through autojoin:
```
CRASH: Error: onConnect
at ScavengerHunt.onConnect (/home/ubuntu/workspace/suppress/chat-plugins/scavengers.js:137:9)
at ChatRoom.onConnect (/home/ubuntu/workspace/suppress/rooms.js:1369:51)
at User.joinRoom (/home/ubuntu/workspace/suppress/users.js:1181:9)
at User.tryJoinRoom (/home/ubuntu/workspace/suppress/users.js:1143:25)
at CommandContext.autojoin (/home/ubuntu/workspace/suppress/chat-commands.js:1334:13)
at CommandContext.run (/home/ubuntu/workspace/suppress/chat.js:292:28)
at CommandContext.parse (/home/ubuntu/workspace/suppress/chat.js:138:19)
at Object.Chat.parse …
```

Users: fix RoomGame connection update

---

chat-plugins/roomsettings.js

- Style
- Use template strings entirely throughout the file.
- Consistency: always put a space between buttons in roomsettings display
- &lt;b&gt; => &lt;strong&gt; - I know this has been contraversial before in https://github.com/Zarel/Pokemon-Showdown/pull/3247, but for the sake of screen-readers and consistency with the style in the newer files (which discourage the use of &lt;b&gt;, &lt;font&gt;, and &lt;center&gt; elements)
- Additions:
- roomsettings section for UNO and hangman
- Fixes:
- Banwords:
- Fix crash from ``/banword add ,`` - if there's no match don't map
- Remove banwords in ``/banword delete`` only
- Make the modnote for adding/removing multiple banned words less misleading.

Roomsettings: Add UNO/Hangman and general fixes

---

chat-commands.js
chat-plugins/uno.js
room-battle.js
room-game.js
users.js

- prevents users from being unable to rejoin games if they ``/logout`` (the server will rename you back to your guest account if you use /logout, thus barring re-entry or re-joining to certain IP limiting room-games)

Room-games: dont rename players to their guest accounts

---

data/scripts.js

This fixes the Z-Weather Ball interaction with weather. As far as I'm aware, every other type-changing move retains their base typing with Z-Moves, so Weather Ball should be the only exception here?
There might be a better way than to rely on Weather Ball's `onModifyMove` to resolve the typing, but without reimplementing it again, I don't know how.

Fix Weather Ball Z-Move

---

data/scripts.js

This lets Zygarde-10% activate Power Construct in two subs, and also simplifies some unnecessarily complex code.

Random Battle: Improve HP evs

---

chat-plugins/uno.js

- only ``|c:|`` notifies, ``|c|`` apparently doesn't

UNO: give notifications for highlights

---

chat-commands.js
ladders-matchmaker.js
rooms.js
test/application/ladders-matchmaker.js
test/application/rooms.js

For now, logging should be dealt by the global room until logging can be
abstracted away from it. This makes it simpler to refactor the logic in
`Matchmaker#startBattle` to be handled by `Rooms.createBattle` where it belongs.

Matchmaking: move battle logging back to Rooms.global

---

data/scripts.js

Fixes http://www.smogon.com/forums/posts/7087130
I'm not entirely convinced this doesn't break anything else, but it passes all the tests...
```
Turn 1
Liepard used Magic Coat!
Liepard shrouded itself with Magic Coat!
The opposing Sableye used Will-O-Wisp!
Liepard bounced the Will-O-Wisp back!
(In gen 7, Dark is immune to Prankster moves.)
It doesn't affect the opposing Sableye...
Turn 2
Liepard used Thunder Wave!
(In gen 7, Dark is immune to Prankster moves.)
It doesn't affect the opposing Sableye...
The opposing Sableye used Will-O-Wisp!
(In gen 7, Dark is immune to Prankster moves.)
It doesn't affect Liepard...
Turn 3
The opposing Sableye's Sablenite is reacting to Quite Quiet's Mega Bracelet!
The opposing Sableye has Mega Evolved into Mega Sableye!
Liepard used Thunder Wave!
[Opposing …
```

Fix Prankster and Magic Bounce interaction

---

test/chat-plugins/trivia.js

Using internal module API to require the Trivia module is insane when it's
very simple to do without it. The trivia room is deleted after the tests
finish, and users are now destroyed properly.

Tests: import the Trivia module in a sane way, clean up users/rooms

---

chat-plugins/scavengers.js

- allow % and up to view what the scavenger points are set at, but only allow RO's to set
- use ``staffHostName`` instead of ``staffHostId`` to preserve formatting of the staff member's name in the display.
- split ``/scav setpoints`` with ``","`` instead of ``", "``
- remove extra ``'`` at the end of the modnote for ``/scav setpoints [values]``

Scavengers: Partially lower permissions, fix display

---

chat-plugins/scavengers.js

- dont stop giving points at the 6th user for official hunts, but base it on the number of places that get points instead

Scavengers: Fix flexible point distribution

---

config/formats.js
data/rulesets.js
team-validator.js

This makes them compatible with custom banlists in tournaments. Unfortunately, adding `'Allow One Sketch'` will add Sketchmons' banlist for sketch moves, but I think that's better than the alternative, which is forcing the maker of the tournament to ban moves like Extreme Speed outright. On the other hand, that's not as much of a problem for AAA, so tournaments that add that ruleset will more often prefer to just ban abilities as a whole rather than be forced to use AAA's banlist, I think.

Refactor nonstandard banlists into rulesets

---

data/scripts.js

Previously, `moveid` would contain the specific type of hidden power such as `'hiddenpowerfire'`, but the switch statement would check for `'hiddenpower'`, and thus Hidden Power would never be rejected.

Random Battle: Correctly handle Hidden Power and Baton Pass

---

team-validator.js

In commit e8b60c1e908b2ea27a120caa8b1325d22ac7b1e4 this line was apparently lost which made sure Special Attack and Special Defense IVs were the same in Gen 2.
This closes #3459 I believe.

Gen 2: Once again combine SpA and SpD DVs into the same value

---

data/rulesets.js

Previously, only CAP Pokemon were allowed to hold Crucibellite, even in CAP, and they've apparently been able to hold Berserk Gene and other Gen 2 items this whole time.

Don't tie ability and item legality to a Pokemon's tier

---

data/moves.js

- Liquid Voice + Perish Song will get absorbed by Storm Drain/Water Absorb
- Electrify Perish Song will trigger Lightningrod/Motor Drive/Volt Absorb
- ~Prankster Perish Song will fail against any Pokemon on the field affected by Psychic Terrain, except the user.~
I couldn't find anything that said the redirecting effects of Storm Drain/Lightningrod activated for the effect of Perish song, though.
@Marty-D can you confirm if this is the correct behaviour for Perish Song now? Or if something else is wrong.

Implement correct Perish Song mechanics

---

data/scripts.js

Reported here with video: http://www.smogon.com/forums/posts/7335549
Obviously they need the appropriate Z-crystal so this is a bit niche, but it does mean that Mew can't use Genesis Supernova after a Transform, even if it still happens to have Psychic.

Z-moves should use Imposter/Transformed species

---

chat-plugins/roomsettings.js

Based on how we do stretching/capitals with the "off" language for being disabled, these should probably use that, too.
Also, "enable" and "enabled" were inconsistent, so this changes that, too.

Roomsettings: Make UNO and Hangman text uniform

---

chat-plugins/uno.js

- announces the presence of a game when a user joins the room.  Players will immediately see their hand instead.
- wild cards will cause the top card display to inherit the changed colour
- retain the ``/uno spectate`` message even after the game starts.

UNO: Add onConnect message

---

data/formats-data.js
data/scripts.js

Wiki Berry and the like are so good in doubles that Gluttony is worth it for them, even without Belly Drum. Simple, on the other hand, is actually a detriment without any setup moves. Also, there are no Pokemon with both Marvel Scale and Psycho Shift, so I'll assume that's an error caused by copy/pasting from Magic Guard.

Update Random Doubles

---

data/scripts.js

Two turn move attacks should not fail when target faints and be redirected.
Attacks like solarbeam and fly should have their turn of charge (1st turn) and not fail if targets faint (healing wish), then redirect attack to new target for the next turn.

Two turn move

---

sim/dex-data.js

- caused weather effects passed in through ``moreData`` to be marked as simply ``"Effect"``
- as a result, sandstorm and hail will damage Rock/Ground/Steel and Ice types  respectively
- this fix makes ``Effect`` inherit the ``effectType`` from ``moreData`` if it doesn't exist in the primary ``data`` variable passed into the constructor

Effect: don't override inherited properties from moreData

---

sim/dex.js

Use the result's name first instead of inexact search term if search is found.

Dex: fix dataSearch

---

chat-plugins/info.js
sim/dex.js

This restores the "No Pokémon, item, move, ability or nature named 'cn' was found. Showing the data of 'cm' instead." message, but continues to show you the data of "Calm Mind" as originally intended.
(Out of interest, the reason ROM was getting it "right" was because its `dataSearch` also returns the Dex object which was giving it the correct name, so I've double-checked this on a dummy server.)

Properly report a near miss for an alias

---

sim/dex.js

This makes them work in `dataSearch` again.
Also included are some leftovers from the fix in PR #3525 - if we're not going to report matched aliases then we can remove all of the support code for reporting matched aliases.

Give Natures a Generation

---

app.js
pokemon-showdown
sockets.js

app.js already is the main module when using the launch script due to
the way the module's required. This also removes `exports.listen` from
app.js, since the launch script was the only place where it was used.
`Sockets.listen` no longer takes a bind address and number of workers to
use, since those parametres were entirely unused.

App: do not spawn double the workers when using the launch script

---

sim/battle.js

In generation 1-4, during Link/Wifi battles you know how many pokemon your opponent has before all Pokemon have been revealed. PS currently doesn't at any point (without team preview) reveal the max number of Pokemon that your opponent has unless it's 6. This fixes that.
Relevant client change as well: https://github.com/Zarel/Pokemon-Showdown-Client/pull/915

Send team size at the start of battles

---

room-battle.js

Using 'inactive' made the client think the timer was on when it wasn't.
This one's on me, I should have paid more attention to that.

Use correct message for timer cooldown notices

---

mods/gen2/statuses.js

Pokemon.toString() looks like ``p2a: Name`` while Pokemon.id is just ``p2: Name``. This means that the latter does not uniquely identify a pokemon when their names are the same. Because of this, the client could spew error messages because it tried to animate a pokemon with the same name that had fainted already. Example: http://replay.pokemonshowdown.com/gen2ou-569298289 turn 23.
The fact that the Standard GSC/RBY rulesets don't include Nickname Clause somewhat facilitated this, I don't know if that's intentional or an oversight.

Gen 2: Use more specific pokemon ids in para/sleep messages

---

sim/dex-data.js

For example, Toxic would still do damage after being healed by Hydration. Basically the same bug as with the weather damage regression.
What does PureEffect represent anyway? An effect without side effects?

Fix statuses still being effective after being removed that turn

---

data/scripts.js

Moves without PP would be skipped entirely, making the canZMove array come up short in those cases, causing the button positions to not match up in the client, making the client send invalid Z move choices.

Fix mismatch between Z moves and base moves

---

data/abilities.js
sim/battle.js

This is mainly on the off-chance that [Dancerability ](https://www.smogon.com/forums/threads/3600658/) wins LC/OMotM, in which case it will want to be able to extend the illusion-breaking event.
This works because we can make the ability Unbreakable which means that it gets the AfterDamage event even when the attacker has a Mold Breaker clone.

Move Illusion-breaking out of the battle engine

---

data/abilities.js
mods/gen6/abilities.js

The description for Refrigerate claims it has been updated to the 1.2x boost applied in Gen 7, however the value is still set to the 1.3x from previous generations

Fix Refrigerate Boost

---

chat-plugins/scavengers.js

- Display answers with capitalization
- answer submission is still matches ``.toLowerCase().replace(/[^a-z0-9]/g, '')`` (alphanumeric characters)
- Anti-merged accounts
- identify the number of connections that are connected to that user's account at that point, and kick the player that's involved and make them impossible to rejoin, alert staff and give 1 infraction point automatically
- Show completed/joined hunts count for users. - /scav playlogs
- cumulative count
- infraction count
- joined/finished count
- history kept for 6 months
- /scav infract/uninfract command - increases infraction count for record purposes in /scav playlogs
- some display improvements
- refactor of leaderboard
- selective methods of sorting
- code styling: some double quotes to single quotes
- reword reply for …

Scavengers: Refactor Leaderboard, add new functions

---

config/formats.js

We were already copying Zygarde's stats if it had Power Construct and was before the Uber in the team, although this is unlikely as Zygarde would probably have been put last.
While I'm here I noticed ROM now seems to count Rayquaza + Dragon Ascent as Uber rather than AG, so if it's buggy, you'll probably want to use `Uber + AG + Power Construct > 1` instead.

Don't allow Power Construct with another Uber

---

mods/gen4/formats-data.js

The way LC bans work is that anything that's naturally tiered by usage has to be explicitly banned but otherwise bans use the LC Uber tier.

Really ban Meditite from Gen 4

---

chat-plugins/datasearch.js

It's using Gen 7 tiers but the Gen 6 banlist...

Dexsearch should use the Gen 7 LC banlist

---

mods/gen1/formats-data.js

Exeggcute can't learn Mega Drain in RBY. I didn't notice it when I made the randbats movesets. Thanks to Mirabel_ for pointing it out in Smogon: http://www.smogon.com/forums/threads/gen-1-and-tradebacks-dev-post-bugs-here.3524844/page-13#post-7382821

Gen 1 Randbats: Fix Exeggcute getting Mega Drain

---

mods/gen5/scripts.js
mods/gen6/scripts.js

As described [here](http://www.smogon.com/forums/posts/7382966/) the randbat generator doesn't take the Gen 5 hidden power BP calculation into account, so it will happily reduce the BP of hidden power by 2 to save a couple of points on the Attack stat. Indeed, for those Pokémon which get both Hidden Power and Trick Room, it will happily reduce the BP by 6 or 7, or potentially even change its type entirely. The latter applies to Gen 6 as well; it should also apply to Gen 7, but the server cheats and pretends that reverse bottle caps exist, and I can't be bothered to fix it.

Require minimum IVs for Hidden Power 70 in Gen 5

---

mods/gen4/abilities.js
mods/gen4/items.js
mods/gen4/moves.js
mods/gen4/scripts.js
sim/battle.js

Inspired by the chain of events in this thread: http://www.smogon.com/forums/threads/bugs-that-directly-influence-the-outcome-of-a-game.3603259/#post-7347664
Basically, while later generations implement most of their modifiers on damage (such as boosts by items, abilities, etc) in one place in the damage calculation, Gen 4 does this in several steps. This creates small discrepancies between expected damage output and PS damage at Level 100, and these become more significant as levels decrease, becoming potentially game-determining at Level 5.
I based the code on http://www.smogon.com/dp/articles/damage_formula which is what the PS damage calc is based on. I made the changes within the context of PS's event system, basically just adding clones of ModifyDamage (ModifyDamageOne and …

Implement DPP damage formula

---

config/config-example.js
repl.js
room-battle.js
sockets.js
team-validator.js
tsconfig.json

- `Config.repl` enables/disables using REPL sockets since it doesn't
make as much sense to configure whether or not it's enabled with the
`REPL_ENABLED` const
- `exports.start` takes a filename parametre rather than a prefix and a
suffix one to avoid having to mutate parametres
- dead REPL sockets are removed from the sockets list when the server
emits an error, and the server closes on error now before respawning
- made the file ready for Typescript
This should be committed after #3605 since this is dependent on `crashlogger.js` being in Typescript.

REPL: add Config.repl, refactor, Typescript

---

crashlogger.js
dev-tools/globals.ts
tsconfig.json

Depended on by numerous other modules to be moved over to Typescript
before they can.
This also adds `Config` to `dev-tools/globals.ts`. I left all of its exports as being `any` type for now. Later, I could add a namespace to `dev-tools/globals.ts` to properly type its exports, since I'd rather not make the types and interfaces local to `config.js` needed for `Config.ssl`, `Config.nodemailer`, and `Config.groups` global by handling the types in `config.js` and adding the interfaces I can't put in the file to `dev-tools/globals.ts`. Alternatively, I could write a type declaration file for it, but it might be too soon to start thinking about those.

Typescript: crashlogger.js

---

chat-plugins/modlog.js

Orda-Y pointed this out; basically, it should be like this "since hidden rooms still give roomlog access"

Modlog: Fix when to link in modlog output

---

rooms.js

As this would make the modlog permission checking overly complicated.

Prevent rooms from being named "all" or "public"

---

dnsbl.js
tsconfig.json

This is the last module I care about moving over to Typescript before having to write type declarations for sockets.js' dependencies.
I had to use `{function(any): any}` syntax instead of `{(id: any) => any}` for function parametres. I'm not entirely sure why `tsc` is complaining about it.

DNSBL: Typescript

---

crashlogger.js
repl.js

`err` is meant to be `NodeJS.ErrnoException` instead of `Error` in this case, but `// @ts-ignore` will have to be used for now

REPL: fix a couple of Typescript errors I missed

---

mods/gen4/items.js
mods/gen4/moves.js

Mentioned in #2367 and with the recent damage formula changes, I had hopes this would've been included but apparently it was forgotten after I mentioned it.
This may not be the best way to implement it though, but it's the best I can come up with that isn't even more hardcoded.

Gen 4: Fix crash damage interaction with Chople Berry

---

chat-commands.js

This allows for staff to add a proof field that is hidden from the user but on the same line in the modlog for their lock/ban reason.

Allow for hidden lock/ban spoiler proof message

---

mods/gen2/scripts.js
mods/gen2/statuses.js

Closes #3229
- Applies item modifiers when relevant
- Gen 2 doesn't have a damage rolls for confusion damage
I double checked this as best as I could with the code from https://github.com/pret/pokecrystal/ so hopefully this should be correct. I don't know if there's someplace else to turn to for this now that Marty stepped down.

Gen 2: Correctly calculate confusion damage

---

punishments.js

This fixes the following problems:
- Users frequently get locked and weeklocked in two different places.
What punishment they end up getting depends on which is applied first
- Namelocking weeklocked users reduces the duration
- Autolocks could potentially reduce punishments

Prevent weak Punishments from overriding stronger ones 

---

PROTOCOL.md

I added a link to my chatbot in protocol.md. I just started commenting the code, so it isn't well documented yet, and I still have to clean some stuff up, but it can still serve as a guide or a base for anyone who wishes to create their bot, learn with an actual example how PS works, and more. Since it's written in Lua, which none of the examples yet use, I thought it could be a nice addition to the list. I plan on making battles available in the future, but I'm afraid that's a feature worth of a summer.

Added link to another chatbot implementation

---

config/formats.js
data/formats-data.js

...it got lost at some point?
This also means that we can take all of the LC Uber Pokémon out of the banlist, and move those that aren't LC Uber into the LC Uber tier, at least until they gain a higher tier by usage.

Put LC Uber back in the Gen 7 LC banlist

---

chat-commands.js
config/config-example.js
room-battle.js
rooms.js

This allows for when the server is in lockdown, and the final battle finishes, for the server to automatically kill itself.

Automatically kill server on 0 battles in lockdown

---

mods/gen4/formats-data.js

Was prompted to do this by this battle: https://prnt.sc/fjzpt4
Quickly scanned the file for other double-ups and also found Crobat, so fixed that too.

Gen 4 Random Battle: Remove move double-ups

---

app.js
pokemon-showdown

Brought up in https://github.com/Zarel/Pokemon-Showdown/pull/3536#issuecomment-308049780. I don't think it'd be feasible to install the dependencies and import newly recreated config files from app.js because of how much  of a hassle that caused with the launch script trying to accomplish the same thing.

App: create default config file in launch script

---

chat-plugins/datasearch.js

i.e. `/ms priority>1` will now not include moves with priority 1, for example.

Fix inequality operators in /ms to not include equal values

---

chat-commands.js

Normally when you do /owner it gives 'did you mean /roomowner or /globalowner?' However global room owner doesn't exist as owner is a room only rank. This PR fixes this issue.
Sorry for the bad pr name, I'm still kinda new to contributing here.

Add a check for Room only ranks

---

mods/gen4/scripts.js

So after going through various sources on the Gen 3 damage formula, I've realized that this small check is basically the only difference between damage calculation in gens 3 and 4. The only other difference is that a small group of moves which double in power in certain situations have that x2 modifier calculated in a different place than in Gen 4, but that change can be made within the context of the gen 4 formula, so I don't see a reason to write a different ``modifyDamage`` for Gen 3. Hooray for old gen implementation.
Sources:
http://upcarchive.playker.info/0/upokecenter/content/pokemon-ruby-version-sapphire-version-and-emerald-version-damage-calculation.html
https://github.com/pret/pokeruby/blob/9640df02dd8651d5b05cf3767f6c7e16a697db3b/src/calculate_base_damage.c

Gen 3: Implement correct damage flooring

---

mods/gen2/scripts.js

This is a bug I introduced in my Gen 2 randbats update. It was making nicknamed Cubone, Marowak, Pikachu and Ditto not to receive boosts from their signature items. With this fix boosts are properly handled both in randbats and in other Gen 2 tiers. Sorry for the inconvenience.
Thanks to @urkerab for bringing this to my attention.

Gen 2: Fix items like Thick Club on nicknamed Pokemon

---

data/formats-data.js

It's commonly used on its sets and can help with trapping.

Random Battle: Add Pursuit to Alolan Muk

---

chat-plugins/uno.js

Previously, if a player was DQd during the color selection of a wild card, players would only be able to play black or wild cards. Uno has no proper rules handling disqualifications.

Uno: wild cards default to the color of the top card when DQd

---

chat-plugins/info.js

Linking to a Smogon format analysis containing /ubers would give a wrong link in the current situation

Fix /smogdex interaction with Ubers

---

ladders-matchmaker.js

Previously matchmaking range was smaller for Gen6 formats, however the most popular formats are Gen7 formats.

Make matchmaking range smaller for Gen7 formats

---

.eslintrc
.travis.yml
README.md
app.js
chat-commands.js
chat.js
dnsbl.js
fs.js
ladders.js
loginserver.js
monitor.js
package-lock.json
package.json
pokemon-showdown
punishments.js
rooms.js
test/main.js
tsconfig.json
users.js

This replaces the fs module with a new abstraction layer.
The new abstraction layer looks slightly different:
```js
// new
const data = await FS("package.json").read();
// old
fs.readFile(path.resolve(__dirname, "package.json"), (err, data) => {
...
});
```
as you can see:
- PS-style API: FS("foo.txt").write("bar") for easier argument order
- Promises (seriously wtf Node Core what are you thinking)
but also:
- ability to turn off all filesystem writing (for unit tests)
- paths are always relative to PS's base directory
- `mkdirp` - make a directory and all the parent directories necessary to make it
- `readTextIfExists` - suppress "file not found" errors and read as string
- `onModify` - like `watchFile` but only calls callback for modifications
- `rmdirIfExists` - suppress "directory not …

Replace fs module

---

repl.js

This stops npm from throwing an ELIFECYCLE exception when receiving a
SIGHUP/SIGINT termination signal on the main process.

REPL: exit cleanly on SIGHUP/SIGINT

---

chat-commands.js

This makes it consistent with the behavior or /blacklist.

Don't trigger CrisisMonitor for nameblacklists in secret rooms

---

app.js
chat-plugins/datasearch.js
chat-plugins/modlog.js
process-manager.js
room-battle.js
team-validator.js
test/application/process-manager.js
tsconfig.json
verifier.js

- spawning and setting up child processes is now handled by
`ProcessManager#constructor` rather than needing to be done manually for
each module that uses `ProcessManager`
- direct references to `ProcessManager` in `ProcessWrapper` were removed to
prevent dead `ProcessWrapper` instances from being leaked when hotpatching
- `process-manager.js` and `verifier.js` now use Typescript

ProcessManager: refactor, fix memory leak, use Typescript

---

data/moves.js

Persistent now affects Room moves introduced after Gen 4 as discussed here: http://www.smogon.com/forums/threads/cap-updates-fidgit-discussion-complete.3602772/

CAP: Update Persistent

---

chat-plugins/scavengers.js

- add history and such to the player leaderboard
- make leavehunt count as a joined hunt, but not as a completed hunt
- allow hosts to be offline for official scavenger hunts (for collabs, events such as point rally where there are many hosts, but some may just be offline during the event)

Scavengers: Enhance leaderboard and leavehunt, allow offline hosts

---

process-manager.js

Doesn't break hotpatching anything related to battles this time!
`ProcessWrapper`was holding on to references to `ProcessManager` after its
process had been killed and it had been removed from `ProcessManager`'s
list of processes, keeping it on the heap. Not good. This removes all
references to the wrapper's manager when disconnecting its process,
allowing it to be GCed.

Process Manager: fix memory leak in ProcessManager#unspawn

---

rooms.js

Game Freak releases new formats quite often, and updating client is somewhat problematic. This introduces backward compatible way for the client (clients unaware of this functionality will just ignore this flag) to know whether teambuilder should set Pokemon levels to 50.
The reason to not have a generic solution is that's unlikely there will be need for different levels than 50, and level 5 formats are usually called LC, so it isn't really an issue for them either.

Inform the client when format's level is 50

---

chat-plugins/modlog.js

Non-rg modlog uses FS while rg modlog uses its own cwd setting, and they were running off different working directories, making use of relative paths difficult, This changes rg modlog to also use PS' main dir as working directory, so we can use the same paths for both.

Fix /modlog all when using ripgrep

---

users.js

check via permissions instead of symbols 
- compared to before, this allows bots to enter the staff room - @Zarel if you do not desire this, I can add ``&& !Config.groups[this.group].addhtml`` to keep them out

Users: isStaff compatibility with custom ranks

---

chat-plugins/info.js

Currently you always get "Fling: This item cannot be used with Fling." when getting details for items in Gen 2/3, instead there should not be any Fling details since Fling was not introduced until Gen 4.

Don't show bogus Fling message in Gen 2/3

---

config/formats.js
mods/gen3/formats-data.js
mods/gen3/scripts.js
test/simulator/misc/random-teams.js

Adds scripts and movepools for Gen 3 Random Battles. Only fully evolved pokemon will appear, so only they got movepools. Also activates tests for gen3 and 4 randbats (since 4 was not turned on earlier).
Smogon Thread: http://www.smogon.com/forums/threads/random-battle.3600389/
Testable on http://spacialgaze.psim.us/

[Gen 3] Random Battles

---

users.js

Unlike any other rank, the admin rank dosen't inherit anything, but instead has `root: true`. When checking `Config.groups['~'].lock`, this comes out to false because of the lack of said inherit even though root gives full access.
EDIT: Ready to merge

Admins are staff too

---

data/moves.js

If you try to get details for a specific type of Hidden Power then you're told it's in Gen 0 (or CAP).

Typed Hidden Power should be Gen 2

---

chat.js

Pokemon Showdown automatically multiplies move's PP by 8/5, and for practical purposes, it's that value that is meaningful, not the base PP of a move which nobody will be using competitively on Showdown.

Multiply PP in move data

---

config/formats.js

It's been a while since I updated the format, and from the few tournament games we've played in Ruins of Alph, everything looks balanced and stable to me. In fact, I'm confident to say that it's more stable than Gen 3 RB right now. I think Gen 2 RB is the only RB format that is not in the ladder already, so I see no reason it shouldn't be there.

Gen 2 Random battles: Push format to ladder

---

chat-plugins/othermetas.js

without `&& !template.isMega`, it still gave uber megas in the first argument the error message about them not being able to mega evolve non natively even though they cant be used in real play at all

fix more error messages in /mnm

---

dev-tools/globals.ts
fs.js
monitor.js
tsconfig.json

Typescript doesn't care whether or not the globals' modules are
actually valid Typescript or not since `globals.ts` isn't required by any
modules. This makes it much easier to get more modules moved to
Typescript since most of the remaining ones are dependent on users.js
and rooms.js, which are also dependent on them.

Typescript: declare all globals, fix FS error, monitor.js

---

chat-commands.js

When a user is spamming, often times they are doing so under several accounts.  When this happens, a staff member has to manually hide each alts messages in the room, which takes up one line of the chat for each alt.  By doing this, it automatically does it on the same line as the lock  message at the same time, which both clutters up the chat less and makes it easier on the staff
PREVIEW:

Add /hidealtstext command

---

data/moves.js
mods/gen1/moves.js
mods/gen2/moves.js
mods/gen3/moves.js
mods/gen4/moves.js
mods/gen5/moves.js

As reported [here](http://www.smogon.com/forums/posts/7428552) for example.
Gen 1 allowed anything except Metronome itself and Stuggle, while Gen 2 had the start of a banlist, and Gen 3 added Mirror Move, which had previously been allowed, while Gen 5 added Nature Power and Snore which had previously been allowed. This means that we still need overrides for the banlists in Gen 1, Gen 2, and Gen 4, so as to allow the moves banned in later gens, but overrides for other gens can be removed.
The other approach would be to add noMetronome as a flag on the appropriate moves (c.f. noSketch in Gen 2), which would mean that allowing Mirror Move in Gen 2 or Nature Power and Snore in Gen 4 would just be a case of overriding that flag for those moves.

Fix Metronome calling Gen 7 moves in Gen 6 battles

---

chat-plugins/modlog.js

This will prevent the classic waiting for modlog and accidentally clicking it away

Modlog: Make popup modal

---

chat-commands.js

I guess I didn't realize the difference between prevNames and alts, now I do.

Hidetextalts: Make it actually hide alts' messages

---

sim/dex.js

It's not correct as far ES2017 specification is concerned (try running `Object.values({a: 1, __proto__: {b: 2}})`), and Showdown requires Node.js 7 anyway

Remove Object.values shim

---

chat-plugins/scavengers.js

Commas turned out to be problematic for many reasons, in particular list answers where users could have submitted answers with commas as separators - and if staff member didn't notice the commas, the hunt could be easily started with wrong answer to frustration of a room. This is the reason why this commit entirely disallows commas.
During the policy discussion with room staff, it was decided that `;` was the best alternative separator. The other options that were voted for were `/`, `\` and `,,`, but they weren't anywhere near as popular as a semicolon.
Also for consistency with answers, list of hosts was changed to also allow `;` as separator. However, there is no real reason to stop accepting `,` here. Neither of `;` and `,` is allowed in usernames so there is no problem with accepting …

Change Scavengers multiple answer separator to a semicolon
