smogon/pokemon-showdown

data/moves.js
Because I had the past gen Metronome code in `data/moves.js` which expected ids, and didn't notice the subtle difference when I copied the generation-testing code for PR #3781.
=> Fix mixup between moves and ids in Metronome

loginserver.js
This has a couple tradeoffs:
- this can't function without `Symbol.toStringTag` and `Symbol.species`
since subclassing `Error` makes some of the subclass' instances' properties
get overridden by its own ones. Symbols allow overriding them with
values `TimeoutError` would normally have without `Error` interfering
- `TimeoutError#toString` doesn't include the error message to make
stringifying `TimeoutError` instances function more like other errors do,
but this can be changed back if wanted
=> Login Server: make TimeoutError a subclass

punishments.js
If there were less than 12 hours left on a lock, it would display as (expires in around 0 days).
If there are 12 hours or less left on a lock, this will instead display the number of hours remaining rounded
=> Punishments#checkLockExpiration: Don't show 0 days

chat-commands.js
This makes accidentally up-arrowing after using one of these commands less "lethal".  The user will have to go through the 2 layers again before the command executes.
=> Remove lastCommand check after the command goes through

mods/gen4/formats-data.js, mods/gen4/scripts.js
I relaxed the bulk requirements for Leftovers on 3-attack sets because DPP has
a lot of defensive-oriented Pokemon that don't want a Life Orb but didn't meet
the 285 cutoff, like Weezing, Quagsire, and Nidoqueen. The extra check for fast
bulky Pokemon with recovery is to avoid taking Life Orb away from stuff like
Roost Zapdos that has good bulk but doesn't mind the recoil nearly as much.
=> Gen 4 Random Battle improvements

data/formats-data.js
Turns out there is indeed some of these that are not LC but indeed CAP NFE's so I will make this a rank to clarify the difference.
In tandem with: https://github.com/Zarel/Pokemon-Showdown-Client/pull/974
=> Add "CAP NFE's"

data/rulesets.js
Seeing as Allow CAP clause is built in the Pokemon Clause I had to add it there, but this should make it where they are considered Illegal in all tiers Allow CAP is not legal.
Thanks to Marty for pointing this out to me.
=> Add CAP LC and NFE to the Allow CAP clause

chat-plugins/uno.js
- Make UNO button be there every turn, so it's less of a "reminder" for the players to hit when it comes out
- fix some HTML escaping I had left out previously
- add a 0.75 second delay for the uno button to get pressed
- (chat filter uses up 600 ms, and the rest (150) can be used to process.  The command will be queue'd regardless so it will run after the 600 mark)
- make it fairer for players to get UNO in, and to make UNO bots not broken af when it comes to sniping users at UNO
=> UNO: make uno less subtle, allow player to uno before next player plays.

config/formats.js
Should have been done when https://github.com/Zarel/Pokemon-Showdown/commit/b91c3cff905de36ceb6aac4aefb8b387d734bd41 got added.
=> Remove pokemon rule from formats.js

chat-plugins/datasearch.js
'priority+' now includes priority +1, and 'priority-' includes -1
(this was a regression most likely introduced in 8299bcc2bfc1007131df502582f361d4ac22eb8e)
=> Fix priority shorthand parameter in movesearch

chat-commands.js, punishments.js, users.js
This both allows staff to lock users that are offline, given they have a previous punishment (globally or in any room)
This also will utilize existing punishment information for handling nameblacklists, making a nameblacklist of a user with a current punishment equivalent to having used /blacklist at the moment of that punishment
=> Refactor both locks and punishments

chat-plugins/modlog.js
Often times, staff want to see more history in the modlog than just 100 lines, so having this command will allow them to use modlog with an increased line limit of 1k lines.
=> Modlog: Refactor line specification

config/formats.js
The former one was outdated since June 4th
=> Update [Gen 7] OU Sample Teams link

data/abilities.js
Currently if Oranguru instructs Kangaskhan-Mega, then only its first hit is at full power, but I'm assuming that both the Instruct first hit and the natural first hit (in whichever order depending on Trick Room etc.) should be at full power.
=> Parental Bond damage should reset for Instruct

data/items.js
Reported [here](https://www.smogon.com/forums/posts/7458261/).
This copies the change that @ascriptmaster mde in PR #1560 for regular Air Balloon hits so that it also works when the user is behind a Substitute.
=> Fix Unburden/Symbiosis interaction with Air Balloon behind Substitute

config/datacenters.csv
188.172.* is no longer owned by xservers, according to RIPE's database. It now seems to be used by a bunch of different companies and ISPs.
=> Datacenters: remove reassigned IP range

config/formats.js
This effectively removes Freeze Clause from Gen 1-3 Random Battles and Gen 1 Challenge Cup, as well OHKO Clause from Gen 2 Random Battles, to make the rulesets consistent across al Random Battle tiers.
=> Consolidate the rulesets of Random Battle tiers

tournaments/index.js
Fixes an issue where chat can fail to load in a room where a tournament with a ``|`` in the custom name has recently ended.
=> Tournaments: Don't allow the | separator in names

chat-plugins/uno.js
The issue was players passing after they played a wild card and did not choose a color. This made the users forced to play wild cards only.
=> UNO: Fix passing when choosing color

chat-commands.js, room-battle.js, sim/battle.js, sim/dex.js, sim/index.js, team-validator.js, tournaments/index.js, users.js
Rules for custom formats are once again sanitized and can be passed around more easily by attaching them to the format's id.
Fixes:
- "Rule:" being required to add or remove a rule
- ruleset changes not being shown in battles
- the display of custom rules being affected by user input
- custom formats being broken by /hotpatch formats
=> Fix remaining custom format issues

data/abilities.js, data/scripts.js, data/statuses.js, mods/gen6/abilities.js
Instruct means that a Pokémon is now capable of making more than one move in a given turn, and not even the same move at that (if the Instruct happens before the Pokémon's own move then the previous move gets repeated).
This means that several effects that used to be per-turn need to be replaced with per-move flags instead, otherwise they could end up affecting both moves.
This PR deals with abilities which used to use effects but should be using per-move flags. (The other effects set by abilities all already have multiple turn duration.)
Note that Dark Aura and Fairy Aura used to be effectively unbreakable because Mold Breaker doesn't ignore the TryPrimaryHit event, and the aura effect isn't affected by Mold Breaker of course.
=> Remove some ability effects to improve compatibility with Instruct

chat.js
Apparently according to https://github.com/Zarel/Pokemon-Showdown/commit/54f957875ee7f2e2c4a6fb3db9da2ef5c96f72af#diff-0b2efe2973c1ca6e59a67d6ffe5516daR9 the teambuilder needs Gen 3 templates to include Gen 4 abilities, but we don't want e.g. `/dt Machamp, Gen3` to show it having the No Guard Ability, which it didn't get until Gen 4.
=> Hide Gen 4 abilities when giving details for Gen 3

chat-plugins/modlog.js
ripgrep's regular expressions consider ッ to be a word character, for example, so rg modlog's username search for "test" won't find the modlog entry "testッ" despite both being the same userid.
Not sure if this is the best solution, but it should work independently of regex flavor.
=> Modlog: Fix user search for names with certain non-alphanum characters

chat-commands.js
``target`` includes the namelock reason in addition to the username.
=> Fix message when namelocking already namelocked user

sim/dex.js
Before : HP_Power=(5*(v+2w+4x+8y)+min(Z, 3))/2 + 31 
After: HP_Power=(5*(v+2w+4x+8y)+(Z % 4))/2 + 31 
where 
* v is 1 if SpcIV>=8; otherwise 0, 
* w is 1 if SpeIV>=8; otherwise 0, 
* x is 1 if DefIV>=8; otherwise 0, 
* y is 1 if AtkIV>=8; otherwise 0, 
* Z = SpcIV
See: 
http://tasvideos.org/forum/viewtopic.php?p=361950#361950
https://github.com/pret/pokecrystal/blob/master/battle/hidden_power.asm#L52
=> Fix gen 2 Hidden Power base power formula

chat.js, tournaments/index.js
This turns Config.chatfilter into Chat.filter.
Also, each chat-plugin can potentially alter the chat filter by exporting 'chatfilter', just as they can export 'commands'.
Note:
1. returning a string in a chatfilter will make that be a user's message sent to the room
2. returning false will make a user's message not send to the room
3. returning undefined will send a user's original message to the room
=> Chat: Refactor chat filter out of Config

data/random-teams.js
It doesn't need it either; even after 2 uses, it still weighs more than twice as much as Mega Aggron.
=> Randbats: Celesteela doesn't learn Rock Polish

data/moves.js
For example, if Chatot uses Chatter on a grounded Pokémon, then the confusion secondary should just be silently ignored, as it would be for e.g. Safeguard or the Ability Own Tempo.
I also copied the status check from the Ability Leaf Guard as it's much simpler. (The Ability Synchronize uses a custom effect object when setting status.)
=> Misty Terrain shouldn't -activate for secondary confusion

sockets.js
<code>worker.kill()</code> already calls <code>worker.disconnect()</code>. See https://github.com/nodejs/node/issues/6117#issuecomment-207770642
<code>socket.destroy()</code> already calls <code>socket.end()</code>. See https://github.com/sockjs/sockjs-node/blob/master/src/transport.coffee#L43
This fixes the <code>ERR_IPC_DISCONNECTED</code> errors we've seen lately, which I traced back to d248b652b04e8c44e4ec748dd394de6fc5fa1f99.
=> Sockets: fix 'already disconnected' errors

config/config-example.js, users.js
This should use the unicode instead of the actual character itself for the same reason the player rank does - some text editors don't like unicode and will override this with an actual question mark.
=> Locked symbol: Use unicode code point

chat-plugins/uno.js
Add a new "uno" state (that does absolutely nothing except define what is going on), so that the previous player can't play their last card during the 750ms grace period for the player to slap the UNO button.
Credits to PS user "Java SE Runtime" for catching this
=> UNO: fix playing 2 cards during UNO

data/moves.js
DaWoblefet also confirmed that if you're both Soundproof and semi-invulnerable then the semi-invulnerability takes precedence (which is why the tests are in the order I've put them; I'm assuming this also applies to the Liquid Voice/Water Immunity variants, and that No Guard ignores this).
=> Perish Song shouldn't normally hit semi-invulnerable Pokémon

data/rulesets.js
Completes https://github.com/Zarel/Pokemon-Showdown-Client/pull/996
This is not backwards-compatible with older clients, though, and may possibly break them in however many ways.
=> Do not send details about shiny-ness on Team Preview

team-validator.js
So instead of saying 
- You are limited to 0 of Drizzle ++ Swift Swim.
it now says
- Your team has the combination of Drizzle ++ Swift Swim, which is banned.
which is slightly closer to what it said before d79e348, which was
- Your team has the combination of Drizzle + Swift Swim, which is banned.
=> Fix mismatched team complex ban messages

data/statuses.js
The original problem with choice lock was that it locked you in to a move that your Magic Bounce bounced. This was hacked around in 08792b1 by checking whether the move had a source effect. (Pursuit has a source effect when it triggers on the foe switching, so an additional hack was added to cope with that case.) Pledge moves also get a source effect when they combine, so this is why they currently don't get choice locked. Instead, we can just directly check whether the move has bounced in the first place.
=>  Fix choice lock for the combined Pledge move

config/config-example.js
`Config.workers` especially deserves to be documented. The other config
settings don't entirely need to be documented, but for the sake of
transparency `Config.ssl` and `Config.bindaddress` have been added as
well.
=> Config: add missing documentation for networking-related settings

sockets.js
- Workers weren't handling dying correctly. Workers getting killed
using Sockets.killWorker were not cleaning up user connections and some
normal process deaths were going through the crashlogger when they
shouldn't have been.
- Depending on how they died, workers would sometimes never disconnect
their IPC channel, which is likely the reason behind the zombie
processes and some of the IPC crashes
- Sockets no longer get their `id` and `remoteAddress` properties mutated
- Buffers for SSL key and cert settings are deprecated in favour of
absolute paths to their respective files in order to defer some of the
work done reading the files on startup to the workers and save on IPC
bandwidth whenever the Go rewrite happens. Some sanity checks for
whether the config is valid before launching the …
=> Sockets: fix crashes on startup and workers not dying properly, refactor

data/formats-data.js
I saw Persian-Alola had randomDoublesBattleMoves rather than randomDoubleBattleMoves
=> Random Doubles: Fix Persian-Alola Typo

package.json
mime 2 broke node-static 0.7.9, update to 0.7.10 fixes this
=> Fix breakage with node-static 0.7.9 and mime 2

pokemon-showdown
In Ubuntu, the binary is called nodejs. In order to support this possibility, ./pokemon-showdown script was changed into shell/Node.js [polyglot](https://en.wikipedia.org/wiki/Polyglot_(computing)) which calls the correct Node.js binary or informs that Node.js is not installed.
Should fix #3997.
=> Automatically detect name of Node.js binary when using ./pokemon-showdown

chat-plugins/datasearch.js
So that searching for gen1 mons doesn't give the rest of the gens too.
=> Dexsearch: fix maxgen parameter

mods/gen3/formats-data.js
Nidoking can't learn Superpower until Gen 4.
=> Gen 3 Randbats: Fix illegal move

mods/gen2/scripts.js
Spotted by @QuiteQuiet, this code was obviously unused in Gen2 even before Illusion-ending got moved to `ability.js`.
=> Remove bogus Illusion check from Gen2

chat-commands.js
This prevents a crash when attempting to read/write a Chatroom's modlog
file on most filesystems, which typically cap filename length at 255
bytes.
=> Commands: cap /makechatroom roomid length at 225 characters

chat-plugins/info.js
So for instance if you use `/data` in a Gen 1 battle you get Gen 1 data by default.
=> Default to battle room's data

data/random-teams.js
- Existing code was accidentally bumping the item count twice
- Since a set can't reuse an existing item, no point bumping the item count, just mark the item's use
- Since all items are subject to the Item Clause, no need to maintain a list of them
=> Simplify artificial replication of Item Clause

chat-commands.js, chat.js, dnsbl.js, ladders.js, loginserver.js, process-manager.js, punishments.js, room-battle.js, rooms.js, team-validator.js, users.js
*Partially* does the thing in #3918 for top-level `.js` files (I'll do subdirs later...)
I did **NOT** convert:
- Loops where the index was needed (these could be converted using `Array.entries()`, possibly)
- Loops that were iterated backwards
- Other weird loops that didn't simply iterate over all elements
Some of these loops could be converted to `.reduce` statements, I think, but I only refactored one of them in this PR
**EDIT**: Had to change first line to from "resolves" otherwise GitHub would close the issue ...
=> Conversion of for...length loops in top-level js files to for...of loops

mods/gen4/formats-data.js, mods/gen4/random-teams.js
* Remove unused NFE movepools
* Favor Energy Ball over Grass Knot in movepools
* Reject Agility + Superpower
* Boost Unown and Ditto to level 99
=> Gen 4 Random Battle updates

mods/gen2/scripts.js
The new Beat Up code assumes it can access the Move object, but Gen 2 has its own unique stat calculation.
=> Pass the active move when modifying stats

chat-plugins/trivia.js
There are currently some questions that cannot be deleted from the trivia database for some reason, I suspect this will allow us to delete them (but either way it's helpful, in case of typos/miscapitalization, and approved by QW staff).
=> Trivia: Delete questions by ID

data/moves.js, test/simulator/moves/reflecttype.js
Previously, Reflect Type didn't treat the "???" type differently than any other type, unlike what its [description](https://dex.pokemonshowdown.com/moves/reflecttype) said it did.
=> Fix Reflect Type vs. Pokemon with the "???" type

chat-plugins/modlog.js
There's a newline at the end of ripgrep's output, which led to an additional empty result element being added.
=> Modlog: fix result count display being off by one

chat-plugins/datasearch.js
For example, compare `/ds hp=65, atk=40` with `/ds3 hp=65, atk=40`. Reported [here](https://www.smogon.com/forums/posts/7541421).
=> /ds<N> single result details should be for gen<N>

chat-plugins/tcgtabletop.js
seems like bulbapedia requires https now, which was breaking ptcg requests
=> tcg: update to use https, fix error with bulba

chat-plugins/scavenger-games.js
- return the value of the timer duration in a scav game so it does not end up as ``undefined``
(NOTE: the timer works as is - it simply does not announce the duration properly to the room)
=> Scavenger games: fix timer

chat-plugins/scavengers.js, punishments.js
This is really not that important in of itself, but it seems right to highlight this in general. It seems as if Travis indentation rules aren't being entirely enforced since these are getting a pass in current pullreqs (https://github.com/Zarel/Pokemon-Showdown/pull/4055). Since the errors do get detected by the rules on other platforms, this doesn't seem to be a problem with the rules themselves but rather the environment its tested in.
```
>npm test
> pokemon-showdown@0.11.2 test .
> eslint --rulesdir=dev-tools/eslint --cache *.js chat-plugins/ config/ data/ dev-tools/ mods/ sim/ tournaments/ test/ && mocha
punishments.js
1251:5  error  Expected indentation of 3 tabs but found 1 space and 3 tabs  indent
1253:5  error  Expected indentation of 3 tabs but found 1 space and 3 tabs  indent …
```
=> Fix inconsistent indentation

data/pokedex.js
Seeing as this generation in the games, you can learn moves with the relearn tutor without actually needing to reach that level it is possible to reach Level 19 and evolve a Tsareena.
=> Pokedex: Update Tsareena Evolution Conditions

data/abilities.js, data/items.js, data/moves.js, sim/battle.js, sim/pokemon.js, test/simulator/items/sitrusberry.js
Mentioned in https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-327332860
Not sure if this is the best way to implement this, but I can't think of anything else.
@Marty or @DaWoblefet can either of you confirm if Oran Berry/Berry Juice/Stat-boosting berries also does this or if it's only the healing berries. Also is this new in Gen 7, or was this also the case before?
=> Confusion self-hit doesn't trigger Sitrus + super sitrus Berries

mods/gen3/random-teams.js
* Reject Mean Look, Spider Web, and Protect without moves to support them
* Reject Sunny Day without Solar Beam and vice versa
* Reject Reversal/Endeavor without Sub/Endure
* Reject multiple self-KO moves on the same set
* Reject Whirlwind with setup
* Reject Endure with Substitute
* Reject redundant Grass- and Fighting-type moves
* Remove checks for moves that don't exist or are irrelevant in ADV
* Fix bug that sometimes caused Castform to have its weather move twice
=> Gen 3 Randbat improvements

team-validator.js
If you type `/learn Palkia, Heal Block`, you currently get the reply
In Gen 7, Palkia _can_ learn Heal Block from:
- anywhere (all moves are level-up/tutor/TM/HM in gen 7)
This is plainly untrue as Heal Block is a Gen 4 level-up move. If you were to query for a Gen 4 TM instead, such as swift, you would get the correct reply.
This bug seems to have been introduced when LC validation was added.
My approach is to limit the LC validity check to under-levelled Gen 4-6 moves only. (In Gen 7 you can of course learn under-levelled moves using the Move Relearner.)
I've tested and with this change Nidoran-M still can't learn Toxic Spikes in Gen 6 LC.
=> Fix source of previous gen level up move

data/abilities.js, data/items.js, data/moves.js, data/random-teams.js, data/scripts.js, mods/gen1/moves.js, mods/gen1/scripts.js, mods/gen2/moves.js, mods/gen2/scripts.js, mods/gen5/moves.js, mods/gen6/moves.js, mods/gennext/abilities.js, mods/stadium/scripts.js, sim/battle.js, sim/dex-data.js, sim/dex.js, sim/pokemon.js, team-validator.js, tournaments/generator-elimination.js, tournaments/generator-round-robin.js
Previously, if we wanted to test if A was either 'B' or 'C', we would use the pattern:
A in {B:1, C:1}
I actually don't know how common this pattern is; I just started using it because I was tired of typing `A === 'B' || A === 'C'` all the time. I never really liked it, though; the `:1` part made it kind of blatantly a hack.
I did some testing and `['B', 'C'].includes(A)` is overall faster.
(A switch statement is around 20x faster still, but who wants to type that much code?)
Anyway, the new standard is
['B', 'C'].includes(A)
Something something progress!
=> Refactor in-object-literal to array-includes

chat-plugins/datasearch.js
Previously, the command allowed users to broadcast commands ending with` ', all'`. I removed the `',all'` option because it was still stripping off the last 5 characters of `target` even when the space was omitted, and the command doesn't support separating any other words with just a comma anyway.
=> /itemsearch: Fix using the 'all' parameter

.editorconfig
As based on discussion on https://github.com/Zarel/Pokemon-Showdown/commit/9435848c16e4fb3aefa903953d0a545de404d5d3 and the poll in Dev
=> Editorconfig: Increase indent size to 3 spaces

users.js
Fixes an issue where users can evade global bans on the same name they were banned under.
=> Fix global bans

data/moves.js
Now they'll return false when they don't heal, which will cause the "But it Failed!" message to appear. At some point, someone should implement a unique failure message ("{Pokemon}'s HP is full!") for when these moves and Recover clones fail to restore HP, but for now this should be sufficient for any future implementation of Stomping Tantrum, as far as actually recording the failure.
=> Variable healing moves should have fail messages

sim/dex.js
should make the output the same as it was before, i think.
afaik the "id" property not being an id is intended
=> dex: fix gettype

mods/dualwielding/scripts.js
Because I had been playing around with where the `Z-` prefix got added to the move name on ROM...
=> Fix Dual Wielding's duplicate Z- prefix

config/formats.js, sim/team-validator.js
http://replay.pokemonshowdown.com/gen7stabmons-654178506
Pokemon were allowed to use banned moves still.
=> STABmons: Fix move validation error

chat-plugins/info.js, config/formats.js, sim/team-validator.js
I moved AAA's validation code to allow it and STABmons to have their ability and move restrictions, respectively, to be viewable through `/om aaa` and `/om stabmons`
=> Modify AAA's validation code

data/rulesets.js
Making `ignorestabmoves` a validator rule allows it to be added to
tournaments. I also removed a clause that was leftover from Sketchmons.
=> STABmons: Make Ignore STAB Moves a ValidatorRule

config/formats.js
unbanning just the item in `unbanlist` still labels the Pokemon that it
Mega Evolves as Uber, thus leaving it banned
=> AAA: Actually unban Mega Metagross

sim/battle.js, sim/pokemon.js, test/simulator/misc/trapmoves.js, test/simulator/moves/skydrop.js
- Fixes a case where if a single Pokemon trapped more than one other Pokemon, they wouldn't all be freed when the trapper switched out, was forced out, or was KO'd.
- Fixes a case where a trapper that was KO'd and not replaced wouldn't free any Pokemon it had trapped, even if it had only trapped one.
- Fixes a case where a Pokemon that transformed into an opposing Pokemon and fainted or was forced out on the same turn would leak the ability and moveset of the Pokemon it transformed into if its owner moused over it in the party menu before sending in a replacement.
In order to get the build to pass, I had to alter an apparently unnecessary assertion from an unrelated test. As far as I know, there's way that Aerodactyl could possibly not have used Sky Drop in that test unless somehow Kyogre …
=> Fix clearing volatiles

chat-plugins/health-fitness.js, chat-plugins/trivia.js, fs.js, punishments.js, rooms.js
Writing program state to a file is fairly hard to do safely, especially with Node's async FS writing. PS previously reimplemented the code necessary to do it safely basically everywhere it was needed. FS().writeUpdate now consolidates that code so anyone can easily safely update a file.
Would like code review on this.
#4110 should be rebased on this.
=> Safe FS writing

punishments.js
This semilocks users with connections that give the server invalid IPs.
`Config.hostfilter` should check for null hosts if it has any custom
behaviour for this type of connection.
If you need to know more about what this is for, ask me privately
=> DNSBL: fix crash when reversing IPs

chat-commands.js
the function ``user.joinRoom(targetRoomId)`` returns null instead of false. And some other functions seem to make use of this returning null on banned users.
=> redirects were not being caught for blacklisted/banned users

data/formats-data.js
This is partly a consistency thing, but it mainly stops these formes from being allowed to team preview in Dual Wielding.
=> Require something for all battleOnly formes

data/abilities.js, data/moves.js, data/random-teams.js, mods/gen4/moves.js
I was looking at some calls to `Dex.getMove` for an unrelated reason and wondered why it wasn't `this.getMove`. I though I should clear that up first before I make any other changes.
=> Use this when it's a Dex

data/moves.js
Compare Core Enforcer. See https://www.youtube.com/watch?v=SNMvXe6evIY
=> Flame Burst should damage target's allies even if it has a Substitute

sim/battle.js
So that when the next foe is processed, it's not considered has having broken protect unless it really did.
Relevant [replay](http://replay.pokemonshowdown.com/gen7doublesou-661362162).
=> Fix Clangorous Soulblaze in Doubles when one foe Protects

data/rulesets.js
Ultra Necrozma is only valid on Psychic teams, not Ghost or Steel, for the same reason Mega Gyarados can't be used on a Flying team.
It should be noted that neither Necrozma Dawn Wings nor Necrozma Dusk Mane are legal in standard Monotype, and that this change will therefore only affect other things that use this rule, such as Monotype Ubers tournaments run in the Monotype room. If that's not a good enough reason for this commit (and an extra unneccesary check for each mon in each mono team) then feel free to reject this commit, however my understanding is that the rule should be valid for all possible situations, rather than just those it's currently often used for.
=> Account for Ultra Necrozma in Same Type Clause

chat-plugins/info.js
```
[10:03:58] @panpawn: nagandel overrated, rainbowzigzagoon has no punishments associated with it
[10:04:06] @panpawn: its possible those punishments have already expired
[10:04:16] nagandel overrated: ?? expireee
[10:04:18] nagandel overrated: i was blacklisted
[10:04:22] nagandel overrated: aint it permaban
[10:04:28] @panpawn: blacklists are for a year
[10:04:38] nagandel overrated: :OO thankss
[10:04:39] @panpawn: but i dont see any blacklists on the name "rainbowzigzagoon"
[10:04:46] @panpawn: are you sure you were blacklisted recently?
[10:04:50] %sparkychild: your lobby blacklist still lasts for another 100 days on - rainbowzigzagoon
```
I think even if they're offline, you should be able to see their punishments
=> Checkpunishment: show punishments for offline users

chat-plugins/othermetas.js
I added the check for the template being Ultra Necrozma in here instead of adding it to the `cannotMega` list in `formats.js` because there is precedent there of only adding base formes.
=> Fix incorrect error messages in /mnm

sim/team-validator.js
- Nature early exits for some reason; changed to `push`
- Messages for nature, happiness and move with multiple ineligible events only used the species
- Event ineligibility message wrong for unnamed Pokémon
=> Fix set name in validation reasons

data/random-teams.js
Before ad8ef6c unified them, Challenge Cup and Hackmons Cup had slightly different team generators: Hackmons Cup excluded all forms without their own learnset while instead Challenge Cup reverted battle-only formes to their base species while still allowing normally usable forms such as Gourgeist or Oricorio forms. This switches the shared generator to allowing all formes, which thus allows Gourgiest and Oricoria forms in Challenge Cup, but also currently allows battle-only forms in Hackmons Cup (but then again, they're allowed in Balanced Hackmons...); if this is undesirable then I can switch the check to `!template.battleOnly` although I would then also want to remove the Challenge Cup code that excludes battle-only formes.
=> Allow other legal forms in Challenge Cup

config/formats.js
I don't think there are any other cases like this, but lemme know if you think of one. Technically, a Wisihiwashi below level 20 can't transform and would technically satisfy the rules of the meta, but I figured nobody would actually want that.
=> Ban Wishiwashi from Mediocremons

chat-commands.js
If someone is already locked, the only reason why they should get another lock is for a weeklock for extending a lock.
This happens a lot when someone goes in several rooms, they will often be locked more than once in a short span of time.
=> Lock: Don't allow regular locks to stack

data/moves.js, mods/gen1/moves.js, mods/gen1/scripts.js, mods/gennext/statuses.js, mods/pic/moves.js, mods/stadium/scripts.js
Most functions run in the battle context so they should be using `this` rather than (e.g.) `target.battle`.
=> Fix this unnecessary reference to battle

chat-plugins/datasearch.js
Adding a `protect` flag allows users to search for moves that break protection with `!protect`
=> Datasearch: Fix zboosts and add protect flag

chat-plugins/info.js
doing something like `/analysis ferrothorn, bw, uber` currently links the user to "BW [Gen 7] Ubers Ferrothorn analysis", which then links to `http://www.smogon.com/dex/bw/pokemon/ferrothorn/gen7ubers`, which gets automatically corrected to `http://www.smogon.com/dex/bw/pokemon/ferrothorn/` due to "gen7ubers" not being a format in BW.
I also added some more gen aliases, as well as redoing the formatting for generation checking, and I changed everything to `` ` `` quotes.
=> Fix specifying formats in /smogdex

data/scripts.js
Reported [here](http://www.smogon.com/forums/posts/7610701).
Clangorous Soulblaze broke through Tapu Lele's Protect (despite it being immune anyway), and that status was then carried over to its hit on Zapdos.
=> Protect should not affect Clangorous Soulblaze's other target

chat-formatter.js
ATM formatting ``[[coordinator spotlight site:bulbapedia.bulbagarden.net]]`` creates an ``<a href>`` to bulbapedia embedded within a bigger google search of ``coordinator spotlight site:<a href="http://bulbapedia.bulbagarden.net" rel="noopener" target="_blank">bulbapedia.bulbagarden.net</a>``
This strips all links within the search term, and leaving behind only the generated google search URI.
I'll make a second PR to change the minimized chat formatter on the client, since both have the same issue. (This version of the chat-formatter is just immensely easier to read and edit)
=> Chat-Formatter: don't embed links within links

chat-plugins/uno.js
- The uno button is on its own row, slightly bigger than the row of draw/pass.   This is to facilitate easier hitting of the button before the next player plays their card
- Display the cards after selecting a colour so the player can hit UNO after.  This prevents a player from losing in a non-1v1 situation where they have to hit uno before they can play the final card.
=> UNO: colour + UNO interaction, make UNO button easier to press

config/config-example.js, package-lock.json, package.json, sockets.js
Permessage-deflate is an extensIon that compresses websocket messages with zlib.
SockJS already supports it (indirectly) and the client's load balancer already
inserts the header in the opening handshake when making a WebSocket connection.
`Config.wsdeflate` makes this optional and allows tweaking the extension's resource
usage.
=> Sockets: implement permessage-deflate support

chat-plugins/tickets.js
Tickets would store the user object of the staff that escalated it, which crashes when it tries to stringify it.
=> Tickets: Fix crash on escalation

chat-commands.js
I've seen several cases where a roomdriver wants to hide a muted users messages but its not worthy of a roomban/lock, and so their natural reaction is to spam the chat with broadcasted commands such as !roomintro.
The correct and more elegant solution for cases like this is for them to be able to use /hidetext. Having to call in a global upper staff for these cases can get frustrating and is not always an easy task.
=> Hidetext: Allow hiding of muted user's messages

data/moves.js
Originally seen with Clangorous Soulblaze in a YouTube video but confirmed for Z-Parting Shot in the US/UM mechanics research thread.
I don't know about other effects such as Gravity yet.
=> Throat Chop shouldn't block Z-moves

chat-plugins/othermetas.js
I'm purposely not accounting for regular Greninja, as it has more than one ability in its base forme.
I also removed unnecessary information from warning messages, as it just elongated them for no reason.
=> /mnm: Remove redundant parts of warning messages

users.js
This is a bug that was introduced in https://github.com/Zarel/Pokemon-Showdown/commit/0b64df7f3cc507f44f51cbd753e8a6a4a641592b
=> Users: Fix marking guest numbers as autoconfirmed

data/abilities.js
So that when Partners in Crime has both Contrary and Competitive active at once, the stat drops caused by Contrary Competitive don't retrigger Competitive.
=> Make Contrary Competitive/Defiant self-inflicted

sim/battle.js
Should Chimera 1v1 win OMotM it will need to be able to do this.
Basically all this does is send `teampreview|6` if the format requests `teamLength: { validate: [6, 6], battle: 6 }` (no existing formats currently do that so they are unaffected).
=> Allow formats to reorder all six Pokémon

punishments.js
This happens when you use `/nameblacklist` on a user that already has some punishments, can get something like
=> Punishments: Fix a few display issues

chat-plugins/datasearch.js
This loop previously ignored the first item in the array (which is the name of the Pokemon), but this was lost in the for...of refactor. I think this is better readability-wise than any shorter or hackier solution.
On the other hand, I'm really behind on the latest standards, so this may not be the optimal way to fix this.
=> Fix for...of bug in /learn command

data/items.js
As discussed in Zarel/Pokemon-Showdown-Client#785 the server should let the client know when an activated item has been consumed so that the client doesn't accidentally set it as the active item.
=> Indicate when an item activates after it is consumed

chat-plugins/othermetas.js
Currently, no warning is given for doing something like `/mnm Arceus-Water @ Sablenite` despite it (alongside Sablenite Silvally-Water) not being usable.
=> Check for Arceus and Silvally formes in /mnm

config/formats.js
Since inheritance is OU-based and goes off of OU's clauses and bans, the OU banlist is "inherited" (hah see what i did there)
=> Inheritance: Remove redundant set validation checks and check for banned Mega Evolutions

data/items.js, data/moves.js, mods/gen1/moves.js, mods/gen1/scripts.js, mods/gen1/statuses.js, mods/gen2/moves.js, mods/gen2/statuses.js, mods/gen3/moves.js, mods/gen4/moves.js, mods/gen5/moves.js, mods/gen6/moves.js, mods/gennext/statuses.js, mods/stadium/statuses.js, sim/battle.js, sim/pokemon.js, test/simulator/abilities/klutz.js, test/simulator/abilities/magicbounce.js, test/simulator/items/assaultvest.js, test/simulator/misc/decisions.js, test/simulator/moves/belch.js, test/simulator/moves/disable.js, test/simulator/moves/embargo.js, test/simulator/moves/gravity.js, test/simulator/moves/healblock.js, test/simulator/moves/imprison.js, test/simulator/moves/magicroom.js, test/simulator/moves/taunt.js
Mostly this is just adding `.id`, but there are some specific changes:
- Conversion 2 now resists the move's actual type (after effects) rather than its original type
- Z-status moves can't be copied etc.
- Some extra null-checks of course (I think I got them all...)
=> Change lastMove from a string to a Move

chat-plugins/info.js, chat-plugins/othermetas.js, config/formats.js
Unlike a total ban, these abilities and moves are still allowed on their natural users. Compare Mix and Mega, where `/mnm` and `/stone` will happily tell you that certain stones are restricted.
=> Restricted makes more sense than banned in some cases

config/formats.js, data/formats-data.js
http://www.smogon.com/forums/threads/usage-based-tier-update-for-january-2018.3625266/
Manaphy, Dragonite, and Mega Charizard Y were BL before they rose.
=> January tier updates

data/moves.js
Nobody said yay or nay for  #4332 so I did it anyway.
Of course unlike Mud Sport and Water Sport these are toggle effects thus the `onRestart` code.
=> Simplify Magic/Trick/Wonder Room

config/config-example.js, users.js
Was broken when `users.js` was type scripted.
Sorry if the type scripting is done wrong, I've never done it before.
=> Fix permission checking for promotions

chat-plugins/info.js, config/formats.js, sim/dex-data.js, sim/team-validator.js
This avoids special hacks for Alphabet Cup and STABmons, but could also be used for Sketchmons and potentially other OMs (ORAS OM examples: Genmons; Move Pass LC; Multitype Mansion; Setupmons; Super-Effectivemons; The Power Within).
=> Allow formats to override checkLearnset

data/scripts.js
Latest [research](http://www.smogon.com/forums/posts/7625046) shows that although Z-Synthesis passes Heal Block, using Z-Copycat to copy Synthesis does not. (Z-Copycat on a damaging move does of course turn into a damaging Z-move.)
Note that this doesn't fix the message (because the Synthesis gets blocked at the healing level rather than at the use) but that's a different issue that affects several move blocking effects against copied moves.
=> Called status moves don't inherit Z power

room-battle.js
Functionally, this stops /forfeit from thinking that it failed when it didn't.
=> Make forfeiting return success/failure properly

mods/gen4/items.js
Reported [here](http://www.smogon.com/forums/posts/7656866).
Tested using the following commands in a `node` REPL:
global.Dex = require('./sim/dex');
const common = require('./test/common');
let battle = common.gen(4).createBattle();
battle.join('p1', 'Guest 1', 1, [{species: 'Registeel', item: 'leftovers', moves: ['seismictoss', 'curse']}]);
battle.join('p2', 'Guest 2', 1, [{species: 'Mesprit', item: 'custapberry', moves: ['stealthrock', 'trick']}]);
battle.makeChoices('move seismicross', 'move stealthrock');
battle.makeChoices('move seismicross', 'move stealthrock');
battle.makeChoices('move seismicross', 'move stealthrock');
battle.makeChoices('move curse', 'move trick');
Before the change, `p1.pokemon[0].item === 'custapberry'` but after the change `p2.pokemon[0].item === …
=> Don't trick away the Custap Berry being eaten

data/moves.js
[16:33:09] +DoW: Hi, is there a reason that ``twineedle.multihit == [2, 2]`` whereas ``doublekick.multihit == 2``?
[16:33:09] +DoW: As far as I can tell they do the same thing
[16:39:21] ~Zarel: yeah
[16:39:25] ~Zarel: they should probably both be ``2``
[16:39:51] +DoW: Cool, thanks
=> Refactor twineedle.multihit to match doublekick

config/formats.js
Curse, String Shot, Forest's Curse, and Power Trick have been temporarily banned from VGC 2018 (Until the 1.2 patch for Ultra Sun and Ultra Moon).
https://assets.pokemon.com//assets/cms2/pdf/play-pokemon/rules/play-pokemon-vg-rules-formats-and-penalty-guidelines-en.pdf Section 1.4
=> VGC: Update bans

data/abilities.js, data/items.js, sim/pokemon.js
Originally inspired by this [video](https://www.youtube.com/watch?v=YmLzeSB0xK0). Thanks to Overdragoon on PS/Smogon forums for helping research this. Results of the research:
- Protective Pads does not affect user's Poison Touch or Tough Claws or target's Pickpocket.
- Protective Pads activates to block the effects of Aftermath, Gooey, Iron Barbs, Mummy, Rough Skin and Tangling Hair, if no other effect already prevents them (e.g. Clear Body or Magic Guard).
- Protective Pads silently blocks the effects of Beak Blast (if the target is heating up its beak), Cute Charm, Effect Spore, Flame Body, Poison Point, Rocky Helmet and Static.
=> Fix Protective Pads mechanics

users.js
Room staff will be able to post 6 lines at once in the rooms they are staff in.
Previously only global staff could post 6 lines at once.
An example of a use for this is buttons (in the room's staffintro) that create custom tournaments (they send alot of commands at once).
=> Allow room staff to post more lines at once

chat-plugins/poll.js
You should not be able to make polls in battle rooms (I think) even though it is somehow possible (and entirely useless since it gives an [error](https://prnt.sc/i55fze).)
=> Block making polls in battles

data/abilities.js, data/moves.js, mods/gennext/abilities.js, sim/pokemon.js
Bestow, Pickup, Switcheroo and Trick do not change a Pokémon's consumed item. In the case of Pickup, this lets two Pokémon pick up each other's item consumed the same turn. This bug was originally reported in this [video](https://www.youtube.com/watch?v=RrBkz1QQYG4) which was subsequently mentioned in the Gen 7 mechanics forum.
To achieve this, I removed the `lastItem` handling code from `setItem` and moved it to those effects that don't already alter the consumed item, which are Fling, Harvest, Natural Gift and Recycle.
=> Fix last item handling

data/scripts.js
I haven't researched this so feel free to prove me wrong but I suspect that Spectral Thief's stat boosts should be self-inflicted, so that Protective Pads shouldn't protect against its Contrary stat drops.
=> Don't protect against contrary spectral thief stat drops

room-battle.js
Crashes are being missed without this.
=> Battles: Handle unhandled promise rejections

config/formats.js
Emergency Exit too;
Even with just Golisopod + Wimpod being able to do this, it still takes an unnecessarily long time. The metagame leader also prefers a complex ban.
=> OMotM: Wimp Out + Regenerator on the same team

config/formats.js
It's always been banned: http://www.smogon.com/dex/xy/formats/monotype/
=> ORAS Monotype: Ban Damp Rock

config/formats.js
Shared abilities were activating once per switch in for every shared user, even if two allies had the same ability. This fixes that by calculating the list of shared abilities in a set. I reused the code for the before switch / after mega cases too although they're not affected.
=> Fix double shared power activation

data/random-teams.js
The randbats generators (except Battle/BSS Factory) let the sim pick a random gender. This doesn't work for Ash Greninja because it starts off with the regular Greninja template which isn't gender limited, so I'm adding the gender manually to all the random sets to handle this case.
=> Don't generate female Greninja-Ash in randbats

chat-plugins/scavengers.js
Currently people can use `/starthunt` to override the queue of hunts, so this prevents `/starthunt` from overriding, although adds a new command, `/forcestarthunt`, if somebody really wants to ignore the queue.
=> Scavengers: add forcestarthunt

rooms.js
Currently, if you vote for a poll on one IP, let your user object expire, and join PS! on a different IP, the following will occur:
telling you that you have already voted for the poll, even though the poll results did not display.
This is since the poll is sent to the user in onConnect, but onConnect is called before the user is actually logged in (while onJoin is called after the user is logged in).
=> Send poll info to users in onJoin

data/moves.js
I believe this will do what's requested in https://www.smogon.com/forums/threads/what-can-ps-do-for-you.3622358/page-5#post-7698629
In any case, this is the only real difference between Floral Healing and Heal Pulse, and therefore seems like it should be removed.
=> Remove floralhealing.isViable to match Heal Pulse

room-battle.js, rooms.js
This was requested by the smogon tournament directors.
Normally when a battle is created, and `Config.reportbattles` is set to a truthy value, it is reported in lobby or the the room `Config.reportbattles` specifies. Battles created with `/importinputlog` are not logged though. This attempts to fix that by calling `Rooms.global.onCreateBattleRoom` when the battle gets both of its players.
=> Report imported battles when players join

mods/natureswap/scripts.js
Currently, you need to put your EVs in the minus stat to boost it, so a Naive Sylveon would need to use 252 SpD EVs (same with IVs, so a Timid Magearna currently has to put 0 IVs in speed for minimum foul play damage and maximum attack IVs)
It's much easier and causes less of a headache to put the EVs and IVs in the plus stat, so this fixes that.
=> Nature Swap: Fix EVs and IVs in swapped stats

mods/gen3/abilities.js, mods/gen4/abilities.js
If a Pokemon with Flash Fire is frozen in Gens 3 and 4, Flash Fire shouldn't activate.
=> Fix Flash Fire + Freeze in Gens 3 and 4

data/abilities.js
This is (so far) only relevant for the specific case of Protective Pads blocking Mummy, because it has an `onSetAbility` handler that uses the source of the change. Since it wasn't set, it caused this: https://replay.pokemonshowdown.com/gen7hackmonscup-708439558 (turn 7-9).
There are a whole lot of calls to `setAbility `without a source, but there are no further `onSetAbility`s so it doesn't matter yet - is it worth bothering to add sources to them all?
=> Set source of ability change on Mummy activation

mods/natureswap/scripts.js
The previous method would cause the EVs and IVs in a stat to swap every time a Pokemon switched out.
=> Nature Swap: Correctly fix EVs and IVs

config/formats.js
Gen 1 1v1 does not have Gen 1 preview. I've discussed this with others, and removing the team preview also further removes and strategy by choosing the first Pokemon in your team. This makes the type match ups completely random.
=> Gen 1 1v1, adding Team Preview

chat-commands.js, punishments.js
the only situation I've found where this is relevant is ``/nameblacklist ,|``, so this stops that case.
=> Punishments: Don't crash on punishing ''

sim/battle.js, sim/dex.js, test/simulator/misc/arceus.js
Battle#getRelevantEffectsInner performs a lookup for the base species of every Pokemon with ModdedDex#getEffect, then invokes callbacks. The lookup is expensive, and callbacks very rare. In fact, there are only ever two callbacks: one for Arceus (SwitchIn) and one for Silvally (SwitchIn).
Instead of an expensive ModdedDex#getEffect lookup for the callbacks, put the callbacks directly on the Pokemon's Template object.
On my machine, this commit speeds up Pokemon Showdown's tests by 20%.
Methodology: With and without this commit, I ran mocha four times with zsh' 'time' builtin, dropped the first result, and averaged the wall times:
mocha times before this commit:
18.20s user 0.33s system 118% cpu 15.704 total
17.91s user 0.34s system 118% cpu 15.454 total
18.11s user 0.33s system 118% cpu …
=> Optimize species-specific effects (e.g. Arceus); 20% overall perf win

sim/dex.js
Various functions call ModdedDex#getEffect with null, undefined, or an empty string. For example, in the common case, Battle#getWeather calls getEffect with an empty string. In these cases, getEffect basically returns the same object each time: a PureEffect indicating that no effect with the given name exists.
Creating the dummy PureEffect is expensive and puts pressure on the JavaScript garbage collector. Memoize the creation in getEffect to improve performance.
(As a bonus, special-casing null, undefined, and empty strings also lets us drop some noisy truthiness checks in getEffect.)
On my machine, this commit speeds up Pokemon Showdown's tests by 11%.
Methodology: With and without this commit, I ran mocha four times with zsh' 'time' builtin, dropped the first result, and averaged the …
=> Optimize no-op effects; 11% overall perf win

mods/natureswap/scripts.js
This is honestly my fault for only paying attention to the modified `nature.plus` stat, but currently, calculating stats will use the EVs and IVs for `nature.plus` in both the `nature.plus` and `nature.minus` stats
=> Nature Swap: Correctly calculate nature.minus

test/simulator/items/protectivepads.js
As per https://github.com/Zarel/Pokemon-Showdown/pull/4447#issuecomment-369892851
I wasn't sure whether to put this with the existing Mummy tests or do add it as a Protective Pads test (which is what it is atm). It tests both general Pads behavior as well as specific Mummy behavior.
I'm not sure if separate tests are wanted for specific kinds of ability effects that Pads blocks (like Iron Barbs) as well as item effects (Rocky Helmet)?
=> Add unit test for Protective Pads/Mummy interaction

test/simulator/items/protectivepads.js
I tried to cover all possible code paths with this - except the abilities like Flame Body and Cute Charm due to their unreliable activation chances.
=> Extend Protective Pads unit tests

data/abilities.js, data/items.js, data/moves.js, data/random-teams.js, data/scripts.js, data/statuses.js, mods/gen1/random-teams.js, mods/gen1/scripts.js, mods/gen1/statuses.js, mods/gen2/items.js, mods/gen2/random-teams.js, mods/gen2/scripts.js, mods/gen2/statuses.js, mods/gen3/abilities.js, mods/gen3/items.js, mods/gen3/random-teams.js, mods/gen4/random-teams.js, mods/gen4/statuses.js, mods/gen5/moves.js, mods/gen5/random-teams.js, mods/gen5/statuses.js, mods/gen6/random-teams.js, mods/gen6/statuses.js, mods/gennext/abilities.js, mods/stadium/scripts.js, mods/stadium/statuses.js, sim/battle.js, sim/prng.js, test/simulator/misc/prng.js
Often, you just need a random boolean. Throughout Pokemon Showdown's code, there are many creative ways of requesting random booleans. For example:
```js
if (this.random(10) < 3) {
if (this.isWeather(['sunnyday', 'desolateland']) || this.random(2) === 0) {
let shiny = !this.random(1024);
if (uberCount > 1 && this.random(5) >= 1) continue;
if (!this.random(3)) ability = ability1.name;
} else if ((ability === 'Iron Barbs' || ability === 'Rough Skin') && this.random(2)) {
if (typeof secondary.chance === 'undefined' || this.random(256) <= effectChance) {
if (accuracy !== true && this.random(256) > accuracy) {
```
Enable these methods to converge by introducing the PRNG#randomChance function. It accepts a probability and returns true with that probability.
Notes for reviewers:
* Commits are …
=> Refactor random booleans into randomChance function

config/formats.js
* The OU Banlist link is from 2016 and is heavily outdated, and it's inconsistent with other tiers
* The UU Viability Ranking thread was actually outdated
* The NU Sample Teams link was changed because the link currently leads to the NU Bazaar, which is a different thread than NU Sample Teams
=> Update format links

sim/battle.js
According to `git grep getResidualStatuses`, the Battle#getResidualStatuses function isn't referenced anywhere. Delete the definition of that unused function.
=> Delete dead code

chat-plugins/datasearch.js
It was only looking for it in the secondary effects of the move, which partial trapping isn't.
=> Fix movesearch for trapping moves

config/formats.js
@TheImmortal 
this seems to be the case with all suspect ladders that unban a Pokemon for their suspect.
=> Allow UU's suspect test to be playable via challenge

chat-commands.js
Especially in slower chats, the `|notify|` event sitting in the last 100 messages sends extra highlights that a lot of users find annoying. This change only highlights users at the time of the declare.
=> Declares: Only notify when the declare is used

test/main.js
Every time I run this unit test, as part of the whole suite or separately, I get a warning message and TypeErrors because the battle is destroyed before ``updateRating()`` is done with it (or probably before it's even called).
Adding a slight delay before destroying the battle fixes it for me, but of course it is a rather ugly solution. I'd very much like to enforce the sequence of events programmatically, but there doesn't seem to be a way to have updateRating be called synchronously.
=> Unit tests: prevent expired battle warning message

users.js
The punishment methods do not impose any order on the affected alts that are returned from them. In particular, the first element is not always the original target user, which the alt list reporting wrongly assumes to always be the case. This can lead to the target user being reported as an alt of itself while an actual alt is missing.
Another possibility would be refactoring the punishents to return {targetUser, alts}, that way the separation would be somewhat enforced and documented.
=> Fix reporting of punished alts

chat-plugins/datasearch.js
Currently, for some old gens ds, it is possible to a mon and the base form to appear, such as
This is due to the mods/gen6/pokedex.js file having only a few mons (the lati@s-mega pair being one), and those mons appear earlier in the dex than the base forms, which normally doesn't happen.  This commit sorts the mons before checking for base forms, so it should fix this, and results are sorted at the end anyways so it shouldn't change the order of results.
=> Dexsearch: fix error in old gen ds

chat-plugins/datasearch.js
`/ds all, !gen6, !gen3` will return all Pokémon not in gen 3 or 6.
`/ds all, !gen6, gen3` will return all Pokémon in gen 3 (like in the old code).
`/ds all, gen3, gen5` will return the message `a pokémon can't have multiple gens`
Also makes `/ds maxgen[n]` work with the "all" parameter, because it didn't before and it probably should
=> Datasearch: Allow exclusion of multiple gens

chat-plugins/info.js, chat.js, config/formats.js, data/abilities.js, data/aliases.js, data/formats-data.js, data/items.js, data/learnsets.js, data/moves.js, data/pokedex.js, data/random-teams.js, data/rulesets.js, data/scripts.js, data/statuses.js, data/typechart.js, dev-tools/global.d.ts, dev-tools/globals.ts, package.json, room-battle.js, sim/battle.js, sim/dex-data.js, sim/dex.js, sim/index.js, sim/pokemon.js, sim/side.js, sim/team-validator.js, tsconfig.json
Also removes Battle Factory methods accidentally re-added in d0a4a689a721ceb602a3d812a332d3080b5e881e.
Sorry for the large changelog but it was easiest to do everything together. I had to split <code>Format.desc</code> into <code>desc: string</code> and <code>threads: string[]</code> to be able to reuse other interfaces. Otherwise though, the additions are just simple type guards and <code>@ts-ignore</code> everywhere else (until it can be verified that nothing breaks).
=> Typescript data/ and config/formats

data/abilities.js, test/simulator/abilities/rockhead.js
onDamage is called in valid situations that don't have activeMove set, such as switching into hazards.
Admittedly, I don't know if `&& this.activeMove` is enough to stop a TS error (which I assume was the reason for adding this) from coming right back, but this is crashing a lot of battles right now.
=> Fix Rock Head throwing errors in valid situations

data/items.js
Same thing as the Rock Head situation. Putting a condition for ``activePokemon´´ around it filters out all effects not caused by the active move, I think. Then again maybe this time we can just check for activeMove straight away? If activeMove is not set but should be, chances are activePokemon will also happen to not be set?
=> Fix Protective Pads throwing errors in valid situations

data/moves.js, test/simulator/moves/pursuit.js
https://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/post-7730273
To do: check whether this actually applies to generations older than 6.
=> Pursuit should not move before a switch when targeting an ally

config/formats.js
https://www.smogon.com/forums/threads/350-cup-leader%E2%80%99s-choice-shadow-tag-is-now-banned.3589641/page-5#post-7748564
=> 350 Cup: Ban Shadow Tag (+ Mega Gengar)

chat-plugins/modlog.js
"[^a-zA-Z0-9]" does not match the end of the string.
=> Modlog: fix matches at end of line

data/random-teams.js
- Fixes Golem-Alola's Return not being counted as STAB, which would cause the set Return/Earthquake/Stealth Rock/Toxic to have a move rejected in favor of STAB.
- Having Conversion in Porygon-Z's moveset now counts for exactly once for STAB and Adaptability, instead of making every move count as STAB but not for Adaptability.
- Fixes Protean making moves that are STAB anyway count as two STABs each.
- Now STAB moves (except those granted by Conversion and Protean) count for 0.1 extra move in their category for the purposes of determining a moveset's `setupType`. This means that, in the case of a tie between physical and special setup, the tie will be broken by which side has more STABs, instead of such a tie always going to special setup by default. This fixes a case where Arceus-Dragon …
=> Random Battle: Improve STAB detection/rejection

sim/battle-stream.js
I'm assuming you don't want `'\n' + null` either.
=> Properly check for battle before logging crash

config/formats.js
https://www.smogon.com/forums/threads/350-cup-leader%E2%80%99s-choice-rufflet-and-arena-trap-are-now-banned.3589641/page-6#post-7756773
=> 350 Cup: Ban Rufflet and Arena Trap

sim/dex.js
The name (and presumably id?) of the typed formes is incorrectly overwritten when applying the type-changing effect. See #4600.
=> Fix name of Arceus/Silvally templates

chat-commands.js
Being able to send 100KiB messages whenever they want this easily
isn't a good idea. Limiting to 8KiB makes it harder for workers to
block.
=> Limit /code characters to 8KiB

sim/team-validator.js
Reported [here](https://www.smogon.com/forums/posts/7763801). `doublesTier` defaults to the same as `tier` so when the tier is banned the ban shows twice if it doesn't have a specific doubles tier.
=> Show only one tier validation problem

chat-plugins/poll.js
It was a little weird not seeing the results of an ended poll until someone spoke. I'm guessing it was unintentional?
=> Poll: Call Room#update in Poll#end to immediately display results

chat-commands.js
It seems that this code made it both groupchats AND private rooms not log roomunbans.
=> Modlog: Make sure "Private Rooms" log UNROOMBAN message

config/datacenters.csv
[67.219.112.0/20](https://whois.arin.net/rest/net/NET-67-219-112-0-1/pft?s=67.219.112.0) is owned by Nextlink Broadband now. The rest is still owned by Razor though.
=> Fix outdated data center IP range

chat-commands.js, chat-plugins/helptickets.js, chat.js
Fresh from the policy table.
Also gives users tips on handling semilocks to reduce the number of those tickets we get.
=> Help Tickets: Allow ticket creators to close their own tickets

chat-plugins/helptickets.js
The roomintro/staffintro of help tickets was different between newly created ticket rooms and reactivated existing ticket rooms. In particular, for the latter, the order of escalate/close ticket was switched and it was missing the contexts stuff.
=> Normalize room/staffintro of helptickets

data/scripts.js, sim/battle.js
These were apparently relying on default behavior that they really shouldn't have been anyway. Granted, I was the one who set up that default behavior _and_ the one who took it out from under them...
=> Fix failure messages of nonstandard healing moves (again)

sim/pokemon.js
In retrospect this was obvious.
=> Fix type display in camomons after switching out

config/datacenters.csv
From what I can tell, KW Datacentre had a part of their range [reassigned to a consumer ISP](https://whois.arin.net/rest/net/NET-45-62-220-0-1/pft?s=45.62.220.0).
=> Update datacenter ranges

data/moves.js, data/scripts.js, sim/pokemon.js, test/simulator/moves/stompingtantrum.js
Since nobody apparently felt like doing the easy solution, I did the hard one.
=>  Stomping Tantrum should never get boosted the turn after hitting Protect.

chat-plugins/info.js
Using a link shorteners here REALLY should be avoided because PS is for kids and lots of kids networks block link shorteners, which would then make them unable to actually see the rules, which defeats the purpose.
=> Rules: Increase link limit to 150 characters

data/moves.js
As if it was Glare/Poison Gas/Spore/Toxic in the first place. Reported in Known Mechanics Bugs.
=> Psycho Shift should fail verbosely

data/moves.js, sim/pokemon.js, test/simulator/moves/transform.js
Looks like we'll have to hard-code something Roost-related after all.
=> Transform should ignore Roost's effects

data/formats-data.js, data/random-teams.js, mods/gen6/formats-data.js, mods/gen6/random-teams.js
Update Flare Blitz vs Fire Blast rejection to prioritize Flare Blitz if
the Pokemon has Reckless as an ability. Also change Stone Edge to Head
Smash to further capitalize on the ability.
=> Random Battle: Fix Flare Blitz Emboar

data/moves.js
This includes when the move is a Z-Status move, in which case we'd be able to find the move's id in the target's learnset.
Thanks to Merritt from the Smogon forums for testing this for me, and also verifying the results of the other relevant moves, although their effect on Z-Status moves has already been fixed by #4298.
> Conversion 2: Z-Will-o-Wisp was used, Conversion 2 was used, Porygon-Z transformed into a Water type (move worked).  
> Copycat: Z-Will-o-Wisp was used, Copycat was attempted without animation, text displayed "But it failed!"  
> Disable: Z-Will-o-Wisp was used, Disable was attempted without animation, text displayed "But it failed!"  
> Instruct: Z-Will-o-Wisp was used, Instruct was attempted without animation, text displayed "But it failed!"  
> Mimic: Z-Will-o-Wisp …
=> Disable, Mirror Move and Spite should fail against a Z-move

data/abilities.js, data/moves.js, dev-tools/globals.ts, test/simulator/abilities/symbiosis.js
Reported [here](https://www.smogon.com/forums/threads/bug-reports-v3-0-read-op-before-posting.3634749/post-7809895) for Symbiosis passing Aerodactylite to an Aerodactyl but also seems to affect using Bestow to pass a Drive, Mega Stone, Memory, Plate etc. to its user or for that user to use Thief or Covet to steal it.
The code for Covet and Thief resembled that for Trick and Switcheroo (which don't have the bug) so they were easy to adapt but for Bestow and Symbiosis I thought it better to copy the Switcheroo code to make future maintenance easier.
=> Fix Bestow, Covet, Symbiosis and Thief with a required item

mods/gen3/moves.js
The desc was updated to reflect that it can miss in Hail there, but the shortdesc wasn't.
=> Fix Blizzard short description in gen 3 and earlier

data/formats-data.js
Quagsire was never PU outside of its alpha stage, which does not count towards tiering.
=> Quagsire should be NU

sim/pokemon.js
Fix for "Illusion should display the Illusion Pokemon's actual level, not the level of the target it is disguised as." from Issue #2367. Illusion user's level is now displayed instead of the level of the Pokemon being displayed.
=> Fix Illusion to display Users level instead of Illusions level

data/moves.js
Mostly so the priority is made clear in the teambuilder.
=> Add priority note to Water Shuriken shortdesc

sim/battle.js
A quick fix I put in for this bug. I would love some feedback, I am not 100% sure exactly what happens in the BeforeFaint state, what it means to be in the faintQueue or if this should return for all boosts in this state(I had event id checks but took them out thinking this should return at this state always?).
Thank you for any feedback provided :D
(refs #2367 Any effect that changes stats after the final Pokemon is KOed in battle should not activate)
=> Prevent effects from changing stats after final Pokemon is KOed

data/formats-data.js, data/random-teams.js
Rest and Sleep Talk are very uncommon on Gyarados. Removing them allows
for a higher chance of using Gyarados' most popular set, Dragon Dance +
Bounce with Flyinium Z.
=> Random Battle: Improve Gyarados

chat-plugins/trivia.js
Note: this is planned to be reverted after August, but it's needed for the event that's going on throughout the month.
=> Trivia: Don't allow voices to search questions

chat-plugins/datasearch.js
Since `entries()` will reflect changes to the array it's based on, it will skip the element immediately following one that was deleted from the array. Doing it in reverse avoids that, and I didn't find a way to do a reverse iterator, hence the `map()`.
=> Itemsearch: Fix some results not being the best match

sim/team-validator.js
Reported [here](https://www.smogon.com/forums/posts/7858923).
When validating event-only Pokémon, the team validator performs a fast validation, then fixes up the gender afterwards. However, when validating Pokémon that are only limited by event-only moves, the team validator fails to fix up the gender. Worse, it doesn't know which event ended up validating, since it isn't calling `validateEvent` directly. To address this, validating an event now sets the gender if the validation is successful and the event specifies a gender, even for fast validation. This also means that the gender fixup code for validating event-only Pokémon can be removed.
=> Set gender when validating restricted sources

sim/battle.js
Reported [here](https://www.smogon.com/forums/posts/7869706).
#3211 wants to pass in the Z-move to avoid Triage boosting a Z-powered draining move. However, it didn't check that the move it got was actually a Z-move. This means that Prankster ended up modifying the wrong move.
=> Followup to #3211 to ignore Z-status moves

config/formats.js
Reported [here](https://www.smogon.com/forums/threads/posts/7870569).
This is basically just cut'n'paste from Zygarde-Complete.
The reason I overlooked this is that ROM puts all of this code in `formeChange` because we've already calculated the new `maxhp` anyway:
if (this.hp) {
let maxhp = this.template.maxHP || stats.hp;
this.hp += maxhp - this.maxhp;
this.maxhp = maxhp;
}
Much more readable IMHO.
=> Recalculate max HP after devolving

config/formats.js
... because `cureStatus` does nothing when you have 0 HP.
=> Followup to #4788 to cure status after setting (max) HP

chat-plugins/datasearch.js
It should not force exactly one space between the comma and "all" to actually display all items (spaces after commas matter just about nowhere else). Especially because, if it's formatted in any other way, it doesn't error out, it just considers "all" a search term, which is doubly wrong.
Now that I think about it, maybe it shouldn't even force the "all" to be at the end, in order to be even more consistent with /ds and /ms. On the other hand, I think that's way less likely than this scenario.
=> Itemsearch: make 'show all' parameter independent from whitespace

config/formats.js
#4788 removed the HP setting from before the `formeChange` because I mistakenly thought it wasn't necessary now that the HP was being recalculated manually (as opposed to having `formeChange` do it for you) but of course you need to have HP for most effects to work and #4791 was the wrong fix, so this undoes #4791 and also restores the (now temporary) HP from #4788.
=> Properly fix Benjamin Butterfree effects

data/factory-sets.json, data/random-teams.js
OU set changes: https://pastebin.com/gsYEEnP6
NU set changes: https://pastebin.com/v3r3LduC https://pastebin.com/6rfDFCJT
PU set changes: https://pastebin.com/Yft1g9L1
LC set removal reasoning:
- [1:03 PM] Quote: remove axew, anorith, venipede, tyrunt, cranidos, skrelp, magby, spinarak, darumaka, deerling, dratini, goldeen, inkay, lileep, mankey, natu, sandile, stufful, sandshrew, tentacool, budew, cubone, dewpider, fletchling, honedge, lickitung, remoraid, stunky, treecko, teddiursa, minccino, rowlet
- [1:03 PM] Quote: that's mostly a list of shitmons that have no place in BF
- [1:04 PM] Kalalokki: wait all of those?
- [1:04 PM] Quote: yes. They're all mons that are super low on our VR
- [1:04 PM] Quote: or not even on the vr any more
- [1:04 PM] Kalalokki: aight
The changes in …
=> Battle Factory: Update sets

data/scripts.js
Reported [here](https://www.smogon.com/forums/posts/7876938) and elaborated on in the next post.
Note that prior to commit d46abff the called move did not get checked, so `baseMove` would have been the same as `move` when it was a dance move, and Dancer didn't get to copy called moves.
Copying a Z-powered status Dance move, or a Dance move called from a Z-powered move, still seems to work.
=> Make Dancer copy the called Dance move

data/factory-sets.json, data/random-teams.js
I also removed Kingler's PU sets since it was banned and I figured I might as well do that.
The issue with the current check is that it just completely skips over Mega Evolutions that change types on every team, including stuff like Mega Gyarados on a Water team.
=> Battle Factory: Fix Mega checking and remove Kingler from PU

chat.js
Bug introduced in https://github.com/Zarel/Pokemon-Showdown/commit/6ed64cf0c24e3b5967d512827e7700702d866f6d
=> Chat: Fix HTML commands in PMs

config/formats.js
Not 100% done but PRed now as per TI's request.
https://www.pokemon.com/us/pokemon-news/get-ready-for-a-legendary-video-game-championships-season/
Your Time needs to be increased to 7 minutes (up from 5) in all formats.
~~Teambuilder is also trying to validate for "gen7vgc2019" rather than the actual format ID, which I am looking into currently.~~
=> Add VGC 2019 formats

mods/gen2/formats-data.js
Mew doesn't learn Recover. Probably a copy-paste error from the similar Mewtwo set.
=> Gen 2 Randbats: Fix typo

data/random-teams.js
Because of operator precedence, there are situations where Flyinium Z
will ignore the Z Crystal check and be selected on a Pokemon regardless
(most commonly on Swords Dance Talonflame).
=> Random Battle: Fix Flyinium Z appearing with other Z Crystals

data/moves.js
Commit 27745ad removed the short descriptions for Aqua Ring and Mirror Move. Commit 21cf8fb then incidentally restored the short description for Aqua Ring but Mirror Move's short description still seems to be missing.
=> Restore Mirror Move's short description

chat-plugins/info.js, chat.js
Also inlined Chat.addBox to prevent code duplication and updated relevant help commands.
This is currently planned to be used with hosting in Tournaments, but it could be useful for other rooms too.
=> Support staff-only HTML boxes

data/formats-data.js, data/random-teams.js, mods/gen6/formats-data.js, mods/gen6/random-teams.js
Hidden Power Fire has virtually no useful coverage for a Pokemon that
should always have a Water move, and Defog is a popular move on
Empoleon. Also add rejection for Defog+Stealth Rock similar to the
already-existing Defog+Spikes rejection.
=> Random Battle: Update Empoleon

chat-plugins/info.js
A user asked me about this, so apparently some people actually do this. The parsed dex number is being compared to the full, non-id target anyway, so I don't think this will introduce any other weird cases.
=> Allow /dt to find CAPmons by their dex number

chat-plugins/info.js
The type from the argument was called ``type``, and the defensive type iteration var was also called ``type``. As a result, the result was actually a list of effectivenesses of each type against itself.
=> Fix /coverage with type arguments

data/factory-sets.json
Updated the sets to match this: https://docs.google.com/spreadsheets/d/1tbC779QTEa1aX8UcOzl_MLfG9SIHshrieW-xGfuEK5w/edit#gid=0
The spreadsheet had some illegal sets, such as Necroma-Dusk-Mane with Neuroforce as opposed to Prism Armor, but those are fixed in the sets here
=> Battle Factory: Update Ubers

data/moves.js
When using Sky Drop on a Flying-type, the "freed from Sky Drop!" message displays twice.
[Before fix](https://imgur.com/kyhws2H)
[After fix](https://imgur.com/o2LXBKh)
=> Fix double Sky Drop message

chat-plugins/chat-monitor.js
And change spacing of help command to match the rest
=> Chat monitor: Add some aliases

chat-plugins/info.js
What's in the username span will be part of the user page link (both in terms of linkification and URL), so the punishment message being in there screws that up.
=> Fix user popup for locked alts in /ip

config/formats.js
This allows Pokemon that still share one type with the "God" after mega evolving to be on the team (i.e. Gyarados -> Mega Gyarados on Yveltal teams still should be legal, since Gyarados shares Flying and Mega Gyarados shares Dark).
=> G&F: Fix Mega Evolution validation again

sim/team-validator.js
The move being listed as `hiddenpowerfairy` is handled by the "does the move exist" check.
This validates that the set's `hpType` slot is a valid type in the generation that is being played (and that its not Fairy ever).
=> Validator: Validate Hidden Power Type

data/abilities.js
Changed ability to allow pokemon under Flower veil to inflict statuses onto themselves using Safeguard as reference
Changed ability to follow the yawn interactions like Safeguard does
Issue brought up by User doipy hooves in https://www.smogon.com/forums/threads/bug-reports-v3-0-read-op-before-posting.3634749/page-17 
Other references:
https://bulbapedia.bulbagarden.net/wiki/Flower_Veil_(Ability)#In_battle
https://bulbapedia.bulbagarden.net/wiki/Safeguard_(move)#Generation_V_onward
=> Fix Flower Veil interaction with Self Inflicted Status and Yawn

chat-plugins/datasearch.js
This will prevent Vulpix showing up in, e.g. 
since Vulpix is banned as "Vulpix-Base".
=> Dexsearch: Stop vulpix appearing in lc searches

lib/fs.js
PS's FS(...).writeUpdate(...) has a `throttle` option.
This changes it so it's possible to call it with the throttle on sometimes and off sometimes, and "throttle off" will pre-empt "throttle on" calls.
I'm pullreqqing because this took me a lot of thinking so I could use a code review.
=> Improve FS throttle

sim/pokemon.js
From issue: https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-381371924
Removed Autotomize from pokemon who undergo formeChange in battle
Needs fix for Client representation to represent this and have the change be silent (submitted fix there)
Replay download showing it works on the server side: https://drive.google.com/file/d/1LdIgE0evOpPWvAbbGFrFL-GLa51XXWmQ/view?usp=sharing
=> Fix Forme Change and Autotomize Interaction (Server Side)

chat-plugins/othermetas.js, data/abilities.js, data/moves.js, data/random-teams.js, data/scripts.js, dev-tools/globals.ts, mods/gen1/moves.js, mods/gen1/scripts.js, mods/gen2/scripts.js, mods/gen2/statuses.js, mods/gen3/scripts.js, mods/gen4/moves.js, mods/gen4/scripts.js, mods/gen6/abilities.js, mods/gennext/moves.js, mods/gennext/scripts.js, mods/mixandmega/scripts.js, mods/stadium/scripts.js, sim/battle.js, sim/dex.js
The types `Template`, `Move`, `Ability`, and `Item` are now read-only. This should guard against accidental writing to types that shouldn't be written to.
A new type, `ActiveMove`, has been introduced. Like it sounds, it's used for moves that are currently actively being used. A lot of attributes that are only relevant to active moves, such as `hasBounced`, are now only available on `ActiveMove`, not on `Move`. `ActiveMove`s are mutable, unlike `Move`s.
`Dex.getMoveCopy` has been renamed `Dex.getActiveMove`, to better reflect its role. `.isCopy` has been deprecated, and distinguishing `Move`s from `ActiveMove`s is now done by `typeof move.hit === 'number'` where necessary.
`ActiveMove`s now internally track which hit of a multihit move they're on, in `move.hit`, so `move.hit` doesn't need …
=> Introduce ActiveMove; make Template/Move/Ability/Item read-only

mods/mixandmega/items.js, sim/pokemon.js
This fixes permanent Desolate Land and a crash when using a primal Orb on a Pokemon with Illusion in Mix and Mega.
Replays showcasing said crash:
https://replay.pokemonshowdown.com/gen7mixandmega-818477762 (Red Orb)
https://replay.pokemonshowdown.com/gen7mixandmega-818477500 (Blue Orb)
@TheImmortal (or anyone who can merge this, really)
=> Mix and Mega: Fix Illusion

data/moves.js, mods/gen1/moves.js, mods/gen2/moves.js, mods/gen3/moves.js, mods/gen4/moves.js, mods/gennext/moves.js, mods/stadium/moves.js, sim/battle.js, sim/pokemon.js
A pull was recently merged to fix the issue of assurance not functioning properly in doubles (specifically, assurance doubling based on its original target, even if its target changed). The move still does not function appropriately, however, when called by other moves (e.g. see https://replay.pokemonshowdown.com/gen7doublescustomgame-797443987, when it is used by Me First). This pull fixes this by removing the reliance on a volatile status condition and instead applying a "hurt" tag to Pokemon when they receive (non-direct) damage.
=> Fix Assurance never doubling when called from other moves

test/application/chat.js
A lot of complexity in a chat formatter link regular expression is to support links with parentheses in them. This commit introduces a test of this to avoid accidentally breaking this functionality.
=> Test links with parenthesis

mods/gen4/moves.js
At least the description was correct
EDIT: Maybe I should actually explain what the PR does. Right now, using Nature Power in a Gen 4 game will call Earthquake. This makes it call Tri Attack as expected.
=> Gen 4: Fix Nature Power

data/moves.js, data/scripts.js, data/statuses.js, mods/gen3/moves.js, mods/gen3/scripts.js, mods/gen4/moves.js, mods/gen4/scripts.js, mods/gen5/moves.js, sim/battle.js, sim/pokemon.js, test/simulator/misc/typechange.js, test/simulator/moves/roost.js
From #2367:
>The target of a failed [move] should be ambiguous to both players; that is, the animation shouldn't play out. This happens with...moves that bring up the message "But it failed!", like Fake Out, Disable, etc., so it can probably be generalized in this way.
>Using a move blocked by Primal weather should not reveal which slot was targeted
~~This adds a new method to battles: `hideLastTarget`. It removes the target from the last `move` message and suppresses its animation.~~
This makes the `[still]` attribute hide the target from the same `move` message whenever it is added.
In addition, the target is ~~removed from~~ replaced with the source in `-fail` minors where it shouldn't be revealed.
Currently, changes are only applied to `-fail` minors where the target could have been …
=> "But it failed!" messages should not reveal the target

config/formats.js
I also removed the array check from move.multihit because it causes moves such as Triple Kick to do this https://replay.pokemonshowdown.com/gen7fortemons-829648311
=> Fortemons: Fix calling 'onHit' in moves with a forte that also has a self

data/formats-data.js
They were always PU by usage, but got looked over. Nobody noticed until now because they're both banned from ZU.
=> Crabominable and Carracosta should be PU

data/formats-data.js
It learns it in USUM and it's much better hazard removal for it because
Hustle gives Rapid Spin a chance of missing, and the evasion reduction
helping its other moves affected by Hustle.
=> Random Battle: Add Defog to Delibird

config/formats.js, dev-tools/globals.ts
* Fix a bug from #4949 that made self-effects not always merge
* If the forte has a `self.onHit` it is now triggered properly (Burn Up, Rapid Spin fortes)
* Allow primary self-boosts and secondary self-boosts to both happen (the weird `onModifySecondaries` hack) e.g. Flame Charge -> V-Create
* Properly implement Fell Stinger and Relic Song as fortes
* Fix crit ratio adding (previously it was causing way too many crits which people were complaining about)
* Implement Knock Off as a forte
=> Fortemons: Fix several moves

test/main.js
A few tests rely on hardcoded groups, which breaks the test if they're different.
=> Use default config for tests

chat-plugins/scavengers.js
- Enable all game creation/moderation/leaderboard commands for subrooms/groupchats
- Disable all staff information commands, or global staff control commands for subrooms.
- Setpoints and Setblitz will be reported to the main room if used in a subroom groupchat, as the Room owners are changed.
This has been approved by Meicoo.
=> Scavengers: Enable for subrooms

data/statuses.js
Im not sure if this is how it works but ive tested it and it works. Idk if the same applies to future sight so thats why im uneasy. 
reported here https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-421827399
=> Doom Desire is affected by Adaptability &Normalize

data/moves.js, data/scripts.js, data/statuses.js
PR #3523 attempted to fix the bug that lack of target checking was being done before the move's charge status was checked. However, there were two problems with that fix:
1. There was no fix for Razor Wind, whose target checking is on a different code path.
2. The fix broke Gen 6 Triples battles. For example, it allows Solar Beam under sun to target a distant foe if you have no adjacent foes.
To address these problems, I've moved charge checking before target checking. However, Solar Beam under sun without an adjacent foe still tries to animate the move even though it now has no target. To address this, I reversed the behaviour so that charging moves have to `[still]` themelves; if the move is on its second turn or the move is powered to execute in one turn then it animates normally, …
=> Fix charge moves without target

mods/gen1/moves.js, mods/gen1/scripts.js
Gen 1's script didn't have the `singleEvent` for `TryMove`.
I also removed the inheritance for Rest's `TryMove`, because I'm not sure Gen 1 wants it.
=> Fix charge moves in Gen 1 again

mods/ssb/moves.js
Zero boosts are currently not allowed.
=> Fix Tipping Over when the boosts are not removable

mods/gen1/moves.js, mods/gennext/moves.js
Another follow up to PR #4974.
For Gen Next, the charged `-anim` will be inherited from PR #4978. (I don't think Skull Bash can be charged in Gen 1, can it?)
=> Fix Skull Bash variants

chat-plugins/datasearch.js, sockets.js, team-validator-async.js
8a88385 removed the `isException` parameter from `crashlogger` but there are a few callers which are still trying to pass `true`.
=> Remove obsolete crashlogger parameter

chat-plugins/helptickets.js
Chat.html escapes all HTML within interpolated values. This was unfortunate in this case, because it tried to interpolate actual HTML for the roomintro hint. I've split it off into a separate string..
=> Help tickets: Correctly display hint in intro

config/config-example.js, sockets.js
The sockets code does an `lstat` of the path to check that it's a file, but that fails for a symlink. I think it should do a `stat` of the path instead.
Additionally, your example config includes the reading of the certificate file, but the sockets code already does this (and in fact it warns if you don't pass the path).
=> Allow SSL options to point to symlinks

data/moves.js
Sleep Clause only activates when the target and source side are not the same. If no source is given in ``trySetStatus``, it will default to the target. I'm honestly not sure what broke this (or, conversely, why it worked before), since I see no recent changes in the ruleset or the move mechanics.
=> Fix Yawn ignoring Sleep Clause

data/moves.js
Not sure if this matters for anything, but since the [of] presumably describes who used the move in the [from], it should always be the source.
=> Fix Defog move attribution

chat-plugins/datasearch.js
This fixes an off-by-one bug where `/ms priority+` returned every move with priority more than, but not including, 1. It also makes `/ms priority` do the same thing as `/ms priority+` rather than giving an unhelpful error message.
=> Fix priority in /movesearch

data/items.js, test/simulator/items/leppaberry.js
This fixes https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-443505854
If I understand correctly, the Leppa Berry is normally eaten when any move is at 0 PP, and restores 10 PP to the first move with 0 PP. If the Leppa Berry is forcibly eaten through means such as Fling, it restores PP to the first move that has any PP missing. If all moves have full PP, nothing happens.
Thank @SadisticMystic for the research
=> Fix Leppa Berry

data/abilities.js
needs to mention its activation message triggers before other abilities regardless of Speed tiers, unlike pressure / trace / whatever
=> dex: clarify unnerve's description

data/scripts.js
As [mentioned](https://github.com/Zarel/Pokemon-Showdown-Client/pull/1186#issuecomment-443384470) in client PR 1186.
=> Use -fail instead of -notarget in Gen 5 or later

data/moves.js, sim/battle.js, test/simulator/abilities/magicguard.js
I wasn't really sure what a more appropriate way to do this would have been, since just using `recoil` would make Rock Head block the damage, I believe.
=> Magic Guard should block crash damage

sim/pokemon.js
Slightly interesting anecdote: I first came across this bug when bruteforcing Metronome battles on TwitchPlaysPokemon.
=> Disabling effects should disable every slot the move is in

sim/battle.js
It's a big pet peeve, but it did also cause information leaks, such as http://replay.pokemonshowdown.com/gen7vgc2019sunseries-832087568 where Jynx's speed was revealed via Perish when it should have already fainted.
=> Faint Pokemon after every residual

sim/pokemon.js
When a move is used, a target is resolved, and then later an array of targets is determined.
In the case of a single-target move, the target is adjusted for validity when it is resolved, and then again in case of redirection, and the log is updated to show the actual target.
In the case of a spread move, a random target is initially chosen and logged, and this does not get updated. Fortunately if the move turns out to have multiple targets then these targets are logged and the move animates correctly. However if the move only turns out to have a single target then it animates to the random target and not the actual target.
This is usually only a problem in triples battles as the random target may not be a suitable target, but I think the problem might also surface in doubles if both foes …
=> Ensure spread moves log a valid target

data/moves.js, test/simulator/moves/stompingtantrum.js
https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-435642464
When I implemented this originally, I'd seen someone say this worked the other way around, so to get it to match on sim I had to put in some hard-coded hacks. Fixing this was as simple as taking them out.
=> Fix Stomping Tantrum interaction with spread moves and Protect

chat-commands.js
Approved by bumba.
It's not uncommon to see roomdrivers mute / hidetext / unmute for things that shouldn't be in chat but don't necessitate any hard punishment, I don't see why it shouldn't be allowed directly.
=> Allow roomdrivers to hidetext anytime

data/abilities.js
In-game, I tested Forewarn against a moveset with both Horn Drill and Prismatic Laser; Prismatic Laser was the alerted move 20 consecutive times. Figuring that's a particularly unlikely cold streak, I then tested Horn Drill vs. Hyper Beam and both moves were able to get noticed, showing that it's really a tie at 150, and not a tie with 160.
The extra clause for CFZs isn't particularly relevant, but it's true so we might as well be complete there.
=> Fix up Forewarn powers

mods/letsgo/random-teams.js
Removing AVs allows for level scaling to come in the near future, and the happiness being set to 70 makes the battles match in-game wifi mechanics. @TheImmortal
=> Let's Go: Add happiness to random battles, remove AVs

config/formats.js
[10:00:13] Skull Knight (Kalalokki): Kris or anyone that does tiering pullreqs, Type:Null is supposed to be ZUBL but it's allowed in ZU still after the tier shifts
=> Ban Type: Null from ZU

data/formats-data.js
Crabominable didn't reach the PU usage threshold, but it was overlooked.
=> Fix Crabominable's tier

config/formats.js, mods/pic/moves.js
This bug was reported on December 14th, at which time I wrote a fix for my side server and then promptly forgot about it:
> I also had a game where (under trick room) my gastro got skill swapped Download but it didn’t activate on my stakataka is this a bug or not?
Then on January 3rd that the same user tripped over a crash:
> https://www.smogon.com/forums/attachments/07f5997d-bf3b-4b38-9593-e943ef5fdfff-png.153898/
I asked them to try playing on my side server in case my bug fix also helps with the crash, which apparently it does.
=> Fix bug in Skill Swap in Partners in Crime

chat-plugins/helptickets.js
Currently, the "User is no longer interested in this ticket. User closed this ticket" will _always_ be shown, even if the ticket was closed already.
=> Helptickets: Prevent superfluous messages when closing

sim/battle.js
It would make sense to short-circuit past a modifier step if it's just going to be *4096 and then /4096. But if you're going for accuracy, it makes a difference in the case where the preexisting value is an exact multiple of 1048576 (in which case it becomes 0), and I can prove that the actual game does apply these seemingly useless modifiers, so here we go.
=> Apply modifiers even when they are exactly x1

chat-plugins/datasearch.js
Reported [here](https://www.smogon.com/forums/posts/8010759). `evos` includes later generations, so we need to check their generation.
=> Fix /ds1 lc

data/abilities.js
Fixes Drapion, who has 3 different abilities with a rating of 1. Keen Eye is
less useful than Battle Armor or Sniper because of a lack of accuracy
reduction moves in random battle, so this ensures that it is not chosen.
=> Random Battle: Lower Keen Eye rating

data/moves.js, sim/battle.js
As discussed in client PR 1210, and also alluded to in #5064 (comment regarding damage effects named after moves which should not be whitelisted).
=> Rename crash damage back to (High) Jump Kick

data/moves.js, data/scripts.js, test/simulator/moves/fakeout.js
The approach from #5090 doesn't work since lastMove is evidently set too early in the process, and the sim thought that the currently-executing move was an existing lastMove.
This approach doesn't allow for the distinct hint messages handling each case, but the cases where it matters (trying to Instruct Fake Out, or having a Pokemon with Fake Out switch in, acquire Dancer, and use a dance move all in the same turn) are presumably rare enough that the people who attempt such things will understand about the slightly inaccurate hint message.
=> Trying another fix for Fake Out

sim/dex-data.js
In https://github.com/Zarel/Pokemon-Showdown/commit/f65ad5ab81b80cb3be2b3110515c21a1ca2446eb, removing Crucibelle-Mega from being marked as Gen 6 also removed it from being marked as a Mega Evolution, so now you can't choose its forme in the teambuilder with a base forme's ability.
=> Fix Crucibelle-Mega

data/random-teams.js
Fixes Skuntank (Pursuit/Sucker Punch/Crunch) and Spiritomb (Pursuit/
Sucker Punch/Dark Pulse) among others. Compare Foul Play rejection check.
=> Random Battle: Reject Pursuit if 3 Dark moves

chat-commands.js
Allowing modnotes to use multiple lines (but still appearing in modnotes unified) would make it easier to copy/paste user messages as needed for room moderation in the modlog.
=> Permit multi-line modnotes

tournaments/index.js
It's currently impossible to tell whether a user left the tour of their own accord or was disqualified by autodq, which makes noticing problems with autodq harder. This also should be a nice bit of transparency for regular users.
=> /tour leave: send a leave message instead of a forfeit message

chat-plugins/helptickets.js
I had to delete a few help tickets on my side server and noticed that the display still showed the ticket I'd just deleted until after I'd deleted the next ticket (which itself didn't go away until I deleted a third ticket.)
=> Notify after, not before, deleting a help ticket

config/formats.js, dev-tools/globals.ts, mods/pic/moves.js, mods/pic/scripts.js, mods/pokebilities/abilities.js, mods/pokebilities/scripts.js, tsconfig.json
ROM always passes a dummy object to `onModifyTemplate` but main never does.
Typescript complained that I didn't allow `innates` to be undefined, so I made the mistake of agreeing with it, but I missed a few null-checks.
=> Fix some OMotM crashes

chat-commands.js, chat-plugins/roomsettings.js
`/help` is rather incomplete for how often it gets recommended in the Help room, so I added a lot of useful commands to it that people should know about.
I'm not entirely sure about these command categories, but I figured I should split off commands that just return some text or links or information about PS/smogon vs those that give information about dex data, because otherwise that's a long list, and their use cases differ.
I made another section for battle room stuff because players should know about it but they're not that well documented if you don't already know they exist.
I added the help text for unlockname/ip because `/help unlockname` does not return the "unlock" help entry because the commands are not aliases, so it just says "help not found", which has happened to me like …
=> Update command documentation

server/chat-commands.js
This warning is strictly speaking correct, the URL isn't verified properly. However, in this case, this isn't a practical issue, as it's possible to use /forcebattleban command anyways.
=> Suppress LGTM's URL sanitization warning

server/chat-plugins/datasearch.js
Movesearching recoil moves is useful on Pokemon with reckless
=> Add Recoil as Move Search Parameter

server/chat-plugins/helptickets.js, server/chat.js, server/room-game.js
1. `~Staff` will prompt users to explain their issue when they open a ticket.
2. Tickets will not trigger highlights or be visible in the staff rooms until the user speaks in the ticket room.
3. Hovering over the view/claim buttons will now show a preview of the last two chat lines.
4. IP-Appeal and ISP-Appeal are exceptions to points 1 and 2, since the user doesn't need to provide any information.
5. Removed "Battle Ban Appeal" (depreciated punishment) and "Inappropriate Content" (misused 99% of the time) tickets.
=> Help Tickets: Require users to explain their issue before getting help

data/formats-data.js, data/mods/gen6/formats-data.js
Earth Power is one of its most used moves because of Steel trapping with
Magnet Pull, while Pain Split is almost unheard of in standard tiers,
and isn't very useful on it unless it has Sturdy (but Magnet Pull is the
better move and is rated higher)
=> Random Battle: Update Probopass

data/formats-data.js, data/mods/gen6/formats-data.js
Aqua Tail gives very minimal meaningful coverage since it mostly is
super effective on Pokemon already weak to Ground. Instead, give it Ice
Punch since it's much more common on it.
=> Random Battle: Update Rhyperior

config/formats.js, data/mods/pokebilities/scripts.js, sim/pokemon.js
Prior to commit c8d4463 this used to say `this.formeChange(this.baseTemplate);`. Typically this would pick up the empty effect created at the start of a battle. Because that effect has no effect type, this would exit early from the `formChange` code. However, that wasn't the only case, and so commit c8d4463 explicitly passed a null effect instead, so that the early exit would always apply. Unfortunately this means that `onModifyTemplate` cannot distinguish between a `clearVolatile` and a `transformInfo`. Since passing the empty effect used to fake everything out at the start of a battle, my best idea was to explicitly pass an empty effect so that everything else works again as they expect.
Note that passing an explicit `this.battle.getEffect('')` doesn't work because that effect still has …
=> Fake out form change when clearing volatiles so OMs still work

data/items.js, data/mods/ssb/scripts.js, dev-tools/globals.ts, sim/battle.js, test/simulator/items/seeds.js
Terrain seeds should activate only after switch-in abilities or when a new terrain starts, and should not activate after Magic Room ends.
=> Fix terrain seed activation timing

sim/dex.js
I've been taking a look at optimizing the simulator (see [pkmn.cc/optimize](https://pkmn.cc/optimize) - comments welcome), and `getEffect` seems ripe for improvements. I can't confirm this caching is 100% safe - I don't know if `Effect`s are supposed to be immutable or not, but the 'tests pass', for whatever that's worth. There's already caching for `Move`/`Ability`/`Item` etc, but `getEffect` only very rarely hits those code paths, so it's actually missing out on most of the benefit. 
This change should result in a **~30% increase in overall battle performance** over repeated runs, but if this caching would break things theres still some other options for restructuring the method for performance, as outlined in the doc. I think there's more performance gains to be had by refactoring …
=> Optimize Dex#getEffect by caching the result.

sim/dex.js
Not ideal from a static typing POV - I don't think this `@ts-ignore`s `PureEffect`/`Effect` any more than the original code did, but its still not very pretty.
=> Refactor Dex#getEffect + Dex#getEffectInner back to one method

data/pokedex.js, dev-tools/globals.ts, server/chat-plugins/info.js
The only thing this doesn't handle that I'm aware of is CAP mons' evolution method.
=> chat-plugins: Fix details to show all evolution methods

test/simulator/abilities/disguise.js, test/simulator/abilities/prankster.js, test/simulator/abilities/rockhead.js, test/simulator/abilities/truant.js, test/simulator/items/protectivepads.js, test/simulator/misc/choice-parser.js, test/simulator/misc/decisions.js, test/simulator/misc/fusion-combo.js, test/simulator/moves/counter.js, test/simulator/moves/trumpcard.js
#2444 indicates that tests should be migrated to use `makeChoices`.
- 6aa40b1 performs a straightforward migration of the Prankster test.
- 03b5b2c migrates to the doubles syntax but also uses `makeChoices` with no args instead of `commitDecisions`, since it should amount to the same thing
- 05fd9b1 takes this further, replaying all `commitDecisions` which just select the default with `makeChoices` instead.
I'm not sure all of these are desirable: 6aa40b1 seems relatively obvious, but I'm not sure if the idea is to remove `commitDecisions` entirely in the long term (calling it indirectly through `makeChoices` like I do in 05fd9b1 seems like a kind of roundabout way of doing things) or just `chooseSwitch`/`chooseMove`, it isn't clear from #2444.
After this, only …
=> Refactor remaining tests to use Battle#makeChoices

sim/battle.js
- rename `thing` when we know what it will be.
- simplify `resolveLastPriority`
- remove `findBattleEventHandlers` param given that its always this
- avoid multiple lookups of the same attribute
These functions related to finding events are very hot
(pkmn.cc/optimize) and microbenchmarks indicate TurboFan is unable
to extract out the constants for us. As a side benefit, there's less
`// @ts-ignore` required, and future optimizations will use the
constants anyway. More extraction can be done in findEventHandlers,
but that will be left for a future change where the need becomes
more obvious.
=> Refactor findEventHandlers further

tsconfig.json
'process-manager.js' now lives under 'lib/' which is already included.
=> Remove 'server/process-manager.js' from tsconfig

server/chat-plugins/mafia.js, sim/battle.js, sim/dex.js
The `Pokemon | Pokemon` TODO seems to be obsolete now - removing the `@return {Pokemon | null}` doesn't cause the compiler to complain.
=> Fix some Typescript related TODOs

sim/SIM-PROTOCOL.md
Oh yeah, a sexy and glamorous documentation PR!
Think this is now exhaustive from grepping through the client/server source (well, maybe `-anim`, but that seems OM only?). The client seems to generate its own artificial events (`-block`, etc) which are obviously not covered here. Had trouble coming up with definitions for some of these, so this PR is WIP until I figure them out or someone chimes in with them. :)
=> Document remaining message types in SIM-PROTOCOL

sim/dex.js
Even though 31c6a32 added caching to make this method less of a
hotspot, there's no reason to use a pattern which is an order of
magnitude slower (https://jsperf.com/pokemon-showdown-getEffect).
Also, rearranges Format to get checked first as pkmn.cc/optimize
finds it to be the most frequently accessed.
=> Refactor getFormat pattern and ordering for speed

sim/dex.js, test/simulator/misc/dex.js
Rollforward of 7a20245 which retains the `hasOwnProperty` checks.
Also changes the method to call `toId` earlier and use the id
as the key to the cache to ensure 'Stealth Rock' and 'stealthrock'
return the same. NOTE: 'move: Stealth Rock' and 'Stealth Rock' will
still continue to return different results.
=> Refactor getFormat for speed safely

sim/pokemon.js
The compiler will start noticing these once converted into a `.ts`. (Discovered from acc23242)
=> Fix field initialization ordering in Pokemon

data/mods/gen1/moves.js, data/mods/gen1/scripts.js, data/mods/gen2/scripts.js, sim/battle.js, test/simulator/moves/substitute.js
First stab at a mechanics change and I'm sure there's a whole host of things I'm missing - I just wrote a test and got it to pass. For example, I'm not sure whether *everything* should be using `uncappedDamage` (all the locations I guessed at have `TODO`s that I'd want removed before I could commit). Assuming the developers never capped damage damage at all seems realistic, but I don't know.
=> Fix Gen 1 bug involving last damage and Substitute (#2598)

sim/battle.js, test/simulator/moves/counter.js
I believe this change should affect Metal Burst as well, because it is the other user of `"target": "scripted"`. From #2367:
> Counter / Mirror Coat currently ignore redirection; they should be affected by redirection as normal ([source](https://www.smogon.com/forums/threads/bug-reports-v3-0-read-op-before-posting.3634749/post-7909353))
_Originally posted by @DaWoblefet in https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-421827399_
Which I need to be careful about referencing so that Github doesn't accidentally close it. ;)
=> Fix Counter/Mirror Coat to respect redirection

data/moves.js, test/simulator/moves/encore.js, test/simulator/moves/focuspunch.js, test/simulator/moves/shelltrap.js
> - [x] Encore should work successfully on Shell Trap, in a similar way to the Focus Punch behavior. EDIT: see [here ](https://www.smogon.com/forums/threads/bug-reports-v3-0-read-op-before-posting.3634749/post-7796738)for clarification.
_Originally posted by @DaWoblefet in https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-390426966_
@Marty-D PTAL :)
=> Fix Focus Punch/Shell Trap behavior with Encore

data/mods/gen1/random-teams.js, data/mods/gen2/random-teams.js
Switching to the pattern used by the later generation random team generators makes things more uniform and avoids any key-ordering issues which were 'not ES-compliant'. Note, this pattern is expected to be slower (though not in a way which matters) given we now `getTemplate` for each id (though it should be noted the old pattern was **not** breaking early and still iterated through every generations Pokemon, it just did less work inside each loop).
=> Remove FIXME's in gen1/gen2 random-teams.js

data/abilities.js
This fixes the following crash:
```
A battle has crashed: TypeError: Cannot read property 'fainted' of null
at Battle.onStart (/home/ps/showdown/data/abilities.js:150:16)
```
=> Fix crash in Anticipation

server/chat-plugins/scavengers.js
This prevents issues with loading old state while hotpatching.
=> Use FS when loading Scavengers' data

build
On Windows,	`shell` doesn't glob for us and the literal
`.sim-dist/*` is passed to `replace` and it doesn't get expanded
into the list of paths.
=> Fix `build` script on Windows.

build
Verified locally that hotpatching formats does not break.
=> Use an absolute path instead of relative path in `build`

build
PS supports ~200k open files, so running out of file descriptors
should not be an issue given we have substantially less than ~200k
source files. Also note - the `build` script will not terminate
until the async operations are complete, and while the `rewrite`
method will 'race' with the logic which creates a `config.js`, this
will have no consequences on correctness.
=> Use async `fs` APIs in `build`

server/chat-commands.js, server/users.js
Prior to this, the forcerename command would wrongfully display (forcerenamed from Guest [number])
=> Fix forcerename tracking wrong username

data/mods/gen6/random-teams.js, data/random-teams.js
Currently, there are many bulky Pokemon that can get Focus Sash, but
shouldn't, such as Swalot, Conkeldurr, and Escavalier. As such, reduce
the threshold of combined bulk that a Pokemon needs to get Focus Sash as
the first Pokemon on the team.
Also, fix Focus Sash Overcoat Forretress.
=> Random Battle: Reduce range of Pokemon that get Focus Sash

data/mods/gen1/moves.js, data/mods/gen1/scripts.js, data/mods/gen2/scripts.js, data/mods/gen3/abilities.js, data/mods/gen4/abilities.js, data/mods/ssb/moves.js, data/moves.js, sim/battle.ts
Also, have `Battle#hint` take Side per @urkerab's suggestion.
Followup to #5258, no functionality changes.
=> Switch `hint`s to use double quotes everywhere

server/chat-plugins/room-faqs.js
The current limit's much too short for Bot Development's room FAQ on
bots' nicks and git repositories.
=> Chat plugins: ignore links when determining room FAQ length

config/formats.js
7:41 PM] anaconja (the metagame leader): Kris can you ban primal and rayquaza evolution in chimera
they were supposed to be ban with the signature item ban and initially, respectively
=> Chimera: Ban Primals and add Mega Rayquaza Clause

config/formats.js, data/mods/ssb/moves.js, sim/battle-stream-example.ts, sim/battle-stream.ts, sim/pokemon.ts, sim/prng.ts, sim/team-validator.ts
Same kind of thing as #5214 (future PRs will cover `battle.ts`/`side.ts`/`dex.ts`).
- Remove most `// @ts-ignore` and document the ones which are left.
- Make as many things `readonly` and `const` as possible
- I had to add back some `// @ts-ignore` for SSB/Chimera 1v1 where they mutate things on `Pokemon` that don't seem like they should be mutable in general.
- Rearrange the large number of fields in `Pokemon` into logical groups (and try to assign them in relatively the same order). `readonly` variables are grouped at the top.
- You may have different opinions on how the blocks of fields should be grouped - I'm happy to change things around. I just think it is easier to grok things if they're somewhat organized as opposed to an imposing block of 50+ fields.
- **Removed calls to …
=> Continue cleaning up `sim/` post native Typescript refactor

build
*Clearly, I really must likely rewriting this code...*
I'm worried that `replace` as it exists today has sharp edges and the next person to try to use it might run into issues. The main thing I'm worried about is someone adding a second `replace` call over the same path and getting into races due to to it writing the same files asynchronously. In addition to the potential correctness issue, it's also inefficient to open up the same files multiple times if you wanted to perform a second replace. 
This approach is the most minimal change, I also [tried an alternative approach](https://github.com/pkmn-cc/Pokemon-Showdown/commit/0d45de25b33c7bcd1528a8de98fbf576e8b15cb9) where I rewrote `replace` to use promises so that if you did want to run something over overlapping paths you could at least …
=> Make `build`s `replace` safer and easier to use

server/chat-commands.js
At the moment, bots can't differentiate between hidden and private rooms, and while they can get the modjoin status and list of auth in rooms, it's very difficult to parse (I had to write a grammar to parse /roomauth's popup, but even then couldn't work out a way to get the room title while accounting for other servers that may have translated the command's output).
This allows bots to be able to get the room title, type, visibility, modjoin status, auth list, and userlist of a room easily.
=> Implement /cmd roominfo

test/simulator/misc/choice-parser.js, test/simulator/misc/decisions.js
These break on [Node < v10.9.0](https://node.green/#ES2015-built-in-extensions-Array-prototype-methods-Array-prototype-values).
=> Remove unnecessary Array.prototype.values() calls

data/abilities.js, data/mods/gen1/scripts.js, data/mods/gen2/scripts.js, data/mods/gennext/abilities.js, data/mods/ssb/abilities.js, data/mods/ssb/scripts.js, data/mods/stadium/scripts.js, data/moves.js, data/scripts.js, dev-tools/globals.ts, sim/battle.ts, sim/pokemon.ts, sim/side.ts, sim/team-validator.ts, test/simulator/abilities/desolateland.js, test/simulator/abilities/primordialsea.js
> I would probably rename these to `storedStats` and `baseStoredStats`; to make it clearer that they aren't the Pokémon's "actual" stats.
_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown/pull/5267_
=> Cleanup stat naming and types (storedStats, StatNameExceptHP)

sim/battle-stream.ts, sim/battle.ts
*TFW you rename a variable because of the linter not liking shadowed variables and having it bite you in the end*
Also some miscellaneous nits I found when looking for the bug.
=> Properly terminate BattleStream (fixes regression caused by #5210)

sim/SIM-PROTOCOL.md, sim/side.ts
Make it take a case-insensitive nickname or species id,
something several of our test cases already rely upon.
=> Make the `switch` command more flexible

sim/side.ts, test/simulator/misc/choice-parser.js
> This test was placed under ``Switch requests > Doubles/Triples``. It should be under ``Move requests > Generic``
_Originally posted by @Slayer95 in https://github.com/Zarel/Pokemon-Showdown/pull/5284_
> Where by "throw" I mean emit a choice error.
_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown/pull/5284#issuecomment-471244025_
---
I also snuck in `'auto'` as an alias for `'default'`, as I've discovered many tests are using it during the cleanup I'm working on in #5286
=> Reject `move` commands with multiple flags

test/simulator/misc/choice-parser.js
> But isn't this test now too overloaded? Conversion 2 is an outstanding issue and its behaviour should be explicitly tested independently IMO.
_Originally posted by @Slayer95 in https://github.com/Zarel/Pokemon-Showdown/pull/5290_
=> Split out 'Conversion 2' tests from targeting

data/mods/stadium/scripts.js, dev-tools/globals.ts, test/simulator/misc/statuses.js
> Could this have affected the attack and speed loss for burn and paralysis in Gen 1 Stadium?
>
> Here is a replay https://replay.pokemonshowdown.com/gen1stadiumou-874684443
See turn 3 for speed being unaffected by paralysis and turn 31 for attack being unaffected by burn.
_Originally posted by @SamanthaLola in https://github.com/Zarel/Pokemon-Showdown/pull/5274#issuecomment-471769625_
I purposefully deleted this (https://github.com/Zarel/Pokemon-Showdown/pull/5274/files#diff-19490bbe318ddb0e323a7bd29127f453L12) because its identical to `getStat` in `gen1` which this mod `inherits` from. What did I miss about inheritance, why do I need to add this back?
=> Fix Stadium mod's stat modification logic

data/mods/gen6/random-teams.js, data/mods/ssb/moves.js, data/random-teams.js, dev-tools/globals.ts, pokemon-showdown, sim/battle.ts, sim/dex.ts, test/simulator/misc/random-teams.js
- Reimplements 23573646d.
- The `side` parameter is required for Seasonal School Schemes and Seasonal Strikes Back, as well as #5303.
=> Fix regressions in team generators

data/random-teams.js
Currently, Superpower is being rejected with RestTalk, but it shouldn't
do that if it is a Malamar, because of Contrary.
=> Random Battle: Fix Malamar

sim/pokemon.ts, test/simulator/misc/inversebattle.js
Reported [here](https://www.smogon.com/forums/posts/8066734/).
This is a regression from commit 13614b9 which among other things stopped `onEffectiveness` events from being sent when running type effectiveness for a string rather than an `ActiveMove`, so to handle these I picked an innocuous move and manually set its type.
=> Run effectiveness events even for string type

sim/battle-stream.ts
> Yes, your teammate gets to see exact HP in 4 player battles, even when your teammate isn't really your teammate, because Zarel didn't think that mattered enough to use 6 channels. That said, I guess we probably should be pushing the updates like you suggested, though I'm not entirely sure what this function even gets used for.
_Originally posted by @MacChaeger in https://github.com/Zarel/Pokemon-Showdown/pull/5297_
---
I think this fix is required given the current design, but I'd also like to start a discussion around the design decisions regarding channels/streams and 4 player battles. 
- From a correctness POV, revealing information unnecessarily seems very undesirable. What is the difficultly with adding additional channels? I think in 2 player battles we should have 2 channels and …
=> Push 'update' to p3 & p4 in `BattleStream`.

data/moves.js
Just a hunch, but if you're at +6 before you stockpile and then the stockpiled effect wears off it probably shouldn't say that the stat couldn't go any higher.
=> Don't show boost failure when stockpile wears off after it didn't boost

data/random-teams.js
`Operands hasMove['hypnosis'] and hasMove['hypnosis'] are identical.`
=> Fix LGTM alert

sim/battle.ts
Regression introduced by 9781c69 in #5325, identified by https://github.com/Zarel/Pokemon-Showdown/pull/5338#issuecomment-475889713.
=> Return from nextTurn if Endless Battle Clause is activated

server/chat-commands.js
In particular this allows displaying this information when room has no roomauth.
=> Always mention subroom status in /roomauth

data/random-teams.js
Castform is moved to 1/3 odds because normal Castform isn't rolled.
=> Random Battle: Fix odds of various forme differences

config/formats.js, data/mods/gennext/abilities.js, data/mods/mixandmega/items.js, data/mods/mixandmega/scripts.js, data/mods/pic/moves.js, data/mods/pic/scripts.js, data/mods/ssb/moves.js, data/mods/ssb/scripts.js, data/mods/ssb/statuses.js, dev-tools/globals.ts, sim/pokemon.ts
Quite often temporary OMs wind up needing to store arbitrary properties to a Pokemon, which TypeScript won't allow. The solution, brought up on #4952 , was to give Pokemon a "data" property with type `AnyObject`. This reduces the need for ts-ignores and properties that were only defined to be used by one OM.
~~"data" is a working name; other possibilities include clearer names like "miscData" or "otherData", or single-letter names like "d"~~ The name "m" was decided
=> Refactor OMs to use "m" property of Pokemon

data/mods/gen3/scripts.js, data/scripts.js, sim/battle.ts, sim/pokemon.ts, test/simulator/misc/target-resolution.js, test/simulator/moves/imprison.js
- Storm Drain and Lightningrod now redirect attacks originally targetted against an empty allied slot of the attacker.
- Imprison and Snatch no longer affect both ``self`` and ``foeSide``.
Fixes #5361 and fixes #5362.
=> Fixes for target resolution

data/scripts.js
Fixes #5383.
I will add a unit test for this once #5348 lands, but I've confirmed this fixes the error which occurs on my branch.
=> canZMove should not be set for disabled moves

sim/battle-stream.ts
Fixes `Error: Push after end of read stream` from https://github.com/Zarel/Pokemon-Showdown/pull/5370#issuecomment-478203045.
`this.push(null)` triggers `this._end()` which calls `this._destroy()` already.
This was fine before (though redundant), but no longer `null`-ing out `this.battle` (either by default or through `{retainBattle: true}`) causes the double `_destroy` to become a problem because the `if (this.battle) this.battle.destroy()` check no longer works, and `Battle#destroy()` is not meant to be called more than once.
=> Make sure BattleStream only calls _destroy once

server/chat-plugins/helptickets.js
It's more readable. Although it's a bit slower (https://jsperf.com/for-in-vs-for-of-in-arrays), I'd take 3% of less speed for readability in a place where speed isn't _that_ important
=> Helpticket: Use for-of instead of for-in in arrays

sim/battle-stream.ts, sim/examples/random-player-ai.ts
`default` papers over AI logic errors. This change fixes those errors instead:
- handle maybeDisabled/maybeTrapped properly
- use 0 PP and ally-less 'adjacentAlly' moves if necessary.
=> Stop returning `default` from RandomPlayerAI

config/config-example.js
While writing this I noticed addhtml is not included in the comment decribing all permissions. I'm bad at writing descriptions so I didn't fix it but I thought I'd mention it
=> Allow Room Owners to use addhtml

data/abilities.js, data/items.js, data/mods/gen1/scripts.js, data/mods/gen2/scripts.js, data/mods/gen4/abilities.js, data/mods/gen4/items.js, data/mods/gen4/moves.js, data/mods/gen4/scripts.js, data/mods/gen5/moves.js, data/mods/gennext/abilities.js, data/mods/ssb/moves.js, data/mods/ssb/statuses.js, data/mods/stadium/scripts.js, data/moves.js, dev-tools/globals.ts, sim/battle.ts, sim/dex-data.ts, sim/pokemon.ts, test/simulator/abilities/battlearmor.js, test/simulator/abilities/disguise.js, test/simulator/abilities/shellarmor.js
See #5415 for context - having these methods is unsafe and leads
to crashes because not all `ActiveMove`s are created through the
`Data.ActiveMove` constructor. Instead of `Pokemon`, these could
alternatively be static methods on` ActiveMove` (or the `ActiveMove`
`class` could be completely abolished and reverted back to an
`interface`), but #5415 will deal with `ActiveMove` long term, this just
fixes the crashes.
=> Move Data.ActiveMove methods to Pokemon

lib/streams.ts
Fixes #5403 for Node versions prior to v10.12.0.
=> Stop closing STDOUT/STDERR in lib/streams.ts

server/chat-commands.js
I don't know what exactly changed, but a while ago, the order of messages got a bit messed up for locks: 
So I switched things around a bit to make it look like this 
which is how it used to look, and what is probably the most sensible.
=> Fix message order for locks

PROTOCOL.md, server/chat-commands.js, server/chat.js, server/rooms.js, server/users.js
Required for Zarel/Pokemon-Showdown-Client#1263.
---
The client (+ Preact client) already seem resilient to having additional parts to `|updateuser|`. I think though it would be better to make a JSON field `SETTINGS` instead of tacking on additional user settings as needed?
=> Send blockpms and blockchallenges status in |updateuser|

server/rooms.js, sim/SIM-PROTOCOL.md, sim/battle-stream.ts, sim/examples/random-player-ai.ts, sim/side.ts, test/assert.js, test/simulator/abilities/arenatrap.js, test/simulator/abilities/magnetpull.js, test/simulator/abilities/shadowtag.js, test/simulator/misc/decisions.js, test/simulator/moves/imprison.js
Fixes #5414.
---
Currently this won't work because the `RandomPlayerAI` will break as receiving the choice `|error|` will cause it to throw. The primary problem is that we don't know which choice error corresponds to the request - with this protocol the AI receives an updated request + an error, but it could issue an updated choice before it receives the error and then cant tell if the error corresponded to the first or second request. 
We could not issue a choice error if we reissue the request, but that seems wrong to me as the original choice was in fact erroneous. I think the best solution is going to be to that instead of emitting the request + error, we emit the request as *part* of the `|error|` (ie/ `|error|<MESSAGE>(|<REQUEST>)?`) provided an update occurred.
I'm also not sure of …
=> Remove |callback| in favor of |error|

data/mods/gen5/moves.js, data/mods/gen6/moves.js, data/moves.js
... in much the same way that Protean does nothing if the user is already the correct type.
Bulbapedia says that Soak doesn't fail for pure Water types in Gen 5.
=> Camouflage and Soak should fail if they don't change the type

server/chat.js
> Step 1: ban `@` from usernames, everywhere.
_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown-Client/pull/1265#issuecomment-482610450_
From #5002.
=> Ban '@' from usernames

.travis.yml, package.json, test/dev-tools/harness.js, test/dev-tools/smoke.js
- Tests flagged with (slow) will no longer be run in `npm test`.
- Travis CI will now run `fulltest`.
- Unskip slow dev-tools tests and flag as such.
=> Test: Implement `npm run fulltest` and flagging tests as slow

data/mods/ssb/moves.js, data/mods/ssb/statuses.js, sim/pokemon.ts
We're still trying to `push` uselessly to it in a couple of places.
I don't know if you want the Typescript annotation or whether it's the best way of annotating the requirement.
=> Make Pokemon.moves a read only array

server/chat-commands.js, server/chat-plugins/helptickets.js, server/chat-plugins/roomsettings.js, server/users.js
Fixes #5424. The client code is already able to handle diffs.
- in certain scenarios I think we want to continue to send all the values instead of just the diffs
- `User.lastConnected` gets updated in `User.markInactive()`, but we cant send an `|updateuser|` at that point
- `User.isStaff` and `User.isSysop` usually get updated right before we'd be sending all the values anyway, so I'm trying to avoid doing a double `update`
- WTF is going on with `specialNextBattle`? I only see it being read, not being written?
```
server/rooms.js:1615:               /** @type {(User & {specialNextBattle: boolean})[]} */
server/rooms.js:1638:               if (players.some(user => user.specialNextBattle)) {
server/rooms.js:1639:                       const p1Special = players[0].specialNextBattle; …
```
=> Include diffs of all User settings in |updateuser|

package.json, test/mocha.opts
_#justbikesheddingthings_
Optional follow up to #5437, maybe you guys are interested in some or none of the following:
- leverage [mocha's merging order](https://mochajs.org/#merging) with an impossible regex and `test/mocha.opts` to make `npx mocha` be the default which skips slow tests
- put `eslint` and `tslint` together under the `lint` script
- use standard [`posttest` and `pretest` hooks](https://docs.npmjs.com/misc/scripts)
In other news, @KrisXV's test is damn slow. How long do we think is OK for Travis? Can I run a full cycle of smokes tests instead of just the one canary one?
=> Rework mocha fulltest configuration

data/abilities.js, data/mods/gen5/moves.js, data/mods/ssb/abilities.js, data/mods/ssb/moves.js, dev-tools/globals.ts
Fixes #5444
Stuff I noticed:
- Battery is assigned a priority of 8. However, from 9635ea7d5643 I'd expect it to have a priority of 3.
- Dry Skin currently doesn't boost Lava Plume's friendly fire. Bug?
cc @Marty-D
=> Fix misspecified event handler priorities

data/mods/gen2/statuses.js
This should fix https://github.com/Zarel/Pokemon-Showdown/projects/3#card-18664063
=> Past Gens: Fix confusion interaction with self-destructing moves in gen 2

data/mods/gen3/scripts.js
Fixes #5464
Simple fix, but I didn't just commit it directly because I want someone confirm that `targets` being empty is actually expected and that there's not a deeper issue at play.
=> Fixes crash in gen3doubles due to missing target

config/formats.js, data/mods/gen2/moves.js, data/mods/gen2/statuses.js, data/mods/gen3/moves.js, data/mods/gen4/abilities.js, data/mods/gennext/statuses.js, data/mods/mixandmega/scripts.js, data/rulesets.js, server/chat-plugins/helptickets.js, server/chat-plugins/mafia.js, server/chat-plugins/room-faqs.js, server/punishments.js, server/tournaments/index.js, sim/battle.ts, sim/dex-data.ts, sim/dex.ts, sim/field.ts, sim/globals.ts, sim/pokemon.ts
Similar to `ID` in Pokemon-Showdown-Client, but also including `''` to avoid a bunch of casts. More places can likely to converted to `ID`, and eventually certain `toId` calls can be removed, but this commit just lays the groundwork.
=> Introduce an ID type to sim

data/mods/gen4/moves.js
Knock Off and Rapid Spin should still take effect even if the user faints in Generation 3 and Generation 4,
Ignore the branch name.
=> Fix Knock Off And Rapid Spin

sim/battle.ts, sim/dex.ts, sim/field.ts, sim/pokemon.ts
**This changes reduces `toID` calls by ~15.7% (from `10238733` -> `8628355` over 100 random battles).**
After #5468, we can now start to avoid unnecessary `toId` calls in critical places. This commit avoids `toId` in certain obvious places by introducing a `Dex.getEffectByID` method which can be used internally to skip both `toId` and unnecessary lookups. This commit also performs a minor optimization by passing `id` to `Data` constructors (which saves a call to `toId` in the `BasicEffect` constructor, and which we could have done before #5468 introduced an `ID` type, I only just noticed it now).
=> Avoid calling toId where possible with Dex.getEffectByID

data/items.js, data/mods/gen1/scripts.js, data/mods/gen3/scripts.js, data/moves.js, data/rulesets.js, data/scripts.js, sim/battle.ts, sim/pokemon.ts, test/sim/misc/endlessbattleclause.js
Based on discussion in #5453, this change implements the core of the new EBC:
- Any Pokémon hit by a foe’s Heal Pulse or Floral Healing becomes stale.
- Any Pokémon _using_ (consuming) an _acquired Leppa Berry_ (defined as a Leppa Berry which the Pokemon did not start the battle with, for example, one obtained Fling, Trick, Harvest, Recycle, Bug Bite, Pluck, Pickup etc) becomes stale.
- If all Pokémon on the field are stale and at least one team does not have the option of switching to a non-stale Pokémon, with at least one Pokémon on a side's staleness having been inflicted by a Pokémon of the opposing side, the game ends. If only one side started the battle with the _rudimentary means to perform Leppa Berry-cycling_ (defined to be a team containing a Pokémon holding a Leppa Berry and a …
=> Redo Endless Battle Clause with a new specification

config/formats.js
Using future stuff in past game custom game still doesn't work so copied the exact same ruleset (gen6's) for all CGs other than Gen7
=> Past Custom Game "canUseRandomTeam", Level 9999/24 Pokemon

data/mods/gen1/scripts.js, data/mods/gen1/statuses.js, data/statuses.js
```
|turn|21
|
|move|p1a: Venomoth|Stun Spore|p2a: Articuno
|-fail|p2a: Articuno|par
|move|p2a: Articuno|Hyper Beam|p1a: Venomoth
|-damage|p1a: Venomoth|156/256
|-mustrecharge|p2a: Articuno
|
|upkeep
|turn|22
|
|move|p1a: Venomoth|Psychic|p2a: Articuno
|-crit|p2a: Articuno
|-damage|p2a: Articuno|206/286 par
|-unboost|p2a: Articuno|spd|1
|-unboost|p2a: Articuno|spa|1
|cant|p2a: Articuno|recharge
|
|upkeep
```
This way it doesn't show up at the end of the turn or get added 3 separate times.
Fixes #5462.
=> Move -mustrecharge message to onStart

data/mods/gen1/scripts.js
Moves with the `'charge'` flag add the `'twoturnmove'` volatile which already handles adding `[still]`.
Fixes #5487
=> Fix double [still] in Gen 1

server/chat-commands.js
Moving the log message to after the unlink messages means that the hide/show prompt has nothing to attach to, making it look weird.
=> Stop hidetext message from getting hidden

CODEOWNERS
This allows me to be notified if any of those files changes and automatically assigns me to pull requests involving those.
Other additions to this file are welcome, obviously, if you are maintaining some chat plugin or something (for instance @TheImmortal may want to be added to `random-teams.js`), you are welcome to add yourself after this change gets merged. Also @sparkychildcharlie and @whalemer are welcome to add themselves to this file as well if they want to be in Scavengers section. The syntax is similar to `.gitignore`.
=> Add xfix as a maintainer for Scavengers and Trivia chat plugins

data/mods/gen2/scripts.js, data/scripts.js, sim/battle.ts, sim/dex-data.ts, sim/globals.ts, sim/pokemon.ts
The other `getEffect` calls all are going to require `data` to be Typescripted because we need to perform *beaucoup* casting.
=> Remove additional toID calls

config/formats.js
* (First pull request) I agree to make this code available under the MIT license.
* Discussed this change with Urkerab in PM, final code is substantially due to him.
* Tested in Trademarked Ubers and Trademarked STABmons public tours.
* Known issue with STABmons: some stabmons moves will still be illegal due to stabmonsmovelegality expecting the format's restrictedMoves to be stabmons restricted moves, not restricted trademarks.
=> Trademarked: Make legality-expanding custom rules effective

server/chat-commands.js, server/chat.js, server/ladders.js, server/users.js
> One solution would be to show a warning the first time a PM or challenge is blocked, every session.
_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown-Client/issues/1271#issuecomment-488094948_
I'm not entirely sure this code does exactly what we want because it isn't completely clear to me what is meant by 'session' in this case (should the notifications be once-per-connection instead? Is there another way to handle sessions?). Also, not sure if the messages should just be plain or if we want `|error|` or something.
=> Notify users the first time a PM/challenge is blocked

sim/battle.ts
Not confident about the wording in the slightest, and obviously `/offertie` is a lame solution to EBC shortcomings, but I think it's going to be difficult for user's to figure out `/offertie` is even an option without this or something similar.
=> Provide a hint regarding '/offertie' in EBC situations

server/tournaments/generator-elimination.js
With the old api, node.getChildAt would return null if the node had no children
=> Fix crash in multi elim tours

sim/pokemon.ts, test/sim/moves/transform.js
> Ditto used Transform!
> Ditto transformed into Gengar!
> [Ditto's none]
https://replay.pokemonshowdown.com/gen1randombattle-919867589
=> Fix incorrect ability message from Gen 1 Transform

server/chat-plugins/chat-monitor.js
Also reword the "name being used" message to make it more clear.
=> Specify if the name was manually forcerenamed in NameMonitor message

data/mods/pic/scripts.js
Reported [here](https://www.smogon.com/forums/posts/8066699/) (and with a couple of followup posts).
When these abilities replace themselves with another Ability, that will then get shared as normal.
I've implemented this by not cloning the effects for those Abilities (resulting in dummy no-op effects instead) so that the code dealing with adding and removing shared abilities is unaffected.
=> Don't share self-replacing abilities

sim/side.ts
- include base power  in the `side` data for Hidden Power when `gen < 6` (like in `sim/pokemon.ts`) instead of when`power != 70`
- alternatively, both places should probably only include base power if (`gen < 6 && pokemon.hpPower < 70`)
- send `frustrationN`/`returnN` as an ID instead of a name: `'Frustration N'`/`'Return N'`. `sim/pokemon.ts` sends the name in its logic, but `side` seems to send IDs
These both nits, but for consistency reasons they seem worth fixing.
=> Tweak cases how/when base power is included in required

data/formats-data.js, data/mods/gen6/formats-data.js, data/mods/gen6/random-teams.js, data/random-teams.js
- Change the Thunder/Thunderbolt rejection condition to a moveset
modification to improve consistency.
- Change the Rain Dance rejection condition on non-Water mons to
have a Water move.
- Give Heliolisk Waterium Z if it has Rain Dance + Surf.
=> Random Battle: Update Heliolisk

data/moves.js
Issue demonstrated by this replay: http://replay.pokemonshowdown.com/gen7doublescustomgame-925407612
Reflect Type fails, but the client thinks it succeeded anyway, because the `-start` is sent before the fail condition is even checked. I didn't see a reason for it to be that way, so I've simply moved it after that check.
=> Fix Reflect Type interaction with typeless targets on client

server/chat-commands.js
5508b4662951bde6c5dd989f6ab515602bafe02b causes:
```
TypeError: Cannot read property 'id' of undefined
at CommandContext.crq (/home/ps/showdown/server/chat-commands.js:4362:42)
at CommandContext.run (/home/ps/showdown/server/chat.js:739:28)
at CommandContext.parse (/home/ps/showdown/server/chat.js:564:19)
at CommandContext.parse (/home/ps/showdown/server/chat.js:556:22)
at CommandContext.msg (/home/ps/showdown/server/chat-commands.js:528:8)
at CommandContext.run (/home/ps/showdown/server/chat.js:739:28)
at CommandContext.parse (/home/ps/showdown/server/chat.js:564:19)
at Object.Chat.parse (/home/ps/showdown/server/chat.js:1436:17)
at User.chat (/home/ps/showdown/server/users.js:1473:9)
at Function.socketReceive (/home/ps/showdown/server/users.js:1692:12)
```
Not positive this is the fix, …
=> Fix crash in /crq

server/global.d.ts, server/room-battle.js, sim/battle.ts, sim/global.d.ts
> I would say `>version` as before, and `>version-origin` only if they differ.
_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown/pull/5417#issuecomment-483391024_
Fixes #5412, #5417.
=> Include a >version-origin hash if different from >version

server/chat-plugins/modlog.js
**Context:** [An option to split modlog into punishments and non punishments](https://www.smogon.com/forums/threads/an-option-to-split-modlog-into-punishments-and-non-punishments.3651100/) (3rd most popular)
- I'm not wedded to the idea of a `'/punishlog'` command vs. implementing some sort of flag (`'scope=punishments'`?) the way `maxLines` works, but this was the easiest approach and its relatively simple to change
- I may be missing or including actions which are or are not 'punishment related'. Something like `'NOTE'` is not necessarily 'punishment-related', but it often provides additional context for punishments so I figured it was useful to include. Ditto some others I've added. On the main server we may wish to add to `PUNISHMENTS` with actions from private code, potentially …
=> Allow for viewing only punishment-related actions in the modlog

server/chat-plugins/datasearch.js
Main use of this feature would be to compare the movesets of two Pokemon. For example, a user comes into Trainer Academy and asks why to use X mon over Z. Now room staff could show them the kinds of moves that X does get that Z doesn't.
I feel like this is also a readability improvement over the previous code.
=> Datasearch: Add ability to search for moves not in a Pokemon's moveset

data/random-teams.js, test/sim/misc/random-teams.js
Shoehorning monotype generation into normal team generation results in several issues, especially for mono-ice where there are only 28 possible Pokemon in the `pokemonPool` to begin with:
- Rotom-F, Ninetales-A and Sandslash-A are all going to be unfairly downsampled even though their alternate formes are not legal options on mono ice (Kyurem downsampling should be OK, because all are ice)
- We limit to 2 Pokemon per tier even though most Ice types are likely to be clustered in the lower tiers (or just Untiered) because theyre kind of trash
- We limit the number of type combinations even though a large fraction of Ice types are actually just pure Ice. We increase the 'allowable number of type combos' from 1 to 2 for monotype, but this is probably still too low for Ice.
- We only consider …
=> Ensure random team generation always ends up with 6 Pokemon

data/random-teams.js
After this, the only remaining restrictions on the second pass are:
1) Species clause
2) 6th slot Zoroak
3) bellydrum/swordsdance/calmmind/nastyplot sets
4) multiple zmoves
Not sure if we want to remove the restrictions from 2-4 as well, LMK.
=> Rework random teams to only perform 2 iterations

server/chat-commands.js, server/users.js
It's possible to spam /warn in groupchats, preventing users from being
able to close the warn modal. This mitigates that by limiting the rate
you can warn a user to once every 15 seconds, which is longer than the
amount of time it takes for the warn modal to allow you to close it.
=> Add a 15 second timeout when warning individual users

data/abilities.js, data/moves.js
Reported [here](https://www.smogon.com/forums/posts/8175821).
This saves the item about to be set and reports it before it actually sets it so that its `onStart` handler can activate in order.
I could do Harvest in the same way, but those are only Berries, which never have an `onStart` handler.
For other item-switching moves there are issues with items that can't be switched so I can't see how to avoid having the messages in the wrong order (think about seed holder having Klutz or affected by Embargo). I don't think the underlying mechanics are wrong in this case though, it's just a cosmetic error.
=> Fix Pickup/Recycle of Terrain Seed while terrain is up

server/punishments.js
**Changes**:
- `PunishmentEntry` now has `ips` and `userids` instead of `keys`.
- `PunishmentEntry` now has `reason` and `expireTime` instead of `rest`.
- `rest` was still kept as Zarel noted it was used for extensibility. 
- `Punishments.renderEntry` converts `PunishmentEntry` into the old format for to not ruin the databases.
- ~Removed `type` from sharedIPs because it's _always_ the same.~ Turns out it's in case there are more types in the future, so I reverted that change.
This will make my life easier when I work on migrating punishments to SQLite3
It has also another advantage in making the code more explicit for future readers.
=> Refactor punishments

server/ladders.js, server/room-battle.js, sim/SIM-PROTOCOL.md, sim/battle.ts, sim/globals.ts
Client Pull Request: Zarel/Pokemon-Showdown-Client#1318
Suggested and approved here: https://www.smogon.com/forums/threads/3651687/
I did not implement the "make `/rank` only display the tier of the battle you're playing in" suggestion because you can use `/rank [player], [format]` or with this change it's even easier because you can just scroll up.
=> Display Elo in rated battles

server/chat-commands.js
This makes it easier to automatically set the status on connect. Instead
of making it so users can't set their status if they can't talk at all,
make it so they can't set it if they're locked or semilocked. Also,
don't send a success response if the command was sent in the global
room.
=> Allow bots to set statuses in the global room

server/tournaments/index.js
`note` in `this.modlog` expects a string.
=> Tournaments: Fix crash in /tournament cap

server/chat-commands.js, server/chat-plugins/chat-monitor.js, server/chat.js, server/globals.ts
- separate `Chat.statusfilter` from `Chat.nicknamefilter` instead of just using `forStatus` for more flexibility going forward. Eliminating the duplicated code present in `namefilter`, `nicknamefilter` and `statusfilter` is out of scope, but would likely be beneficial as a followup
- do basic rank impersonation filtering, which when coupled with a UI which better differentiates rank in the user card (eg. Zarel/Pokemon-Showdown-Client#1319) should help with abuse
=> Create Chat.statusfilter which also performs basic rank impersonation filtering

data/scripts.js, test/sim/abilities/dancer.js
This fixes https://github.com/Zarel/Pokemon-Showdown/projects/3#card-23723922 based on the research conducted [here](https://www.smogon.com/forums/threads/pokemon-sun-moon-battle-mechanics-research.3586701/post-7965255/).
I don't think it's possible for this code path to be reached when `target === null`, so the `ts-ignore` directives hides those errors. If I'm incorrect in that regard, then let me know what the behavior should be and I can implement it.
Also now with unit tests. :)
=> Make moves called by Dancer target properly

server/users.ts
This was originally added in the original design when we were actively logging Idle users out of their account. Currently it serves mostly to explain what Idle is, but mostly it just annoys users.
=> Remove Idle popup

server/users.ts
Currently users are complaining about being `Idle` right from startup until they click a username/chat.
Merging users seems active enough to wipe the `Idle` state - do merges ever happen without activity on the user's end?
We may also want to clear `Idle` in `markDisconnected`? WDYT?
=> Prevent Idle state from propagating

server/chat-commands.js, server/users.ts
The change in users.js is so you can actually untrustuser and then trustuser again without requiring the user to do a logout cycle to reset their trusted status. I've run into issues like that and it was painful.
Hope it's ok to just re-use the trustuser command for the untrustusering as well. I originally had a separate one but duplicating all the boilerplate didn't feel very elegant.
=> Add easy method of undoing /trustuser

PROTOCOL.md
This needs a review, I'm only basing this off changes I can see while interacting with the server.
=> Update PROTOCOL.md WRT recent user status protocol changes

config/formats.js
The link 404s when it has a slash at the end.
=> Fix article link for Gen 1 Tradeback OU

README.md
Trying to standardize on `Real name [PS username]`.
Currently its inconsistent whether the username is included when its identical to one of a contributor's real name (Austin vs. Kris + McLemore + Spandan). Furthermore, GH username is only included in some cases (scheibo, Kaipei) and not in all (peach + whaelmer, McLemore + jmclemo6, jetou + TheJetOU, spandan + Spandanm etc).
I'm not sure which of `[moo, CheeseMuffin]` and `[Lyren, SolarisFox]` is the PS username (I assume the first?). If you're adamant on keeping GH username, I'd want us to include it for everyone where it differs, not just on a select few names.
=> Improve README attribution

server/chat-formatter.ts, server/chat-plugins/daily-spotlight.js, server/chat-plugins/room-faqs.js, server/chat.js
The idea here is that formatting such as `**`, `__`, `~~`, ect and links (bar the "text" in `[[text<url>]]`) do not count to the 500 character limit for daily spotlights/rfaqs. This has been requested by UnleashOurPassion (and iirc other staff members).
This Pull Request closes #5659 (I asked UOP if I could merge their changes into this).
=> Implement Chat.stripFormatting

config/config-example.js, server/chat-commands.js, server/chat-plugins/roomsettings.js, server/room-battle.js, server/rooms.js, server/users.ts
Usernames prefixed by a special value decided ahead of time (eg. `'LT61RQ'`) will unable to hide their battles from spectators, as discussed in #5646. This is not a 'complete' OLT solution, we will probably want to followup with support for `/hidereplay`, as well as force unregistered accounts to only be able to ladder unrated to simplify coordination issues. However, simply coordinating  around updating `Config.forcedpublicprefixes` with the new prefix for the next qualifying periods is probably sufficient.
=> Add forcedpublicprefixes for public OLT battles

server/room-battle.js, server/rooms.js
The OLTBot provides links to highly rated games in the OLT room, but the existence of these links means that even if `/hidereplay` is used, players can still try to scout/counter team their opponents  by looking in the OLT room to see if any of their previous matches have been linked. Battle rooms eventually expire, but not if they're constantly being visited by spectators after the fact, so this can still be a problem hours after the match. 
Currently the OLTBot has switched to using links which decay after 10 minutes to avoid this issue, but these links are external to PS so get a `target="_blank"` attribute appended by the chat formatter, causing the links to open in new tabs which annoys spectators. One solution for players is to do `/modjoin sync` and `/hideroom` _once the battle is …
=> Have /hidereplay turn on modjoin % once the battle is over

sim/team-validator.ts
This PR fixes #5668 by modifying the behavior of the `removeNicknames` flag for Cross Evolution: if a Pokemon's nickname represents the name of an actual Pokemon, it is not removed.
=>  Prevent locked users from having Pokemon nicknames hidden in Cross Evolution

server/users.ts
.............this doesn't fix the issue entirely, because apparently there's a clientside bug with seeing the ``|n|peach@!|peach`` message in the room backlog and marking you as away off that, but at least the server is doing everything correctly now.
=> Fix self idle display on merging

server/chat-commands.js, server/users.ts
This lets the client not rely on seeing the `|n|peach@!|peach` message to know when it's afk or not, which makes afk states display properly if you aren't in any rooms and is (imo) the best fix for the bug described in #5674. It _does_ mean that `/busy` will send 3 updateuser messages, but it's all one way and technically still part of 3 actions, so I think it's an acceptable trade.
=> Send updateuser when changing status type

sim/dex.ts
0|1|H saves minimal space over the ability ID and requires parsers have the data files, in addition to limiting the ability to search abilities in the teambuilder.
---
Some thoughts:
**1)** I assume we need to keep the logic for decoding `0|1|H` in `fastUnpackTeam` for a while for backwards compatibility? 
**2)** Client side changes obviously need to be made as well (though maybe this is the only place we need the backwards compatibility?)
**3)** Can we change gender's encoding as well to make things completely data-free?
=> Change packed encoding of abilities

server/chat-commands.js, server/room-battle.js
- hide the room as well so that it doesnt show up in a user's trainer card and end up auto-linking to replays
- upload a replay after the game to ensure the hidden setting is properly written
**NOTE:** this change does **not** fix private battles not properly getting passworded, but closes a few other loopholes that were found while investigating.
=> Improve /hidereplay privacy

data/rulesets.js
it should be saying 15 seconds per turn like it actually is, currently says 10 seconds.
=> update blitz's description to proper timings

server/chat-plugins/scavengers.js
This adds a database of recycled hunts that Scavengers room staff can start and also auto-queue for times when the room is slow. This has been discussed with appropriate room staff.
The database itself is just JSON that is loaded and worked with in memory. Any changes that are made are immediately written back out to the JSON file.
The main way to interact with the database is through a new master command `/recycledhunts`. It is possible to add hunts, remove hunts, add hints, remove hints, and to enable/disable the auto-queue functionality through this command.
The existing queue and create commands were also updated to work with recycled hunts. Staff are able to queue and create either a random or specific recycled hunt from the database.
I think I updated and created all appropriate …
=> Scavengers: Add Recycled Hunts functionality

server/chat-plugins/info.js
The link in /intro about "What do 'OU' and etc. mean" is from BW era so I am pushing an edit to replace it with the SM one.
=> Update a link in the /intro command

server/chat-plugins/datasearch.js
it says [move description], I assume it meant [item description]
reported here: https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/page-54#post-8211844
=> Minor fix to /itemsearchhelp

server/chat-plugins/datasearch.js
Added charge, gravity, recharge and reflectable tags to movesearch and the command description. Meaning of these flags should be self-explanatory so no description of the flags was added in the command description.
(Apologies if I had done this wrongly, this is my first time attempting a pull request.)
=> Added various flags to movesearch

server/chat-plugins/info.js
Charge moves and Recharge moves will have a tag when using /dt, similar to other tags like "Supressed by Gravity" or "Bite".
=> Added new descriptions for certain tags in /descriptions

server/chat-plugins/mafia.js
The latter feature relies on the nature of arithmetic with NaN to propagate the NaN value, so hammer counts and the like should always remain at NaN and fail.
=> Mafia: Implement forced selflynch, disabling hammer

server/chat-plugins/datasearch.js
* Don't count the special stat twice for searching by BST in gen 1
* Use the type effectiveness from the gen we're actually searching in, not always gen 7's
=> Fix some small oldgens dexsearch issues

server/chat-commands.js
PoS-Bot uses `/cmd userdetails` when PM commands are used and it is not actually aware of the user existing because they're not in any of its rooms. It expects a userid, name, group, and status of some sort when creating user objects, but `/cmd userdetails` doesn't include a name at the moment. It'd be nice if it did so I don't have to pass both a username and userid to the routine for getting users from the bot's state machine.
I'm not explaining the second commit. You should already know why it's included and why it wouldn't be a good idea to do so.
=> Make a couple improvements to /cmd

server/chat-plugins/room-faqs.js
Bot Development needs a much longer max room FAQ length limit because of its bot list in /rfaq bots. Even when excluding the formatting in the length limit, it's simply too short.
=> Bump max room FAQ length to 8KB

server/chat-plugins/info.js
This is a QoL change for easier access to the user page for cases where the active name isn't the autoconfirmed one.
=> Linkify autoconfirmed alt display

package.json
It's kind of annoying to run 5 minutes of mocha test just for the test to fail in the TypeScript compiler which is at least 5x times faster.
=> Run tsc before mocha in `npm run fulltest`

server/chat-plugins/scavengers.js
- Hints: add a command to display hints that can be recalled using /scav hint and /viewhunt for hunts that last several hours.  This allows previously given hints to still be visible even after it scrolls out of chat, or the user uses /clear after completing some difficult param question.  This command cannot be used until after 10 minutes of th
- /scav status is enhanced to show users who have tried to guess in the last 5 minutes in bold (&lt;strong&gt; for you HTML purists)
This has been approved by all 4 roomowners.
=> Add more hunt management options

logs/tickets/README.md, server/chat-plugins/helptickets.js
This Pull Request adds support for logging statistics about help tickets. These statistics are stored in tsv files located in `logs/tickets/YYYY-MM.tsv`.
When a ticket is closed, a line is added to the current month's tsv file containing information about the ticket including its type, how long it was open, how long it took staff to claim it for the first time, how long it was waiting on staff in total, what staff members participated (to our best knowledge) in the ticket's resolution, if the ticket was resolved, and its result. The possible ticket resolutions are:
- "dead" - The ticket was never activated by the user and was closed by the user (staff were not contacted).
- "unresolved" - The ticket was activated and staff were contacted, but no staff member came before the ticket was …
=> Record statistics for help tickets

server/chat-plugins/helptickets.js
Ticketbans with reasons currently show up in modlog like "by Anubisbad user" when they should show "by Anubis: bad user".
=> Fix ticketbans logging reasons

data/mods/ssb/abilities.js
Gracidea Mastery is making Shaymin-Sky transform into Shaymin-Sky after every move, when it should only be doing this if Shaymin is in its regular forme.
=> Fix SSB bug in Gracidea Mastery

data/mods/ssb/statuses.js
Crash happened because an Illusion'd mon pretending to be Kay swapped into Sticky Web, which causes an undefined ``source``.  The line is meant to prevent Illusion from copying Kay's innate Simple ability, so the check is now on whether the ``target`` is an Illusion'd mon.
=> Fix SSB crash in Kay's innate ability when copied through Illusion

server/chat-plugins/modlog.js
Based on a staff suggestion that turned out rather popular. Looking up modlogs in help tickets is somewhat of a common occurrence, so this'll save switching rooms or adding "global" manually.
=> Use global modlog for queries in help tickets instead of failing

data/mods/ssb/moves.js
QC update:
> we're removing Murky Ambush's ability to trigger against special attacks because there's literally no way to avoid being hit repeatedly by quag's 150 bp stab as it stands right now
> 
> also i'd prefer if it didn't take halved damage from special attacks while preparing the move, to match the change
=> Change Murky Ambush to only work on Physical attacks

server/chat-plugins/chat-monitor.js, server/users.ts
getAccountStatusString() is only used in forcerename messages to append the status of the name.  The main reason for displaying the account status is so leaders+ can disable registered bad names, but labeling every unregistered account makes the messages messier and doesn't add any valuable information.  I also shortened the notification for an FR'd name being reused; I ran this by several new people who were able to understand what it meant.
Old:
> «lobby» werwerara [unregistered] was forced to choose a new name by Anubis
[NameMonitor] Username used: aseraehshsd [unregistered] (forcerenamed from werwerara)
[NameMonitor] Forcerenamed name being reused (forcerenamed 1 time): werwerara [unregistered]
New:
> «lobby» g43tarsgga was forced to choose a new name by Anubis
> [NameMonitor] …
=> Clean up forcerename messages

data/mods/ssb/moves.js, data/mods/ssb/scripts.js
[10:18 AM] A Cake Wearing A Hat: Okay yeah @ Programmer acid rain will no longer allow poison types to be poisoned, and the description should also not erroneously state that steels are not immune to poison under acid rain
Paradise's Corrosive Toxic was acting up with Distortion Blast because of the hacky way it was implemented, so with the help of @whalemer, it's been changed over to use setStatus.
=> Change Acid Rain so Steel/Poison retain immunities; Rewrite Corrosive Toxic

server/chat-plugins/info.js
The links labeled "Snatchable/Mirrorable Moves" didn't actually point anywhere useful - just the dex page of Snatch/Mirror Move, which don't have a list of moves they affect.
=> Fix informational link for Snatch/Mirror Move

server/users.ts
down from 300ms for global auth
=> Give trusted users a 100ms chat delay

data/abilities.js, data/items.js, data/mods/gen5/moves.js, data/mods/letsgo/scripts.js, data/mods/mixandmega/scripts.js, data/mods/ssb/moves.js, data/mods/ssb/statuses.js, data/moves.js, old-simulator-doc.txt, server/chat-plugins/datasearch.js, server/chat-plugins/info.js, server/chat-plugins/othermetas.js, sim/dex-data.ts, sim/globals.ts, sim/pokemon.ts, test/sim/misc/weight.js
Mechanics implemented:
- Weight is calculated in positive integer multiples of hectograms, in particular for Light Metal
- Heavy Metal always applies before Float Stone
- Since Gen 6, weight is a property of the forme that is directly modified by Autotomize
My attempt to implement the mechanics described here:
https://www.smogon.com/forums/posts/8095060
=> Change weight units to hectograms

server/chat-commands.js, server/punishments.ts, server/users.ts
This is for the situations "permalocked user logging in" and "lock on shared IP". In both cases, existing alts are also locked by name right now. This tends to be overkill.
Unfortunately this had the side effect of not locking existing alts at all (not even based on the locked IP). 
Do we want that behavior? Do we need to re-run checkIP for every alt so it locks them properly (just without punishing their usernames)?
=> Prevent overzealous spead of locks under some circumstances

config/config-example.js, server/chat-plugins/info.js
Certain bad users are convincing people to merge their accounts as a way to find their IP, and most people don't have a real need to see their own IP through PS.
=> Disallow regs from seeing their own IPs

server/chat-commands.js
Staff consensus is that it's entirely useless.
=> Remove hidetext abuse monitor

sim/battle.ts
If in a triples battle you use a move that would target an adjacent foe, but by the time it is your turn the only active foe is on the far side of the field, then this should causes the move to fail. Note that it's possible for your adjacent ally to redirect the move, so we can't get claim there is no target until after that check. Otherwise we get stuck in an infinite loop for some reason.
=> Require normal targets to be adjacent in Triples battles

server/chat-commands.js
`globalModlog` writes to both the global modlog and the room one. Calling `modlog` in addition to this means stuff is logged twice.
I suppose `modlog` can have some slightly different behavior with the noip ad noalts options, but we have been logging the version with IP and alts in the roomlog for years as well now so this doesn't introduce any _new_ behavior. This is also only for stuff that's globally relevant enough to get put in the global modlog, so incuding alts/IPs should not be an issue.
=> Don't duplicate some mod actions in room modlogs

server/chat-commands.js, server/punishments.ts
There is of course the problem that the savereplay command requires a user, which does not mesh well with the concept of an autolock. Current convention seems to be to just use the user who is getting locked, which works, but means they'll get the replay sent to them with the popup and all. I don't really like that but I'm not sure what else to do.
=> Automatically save replays for global warnings and autolocks

.gitignore, lib/fs.ts, server/chat.ts
As requested by @scheibo. This looks through all files in all subdirectories and tries to load them as chat plugins. I excluded hidden directories so it doesn't bother looking through .git in the case that someone checks out a chat plugin from a separate repository here.
=> Allow loading chat plugins from subdirectories

server/chat.ts
Stops globalModlog from duplicating entries in the global modlog in specific cases.
=> Fix duplicate globalModlog entries in some cases

data/abilities.js, data/mods/gen1/scripts.js, data/mods/gen2/moves.js, data/mods/gen2/scripts.js, data/mods/gen3/scripts.js, data/mods/gen4/moves.js, data/mods/gen4/scripts.js, data/mods/gen5/moves.js, data/moves.js, data/scripts.js, sim/globals.ts
if (source.hasAbility('noguard') || target.hasAbility('noguard')) {
return;
}
if (source.volatiles['lockon'] && target === source.volatiles['lockon'].source) return;
Rather than copy/pasting this code block for every semi-invulnerability move, I thought that perhaps the tests could all be done centrally (except for Gen 2, which is a special snowflake), so I made a zero return from `onInvulnerability` mean not invulnerable due to No Guard or Lock On, while false continues to mean semi-invulnerable and true means neither of the above.
I wasn't sure what was going on with Lock On in Gen 4 though; the description differs from later gens in that Baton Pass is not specifically exempted, but there's no relevant code change? I added one in, but...
=> Centralise invulnerability checks for No Guard and Lock On

data/abilities.js, sim/battle.ts
Currently if you're already at `+6` when your Defiant or Competitive activates, you do get the "[POKEMON]'s [STAT] won't go any higher!" message, but without the Defiant or Competitive activation that showed why the stat tried to rise.
Compare Gooey which shows the activation and then the stat change, whether it succeeds or fails. It is granted a special case in the `boost` function to avoid the ability activation therein allowing it to enforce it prior to the invocation (necessary for Clear Body to function), so I could have just copied that hack for Defiant and Competitive.
But rather than having more special cases, I thought it was better to use the flag that Gooey was already passing in to `boost` to get special behaviour in the failure case and grant all the relevant Abilities …
=> Fix activation of Defiant and Competitive when boosts are maxed

data/mods/ssb/moves.js
Fails currently if opponent's Substitute is up.  This allows it to still attempt to use the 4 moves.
=> SSB: Fixes Pirate Princess's Tea Break vs Substitute

data/mods/ssb/moves.js
This move is supposed to use Defog followed by a 90 BP U-turn, but original implementation had two major issues, such as 1) screens were getting cleared from both sides, 2) the evasion drop was happening after the damage occurred (original idea was that evasion drop would help Hustle to deal the damage).  Calling both moves instead appears to work properly.
=> SSB: Fix Quick Reload to properly use Defog and then U-Turn

server/chat-plugins/helptickets.js
A few notes:
- Standardized "Pokemon" since that's what descs use
- ``#hostfilter`` doesn't seem to be visible to users; it instead tells them they are on a proxy.  We also get users who say "I'm not on a proxy, I'm on a VPN."  Hence I clarified any instructions or buttons to include proxy and VPN.
- Changed up some instructions to ask people to link battles instead of only waiting for a replay.
- Removed some "Click the appropriate button"s since there is only one button.
- Used ``<code>`` tags for all commands.
=> GP help ticket messages

server/chat-plugins/chat-monitor.js
Refer to the code's comment for what this means.
This hasn't been tested.
=> Normalize messages before detecting filter evasion (quick fix)

data/mods/gen1/scripts.js, data/mods/gen2/scripts.js, data/mods/gen3/scripts.js, data/mods/gen4/moves.js, data/moves.js, data/scripts.js, sim/battle.ts, sim/global-types.ts
Captivate, Dream Eater, Leech Seed and Synchronoise have a target-specific immunity calculation. These moves used to use the `TryHit` event, as this used to run once per target. However, this does not properly recreate cart mechanics, as the check should happen before the accuracy check. Additionally, the spread move effect order refactor (#5216) changed the mechanics of the `TryHit` event so that it only runs once (for the first target) thus breaking Captivate and Synchronoise.
This new `TryImmunity` (or I guess you want it just called `Immunity` right?) event allows the move to veto each target independently by returning `false` for immune targets. This also avoids having to specifically add the `-immune` message in each of those moves.
=> Add a single event for a move's own immunity to a specific target

server/tournaments/index.ts
The client already does this, and doing it twice causes `[Gen 7 Let&apos;s Go] OU Single Elimination Tournament!` this, which doesn't seem necessary
=> Don't escape HTML for tour names

config/config-example.js, server/global-types.ts, server/global-variables.d.ts, server/rooms.ts, server/sockets.js, server/tournaments/index.ts, server/users.ts
This commit changes the TypeScript global variable of `Config` from
`AnyObject` to `Config & AnyObject`.
It still falls back to `AnyObject` (hence the 'Take steps') because of
the main-specific `Config` properties that are used without being in the
`Config` object itself.
These can be added by someone with access to the PS main server.
Regardless, this is an improvement as IntelliSense can display and
autocomplete the known properties.
In addition, the TypeScript compiler will now report bugs
concerning the types of the properties, which I have fixed in this
commit.
=> Take steps to statically type Config

server/chat-commands.js, server/users.ts
Per global staff discussion, allow gstaff to opt into blocking PMs from locked and semilocked users due to harassment issues. They're directed to a help ticket if they truly need help.
=> Allow /blockpms to block locked and semilocked users

server/punishments.ts
Request from Staff Suggestions: Currently, if the alt of a trusted user is roombanned or blacklisted, the trusted user remains in the room but can't rejoin from the same IP if they leave.  This bypasses that check since we assume trusted users on shared/mobile IPs aren't malicious if the punishment wasn't directed towards them.
=> Allow trusted users to bypass blacklist/roomban if not directly punished

data/moves.js
Blast Burn's desc changed from "cannot make a move" to "cannot select a move" to match with all other recharge moves
=> Fix Blast Burn wording for consistency

data/random-teams.js, package.json, server/team-validator-async.js, sim/global-types.ts
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/
Unfortunately, we will not be able to use the exciting new features
such as optional chaining and nullish coalescing until Node.js
supports them natively as we use a third-party compiler (sucrase)
rather than tsc to ensure fast build times.
=> Upgrade to TypeScript 3.7

config/formats.js, data/rulesets.js
so various NFE tournaments like old generations or Mix & Mega can be played without gentleman's rule or complex banlists. Tried to ask @TheImmortal for permission beforehand but didn't get an answer so figured I'd just propose it and see if it gets approved
=> Generalize NFE bans into validator rule

server/chat-plugins/roomsettings.js, server/rooms.ts
The TDs have found that setting the default modchat on smogtours to player is undesirable because a lot more casual games happen there than they anticipated.
```
[14:19]Tony:i was wondering how possible it was for to create a /ionext type of command for modchat on smogtours
[14:20]Tony:as in, one of the two players (or both players) enters /modchaton or something in the lobby or their private messages
[14:20]Tony:and then the game starts with modchat immediately on
[14:20]Tony:and if neither player does, then modchat is off
[17:14]pre:we would need to do it in the main code, because its somewhat tricky to implement a /modchatnext as a private plugin
[17:15]pre:whats the motivation?
[17:16]pre:ionext needs to work the way it does to ensure the battle stays private, but is /modchat at the …
```
=> Introduce /modchatnext command

server/chat-plugins/helptickets.js, server/chat-plugins/info.js, server/punishments.ts, server/users.ts
A few changes to the popup for users on a proxy:
1) Link a user on a proxy to information on disabling it within the help ticket system.
2) Handles the case where a user turns off the proxy but doesn't log out by telling them they need to log out fully.  These people frequently end up in help tickets.  Ideally, I'd like to have a "Log out" button here but I can't get it to do anything right now.
Adds the case in help ticket appeals where a user on a "[proxy]" IP that is locked as another user is directed to how to turn off their proxy rather than to IP-appeals, where they would normally get the IP markshared or unlocked. Proxy IPs should remain locked by default, even if another user has a punishment on it.
=> Fix handling of locked and proxy connections

data/formats-data.js, data/mods/ssb/scripts.js, data/moves.js, data/scripts.js, data/statuses.js, sim/battle.ts, sim/dex-data.ts, sim/global-types.ts, sim/pokemon.ts, sim/side.ts, sim/state.ts
Paired with https://github.com/smogon/pokemon-showdown-client/pull/1394
This is a draft of dynamaxing. Feedback is appreciated, I will be debugging and improving the code today myself too. 
TODO:
Client support details:
the `|request|` protocal object will soon also send two new properties on an active pokemon. `canDynamax` is a boolean indicating if the dynamax checkbox should be enabled. `maxMoves` is an array of objects setup in the same way as Z-Moves. `maxMoves` will be defined if `canDynamax` is or if the pokemon is already dynamaxed. Be sure to show the max moves when the checkbox is clicked/by default when `maxMoves` is defined but `canDynamax` isn't.
Start and end minor messages currently are `-dynamax|POKEMON` and `-undynamax|POKEMON`, feel free to have those changed its an easy …
=> Dynamax Draft

server/chat-commands/info.js
Now says "Past Gens Only" if and only if the move is gone from swsh and the gen number is 8 or greater.
=> Add "Past Gens Only" to gen 8 /dt

config/formats.js
Bans for Gen 8 Doubles OU, approved from tier leader MajorBowman:
- Zacian
- Zamazenta
- Eternatus
- Gravnosis clause
=> Add Gen 8 Doubles OU Beta

data/mods/gen7/pokedex.js
...by taking away their Gmax formes in the oldgen pokedex, so those don't get randomly chosen anymore.
=> Fix Pokemon in pastgen randbats sometimes having no moves

sim/dex.ts
Since the data files are only loaded in the getter for Dex.data, which RandomTeam does not actually access, Dex.gen was 0, which led to an empty pokemon pool for random team generation.
This way, Dex.forFormat loads the data required for that format on its own.
=> Fix data loading for 'generate-team'

README.md
The Travis badge on the README.md pointed to a Travis build that did not exist. I pointed it towards the current version at `travis-ci.com/smogon/pokemon-showdown`.
=> Update the Travis badge on README.md

data/abilities.js
Added Intimidate to shortDesc of Keen Eye, Own Tempo, Inner Focus, Oblivious.
Added Oblivious to Intimidate exceptions (source: https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8286324).
Removed `Gaining this ability` from shortDesc of Own Tempo and Oblivious.
Might wanna double-check Keen Eye for rephrasing.
=> Update shortDesc with Intimidate interactions

data/mods/gen7/formats-data.js
This issue was caught by smogon/data's test suite when upgrading from 7 -> 8. I'm not 100% sure about the other attributes, I'm just following the lead on Vikavolt-Totem's entry.
=> Fix previous gen Pikachu/Gumshoos formes

server/chat-plugins/othermetas.js
Right now the /mnm command results in warnings that the mega stone is a CAP stone, even when it is not. This is because isNonstandard is now set to "Past" instead of undefined.
=> Limit MNM warnings to CAP stones

server/chat-plugins/datasearch.js
- added `ds8` alias for `dexsearch` and `usumlearn` for `learn` (should maybe just be sm or both)
- added `gmaxSearch` and `tierSearch` variables to exclude gmax formes unless relevant
- increased every generation cap by one
- added `gmax` parameter to search for gmax formes
- (temporarily) made pokemon tiered `New` show up in `/ds ou`
- Added life dew to recovery moves
Might be wise to not merge until gen8 is more mainstream competitively so people for now just get their gen 7 default datasearch.
Also, `/ds all` excludes pokemon that aren't in the galar dex, but do when you `/ds all, maxgen7`. Might be an unwanted inconsistency, might be the way it should be, I'm not quite sure what to do with it.
=> Update datasearch for gen 8

server/chat-plugins/chat-monitor.js
This doesn't exactly feel like a /good/ way to do this to me, but I can't think of any better way.
=> Require a break on either side of evaded words

sim/dex-data.ts
It's explicitly nonstandard in gen 7 SM, so I think this is fine to do.
=> Mark double iron bash as gen 7

server/chat-plugins/chat-monitor.js
The "."->"__.__" is copy-pasted from elsewhere, but here, the match is put in code formatting, so there's no need for it and it adds more clutter.
=> Remove erroneous autolink escape formatting

sim/team-validator.ts
Removed nature lock from certain events in gen 8 formats as mints allow for editing natures.
=> Change moveset validation to ignore nature restrictions in gen 8

config/formats.js
Approved by 'format leader' Ivy
Ban Libero, Perish Body: https://www.smogon.com/forums/threads/metronome-battles.3632075/post-8289272
Ban Sand Spit, unban Normalium Z: https://www.smogon.com/forums/threads/metronome-battles.3632075/post-8290278
Schooling is unbanned because it is a relic of when the BST limit was 600, and the current 625 limit allows Wishiwashi-School to be used at base.
=> Metronome Battle: Update banlist

data/scripts.js
"A minor text error in the battle log: when a pokemon with Prankster tries to status a Dark-type, it fails and says "In gen 7, Dark is immune to Prankster moves." Since gen 8 is now out, the sentence should probably implicate gen 8 in its semantics (i.e., "Since gen 7")."
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8289288
=> Updated dark pranster immunity message for gen 8.

data/statuses.js
Currently, moves that cause fatigue such as Thrash and Outrage will cause the battle to pause after the first turn of dynamaxing. in [this battle](https://replay.pokemonshowdown.com/gen8doublesou-1014430299), n10sit uses Max Wyrmwind based off of Outrage to attack, and it works fine the first turn. However, the battle falsely emits an Invalid choice on the following turn.
=> Fix lockedmove volatile interaction with Max moves

data/moves.js
Couldn't find any sources on the matter, but Obstruct should behave like the other protection moves. Can someone verify?
EDIT: Current behaviour: Obstruct is broken, regular damage is dealt without being quartered.
=> Make Max moves deal 25% through Obstruct

data/moves.js
Fixes `/ms boosts atk, boosts def, boosts spa, boosts spd, boosts spe` not showing Clangorous Soul.
=> Fix Clangorous Soul not showing up in /ms

data/abilities.js
Overflowing at the moment. 
Also, what's the policy on descriptive abilities?
(stuff like ``This Pokemon is protected by ice scales, which`` which provide a description and can be removed without leaving the effects out of context)
=> Shorten Ice Scales shortDesc

server/rooms.ts
Errors in private code aren't actionable for Showdown contributors without access to private code, so no need to show them the details of those, only for them to realize those files aren't in the repo. This unnecessarily wastes time.
=> Hide stacktraces for private code

data/moves.js, sim/battle.ts, test/sim/misc/target-resolution.js, test/sim/misc/turn-order.js
This makes generation 8 use dynamically updating speed. Specifically speeds are updated after each action in the queue completes. Changes up to this point tested with @DaWoblefet.
TODO:
=> Dynamic speed updates for Gen 8

data/moves.js
Confirmed by Anubis but also mentioned on the forums.
- Magic Powder is a Powder move, and doesn't affect e.g. Grass types.
- Magic Powder just fails, unlike Soak.
=> Fix two issues with Magic Powder

sim/pokemon.ts
I was converting some old OMs to use the `m` property and some of them need it in `onModifyTemplate` which is called during the constructor, and theoretically OMs could override other Pokemon functions and would want `m` to already exist there too.
=> Initialise the m property on Pokemon earlier

data/moves.js
Reported here: https://www.smogon.com/forums/posts/8297191 and other places.
All (G-)Max effects need to run as `self` so that they're unaffected by the target's Substitute.
Since self effects don't identify the target, this means that anything that effects the foes has to explicitly use `source.side.foe`. To make this clearer, I've updated all of the effects for all (G-)Max moves to only use a single `source` parameter, as I'm concerned that someone might subsequently try to use `target` by mistake.
Sandaconda's G-Max move appears not to match its description; Anubis has it on his to-do list of things to check. In the mean time I changed it so something nearer its description.
I also changed G-Max Wind Rage to use itself as the effect that's removing hazards, as that seemed wrong to me. …
=> G-Max moves should run their effects against a substitute

sim/team-validator.ts
Reported here: https://www.smogon.com/forums/posts/8298152
The Gen 8 relearner only allows previously learned moves again.
=> Only in Gen 7 can level-up moves be relearned at any level

config/formats.js
Snorlax-Gmax will be released before the competition starts on cartridge and therefore allowed in the competition, so it'd be great if we could get it unbanned here for testing before the comp starts.
=> Galar Beginnings: Allow Snorlax-Gmax

server/chat-plugins/mafia.js
`Chat#canBroadcast` sets `broadcastMessage` as an indicator that it's run, so setting it manually lets us bypass `canBroadcast`.
=> Mafia: Use a slightly better hack to allow hosts to broadcast

server/ladders-remote.ts, server/ladders.ts
If the remote ladder's update rating method dosen't receive
a response from the login server, it will not change the user's
mmrCache for the format, resulting in future ladder matches using
an outdated ELO until the server receives a response at the end of
a future match.
This is the cause of issues such as users with 1400 ELO being matched
with users with 1000 ELO with a 10 second wait time in current gen OU.
HIGH PRIORITY due to an upcoming OU suspect test. Ideally we merge this and reboot the server tonight.
=> Ladders: Delete rating cache if no response.

config/formats.js
the changes in #6128 make `+Unreleased` no longer needed since `+Past` handles past gen unreleased pokemon now,
=> Remove `+Unreleased` from NatDex Formats

data/formats-data.js
All three can't evolve, and the latter one isn't capable of getting evolved into.
It's the same situation as the other arbitrary Pikachu formes from previous generations.
=> Gmax Eevee, Meowth, and Pikachu shouldn't be LC/NFE

config/formats.js
> chaos11/19/2019
> The Immortal i think we should ban dynamax in cc1v1, theres no point to the random moveset when you're just gonna be spamming Max ___
> or maybe you wanna wait until dynamax stuff is settled in other formats, just seems particularly egregious in this one
> 
> The Immortal11/19/2019
> good point
Given that it is banned in regular 1v1 now, seems like the right time
=> Add Dynamax Clause to CC1v1/CC2v2

data/mods/gen7/moves.js, data/moves.js, sim/battle.ts, sim/global-types.ts
This fixes the issues with priority moves in gen 8.
=> Sort battle actions by order instead of priority

config/formats.js
Rules announced by TPCi: https://www.pokemon.com/us/pokemon-news/2020-pokemon-video-game-championships-vgc-format-rules/
- Still has 7 minute Your Time
- Only legal Gmax Pokemon are the following: Butterfree, Corviknight, Drednaw, Centiskorch, Meowth, Pikachu, Eevee, Snorlax, Sandaconda, Charizard with Blaze. I implemented this by just hard banning every other Gmax mon.
=> Add VGC 2020 format

data/statuses.js
* Removed check that prevented `dynamax` volatile from calling `onEnd` when species is Eternatus-Eternamax.
* Lack of `onEnd` prevented Eternamax's `maxhp` from resetting thanks to the volatile simply being cleared rather than being ended properly. Further switch-ins and switch outs result in further doubling: `maxHp` goes from 700 -> 1400 -> 2800 etc, then is doubled for Dynamax and kept on switch-out, thus causing the bug.
Edit: flaw in initial logic
=> Prevent Eternamax Max HP Doubling

data/statuses.js
Eternamax was losing dynamax benefits after switching out once. This changes the way eternatus-eternamax interacts with the volatile to completely remove health-related matters from the dynamax volatile, instead being handled by the eternamax volatile right at the beginning. 
I've reviewed videos, and none of them have an indicator of any such thing as "eternamax" starting, so a silent start is the most accurate here. It's intrinsic to the mon itself, except weirdly without an accompanying ability.
=> Fix bug caused by #6149

data/moves.js
Confirmed by Anubis: https://www.smogon.com/forums/posts/8305757
- Tea Time targets all Pokémon
- Tea Time doesn't hit semi-invulnerable Pokémon
Tea Time also ignores Unnerve; it was already doing that, but I added a comment to that effect.
I noticed that Perish Song was still trying to do an Accuracy check despite the Invulnerability changes which originally came in with the spread move refactor so I converted it to an Invulnerability check.
=> Some Tea Time updates

data/mods/gen2/formats-data.js
Team generation requires a randomSet1 property on the mon, which this didn't have, I assume because at some point there were multiple sets and they were collapsed into one.
=> Fix Forretress not showing up in gen 2 randbats

config/formats.js
VGC 2020, Battle Stadium Doubles, and Battle Stadium Singles all take Pokemon below level 50 and force them to be level 50 (this was my error when I added Battle Stadium Doubles / VGC 2020 originally). VGC 2020 technically doesn't have a released ruleset in-game yet, but the format announcement confirms it will be autolevel up. https://www.pokemon.com/us/pokemon-news/2020-pokemon-video-game-championships-vgc-format-rules/
=> Correct level implementation for Gen 8 cartridge formats

data/rulesets.js, data/scripts.js
Ditto is still able to Dynamax while transformed as a Megas, Primals, and Ultra Necrozma.  Since Ditto cannot Dynamax as Zacian, Zamazenta, and Eternatus, Megazard has asked me to fix this for more Balance within the National Dex formats.
=> Fix Ditto from Dynamaxing as a Mega/Primal etc

server/chat-plugins/chat-monitor.js, server/ladders.ts, server/room-battle.ts, server/tournaments/index.ts
This commit adds a `challengeType` property to `RoomBattle` of
type `rated | unrated | challenge | tour`.
Previously, there was no way to programatically differ an unrated
battle from a challenge, which is useful in places like filters.
(This pull request requires a restart.)
=> Add a RoomBattle#challengeType property

data/abilities.js, data/moves.js, sim/pokemon.ts
- Cherrim should revert if given a Utility Umbrella in Sun.
- Castform shouldn't keep transforming if it holds a Utility Umbrella.
- Leaf guard Utility Umbrella check works but is just inconsistent placement.
- Sun/Rain affected recovery moves should heal 50% with Utility Umbrella.
- Solar moves power should halve in sand or hail even with Utility Umbrella.
- Weather Ball should double in power if Magic Room blocks Utility Umbrella.
=> Some Utility Umbrella fixes

config/config-example.js
As was discussed.
The roomban permission thing is probably not great. There is a ban permission in the config, but it will apply to all drivers (and includes gban for gdrivers), which I don't want. I'm open to other suggestions of how to implement that.
=> Allow drivers to modchat by default

server/chat-commands/admin.ts
Tested on windows and on linux/bash and I don't think this breaks anything as long as you have a proper node install.
=> Fix rebuilding on windows

data/moves.js
Oversight on my part in #6156: the `Invulnerability` event returns `0` if either source or target has No Guard, `false` if the target is semi-invulnerable, otherwise `true`. Thanks to +Cake for spotting this.
=> Fix No Guard interaction with Perish Song and Tea Time

server/chat-commands/room-settings.ts
(whoops)
"false" is to match the previous formatting for it.
=> Fix modchat modlog entry

server/chat-commands/info.js
Forcing people to use inline code formatting over restrictions that aren't clearly explained and having the input given be changed on you if it starts with a newline is really annoying. This should make it so /code handles input the same way inline code formatting does, just with the addition of accepting multiline input.
=> Commands: remove minimum length and newline restrictions on /code

data/mods/gen1/moves.js
The changes I made to simplify the No Guard checks in later gens mean that this function is assumed to return one of `true`, `false` or `0`, but not `null`, which I overlooked at the time...
=> Make semi-invulnerability work in Gen 1 again

data/abilities.js
Normal Choice items work by setting the choice volatile once a move starts to execute. Since a volatile can only be started once, this means that when you lock into a move that calls another move the lock has already been taken and the second move is ignored.
This emulates that behaviour for Gorilla Tactics by checking that we aren't already locked into a move.
=> Gorilla Tactics should only lock into the first successful move

data/mods/gen2/rulesets.js
Sunflora can only learn Razor Leaf at Level 10, after it evolves. It can only learn Synthesis at Level 31, before it evolves. So it can't have both.
=> Sunflora Gen 2 move legality

data/abilities.js, data/items.js, data/mods/gen7/items.js, sim/battle.ts, sim/global-types.ts
This fixes Custap Berry, Quick Claw and Stall for Gen 8.
In particular, Skill Swap on Stall doesn't affect turn order this turn.
=> Calculate fractional priority once per turn

data/pokedex.js
Pokedex / National Dex number for Toxtricity-Gmax should be 849 instead of 844. Toxtricity and Toxtricity-Low-Key already use the correct number.
=> fix Toxtricity-Gmax pokedex number

data/mods/gen5/random-teams.js
The first Pokémon in any tier is getting counted twice, which is a shame when you're trying to limit to 2 per tier, as you then end up with 1 per tier. The Gen 2 code for counting tiers seems to be appropriate here. A fix may be needed for later gens but I don't understand what the code there is trying to do.
=> Fix tier counting in Gen 5 randbats

sim/battle.ts
Body Press tries really hard to use the attacker's Def, and it's almost clever enough to compensate for Wonder Room, but it turns out that it then goes on to use the attacker's SpD boosts.
Sorry, but I can't remember which researcher discovered this quirk.
=> Body Press uses SpD boosts under Wonder Room

server/rooms.ts
As far as I can tell, the desynch here consists of:
- A tournament is created inside a groupchat.
- The groupchat is manually deleted, destroying the room.
- The tour's end message restarts the room's expire timer after the room has been deleted.
- A new groupchat with the same name is created. 
- The expire timer from the deleted groupchat fires, removing the room's entry in the `Rooms.rooms` map, which now points at the new groupchat.
- The new groupchat now exists without being in the `Rooms.rooms` map. Calamity ensues.
This flushes the groupchat's broadcast buffer when it is deleted, preventing the expire timer from being poked and thus preventing the room being deleted twice.
=> Fix room desynch bug

data/moves.js
In Doubles, Shell Trap fires directly after the physical hit that triggers hit, before anyone else would normally move. Seen in this video: https://www.youtube.com/watch?v=zFnIvJfgvVk&t=270 where Grimmsnarl hits Turtonator with Sucker Punch and Shell Trap then fires before Drednaw or Ninetales can move. Behaviour confirmed to apply also to Gen 7 by @SadisticMystic.
=> Shell trap takes effect directly after a physical hit

data/abilities.js, sim/pokemon.ts
If you switch out the Neutralizing Gas Pokemon once, the ability will simply never work again in the battle.
https://replay.pokemonshowdown.com/gen8customgame-1037347095-5gmu42swmzhcxgzpyfytlk4kkzzkf3gpw
This fixes that.
=> Fix Neutralizing Gas

data/mods/gen1/scripts.js, data/mods/gen2/scripts.js
Followup to #5904; Leech Seed into a Grass type and Dream Eater into anything awake are calculating the immunity correctly but then erroneously crediting it to the attacker instead of the defender.
=> Fix displayed target of move-specific immunity in Gen 1 and 2

server/chat-commands/info.js
!code no longer requires global voice rank to be used in private messages.
=> Update !code help description

server/chat-commands/info.js
Non-existant templates have a base stat object now (with every stat at 0), so just checking whether there is a base stat object isn't enough to filter out nonexistent templates.
=> Fix /statcalc without pokemon argument

sim/battle.ts, test/sim/moves/focuspunch.js
PR for https://github.com/smogon/pokemon-showdown/projects/3#card-29862179
~~Check the current turn's queued messages to see if the pokemon in question will be Dynamaxing this turn or not. If it is Dynamaxing, do not tighten the focus. It will be converted into Max Knuckle later.~~ Now checks all moves during resolution, and lets the `runDynamax` mechanic handle move resolution if the move is considered a Max Move.
I've tested it locally of course. If there's anything else, feel free to leave a comment :)
=> Remove tightening focus mechanic when used by dynamaxed pokemon

config/formats.js
Season 2 of on-cart Battle Stadium unbans select Gmaxes, as per https://www.pokemon.com/us/pokemon-news/clash-with-gigantamax-pokemon-for-great-prizes-in-ranked-battles-january-season/
=> Battle Stadium: Allow Season 2 Gmaxes

data/moves.js
As discovered by a Pokétuber, if you use Court Change to move the webs you set on your opponent's side to your side, they're still your webs, so they don't trigger Defiant or Competitive. (Contrary still works of course.)
=> Fix interaction between Court Change, Sticky Web, and Defiant or Competitive

data/abilities.js, test/sim/abilities/pickpocket.js
Also makes sure that dragging moves like Dragon Tail do activate Pickpocket.
This fixes https://github.com/smogon/pokemon-showdown/projects/3#card-25870242
=> Fix Pickpocket applying when being switched out through Eject Button

config/formats.js
Only Charizard with Solar Power is banned, not the combination of Charizard and another Pokemon with Solar Power.
=> VGC 2020 Validator - Charizard-GMax Fix

data/abilities.js, data/mods/gen3/abilities.js, data/mods/gen4/abilities.js, data/mods/ssb/abilities.js, data/moves.js, sim/battle.ts
Prior to PR #5851 it was possible for OMs such as Dual Wielding and Trademarked to override `battle.getAbility` to introduce custom Ability behaviour.
Although this is no longer possible, most calls to `dex.getAbility` are actually via `pokemon.getAbility` which is still readily overridable by OMs.
This PR is just a mechanical change for 15 places that don't call `pokemon.getAbility` but look as if they could or should.
=> Always use getAbility to get a Pokémon's Ability

data/mods/gen2/moves.js, data/mods/gen3/moves.js, data/mods/gen4/moves.js, data/mods/gen6/moves.js, data/moves.js
- Prior to Gen 6, the Encore volatile's `onStart` handler forcibly removes the volatile if it detects a failure condition. Starting in Gen 6, it also returns `false`, which would automatically cancel the volatile, except that it's still forcibly removed it. All these occurrences have been changed to just return `false`.
- When the Encore needs to be aborted, the current code always forcibly removes the volatile and then manually sends the `-end` message to the client. However, the volatile's `onEnd` handler already sends the message, so the volatile can just be removed normally.
=> Simplify handling of Encore volatile

config/formats.js
we decided to expand the ban to all defense-boosting moves
=> Change the RoA Rotational staff pick

data/mods/gen7/moves.js, data/moves.js, sim/battle.ts, sim/global-types.ts, test/sim/moves/healingwish.js
It's been years since I did this last so idk if I did this right.
Reference https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/page-39#post-8341844
- Healing Wish is not consumed if the Pokemon switching in
has full health and no status condition
- There is no timeout for this effect, it lasts until consumed
- Being statused with full health will consume the Healing Wish
- It does not trigger on damage after switching in
- The effect will be consumed if an injured Pokemon is swapped
into a slot with an active Healing Wish by Ally Switch
=> Fix Healing Wish for Gen 8

data/abilities.js
Currently, Zygarde can have 0% or even negative HP if the Power Construct transformation takes place while it's Dynamaxed (ie. as shown in [this](https://replay.pokemonshowdown.com/gen8nationaldexag-1043549787) replay on turn 9). This PR fixes that.
=> Correctly set hp and maxhp fields if Zygarde transforms while Dynamaxed

server/chat-plugins/helptickets.js
When taking appeals, you're probably wanting to check their modlog roughly 100% of the time, so this is useful for people who like having something to click instead of having to type the command.
(It does hide the button under "other options" but I guess having to click another button first isn't that bad)
=> Add modlog button to appeal tickets

server/chat-plugins/hangman.ts, server/chat-plugins/mafia.ts, server/chat-plugins/uno.ts, server/punishments.ts, server/rooms.ts, server/tournaments/index.ts, test/server/rooms.js
By adding a `getGame` function of type:
```typescript
// null is returned if the gameids don't match
// or the game doesn't exist
getGame<T extends RoomGame>(constructor: new (...args: any[]) => T) => T | null
```
(Credits @urkerab and @whalemer for the function signature.)
It allows refactoring previous code of:
```typescript
if (room.game && room.game.gameid !== 'hangman') return;
const game = room.game as Hangman;
```
to:
```typescript
const game = room.getGame<Hangman>(Hangman);
if (!game) return;
```
This has a couple of advantages:
- TypeScript will throw an error if the if condition is not present.
- In the new code, the template must extends `RoomGame` and be assignable to the same ID, so it's 100% typesafe
=> Allow safer and exact type retrieval of Room#game

data/mods/letsgo/formats-data.js
https://www.smogon.com/forums/threads/lgpe-ou-spectre-mega-gengar-is-now-banned.3658931/#post-8357495
=> Ban Mega Gengar from LGPE OU

server/chat-plugins/lottery.ts
There is no lottery editmarkup command. The proper use is to use /lottery edit, which allows you to edit the number of max winners, the name of the lottery, and the HTML, but also requires all three parameters be included.
=> Fix Lottery Help

config/formats.js
https://www.smogon.com/forums/threads/mew-has-been-banned-from-ss-1v1-moody-quickban.3659726/
=> 1v1: Ban Moody

data/abilities.js, data/items.js, data/mods/gen2/moves.js, data/mods/gen3/abilities.js, data/mods/gen4/abilities.js, data/mods/gen4/items.js, data/mods/gen6/abilities.js, data/mods/gen6/items.js, data/mods/gen7/abilities.js, data/mods/gennext/abilities.js, data/mods/ssb/abilities.js, data/mods/ssb/statuses.js, data/moves.js, data/scripts.js, sim/battle.ts, sim/global-types.ts, simulator-doc.txt, test/sim/abilities/emergencyexit.js
Fixes #6346
#6346 reports that all existing `AfterDamage` handlers should happen after secondaries.
This does that:
- The `AfterDamage` event has been replaced with `DamagingHit`, which which happens for damaging moves after secondaries.
- The `AfterHit` event has also been moved after `DamagingHit`, to make sure Knock Off still procs after Rocky Helmet.
- `AfterHit` is no longer a valid event on `secondary` and `self` blocks, because it's meaningless in those blocks, anyway. All `self.onAfterHit` and `secondary.onAfterHit` handlers have been moved to `onHit`, which should have the same timing in practice.
=> Refactor `AfterDamage` to `DamagingHit`

data/abilities.js, data/items.js, data/mods/gen1/moves.js, data/mods/gen2/moves.js, data/mods/gen2/scripts.js, data/mods/gen2/statuses.js, data/mods/gen3/moves.js, data/mods/gen4/items.js, data/mods/gen4/moves.js, data/mods/gen5/moves.js, data/mods/gen6/moves.js, data/mods/gen7/moves.js, data/mods/gennext/items.js, data/mods/gennext/moves.js, data/mods/ssb/moves.js, data/mods/ssb/scripts.js, data/moves.js, data/scripts.js, sim/battle-queue.ts, sim/battle.ts, sim/global-types.ts, sim/side.ts, sim/state.ts
Previously, battle queue stuff was just strewn around `battle.ts`. This gives it a new home: `battle-queue.ts`.
This was intended to make `battle.ts` slightly more tractable, although the difference is so small that maybe I shouldn't bother. Oh, well, every little bit helps.
=> Refactor queue to new BattleQueue class

config/formats.js
https://www.smogon.com/forums/threads/melmetal-marshadow-and-kyurem-black-have-been-banned-from-gen-8-1v1.3660007/
=> 1v1: Ban Melmetal

server/users.ts
Would let us catch people mistyping `user.update('blockpms')` and the like, if any of those files were typescripted.
=> Make User#update more typesafe

data/formats-data.js
https://www.smogon.com/forums/threads/kyurem-black-and-melmetal-are-now-banned-from-ou.3660047/
=> OU: Ban Melmetal and Kyurem-Black

data/abilities.js, data/moves.js, data/scripts.js, sim/pokemon.ts, test/sim/moves/dragondarts.js
This makes `move.smartTarget` a three-state. I was considering turning it into an integer though.
If it's `true`, then this means that there are two targets, so that Wonder Guard, Protect, semi-invulnerability, type immunity and evasion should be silent.
However, as soon as one of these effects applies, it then goes and sets it to `false`, which means that further failure messages for the other target will appear normally.
Thus if Dragon Darts misses both targets due to evasion, only the neighbouring ally's miss message will appear, as desired.
Note that `false` still counts as smart targeting from the point of view of the hit step loop.
I also tweaked the early exit condition from the hit step loop so that Dragon Darts can hit both foes even if the first faints.
=> Refactor Dragon Darts

config/formats.js, data/mods/gen3/rulesets.js, data/rulesets.js
Even though there is discussion about its existence, I was asked by hogg to implement it for the time being so that ADV UU is being accurately simulated.
I originally did this with ``onValidateSet`` and ``template.nfe``, but the ``template.nfe`` check isnt supported in previous generations.
=> Add ADV UU NFE Clause

server/tournaments/index.ts
The most recent change to this file prevents "/tour autodq off" from working and sends a "That isn't a valid timeout value." error to the client. This is because it checks for a condition where timeout is greater than 1 hour, but when turning autodq off, the timeout variable is set to Infinity.
This proposed change adds a check in the condition for if the timeout value is Infinity and does not send the error if that is the case (but if timeout is a numeric value greater than 1 hour, it still will fail).
=> Fix /tour autodq off

config/formats.js
This fixes some some legal sets not being able to validate, such as a normal Abomasnow set not validating because it thinks the set is Vanillish.
=> Inheritance: Add basic move validation support

data/rulesets.js, server/room-battle.ts
This should work for both the format (when it's back) and tours (when the mod is applied). 
Let me know if there's a way to do this better, but this seemed optimal, since it gets `@@@blitz` too.
from: https://www.smogon.com/forums/threads/enforce-timer-when-blitz-is-added.3655991/
=> Force timer if blitz mod is in effect

sim/global-types.ts, sim/team-validator.ts
This option allows for decoupling intra-set validation from the inter-set team validations which is useful for the team validator to be used incrementally more efficiently in a generative context (i.e. each time a new set is added to a team the team can be validated and then *just* the new set, ie. N set validations instead of N!)
=> Add a skipSets parameter to validateTeam

test/main.js
some of our tests use the chatroom `test`, which goes poorly if that room already exists.
=> Ignore existing chatrooms in tests

server/tournaments/index.ts
Currently, if a tournament has autostart on and less than 2 players exist in the tournament when the autostart timer hits 0, the autostart timer basically never resolves and the tournament never starts. VGC's had this happen a couple times, and other rooms have had the problem too. I thought of three potential solutions to this:
If autostart timer is 0 and there are less than two players:
1. End the tournament
2. Restart the autostart timer with an additional 30 seconds
3. Wait until the tournament reaches 2 players and automatically start
Neither 2) nor 3) are ever guaranteed to make anything happen, so I picked solution 1) for this PR (it was also simplest).
See [bug reports post](https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8212361) …
=> Fix autostart timer bug with less than 2 players

config/formats.js
Does the following:
- Removes Gravity Sleep Clause (approved by DOU tier leader talkingtree and myself, I'm the one taking over the thread)
- Adds the DUbers thread
- Allows DUbers live on the ladder
=> Update Doubles Ubers

test/sim/items/ejectpack.js
Adds three new Eject Pack tests.
**Test 1** (currently fails on sim): Eject Pack should not trigger until all entrance abilities have been resolved in cases of simultaneous switches (such as at the start of the battle or switching in Pokemon after 2 KOs).
I'm not sure if this test is set up quite correct. I want to verify Sun and Electric Terrain exist on the field, then that player 2 is currently attempting to switch.
In-game behavior: https://www.youtube.com/watch?v=dAY99Y5mABk
Showdown behavior (attempts to resolve the switch instantly): https://replay.pokemonshowdown.com/gen8vgc2020-1074228320-w27uyh1s3ble7k2v1d9bas2895nq8x4pw
**Test 2** (currently fails on sim): If multiple Pokemon have Eject Pack, effects such as Intimidate, Leer, or Icy Wind should cause only the fastest Pokemon …
=> Add additional Eject Pack tests

test/sim/abilities/mirrorarmor.js
Currently fails on sim (this test currently fails). Sequence of events should be:
1. Parting Shot used into Mirror Armor.
2. Mirror Armor triggers.
3. Mirror Armor lowers the Attack of the Parting Shot user.
4. Mirror Armor triggers.
5. Mirror Armor lowers the Sp. Atk of the Parting Shot user.
6. The Parting Shot user switches out.
In-game behavior: (same as steps above): https://streamable.com/s2ewv
Showdown behavior (Mirror Armor only triggers once and does not let the user switch out): https://replay.pokemonshowdown.com/gen8ou-1067733088
=> Add Mirror Armor Parting Shot test

config/formats.js
Bans for Mamoswine familly. Glaceon and Frostlass have only 1 ability.
[https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8395762](url)
=> Add Snow Cloak to gen4ou bans

server/chat-commands/admin.ts, server/chat-commands/info.js
Serverside half of https://github.com/smogon/pokemon-showdown-client/pull/1475
Requires the client change, because of the /uhtml fix.
=> Attribute addhtml and code commands

config/CUSTOM-RULES.md
* Cancel Mod was listed twice
* Exact HP Mod does actually show the exact HP, when you hover over it in the battle log
=> Fix in-battle rules list

server/chat-commands/moderation.js, server/roomlogs.ts, server/rooms.ts
This patch (coupled with its accompanying client-side patch) amends the /hidetext command to accept an integer that represents the number of lines that should be hidden.
Sometimes not all lines need to be cleared and several staff (room and global) have suggested that the option to hide just some lines would be useful.
=> Support /hidetext [line count]

test/sim/misc/pledgemoves.js
Currently, when you Dynamax/Z-move with a Pledge attack going second, it interrupts the initial Pledge move for a Pledge combo and sets the base power to 150. It should not be starting a Pledge combo at all; Z-moves / Max Moves do not retain Pledge properties. This commits failing skipped tests for those interactions.
Showdown replays (incorrect):
Dynamax: https://replay.pokemonshowdown.com/gen8doublescustomgame-1085419852
Z-move: https://replay.pokemonshowdown.com/gen7doublescustomgame-1085424282
=> Add tests for Pledge moves modified by Z/Dynamax

test/sim/misc/dynamax.js
Currently, Dynamax reversion is treated as an end-of-turn effect (and a very early one, I might add). It should be the last thing to occur before the start of the 4th turn, after switches have resolved. Because of the improper timing, things like Wishiwashi's transformation, various chip damage (e.g. G-Max Wildfire, Sticky Barb), etc. can all result in slightly different amounts of HP. This commits a skipped failing test for the interaction that gets as close to it as I can think of.
Cartridge interaction: https://youtu.be/5C6JfhhXn2w?t=1017
Sample replay showcasing why this matters, e.g. with G-Max Wildfire: https://replay.pokemonshowdown.com/gen8doublescustomgame-1087718887
A bandaid fix would be to just set Dynamax reversion as the last effect to happen in the end-turn resolution …
=> Add test for when Dynamax should revert

server/chat-plugins/othermetas.ts
I also opted to remove support for `/scale [pokemon], hp` since it was largely unused ad had no actual use.
=> Other Metas chat plugin: Add past-gen support
