smogon/pokemon-showdown

chat-plugins/trivia.js
Reverts Zarel/Pokemon-Showdown#4030
=> Revert "Trivia: make searching results scroll"

chat-plugins/scavengers.js
=> Scavengers: Remove the temporary warning on commas

data/moves.js, data/scripts.js
Made the target of the move ambiguous
=> Update Encore & Fake Out move animations

config/formats.js
=> BH: Ban Primal Groudon

config/formats.js
http://www.smogon.com/forums/threads/sm-monotype-suspect-3-shadow-tag.3617517/
=> Add Monotype suspect test

data/formats-data.js
Based mostly on usage stats for doubles.
=> Random Doubles: Update Necrozma

chat-plugins/info.js
People have reported getting errors like https://i.gyazo.com/778739472cf16b75377bef1c506a493d.png when using `/smogdex`. While this is a smogon-side issue, this is a temporary fix to that error.
=> Don't send people with HTTPS pages with /smogdex

chat-plugins/info.js, chat-plugins/othermetas.js, config/formats.js, tournaments/index.js
=> Don't send people to HTTPS links on smogon

chat-plugins/scavengers.js
Fix crash for ending scavenger game hunts.
=> Fix ending hunts within a parent game

test/simulator/moves/reflecttype.js
=> Tests: Moltres doesn't get Intimidate

PROTOCOL.md
I realized that the headers somehow were removed; this will fix that.
=> Protocol: Fix Markdown Headers

config/formats.js
I'm not sure why this wasn't banned on the 11th
=> AAA: Ban Terrakion

dev-tools/global.d.ts, dev-tools/globals.ts, dev-tools/node.d.ts, sim/battle.js, sim/dex-data.js, sim/dex.js, sim/index.js, sim/pokemon.js, sim/side.js, tsconfig.json
Also improves intellisense for Visual Studio and Visual Studio Code.
A few bugs were found, such as <code>Pokemon.isLastActive()</code> not properly checking for fainted allies and gens 4 and earlier not announcing that a Pokemon has no moves left.
Most of <code>dev-tools/globals.ts</code> can be moved to the new <code>.d.ts</code> files for similar improvements, which I plan to work on incrementally.
=> Typescript: improve Sim typing

chat-plugins/info.js
An idea I had after asking Scotteh to run an `/ipsearch` on a range almost always used by a certain troll. 100+ users is alot to search for, being able to filter by just users in the specific room makes it easier to find them.
=> Allow ipsearch to search specific rooms

config/formats.js
the first ladder period starts at 11 PM GMT -4 on Wednesday the 25th, so if this is merged beforehand, don't hotpatch until that time is reached
=> Add Doubles OU suspect test

config/formats.js
http://www.smogon.com/forums/threads/np-ru-stage-7-oblivion.3619225/
=> Add RU suspect test

config/formats.js
the first ladder period ends tonight at 11 PM GMT -4, and the next ladder period doesn't start until Nov. 1
=> Comment out Doubles OU suspect test

chat.js
I know a lot more about html and javascript now than when I did in August, but it's still a little shaky.
=> /data: Hyperlink to the dex for everything

tournaments/index.js
setMatchResult is already called when the battle is won through the forfeit
=> Tours: fix error on DQ

chat.js
Turns out nesting anchor tags does some weird shit so I had to remove the external ones that appear to be unused anyway.
I'm still not totally sure how I didn't notice that freaky formatting when I tested this.
=> Fix /dt with non-Pokemon

chat-plugins/info.js
I'll also modify /effectiveness in a while
=> Support mod parameter for /weak and /coverage

config/formats.js
requested by @TheImmortal over PMs on discord
=> Add RoA Spotlight

chat-plugins/info.js, config/formats.js
=> Fix /coverage

tournaments/index.js
Also the dq check is cleaner now!
=> tours: fix crash on DQing in RR

tournaments/generator-elimination.js, tournaments/generator-round-robin.js
Apologies if there was a reason for keeping them like that
=> Tours: update brackets to use ES6 classes

chat-plugins/scavengers.js
=> Scavengers: Update scav status for hosts

chat-plugins/scavengers.js
- allow automatically set timer to be adjustable
- allow toggling the queue on and off
- fix bug in /viewhunt when used during a scavenger game with no hunt active
=> Scavenger: add new queue functions

data/formats-data.js
http://www.smogon.com/forums/threads/usage-based-tier-update-for-september-2017-nov-quick-changes-129.3614028/page-6#post-7572991
=> November tier shifts

data/formats-data.js
=> Manaphy is still OU

config/formats.js
- Fix Double of the same item on a pokemon
- Fix two choice items on a pokemon
=> Fix Double Items in Dual Wielding

data/scripts.js
Reported by @DaWoblefet. In particular, Oricorio learns Fly, so it's reasonably easy to reproduce.
=> Dancer should not activate while semi-invulnerable

mods/dualwielding/moves.js
Reported [here](http://www.smogon.com/forums/posts/7577866).
=> Make dual item Switcheroo/Trick permanent

config/formats.js
=> MnM: Actually prevent Deoxys-A from Mega Evolving

mods/gen1/moves.js, mods/gen3/moves.js
Reported [here](https://www.smogon.com/forums/posts/7584241) with video.
=> Struggle only does 1/4 damage in Gen 2 or 3

data/aliases.js
Fairy 虹 Pixie: idk where to post suggestions but i'd like necrozmaU to be an alias of necrozma ultra in /dt
=> Aliases: add necrozmau for ultra necrozma

data/scripts.js, test/simulator/abilities/dancer.js
As far as I can tell, changing the return values for these functions as I have doesn't affect anything else. Lemme know if there's more stuff I should test, or if this is more testing than is really necessary.
=> Dancer shouldn't copy moves that did nothing

data/moves.js, mods/vgc17/moves.js
Should the bug get patched all that needs to be done is to switch the two conditions around. This will keep the necessary Clangorous Soulblaze mechanics. (Currently PS grants Wide Guard full protection against it.)
=> Implement Ultra Sun/Moon's Wide guard Z-move bug

config/formats.js
new mons that aren't in doubles uber should be in doubles ou
=> Doubles UU: Ban New Ultra Beasts and Lycanroc-Dusk

mods/dualwielding/scripts.js
Reported [here](https://www.smogon.com/forums/posts/7590241).
=> Fix Red Card in Dual Wielding

data/moves.js, sim/battle.js, sim/dex-data.js
Thus making `useBestSourceOffensive` unnecessary.
=> Use ModifyMove to handle Photon Geyser mechanics

mods/gen3/formats-data.js, mods/gen3/random-teams.js
* Prioritize high-value STABs and other important moves
* Clean up STAB enforcement and allow certain Pokemon to be STABless
* Optimize Hidden Power selection
* Add a few missing Pokemon
* Remove illegal moves from movepools
* Lots of other minor movepool and move selection improvements
=> Gen 3 Randbat updates

chat-plugins/othermetas.js
I couldn't use `Chat.getDataPokemonHTML`, `Chat.getDataItemHTML`, or `Chat.getDataMoveHTML`, as this required elements that none of those fully provide.
=> othermetas.js: Add /stone

chat-plugins/othermetas.js
I'm not expecting the CAP project to add more mega stones, but you never know...
=> Use isNonstandard to detect CAP Mega Stone(s)

sim/dex.js
As mentioned on commit https://github.com/Zarel/Pokemon-Showdown/commit/e25eeb9eb0e88f7f63c89f9328d5b8344540fe4c#commitcomment-25673579.
=> Put Rockruff-Dusk's template into the cache

data/scripts.js
As mentioned in #4137. Is an accuracy check the best way of detecting a semi-invulnerable state?
This approach also affects both Sky Drop participants - @DaWoblefet can you confirm/deny?
=> Dancer should activate during other two-turn moves

chat-plugins/info.js, punishments.js
Also adds Punishments.punishmentTypes, mirroring Punishments.roomPunishmentTypes
=> Display ip-based punishments on /ip

data/formats-data.js
- Lycanroc-Midday learns Drill Run.
- Lycanroc-Midnight learns Fire Punch.
=> Random Battle: Tweak Lycanroc slightly

chat-plugins/scavengers.js
- In preparation for UGM - make it possible for staff to inherit hunts started from queue
- also fix a small almost non-existent crash between hunts in a scavenger game.
=> Scavengers: update filter, add /inherithunt

config/formats.js, data/formats-data.js
http://www.smogon.com/forums/threads/np-usum-uu-stage-5-obsessions-kommonium-z-and-scolipede-banned-from-uu.3621032/page-3#post-7602183
=> UU: Ban Kommonium Z and Scolipede

chat-plugins/othermetas.js, config/formats.js
The Semi-Official OM analysis project is no longer running, so these pages no longer exist.
=> Formats: Remove OM analysis links

config/formats.js, mods/pic/scripts.js
=> Really fix move disabling in PiC

config/formats.js, data/formats-data.js
http://www.smogon.com/forums/threads/aipom-is-now-banned-from-sm-lc.3622326/
@theimmortal
=> LC: Ban Aipom

mods/gen4/rulesets.js
=> Fix missing semicolon in rulesets.js

config/formats.js
http://www.smogon.com/forums/threads/mix-and-mega-suspect-6-shadow-tag.3622654/
=> Add Mix and Mega suspect test

mods/pic/moves.js
This fixes the new ability's `onStart` function not being called for the ally of the target/user of Skill Swap.
=> Partners in Crime: Fix Skill Swap

data/moves.js, data/scripts.js, data/statuses.js, sim/battle.js, sim/pokemon.js, test/simulator/moves/stompingtantrum.js
(and Happy Hour, for those counting at home)
=> Implement Stomping Tantrum

test/simulator/moves/stompingtantrum.js
Starring gen 7 Pokemon this time for no particular reason.
=> Add test for Recharge -> Stomping Tantrum

chat-plugins/scavengers.js
(mainly used in tandem with /inherithunt)
=> Scavengers: allow all finishers to view hunt

config/formats.js
[OMG YES](http://www.smogon.com/forums/threads/partners-in-crime-om-of-the-month.3618488/page-8#post-7609532)
Tagging @TheImmortal
=> OMotM: Add Sleep Clause

data/items.js, data/moves.js
If you know a better way to avoid the duplication then I'm all ears.
=> Make Leftovers/Black Sludge recovery happen during Grassy Terrain recovery

chat-plugins/tickets.js
All these commands need to work regardless of if the user is in lobby.
/ticket list - Sent by the refresh button
/ticket submit - Sent by the ticket form
/ticket close - Can be sent from the ticket list
=> Make some ticket commands global

chat-plugins/scavengers.js
- cooldown up to 2 minutes
- show finish times for official hunts
Approved by 2/3 RO's (Meicoo, GME) in scavengers room as per room policy.
This change is needed for the very closely approaching UGM, stemmed from UGM room policy discussions.
=> Scavengers: increate cooldown, show official times

data/scripts.js, sim/battle.js, test/simulator/moves/clangoroussoulblaze.js
=> Protect should not affect Clangorous Soulblaze's other target

data/aliases.js
Just some new abbreviations for Pokemon that I've seen used several times before
=> New Aliases

config/formats.js
[18:20:05] %GL Volkner: wait
[18:20:06] %GL Volkner: chloe
[18:20:17] %GL Volkner: i just realized
[18:20:20] %GL Volkner: gengarite's legan
[18:20:23] %GL Volkner: legal
[18:20:26] %GL Volkner: on suspect ladder
[18:22:59] %GL Volkner: meanwhile i have like
[18:23:03] %GL Volkner: 350 coil left for mono
[18:23:09] %GL Volkner: and 51 games left to get it
[18:23:29] #chloe: ye i told ti to fix it he ignored me rip
=> Gengarite shouldn't be legal on MnM suspect ladder

chat-commands.js, package-lock.json, punishments.js, rooms.js, test/application/rooms.js
A work in progress, please leave input here. Requires a client change I'm still working on, will post that at a later date.
=> Add a system for subrooms

chat-commands.js
Don't allow setting a room to be a subroom of itself.
=> Subrooms: Fix another crash

data/abilities.js, data/items.js, data/scripts.js, data/statuses.js, mods/mixandmega/items.js, mods/mixandmega/scripts.js, mods/pic/scripts.js, sim/pokemon.js, test/simulator/abilities/mummy.js, test/simulator/misc/megaevolution.js, test/simulator/misc/mixandmega.js
MnM test pending me figuring out how to do that.
=> Fix certain abilities not being overwritten by most forme changes

chat-commands.js
- Adds /desubroom alias to /unsubroom
- Adds /setsubroom alias to /subroom
- Adds error checking in /subroom to say "Did you mean /subrooms?"
- Now says the parent room when you do /subrooms in a subroom. Also adds /parentroom to do this as well
- Changes some non-changing `let` to `const`
- Removes unnecessary space following `Chat.html`
=> Subrooms: Add more error checking & misc changes

chat-plugins/othermetas.js, config/formats.js
http://www.smogon.com/forums/threads/mix-and-mega-suspect-6-shadow-tag.3622654/page-2#post-7622325
=> MnM: Ban Gengarite and Shadow Tag

data/items.js, sim/pokemon.js
=> Remove an unused parameter from eatItem and useItem

chat.js, package-lock.json, rooms.js, sim/dex-data.js, tsconfig.json
This currently has the minimum requirements to make TypeScript happy for chat.js; most of the function parameters are undocumented. Let me know if you would like me to (to the best of my ability) add descriptions for them.
=> Finish typescripting chat.js

chat-plugins/datasearch.js, chat-plugins/hangman.js, chat-plugins/info.js, chat-plugins/jeopardy.js, chat-plugins/mafia.js, chat-plugins/modlog.js, chat-plugins/poll.js, chat-plugins/roomsettings.js, chat-plugins/scavenger-games.js, chat-plugins/scavengers.js, chat-plugins/thestudio.js, chat-plugins/trivia.js, chat-plugins/uno.js, config/formats.js
In the instances of ``for (let x of y)``, I didn't use `const` because they were modified within the loop and I don't like declaring needless variables just do modify them if we use `const`. However, if `const` is supposed to be standard, I will do that.
=> Refactor chat-plugins and formats to for...of

config/formats.js
http://www.smogon.com/forums/threads/nu-stage-5-pursuit-of-happiness.3624392/
=> Add NU suspect test

config/formats.js, sim/team-validator.js
Also i changed the for loops that i had a stroke over in https://github.com/Zarel/Pokemon-Showdown/commit/74a5863a7c6eae56b88b8603c56fd05f37778055 to for...of loops
@theimmortal
=> Fix formats.noLearn validation

data/abilities.js, mods/gen6/abilities.js
The description only just fits in Team Builder on my Windows 10 PC - I had to switch from commas to `/`s to get it to fit.
=> Add Mind Blown to Damp's description

chat-plugins/scavengers.js
=> Scavengers: change official time colours

chat-plugins/helptickets.js
fixes this thing: ![image](https://image.prntscr.com/image/CmK70ZsASWi1pe10NljEGw.png)
=> Help Tickets: this.room.modlog() should include roomid

chat.js
=> Modlog: remove extra roomid

data/formats-data.js
http://www.smogon.com/forums/threads/drastic-tier-shifts.3578584/page-2#post-6957897
It was BL3 before it moved to OU
=> Kingdra is BL3

config/formats.js
The 1v1 council miscounted the votes
http://www.smogon.com/forums/threads/1v1.3587523/page-40#post-7644586
=> Jirachi isn't actually banned from 1v1

data/formats-data.js
http://www.smogon.com/forums/threads/np-usum-uu-stage-6-chanel-ninetales-alola-banned-see-post-19.3625273/#post-7645482
=> UU: Ban Ninetales-Alola

data/moves.js
I can add something similar for Magic/Trick/Wonder Room as well if you like.
=> Simplify Mud Sport and Water Sport

config/formats.js
http://www.smogon.com/forums/threads/usage-based-tier-update-for-january-2018.3625266/#post-7643579
=> Doubles UU: Cresselia rose to DOU

config/formats.js
blame Kris 
http://www.smogon.com/forums/threads/usage-based-tier-update-for-january-2018.3625266/#post-7643579
=> Doubles UU: Camerupt-Mega rose to DOU

config/formats.js
=> STABmons: Unhardcode checkLearnset

chat-plugins/helptickets.js
Adds a button that you need to click to confirm you want to open a help ticket before its created.
=> Help Tickets: Add confirmation button

sim/battle.js, sim/pokemon.js, sim/side.js, test/simulator/abilities/dancer.js, test/simulator/abilities/thickfat.js, test/simulator/abilities/unaware.js, test/simulator/misc/statuses.js
Edit 3: Okay, we're good to go, pending CI on d98731b.
Edit 2: Hold on, there's a bit more to this commit.
Edit: This PR is ready for review. Should fix #4365.
-----
This PR is not yet complete because some tests are broken, which somewhat confuse me (perhaps because I'm not as familiar with the mechanics of PS/cartridge games).
For example, the Thick Fat test failed with this message:
```
2) Thick Fat
should halve damage from Fire- or Ice-type attacks:
AssertionError [ERR_ASSERTION]: 97 ∈ '[56, 66]'
at Context.<anonymous> (test/simulator/abilities/thickfat.js:22:10)
3) Thick Fat
should be suppressed by Mold Breaker:
AssertionError [ERR_ASSERTION]: 147 ∈ '[85, 101]'
at Context.<anonymous> (test/simulator/abilities/thickfat.js:34:10)
```
but succeeded once I fixed the gender of the Thick …
=> Use PRNG in sim/ files

test/simulator/abilities/angerpoint.js, test/simulator/abilities/arenatrap.js, test/simulator/abilities/clearbody.js, test/simulator/abilities/colorchange.js, test/simulator/moves/belch.js, test/simulator/moves/snarl.js
Our team refactored 7 test files to use the new makeChoices().  We've maintained the previous flow of the battle, including the player choices for 'idle' pokemon. Please let me know if you have any feedback and we can work to improve it! 
Thank you!
=> Refactor 7 Test Files to use makeChoices()

chat-commands.js
To avoid deleting the wrong room by accident, deleteroom requires typing out the full room name.
This PR removes that requirement for personal rooms. It also addresses the following issues with the permission check:
(1) The auth check looks at ``room.isPersonal`` instead of ``targetRoom.isPersonal``.
This should allow any room owner to delete their room if they do it from a groupchat, even if they do not have the makeroom permission.
(2) The room is searched for before permissions are checked. That creates an information leak. Any user can do the following:
- Use on an existing room: /deleteroom - Access denied.
- Use on a non-existing room: The room 'yxxyxyxyxxyy' doesn't exist.
=> /deletegroupchat: Simplify usage

chat-commands.js
(Like the behavior of /deleteroom)
=> Log when a room is deregistered and by who

config/formats.js, data/formats-data.js
http://www.smogon.com/forums/threads/3627043/
RU doesn't want Drought banned: http://www.smogon.com/forums/posts/7664690/
=> UU: Unban Mega Houndoom and ban Drought

chat-plugins/datasearch.js, chat-plugins/info.js, config/formats.js, data/formats-data.js, mods/gen6/formats-data.js, sim/dex-data.js, sim/dex.js, sim/team-validator.js
This is the server-side part of adding `doublesTier`
=> Add doublesTier

config/formats.js
http://www.smogon.com/forums/threads/3627043/
PLEASE DO NOT MERGE THIS UNTIL 10 PM EST (GMT -5) ON JANUARY 26, AND PLEASE HOTPATCH FORMATS AFTER MERGING THIS WHEN IT IS MERGED
=> Add UU Suspect Test

data/moves.js
PS! currently displays "But it failed!" in this case, which is wrong according to a YouTube video I watched recently (sorry I've mislaid it but I'll comment if I find it again.)
=> Targets of the wrong type are immune to Synchronoise

data/formats-data.js, sim/dex.js
handled in https://github.com/Zarel/Pokemon-Showdown-Client/pull/1076
=> Fix Mimikyu-Busted-Totem's tiers

config/formats.js
http://www.smogon.com/forums/threads/stabmons.3587949/page-23#post-7673099
=> STABmons: Ban Blacephalon

data/scripts.js
I got a complaint about this in a PM... this was the only way I could think of fixing it though.
=> Make Pressure work in Shared Power

config/formats.js
http://www.smogon.com/forums/threads/shared-power-om-of-the-month-new-bans.3623341/page-19#post-7674574
=> Shared Power: Update bans

config/formats.js
http://www.smogon.com/forums/threads/mix-and-mega-suspect-test-7-deoxys-speed.3626245/page-3#post-7676949
@TheImmortal
=> MnM: Deoxys-S is banned from holding Mega Stones

config/formats.js
http://www.smogon.com/forums/threads/camomons.3598418/page-7#post-7670402
=> Camomons: Ban Kartana and Kyurem-B

config/formats.js
http://www.smogon.com/forums/threads/shared-power-om-of-the-month.3623341/page-28#post-7680577
=> Shared Power: Ban Mega Beedrill, Harvest, and Multiscale

config/formats.js
(im shared power council)
[8:26 PM] Haaku: Kris you there?
[8:26 PM] Haaku: i think banning sub is the best way to go
[8:31 PM] Kris: ok
[8:31 PM] Haaku: ill make a post about it
=> Shared Power: Ban Substitute

chat-commands.js, ladders.js, punishments.js, tournaments/index.js
I was bored and this has been requested forever.
=> Punishments: Add battle ban

sim/team-validator.js
IMHO if you want to unban both Blaziken and Mega Blaziken then you should have to explicitly unban both.
=> Overriding a template should not unban the Mega

data/rulesets.js
Hacky but this is the only forme that currently has this issue
=> STABmons: Correctly restrict Wormadam

chat-plugins/thehappyplace.js
(Also some string changes)
These changes have been requested by Cerberax
=> THP QotD: Update cmd permission and require author

config/formats.js
https://www.smogon.com/forums/threads/lc-suspect-chickens-in-the-pen.3629645/ @theimmortal
=> Add LC Suspect Test

chat-plugins/mafia-data.js, chat-plugins/mafia.js
Also make lynches reset on day start, not on night start.
=> Mafia: fix some constructor bugs

config/formats.js
@TheImmortal
https://www.smogon.com/forums/threads/nature-swap-leaders-choice.3612727/page-6#post-7706854
=> Nature Swap: Ban Stakataka

data/formats-data.js
https://www.smogon.com/forums/threads/usum-dou-stage-2-suspect-voting.3629784/page-2#post-7708807
=> Move Snorlax to DUber

chat-plugins/mafia.js
=> Mafia: Add selflynch command

config/formats.js
https://www.smogon.com/forums/threads/stabmons.3587949/page-24#post-7711998
=> STABmons: Ban Porygon-Z and restrict Spore

chat-plugins/info.js
The link was broken, so I changed to ("https://www.smogon.com/forums/threads/the-beginners-guide-to-pokémon-showdown.3496279/")
=> Fix broken link to beginner guide

data/scripts.js
As per Mega/Primal. Source: https://www.youtube.com/watch?v=fcsmgNluFhI
=> Fix Z-Power behaviour while Transformed into Ultra

data/abilities.js, data/items.js, data/moves.js, data/random-teams.js, data/scripts.js, mods/gen1/moves.js, mods/gen1/random-teams.js, mods/gen1/scripts.js, mods/gen1/statuses.js, mods/gen2/moves.js, mods/gen2/random-teams.js, mods/gen2/scripts.js, mods/gen3/moves.js, mods/gen3/random-teams.js, mods/gen4/abilities.js, mods/gen4/moves.js, mods/gen4/random-teams.js, mods/gen5/moves.js, mods/gen5/random-teams.js, mods/gen6/random-teams.js, mods/gennext/moves.js, mods/stadium/scripts.js, sim/battle.js, sim/prng.js, sim/side.js, test/simulator/misc/prng.js
Often, you just need a random item in an array. Throughout Pokemon Showdown's code, there are many instances of the following pattern:
```js
let randomThing = things[this.random(things.length)];
```
Make this code easier to read by factoring the indexing into the PRNG#sample function:
```js
let randomThing = this.sample(things);
```
=> Refactor random indexes into sample function

data/aliases.js
bf is now gen7bf, added gen6bf.
=> Update bf alias

config/formats.js, data/formats-data.js
https://www.smogon.com/forums/threads/usum-uu-stage-6-2-voting.3630735/page-3#post-7728269
=> UU: Unban Mega Slowbro

config/formats.js
https://www.smogon.com/forums/threads/baton-pass-has-been-banned-from-oras-ou.3631225/
=> ORAS OU: Ban Baton Pass

chat-plugins/modlog.js
This command allows leaders and administrators to search the rated battle logs found in `logs/` by tier, user, and how quickly the battle finished. It displays the number of matching battles, how many times the user won, lost, tied, and who they fought and how many times. This command would be used to help detect ladder boosting. Already talked with @Marty-D and other upper staff, it appears to have strong support.
=> Add /battlesearch

chat-plugins/mafia.js
=> Mafia: Notify the player subbed in and when they receive their role

config/formats.js
https://www.smogon.com/forums/threads/1v1.3587523/post-7738063
=> 1v1: Unban Marshadow

config/formats.js
=> 1v1: Ban Marshadow

data/random-teams.js
discussed in dev, comment on anything i should do differently
=> Random Battle: Change joke Pokemon

data/factory-sets.json
thank Bughouse for finding these
=> Fix sets having/risking bad Z-Crystals

chat-commands.js, chat.js
Talked about in upper staff a few days ago, no objections, supported.
=> Allow Leaders to block pms

data/moves.js
Spotted in this [video](https://www.youtube.com/watch?v=BJ1-Mmw1-0A), and confirmed for ORAS by Merrity.
=> Delta Stream does not affect Weather Ball

config/formats.js
Hopefully this is the last ban for a while
=> Metronome Battle: Ban Fluffy

data/formats-data.js
https://www.smogon.com/forums/threads/usage-based-tier-update-for-april-2018.3632386/#post-7753731
=> Update doublesTier for April

data/formats-data.js
This also handles the Togedemaru oversight.
=> Tiers: Fix overlooked Doubles shifts

data/moves.js, data/scripts.js, dev-tools/globals.ts, mods/gen1/moves.js, mods/gen1/scripts.js, mods/gen2/moves.js, mods/gen2/scripts.js, mods/gen3/scripts.js, mods/gen4/scripts.js, test/simulator/abilities/magicbounce.js
This mostly matters for stuff like Magic Bounce and Volt Absorb, which should not activate when the target of the move that would activate them is semi-invulnerable. You can thank Metronome Battle for me finding this.
=> Check semi-invulnerability before immunities, abilities, etc.

data/moves.js, sim/pokemon.js
TODO: Check if this also applies to gens 2 and 3.
=> Spite: show actual PP reduction

package.json
**What?**
[Husky](https://www.npmjs.com/package/husky) is a dependency that makes githooks easy. It allows you to hook into commits, pushes & etc.
**Why?**
Prevent bad commits. Make pull request look more clear by preventing commits like 'Fix Travis'. This makes it easier to focus on the problem a PR is trying to solve.
=> Dependencies: Add Husky githook

config/formats.js
https://www.smogon.com/forums/threads/baton-pass-adv-ubers-edition.3632571/
=> ADV Ubers: Ban Smeargle + Ingrain

chat-plugins/mafia.js
Modlog: Make modlog not modlog in global modlog when game is ended via html room
Broadcast: Make host broadcast certain commands
Add: Show who added a user
Playercap: Lets host to set a player cap for users to join the game
=> Mafia: Modlog/Broadcast/Add Changes & add playercap

data/formats-data.js
https://www.smogon.com/forums/threads/np-nu-stage-7-back-in-black.3631363/page-2#post-7759801 @TheImmortal
=> NU: Ban Abomasnow-Mega, Bruxish, and Camerupt-Mega

config/formats.js
https://www.smogon.com/forums/threads/almost-any-ability.3587901/page-19#post-7518170
It was unbanned in September last year..... nobody unbanned it
=> AAA: Unban Aegislash

config/formats.js
https://www.smogon.com/forums/threads/stabmons.3587949/page-25#post-7761459
=> STABmons: Ban E-Speed on the suspect test ladder

data/formats-data.js
https://www.smogon.com/forums/threads/np-ru-stage-9-save-tonight-mega-houndoom-mienshao-and-entei-banned.3625382/page-2#post-7762211
=> RU: Update bans

config/formats.js
=> Metronome Battle: Update Bans

mods/gen1/scripts.js, mods/gen2/scripts.js
While I'm at it, what does that comment in the gen 1 file mean? It's 3 years old now.
=> Gens 1 & 2: Support Inverse mod

data/moves.js
Reported [here](https://www.smogon.com/forums/posts/7757283), so I copied Outrage/Petal Dance/Thrash, although they might not be 100% correct either.
=> Sleep should prevent Ice Ball and Rollout from locking

data/abilities.js, mods/gen6/abilities.js
Double Checked by testing in the sim.
=> Fix Mummy Desc

data/moves.js, data/scripts.js, test/simulator/moves/stompingtantrum.js
Please excuse the typo in the commit name.
=> Fix Defog and Splash-likes being erroneously counted as failures

chat-plugins/poll.js
This refactors chat-plugins/poll.js to use template strings as opposed to string concatenation to construct the data it sends to a room.
=> Poll: refactor to use template strings

config/formats.js
https://www.smogon.com/forums/threads/mix-and-mega-suspect-8-naganadel.3632455/page-3#post-7773084
=> Mix and Mega: Naganadel can't Mega Stones

chat-plugins/mafia.js
not sure how this wasn't found earlier, honestly
=> Mafia: fix crash with subs

data/scripts.js
I realized I had made a mistaken assumption.
=> Fix Baton Pass fail message

data/formats-data.js
https://www.smogon.com/forums/threads/np-ru-stage-10-levels-entei-unbanned.3633367/#post-7781594
=> RU: Unban Entei

config/formats.js
Until this move gets fixed, it's getting banned
=> Metronome Battles: Ban Metronome (Item)

chat-plugins/info.js
Reported [here](https://www.smogon.com/forums/posts/7787099).
=> Show details for both Metronomes

data/formats-data.js, data/random-teams.js
Also, fix Intimidate Facade Luxray in doubles.
=> Random Doubles: Add sets for new USUM mons

chat-plugins/modlog.js
- Supports `ripgrep`, and uses it if possible.
- Only searches the last 3 months of logs for the tier provided.
=> Refactor /battlesearch

chat-commands.js
Same reasoning as <code>/adduhtml</code>, but in PMs.
=> Add /pmuhtml

data/moves.js, test/simulator/moves/healblock.js
Was reported a while ago, but fixing the other thing reminded me https://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/page-369#post-7532434
=> Heal Block should not prevent any direct healing effects from Z Moves

config/formats.js, data/moves.js, data/statuses.js, dev-tools/globals.ts, sim/battle.js, sim/pokemon.js, test/simulator/misc/silvally.js
This fixes Pokemon like Minior having their type hidden after a forme change in Camomons, and fixes hacked Arceus in BH not showing their true type.
=> Fix type display in Gen 7 metas

sim/pokemon.js
I think I'm gonna take a break from coding for a while, I feel too embarassed about this.
Honestly, I remember thinking, "Did I test megas? Yeah, I tested Mega Alakazam."
=> Actually fix Camomons

data/abilities.js, data/items.js, data/moves.js, data/scripts.js, data/statuses.js, mods/gennext/moves.js, mods/mixandmega/items.js, mods/mixandmega/scripts.js, sim/battle.js, sim/dex-data.js, sim/pokemon.js, test/simulator/misc/statuses.js
I was originally trying to do something else but I ended up doing this which turns out to have nothing to do with the solution to the original problem so I'm making this its own PR.
=> Make formeChange handle relevant messages and ability changes

sim/pokemon.js, test/simulator/moves/transform.js
Finally, something I can add unit tests for.
=> Fix transforming into Arceus/Silvally

config/formats.js, data/statuses.js, sim/pokemon.js
Ok, hopefully this is the last camomons fix 😅
=> Camomons: always modify the template unless the Pokemon is transforming

data/moves.js
Brine is meant to work at 50% of max HP or less, not just at below 50%.
=> Fix Brine at exactly 50% HP

data/moves.js
Reverts Zarel/Pokemon-Showdown#4695
=> Revert "Psycho Shift should fail verbosely"

data/moves.js, mods/gen2/moves.js
Reported [here](https://www.smogon.com/forums//posts/7794032).
=> Rest's HP check precedes Snatch

config/formats.js
Having the source check just kind of broke the mechanic
=> Fix Scalemons

config/formats.js
=> Suicide Cup: Prevent Pokemon from starting as Mega

chat-plugins/mafia-data.js
tests for themes and ideas will come once role parsing's been refactored out of the mafia object
=> Mafia data: fix errors

config/formats.js
https://www.smogon.com/forums/threads/scalemons-leaders-choice.3607934/page-4#post-7805453
=> Scalemons: Ban Carvanha

chat-plugins/mafia-data.js, chat-plugins/mafia.js
todo: actually add proper idea roles
=> Mafia: Add ideas

chat-plugins/mafia.js
no idea why typescript let this through originally
=> Mafia: fix crashes with role setting

chat-plugins/mafia.js
and start refactoring logic into the mafia object
i swear that ive fixed this issue with spirits before...
=> Mafia: fix crash with restless spirits

config/formats.js
https://www.smogon.com/forums/threads/scalemons-leaders-choice.3607934/page-4#post-7812557
=> Scalemons: Ban Abra, Gastly, and Huge Power

chat-plugins/mafia.js
=> Mafia: fix crash on subbing

chat-plugins/mafia-data.js
Add data for Goon and Vanilla Townie so they don't crash upon their data being called.
=> Mafia: Fix data crashes.

chat-plugins/mafia-data.js, chat-plugins/mafia.js
=> Typescript mafia data

chat-plugins/datasearch.js
=> Fix logical error in movesearch

config/formats.js, mods/metagamiate/scripts.js
=> Metagamiate: Fix shiny-locked Pokemon

config/formats.js
https://www.smogon.com/forums/threads/dpp-baton-pass.3635756/page-2#post-7831055
=> Gen IV OU: Add Baton Pass Clause

sim/dex-data.js, sim/dex.js, test/application/team-validator.js
Also adds some tests for custom rules
=> Dex: support custom rules altering complex bans

.travis.yml, package.json
Also attempt to fix npm cache issue
(making a PR to test cache changes)
=> Travis CI: update to Node 8 and fix Typescript cache

chat-plugins/scavenger-games.js, chat-plugins/scavengers.js
- add Incognito
- fix Jump Start
- enhance display for /scav status
=> Scavengers: Manage Game Modes

data/formats-data.js
https://www.smogon.com/forums/threads/usage-based-tier-update-for-july-2018-for-real-this-time.3639170/
https://www.smogon.com/forums/threads/usage-based-tier-update-for-july-2018-for-real-this-time.3639170/#post-7848862
=> Doubles UU: usage update

data/moves.js
Reported [here](https://www.smogon.com/forums/posts/7807585).
=> Splintered Stormshards should not trigger Grassy Terrain recovery

config/formats.js
https://www.smogon.com/forums/threads/reversed-leaders-choice.3623871/page-6#post-7850450
=> Reversed: Ban Tapu Koko

data/formats-data.js
https://www.smogon.com/forums/threads/np-ru-stage-11-ill-drown-mega-slowbro-mega-sceptile-banned.3638874/#post-7855251
=> RU: Ban Mega Sceptile and Mega Slowbro

chat-plugins/modlog.js
- Only searches one day of logs to speed up the search process by alot (tested with 1.7k RU logs)
- Improved the regexp used with ripgrep so that it handles characters that arent in userids (spaces, _, *, ect). This fixes a bug where battle search would not find any battles for user who had characters other than letters/numbers in their name, even if there were battles.
- Used the HTML room for selecting the month, tier (based on month), and date (based on month & tier). This means that battle search can even be used on formats that are no longer playable.
Should overall be faster, and work much better.
=> Battlesearch: Refactor to only search one day

chat-plugins/mafia.js
playerrole was requested by snaq
=> Mafia: support lynch modifiers

config/formats.js, dev-tools/globals.ts, sim/battle.js, sim/pokemon.js
I think this includes all of the little tweaks needed to get Benjamin Butterfree working:
- Allowing `BeforeFaint` to cancel the faint
- Allowing `FormeChange` to keep the secondary or Hidden Ability
- Not immediately claiming that 0HP is fainted so that the client doesn't get confused.
=> Other Metagames of the Month August 2018

config/formats.js
@TheImmortal or anyone this is urgent
=> Ban Shaymin-Sky from Gen 6 Mix and Mega

config/formats.js
Reported [here](https://www.smogon.com/forums/posts/7869988).
Abilities process during the forme change which means that Porygon's Download boost is getting lost.
=> Clear boosts before devolving

chat-plugins/info.js
Helps answer a question that is asked very often
=> Add new ladderhelp entry to /faq

chat-plugins/othermetas.js, config/formats.js
https://www.smogon.com/forums/threads/mix-and-mega.3587740/page-39#post-7875218
=> M&M: Allow NFE Pokemon to Mega Evolve

config/formats.js
=> Formats: Fix Mix and Mega's description

config/formats.js
https://www.smogon.com/forums/threads/benjamin-butterfree-leaders-choice.3605680/
the initial banlist was never implemented
@TheImmortal
=> Benjamin Butterfree: Update bans

data/abilities.js
Reported [here](https://www.smogon.com/forums/posts/7877947). Regression from 82c792f.
=> Synchronize should trigger activations of other Abilities again

data/factory-sets.json
new sets: https://pastebin.com/pNhcCbGv
set updates (i looked over these and fixed code and got rid of duplicates, etc, they just submitted it like this fsr): https://pastebin.com/nvWzWHf4
=> Battle Factory: Update UU

chat-plugins/scavengers.js
=> Scavs: Point system updates

chat-plugins/scavenger-games.js, chat-plugins/scavengers.js
=> Scavs: Fix bugs with create aliases

data/random-teams.js, mods/gen6/random-teams.js
In extremely rare situations, Techno Blast will be rejected on Genesect
because Bug Buzz has not been chosen from the move pool. Prevent that.
=> Random Battle: Fix Genesect formes

config/config-example.js
Inadvertently changed in 7596746.
=> Fix http://

chat-plugins/info.js, chat.js, rooms.js
Same commands and reasoning as https://github.com/Zarel/Pokemon-Showdown/pull/4840, but sending to voices as well.
=> Support roomauth-only HTML boxes

config/formats.js
https://www.smogon.com/forums/threads/sketchmons-om-of-the-month.3587743/page-14#post-7908288
=> Sketchmons: Restrict Extreme Speed

chat-plugins/info.js
Introduced in https://github.com/Zarel/Pokemon-Showdown/commit/9e93c4cf1d54ec3da65cbc95a8c64b3214e628d8
=> Rules: Fix crashes when used in PMs

config/formats.js, mods/gen5/formats-data.js
https://www.smogon.com/forums/threads/bw-ou-diglett-and-excadrill-suspect-discussion.3641738/page-2#post-7920364
=> BW OU: Ban Arena Trap, Unban Dugtrio

config/formats.js, tsconfig.json
=> Gods and Followers: Fix Mega Evolution validation

chat.js
fixes `/mafia player` and friends giving promotehelp
=> Chat: Don't try to parse promote commands in namespaces

data/formats-data.js
https://www.smogon.com/forums/threads/usage-based-tier-update-for-october-2018.3642391/page-2#post-7926403
=> Doubles tier shift updates

chat-commands.js, punishments.js
Most punishments should be dealt with using help tickets instead of the forum
=> Update appeal links

data/aliases.js
[19:29:34] %Kris: Zarel can i add neckboy as an alias for exeggutor alola
[20:27:38] #Zarel: hm
[20:27:41] #Zarel: I'd say yes
[20:27:45] #Zarel: how common is that?
[20:27:57] %Kris: its like
[20:28:13] %Kris: used more to refer to exeggutor alola in the randbats room
[20:28:18] %Kris: than the name itself
[20:40:07] +ACakeWearingAHat: I can confirm with neckboy btw zarel
=> Add 'neckboy' alias for Exeggutor-Alola

config/formats.js
@TheImmortal https://www.smogon.com/forums/threads/ultra-spooky-cup-ghost-shiny-mimikyu-as-entry-gift.3642514/
@Marty-D (because there was some miscommunication about if `requirePlus` is needed or not)
=> Add Ultra Spooky Cup

config/formats.js
https://3ds.pokemon-gl.com/dl-regulation/6019
=> Fix Ultra Spooky Cup Banlist

chat-plugins/scavengers.js
by request of the room and approval of Meicoo-sama
=> Scavengers: make queue public

chat-plugins/mafia.js
=> Mafia: Fix lynch transferring on sub

mods/ssb/moves.js
Changelog: Prevents Lycan from having no status move, fix infinite sleep glitch, fix hurl, clarify descriptions
=> Ssb: fix bugs

config/formats.js, data/formats-data.js
https://www.smogon.com/forums/threads/usum-uu-suspect-process-stage-9-1-voting.3642944/page-3#post-7942983
=> UU: Unban Bisharp

chat-plugins/modlog.js
-Always use ripgrep if possible
-Don't fetch vastly more lines than needed
-Make crashes more obvious to the user
This relies on `tac` but i think anything with ripgrep should also have it
=> Improve modlog

chat-commands.js
https://www.smogon.com/forums/threads/approved-suggestions.3514540/post-7939081
=> Battleban: Require a battle replay if used outside of a battle

config/formats.js, mods/fortemons/scripts.js, sim/pokemon.js, tsconfig.json
=> Add OMotM, LCotM, and RoA Spotlight November

config/formats.js
https://www.smogon.com/forums/threads/averagemons-leaders-choice.3590605/page-3#post-7949179
=> Averagemons: Ban Baton Pass

chat-plugins/thecafe.js
with file loading it's far easier just to hardcode constructor checks
=> Cafe: Bugfixes

config/formats.js
https://www.smogon.com/forums/threads/fortemons-om-of-the-month.3638520/page-12#post-7953876
=> Fortemons: Fix onModifyPriority, update bans

chat-plugins/modlog.js
=> Modlog: Check for tac availability for modlog

data/bss-factory-sets.json
...to ensure that Salac Berry activates after Belly Drum + Sub
=> Update BSSF Kommo-o EVs

config/formats.js, mods/ssb/moves.js, mods/ssb/scripts.js, mods/ssb/statuses.js
A lot of bugs were reported so i decided to fix them
=> SSB: Bugfixes

chat-commands.js, chat-plugins/roomsettings.js, config/config-example.js
Technically it is possible, but talking w HoeenHero and we decided that its really impractical. So probably to get rid of it.
Any other commands that seem unnecessary is battles?
=> Prevent room and staff introductions in battles

data/formats-data.js
Replace Hammer Arm with Drain Punch in Doubles, and add Protect.
=> Random Battle: Update Buzzwole

mods/ssb/moves.js, mods/ssb/random-teams.js, mods/ssb/statuses.js
tested and works.
I have confirmed with the user formerly known as Zyg with the new move name
=> SSB: Zyg -> Earthbound Misfit

mods/letsgo/formats-data.js
@TheImmortal 
This is the server-side part of the client-side changes
=> Update Let's Go tiers

config/formats.js
https://www.smogon.com/forums/threads/1v1-metagame-discussion.3587523/post-7966762
=> 1v1: Ban Detect

config/datacenters.csv
Did some research, this should prevent most TouchVPN connections. /ipsearch only found one user, and viewing that IP with a web browser has shown NordVPN webpage.
=> Add datacenters used by TouchVPN

config/formats.js
https://www.smogon.com/forums/threads/oldgens-little-cup-resource-thread-beta.3602557/post-7968305
=> Ban Sand Rush from BW LC

data/moves.js
=> Fix Solar Blade in Sun animation

mods/letsgo/rulesets.js
@TheImmortal 
I didn't really think about LGPE Hackmons happening so I overlooked these. Sorry.
=> Let's Go: Fix issues with legality

README.md
surprised i didnt catch this before it was merged actually
=> Fix misspelled name in credits

chat-plugins/trivia.js
We're trying to find a happy balance of how long these questions will be so there might be another couple of these just modifying in this soon.
=> Trivia: Update number mode to 6 seconds

data/formats-data.js
It's more powerful than Flame Wheel and hits both Rock and Steel super
effectively, unlike Flame Wheel only being super effective on Steel.
=> Random Battle: Enable Stomping Tantrum Raticate

mods/ssb/moves.js, mods/ssb/random-teams.js, mods/ssb/statuses.js
tested everything and works
~~also why is zyg making me do more work than needed?~~
=> SSB: Zyg again + bugfixes

config/formats.js
@TheImmortal https://www.smogon.com/forums/threads/almost-any-ability-suspect-weavile.3645196/
=> AAA: Add Weavile suspect notice

chat-plugins/info.js
The thread is called "Bug Reports"
=> Add bugreports alias for bugs

sim/pokemon.js
Reported [here](https://www.smogon.com/forums/posts/7994362).
Presumably a regression from #4764.
=> Illusion should copy post-mega species

chat-commands.js
Also moved RO to be before Leader and Admin
=> deleteroomhelp: Hosts can delete their own groupchat

data/scripts.js
(screenshot and research credit to SadisticMystic)
=> Submoves lose their inherent Mold-Breaking properties, if any

chat-plugins/info.js
Modchat can be set for any rank, voice isn't anyhow special.
=> Remove a note about talking during moderated chat from /groups

data/formats-data.js
https://www.smogon.com/forums/threads/sm-ou-suspect-process-round-6-voting.3645563/page-11#post-7999912
=> Move Zygarde to Uber

mods/letsgo/formats-data.js
@Marty-D https://www.smogon.com/forums/threads/lgpe-overused.3644015/page-18#post-8000726
=> Let's Go: Update tiers

config/formats.js, mods/gen4/formats-data.js
https://www.smogon.com/forums/threads/dpp-ou-latias-test.3645502/page-2#post-7998496
=> DPP: Move Latias to OU

PROTOCOL.md
PSBot is a bot I'm working on that will specialize in easily
customizable responses to chat messages, so it fills a niche that the
other bots on the list don't fill.
=> Add PSBot to the bot list in PROTOCOL.md

data/formats-data.js
singles: https://www.smogon.com/forums/threads/usage-based-tier-update-for-jan-2019.3645743/#post-8003320
doubles: https://www.smogon.com/forums/threads/usage-based-tier-update-for-jan-2019.3645743/#post-8003351
=> Implement January 2019 tier changes

data/formats-data.js
=> Fix Mega Glalie's, Mega Slowbro's, and Slowking's tiers

data/formats-data.js
https://www.smogon.com/forums/threads/np-ru-stage-12-summertime.3639410/page-3#post-8006400
=> RU: Quickban Darmanitan

chat-plugins/trivia.js
This makes leaders get computed when necessary and prepares for multiple leaderboards in the future.
=> Refactor trivia leaders computation

config/formats.js
https://www.smogon.com/forums/threads/np-ru-stage-13-party-for-one-meloetta-suspect-test.3645883/
=> RU: Add Meloetta suspect notice

chat-plugins/daily-spotlight.js
=> Spotlights: Improve help

chat-plugins/trivia.js, test/chat-plugins/trivia.js
The old leaderboard will be the all-time leaderboard, and work the same way as it always did.
The new leaderboard gives 5 points for the first place, 3 points for the second place, and 1 point the third place and will get reset sometimes.
=> Trivia alternate leaderboard

sockets.js
xhr-streaming connections were the only connections that were becoming
ghost connections. This sets a timeout of the SockJS heartbeat interval
plus one second to account for any delay in receiving the SockJS
heartbeat packet to close the connection if it has been inactive during
that time.
=> Properly handle ghost connections

data/moves.js, data/scripts.js, dev-tools/globals.ts, mods/gen1/scripts.js, sim/battle.js, test/simulator/moves/stompingtantrum.js
This works, though I don't know if it's what @Zarel had in mind...
p.s. no idea why the old build even passed, seeing as the original test i wrote was actually wrong.......
=> Fix stomping tantrum vs. only Protect

mods/ssb/moves.js, mods/ssb/statuses.js
=> SSB: Fix Compost & Wonder trade with False

chat-plugins/datasearch.js
The Alola formes are so different to regular formes that displaying both the regular form and Alola form is actually a useful information.
=> Always display Alola formes in /ds

data/factory-sets.json
RU QC gave me updated sets for Battle Factory because the last time RU Battle Factory sets were updated was when they were added.
Wingull was removed because it's LC Uber.
=> Battle Factory: Update RU and LC

.eslintrc, .travis.yml, package.json, pokemon-showdown, server/chat.js, server/index.js
Keep in mind that this increases Showdown's version requirements to next LTS.
=> [Increases Node.js version requirement] Refactor Emoji regex to use \p syntax

config/formats.js
Only the base forme was supposed to be banned.
=> STABmons: Fix Thundurus ban

server/chat-plugins/info.js
As per @HoeenCoder's addition to issue #2444
=> Add in-battle mod detection to /weak and /coverage

config/formats.js
https://www.smogon.com/forums/threads/lc-suspect-bush-doesnt-care.3647220/
=> Add LC suspect notice

config/formats.js, data/learnsets.js, data/mods/gen6/pokedex.js, data/pokedex.js
https://www.smogon.com/forums/threads/np-sm-cap-stage-1-toxic-mega-crucibelle-nerfed.3646819/page-2#post-8044530
=> CAP: Nerf Crucibelle-Mega

data/items.js, data/mods/ssb/scripts.js, dev-tools/globals.ts, sim/battle.js, test/simulator/items/seeds.js
Reverts Zarel/Pokemon-Showdown#5163
=> Revert "Fix terrain seed activation timing"

config/formats.js
Quote asked me to do this for an upcoming suspect.
=> 1v1: Unban Kyurem-Black

server/tournaments/index.js
Fixes a bug introduced by #5121
=> Tours: Fix a forfeit being reported as failed even though it succeeded

test/simulator/abilities/normalize.js, test/simulator/moves/curse.js
Stumbled upon these as I was in the process of debugging my `getRelevantEffects` optimization.
=> Fix random typos in tests

translations/simplifiedchinese.json
Bumba's OS not showing those characters somehow
=> Fix an inaccurate simplified Chinese translation

data/mods/pokebilities/abilities.js
Now Trace copies a random ability from a random target, regardless of whether it was originally an innate or not. (This fixes Trace)
=> Pokebilities: Update Trace, Power of Alchemy, and Receiver

config/formats.js, dev-tools/globals.ts, sim/battle.ts, sim/pokemon.ts
And now to take my pound of flesh from battle performance for the sake of OM mashups 😈 
(but seriously this only runs once per switch and forme change)
=> Run onModifyTemplate on rulesets for custom formats

server/chat-plugins/modlog.js
This should prevent issues in which the /modlog takes forever because it's waiting for previous /modlog command.
=> Make modlog asynchronous

config/formats.js
=> Fix Other Metagames of the Month

config/formats.js
Can RBY UU added as a challenge option? It's featured in 1 gym challenge annually, 1 ladder annually and 1 team tournament annually.
=> Added RBY UU

server/chat.js
Special case for Zygarde since it has an S ability but no hidden one.
=> Fix /dt showing 'undefined' as Zygarde ability

config/formats.js
https://www.smogon.com/forums/threads/usum-lc-abra-suspect-voting.3647754/page-2#post-8057147
=> Remove LC suspect notice

config/formats.js, data/formats-data.js
https://www.smogon.com/forums/threads/torchic-has-been-freed.3647800/
=> LC: Unban Torchic

config/formats.js
=> Revert buggy Megamons "fix"

config/formats.js
=> Fix Chimera HP Bug part 2

config/formats.js
https://www.smogon.com/forums/threads/chimera-1v1-leader%E2%80%99s-choice.3607451/
=> Chimera: Fix ability bugs and fix banlist

data/mods/gen6/moves.js, data/moves.js, test/simulator/moves/stockpile.js
as researched by @SadisticMystic
=> Gen 7: Stockpile should keep track of how many times it alters each stat

server/chat-plugins/info.js
So it doesn't not give you the right result if you end it in a space
=> Trim FAQ target

data/mods/gen2/scripts.js
=> Add hints for odd Gen 2 behavior

data/mods/gen1/moves.js, sim/battle.ts
Bulbapedia, UPC, etc all seem to agree that these should act the same.
=> Fix Gen 1 Jump Kick to be like Hi Jump Kick

data/learnsets.js, data/mods/gen6/pokedex.js, data/pokedex.js
https://www.smogon.com/forums/threads/np-sm-cap-stage-2-kiss-from-a-rose-necturna-nerfed.3647435/page-2#post-8059938
=> CAP: Nerf Necturna

config/formats.js, data/mods/mixandmega/scripts.js, dev-tools/globals.ts, sim/dex-data.ts
- BasicEffect#weather's type got messed up during the rewrite in .ts
- Add Template#originalMega? to match the declaration in globals.ts
=> Fix minor Typescript bugs in dex-data.ts

data/mods/gen1/moves.js, data/mods/gen1/scripts.js, data/mods/gen1/statuses.js, data/mods/gen2/moves.js, data/mods/gen2/scripts.js, data/mods/gen2/statuses.js, data/mods/gen4/abilities.js, data/mods/ssb/moves.js, data/mods/ssb/scripts.js, data/moves.js, data/scripts.js, data/statuses.js, sim/battle.ts
After which most of #5242 will be covered, minus behavior I can't confirm we even implement yet which will take longer.
=> Add more hints to Gen 1 & 4, migrate others to Battle#hint

data/mods/gen1/moves.js, data/mods/gen1/statuses.js, sim/battle.ts, test/simulator/moves/substitute.js
=> Fix Gen 1 Substitute + self damage behavior

data/mods/gen2/scripts.js
https://github.com/Zarel/Pokemon-Showdown/commit/a04d4da992ef577b8d6073855c0d90b0ee59cf1a#r32637818
=> Fix Gen 2 stat rollover hint

data/mods/gen2/moves.js, data/mods/gen4/moves.js, data/mods/gen5/moves.js, dev-tools/users-utils.js, lib/repl.ts, server/chat-commands.js, server/chat-plugins/info.js, server/chat-plugins/poll.js, server/chat-plugins/thing-of-the-day.js, server/chat-plugins/trivia.js, server/chat-plugins/wifi.js, server/punishments.js, server/tournaments/generator-elimination.js, server/tournaments/generator-round-robin.js, server/tournaments/index.js, sim/side.ts, test/application/rooms.js, test/application/sockets.js, test/simulator/abilities/clearbody.js, test/simulator/misc/choice-parser.js, test/simulator/misc/decisions.js, test/simulator/misc/statusmoves.js
~This is a WIP, because it breaks a lot of things (specifically the `forEach`'s with multiple params), so I will need to test each one of them and fix accordingly.~
=> Change forEach to for...of

server/chat-plugins/info.js
https://www.smogon.com/forums/threads/3534365/page-81#post-7977912
~I'm not a big fan of the approach used here, but I didn't have any better ideas that worked.~
=> Info: Add /showpunishments command

config/formats.js
https://www.smogon.com/forums/threads/2v2-doubles.3606989/post-8063473
=> 2v2: Unban Mega Gengar

config/formats.js
... And remove it from the ladder
https://www.smogon.com/forums/threads/metronome-battles.3632075/post-8066280
=> Metronome Battles: Ban steel types

data/formats-data.js, data/mods/gen6/random-teams.js, data/random-teams.js
- Fix Guts Dynamic Punch Machamp.
- Mega Heracross with Protect doesn't need Guts in its base form.
- Give Kingler Liquidation for its Sheer Force.
=> Random Doubles Updates

data/mods/gen4/scripts.js, sim/battle.ts
=> Fix spread modifier for gen 4 FFA battles

data/formats-data.js
https://www.smogon.com/forums/threads/usum-pu-suspect-process-stage-5-5-voting.3648342/page-2#post-8071681
=> Move Houndoom to PUBL

config/formats.js
https://www.smogon.com/forums/threads/usum-m-m-landorus-therian-suspect-voting.3648321/page-2#post-8072356
=> Prevent Landorus-Therian from holding Mega Stones in M&M

data/formats-data.js, data/random-teams.js
- Rain Dance does not work well with Heliolisk; it prefers wallbreaker
roles instead.
- Mind Blown is not good if the Z-Crystal is already taken.
- Seviper learns Swords Dance in Gen 7.
=> Random Battle: Update Heliolisk, Blacephalon, Seviper

config/formats.js
it shouldnt be in it <https://www.smogon.com/forums/threads/1v1-old-gens.3646875/#post-8031456>
=> Remove Species Clause from Gen 6 1v1

data/random-teams.js
Without this, it's level 97 with 230 speed and over 300 in each attack stat...
=> Nerf Pikachu in randdubs

sim/battle.ts
=> Restore Cancel Button

data/scripts.js, test/simulator/misc/recoil.js, test/simulator/moves/mindblown.js
Fixes both Mind Blown and standard recoil moves.
=> Fix doubled recoil

config/formats.js, data/abilities.js, data/mods/gen1/moves.js, data/mods/gen3/abilities.js, data/mods/ssb/moves.js, data/mods/ssb/scripts.js, data/mods/ssb/statuses.js, data/moves.js, data/rulesets.js, data/scripts.js, sim/battle.ts, sim/pokemon.ts, test/simulator/misc/decisions.js
- Implements ``Pokemon#nearbyAllies()``, ``Pokemon#nearbyFoes()``
- Implements ``Battle#getAllPokemon()``, ``Battle#getAllActive()``
- Refactors accordingly
=> Sim: Improve querying Pokémon

config/formats.js
https://www.smogon.com/forums/threads/usum-1v1-jirachi-retest-voting.3648617/#post-8079383
=> Remove 1v1 suspect notice

LICENSE
4a67a1f38a9ff15444c85c21f11d1f15dedcfec1 didn't seem to fix it, I tested this on my fork and it seemed to work.
=> Fix LICENSE.md

data/mods/gen6/random-teams.js, data/random-teams.js
Without Earth Power, there isn't anything Probopass can actually do to hurt the Steels that it traps, so it might as well get Sturdy in those situations.
=> Reject Magnet Pull on non-Earth Power Probopass

data/moves.js, test/simulator/moves/gearup.js, test/simulator/moves/magneticflux.js
=> Fix Gear Up and Magnetic Flux

package.json, server/sockets.js
```
TypeError: Cannot read property '_session' of undefined
at TLSSocket.wsOnTimeout (/home/ps/showdown/server/sockets.js:676:14)
at Object.onceWrapper (events.js:273:13)
at TLSSocket.emit (events.js:187:15)
at TLSSocket.EventEmitter.emit (domain.js:441:20)
at TLSSocket.Socket._onTimeout (net.js:453:8)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)
```
@Slayer95 FYI
=> Revert "Sockets: Refactor event handlers" instead of sockjs.

sim/examples/random-player-ai.ts
=> Handle targeting adjacentFoe and adjacentAllyOrSelf in RandomPlayerAI

data/abilities.js, data/items.js, data/mods/gen1/moves.js, data/mods/gen1/statuses.js, data/mods/gen2/statuses.js, data/mods/gen3/moves.js, data/mods/gen3/statuses.js, data/mods/gen4/statuses.js, data/mods/gen5/statuses.js, data/mods/gen6/statuses.js, data/mods/gennext/abilities.js, data/mods/gennext/moves.js, data/mods/gennext/statuses.js, data/mods/ssb/abilities.js, data/mods/ssb/moves.js, data/mods/ssb/statuses.js, data/mods/stadium/moves.js, data/mods/stadium/statuses.js, data/moves.js, data/statuses.js, dev-tools/globals.ts, sim/dex-data.ts
- All event handlers typed
- BattleStatuses switched to PureEffectData
=> Stricter type definitions for dex data

data/scripts.js
Turned out that `reduce` was important! Sorry for not trusting you, past me!
=> Don't display "But it failed!" on a success

data/factory-sets.json
Prevents fully Physical Marshadow from getting a Mixed Nature
=> BF: Update Marshadow

server/chat-plugins/datasearch.js
I felt that something like this would be useful
=> Add Sort Parameter to Dexsearch

data/formats-data.js
https://www.smogon.com/forums/threads/usum-lc-trapinch-suspect-voting.3648825/post-8086522
=> Ban Trapinch from LC

data/scripts.js, test/simulator/moves/trumpcard.js
=> Fix crash from Gen 4 Custap Berry + Trump Card interaction

data/mods/gen4/random-teams.js
https://lgtm.com/projects/g/Zarel/Pokemon-Showdown/alerts?mode=list
=> Fix LGTM alert in data/mods/gen4/random-teams.js

data/abilities.js, data/items.js, data/mods/gen1/scripts.js, data/mods/gen2/scripts.js, data/mods/gen4/abilities.js, data/mods/gen4/items.js, data/mods/gen4/moves.js, data/mods/gen4/scripts.js, data/mods/gen5/moves.js, data/mods/gennext/abilities.js, data/mods/ssb/moves.js, data/mods/ssb/statuses.js, data/mods/stadium/scripts.js, data/moves.js, data/scripts.js, data/statuses.js, dev-tools/global.d.ts, dev-tools/globals.ts, sim/battle.ts, sim/dex-data.ts, sim/dex.ts, test/simulator/abilities/battlearmor.js, test/simulator/abilities/disguise.js, test/simulator/abilities/shellarmor.js, test/simulator/items/weaknesspolicy.js, test/simulator/moves/clangoroussoulblaze.js
Such a simple title for such a massive change...
=> Fix Weakness Policy and Clangorous Soulblaze in doubles

data/mods/gen3/random-teams.js, package.json
It does not get Super Luck in this generation, so it should always get
Serene Grace, but it keeps getting rejected.
=> Random Battle Gen 3 and 4: Fix Togetic

server/chat-plugins/info.js, server/punishments.js
This commit fixes/changes: 
- Fixes alts always having `undefined`
- Sorts expireTime to ascending order
- Moves some code to server/punishments.js
- Uses table instead of `<p>`
- Handles errors more correctly
(I had a local git branch that I commited when I did each fix/change with a proper description for ease of reviewning but my laptop froze and it got corrupted)
=> Improve /sp

server/chat.js, server/users.js
I'm not pushing this directly because it's not hotpatchable. So... PR it is.
=> Support multiline commands in PM

server/chat-plugins/helptickets.js
I just noticed that the link is not up to date. On the room help is another link, so I replaced it.
=> Helptickets: Fix Request a password reset

data/factory-sets.json
OU: https://pastebin.com/4X5VRnzN
UU: https://pastebin.com/E3ApHPKu
NU: https://pastebin.com/nNmgAV6t
=> Update Battle Factory OU, UU, and NU

server/chat-plugins/scavengers.js
=> Scavs: Fix reset message

data/formats-data.js, data/mods/gen6/formats-data.js
Removing Brave Bird prevents Banded sets.
=> Random Battle: Update Mandibuzz

server/chat-plugins/datasearch.js
=> Movesearch: Add ability to search for moves in more than one Pokemon's learnset

config/config-example.js
https://github.com/Zarel/Pokemon-Showdown/pull/5456#discussion_r277133266
=> Synchronize config-example with Main's config

server/chat-commands.js, server/chat.js
Reported here: https://www.smogon.com/forums/posts/8114587
=> Fix bug in /msg

config/formats.js, data/abilities.js, data/mods/gen1/scripts.js, data/mods/stadium/scripts.js, server/chat-commands.js, sim/battle.ts, sim/field.ts, sim/globals.ts, sim/pokemon.ts, sim/side.ts, sim/state.ts, sim/tools/exhaustive-runner.ts, sim/tools/runner.ts, test/sim/misc/state.js, tools/simulate.js
Allow for serializing and deserializing simulator state.
Fixes #5270.
=> Battle toJSON/fromJSON

config/formats.js
[15:18:44] dom: can some1 ban perish song from gen5 1v1 i lead that tier thanks
=> [Gen 5] 1v1: Ban Perish Song

server/chat-commands.js
Relevant when hidetexting yourself
=> Stop hidetext hiding the log message

server/chat-plugins/info.js, sim/dex.ts
This fixes the weakness regression that was discussed in the dev room on PS.
=> Chat-Plugins: Fix regression in weakness command

data/mods/gen1/moves.js, data/mods/gen1/statuses.js, data/mods/gen2/moves.js, data/mods/gen2/statuses.js, data/mods/gen3/statuses.js, data/mods/gen4/statuses.js, data/mods/ssb/moves.js, data/mods/stadium/moves.js, data/mods/stadium/statuses.js, data/moves.js, data/statuses.js
=> Only add the '-status slp' message in statuses

data/moves.js, sim/battle.ts, test/sim/misc/fusion-combo.js
This should fix https://github.com/Zarel/Pokemon-Showdown/projects/3#card-18662639
=> Fix Fusion Bolt and Fusion Flare's interaction with each other

server/chat-plugins/scavengers.js
- Add "unrated" hunts to queue system
- fix /forcestarthunt, an add an unrated option for this.
- allow /viewhunt to show the current question while leaving the unknown answer blank
I plan to soon do typescripting with scav stuff so it's like the other chat-plugins
<sub>I swear I am a good neko!!!</sub>
=> Scavengers: Viewhunt/Queue improvements/fixes

server/chat-plugins/room-events.js
This was on the "More common suggestions" in the [suggestions thread](https://www.smogon.com/forums/threads/3534365/).
=> Improve roomevents

server/users.js
Fixes a bug which was mentioned in the Smogon bug thread. I'm Annika0 on PS btw.
=> Fix quotation marks when a username is already in use

server/room-game.js
As used in `room-battle#leaveGame`
=> Fix a potential user game state desync

server/chat-plugins/info.js
=> Info.js: Randbats calculator typo fix

sim/side.ts
Context: https://www.smogon.com/forums/threads/return-frustration-base-power-tooltip.3650730/
=> Include base power in |request| side data for Frustration/Return

data/mods/gen2/moves.js
Fixes tooltips showing too many turns asleep in gen 2.
=> Send rest message in gen 2

server/chat-commands.js, server/rooms.js
https://www.smogon.com/forums/posts/8138951
https://www.smogon.com/forums/posts/8155622
=> Slightly improve groupchats

config/formats.js
Due to popular demand, this brings back Metronome Battles on the ladder, but it'll be unranked
https://www.smogon.com/forums/threads/metronome-battles.3632075/post-8161250
=> Make Metronome Battles playable on the ladder

server/chat-plugins/info.js
link was still to the old thread.
=> Update link in !suggestions

server/chat-commands.js, server/room-battle.js, server/room-game.js
I wanted to also add tests for this since this is the 3rd/4th time I've fixed input logs, though I'm having issues with sockets crashing in the tests and haven't been able to find morfent to talk with them about whats going on. I'll add tests in a different commit, but I don't want to delay the fix any longer for tests.
=> Fix input logs

config/formats.js, server/chat-plugins/othermetas.js
@TheImmortal 
I think this would be useful.
=> Update Nature Swap

server/chat-commands.js
This won't catch everything that namefilter does, but I think it's /close enough/ to work
=> Check for obvious invalid statuses

PROTOCOL.md, server/tournaments/index.js
Client: Zarel/Pokemon-Showdown-Client#1315
=> Include player count in |tournament|start and /tour getusers

server/chat.js
Add more domain extensions to help filter more off-site links in chat, usernames, and especially statuses.
=> Update Domain Blacklist

server/chat-commands.js
I did this command about 3 times thinking the server was lagging, but instead it wasn't sending a response.
=> Back: Return an error message if user is back

server/chat-commands.js, server/ladders-local.ts, server/ladders-remote.ts
**Context:** Zarel/Pokemon-Showdown-Client#1326
=> Add support to local /laddertop for restricting by user prefix

server/chat-plugins/datasearch.js
The help text is becoming rather unwieldy. Maybe we should eventually put it in sections or something.
=> Support ohko flag in movesearch, update helptext

CONTRIBUTING.md
Adding these since they came up in the dev room, but aren't documented.
=> Update CONTRIBUTING.md with rules about Const Enums and Default Properties

data/moves.js
Fixes https://github.com/Zarel/Pokemon-Showdown/projects/3#card-23723574
=> Moves: Fix Psych Up's interaction with Focus Energy and Laser Focus

data/mods/gen2/formats-data.js
https://www.smogon.com/forums/threads/gsc-ou-tiering-changes.3652655/
=> GSC OU: Jynx/Golem are OU, Porygon2/Jolteon are UUBL

data/abilities.js
Fixes https://github.com/Zarel/Pokemon-Showdown/projects/3#card-24204996
=> Fix Poison Touch interaction with self-targeting contact moves

data/abilities.js, test/sim/abilities/flowerveil.js
Fixes https://github.com/Zarel/Pokemon-Showdown/projects/3#card-24205020
Unit test included.
=> Moves: Fix Flower Veil + Yawn interaction when ally is already under effect of Yawn

data/items.js, sim/dex-data.ts, sim/globals.ts
**Context:** https://github.com/Zarel/Pokemon-Showdown-Client/pull/1335
=> Add isPokeball field to Items data

server/chat-commands.js
This adds /shrug, /tableflip, and /tableunflip.
=> Add a few kaomoji commands

config/formats.js, data/formats-data.js
https://www.smogon.com/forums/threads/usum-uu-suspect-process-stage-10-4-voting.3652762/page-3#post-8192909
=> UU: Allow Mimikyu

server/rooms.js
(Client PR: Zarel/Pokemon-Showdown-Client#1342)
Suggested and apporved here: https://www.smogon.com/forums/threads/3653073/
=> Allow filtering by userid prefix in battle search

data/scripts.js, test/sim/misc/pledgemoves.js
I believe this fixes https://github.com/Zarel/Pokemon-Showdown/projects/3#card-24204988.
I added a test for this, but there are probably better ways to check what I was checking. If so, let me know and I can fix them up.
=> Fix Encore + Pledge moves interaction

server/chat-plugins/hangman.js, server/chat-plugins/poll.js
re: this approved suggestion. 
https://www.smogon.com/forums/threads/let-users-see-who-made-a-poll-or-hangman.3652444/
=> Let users see who made a hangman/poll

server/chat-plugins/blackjack.js, server/chat-plugins/roomsettings.js, server/rooms.js
This is a WIP. ~~[DO NOT MERGE YET]~~
[Card images](https://my.mixtape.moe/gvwxld.tar.gz) (NOTE: Card images have been released into [public domain](https://en.wikipedia.org/wiki/Public_domain).) [OUTDATED - Will give updated files soon]
This is pretty much ready for code review. (Jul 26, 2019)
ROUGH PREVIEW OF GAMEPLAY:
(ignore the cards changing color; that's a graphical issue on my end >_<)
=> Implement blackjack game

server/chat-commands.js, server/room-battle.js
Also use that new property in `/offertie`.
=> Track turns in RoomBattle

server/tournaments/index.js
Previously players were able to join battles as soon as they ended
=> Tournaments: always enforce scouting setting

server/users.ts
As far as I can tell this isn't intended behaviour.
=> Set prevUsers properly when merging

server/room-battle.ts
Approved by @Zarel in https://github.com/Zarel/Pokemon-Showdown/pull/5456#discussion_r312765366 and needed for #5456.
=> Don't clear player.userid upon unlinking

lib/fs.ts, server/chat-commands.js, server/chat.ts, server/global.d.ts, server/index.js, server/monitor.ts, server/rooms.js, sim/global.d.ts
/forcehotpatch can be used to perform the hotpatch regardless.
=> Make /hotpatch fail if git history hasn't changed

server/chat-formatter.ts, server/room-battle.ts, server/room-game.ts, server/users.ts
(This makes IntelliSense show the JSDoc comment.)
=> Move JSDoc comments from assignment to declaration

server/chat-plugins/info.js
This splits the "What are the rules for each format? What is 'Sleep Clause'?" part of /intro into two questions, both with updated links.
=> Updated /intro

server/chat-commands.js, server/room-battle.ts
This refactor changes:
- Allows multiple people to extract input logs
- Scales beyond 2 players
=> Refactor /(allow)exportinput log

server/ladders.ts
**Context:** https://www.smogon.com/forums/threads/fixing-simultaneous-challenges.3653287/
I don't think this precludes us from *also* improving the UI, but defense in depth is never a bad thing.
```
[09:51] Zarel: we might also want to think more about this, to see if we can think of better solutions
[09:51] Zarel: simultaneously displaying a challenge box and a being-challenged screen would help
[09:52] Zarel: so when you saw you were being challenged, you would stop challenging your opponent
```
=> Auto-accept challenges from challenge target

data/formats-data.js, data/learnsets.js
Being distributed as of today. Notable change is that it now has access to Celebrate.
https://www.pokemon.com/us/play-pokemon/worlds/2019/pokemon-distribution/
=> Add Aerodactyl Event

server/chat-plugins/helptickets.js
They look a bit too cluttered when they wrap into more than one line IMO.
=> Add margin in helptickets

server/chat-plugins/info.js
credits to snaquaza / smii for finding this
=> Fix URL for snatch and mirror dex lists

server/chat-plugins/datasearch.js, server/chat-plugins/info.js
Added mirror flag to movesearch to match snatch, as well as updating the help for the command to reflect the addition.
=> Added mirror flag to movesearch.

server/chat-plugins/helptickets.js
This reverts commit f128b74276b0bc85e0e18548407ecedcc63d93b2.
(Some people absoultley abhor this change.)
=> Revert "Add margin in helptickets (#5713)"

server/chat-commands.js
seemed to be a solution that at least a few people liked
=> Improve hidetext permissions

server/punishments.ts
turns out everything I said about the type of the userid in a punishment was wrong
=> Fix indirect punishments

server/chat-commands.js, server/chat-plugins/lottery.ts, server/chat.ts, server/global.d.ts, tsconfig.json
This is mostly just a test for typescripting a chat plugin.
=> Typescript lottery

server/chat-plugins/info.js
(Thanks to @DaWoblefet for the report)
=> /showpunishments: Fix sorting

server/sockets.js
See https://github.com/Zarel/Pokemon-Showdown-Client/pull/1358
=> Update the server WRT client connection timeouts

server/sockets.js
See https://github.com/Zarel/Pokemon-Showdown-Client/pull/1360
=> Update the server WRT SockJS desktop client fix

server/chat-plugins/lottery.ts
- Anyone can see the amount of participants
- Max winners can't go above `Number.MAX_SAFE_INTEGER`
- Max winners is added in modlog
- `/lottery edit <max winners>, <name>, <markup>` can be used to edit the markup
- `/lottery edit` shows the current configuration of the lottery
- "Page unavailable" is not shown to guest users, instead the not "allowing guests to join" logic is done in `/lottery join`.
=> Improve Lottery

server/chat-plugins/helptickets.js, server/chat-plugins/lottery.ts, server/chat-plugins/room-faqs.js, server/global.d.ts, server/punishments.ts, server/room-game.ts, server/rooms.ts, server/sockets.js, server/tournaments/index.ts, server/users.ts
Next: Rename `Room#id` -> `Room#roomid` and `User#userid` -> `User#id`.
=> Add a RoomID type

data/mods/gen1/scripts.js
=> Fix typo in Gen 1 accuracy hint

server/chat-commands.js
Fixed a missing space in clearstatus modlogging and added quotes around the bad status.
=> Clearstatus Modlog Fixes

server/chat-plugins/info.js
[19:27:18] &Anubis: It would be cool if the IPs in /alts were clickable too.
[19:28:44] &Anubis: like what help tickets use
[19:28:51] @ Mitsuki: it would be great
[19:33:43] &asgdf: maybe something smaller, like a [info]
=> Add IP lookup link to /alts

server/chat-commands.js, server/chat-plugins/chat-monitor.js, server/chat.ts, server/users.ts
Track how many times a name has been forcerenamed, note differently for offline warns and forcerenames
=> Improve username punishments

server/chat-commands.js
Allow subrooms of public rooms to have subrooms, allow making a room with subroomgroupchats private
=> Improve subroom checks

server/chat-commands.js, server/chat.ts
as per https://www.smogon.com/forums/threads/allow-users-to-set-modchat-for-their-pms.3654393/
=> Support blockPMs ac / trusted

server/users.ts
=> Show an access denied for modjoined battle rooms

server/chat-plugins/mafia.js
This adds a list of dead players along with their roles (if role reveal is on).
=> Mafia Dead List

data/mods/ssb/random-teams.js
=> SSB: Akasianse is a girl

config/formats.js
English PGL was wrong again...
=> Fix BSS17 banlist

data/mods/ssb/moves.js, data/mods/ssb/statuses.js
Lava Terrain leaks Illusion; this fix shows the Illusion mon's name if it's in effect.
=> Fix multiple places in SSB leaking Illusion

server/chat-plugins/roomsettings.js
Correct spelling not succesful
=> Fix typo in banwords reply

server/users.ts
=> Properly give trusted users a 100ms throttle

lib/fs.ts, server/chat.ts, server/monitor.ts, server/punishments.ts, server/room-battle.ts, server/roomlogs.ts, server/rooms.ts, server/tournaments/index.ts, server/users.ts, tslint.json
We obviously don't care about floating promises if we're disabling them.
The server checks checks for `unhandledRejection`s anyway.
=> Use void in promises to appease TSLint

server/chat-plugins/chat-monitor.js
=> Add battle filter and evasion detection to chat monitor

server/chat-plugins/chat-monitor.js, server/chat-plugins/helptickets.js, server/chat.ts, server/monitor.ts, server/punishments.ts, server/rooms.ts, server/users.ts
Now that we have typescript's `!` in most places, I much prefer using that to asserting `getRoom`'s return value
=> Rooms: Rooms.get can return null

server/chat.ts
Typescript scares me, I hope I didn't do anything bad
=> Trim all command arguments

data/abilities.js, data/mods/gen6/abilities.js
https://www.smogon.com/forums/threads/add-a-full-ability-description-for-contrary.3652011/
@Marty-D , if you want add something or change, say it.
https://bulbapedia.bulbagarden.net/wiki/Contrary_(Ability)
=> Add a full ability description for Contrary + Simple

data/mods/ssb/statuses.js
bad puns make the world go round
=> SSB: Update Rory's quotes

data/mods/ssb/abilities.js
QC wants to buff Fat Rain to give 2x Defense boost in rain.
=> SSB: Buff ptoad

data/mods/ssb/moves.js, data/mods/ssb/random-teams.js
QC wants to change Wish to Recover.
Iyarito wants to change the name of her signature move from "Vibora" to "Rosa Rosa".
=> SSB: Buff Iyarito, rename signature move

server/chat-plugins/modlog.js
As per the suggestion at https://www.smogon.com/forums/threads/add-pl-as-an-alias-for-punishlog.3655323/
=> Add /pl as an alias to /punishlog

sim/pokemon.ts
The changes in PR #5765 make this trivial; I just forgot to make the change at the time. Sorry for the oversight.
https://www.smogon.com/forums/posts/8096570
=> Transform should copy the target's current weight

data/mods/gen1/moves.js, data/mods/gen1/scripts.js, data/mods/gen2/moves.js, data/mods/gen2/scripts.js, data/mods/gen3/scripts.js, data/mods/gen4/scripts.js, data/mods/gen5/moves.js, data/moves.js, data/scripts.js, sim/battle.ts, sim/globals.ts
It's a check for semi-invulnerability rather than any sort of immunity.
=> Rename TryImmunity to TryInvulnerability

server/chat-plugins/chat-monitor.js, server/chat.ts
Performance shouldn't be affected too much by this change, especially since there's a lot of overhead being removed too (creating regexes on the fly, amongst others).
=> Refactor filters to always use regex

data/mods/ssb/moves.js, data/mods/ssb/random-teams.js, data/mods/ssb/statuses.js
QC agrees to change nature from Timid to Serious and Focus Blast to HP Fighting to give other mons in the format a chance to take down Sundar.
=> SSB: Nerf Sundar

data/mods/ssb/abilities.js
Should have fixed the descs to say 2x when I fixed the move.
=> SSB: Correct Fat Rain descriptions

server/chat-plugins/room-events.js
Lack of consistency was bothering me
=> Make /events view visually match /events

server/chat-plugins/scavengers.js
Checked with Meicoo and sparklychild.
=> Add /scav addhint to help

server/chat-plugins/datasearch.js
=> Fix movesearch bug with lowers

data/mods/gen5/moves.js, data/moves.js, data/scripts.js
Also optionally centralise the check for Helping Hand.
=> Centralise semi-invulnerability checks for Poison type using Toxic in Gen6+

server/chat-plugins/room-faqs.js
It's annoying and floody having the source come up for roomfaqs every time if you're a mod.
wtb better command name
=> Allow viewing roomfaqs without showing source

data/items.js
Sorry  I didn't get to this beforehand, but I was able to finish this now, but there is now some sort of short description that should work for this!
=> Add Fossils

data/formats-data.js
It goes without saying that Coalossal is not Boltund and thus should not have its random battle moveset. Tentative set.
=> Random Battle: Update Coalossal

data/abilities.js
Some of these are really bad, particularly Gulp Missile, but I didn't know how to condense it properly
=> Add shortDesc to abilities

data/formats-data.js, data/mods/gen7/formats-data.js
continuation of #5978 because that pokemon snuck under my radar when fixing it originally.
=> Disallow vivillon formes in gen 8

data/moves.js
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8285488
=> Make Pyro Ball viable

data/abilities.js
=> Make Libero descriptions match Protean

data/pokedex.js
Should be 30 instead of 35 according to https://pastebin.com/Cyg8Rp53
Thanks to Rhydonphilip for pointing this out.
=> Fix Corsola-G's Speed

server/room-game.ts, server/users.ts
TypeScript will now recognizes these functions existence so
we don't have to supress the compiler whenever they come up.
=> RoomGame: Uncomment optional functions

data/moves.js
Add the dance flag to Clangorous Soul according to the info sheet
=> Add dance flag to Clangorous Soul

data/moves.js
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8287014
=> Fix Dragon Darts interaction in Doubles

server/chat-plugins/wifi.js
=> Update Wi-Fi GA message for Gen 8

config/formats.js
=> Fix gen 8 LC and Mono mod

data/moves.js
I also fixed G-Max Resonance setting Aurora Veil on the opposing side.
=> Fix Max moves' interaction with non-dynamaxed Pokemon

config/formats.js
Ask Quote if you don't believe me
=> Moody is allowed in gen81v1

config/formats.js
Council voted on these, announcement by TL was made in discord, smogon post will follow later but I wanted to get these on PS before we got the ladder released
=> NFE: Banlist update

data/abilities.js, data/mods/gen7/abilities.js
Added Speed boost due to Rattled being hit by Intimidate (source: https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8285401).
Edited desc and shortDesc of Rattled to include new interaction.
=> Update Intimidate Interactions

data/mods/gen7/pokedex.js, data/pokedex.js
Source: https://gamewith.net/pokemon-swordshield/article/show/13884
=> Update Egg Groups (Trapinch, Ralts lines)

data/formats-data.js
merge with @TheRealQuote's PR please
=> Fix the tier of Corsola-Galar, Gothita, Sneasel, and Swirlix

config/formats.js
=> Ban Corsola-Galar from Gen 8 LC

data/moves.js
Source: https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/page-15#post-8288361
=> Make G-Max Steel Surge hazards removable

config/formats.js
=> Add Gen 8 CAP

data/moves.js
Source: https://bulbapedia.bulbagarden.net/wiki/Eternabeam_(move)
=> Eternabeam is one word

server/chat-commands/info.js
Also added a Max Move flag, like Z-moves currently have.
=> Display User for GMax moves

server/index.js, server/ladders-local.ts, server/ladders-remote.ts, server/rooms.ts, server/sockets.js
Update the extensions of a bunch of files that were migated to typescript in comments
=> Fix file extensions in comments

data/moves.js
Reported somewhere, but I forget where, sorry...
=> G-Max Snooze shouldn't affect already statused foes

data/rulesets.js
Not sure if this is the best way to do this so PRed.
=> Most past gen items should still be illegal

data/items.js
Description reflects that it can evolve Galarian Darumaka into Galarian Darmanitan
=> Fix Ice Stone description

data/moves.js
Fixes Octolock not activating Defiant, Simple, Mirror Armor, Contrary, Competitive, Clear Body, Big Pecks
Defiant: https://vimeo.com/375255848
Big Pecks: https://vimeo.com/375262242
Will update when I get sources for others.
=> Fix Octolock not activating certain abilities

data/abilities.js
Make Gulp Missile actually explain what it does. This implementation is a bit wordy, though.
=> Explain Gulp Missile

data/moves.js
Source:
https://pokemondb.net/move/steel-beam
https://pokemon.fandom.com/wiki/Steel_Beam
https://www.serebii.net/attackdex-swsh/steelbeam.shtml
=> Steel Beam hits one adjacent Pokemon

data/mods/ssb/scripts.js, data/scripts.js
Other note: should `Game Boy` for gen 2 should specifically be Game Boy Color?
=> Change the current Game Console

server/chat-plugins/datasearch.js
- Allow searching for max and gmax moves
- Allow searching for protection moves
=> Some Movesearch Changes

translations/french.json
Removing a typo & rewording a sentence to make sense.
=> Update French translation

data/abilities.js
Fixes https://github.com/smogon/pokemon-showdown/issues/6083
=> Fix Disguise HP loss from 1/10 to 1/8

CONTRIBUTING.md, PROTOCOL.md, README.md, data/mods/gennext/README.md, data/mods/ssb/abilities.js, data/mods/ssb/moves.js, lib/repl.ts, package.json, server/chat-commands/info.js, sim/README.md, sim/prng.ts, tools/set-import/index.js, tools/set-import/sets/README.md
Obviously had to write a script for this
=> Update Repo Links

server/chat-plugins/datasearch.js
=> Dexsearch: Allow searching for some formes

data/mods/gen7/formats-data.js, server/chat-plugins/datasearch.js
And add descriptions for new parameters
=> Dexsearch: Allow searching national dex

server/chat-commands/info.js
Alternatively, I can make it display `` Weight: 0 kg`` over `` Weight: 0 kg (20 BP)``.
=> Don't display Weight for GMax Pokemon

data/abilities.js, data/items.js, data/moves.js, data/statuses.js
=> Add Utility Umbrella

data/mods/gen7/moves.js, data/moves.js
https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/page-29#post-8298814
also allows gmax steelsurge to be removed on both sides. Sorry >.>
=> Defog now removes terrains and G-Max Steelsurge

config/formats.js
As per https://www.smogon.com/forums/threads/national-dex-ou-metagame-discussion.3656899/.
=> Natdex: Power Construct is banned

data/formats-data.js
=> Add 'Past' values for `isUnreleased` and `unreleasedHidden`

data/pokedex.js, sim/dex-data.ts, sim/global-types.ts, sim/team-validator.ts
Sorry this took longer than expected
also Necrozma-U's learnset inheritance is technically not correct right now but for validation purposes that's not overly important since you cant validate a team with a necrozma-u selected
=> Add inheritsLearnsetFrom property

data/formats-data.js
https://serebii.net/swordshield/wildareaevents.shtml
=> Snorlax-GMax Released

server/chat-plugins/datasearch.js
Forgive for commit name, apparently, i shouldn't have started with a "/".
=> /nds: Fix Moves

data/moves.js
Thanks to Anubis for confirming: https://www.smogon.com/forums/posts/8303447
- GMax Centiferno applies Fire Spin
- GMax Sandblast applies Sand Tomb behind Substitute
- GMax Sweetness cures despite Substitute or Sap Sipper
=> Improve GMax Centiferno, GMax Sandblast and GMax Sweetness

server/chat-plugins/datasearch.js
=> NDS: Don't allow Pokestar and such

config/formats.js
Is it possible to get this in the server since there are still other Gen7 metas? 
FYI I did test locally.
=> Add Gen 7 Hackmons Cup

config/formats.js, data/formats-data.js
https://www.smogon.com/forums/threads/cherubi-has-been-banned-from-gen-8-little-cup.3657592/
Hopefully i did this right ^^'
=> Gen 8 LC: ban Cherubi

data/abilities.js
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8299187
The shortDesc was kind of misleading with the "Restored in hail" part, but I am not sure what to change to make it more clear when it actually restores.
=> Ice Face restores on switch-in when hail is active

server/chat-plugins/room-events.js
Added bots to the Requires part of the help message
Added Requires to /roomevents start
=> Fix roomevents help messages

data/statuses.js
Despite accepting that his other reports were invalid the reporter here https://www.smogon.com/forums/posts/8312554 is defiant(!) about this one...
=> Gigantamax forme change is client-only

server/chat-commands/info.js
Currently fails on Pokemon and moves not included in gen 8
=> Include National Dex mons in veekun command

config/formats.js
https://www.smogon.com/forums/threads/sword-and-shield-tiering-announcements.3657492/#post-8315007
=> Monotype: Ban Moody

config/formats.js
https://www.smogon.com/forums/threads/sword-and-shield-tiering-announcements.3657492/#post-8315347
=> Monotype: Add Dynamax Clause

config/formats.js
https://www.smogon.com/forums/threads/lc-suspect-black-balloons.3658010/
=> LC and M&M: Add suspect notices

data/moves.js
I assume the values were misplaced.
~~This is 420Blazeitt now btw~~
=> Fix Sparkly Swirl data

config/formats.js
As per the Doubles OU council's decision: https://www.smogon.com/forums/threads/np-swsh-dou-stage-0-begin-again.3656244/post-8322659
=> Remove Gravnosis Clause from Gen 8 DOU

sim/tools/random-player-ai.ts
=> Fix RandomPlayerAI wrong teamsize assumption

data/formats-data.js
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/page-101#post-8322820
=> Mew is obtainable with 3 perfect IVs in SwSh

data/items.js
I forgot that these two items also have fractional priority. Sorry about that.
=> #6224 Followup for Full Incense and Lagging Tail

config/CUSTOM-RULES.md
Many of these are not very useful but I'm being thorough.
=> Complete the custom rules documentation

config/formats.js, data/formats-data.js
https://www.smogon.com/forums/threads/usage-based-tier-update-for-january-2020-ru-ready.3658469/
=> January usage-based tier changes

data/mods/ssb/abilities.js, data/mods/ssb/statuses.js
=> SSB: More bugfixes/updates

data/moves.js
In-game proof: https://www.youtube.com/watch?v=8EVTeRfY-0c (Thanks KennedyLFC)
=> Status moves bypass Obstruct

config/formats.js
https://www.smogon.com/forums/threads/nfe-metagame-discussion.3656332/page-2#post-8334055
=> NFE: Ban Mr. Mime Galar

data/mods/ssb/moves.js, sim/dex-data.ts, sim/global-types.ts
Also allowing the various move targets to be documented.
This found a bug in SSB!
=> Typescript move.target

data/formats-data.js
https://www.smogon.com/forums/threads/np-ss-uu-stage-1-here-comes-the-sun-crawdaunt-gengar-and-hawlucha-banned.3658529/page-2#post-8339339
=> UU: Update bans

server/chat-commands/admin.ts, server/global-types.ts, server/rooms.ts, server/users.ts
I tried dynamically generating the type but it turned out to be
too much of a headache, but it doesn't seem worth it to block on.
=> Add a GroupSymbol type

config/formats.js
https://www.smogon.com/forums/threads/metronome-battles.3632075/page-19#post-8342281
=> Metronome Battle: Ban Gorilla Tactics

config/formats.js
https://www.smogon.com/forums/threads/arena-trap-has-been-quickbanned-from-national-dex-ou.3659180/
=> National Dex: Ban Arena Trap

data/mods/gen1/rulesets.js, data/mods/gen2/rulesets.js, test/sim/misc/endlessbattleclause.js
Also add test for 1000 turn termination behavior.
=> Add EBC to Gens 1 and 2

config/formats.js
Apparently this was supposed to be added 3 weeks ago
https://www.smogon.com/forums/threads/1v1-old-gens.3646875/page-4#post-8329377
=> ADV 1v1: Add Sleep Moves Clause

config/formats.js
https://www.smogon.com/forums/threads/pure-hackmons.3656851/page-2#post-8347871
=> BH: Zacian-C and Zamazenta-C are hackable

server/chat-commands/moderation.js
Most notably, allow the commands to be used without needing the exact user to be online.
=> Refactor trustuser checks

test/server/users.js
=> Stop using `Rooms.lobby` in tests

config/formats.js
[8:23 PM] MajorBowman: hey when you get a chance can you make shaymin-sky legal in the xy doubles ou challenge format
[8:23 PM] Kris: was it just unbanned
[8:23 PM] MajorBowman: we're running a mini tournament with it legal as a pre-suspect but there's no xy doubles ubers format to challenge in
[8:24 PM] Kris: ic
[8:24 PM] MajorBowman: it's not starting for a week so no rush
[8:24 PM] Kris: is it ok if i do it now
[8:24 PM] MajorBowman: yeah that's fine
[8:25 PM] Kris: if it happens now itll be legal for an entire week
[8:25 PM] Kris: before the tour
[8:25 PM] Kris: so ppl can do some teambuild testing
[8:25 PM] MajorBowman: no one plays it outside our circuit tours so it's nbd
[8:25 PM] MajorBowman: yea that too
=> ORAS DOU: Unban Shaymin-Sky

config/formats.js
https://www.smogon.com/forums/threads/trademarked-leaders-choice.3656980/
i forgot to add it
=> Trademarked: Restrict Sleep Talk

config/formats.js
https://www.smogon.com/forums/threads/ss-1v1-mew-voting.3659689/#post-8358069
=> 1v1: Ban Mew

data/formats-data.js
dont merge until 7 PM EST on February 6
=> Release Gigantamax Toxtricity

config/formats.js
https://www.smogon.com/forums/threads/stabmons.3656429/page-2#post-8360304
=> STABmons: Restrict Extreme Speed

data/moves.js
https://github.com/Zarel/Pokemon-Showdown/projects/3#card-25870237
=> Fix keeberry activiating due to present healing

data/mods/letsgo/formats-data.js
https://www.smogon.com/stats/2019-11/gen7letsgoou-1630.txt
LGPE OU hasn't had its tiers updated on the server a long while, so here's the changes from the latest usage stats.
=> Update LGPE OU Tiers

data/mods/letsgo/formats-data.js
Done using LGPE OU 1630 stats from October 2019 (when the final tier shifts happened)
https://www.smogon.com/stats/2019-10/gen7letsgoou-1630.txt
=> Accurately update LGPE tiers

config/formats.js
Posts were re-arranged and links needed some shuffling
=> Fix 1v1 old gen links

data/mods/gen5/moves.js, data/moves.js, test/sim/moves/trickroom.js
The move documentation was accurate here, but the behavior was never actually implemented. So there's that.
=> Fix Gyro Ball/Electro Ball divide-by-0 edge cases

server/chat-commands/info.js
from https://www.smogon.com/forums/threads/shuffle-command.3660152/
=> Add /shuffle command 

server/chat-plugins/poll.ts
This makes polls store their options and require a separate submission step, and also adds a new type of poll for selecting any number of options.
A lot of the caching for the _italicized selected_ answer on the results screen has been removed, but in my testing the function's fast enough to have practically 0 impact.
=> Support polls allowing multiple responses

lib/fs.ts, server/chat-commands/room-settings.ts, server/room-game.ts, server/roomlogs.ts, server/rooms.ts, test/server/rooms.js
Client PR: smogon/pokemon-showdown-client#1447.
=> Support renaming rooms

config/formats.js
https://www.smogon.com/forums/threads/on-the-radar-arena-trap.3660066/#post-8373574
=> CAP: Ban Arena Trap

config/config-example.js, server/index.ts
This is called when the server is fully initialized and ready to serve requests. Useful for notifying a process manager.
=> Add Config.startuphook

data/formats-data.js
https://www.smogon.com/forums/threads/np-ss-uu-stage-1-here-comes-the-sun-diggersby-durant-weavile-banned.3658529/page-6#post-8374900
=> Move Diggersby, Durant, and Weavile to UUBL

server/chat-commands/room-settings.ts, server/roomlogs.ts, server/rooms.ts
Recreate the logs properly, fix aliases
Incidentally, should the rename command modlog, or log to the staff room?
=> Fix bugs with renaming rooms

config/formats.js
https://www.smogon.com/forums/threads/trademarked-leaders-choice.3656980/page-4#post-8376346
=> Trademarked: Ban Arena Trap

data/mods/gen5/random-teams.js
included everything i could think of, might've missed a couple edge cases of rejection tho
=> Gen 5 Rands Update pt 2

config/formats.js
https://www.smogon.com/forums/threads/lc-suspect-behind-the-veil.3660436/
=> LC: Add suspect notice

config/formats.js
https://www.smogon.com/forums/threads/balanced-hackmons.3656408/page-13#post-8378504
=> BH: Ban Octolock

config/formats.js
https://www.smogon.com/forums/threads/inheritance-om-of-the-month.3656811/#post-8379403
=> Inheritance: Update banlist

config/formats.js
https://www.smogon.com/forums/threads/np-ss-dou-stage-0-begin-again-beat-up-banned.3656244/page-9#post-8381535
=> Doubles OU: Ban Beat Up

config/formats.js
https://www.smogon.com/forums/threads/nfe-metagame-discussion.3656332/page-3#post-8381997
=> NFE: Ban Gurdurr, Rufflet, Sneasel

config/formats.js
https://www.smogon.com/forums/threads/scalemons-leaders-choice.3658482/page-2#post-8383281
=> Scalemons: Update bans

server/chat-plugins/room-events.ts
fixes bug of link targets not showing up in /event view for staff members
=> Escape HTML in events

config/formats.js, data/formats-data.js
https://www.smogon.com/forums/threads/ss-lc-vulpix-alola-voting.3660878/page-2#post-8385098
=> LC: Ban Vulpix-Alola

data/formats-data.js
https://www.smogon.com/forums/threads/np-nu-stage-1-criminal-see-post-10.3660646/#post-8385934
=> Move Kingler, Vikavolt, and Turtonator to NUBL

server/chat-plugins/random-battles.ts, sim/dex-data.ts
Im aware the randomSets are extremely counterintuitive, im going to work on that after this
=> Add Random Battles chat plugin

data/mods/gen2/formats-data.js, data/mods/gen2/random-teams.js, server/chat-plugins/random-battles.ts, sim/dex-data.ts, sim/global-types.ts
This also fixes a typo in random-battles.ts
=> Refactor [Gen 2] Random Battle

data/moves.js, test/sim/moves/gmaxvolcalith.js, test/sim/moves/gmaxwildfire.js
G-Max Volcalith should be using identical mechanics to G-Max Wildfire (deal 1/6 damage for 4 turns to non-Rock type opponents). I added tests for both as well.
=> Fix G-Max Volcalith and add tests for G-Max Wildfire/Volcalith

data/mods/gen2/formats-data.js, data/mods/gen2/random-teams.js, server/chat-plugins/random-battles.ts, sim/global-types.ts
Fixes oversight where Pokemon with no item were showing as `Species @ ` or `Species @ / Other Item`
Fix typos in help descriptions
Sort moves and items
Fix spelling of High Jump Kick
=> Fix various with about Random Battles chat plugin

config/formats.js
https://www.smogon.com/forums/threads/scalemons-leaders-choice.3658482/page-2#post-8388710
=> Scalemons: Ban Moody, Rain Dance, and Sunny Day

config/formats.js, data/rulesets.js
https://www.smogon.com/forums/threads/balanced-hackmons.3656408/page-14#post-8389927
https://www.smogon.com/forums/threads/ss-bh-suspect-test-2-giants.3661121/
=> BH: Add Forme Clause and suspect notice

config/formats.js
Extreme Speed! Single Battles!!
https://www.smogon.com/forums/threads/extreme-speed-single-battles.3661123/
=> Add new Online Competition

config/formats.js
https://www.smogon.com/forums/threads/2v2-doubles.3656321/page-7#post-8392997
=> Ban Melmetal from 2v2

server/ladders.ts, server/room-battle.ts, server/users.ts, sim/global-types.ts
https://www.smogon.com/forums/threads/improve-searching-for-concurrent-ladder-battles.3660989/
=> Remove restrictions on concurrent battle searches

server/chat-plugins/random-battles.ts
currently takes you to play.pokemonshowdown.com/dex.pokemonshowdown.com, which is obviously not right.
=> Fix formatting links for /randbats

config/formats.js
https://www.smogon.com/forums/threads/mix-and-mega-suspect-2-gengar.3661363/
=> Mix and Mega: Add suspect notice

config/formats.js
https://www.smogon.com/forums/threads/np-ss-dou-stage-1-when-i-grow-up-dynamax-suspect.3661422/
=> Doubles OU: Add suspect notice

config/formats.js
https://www.smogon.com/forums/threads/scalemons-leaders-choice.3658482/page-2#post-8398670
=> Scalemons: Update banlist

data/formats-data.js
https://www.smogon.com/forums/threads/np-nu-stage-1-criminal-see-post-10.3660646/#post-8398979
=> Move Scrafty to NUBL

data/mods/gen1/pokedex.js
=> Fix species -> name in Gen 1 Pokedex

config/formats.js
https://www.smogon.com/forums/threads/stabmons.3656429/page-2#post-8405292
=> STABmons: Restrict Electrify

config/formats.js
https://www.smogon.com/forums/threads/ss-ou-suspect-process-round-2-voting.3661865/page-5#post-8409851
=> OU: Ban Arena Trap

config/formats.js, data/formats-data.js
https://www.smogon.com/forums/threads/sword-and-shield-tiering-announcements.3657492/page-2#post-8410710
=> LC: Ban Cutiefly

server/chat-plugins/tcgtabletop.ts
i'm a bit concerned about the `search: any` specification on line 16 but that was the only way to fix a specific error (and two deriving from it)  - lmk if there's a better way to handle that.
Passes tests, though, but was advised against `any` unless there was nothing better (not sure if there is or not, since Object and AnyObject also disagree with it).
=> Typescript TCG & Tabletop's plugin

server/chat-plugins/scavengers.js
Oops, i missed a ``!``.  (return true means something happened in place of the original code)
=> Scavengers: fix point giving

config/formats.js
https://www.smogon.com/forums/threads/national-dex-suspect-3-just-like-water.3662033/
=> National Dex: Add suspect notice

data/formats-data.js
https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/#post-8413785
=> Silvally, Swoobat, Arctovish, and Arctozolt are PUBL

config/formats.js, sim/dex.ts
thanks to urkerab for helping me fix the crashes
=> Add Shared Power

config/formats.js
https://replay.pokemonshowdown.com/gen8sharedpower-1091182721
this battle only went to turn 9; skip to turn 8 to see the text log
=> Shared Power: Fix crashes and ban game-breaking abilities

config/formats.js
https://www.smogon.com/forums/threads/pacifistmons-leaders-choice.3658719/page-2#post-8416911
=> Pacifistmons: Update bans

config/formats.js, data/mods/gen6/formats-data.js
=> Shared Power and ORAS Doubles: Update bans

data/rulesets.js
This fix re-introduces Arceus plates.
=> Additional fix for NatDex validation

config/formats.js
https://www.smogon.com/forums/threads/smogon-happenings-post-here-for-publicity-yes-you.3520642/page-202#post-8419618
=> Doubles OU: Add Dynamax Clause

server/chat-plugins/scavenger-games.js, server/chat-plugins/scavengers.js
Add/update informational commands for scavengers
=> Scavengers: Information commands for twists

config/formats.js
The Immortal recommended I do it this way, since it's just two Hidden Abilities, rather than creating a mod for it.
=> Ban Hidden Abilities unreleased in VGC18

server/chat-commands/info.js
also change the link for /calc as per pre
=> info.js: Update the /randomscalc command

server/chat-commands/moderation.ts, server/global-types.ts, server/punishments.ts, server/rooms.ts, server/users.ts
Draft, due to an issue with eslint `no-unused-expressions`.
(ignore extra commits - had an issue with git)
=> Typescript chat-commands/moderation 

data/moves.js
Accidentally introduced by PR #6180.
=> Fix accuracy of Hurricane and Thunder against holder of Uility Umbrella

server/chat-plugins/scavenger-games.js, server/chat-plugins/scavengers.js
- Custom twists take precedence over official twists
- twists (mods) can be loaded into any game mode, except for unrated.
- More than one twist can be loaded in at a time. (priority is finally put to use to change the order the twist is run at)
- Update Perfect Score functionality
This has received Meicoo's seal of approval
Mergeをするお願いします！
=> Support (multiple) twists for all game modes

server/chat-commands/info.js
Per the approved suggestion at https://www.smogon.com/forums/threads/add-a-tutorial-for-room-tours-as-a-faq.3661536/.
=> Add /faq tournaments

data/formats-data.js
https://www.smogon.com/forums/threads/np-ru-stage-1-i-lost-something-in-the-hills-barraskewda-and-centiskorch-banned-see-post-71.3659533/page-3#post-8427541
=> Move Barraskewda and Centiskorch to RUBL

test/sim/abilities/emergencyexit.js, test/sim/abilities/pastelveil.js, test/sim/moves/fellstinger.js
Most of these are skipped. Source for Pastel Veil mechanics research: https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8426218
=> Add Pastel Veil, Emergency Exit, and Fell Stinger tests

data/abilities.js, test/sim/abilities/pastelveil.js
Makes Pastel Veil pass the tests from #6568
=> Fix Pastel Veil mechanics

data/formats-data.js
https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/#post-8428752
=> Move Noctowl, Silvally-Fire, and Silvally-Ground to PUBL

data/formats-data.js, data/rulesets.js
I also modified the in-battle description of Gravity Sleep Clause as per request of MajorBowman
=> Move Gmax formes to (DUber)

data/abilities.js, data/moves.js
See research:
https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8430587
=> Fix Neutralizing Gas + ability changing effects

test/sim/team-validator.js
Complements https://github.com/smogon/pokemon-showdown/commit/f194d31aacfcdd2edc33b95dd68738f84436c580
=> Add G-Max move validator illegality test

test/sim/moves/teattime.js
They all pass, hooray!
Some mechanics research thread posts (I can corroborate):
- https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8323241
- https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8305757
- https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8428783
=> Add Teatime tests

server/chat-plugins/mafia.ts
=> Mafia: Misc updates

config/formats.js
https://www.smogon.com/forums/threads/1v1-suspect-2-mimikyu.3662782/
=> 1v1: Add suspect notice

data/mods/ssb/statuses.js
=> SSB: Update several ranks

config/formats.js
https://www.smogon.com/forums/threads/national-dex-mega-blastoise-suspect-voting.3662763/page-3#post-8437163
=> National Dex: Ban Blastoise

server/chat-commands/info.js
Implementing the suggestion from [this smogon thread](https://www.smogon.com/forums/threads/add-a-gmax-move-in-dt-gmax-mon.3661114/).
=> Add G-Max Move to /details results

data/formats-data.ts, data/random-teams.ts
Thanks to PlatinumCheesecake, not a racist, cake, yellow paint, Kris, and everyone else who helped me out on this!
=> Gen 8 Random Doubles Update 

config/formats.js, data/formats-data.ts
https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/#post-8440324
=> PU: Ban Silvally-Flying, Drought, and Heat Rock

data/formats-data.ts
Confirmed by https://twitter.com/zakocky/status/1230710908130754560 and inquired by @Lusamine
=> Weezing's hidden ability is released

server/chat-plugins/blackjack.ts
Bug introduced in https://github.com/smogon/pokemon-showdown/commit/36d6dc8b0c93c9c4e10a55839b9cb7ab1aa856d6#diff-797aaa7fdf5beb7302351b8ad019da67
=> Blackjack: Do not require an autostart to create

config/formats.js
```
[21:50:14] %Akir: well, a while ago u said that u were willing to add in gen5 publ
[21:50:25] %Akir: i finally have a list for u if u wanted something to do lol
[21:50:41] %Kris: idk if ill be able to add it as a formal teambuilder banlist
[21:50:45] %Kris: but i will bann it
[21:50:47] %Kris: ban it
[21:50:51] %Kris: and sure
[21:50:53] %Kris: just link me the thread
[21:51:26] %Akir: well i have the mons that need to be pushed up if that makes it easier
[21:52:04] %Kris: sure
[21:52:26] %Akir: They are: Combusken, Rotom Frost, Vigoroth, and Riolu
[21:53:25] %Kris: ok cool
```
E: 
[22:05:19] %Akir: ah fuck and linoone
=> BW2 PU: Update banlist

data/mods/gen1/moves.ts
Bulbapedia seems to suggest this is the case
=> Give Struggle 10 PP in Gen 1

sim/team-validator.ts, test/sim/team-validator.js
Pointed out by FOMG in https://www.smogon.com/forums/threads/gen-2-ps-development-post-bugs-here.3524926/post-8439815
=> Validate that SpA and SpD EVs match in Gen 2

server/chat-commands/info.js
>Zarel Yesterday at 10:01 PM
I think that makes sense
sure, PR that
=> Mention TypeScript in /git

data/formats-data.ts
https://www.smogon.com/forums/threads/np-ss-uu-stage-3-as-the-world-falls-down-mamoswine-banned.3661513/page-5#post-8445057
=> Move Venusaur to UUBL

config/formats.js
https://www.smogon.com/forums/threads/ss-bh-suspect-test-3-break-free.3663202/
=> Add Balanced Hackmons suspect notice

translations/portuguese.json
I fixed a mistake and made some changes so it's consistent. Hopefully I'm doing this right
=> Change the Portuguese translation for groups

config/formats.js, sim/dex.ts
=> Add May 2020 OMotM and RoA Spotlight

sim/pokemon.ts
Basically the same as Psych Up, from where I copied the code.
=> Gen6+ Transform should also remove Focus Energy if necessary

server/chat.ts
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/page-128#post-8451861
=> escapeHTML when notifications blocked

server/chat-plugins/scavenger-games.js, server/chat-plugins/scavengers.js
_Nyuuu_ game mode (last of the game modes for May!)
This is approved by Meicoo-sama!  よろしくお願いし _”にゃ”_ す！
=> Scavengers: Add Jump Start

server/chat-plugins/wifi.ts
Gmax and Galarian/Alolan sprites were broken after recent changes.  Thanks for the help, @scheibo!
=> Fix sprite formes for Wi-Fi lotto giveaways

config/formats.js
https://www.smogon.com/forums/threads/flipped-leaders-choice.3662020/page-2#post-8450612
=> Flipped: Ban Psychic Surge and Psychic Terrain

data/formats-data.ts
https://www.smogon.com/forums/threads/np-nu-stage-1-criminal-see-post-10.3660646/page-2#post-8453880
=> Move Linoone to NUBL

config/formats.js
https://www.smogon.com/forums/threads/ss-1v1-mimikyu-voting.3663532/page-2#post-8453747
=> 1v1: Ban Mimikyu

data/mods/gen4/moves.ts
Complements https://github.com/smogon/pokemon-showdown/commit/e20a71206e46f581e54e5b65db6d1065b0a722c9.
=> Update Struggle's Gen 4 description

config/formats.js
https://www.smogon.com/forums/threads/national-dex-suspect-4-dirty-computer-mega-metagross.3663780/
=> Add National Dex suspect notice

data/mods/gen6/pokedex.ts, data/pokedex.ts, sim/dex-data.ts, sim/global-types.ts, test/sim/data.js, test/sim/dex.js
Numbers obtained from kwsch/PKHeX's FormConverter.cs (thanks Kurt).
Thanks to @Lusamine (Anubis) for help with the peculiarities.
=> Add alt form index data to dex

data/formats-data.ts
https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/#post-8464064
=> Move Appletun, Silvally-Fighting, and Silvally-Poison to PUBL

data/formats-data.ts, data/learnsets.ts, sim/team-validator.ts, test/sim/team-validator.js
https://github.com/kwsch/PKHeX/commit/3210ced006409ef298238059fbb038b17368dd28
=> Pikachu-Gmax is now available from raids

server/chat-plugins/thing-of-the-day.ts
@HoeenCoder seems you missed one
=> vgotd: add missing image property

config/formats.js
https://www.smogon.com/forums/threads/dpp-baton-pass-revisited-baton-pass-is-now-banned.3663689/#post-8467319
=> DPP OU: Ban Baton Pass

data/formats-data.ts, data/pokedex.ts
=> Correct Xerneas formeOrder oversight

config/formats.js
https://www.smogon.com/forums/threads/almost-any-ability.3656414/page-4#post-8462246
=> AAA: Ban Dragapult

server/chat-plugins/scavengers.js
Requested by A Phantom, waiting on Room Owner approval
Requesting a review from sparkychild
Edit: Apparently, I can't directly request one from them, but I've asked them to take a look at it.
=> (Not yet approved) Add /scav removehint and /scav edithint

server/chat-plugins/thing-of-the-day.ts
this was requested by members of roomauth
=> vgotd: replace quote with tagline

server/chat-commands/admin.ts, server/chat-plugins/hangman.ts, server/chat-plugins/jeopardy.ts, server/chat-plugins/thing-of-the-day.ts, server/chat-plugins/wifi.ts, server/roomlogs.ts, server/rooms.ts
Not doing so wastes a lot of bandwidth.
This fixes https://www.smogon.com/forums/threads/dont-send-all-uhtml-messages.3664370/
=> Replace attributed uhtml on change

config/formats.js
People have complained that "Black Kyurem", although formal, sounds dumb
=> Change Monotype suspect notice message

server/chat-plugins/scavengers.js
Remove the 10 minute restriction as discussed in scavenger room policy and approved by Meicoo.
[insert signature weeb talk]
=> Scavengers: remove 10 minute restriction on hints

server/chat.ts
Please don't exceed the line length this time. ;;
=> Add case insensitivity to Scripted Buttons

data/formats-data.ts
https://www.smogon.com/forums/threads/np-ru-stage-1-i-lost-something-in-the-hills-inteleon-and-slurpuff-banned-see-post-104.3659533/page-5#post-8470839
=> Move Inteleon and Slurpuff to RUBL

data/abilities.ts
Missed Trace when I was doing research on NGas for https://github.com/smogon/pokemon-showdown/pull/6581
=> Fix Trace's interaction with Neutralizing Gas

config/formats.js
https://www.smogon.com/forums/threads/np-ss-ou-suspect-process-round-4-fish-out-of-water.3664521/
https://www.smogon.com/forums/threads/np-ss-uu-stage-4-heads-will-roll-haxorus-suspect-test.3664575/
=> Add OU and UU suspect notices

config/formats.js
https://www.smogon.com/forums/threads/mix-and-mega.3656469/page-3#post-8470642
=> M&M: Restrict Zeraora

data/formats-data.ts, data/learnsets.ts
I was notified by @Lusamine about this
=> Gmax Eevee is no longer event-only

config/formats.js
All of the threads besides modern gen were old.
=> Update oldgen Doubles OU thread links

data/mods/ssb/statuses.ts
Name change that I missed in my batch update
=> SSB: Batch Update

server/chat-plugins/lottery.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8474970
=> Fix Visual Lottery Bug

data/mods/gen7/moves.ts, data/moves.ts
(In Gen8, according to both Bulbapedia and Serebii, Howl is a Sound move)
=> Add Sound flag to Howl

CODEOWNERS
Thanks @xfix for noticing this in my scavengers to TS pullreq.... and mafia had the same thing!
=> CODEOWNERS: update mafia to .ts

server/chat.ts
(No longer needs the client change)
=> Add msg button

config/formats.js
https://www.smogon.com/forums/threads/stabmons.3656429/page-3#post-8476391
=> STABmons: Ban Dracovish

server/chat-commands/info.ts
=> Fix Effectiveness showing undefined
