CODEOWNERS, server/chat-plugins/scavenger-games.js, server/chat-plugins/scavengers.js
- apply them as "formats"/"mods" instead of a large parent game with another room game nested inside
- the parent game is attached to ``room.scavgame`` as an independent object instead.
- add a command to set the twist (/scav settwist) and reset the twist (/scav resettwist) for scripted formats
- this means that scavenger-games.js might be updated once per month as new twists are created.
- add a command to start a regular hunt with twists
More than one twist can be loaded into a single scavenger hunt (from scavenger game mode + /scav createtwist)
And as usual, this has Meicoo's seal of approval.
=> Rework special scavenger modes

test/sim/abilities/unaware.js
Currently, Unaware is somehow setting the its flag for multiple targets. In this test, a +3 Surf is used into an Unaware ally and two opposing Sturdy Pokemon - it should always deal enough damage to trigger Sturdy (and never enough on a crit), but it does not because Unaware is getting applied to the Sturdy Pokemon.
Showdown replay example (incorrect, turn 4) (this was actually from me laddering for a DOU suspect!): https://replay.pokemonshowdown.com/gen8doublesou-1088725658-xrpimtcqyp07fmz994elc0rwer26vf6pw
=> Add test for Unaware & spread moves

test/sim/decisions.js
This is a regression from changeset 28be861 where the test passes.
=> Add test for priority of shift action in Triples battles

server/chat-commands/moderation.js
If /hidetext is used with a linecount parameter on a trusted user, it currently says "USER, 4 is a trusted user, are you sure you want to hide their messages? Use /forcehidetext if you're sure." This change hides the additional linecount parameter from the message.
=> Fix minor /hidetext bug

sim/battle.ts, test/sim/abilities/naturalcure.js
Regression caused by: https://github.com/smogon/pokemon-showdown/commit/47b55f96bc5c62e51255012e154ea81a46a2bb90
`Battle#dragIn` used to run the `SwitchOut` event among other functions
but were accidentally left off in the refactor. This commit adds them back.
The main bug caused by this is Natural Cure not curing status aliments when
phased out by Roar.
@Zarel: **please review/merge ASAP** as a major ADV tournament is going on
currently, so Natural Cure being broken is a big deal.
=> Fix `Battle#switchIn`

test/sim/abilities/desolateland.js
Zarel fixed yesterday in https://github.com/smogon/pokemon-showdown/commit/20e7e604ebe1913a7a7658745b2d23f9c6cb4c19, but just as a sanity thing.
=> Add Primal weather phazing test

data/items.js, data/mods/gen7/items.js
You can't obtain Plates, save Pixie Plate, in Sword and Shield.
=> Mark Plates (except Pixie Plate) as past gen items

data/mods/vgc17/formats-data.js
Most old VGC 2017 tournaments just have to gentlemen's agreement not to use these right now; we probably should actually ban them! The Immortal's commit to fix illegal Z-moves in 2017 prompted this.
=> Ban Hidden Abilities unreleased in VGC17

data/mods/gen2/items.js, data/mods/gen3/items.js, data/mods/gen4/items.js
72976d1 sort of fixed Quick Claw for past gens, but while simplifying it I noticed that Custap Berry also needed a fix.
=> Properly override onFractionalPriority in past gens

config/formats.js
Mirror Armor is a temporary ban because it is causing stack overflow errors
=> Shared Power: Fix banlist and ban crash-causing ability

server/chat-plugins/chatlog.ts
fuck the js date api
mia's doesn't work because `${date}-15` isn't guaranteed to be valid, ie `2010-04-5` is valid while `2010-04-5-15` isn't.
=> Fix bugs in chatlog date parsing

data/mods/ssb/scripts.js
Bar Fight is supposed to act like Fake Out and only work on turn 1. This line added in this PR was missing from the runMove function, so Bar Fight and Fake Out were usable past turn 1.
=> Fix activeMoveActions bug

data/scripts.js, test/sim/moves/fellstinger.js
This also fixes a bug whereby if you target your own ally with Aqua Jet, but your opponent switches in Gastrodon and Bruxish, then Dazzling should prevent the move from executing.
I take the last target because Dazzling still needs to be able to block Prankster Copycat Earthquake. If you prefer I could probably change the test to `targets.length === 1` since there can only be one target for a redirect.
=> Fix Fell Stinger after redirection

data/moves.js
Fixes the behavior from this replay:
https://replay.pokemonshowdown.com/gen8doublescustomgame-1096032925.log
=> Prevent Crafty Shield from blocking Perish Song 

server/ip-tools.ts
Hostfiltering the whole range might cause casualties, but based on experience I am almost 100% sure that these (rather small) ranges specifically are not residential connections.
This is kinda bypassing the datacenters list so I'm open to better implementation ideas
=> Improve hosttype detection for special case

sim/team-validator.ts, test/sim/team-validator.js
Previously, format bans/unbans were processed in order of "most specific to least specific".
So `+Giratina-Origin` trumps `-Giratina` trumps `+Uber` trumps `-All Pokemon`.
And nonstandard reasons (`Unobtainable`, `Past`, `CAP`, etc) were slotted between `Uber` and `All Pokemon`.
This has the unfortunate effect that if a base ruleset allows a certain normally-banned category of Pokémon, you can't use `-All Pokemon` to whitelist a list of Pokémon.
Moving nonstandard reasons to lowest precedence once again allows `-All Pokemon` to be used as intended.
=> Support whitelisting in illegal rulesets

data/abilities.js, data/items.js, data/moves.js, test/sim/moves/gmaxvolcalith.js
Currently, G-Max Volcalith / G-Max Wildfire / Sea of Fire do not have a proper residual order variable, so it runs _after_ the end-of-turn effects which I am sick of dealing with in VGC haha. This fix isn't perfect, though. Sea of Fire / G-Max Volcalith / G-Max Wildfire all definitely have a onResidualOrder of 5 and a suborder of 1, but that suborder of 1 is queue-based; it happens in whatever order the effects were set. So currently, if two of these 3 effects are active, it will be random which one happens first, which can matter but is more niche. My hacky solution is to set the G-Max moves to be suborder 1.1, and then write a skipped test for it, except there's _another_ mechanics bug that doesn't let healing Berries activate in between Sea of Fire and G-Max Volcalith, so my test is …
=> Fix residual order for G-Max Volcalith / Wildfire

data/aliases.js
The entire Pokemon Games room refers to Sealeo as Seejong and it has significant meme value. Additionally, Seejong is Sealeo's German name.
=> Add "seejong" as an alias for Sealeo

data/abilities.js, test/sim/abilities/technician.js
As pointed by @DaWoblefet, the interaction of Technician with some abilities boosting move BPs was faulty; Technician would apply even though the move was boosted over 60 BP. This should now be fixed. The concerned abilities are Fairy Aura, Dark Aura, Aura Break, Battery and Power Spot.
Also, according to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Technician_(Ability)), this behaviour doesn't apply to Steely Spirit. I'm not sure if I can trust Bulbapedia on this, and seeing as the only concerned move would be Metal Claw, which can only be learned by Scizor and is therefore unavailable in gen 8, this is not really checkable anyway. I coded it so that Technician would apply first.
https://github.com/smogon/pokemon-showdown/projects/3#card-25870312
=> Fix Technician interaction with Battery/Auras/PowerSpot

data/scripts.js
Currently, Max Moves are sending `sourceEffect` of their base move when the original move type isn't identical to source move type. This results in the server leaking which base move was used. For example:
|move|p2a: Nine lives|Max Flare|p1a: Smeargle|[from]Weather Ball
|move|p1a: Silvally|Max Flutterby|p2a: Necrozma|[from]Multi-Attack
It's more apparent with Weather Ball because it has a custom string attached to its Z-move transformation, but it's getting sent with any Max Move that dynamically changes typing, e.g. https://replay.pokemonshowdown.com/gen8doublescustomgame-1099210961.
=> Fix Max Move base move source from leaking

data/FORMES.md
Follow-up to the discussion between @Zarel and @urkerab in b9e25acbbf30cdcaaed1439882b45146224d18c2 and 7c0a6a9c603e8fb2488472bb50e3ce80eb4cafbf
I'd like a few comments on:
- Shaymin-Sky that was in @urkerab's list does not actually have `battleOnly`, so even though I understand that due to the reversion when frozen during battle it has a special treatment, does it fit in that list?
- Megas and Primals also do not have `battleOnly`, so should they stay in that list? Or should the text below be rewritten to exclude these specific cases?
- Ash-Greninja is now in the "In-battle formes" list and also in the "Event-only Ability formes" list, and again I understand why with its distribution, but should it stay this way? I was leaning towards yes so I left it so far.
- There was an explanation …
=> Typos and complete list of in-battle formes

data/abilities.js, data/moves.js, test/sim/moves/skydrop.js
https://github.com/smogon/pokemon-showdown/projects/3#card-25870318
Sky Drop should affect every Wonder Guard Pokemon on the first turn, effectively taking them in the sky. Then Wonder Guard would activate on the second turn, when the attack actually happens. This should now be the case. Additionally, Sky Drop still affects Flying-weak Wonder Guard Pokemon.
I noticed the message "[Pokemon] is freed from the Sky Drop" still displays even if the Pokemon faints. I don't know if it should be the case or if it should be omitted.
=> Fix Sky Drop Wonder Guard interaction

server/chat-plugins/datasearch.ts
This was inspired by [this suggestion about !ds all](https://www.smogon.com/forums/threads/improve-how-ds-all-displays.3654308/), but in my opinion there's not really a good use case for broadcasting _any_ errors, so I went ahead and disabled broadcasting for all errors (also, since we have `this.errorReply()`, I went ahead and made sure that errors used that).
=> Datasearch: don't broadcast errors

data/scripts.ts, test/sim/abilities/dancer.js
If the holder has no more allies then the battle simply ends, but if you KO a Dancer with a Dance move then you get a presumably spurious activation message. (The Dancer doesn't actually copy the Dance move; this is just an ability activation display error.)
=> Dancer should not activate if the holder fainted

data/moves.ts
Per SadisticMystic:
"https://docs.google.com/spreadsheets/d/15r_-iUngMDoA9ux7tCkUJLJVBeQhpIzEH7rju9fgWOQ/edit
the "Moves" tab is a dump of move data from the game, CS has a "-33"
listed under the Heal% field, just like Double-Edge has under
Drain%"
=> Change Clangorous Soul self damage from 1/3 -> 33%

sim/pokemon.ts
As discussed here: https://github.com/smogon/pokemon-showdown/commit/9b943fb#r38273770
`onModifySpecies`, or as it was called back then `onModifyTemplate`, always used to be passed the effect that was setting the template. Commit 9b943fb changed that to always pass `null` for Transform and Imposter. Although I don't mind either way, commit history suggests that it's preferred to pass the effect in all cases. (Note that `Transform` doesn't actually pass the effect to `transformInfo` but because the effect is missing rather than null this means that `setSpecies` is able to look up the effect by default anyway.) In particular Camomons is currently checking for the two specific effects to avoid modifying a Transformed template.
=> Pass the Transform or Imposter effect to onModifySpecies

data/pokedex.ts, data/random-teams.ts, data/rulesets.ts, server/chat-commands/info.js, sim/dex-data.ts, sim/dex.ts, sim/global-types.ts, sim/team-validator.ts
I renamed it from `inheritsFrom` to `changesFrom`, and it is no longer an `ID` to be consistent with upcoming changes to `otherFormes` and `cosmeticFormes`
=> Refactor inheritsFrom to changesFrom

data/moves.ts, test/sim/moves/shelltrap.js
Error introduced as part of the fix for PR #6231.
Reported here: https://www.smogon.com/forums/posts/8438387
Relevant replay in the post: https://replay.pokemonshowdown.com/gen8hackmonscup-1101486710 turn 47
=> Shell Trap should not power up if hit by a Z- or Max move

data/abilities.ts, sim/battle.ts, sim/global-types.ts, test/sim/abilities/moxie.js
In addition, they should not activate for a spread move that ends the game.
(This contrasts with Soul-Heart, which will activate until the last target.)
This behaviour is on one of @DaWoblefet's lists somewhere.
(Given my recent luck, this is probably not the best way to implement this.)
=> Moxie and Beast Boost should have one combined boost for all fainted Pokémon.

data/mods/gen2/moves.ts, data/mods/gen4/moves.ts, sim/battle.ts
As confirmed by SadisticMystic, base power cannot be above 255, so
this move data is clearly incorrect and results in downstream users
of the data files such as the Smogon or PS dex or the tooltips
displaying misleading information.
=> Correct Self-Destruct and Explosion base power

config/formats.js
DO NOT MERGE UNTIL MAY 1
The newest Battle Stadium legalizes all remaining Gigantamax Pokemon. As far as I can tell, it's otherwise identical to series 3.
=> Update VGC and Battle Stadium to Series 4

sim/dex-data.ts
Disclaimer: I don't know whether or not this is correct or desirable. I noticed "Let's Snuggle Forever" getting assigned a `zMovePower` of 200 which seemed very odd to me given its base power is `190`. It seems confusing to set these attributes (though I imagine the engine is not looking at them for these moves)
=> Fix default Max/Z power for isMax/isZ moves

data/moves.ts, sim/global-types.ts, sim/pokemon.ts
As researched by @DaWoblefet: https://www.smogon.com/forums/posts/8440929
- Each use of G-Max Chi Strike increases team's crit ratio by 1
- This increase stacks up to 3 layers
- Can be copied by Psych Up, Imposter and Transform but not Baton Pass
I don't know why `global-types.ts` had two copies of `onRestart`; it seems to compile fine with just the one.
=> Fix G-Max Chi Strike's effect on Crit Ratio

server/rooms.ts
Guests usually don't appear in join/leave/rename messages, but it's
possible for a bot to /trn to a guest nick with an assertion from the
login server and trigger a leave message for a guest nick to get sent.
This shouldn't have any consequences for the official client, but can
crash bots that keep state for users.
=> Prevent user identity updates from sending leave messages for guests

server/chat-commands/moderation.ts
This is a more common alias for blacklist than ab, which was implemented because that's what bots at the time used
=> Add bl as an alias for blacklist

data/abilities.ts, data/mods/gen7/moves.ts, data/mods/ssb/moves.ts, data/mods/ssb/scripts.ts, data/moves.ts, data/rulesets.ts, data/scripts.ts, server/chat-commands/info.js, server/chat-plugins/datasearch.ts, sim/battle.ts, sim/dex-data.ts, sim/global-types.ts, sim/pokemon.ts
This mostly serves to provide cleaner and more consistent field
naming. maxMove currently doesn't have boosts or effects to group
together but who knows what will be thrown at us via DLC, and being
symmetrical with zMoves is a nice.
=> Group zMove and maxMove attributes

test/server/sockets.js, test/sim/abilities/disguise.js, test/sim/abilities/flashfire.js, test/sim/dex.js, test/sim/moves/shelltrap.js
This removes the skip from two passing tests (Shell Trap was failing due to a syntax error that I corrected, and Flash Fire's oldgen mechanic was actually working). I also simplified a failing Disguise critical hit test.
It also adds notes that the socket tests are failing due to a syntax error rather than actually failing tests, and that dex is failing due to the relative paths of the files it's trying to find being wrong. I don't feel confident enough to fix those later two, but I did add comments for them.
=> Unskip passing tests

server/chat-commands/core.ts
@asgdf  brought this up recently to me. This is purely a convenience command so it doesn't have to be done via replays and can instead grab the inputlog natively within Showdown. I'm not sure if this needs policy hashed out or anything, but the only difference I'm seeing is that it's being done through Showdown and not through replays. Leaders still have access either way. Players still have to explicitly request permission to obtain the inputlog from a battle, even if a leader+ grabbed the inputlog first. As a sanity check, it also still logs to the battle that the leader+ exported the input log.
=> Allow leaders+ to exportinputlog directly

server/chat-plugins/datasearch.ts
Returns this now:
instead of this:
I didn't make it return G-Max moves since there's a separate flag already for them.
=> Fix movesearch with max flag

config/formats.js
There is currently an exploit where if you put Gengarite on Gengar-Gmax in a National Dex team, you will be able to bring Gengar @ Gengarite to battle. This only happens because of dynamax clause existing, preventing the dynamax button from appearing.
I will find a real fix to this soon, but this is very high priority that it gets patched in some way for now.
=> National Dex: Ban Gengarite

server/chat-commands/info.ts
I didn't update the tiers article because I couldn't find a Gen 8 equivalent.
=> Update links in /intro for Gen 8

test/sim/moves/gmaxchistrike.js
G-Max Chi Strike currently sets Focus Energy, when it should actually set an independent stat boost. G-Max Chi Strike boosts crit rate by 1 and is stackable, unlike Focus Energy which boosts by 2 and is not stackable. See research:
https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8440929
My tests here are weird. For one thing, crits are random; normally it'd be easy to test because you'd just give the mon Scope Lens and Super Luck and check if the move crit after a single use since the mon is +3, but since Focus Energy is being set you can't really use that as a test because the old implementation would just reach +4 and you'd crit anyway.
The 1st test checks that it's different from Focus Energy. Some subsequent tests pass when they should not …
=> Add a few G-Max Chi Strike tests

data/mods/gen1/moves.ts
By the way, this pull request assumes there is no other way for Rest to fail, otherwise such a message could be an information leak. Is this the case for Gen1 games? I don't think there is a way to prevent sleep, but maybe I did miss something.
=> Gen I: Add HP hint for Rest

test/sim/team-validator.js
Kyurem-B and Kyurem-W should not have access to Glaciate (all gens) or Scary Face (pre-Gen 8, since it was made a TM in Gen 8). It also adds cases for Toxicrity and Rotom, which pass.
=> Add forme-exclusive move validator tests

server/chat-commands/room-settings.ts, server/roomlogs.ts
If someone were to type ``/rename `` it would then glitch any server that has the autojoin for lobby enabled. Also for whatever reason it just didn't log the newly named room in chat logs.
=> Fix the rename command to log the new room & require a target

test/sim/abilities/steelyspirit.js, test/sim/abilities/symbiosis.js, test/sim/items/metronome.js, test/sim/misc/dynamax.js, test/sim/misc/target-resolution.js, test/sim/moves/fling.js, test/sim/moves/maxguard.js, test/sim/moves/tarshot.js
Specifically, Fling, Tar Shot, Symbiosis, Steely Spirit, the item Metronome, Max Guard, and a bizarre interaction with moves that call other moves + moves that have a charge turn + Ally Switch all have additional tests. There are 8 skipped tests in here to account for the mechanics bugs reported so far in the new bug reports thread (up to post 61) as well as 11 passing tests to complement behavior and hopefully ensure behavior doesn't regress if any of the failing tests are tackled.
=> Add various mechanics tests

server/chat-plugins/wifi.ts
* /qg is an alias for /giveaway question, whereas /question on its own does not exist
* Because the can() check generates the "Access denied" message but there's another part of the condition (you can always end giveaways for yourself), it was possible to get `Access denied` despite the command stil going through. I switched the conditions so short circuit evaluation prevents this from happening
=> Wifi plugin: Fix display issues

server/chat-plugins/scavenger-games.ts
Previously, the code only allowed for those who were not on the playerlist to join hunts, when it should be only those who are on the playerlist.
Also, the first end-of-round announcement announced those who were in the game, rather than only those who had completed it.
=> Scavgames KO Games: Allow finishers to continue and announce correctly

data/scripts.ts, test/sim/abilities/emergencyexit.js
Life Orb should trigger Emergency Exit.
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-2#post-8465511
I apologize if this isn't the cleanest way to do it. I initially had placed the Emergency Exit runEvent inside of Life Orb's code but I know that's not an acceptable way to accomplish this. This passes all tests and I believe should be okay, but if there's tweaks I should make to it, please let me know.
=> Life Orb + Emergency Exit Interaction Fix

server/chat-plugins/youtube.ts, server/rooms.ts
This is mostly for the youtube room. However, /requestapproval and /link are meant for all rooms, since they're very commonly used through Kid A and very useful, and can be streamlined a bit here (they're in this plugin so they can make use of the Youtube interface.) 
Specifics are here https://www.smogon.com/forums/threads/youtube-channel-database.3664726/.
This has been approved by both Kie and A Random Duck.
As for the Config setting for the api key, i have a key that can be used, and can share privately for someone who can set that.
=> Youtube: add plugin for viewing videos/channels

test/sim/abilities/emergencyexit.js
fart's change in https://github.com/smogon/pokemon-showdown/pull/6738 unfortunately broke Emergency Exit in another way; it's requesting switchout if its HP is already below 50%, see bugged behavior turn 17: https://replay.pokemonshowdown.com/gen8randombattle-1122012552
Adds skipped test (what's failing) and passing test for if Emergency Exit heals HP above 50% and gets brought back down again (currently passing)
=> Add Emergency Exit tests for new bugged behavior

data/moves.ts, test/sim/moves/tarshot.js
When a Fire type move is used against a dual typed victim of Tar Shot, the resulting effectiveness is applied twice. This is because the Effectiveness event gets called for each type of the target. (Freeze Dry relies on this for instance.)
- For (dual) types that normally dual resist Fire, this means that they still dual resist Fire.
- Types that normally resist Fire are unaffected as they are now neutral to fire anyway.
- For dual types that were neutral to Fire, this means that they are now quad weak to Fire.
- For dual types that were weak to Fire, this means that they are now 16× weak to Fire.
- For (dual) types that were quad weak to Fire, this means that they are now 64× weak to Fire. (The sim clamps the weakness to this level, so you can't go higher using Forest's Curse.)
The test …
=> Fix doubled effectiveness for victims of Tar Shot

server/chat-commands/admin.ts
- Allow whitespace around the party slot number
- Fix finding a Pokemon by species name
- Fix adjusting PP
- Make the help message clearer in that a number for a pokemon represents the position in the party
=> Fix and enhance /editbattle

config/formats.js, sim/battle.ts, sim/global-types.ts
Making it a `battle` property means that it doesn't have to be explicitly copied when starting or deserialising battles.
=> Simplify handling of `trunc` for custom battles

data/moves.ts, data/rulesets.ts, data/statuses.ts, sim/global-types.ts, test/sim/misc/inversebattle.js, test/sim/moves/tarshot.js
Inverse Mod needs to go first, to calculate the negated effectiveness.
Disguise goes second, to suppress effectiveness.
Delta Stream goes third, to weaken moves super-effective against Flying types.
Tar Shot goes last, to make its victim weak to Fire type moves.
This allows the existing test for Delta Stream with Tar Shot to pass.
Additionally a new test for Delta Stream with Inverse Mod now passes.
A test for Flying Press with Inverse Mod is also included.
=> Fix bugs caused by not specifying effectiveness priority

server/chat-commands/info.ts
This is a pretty minor issue but I stumbled upon it while adding searching by target to `/movesearch` so I figured I'd just open a PR fixing it.
=> Add more move target types to /details

server/tournaments/index.ts
Fixes the bug shown in the attached image.
=> Tournaments: escape usernames in /tour getusers

data/abilities.ts, test/sim/abilities/disguise.js
Basically in the same way that effectiveness is ignored.
Also enabling the test, of course.
=> Disguise breaking prevents critical hits

server/chat-plugins/datasearch.ts
I also redesigned dexsearchhelp.
(suggestion [here](https://www.smogon.com/forums/threads/more-clear-ds-paramater-to-exclude-nfe-and-lc-mons.3665165/#post-8484543))
=> Datasearch: Support searching for fully evolved Pokemon

sim/team-validator.ts
If you write `/learn clefable, wish` it says:
In Gen 8, Clefairy can learn Wish from:
- anywhere (move is level-up/tutor/TM/HM/egg in Gen 8)
- must be obtained as Cleffa
The latter is not true, as you can breed a second Cleffa with Wish, evolve it into Clefairy, and then transfer Wish in the Nursery.
I couldn't work out why `/learn clefable, wish, teleport` works even without this though, so maybe there's a special case somewhere else that is no longer necessary.
=> Fix display of Gen 8 Nursery Mechanics in `/learn`

data/mods/gen5/formats-data.ts
https://www.smogon.com/forums/threads/official-smogon-university-simulator-statistics-%E2%80%94-august-2013.3487934/ It very clearly has 7% usage in the last tier shift of gen 5, i just accidentally changed its tier when implementing Gen 5's Below NU support
=> Fix Mandibuzz's Gen 5 tier

data/formats-data.ts
(i) Gourgeist can't learn Shadow Claw.
(ii) I was also asked by A Cake Wearing A Hat to remove Type: Null's entry from Doubles.
=> Update Gourgeist / Type: Null Doubles Sets

data/moves.ts
Commmit 1fa9e14 erroneously added the source effect to all the calls to `prioritizeAction`, not just those for the Pledge moves and Round. As well as breaking After You, this also confused me when I created PR #6231 and I had to fix that separately in PR #6622.
No, I don't have a test handy.
=> Back out erroneous change from 1fa9e14 to fix After You regression

data/scripts.ts
Things like Life Dew and Heal Pulse aren't generating correct failure messages when the target is at full HP. Example report: https://www.smogon.com/forums/posts/8492144
=> Correctly attribute target with full HP

sim/battle.ts
PR #4281 again, but with a comment this time, so that it won't get accidentally reverted like it did in PR #5427.
=> Allow formats to reorder all six Pokémon again

server/chat-plugins/datasearch.ts
A lot of people had been asking about whether it was possible to search for moves with a high critical-hit ratio (relevant for building with things like Sniper or Focus Energy).
Note: This does not include directly searching for moves that have a critRatio of 3 (only one move has that) or 4 (not many have those - if you guys feel I should support searching for crit levels like priority does, I'll add that in.)
=> Support Crit in Movesearch

server/chat-commands/admin.ts
Some commands like  `/adduhtml` and other HTML based commands didn't mention that Room owners can use those commands.
PS: I have tested it.
=> Add Room Owner rank in Help Commands

server/chat-plugins/youtube.ts
Was splitting the id wrong previously. 
Additionally, would sometimes not exist.
Fixes that and ensures the id always exists as ``''`` - just is falsy if nothing else is provided.
=> Youtube: fix crashes with checking ID

data/pokedex.ts
Evidence, if needed:
- https://www.smogon.com/forums/threads/cap-18-final-product.3507516/post-5471155 final product was 2014, well after gen 6 release
- https://www.smogon.com/cap/pokemon/ has it listed under gen 6
- learnsets.js doesn't contain gen 5 data
=> CAP: Volkraken and Volkritter are gen 6

sim/team-validator.ts
If you attempt to challenge an opponent to Tradebacks, it will reject Pokemon with NYPC moves even though they should be legal. For example, attempting to use Lovely Kiss Snorlax in RBY Tradebacks:
"Your team was rejected for the following reasons:
- Snorlax has an event-exclusive move that it doesn't qualify for (only one of several ways to get the move will be listed):
- This format is in gen 1 and Snorlax is from gen 2 because it has a move only available from an event."
By changing dex.gen to this.maxSourceGen in the validator for event moves, NYPC moves work as they should in Tradebacks.
=> Fix event validator for RBY Tradebacks

config/formats.ts, data/rulesets.ts
Adds Stadium's Sleep Clause to [Gen 1] Stadium OU.
In Pokemon Stadium, Sleep Clause only checks whether any Pokemon on the opposing side is asleep to activate, and does not check the source of sleep.
This means if a player's Pokemon uses Rest, Sleep Clause is activated for their side and is protected from Sleep moves, even though the sleep was self-inflicted from Rest.
Proof:
https://www.smogon.com/forums/threads/gen-1-and-tradebacks-dev-post-bugs-here.3524844/page-14#post-8502315
=> Implement Stadium Sleep Clause

config/formats.ts, sim/dex.ts
`'nduubl'` is very hacky but it hampers performance much less than adding a `nationaldex` mod.
@TheImmortal
=> Add National Dex UU

server/chat-plugins/trivia.ts
=> Trivia: Fix bug with computing user ranking

data/mods/stadium/moves.ts, data/mods/stadium/scripts.ts, sim/battle.ts
Fixed the following issues with Stadium:
-Must Recharge did not display after using Hyper Beam
-Hyper Beam did not require recharging after missing
-Self-destruct and Explosion did not cause the user to faint if it broke a Substitute
-All moves ignored the semi-invulnerability from Dig/Fly
-Dream Eater hit Pokemon that were not asleep
-Recoil moves inflicted recoil when the opponent was KO'd
Based fixes on research done by Plague von Karma and Beelzemon 2003
https://www.smogon.com/forums/threads/stadium-format-is-now-available-on-ps.3526616/page-2#post-8502629
=> Fix various Stadium issues

server/chat-plugins/modlog.ts
Currently, if you /modlog [ip] (as a non-gstaff user) it will show actions with that IP,  even though the IP is removed. EG: https://prnt.sc/t10k1r
This prevents anyone who isn't gstaff from searching _just_ numbers, since without it it will include IP results.
I'm not sure if there's a better way to do this with regex but this blocks all cases i can think of and doesn't hurt functionality.
=> Modlog: prevent non-gstaff from searching for IPs

server/chat.ts
- server will crash and be unable to handle any further inputs from users.   Got this error when i accidentally posted a super long HTML post that exploited /requestshow
Byproduct of https://github.com/smogon/pokemon-showdown/pull/6745
=> Fix server crash from overlength posts

config/formats.ts, data/formats-data.ts
https://www.smogon.com/forums/threads/ss-lc-chlorophyll-voting.3666084/post-8505956
Coconut (one of the TLs) asked me to tier Cherubi as LC Uber as well, since it is unusable due to this ban.
=> LC: Remove suspect notice and ban Chlorophyll

data/moves.ts
The exact power boost for Triple Axel is unknown, nor is it known if Triple Axel has multi-accuracy, but it is supposed to be a variant of Triple Kick, so this is more accurate at the very least.
The boosts from Scale Shot are only supposed to trigger after all hits occur.
=> Fix Scale Shot and Triple Axel

server/chat-plugins/youtube.ts
This ensures ID exists when checking if it includes. It already handles if this returns undefined, so no other changes should need to be made.
=> Youtube: fix ID crash 

server/chat-commands/room-settings.ts
``Config.groupsranking[1]`` is now whitelist, not voice, so this needs to be changed.
=> Fix setting modchat in battles

data/moves.ts
Shell Side Arm's currently states and functions as "Physical if target Def > Sp. Def.", contrary to the ingame description that it will use whichever stat is more effective. (If it was physical when Def was higher, the damage would be LESS effective than if Sp. Def was used.)
=> Fix Shell Side Arm

data/pokedex.ts
Right now Venusaur-Gmax isn't considered a Gmax Pokemon because its move hasn't been specified.
=> Add Venusaur-Gmax's Gmax Move

server/chat-commands/room-settings.ts, server/rooms.ts
Creation time is set on creation of the room - eg restart / command creation. 
All rooms have uptime regardless now, and uptime is saved on settings for perm rooms.
=> Rooms: save creation time for all rooms

server/chat-commands/admin.ts, server/chat-commands/info.ts, server/chat.ts, server/rooms.ts
Similar to /evalbattle, when ``>>`` is used, it now broadcasts into the room. /eval still does not. 
They both log into the development roomlogs. Also puts eval output that's larger than 200 characters (tentative) into a readmore details tag.
=> eval: Log in dev room and broadcast 

config/formats.ts
Cobalion, Terrakion, and Virizion can all be legally used via the in-game character that wipes their pastgen learnset and gives them the "battle-ready" symbol. Raichu-Alola and Weezing-Kanto can both be obtained naturally now (pretty sure) and even if they couldn't you could use the battle-ready trick to do so.
Given that the rest of DLC is already VGC legal (notably learnsets), there are no other Series 4 tournaments between now and July 1 (when we officially swap), I'm ok pushing this through early to allow hype.
=> Update VGC to Series 5

server/chat-plugins/trivia.ts
The command was requested by the Trivia staff, so that Voices could avoid repeating the same type of Trivia game without needing access to modlogs.
=> Trivia: Add /trivia history command

server/chat-plugins/youtube.ts
Not sure how this hasn't been tripped before. The first item holds the video data, so without that you get an issue.
=> Youtube: ensure video data exists in the response

server/chat-commands/info.ts
I saw this feature request somewhere although I forget where now.
=> Show status immunities in /weak output

server/chat-commands/room-settings.ts
Filter out empty strings from the `banword add` and `banword delete`
arguments. Added a check in `banword add` for an empty array of
arguments.
Thought it could be useful after today's Video Games room issue.
=> Prevent empty string from being added to banwords

config/formats.ts
https://www.smogon.com/forums/threads/magearna-is-now-banned-from-monotype.3666296/
=> Monotype: Ban Magearna

data/moves.ts
Sorry, the most recent change I did to this (which I weirdly based off of Rototiller) actually made it so that the terrain boost would never occur. As Kris suggested, this is the correct way to handle it.
=> Fix Rising Voltage

server/ip-tools.ts
A large portion of the IPs with that hostname are static broadband connections.
=> Remove incorrect host classification

data/mods/gen1/formats-data.ts
Clefairy isn't available at or below level 5 from RBY or from trading back from GSC
=> RBY: Move Clefairy to NFE

server/chat-plugins/trivia.ts
Fixes this bug where the reversed history gets saved.
=> Trivia: Fix bug in /trivia history

server/chat-plugins/room-events.ts
Pretty self-explanatory, `/events remove Test Event` didn't remove the event because Test Event isn't an ID. Now it uses eventID
Edit: found a second bug, added a commit to fix.
=> Fix multiple bugs in events

data/formats-data.ts, data/random-teams.ts
random doubles will be waiting until DLC2 to include DLC2 Pokemon. I have the sets removed saved in a google doc.
Choice item and life orb code revamped for doubles. Contains minor hardcoding to prevent scarf scyther.
All the Focus Energy stuff is for Inteleon-Gmax, and all the Klutz stuff is for Lopunny.
=> Random Doubles Update

config/formats.ts
https://www.smogon.com/forums/threads/np-zu-stage-1-introduction-qb-slate-results-47.3663459/page-2#post-8520841
Silvally-Electric is already PUBL, so it's not usable
=> ZU: Ban Thwackey

data/abilities.ts, data/items.ts, data/mods/gen2/items.ts, data/mods/gen3/items.ts, sim/global-types.ts
The main change is due to Anubis's research into Quick Draw and Quick Claw; the latter only gets a chance to activate if the former does not.
While I was there I noticed that the fractional priority is always `-0.1`, `0`, or `0.1`, so that the `Math.round()` is pointless which simplifies the code.
I also assumed that Custap Berry, should it ever be released, will activate in preference to Quick Draw.
=> Adjust fractional priority for latest research

server/chat-commands/info.ts, server/rooms.ts
Requests from various room staff.
- support /hidetexting requested media once shown (done with using /uhtml)
- support viewing pending requests (done in a page)
- modlog who approves / denies a link 
On another note, makes the comment on /requestshow more viewable by putting it in a box.
=> Info: Support viewing current media requests and hiding media

server/chat-commands/admin.ts, server/chat-commands/core.ts, server/chat-commands/info.ts, server/chat-commands/moderation.ts, server/chat-plugins/announcements.ts, server/chat-plugins/blackjack.ts, server/chat-plugins/chat-monitor.ts, server/chat-plugins/daily-spotlight.ts, server/chat-plugins/hangman.ts, server/chat-plugins/jeopardy.ts, server/chat-plugins/lottery.ts, server/chat-plugins/modlog.ts, server/chat-plugins/poll.ts, server/chat-plugins/scavenger-games.ts, server/chat-plugins/scavengers.ts, server/chat-plugins/thing-of-the-day.ts, server/chat-plugins/trivia.ts, server/chat-plugins/uno.ts, server/chat-plugins/wifi.ts, server/chat.ts, server/global-types.ts, server/room-game.ts, server/rooms.ts, server/sockets.ts, server/tournaments/index.ts, server/users.ts, test/server/chat-plugins/trivia.js, test/users-utils.js
I couldn't completely remove the global room in one commit, but this solves basically every problem with it by making it no longer a `Room`.
In particular, this means:
- It's no longer of type `Room`
- It's no longer in the `Rooms.rooms` table
- Its class name is now `GlobalRoomState` rather than `GlobalRoom`
- It no longer tracks its own user list (online user count is now provided by `Users.onlineCount`)
- It's no longer a socket channel (there's new syntax for "send this message to every user")
=> "Remove" the global room

server/tournaments/generator-round-robin.ts
Fixes a regression from PR #5492 which removed a `map` from the relevant expression, thus causing the player array itself to become sorted, which means that players are no longer associated with their correct battle results (the scores are still correct though).
=> Don't sort player array in-place when scoring round robin tournaments

config/formats.ts
https://www.smogon.com/forums/threads/galarian-darmanitan-ash-greninja-mega-metagross-tornadus-t-and-urshifu-s-are-now-banned-from-national-dex.3666855/#post-8526942
=> National Dex: Update bans

config/formats.ts, data/rulesets.ts, sim/dex-data.ts, sim/dex.ts, sim/global-types.ts
This puts the restrictions in the rule table, thus allowing them to be inherited and modified, but also avoids having to guess where to find them in the code that implements them.
I just picked `*` because it's the next mathematical symbol after `+` and `-`...
=> Allow custom formats (e.g. for tours) to modify format restrictions

config/formats.ts
https://www.smogon.com/forums/threads/urshifu-rapid-strike-style-is-now-banned-from-monotype.3666918/#post-8528714
=> Monotype: Ban Urshifu-Rapid-Strike

server/chat-plugins/trivia.ts, server/chat-plugins/youtube.ts, server/chat.ts
This has been discussed extensively on Discord, but in case any of you don't keep up there or want more details...
This change adds a new class `Chat.ErrorMessage extends Error`, which can be thrown. If thrown inside a chat command, PS won't crash, but will instead send its message to the user as an error message. Otherwise, PS will crash normally.
The purpose here is to eliminate some boilerplate. This would otherwise have been written:
```ts
try {
doAThing();
} catch (e) {
return this.errorReply(e.message);
}
```
But by standardizing an error type that's intended to represent a user error, we can simplify this to:
```ts
doAThing();
```
The main disadvantage here is that it's no longer obvious that `doAThing()` can throw, exiting the scope and preventing anything more from happening. …
=> Support throwing error messages

server/chat-commands/admin.ts, server/chat-commands/core.ts, server/chat-commands/room-settings.ts, server/chat-plugins/helptickets.ts, server/chat.ts, server/ladders.ts, server/punishments.ts, server/rooms.ts, server/tournaments/index.ts, server/users.ts, test/server/ladders.js
Server side portion of https://github.com/smogon/pokemon-showdown-client/issues/1271, in two commits which can be rebased (instead of squashed). Pretty sure this requires a restart because I dont think we can hotpatch the first change. The change to `SETTINGS` and `updateuser` should be safe, this was its original state before I randomly added the other crap by mistake in a previous commit.
I've confirmed hackily with
```ts
var json = JSON.stringify({inviteOnlyNextBattle: true});
app.send('/updatesettings ' + json  + '\n/trn ' + name + ',0,' + assertion);
```
on the client that the setting seems to accurately be updated:
I'll open a client side PR tomorrow.
=> Server side changes to support persistent user settings and privacy changes

data/mods/gen2/learnsets.ts
Fixes #6975; should only be merged if that issue is accurate.
=> Porygon doesn't learn Defense Curl in Gen 2

config/formats.ts, data/rulesets.ts, sim/dex-data.ts
I put all the tier stuff in there too, just in case someone wants to be able to restrict a tier (using Mix and Mega as an example, it would be able to set restricted: Uber, Gengar, Zeraora; unbanlist: Darmanitan, Dracovish, Lunala, Zamazenta).
=> Centralise the check for a restricted species

server/chat-plugins/datasearch.ts
When I originally coded this, I assumed no one wanted to see all monotype Pokémon, but apparently that's a useful thing so I changed the implementation to permit it.
=> Datasearch: Support /ds monotype without a type

server/chat-plugins/poll.ts
/j view-pollqueue without a room crashes, since there's no ``args[0]`` to run Rooms.get on.
=> Fix pollqueue page crash

data/mods/linked/scripts.ts
Second move in a chain ignores Gen 8 dynamic turn-order mechanic.
=> Linked: Fix priority of linked moves

server/chat-commands/core.ts, server/chat.ts
Note that this only suppresses `sendReply()`, so something like `/nofeedback /hourmute SomeTroll` will still display the mute message in chat (which I think is important for transparency). However, this does mean that things like `/nofeedback /hideroom` will still display in chat for the opponent to see (note that `/nofeedback /ionext`, which seems to be the main use-case, is completely suppressed).
=> Add /nofeedback command

config/config-example.js
Currently, because global bots inherit from %, their groupchat jurisdiction is actually lowered to @, denying them the (valuable) addhtml permission
=> Set global bot permissions in groupchats to bot

config/formats.ts
Currently, a set with a banned Pokemon as the species that is named after an unbanned evolution allows the Pokemon to be used (i.e a Type: Null named "Urshifu" validates), and it shouldn't.
=> Cross Evolution: Fix validating with the set's species

data/moves.ts
PR #6652 accidentally changed the logic for Copycat and Encore which previously only special-cased Max Moves (the previous condition was just `move.maxPowered`). In order to appease TypeScript I just check `move.baseMove` direcfly, however I still need to check `move.isMax` because of a hack SSB needs for Snaquaza's Z-move, and someone might try to Encore it, which would be bad.
=> Copycat and Encore should fail against a Z move

PROTOCOL.md
Added Android-Unofficial-Showdown-Client as an example of ps client implementation. This might help people to understand Pokémon Showdown's protocol easily.
=> Added another example of client implementation

config/formats.ts
All NFE Pokemon are going to be banned instead of restricted from now on, so the second check is useless.
=> Cross Evolution: Simplify validation

server/room-battle.ts, server/rooms.ts, server/users.ts
This will pave the way for @scheibo's code in #6950 to be implemented.
If you want to actually _use_ `renameBattle()`, smogon/pokemon-showdown-client#1559 will need to be merged (otherwise the client is unable to display chat messages in a renamed battle until you reload it).
=> Support renaming battles

sim/SIM-PROTOCOL.md, sim/battle.ts
https://www.smogon.com/forums/threads/real-time-replay-speed.3666710/
```
|t:|1594612966
|player|p1|Bot 1||
|player|p2|Bot 2||
|teamsize|p1|6
|teamsize|p2|6
|gametype|singles
|gen|4
|tier|[Gen 4] Random Battle
|rule|Sleep Clause Mod: Limit one foe put to sleep
|rule|HP Percentage Mod: HP is shown in percentages
|
|t:|1594612966
|start
|switch|p1a: Ariados|Ariados, L83, M|251/251
|switch|p2a: Sharpedo|Sharpedo, L83, M|252/252
|turn|1
|
|t:|1594612966
|move|p2a: Sharpedo|Hidden Power|p1a: Ariados
|-resisted|p1a: Ariados
|-damage|p1a: Ariados|236/251
|move|p1a: Ariados|Poison Jab|p2a: Sharpedo
|-damage|p2a: Sharpedo|116/252
|-damage|p1a: Ariados|221/251|[from] ability: Rough Skin|[of] p2a: Sharpedo
|
|upkeep
|turn|2
|
|t:|1594612966
|switch|p2a: Mismagius|Mismagius, L79, F|224/224
|move|p1a: …
```
=> Add |t:| to support real-time replays

data/abilities.ts, data/mods/gen7/abilities.ts
`Damp prevents all Pokémon from using Self-Destruct, Explosion, Mind Blown, and Misty Explosion;` - Bulbapedia
SmogDex says so, too.
=> Damp Negates Misty Explosion

data/items.ts
Silver Powder has had a space in its name since Gen 6
=> Fix Silver Powder's name

server/rooms.ts
This will actually destroy groupchats when a user is locked/globally banned, which to my understanding is the intended behavior.
`continue`ing when a room isn't persistent makes no sense, since groupchats are by definition not persistent.
=> Fix bug in destroyPersonalRooms()

server/rooms.ts, server/users.ts
If it would be more useful with a different cooldown length (I just grabbed 2 minutes off the top of my head) or enforcing a cooldown on namechanges to registered alts as well, I'm happy to change it.
=> Add cooldown for unregistered namechanges

server/chat-commands/core.ts, server/users.ts
I've heard that some global staff want this feature as a way to prevent people from joining battles by clicking their usercard, without full-on hiding all battles they play in.
=> Support hiding battles from /cmd userdetails

server/chat-commands/core.ts
The server-side portion of https://github.com/smogon/pokemon-showdown-client/pull/1568. This might be better restricted to trusted users (since they can use `/checkpunishment`) — personally, I think it's fine since a locked user in a room will have their status publicly visible, but there is an argument otherwise.
=> Send group for punished users in /cmd userdetails

server/chat-commands/admin.ts
Minor QOL thing, but apparently it'd be nice to have this.
See: Felucia in dev talking about it being sent to the first conn, not the current.
=> Chat commands: Make /sendhtmlpage send to the last active connection

server/chat-commands/core.ts, server/ladders.ts, server/users.ts
This is to resolve an issue where a user would be spammed by challenges from unregged bot accounts until their browser crashed. 
This PR:
- prevents unnamed users from challenging 
- Prevents a user from being challenged by a non-autoconfirmed user if they already have 3 challenges pending.
In short, should stop users from spambot-challenging.
=> Add a throttle for pending challenges

server/chat-commands/admin.ts
Allows admins to easily enable hotpatching after disabling it. This allows us to use `/nohotpatch` for more than just restart blocks (eg: temporary issues where we should not patch like when we use eval to disable commands that have very serious bugs).
A reason is required so some information on why the lock was removed is available.
=> Add a command to enable hotpatching

server/rooms.ts
This should fix the bugs about locked users not showing up in the userlist of battle rooms.
(Not letting the join/leave/rename messages of users who can't talk be displayed was originally done to prevent spamming — I assume that the spammers don't actually _play_ the battles? If they do, I can look for another solution.)
=> Display join/leave messages for locked players

config/config-example.js, server/chat-commands/core.ts
This would, for example, let PS require users to register their accounts to continue laddering past 1500 ELO.
The Register button in the popup will not work without client support (https://github.com/smogon/pokemon-showdown-client/pull/1574).
=> Support requiring high-rated users to register

server/chat-commands/moderation.ts, server/rooms.ts
This command will allow staff to clear messages while telling the client not to show a reveal button. 
Requires client support in the form of https://github.com/smogon/pokemon-showdown-client/pull/1572.
=> Implement a /cleartext command

config/config-example.js, server/chat-commands/core.ts, server/chat-commands/info.ts, server/chat-commands/moderation.ts, server/chat-commands/room-settings.ts, server/chat-plugins/lottery.ts, server/config-loader.ts, server/monitor.ts, server/punishments.ts, server/user-groups.ts, test/server/users.js
- `ip` and `ipself` are now separate permissions. This means that `ip`  is now a generalized permission for viewing IPs (no more need to use `globalban` because `can('ip')` is true for all users)
- `alts` and `altsself` are now also separate (all users used to be able to `altsself`).
- `modchat`, `modchatall`, and `manageroom` are now just one `modchat` permission whose jurisdiction controls how high you can set modchat.
=> Refactor ip and modchat permissions

server/config-loader.ts
Monitor depends on config, so we can't call any of its functions while loading config.
=> Don't hardcrash when loading config

server/chat-commands/core.ts
This was requested and makes sense to me, since it's quite a long command to type out each time.
=> Add short alias for /hidebattlesfromtrainercard

server/rooms.ts
ROs can addhtml, so it returned normal automatically, when it should have returned `leadership`.
Fixes #7007
=> Fix RO rank display on side servers

server/chat-commands/info.ts
This command was originally added for bots but they no longer inherit `@`.
=> Allow bots to use !checkchallenges again

server/chat-plugins/announcements.ts, translations/dutch.json, translations/english.json, translations/french.json, translations/german.json, translations/hindi.json, translations/italian.json, translations/japanese.json, translations/portuguese.json, translations/simplifiedchinese.json, translations/spanish.json, translations/traditionalchinese.json
Unfortunately, I don't speak any of the languages PS! is translated into well enough to actually do any translation, but I did handle the technical side.
One minor snag (which I want to discuss either here or on Discord) is that `Chat#plural` only correctly creates a plural form for English, and not other languages. Personally, I think if we are to be truly multilingual, assuming that words are always plural is probably simpler (albeit less clean-looking) than trying to programmatically generate plural forms for every language PS is translated into or gets a translation for in the future.
=> Announcements: Make strings translatable

data/mods/gen1/moves.ts, data/mods/gennext/moves.ts, data/moves.ts, sim/SIM-PROTOCOL.md
Because -prepare protocol currently sends target with two-turn moves, the server currently leaks the target of two-turn moves like Phantom Force, etc. in doubles play in the console. This removes all instances of -prepare sending the target, except for Sky Drop, where the target should be known on the first turn of the move.
Thanks to PlatypusVGC for telling me about the info leak and @Marty-D for pointing me in the right direction to fix it! Marty asked me to check to make sure nothing breaks on client from this change and nothing does.
=> Fix target leak of two-turn charge moves in Doubles

server/roomlogs.ts, server/rooms.ts
This removes any extra unnecessary newlines at the end of each message sent to each client, and will always handle all messages assigned to the buffer properly.  (saving bandwidth = yay) Tagging @Zarel because he's was fine with this
=> Make broadcastBuffer an array

server/chat-plugins/chatlog.ts
Changes: 
- ripgrep now uses childprocess#exec, for more precise error handling and to prevent an unidentified bug that made execFile fail. 
- ripgrep supports searching for multiple terms 
- ripgrep supports searching a specific month.
- argument handling is now handled based on regex.exec, using `room: targetRoom`, `limit: number` etc to retrieve the arguments.
- also doesn't reverse the results like it previously did.
=> Chatlog: Improve search

server/chat-commands/room-settings.ts
Currently it just checks if they can rename the room. This intentionally allows users with mute perms to rename so that both the host and gstaff can, in case the user names it something that also bypasses the filter.
=> Fix /renamegroupchat's permission checking

server/chat-plugins/lottery.ts
Before [from this bug report](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8474970)
After:
=> Fix /lottery participants from escaping container

server/chat-commands/room-settings.ts, server/rooms.ts
This allows you to create groupchats again which #6965 entirely broke, @mia-pi-git i suggest you test your code thoroughly in the future because it's apparent you do not, and also patches renaming rooms to no name, for the second time since I already fixed this prior. Again mia, please test your code thoroughly.
=> Fix renaming groupchats and groupchat creation

server/chat-plugins/chatlog.ts
Ripgrep doesn't debug well, given the only error it gives is `` Error: Command failed``, which it can throw for legit reasons like no results. Given that, the best solution is to handle it like modlog and just return an empty result array. 
It also checks `e.stdout` since sometimes it errors but still stores the results there. 
If anyone has any better ideas, i'm open, but given the awful nature of child_process.execFile's errors, i think this is the best handling.
=> Searchlog: fix crash

server/chat-commands/room-settings.ts
We already have an off button that's hardcoded.
=> Room Settings: Don't display ' ' as a modchat option

server/chat.ts
See https://www.smogon.com/forums/threads/allow-images-displayed-with-show-to-be-hidden-by-hidetext-and-similar-commands.3668239/. Should also be useful to make some other commands (see: /ds, etc) that are really spammy, hidetextable.
=> Chat: Make broadcasted sendReplyBoxes hidetextable

config/formats.ts
There's currently an issue in validation where sets will not validate unless the Pokemon has a nickname, and since locked users can't nickname Pokemon, they're unable to play the format.
nicknames get reassigned later in the validation process, so this is just to make the validator be quiet.
=> Inheritance: Fix validation issue

server/chat-commands/room-settings.ts, server/chat.ts, server/global-types.ts, server/user-groups.ts
Reported by randbats roomstaff. Currently, this doesn't check sub command objects, eg /roomevents.
This fixes that.
=> Support per-command permissions for sub-commands

server/chat-commands/info.ts
This was requested in Staff room a few days back but I forgot about it until now.
=> Add short alias for /sharedbattles

config/config-example.js, server/chat-commands/core.ts, server/chat-commands/room-settings.ts, server/chat.ts, server/global-types.ts, server/rooms.ts, server/user-groups.ts, server/users.ts
This ~~allows global staff to set modchat up to % in battles, and~~ allows sysops to bypass a few permissions checks that they previously weren't able to.
=> Remove User#authAtLeast and add more sysop bypasses

server/room-battle.ts, sim/global-types.ts
This allows formats to specify a different ladder than their own, for their rated battles to go on.
=> Support custom ladders

.gitignore, lib/fs.ts, server/chat-plugins/modlog-viewer.ts, server/chat.ts, server/index.ts, server/modlog.ts, server/roomlogs.ts, server/rooms.ts, test/server/modlog.js
This will make it easier to implement changes to modlog, such as #7074 and #6469.
I'm not sure if battlesearch should stay with the modlog. I find it pretty illogical to group them together in the same file, since they do fairly different things, but it would reduce the number of subprocesses (and they do both search logs, although by that logic you could argue for putting `/searchlog` in modlog.ts as well).
=> Refactor Modlog into one file

config/formats.ts
This reverts commit 79dd42d955a4ec835c37c89eb613bc0645e161da.
The suspect system doesn't work.
=> Revert "Update LC suspect notice for new custom ladder (#7157)"

data/mods/gen4/conditions.ts, data/mods/gen4/moves.ts, sim/pokemon.ts, test/sim/moves/camouflage.js
Custom behavior for Gen 5 was being inherited by 3-4. I also bothered to test to make sure Camouflage really does change the user to be Ground-type in Gen 5 Link Battles on cart and it does, which is really stupid. It's Normal-type in Gen 4 and 6-7.
=> Gen 3-4: Fix Camouflage to change to Normal-type

server/chat-commands/room-settings.ts, server/user-groups.ts
Also prevents setting mod(chat|join) below regular user, as well as things like this.
=> Fix Auth#isAuthLevel

server/chat-commands/room-settings.ts
We shouldn't be checking `Auth#hasPermission` if the permission isn't a room or global permission, which I didn't understand in my previous bugfix.
=> Roomsettings: Fix bug with single-command permissions

data/formats-data.ts
https://www.smogon.com/forums/threads/np-ru-stage-2-lights-out-linoone-sharpedo-and-zoroark-banned.3666733/page-4#post-8562763
=> Move Linoone, Sharpedo, and Zoroark to RUBL

.github/workflows/test.yml, README.md, lib/fs.ts, package.json, test/server/modlog.js
While it's certainly possible to implement a `FS#rmdir` method, removing directories on Node versions <12 is rather clunky given the minute idiosyncrasies of different operating systems and Node versions. Since PS! doesn't really need to remove directories, I think simply removing all the files within the directory is a reasonable solution for this usecase.
=> Fix modlog tests on Windows

test/server/modlog.js
https://github.com/smogon/pokemon-showdown/pull/7187 ended up not actually fixing the associated test crash on Windows, so skipping the test for now since I've made Annika try to fix a bug on a system Annika doesn't own and it's not worth the effort at this point.
=> Skip failing modlog test

server/chat-plugins/hosts.ts, server/ip-tools.ts
We need to actually remove ranges that widen is replacing.
(This requires an IPTools hotpatch as well as chat.)
=> Hosts: Fix bug with /ipranges widen

server/chat-commands/core.ts, sim/dex.ts
There was an extraneous ``<`` that cut off the first line, when using !showteam.
Additionally, this now formats natures better.
=> /showteam: Fix bugs

server/rooms.ts
Rooms.global.battleCount considers both public and private battles,
but getBattles already passes over isPrivate battles, meaning if a
non-trivial number of battles are private, battleCount is much
larger than the number of public battles and all battles will be
skipped resulting in an empty "Watch Battles" tab for "(all
formats)".
=> Fix getBattles skip behavior wrt private rooms

server/chat-commands/admin.ts, server/chat-plugins/modlog-viewer.ts, server/modlog.ts
Hotpatching modlog "properly" (i.e. reinitializing each stream) turns out to be far too slow in practice, causing the main server to lock up for >30 seconds. This will hopefully be quicker, albeit hackier.
=> Modlog: Fix exact searches and improve hotpatching

server/chat-plugins/help.ts, server/chat-plugins/room-faqs.ts, test/server/chat-plugins/help.js
Previously this would write state whenever a faq was changed anywhere - an oversight on my part. 
now this checks to ensure that the roomfaq object has the faq - if not, it deletes the data for that faq and writes state. 
This DOES complicate testing, but the way i went with is asserting that nofswriting is off, since that (mostly) eliminates the point of the step with it on,
=> Help: Only write state when relevant to the room

server/chat.ts
Changes this makes:
a) Lets people use `/pm` instead of `/msg` in buttons, which is a lot more intuitive.
b) Permits the author of the HTML to direct messages towards themselves via buttons (useful for when Bots create subroomgroupchats and become #, or if they suddenly want hugs from random people).
(Didn't add /w since line limits are worse than horizontally sliced bread)
=> Slight HTML Button Improvements

server/rooms.ts
This was an extraneous `</div>` tag which resulted in only the first pending media request to show inside of the `<details>` tag.
=> Fix HTML error with pending media requests

server/rooms.ts
At the moment, the staff intro and pending requests only appear on manual joins, not on autojoin. This is because `user.can('mute', null, this)` results false when it is run since the user is not yet logged in. This change creates a new method for generating the staff intro that is run after the user is fully logged in. It also modifies the original `getIntroMessage` so that the staff intro and pending requests still appear on manual joins.
=> Show staff intro + pending requests on autojoin

server/chat-plugins/chat-monitor.ts, server/punishments.ts
This PR:
- Writes the Pokémon nickname and slur evaded to modlog
- Ensures an already-locked won't be autolocked (this also prevents Staff room for being spammed with FilterEvasionMonitor messages whenever a troll tries to validate a team with awful names)>
=> Improve Pokémon nickname filter and autolocks

server/users.ts
This should fix the bug where usernames remain grey on the client after reloading.
=> Properly inform client of statusType changes

server/chat.ts
As per [this bug report](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8517371), the help message directs you to type `/back` when marked as idle/away, when really, `/back` is only necessary for the Busy status.
=> Fix extraneous error message in /back

server/chat-plugins/announcements.ts, server/chat-plugins/poll.ts, server/chat-plugins/trivia.ts
Now that we actually use user languages we shouldn't be translating moderator messages. We could translate them with the room language, I suppose, but that seems rather overkill for a rather narrow case (moderators of language rooms who don't know enough English to understand these short strings).
=> Chat plugins: Use the room language to translate mod actions

config/formats.ts
Series 6 bans 16 different Pokemon (17 if you count Indeedee as two mons).
The Immortal and I discussed this on Discord. VGC without bans still needs to exist due to several online tournaments using Series 5. Series 6 VGC will be implemented separately as Battle Stadium Doubles, which is still accurate while giving players the option to ladder in either format (Series 6 will only last 2 months). Battle Stadium Singles is also updated but will just use the Series 6 banlist and not have a separate ladder.
I'm not sure if it would be useful to clarify in Battle Stadium Doubles that this is Series 6 somehow. iirc we don't typically include the series information.
=> Implement Battle Stadium Singles/Doubles Series 6

server/chat-commands/moderation.ts
#7266 fixed the behavior of `/unrangelock`, but introduced another bug. As far as I can tell, `/unlockip` should unlock all  users locked by name on the IP, while `/unrangelock` should unlock all users locked by a rangelock on the IP range.
=> Fix /unlockip

server/chat.ts
small QOL thing, but just erroring with `this.cmd` can be slightly misleading sometimes. 
(not sure if this was intentional, but it seemed off)
=> Chat: Show the full command in nonexistent errors

server/ladders.ts
This will prevent the staff room from getting spammed when people do things like nickname their Pokémon 10,000 n-slurs in a row.
=> Filter Pokémon nicknames after team validation

server/chat-plugins/help.ts
This causes issues for other servers to default to help if it doesn't exist. Not worth providing. If you want it, it can just be configured.
=> Help: Disable if a room is not set in Config

server/chat-plugins/chatlog.ts
Apparently this wasn't trimmed, so when the date was sliced later on, it fucked with the handling.
Also now has a safety against when you search logs for a month that doesn't have logs.
=> Searchlogs: Fix crash in date parsing

server/chat-plugins/chatlog.ts
People with HTML tags in their usernames can mess with chatlog formatting.
=> Log viewer: Escape usernames

server/users.ts, test/server/users.js
This fixes the issue where global moderators/admins can't view the IPs of offline users with `/ip`. It should probably be monkeypatched (unless we want to restart).
=> Users: Fix bug with IP handling

data/moves.ts
Instruct fails for all Max moves (similarly to Z-Moves), though its current description does not reflect this.
=> Update Instruct's longdesc

server/chat-plugins/modlog-viewer.ts, server/modlog.ts
The issue that caused them to log to help room was that when checking shared modlogs, it splits the ID by ``-``. As a result, it got the id `help`, and would write to `modlog_help.txt`. This PR renames shared modlog files to ``[id]-rooms``, so that it doesn't conflict with existing rooms.
Likewise, i've also written a conversion script (https://gist.github.com/mia-pi-git/20b4f501b99445ad592f521776fbf718) to move old ticket entries from the help modlog to the new modlog file. This can also be hotpatchable, someone just needs to force helpticket rooms to set up their modlogStreams again (i can also add that into the script, if that's easier?).
=> Helptickets: Stop modlogging to Help room

server/chat-commands/moderation.ts
`/forceweekroomban` does not exist so having it in an error is not ideal. I'm adding `/wb` for consistency since `/roomban` is abbreviated to `/rb`
=> Weekban: Fix error message and add /wb alias

server/user-groups.ts
as far as I can tell, all uses of `checkCan` will provide `cmd`, so setting a group permission to change perms across lots of commands doesn't work at all.
=> Auth: Fix changing a group's permission for commands

server/chat-plugins/chat-monitor.ts
Currently, this is only done for slurs, which has led to globals unhappy about porn sites being mentioned in Staff room.
=> Chatfilters: Spoiler autolocking banwords

data/mods/letsgo/rulesets.ts, data/mods/letsgo/scripts.ts, data/rulesets.ts, sim/dex.ts, sim/pokemon.ts
`getAwakeningValues` used to be used by Let's Go's `rulesets.ts` to check that AVs were capped at 200. This was moved to `sim/team-validator.ts` by PR #5840 so now all that remains is a thick wrapper around `set.evs`, which can simply be removed, conveniently additionally increasing type safety.
=> Remove outdated getAwakeningValues function

data/mods/gen2/moves.ts, data/mods/gen3/moves.ts, data/mods/gen4/moves.ts
Followup to PR #6292, the simplification means that the `-fail` and `[still]` actions are automatically invoked and this no longer needs to be done manually, indeed it causes duplication as pointed out [here](https://www.smogon.com/forums/posts/8591799).
=> Remove duplicate fail message from Encore

server/chat.ts
Not the most elegant solution, but if it works it works.
Fixes tags like `<br/>` being banned because the tag name end gets detected via spaces, leaving tagName to be `br/`, which isn't a valid tag name
=> Don't ban autoclose tags without spaces from html

server/chat-plugins/thing-of-the-day.ts
`user.previousIDs` did not contain the user's _current_ ID, so removing nominations from them wouldn't work, as it checks the property that `user.previousIDs.slice()` was assigned to. This `concat`s the current `id` to the `userid` array so it's properly tracked.
=> Thing of the Day: Fix bug in removing users

server/chat-commands/core.ts
Apparently sending an invite to `~` crashes PS. I don't know if this is the ideal way to fix this or if it's better to move the "this message can't be sent" thing, but this should work.
=> Fix crash in /invite

server/chat-commands/core.ts, sim/dex.ts
I'm not sure if it'll ever get used as such, but !showteam is very very close to how VGC Player's Cup works - each side has the other's complete team information, except for stats. This does the following:
- Adds a "hidestats" arg which prevents EVs, IVs, and Nature from printing
- Adds the Gmax forme information if applicable
- Doesn't display the @ if the Pokemon is not holding an item
=> Add hidestats arg to showteam and improve output

data/scripts.ts
Simply replacing these instances with `damage[i]` doesn't work, since `damage[i]` can legally be `undefined` at ths point, typically for status moves, so I just copied the check used for the return value of `getSpreadDamage`.
=> Improve spread damage return value check

server/tournaments/index.ts
The conversion to the conventional commands formatting removed all permissions checks, so now regular users can modify tournaments.
This also introduced a bug where the args order for /tour settype was switched around.
=> Tournaments: Check permissions properly

server/users.ts
Currently, users are getting their status set to Idle when they log back in after a time of being logged out. According to the comment in `users.ts`, we consider logging in enough activity to remove Idle status, but this was not borne out in the code.
=> Remove Idle status on login

server/chat-plugins/chat-monitor.ts
This command allows global bots to avoid triggering any of the filters with things like randomly generated strings in chat games.
=> Restore global bot permissions for /filters list

server/chat-plugins/modlog-viewer.ts
Various improvements requested by Dawoblefet. 
It now searches by month, not day, has a back button, supports searching for 2 users, and the formats list is reformatted.
Screenshots: multisearch (https://prnt.sc/uj8ih4), singlesearch (https://prnt.sc/uj8ioq)
=> Battlesearch: Support searching for multiple users and searching months

server/chat-commands/moderation.ts, server/chat-plugins/chat-monitor.ts, server/chat.ts, server/monitor.ts, server/punishments.ts
This is so they don't get cleared on hotpatch. 
Monkeypatch (NECESSARY, OR BAD THINGS CRASH) 
```ts
>> Punishments.namefilterwhitelist = Chat.namefilterwhitelist;
Punishments.saveNameWhitelist();
Monitor.forceRenames = Chat.forceRenames;
delete Chat.forceRenames;
delete Chat.namefilterwhitelist;
```
=> Chat: Move forcerename tracking to Monitor and Punishments

data/abilities.ts, data/conditions.ts, data/mods/gen1/conditions.ts, data/mods/gen1/scripts.ts, data/mods/gen5/conditions.ts, data/mods/gen6/random-teams.ts, data/mods/gennext/abilities.ts, data/mods/gennext/moves.ts, data/mods/stadium/scripts.ts, data/moves.ts, data/rulesets.ts, data/scripts.ts, sim/battle-queue.ts, sim/battle.ts, sim/dex.ts, sim/field.ts, sim/global-types.ts, sim/pokemon.ts, sim/side.ts, sim/state.ts
... or just remove it if it's become unnecessary, of course.
I was also considering changing second parameter to `calcRecoilDamage` to be the recoil rather than the move. Currently most of the implementations assert that the recoil exists, since while the callers all know that the recoil is a tuple, that information is lost to the callee, and I have copied that style to the last place that was using a `@ts-ignore`. If instead the parameter was just the recoil tuple itself, no assertion would be necessary at all.
=> Replace @ts-ignore with type assertions or other less unsafe constructs

server/chat-commands/info.ts
The upshot is that if you use, say, the `/om cup` command, this finds `gen8350cup` as a single near match (because it thinks that this is an om called "cup" in generation 8350...), but fails to display all of the details correctly.
I tried to clarify by inlining the `format` variable but of course that results in a line of code longer than 120 characters...
=> Fix missing variable renames after PR #6670

server/chat-plugins/trivia.ts
@Zarel and @sparkychildcharlie, I think this is what you were proposing? It makes `Room#mastermindGame` track the Mastermind game, and uses `Room#game` for the rounds and finals. I also made `RoomGamePlayer`s independent of the game since all the state we really need is the room ID.
=> Trivia: Use Room#subGame for Mastermind

server/chat-commands/moderation.ts
This mainly applies to modnotes in help tickets and battles, as well as global staff modnoting in groupchats (in case of misbehavior in a groupchat).
=> Make modnotes global in rooms with shared modlogs

data/pokedex.ts
https://bulbapedia.bulbagarden.net/wiki/Dubious_Disc
https://www.serebii.net/itemdex/dubiousdisc.shtml
It's already spelled correctly in data/items.ts and data/text/items.ts.
=> Fix typo in Dubious Disc

server/chat-plugins/helptickets.ts
We should only be sending notifications through Staff room rather than the page.
=> Helptickets: Fix double notification

server/user-groups.ts
This seemed a better solution than hardcoding `!['^', ' '].includes(this.get(userid))`. Bug happens because they have a rank in the auth table (which it checks) other than `+`, `' '`, and we didn't account for that implementing whitelist. 
This needs a pretty simple monkeypatch in order to take affect (no, it won't crash things, but giving trusted wrongly is a bit of an issue): 
```ts
>> Users.Auth.prototype.isStaff = function(userid) {
return this.has(userid) && Users.Auth.atLeast(this.get(userid), '%');
}
```
=> Auth: Make whitelist/prizewinner not give trusted status

lib/STREAMS.md, lib/streams.ts, server/chat-plugins/chatlog.ts, server/modlog.ts
This adds new functions `stream.byChunk(bytes)`, `stream.byLine()` etc which parse a `ReadStream` into an `ObjectReadStream<string>` which can then be consumed with for-await.
Fixes #7195
=> Introduce chunk readers for ReadStream

build, server/chat-plugins/suspect-tests.ts, sim/battle.ts
A chat-plugin to allow suspect test notices to be added and removed via a command rather than modifying the formats file.
Date isn't necessary per say but I included it for the purpose of being able to see suspect deadlines in `/suspects`.
Shoutout Annika for solving some of my TS issues.
=> Add suspect tests plugin

server/rooms.ts
`room.settings.autojoin` and `room.settings.staffAutojoin` are now merged.
Staff autojoin rooms are now simply regular autojoin rooms with a modjoin setting. You simply autojoin all autojoin modjoin rooms that you're allowed to join.
Fixes #7413
=> Refactor staffAutojoin

server/chat-plugins/modlog-viewer.ts, server/modlog.ts
This moves `parseModlog` into the child process so that it doesn't lag the main process. Also I fixed a crash I saw in Dev room.
=> Modlog: Parse entries in the child process

server/chat-plugins/modlog-viewer.ts
Some requests from gstaff: 
- Param detection assumes that the first argument is a roomid since that's how it used to work
- Moves the  `<- Current server time` indicator back up to the top
=> Modlog viewer: Improve UI

server/chat-plugins/modlog-viewer.ts
It looks like #7436 didn't do this which is causing problems when trying to view older results.
=> Modlog viewer: Update regex for new modlog syntax

server/chat-commands/admin.ts, server/chat-plugins/helptickets.ts, server/chat.ts
This provides a new way to persist chat plugin data across hotpatches: `Chat.oldPlugins`.
In a plugin, you can now do:
```
export const cache = Chat.oldPlugins.pluginname?.cache || {};
```
to create a cache that will persist across hotpatches.
=> Introduce Chat.oldPlugins

server/chat-plugins/scavengers.ts
Two minor changes for the Scavengers plugin:
- In /viewhunt, change the ``/`` for alts to a ``;`` to allow easier copying.
- For /edithunt, allow commas in answers.
=> Scavengers: Improve /edithunt

server/chat-commands/info.ts, server/chat-plugins/announcements.ts, server/chat.ts
This does not change the parameters passed to individual filters, in the name of backwards compatibility with old filters.
=> Use attributes of CommandContext in Chat.filter

server/chat-plugins/chatlog.ts
Minor thing, but since battlesearch has this behavior and chatlog searches are slow, this is useful to have.
Also adds some aliases to /searchlogs.
=> Chatlog: Notify the user that a search is running

server/chat.ts
iframes don't work in /htmlbox etc. right now anyway and I don't think there's a good reason to allow it.
Screenshot of current behavior:
=> Chat#checkHTML: Ban <iframe> tags

server/chat-commands/core.ts
I'm not sure if a regex is the right way to do this but it seems more compact than listing every possible variation, and I figure that we care more about readability than performance here.
=> Fix /help for room promotion commands

test/sim/team-validator.js
Adds 3 failing validator tests related to events:
1. Evolutions of Shiny-locked event Pokemon should not be able to be Shiny (e.g. Urshifu, Cosmoem)
2. Unreleased G-Max Pokemon should not be allowed (Melmetal)
3. Events should not have access to past-generation moves (e.g. Shiny Zeraora is Gen 8-only, so it can't have Knock Off since it only gets that in Gen 7)
=> Add skipped failing event validator tests

server/chat-plugins/othermetas.ts
Suggested in https://www.smogon.com/forums/threads/stone-pokemon-name-instead-of-stone-stone-name.3657629/#post-8620547
Behaviour:
Displays the stone for Pokemon with a single Mega Evolution (Beedrill, Bee, Beedrill-Mega)
Displays all stones if there are multiple Mega Evolutions (Mewtwo, Mewtwo-Mega)
Displays the relevant stone if a particular Mega Evolution is specified (Mewtwo-Mega-X)
Displays Dragon Ascent for Rayquaza-Mega (Rayquaza, Ray, Rayquaza-Mega)
All warnings have been retained.
=> Allow Pokemon names as arguments in /stone

data/moves.ts
Reported [here](https://www.smogon.com/forums/posts/8537785).
Additionally, Jungle Healing never says "[POKEMON]'s HP is full", it just says "But it failed!", so manually calling `this.heal()` fixes both issues. See @DaWoblefet's [video](https://youtu.be/q54mP60YC3c?t=378).
=> Fix Jungle Healing when target's HP is full

server/chat.ts
Although I was unable to replicate the crash about translating to a nonexistent language locally, this should fix it (and is a good change regardless).
=> Chat: Propagate promises for loading translations

server/chat-plugins/modlog-viewer.ts
- prevents non-global roomstaff from seeing IPs in modnotes or legacy modlogs
- makes modnoted IP addresses link to whatismyipaddress.com
=> Modlog viewer: Improve IP handling

data/mods/gen1/formats-data.ts
This removes Harden from Kakuna and Dragon Rage from Magikarp. 
Harden is incompatible with Poison Sting and String Shot, as Kakuna doesn't learn it upon evolving like Metapod. 
Source: https://www.smogon.com/forums/threads/random-battles.3526564/post-8577809
Magikarp only gets Dragon Rage via a Japanese event, and since international RBY mechanics are used, it's impossible for this to be used. 
As far as I know, these are the only issues.
=> Remove illegal moves from RBY Random Battles

data/mods/gen3/scripts.ts
In ADV, spread moves that hit exactly two opponents have a spread modifier of 0.5x instead of 0.75x. Moves that have more than two targets (Explosion, Earthquake, etc.) don't get affected by spread modification at all.
=> Fix spread move mechanics in ADV Doubles

data/mods/stadium/moves.ts
Struggle should affect Ghost-types in Stadium, designed to avoid infinite battles. Thanks to Kris for helping me figure out what to do...
Source: https://www.smogon.com/forums/threads/stadium-format-is-now-available-on-ps.3526616/post-8517229
I'm not necessarily a _programmer_, but if I can help the Stadium sim improve in some way, that's good enough for me.
=> Fix Stadium Mechanics (Struggle VS Ghost-types)

server/chat-plugins/youtube.ts
=> Youtube: Persist interval time

sim/team-validator.ts, test/sim/team-validator.js
I believe this only affects the hardcode on Entei/Suicune/Raikou. What I did is functional but not sure if I did it correctly and/or if there's other checks here that should be freed with the release of Ability Patch.
=> Validator: Allow Hidden Ability Entei/Raikou/Suicune in Gen 8 natively

CODEOWNERS, config/config-example.js, server/chat-commands/info.ts, server/chat-plugins/the-studio.ts, server/chat-plugins/youtube.ts, server/chat.ts
I have a key generated locally, this just won't be ready until #7536 is merged
=> Add The Studio's chat plugin

data/mods/letsgo/scripts.ts, sim/battle.ts, sim/dex.ts, sim/pokemon.ts
Latest research shows that in Pure Hackmons, Eternatus-Eternamax can have enough EVs such that its stat can overflow when calculating its nature. If with a neutral nature it would have 596 in a stat, the nature adjustment calculates 596 * 110 / 100, however this is a 16-bit calculation and the 596 * 110 overflows. (Its stat can actually go slightly higer than 596 with predictable results.)
=> Calculate natures with 16-bit truncation

data/abilities.ts
As [researched](https://www.smogon.com/forums/posts/8637512) by @DaWoblefet, the boosts should not activate when the stat is already maxed out.
=> Ignore As One boosts when already maxed out

data/mods/gen2/learnsets.ts, sim/global-types.ts
In reference to this, which I assume can be closed now: https://github.com/smogon/pokemon-showdown/pull/7516
Zarel asked for a PR marking the JP Events so he can take it from there? I've marked it with comments as so: "//JP Event". A simple Ctrl+F should have them pop up.
=> Ban Japanese Gen 1 Events in Int Formats: Part 2

data/moves.ts
As researched by Zaggyo, Eerie Spell's PP deduction is a secondary effect for the purposes of Sheer Force and Shield Dust.
=> Make Eerie Spell's secondary effect secondary

server/chat-commands/admin.ts
After this change running a command like this:
```
/eval new Promise(resolve => { setTimeout(() => resolve(42), 1000) })
```
will print
```
<< Promise pending
```
before saying
```
<< Promise -> 42
```
This will make it clearer that the promise is resolving.
=> Indicate pending promises in /eval

sim/dex.ts
`/challenge [Gen 8] OU @@@ +Reshiram` failed earlier, since the rule wasn't trimmed.
Also going to add the fix for chat only including the first rule.
=> Fix Custom Rules Error

server/chat-commands/core.ts
`/forcerename` and other global punishments do this.
=> Make /clearstatus log to Staff room

server/chat.ts
This makes non-broadcasted reply infoboxes come from user ``~`` (This is questionable - shouldn't it be & by now since the beautiful admin sign ~ is replaced with the super ugly &) instead of the user themselves.  This makes it so that un-broadcasted information searches won't be hidden by any /hidetext, hidelines command.  This is rather important in game rooms that rely on /ds for searches.  If someone accidentally leaks something that might be an answer and the room's staff has to quickly suppress their text, losing progress of all their previous searches would be detrimental to their progress in the current game.
=> sendReplyBox: Fix interaction with hidelines

server/chat-plugins/helptickets.ts
As per [this suggestion](https://www.smogon.com/forums/threads/staff-suggestions-bugs.3514540/page-17#post-8634198).
=> Helptickets: Add button for the reporter's modlog

server/chat-plugins/datasearch.ts
Happened because G-Max moves had move.isNonstandard as 'Gigantamax'.
=> Fix G-Max moves not showing up in /ms Gmax

config/formats.ts
Banned Mawile-Mega and Power Construct; unbanned Zygarde-10% and Tapu Lele
=> National Dex Monotype: New bans and unbans

config/config-example.js
This allows users to be banned from modjoined autojoined rooms (which is useful for keeping global bots out of Staff room when some of their owners aren't global staff).
=> Config: Move Bot rank below Driver 

server/user-groups.ts
This fixes an issue which caused bots to be untrusted after moving bot rank below driver rank.
=> Consider bots to be staff

server/chat-plugins/chatlog.ts
.......apparently the ``['']`` doesn't play nice with ripgrep.
Sigh.
=> Topusers: Fix arg handling

config/formats.ts
Also removed `onAfterMega` as it's not relevant in Gen 8.
=> Don't reveal Illusion in Camomons

server/chat-formatter.ts
This fixes a bug which caused lines like `rooms.js: does room stuff` to be incorrectly linked.
=> Require a digit to follow port number in links

server/chat-commands/admin.ts
Hotpatch notifications in Upper Staff aren't very useful considering Staff already gets those.
=> Remove hotpatch notifications from Upper Staff

server/chat-commands/room-settings.ts, server/room-battle.ts, server/room-game.ts, server/rooms.ts
Third time's the charm? The issue was that `RoomGame#roomid` wasn't being updated. I fixed that, and it seems to work fine on localhost (I believe that the replay server already handles replay uploads from battles with passwords, so I didn't put in the extra work to test this on my replay server, but I can do that if we're unsure about the replay server functionality).
=> Fix renaming battle rooms

server/chat-plugins/chatlog.ts
This makes ripgrep use PCRE2 for searching logs only when necessary.
=> Chatlog: Automatically determine regex engine

server/chat-plugins/chatlog.ts
At the moment, this uses the full regex, which is messy and doesn't work right.
=> Chatlog: Handle next result buttons properly

data/items.ts
Stupid error in PR #6931 where I inserted the `priority <= 0 && ` without bracketing the existing `||` conditions first (confusing someone into helpfully bracketing them the wrong way). Since the only other ways to get a positive fractional priority is either with Quick Claw (and therefore not Custap Berry) or Quick Draw (and therefore not Gluttony), this doesn't affect normal play, but some OMs might misbehave, if anyone wanted to combine these for some reason.
=> Fix custap berry with gluttony

server/chat-commands/info.ts, server/chat-commands/room-settings.ts, server/rooms.ts
/permissions means this isn't necessary. 
Relevant monkeypatch to easily change settings:
```ts
const changed = []; 
for (const curRoom of Rooms.rooms.values()) {
let s = curRoom.settings.showEnabled;
if (s) {
if (s === true) s = 'whitelist';
if (!curRoom.settings.permissions) curRoom.settings.permissions = {};
curRoom.settings.permissions['/show'] = s;
changed.push(`${curRoom.title}: ${s}`);
curRoom.saveSettings();
}
}
changed
```
=> Deprecate /showmedia

server/chat-plugins/helptickets.ts
Nitpick. addModAction means basically nothing since the room is deleted immediately.
=> Helptickets: Use globalModAction for /ht ban

server/rooms.ts
This is causing the /roomban crash.
Relevant monkeypatch: 
```ts
>> Rooms.GameRoom.prototype.makePublic = function() {
this.settings.isPrivate = false;
if (!this.roomid.endsWith('pw')) return true;
const {id} = this.getReplayData();
this.rename(this.title, `battle-${id}`);
}
=> Rooms: Properly rename private battle rooms

server/chat-commands/info.ts
Apparently a lot of people make the mistake of `/rules [room]` giving the rules for the given room, and of `/rules format` giving rules for that format. So, couldn't hurt to make that work.
=> Info: Make /rules account for other possible use-cases

data/mods/gen1/moves.ts, data/mods/stadium/moves.ts
This implements the Psywave Desync Patch from the tiering decision found [here](https://www.smogon.com/forums/threads/rby-psywave-imperfect-dvs-and-thawing-desync-glitches.3668900/)
For details on how the desync works, go [here](https://www.youtube.com/watch?v=5KmTCdnWzVI)
[Here is a replay from the RBY 2k20 PS Server showing the implementation in action.](https://replay.pokemonshowdown.com/rby-gen1customgame-897)
I'm by no means a _good_ programmer, nor do I consider myself one, so I think my code may be a bit suboptimal.
=> Fix Gen 1 Psywave mechanics

data/random-teams.ts
Unfortunately my crash log doesn't actually include the seed used to generate the invalid team for some reason, and the battle had already expired so I couldn't check it directly, so I can't test this...
=> Fix Gastrodon-East in Challenge Cup

data/abilities.ts, data/mods/gen6/moves.ts, data/moves.ts, data/scripts.ts, sim/dex-moves.ts
As researched by @DaWoblefet, Diamond Storm boosts only apply once per move, like Clangorous Soulblaze. To get this to work correctly:
- Moved boost from `secondary` to `selfBoost` except in Gen 6
- Added support for `chance` on `selfBoost`, including Serene Grace and Fire+Water Pledge combo rainbow
- Sheer Force deletes the `selfBoost` if the move also has secondaries (dummy secondary added to Diamond Storm to enable this)
=> Properly update Diamond Storm boosts for Gen 7

data/mods/gen1/moves.ts
This was a minor mistake when I was writing this thing up. Since Desync Clause isn't something you replicate in RBY, it is more accurate to describe it as a Mod, in line with the ADV Switch Priority Clause Mod.
=> Rename "Desync Clause" to "Desync Clause Mod"

data/formats-data.ts, data/mods/gen2/formats-data.ts, data/mods/gen2/random-teams.ts, data/random-teams.ts
Gen 2: 
fix various Pokemon getting mono-sleep talk due to various reasons (Curse line is meant to allow both curse resttalk piloswine and resttalk STABs piloswine while fixing mono-sleeptalk)
fix ice beam persian (illegal)
remove quick attack from dodrio to force stabs
improve Umbreon and Misdreavus's sets
Doubles:
Fix mono-poltergeist Gourgeist and Gourgeist-Small
Howl Zamazenta-Crowned over Coaching
Charm Eldegoss
Fix Life Orb Archeops
Remove Blaze Charizard
TI, can you check this one out:
Swords Dance keeps getting rejected on Gen 2 Seaking and Beedrill. This makes Sub+Agility exist. This shouldn't exist. Tried a few ways to fix it. Didn't work.
=> Update Gen 2/Gen 8 Doubles Random Battle

config/formats.ts, data/mods/gen1/rulesets.ts, data/mods/stadium/rulesets.ts, data/rulesets.ts, test/sim/moves/counter.js
This is to be added to the "Standard" ruleset, so that "Desync Clause Mod" will show up when you start an RBY game on PS. I'll add this to the gen1/rulesets.ts "Standard" and any Gen 1 formats that don't use it, which should cover everything. 
This isn't meant to actually _do_ anything on its own, only note that the "mod" exists and will trigger in certain scenarios. 
I've written the rule description in a way that it will need updating whenever another desync is patched. There's still quite a few of these, though, and I believe the RBY Council still needs to go over a bunch. This includes Bide and Mirror Move + Partial Trapping. There's also some game crashes involving specific defensive stats but those are different. 
While doing this, I noticed that Stadium OU was removing Smogon Sleep …
=> Gen 1: Announce Desync Clause Mod, fix Stadium Sleep Clause

server/chat-commands/moderation.ts
We shouldn't be suppressing errors caught here that are really errors. Caused an obscure bug this morning that I had to hunt down.
=> Throw unrelated errors caught in runPromote

data/conditions.ts, data/scripts.ts
Based on new research, multi-hit distribution is now known to be 35-35-15-15 rather than 1/3-1/3-1/6-1/6, and confusion is now known to be 33/100 rather than 1/3.
See videos:
https://www.youtube.com/watch?v=Il1sMnFUh9s
https://www.youtube.com/watch?v=TMtpLva4_qM
I think the way I corrected multi-hit move distribution is accurate, but it looks kind of dumb; not sure if there's a preferable way to do it.
=> Correct multi-hit distribution and confusion odds

data/scripts.ts
Reported [here](https://www.smogon.com/forums/posts/7995630). This is going to need client-side changes too (both for the [Pokémon's Magic Bounce] text and the ability activation animation) but this will simplify the necessary changes (I think the old code had to special-case Magic Bounce and Rebound to achieve this).
=> Magic Bounce and Rebound should not use old protocol messages

sim/battle-queue.ts
Fixes this issue, which was brought to my attention by EB0LA: 
https://replay.pokemonshowdown.com/gen1ou-1226178707-boclvwycxq72syl17qt9a3729l1tprkpw 
https://replay.pokemonshowdown.com/gen1randombattle-1224344866-9ha6ocg38ru2ontlnf0iak467r2nzu0pw (T15)
Thanks to Zarel for helping me figure out what to do ^^;
Attached is a replay featuring me testing the fix on localhost.
[Gen1OU-2020-11-18-plaguevonkarma-karmatest.zip](https://github.com/smogon/pokemon-showdown/files/5560363/Gen1OU-2020-11-18-plaguevonkarma-karmatest.zip)
=> Gen 1: Fix Counter vs Hyper Beam

server/chat-plugins/chat-monitor.ts
https://www.smogon.com/forums/threads/staff-suggestions-bugs.3514540/page-17#post-8642512
(before this change, it was just stopping users that had been forcerenamed from using pokemon nicknames)
=> Filters: Properly stop forcerenamed names from being used

server/tournaments/index.ts
turns out since "inProgressMatch" only sets on 1 of the players the sub room deletions on line 733 only happen if the user it's set to is disqualified. Not sure if the inProgressMatch setting that way intentional or not so i just figured I'd pr this fix and if it's preferred for me to make it so inProgressMatch is set on both players instead of just one i can do that instead.
=> Fix disqualifyUser bug in tournaments

server/punishments.ts
As discussed in PMs with Zarel, this pokes every punishment timer daily, allowing for punishments longer than Node's maximum timeout length to automatically expire.
=> Support automatic expiry for monthlocks

server/chat-plugins/random-battles.ts
There are several Pokemon species for which only the Gmax forme has a random battles/random doubles move pool, and the /randbats and /randdubs commands would report that these Pokemon had no moves unless users specified said Gmax forme.
=> /randombattles: Check Gmax forme for moves

server/chat-plugins/datasearch.ts
Unlike /effectiveness and /coverage, /dexsearch doesn't need to support arbitrary mods, so Thousand Arrows can be hard-coded as the only move to ignore any immunities. Simplifying the check like this was pretty much necessary for me to actually be able to understand how the logic should be structured to accommodate the opposing exceptions for Thousand Arrows and Sheer Cold.
=> /dexsearch: Fix immunity check for Thousand Arrows

data/conditions.ts, sim/side.ts, test/sim/misc/target-resolution.js
Previously, two-turn moves called by another move such as Metronome would target the user’s ally if Ally Switch was used to make the user and its ally trade places on the second turn. This change makes the move correctly choose a random target on the first turn instead of the second and makes the battle engine respect that choice instead of defaulting to what the user’s previous move targeted (when the two-turn move was called by a self-targeting move, this would make the two-turn move target the user which would conveniently be interpreted as a random opponent except when the user and ally traded places).
=> Fix two-turn submoves + Ally Switch in doubles

server/chat-plugins/mafia.ts
- Forceadd allows players who have subbed out or stopped cohosting to re-enter the game. 
- Plurality shifts to the subbed in player if it was on the subbed out player, and the mafia page is updated after the subbed out player is removed from the player list.
- /mafia dt gi/ci/etc gives the rolelists for each.
- Role lists have spaces between each role. 
- The clear button during ideapick phase is fixed.
=> Fix sub player and IDEA mechanics (Mafia)

test/sim/abilities/emergencyexit.js
Apparently my previous Emergency Exit change also fixed what would have been the last skipped Emergency Exit test. However, this also adds a new skipped test for a minor visual bug I don't really know how to fix, which is that when a Pokemon with Wimp Out or Emergency Exit forces another Pokemon out with Dragon Tail or Circle Throw and takes recoil damage that drops it down to less than 50% HP, the ability visibly activates before the target is switched out, though the player controlling the attacker in that case is correctly asked to switch their Pokemon out after the target's replacement is dragged in. The only error is in the message timing.
=> Residual damage Wimp Out timing is correct

.vscode/settings.json
Fixes the error in vscode for the ESLint Plugin:
Error: ENOENT: no such file or directory, open '******/pokemon-showdown/.eslintrc-types.json'
=> Correct eslint.options.configFile for vscode

.gitignore, test/common.js, test/replays/README.md
The intended use for this is to add a `common.saveReplay(battle);` line to tests you want to watch back in the client so you can see why a given assertion might be failing. I don't know enough about the testing suite to figure out how to make it automatically clear out the `replays` folder when `npm test` gets run, but I don't think that's entirely necessary anyway since one might want to compare two replays from different versions of the code.
Now that I think about it, it might be worth automatically storing replays for every applicable test and replacing them all when `npm test` is run to potentially detect regressions by checking for battle logs that have changed even though their assertions all pass. I don't know how to do that either, though.
=> Tests: add a function to save a replay of a battle

server/users.ts
Bots which are staff room bots are currently able to bypass filters, which is bad because they could be used to mail other users slurs.
=> Users: Don't give bots isStaff

data/mods/gen1/moves.ts, data/mods/gen2/moves.ts, data/mods/gen5/moves.ts, data/mods/gen6/moves.ts, data/mods/gen7/moves.ts, data/moves.ts, data/scripts.ts, test/sim/abilities/comatose.js, test/sim/abilities/protean.js, test/sim/moves/followme.js, test/sim/moves/gravity.js, test/sim/moves/noretreat.js, test/sim/moves/stompingtantrum.js
Originally, I was just going to add a couple additional Protean tests on The Immortal's recommendation. Thanks to additional [USUM research](https://pastebin.com/bDtvxdT2), we now have a more complete list of what I call in the checks done before move success "[move failure checks part 1](https://docs.google.com/spreadsheets/d/1nn0b7Na9UEoE_NChLLlknV3ERacNeenV4TiMieTpS8U/edit#gid=0)". I just decided to implement it. The only new checks we learned about were:
- Aurora Veil without hail
- Splash / Magnet Rise / Telekinesis used in Gravity - this is why Z-Splash in Gravity boosts to +3 attack but still fails
- Teleport (pre-Gen 8)
- Magnet Rise when the user has Smack Down or Ingrain status
- Sky Drop if the thing it had picked up already fainted
However, Showdown was very inconsistent on …
=> Correct Protean interactions & Gravity-blocked status Z-moves

server/chat-commands/room-settings.ts, server/rooms.ts, server/tournaments/index.ts
This introduces a new function, `setParent`, to handle the details of setting up subrooms.
`roomid`, `parent`, and `subRooms` are now read-only, so they can't be accidentally be set directly rather than through their setters (`rename`, `setParent`, and `clearSubRooms`).
I don't think setters should be used for this, because I think it's important to be clear that `rename` and `setParent` will change a lot of other state and induce network activity.
=> Refactor subroom code

server/chat-commands/moderation.ts
Not really sure why this was done in the first place? Seems to be weird though.
=> Moderation: Properly disallow forcerenamed offline names

server/chat.ts, server/user-groups.ts
Does what it says on the tin. This is much easier now with `this.requireRoom(roomid)`.
=>  Exclude room-specific commands for other rooms in /permissions

server/chat-commands/info.ts
Seems like this should exist, especially because the help for the command shows: `/weakness [type 1]/[type 2] - Provides a type or type combination's resistances, weaknesses, and immunities, ignoring abilities.`
=> Make `/weak type1/type2` work

data/abilities.ts, data/conditions.ts, data/moves.ts, data/scripts.ts, sim/dex-conditions.ts, test/sim/moves/snatch.js
According to the move checks in one of the research threads (and also repeated by @DaWoblefet in PR https://github.com/smogon/pokemon-showdown/pull/7758#issuecomment-738547967), Snatch actually happens just after Protean, so I moved its event to onAnyPrepareHit at lower priority, with fixups so that the `PrepareHit` event can actually cause the move to stop executing. I then made Protean/Libero not run on the Snatched move. After checking with researchers I also ensured that choice locking doesn't happen for Snatched moves (you could be Tricked a choice item in between using Snatch and snatching a move). (I don't know whether it would be worth refactoring `hasBounced` into new property which covers both bounced and snatched moves.)
=> Protean should affect the victim of Snatch rather than the user

data/mods/gen1/random-teams.ts, data/random-teams.ts
The old formula was, to put it lightly, terrible. This new formula, besides actually calculating stats correctly, uses logarithms and compares stats more directly to each other instead of just adding them all up, and thus better representing what the stats actually do.
The other big change this makes is actually taking the IVs, EVs, and nature of the Pokemon being level balanced into account instead of just assuming some average values for all stats. A consequence of this is that Pokemon within a species can now be different levels from each other, with wider variance the higher its average level is. Because of this variance, while the balancing still compares stats against the weakest possible Pokemon, that benchmark is given average IVs and EVs to prevent the level balancing from …
=> CC/HC: Fix level balancing formula

config/formats.ts, data/rulesets.ts
This is useful for custom challenges / room tournaments especially, so you get the whole "only up to 2 legends" rule included if you add Minimal GBU. It also adds the Gen 8 Mythicals / restricted legends.
=> Formats: Move legendary validation to Minimal GBU

data/mods/gen7/factory-sets.json
I used a regex of `("spe"[^}]*("spd"|"spa"|"def"|"atk"|"hp"))|("spd"[^}]*("spa"|"def"|"atk"|"hp"))|("spa"[^}]*("def"|"atk"|"hp"))|("def"[^}]*("atk"|"hp"))|("atk"[^}]*"hp")` to check through this and the bss file for any other wrong sets. I didn't find any, but that just means there aren't any other sets with EVs in the wrong order, which would be an obvious sign of a mistake, as in the case of this Gligar set.
=> Fix Gen 7 UU Gligar Battle Factory EVs

server/tournaments/index.ts
There's currently no check for if a tournament is already being forced public, which I noticed when testing the feature on my bot.
> [06:01:47] (Tournament public battles were turned ON by Unown)
Tournament battles forced public: ON
[06:01:47] (Tournament public battles were turned ON by Unown)
Tournament battles forced public: ON
[06:01:47] (The tournament auto disqualify timer was set to 2 by Unown)
The tournament's automatic disqualify timer has been set to 2 minutes.
[06:01:48] (The tournament auto start timer was set to 3 by Unown)
The tournament will automatically start in 3 minutes.
[06:01:48] (Tournament public battles were turned ON by Unown)
Tournament battles forced public: ON
=> Prevent /tour forcepublic spamming rooms

config/formats.ts
Steel types are all supposed to be banned from Metronome Battle, but a Silvally other than Silvally-Steel could hold a Steel Memory with RKS System to be Steel type while fooling the validator into thinking it's not.
=> Metronome Battle: Ban Steel Memory

data/conditions.ts, test/sim/moves/futuresight.js
Regarding the card:
> Moves that call other moves + Future Sight / Doom Desire cause the target to be itself? Also it seems to be deterministic and always targets opponent's left slot? See replay - DW
I also tested the determinism with a few seeds and it is indeed random.
=> Bug fix: Future Move Failure Message

sim/tools/exhaustive-runner.ts, sim/tools/runner.ts, tools/simulate/index.js
Ran 10000 games of [Gen 8] Multi Hackmons Cup at 6 Pokemon per player (24 pokemon per battle) on the latest version of the server-side multi battle branch, and got 0 crashes.
`[gen8multihackmonscup] P:0 (11/761) I:203 (4/357) A:285 (3/267) M:106 (1/664) = 10000`
Then again, apparently it wasn't actually an exhaustive test because 11 species of Pokemon never got used at all, even though it should have used somewhere between 120,000 and 240,000 individual Pokemon. I can guess those 11 aren't terribly important, though, if they can't appear even in Hackmons Cup.
=> Runners: support 4P (and max games for exhaustive)

data/abilities.ts, data/items.ts, data/mods/gen4/abilities.ts, data/mods/gen4/items.ts, data/mods/gen4/scripts.ts, data/moves.ts, data/scripts.ts, sim/dex-conditions.ts, test/sim/misc/accuracy.js
According to @DaWoblefet's latest research:
- Accuracy modifiers are chained, Gravity first, then Abilities, then Items
- Within each category modifiers execute in usual speed order
- Then, relative boosts are applied, so that 0/-6, +3/-3 and +6/0 have the same effect
- Finally, Micle Berry is applied, if appropriate.
The old code was moved to Gen 4 since the commit that added it says that this is the gen that it was based on.
=> Update accuracy calculation for latest Gen 7 research

server/chat-plugins/responder.ts
Currently if you go into `/autoresponder view` and choose to view autoresponder Stats, it opens a menu where no date is specified and you can choose a date from there. If, however, you press the Refresh button (where no date is specified), it opens a new page called "view-autoresponder-room-stats-" (note the extra hyphen at the end). This is because the "refresh" function is called (on line 458) with [date], which would equal [""]. This is a truthy value, unlike [] and unlike "". This patch changes the conditional statement to look at the first item in the array's truthfulness - it is either an empty string (falsey) or a non-empty string (truthy) - instead of always being truthy.
=> Fix Autoresponder Refresh button bug

.vscode/settings.json
This setting is off by default in vscode, but is commonly enabled at the User-level (it's under "Commonly Used"). Since this repo does not include a standardized formatter, it should be explicitly disabled.
=> Turn off Format On Save in VS Code

server/chat.ts
At the moment, sourceMaps is getting loaded as a language. This is obviously not right, so i replaced the current directory check (which it passes because sourceMaps is a directory) with a simple caps check, since as the comment says none of the languages should have caps in the dir title.
=> Translations: Properly ignore non-translation directories

server/chat-plugins/datasearch.ts
Both are viable recovery moves (from what I saw on smogdex analyses, at least), they should be added to the list of possible recovery moves. I also alphabetized this list on top of adding the new elements.
=> Dexsearch: Add Strength Sap & Jungle Healing to list of recovery moves

data/moves.ts, sim/battle.ts, sim/pokemon.ts, test/sim/moves/pursuit.js
> If Pursuit is used on the same turn a Pokemon uses Volt Switch, U-turn, or Parting Shot (not Baton Pass), the user of the switching move should take damage, then the player should have the option to choose a new Pokemon. Currently, the player is able to select a new Pokemon prior to taking Pursuit damage. See replay. DaWoblefet tested in Gens 5, 6, and 7, and Marty said it's always been this way
=> Bug fix: pursuit switch move interaction

data/moves.ts, data/scripts.ts, sim/pokemon.ts, test/sim/moves/conversion2.js
> Conversion 2 vs. moves that call other moves should use the called move, not the original move. e.g. Sleep Talk -> Thunderbolt should roll Ground, Electric, Grass, or Dragon, NOT Steel, Rock, or Ghost. See [replay ](https://replay.pokemonshowdown.com/gen7customgame-969010846)- DW
Are there any other moves in which the differentiation between `runMove` and `useMove` is significant?
Moves with references to `lastMove`: copycat, disable, eeriespell, encore, gmaxdepletion, grudge, iceball, instruct, mimic, mirrormove, rollout, skech, spite, torment, uproar
=> Bugfix: Conversion 2 Submove Interaction

data/moves.ts, data/scripts.ts, sim/dex-conditions.ts, sim/dex-moves.ts, sim/pokemon.ts, test/sim/moves/metalburst.js
> If a move that calls another move calls Metal Burst it should behave exactly like a normal Metal Burst ie. deal 1.5x damage back to the Pokemon that most recently targeted it. See replay
> 
> Added by scheibo
Question: Smogon states that this move can deal 1 damage if the user of the move did not take damage from an attacker. Does this include all attacks, including failures or non-damaging moves?
=> Bug fix: Metal Burst Submove Interaction

config/formats.ts, data/bss-factory-sets.json, data/mods/gen6/random-teams.ts, data/mods/gen7/random-teams.ts, data/random-teams.ts, sim/global-types.ts, tools/build-utils.js
@ACakeWearingAHat and @cantsay wanted me to try and get this open before the end of the year, so here it is! Relevant smogon thread will be un-deleted once this is merged.
Most copy-paste from last gen's BSS Factory with updated sets, though I've used weighted random sampling (based off viability) in an attempt to create "better" teams, unlike previous Factory implementations (at the request of the vast majority of the playerbase). Thanks to xfix for giving Kala the idea, it only took me 2 years to figure out how to implement it 😅 
It's also my first time properly working with TypeScript so please let me know if I goofed anything up, though `full-test` passes fine on my machine.
=> Add Gen 8 BSS Factory

data/scripts.ts, sim/pokemon.ts, sim/side.ts, test/sim/misc/dynamax.js
To sum up what I've seen from research, it should work like this:
- Taunt and Assault Vest disable Max Guard
- No Max Move can be used if the base move is out of PP
- No other effects can individually disable Max Moves, but if each and every one of a dynamaxed Pokemon's base moves is disabled by way of being out of PP, or by the effects of Encore, Disable, Taunt, Assault Vest, or Belch or Stuff Cheeks disabling themselves, then the Pokemon will be forced to use Struggle anyway
I removed the no-PP hint because I think this is at least the third time it's been wrong, and Metronome Battle players have been seeing that message every time they dynamax at 1 PP left to win Struggle wars, so when that doesn't work anymore you can bet there will be at least irate post in the bugs thread about it.
=> Fix move-disabling mechanics for dynamaxed Pokemon

server/chat-plugins/repeats.ts
`/repeatfaq` works as expected but the private mod actions that it sends depending on whether a repeat is set by minutes or by messages should be swapped.
=> Repeats: Fix private mod actions

data/abilities.ts, data/moves.ts, test/sim/abilities/neutralizinggas.js
As recently mentioned by @DaWoblefet, if Unnerve has not yet activated, then it should activate when Neutralising Gas wears off.
It should also activate when Skill Swapped.
=> Make Unnerve activate after Skill Swap and Neutralising Gas wearing off

data/bss-factory-sets.json
Fixes:
* AV SD Glastrier
* 0 Spe IV Tornadus Therian
* 252 HP Scarf Chandelure
* Babiri Mimikyu has Kee moveset
=> BSSF: Update sets

data/conditions.ts, test/sim/abilities/protean.js
> Protean / Libero should activate on both turns of a charge move like Fly or Phantom Force
=> Bug Fix: Protean/Libero on first of two turn moves

server/chat-commands/admin.ts, server/monitor.ts
The `hotpatchVersions` variable was only used by `requiresForce`.
The `patch` variable no longer provides any benefit over `target`, so I removed it too.
=> Remove variables made redundant by PR #7663

data/abilities.ts, data/text/abilities.ts
Inner Focus, Oblivious, Scrappy, and Own Tempo were not displaying "[Pokemon]'s Attack was not lowered!", instead a generic immunity message. Additionally, I've removed the string for Own Tempo in ``block``; I tried it out on testclient without it and it still displayed "[Pokemon] cannot be confused!" on Confuse Ray so that should be ok, and it fixes the bug with Own Tempo blocking Intimidate using its confusion blocking message.
=> Fix Intimidate failure text

data/mods/gen7/moves.ts, data/moves.ts, sim/dex-conditions.ts, test/sim/moves/grassyterrain.js
The test was a little fragile until I worked out that it was looking for the wrong amount of healing, so Alakazam was still healing first, even though the test thought it wasn't.
=> Grassy Terrain should heal before Leftovers

server/tournaments/index.ts
- Currently, you can replace the old user with a new user that exists, even if they're not in the room, which leads to easy autodq wins.
- Challenges aren't canceled when replacing users, so a replaced user can still be challenging their opponent without knowing it and go into battle without being able to select a team.
=> Tournaments: Fix bugs with replacing users

data/mods/stadium/moves.ts
The current implementation of Rest on the Stadium sim fails to recalculate stats when Rest is used. This means that right now, the stat drops from Paralysis and Burn remain when you use it. This is inaccurate, and a massive problem considering Rest's increased relevance in the Stadium metagame.
Here is a video of how the interaction works in Stadium: https://www.youtube.com/watch?v=8o0uVj4bARo
Here is a replay of the bugged interaction on PS Main: https://replay.pokemonshowdown.com/gen1stadiumou-1132924324
Here is a replay of my fixed version of Rest working on the RBY server: https://replay.pokemonshowdown.com/rby-gen1stadiumou-1448
Note that on Turn 3, Vaporeon moves **first** when fast asleep. That's how you know the fix has succeeded.
Here is my report on the issue from June of this …
=> Gen 1: Fix Stadium Rest

data/abilities.ts
When enabling Cursed Body against Z-moves in PR #7879 I accidentally allowed it to process against Max moves as well.
=> Cursed Body ignores Max Moves

lib/fs.ts, server/chat-plugins/helptickets.ts, server/global-variables.d.ts, server/punishments.ts, server/rooms.ts
- `writeUpdate` state is now stored in a global variable, so hotpatching doesn't crash it
- throttling now writes on the tail (so two throttled `writeUpdate` calls will write one update, not two)
- room settings, punishments, and helptickets are now throttled
-----
Discussed with @Zarel, decided this would be the best way to stop the writeUpdate crashes.
(for example, `A main process Promise crashed: Error: ENOENT: no such file or directory, rename '/home/ps/main/config/tickets.json.NEW' -> '/home/ps/main/config/tickets.json'`, etc)
=> FS: Fix hotpatching and add more throttling

sim/battle.ts
This makes the `PreStart` event happen before the `Start` event, which also incidentally prevents the related double Unnerve activation message.
=> Unnerve should activate before hazards after phazing

data/abilities.ts, data/mods/gen7/abilities.ts, test/sim/moves/perishsong.js
Note that the tests are subtly different:
- In the first test, nobody would lose if both Soundproof work, and if you take both Soundproof away, then player 2 wins (as per the previous existing test), so this shows that only Player 2's Soundproof didn't take effect
- In the second test, Player 2 would win if Player 1's Soundproof didn't work, so this shows that Player 1's Soundproof took effect in this gen where it didn't for Player 2 in the previous test
=> Fix Soundproof blocking self sound moves in Gen 8

config/formats.ts
Forum post describing the ban hasn't been created yet, but I went ahead and did the ban here since we want it in time for MWP playoffs.  Included is a screenshot of the voting channel from the discord and the tiering announcement there.  
http://prntscr.com/x3i15t (Voting Channel)
http://prntscr.com/x3ibbx (Tiering Announcements Channel)
Hope this enough.
=> National Dex Monotype Mega Medi Ban

data/mods/gen4/moves.ts, data/moves.ts, test/sim/moves/brickbreak.js
Currently for Gen 5 or later the sim hard-codes the type immunity when checking whether Brick Break should destroy screens, but it doesn't for Gen 4. This suggests that the order of events was different back in the day. Sadly I can't figure out what the correct order of events is for Gen 4, so I'll just have to limit myself for fixing Gen 5 or later, by removing the explicit type immunity check and relying on type immunity having been checked before this event runs. This fixes using Brick Break against Ghost types in a number of scenarios, such as if the move is Electrified, or type immunity is bypassed through such means as Scrappy or the Ring Target.
=> Brick Break should destroy screens if type immunity is bypassed

server/chat-plugins/datasearch.ts, test/server/chat-plugins/datasearch.js
For !recovery, !recoil, and !pivot. !zrecovery was fine, but I added tests.
=> Fix excluding variables in /ms

server/chat-commands/room-settings.ts
As per the WAIL thread.
Aeo said it was cool to do this now.
=> Make groupchats require trusted again

data/mods/megasforall/abilities.ts, data/mods/megasforall/rulesets.ts
We caught that the Ability Masquerade was behaving strangely after some further testing, so this is a fix that I've tested and can confirm works better. Notable changes include that it now skips the last Pokémon and proceeds to the next one instead of giving up when an Ability cannot be copied, and that it can successfully activate more than once per battle, whereas the current implementation appears to fail every time following the first successful activation.
I also tweaked Mega Data Mod slightly so that it doesn't misreport type changes on Pokémon with Illusion. For example, if a Pokémon behind an Illusion was affected by Soak, it would look like this was cleared when it was hit. This no longer happens, and it now keeps the type change indicator if they don't match the types of its …
=> Megas for All: Fix Hawlucha's ability + Data Mod

data/mods/gen1/formats-data.ts
I originally brought this up with FOMG, and since then, clarification has been given. The RBY Council supports moving Graveler to NFE since Golem has dropped to UU (and will drop to NU should it be made official). There's a screenshot **[here](https://i.imgur.com/dhEt44O.png)**, I guess. 
FOMG originally told Kris but nothing seems to have happened for the past 2 and a half days, so I decided to make the PR myself rather than saddle him with more work. 
Should be mentioned that NU Live Tours in RoA were using Graveler all this time kekw
=> Gen 1: Move Graveler to NFE

server/chat.ts, server/users.ts
The room was Zarel's suggestion - more accessible.
As a side note, I set errors to be logged since I figure knowing something lasted >3000ms before crashing is still useful knowledge.
=> Chat: Track slow async commands

server/chat-commands/core.ts, server/chat.ts
The `return` makes it so async commands in pms are now properly propagated, which means they're now logged correctly.
This also removes the extra debugger.
=> Chat: Fix slow command logger

CODEOWNERS, package.json, server/chat-plugins/net-filters.ts, server/chat.ts
Aeonic said it was fine to go ahead and PR this now. 
Yes, the static train method is a bit hacky, but training is so heavy on the processes (and it blocks the process entirely since it's sync) that it's the best solution that doesn't involve also holding up the messages.
=> Add machine-learning based monitors

data/items.ts
Changed the accuracy modifier on Bright Powder and Lax Incense from 0x0F1C (eff. 94.4%) to 0x0E66 (eff. 89.99%).
=> Accuracy on Bright Powder+Lax Incense

server/chat-plugins/calculator.ts
Make the calculator support hexadecimal numbers like these: 1h; 16h; Fh etc.
Tested this locally, it works.
=> Calculator: Support h, o and b suffixes for base 16, 8 and 2 numbers

server/chat-plugins/scavengers.ts
Fix /scavhelp to say "/scavhelp staff" instead of "/roomhelp staff"
=> Scavengers: minor update /scavhelp 

server/room-battle.ts, sim/battle-stream.ts
RoomBattleStream originally overrode `_writeLine` in #5428 because `>eval` had a dependency on `Chat.stringify`, and we were trying to separate sim and server.
`Chat.stringify` is now `Utils.visualize`, so there's no more reason for the separation. In addition, the separation is actively bad, because it makes it impossible to import certain inputlogs outside of the simulator (for instance, any inputlog with `>eval` won't work with `./pokemon-showdown simulate-battle`).
=> Merge BattleStream and RoomBattleStream commands

server/chat-plugins/random-battles.ts
Searching for a Monotype or LC set in Gen 6 battle factory causes PS to puke so here's a fix.
=> /battlefactory: Fix searching for nonexistent tiers

server/chat-plugins/uno.ts
Fix this bug
```
Distrib ★ has set the UNO automatic disqualification timer to 10 seconds.
Vextal's turn.
Jojos's turn.
Jojos has played a Blue 6.
```
=> UNO: Fix double turn after auto-disqualification

data/mods/gen2/learnsets.ts
As a follow-up to this Pull Request: https://github.com/smogon/pokemon-showdown/pull/7581
And in response to this: https://www.smogon.com/forums/threads/gen-2-ps-development-post-bugs-here.3524926/page-16#post-8746635
GSC is similar to RBY in that if you trade with a game with different letter characters, it'll corrupt your save file. As such, it is impossible to obtain this Phanpy in western copies of GSC. This can also be applied to Korean events, though as far as I know, they never got any notable ones nor any with special moves. I believe this is the only Japanese GSC event that did not get imported.
This effectively removes Encore Phanpy and Donphan from Gen 2 OU. 
Thanks to Zarel for alerting me to do this!
(also what a nerf between regions holy shit imagine having encore replaced …
=> Gen 2: Ban JP Phanpy Event in Int Formats

server/chat-plugins/poll.ts, server/room-minor-activity.ts
the ``ts-ignores`` are because when i added ``class: Poll`` it says some properties are missing and the other one is "type MinorActivity has no construct signatures". If you recommend handling the errors some way else lmk.
personally I wish it was possible to import poll.ts to room-minor-activity without it crashing on boot but if it was then the ``throw new Error`` line would have never been necessary
=> Fix minor activity timer not queuing polls

server/user-groups.ts
We deprecated `s`, so this was causing issues.
=> Usergroups: Remove deprecated 's' permission

data/abilities.ts, data/conditions.ts, data/items.ts, data/mods/gen5/moves.ts, data/mods/gen6/abilities.ts, data/mods/megasforall/abilities.ts, data/mods/megasforall/conditions.ts, data/mods/megasforall/moves.ts, data/mods/ssb/abilities.ts, data/mods/ssb/conditions.ts, data/moves.ts, sim/pokemon.ts
Working with hex in modifiers is cumbersome. It's pretty outdated, and I assume only used for consistency with the [old BW damage formula article](https://www.smogon.com/bw/articles/bw_complete_damage_formula). However, requiring the extra step of converting to hex leads to issues where simple mistakes can be made - for example, the Aura multiplier was wrong (listed as 0x1547, which is 5447 in decimal, but it should be 5448). Using decimal allows for better maintainability.
This PR doesn't guarantee all the modifiers are accurate, but the conversions from the old hex values to the decimal values should be accurate.
=> Convert modifiers from hex to decimal

data/mods/stadium/moves.ts
So, to be clear: this doesn't fix the whole host of bugs this move has. There's a lot of them.
This fix intends to give Haze its "refresh" effect that it has exclusively in Stadium. Not only does it cure the opponent's status, but it also cures the user's as well. This is an important change for Vaporeon in particular, as it makes a decent status absorber. There _may_ be a better way to implement this, I'm not sure, but I'm guessing this'll receive edits during review. My code seems a touch inefficient?
Here is my implementation working on the RBY Server and my subsequent freakout: 
https://replay.pokemonshowdown.com/rby-gen1stadiumou-1735
This addresses part of my vitriolic criticisms of the Haze implementation here:
https://www.smogon.com/forums/threads/stadium-format-is-now-available-on …
=> Gen 1: Stadium Haze should cure user's status

data/mods/gen2/random-teams.ts, data/mods/gen3/random-teams.ts, data/mods/gen4/random-teams.ts, data/mods/gen5/random-teams.ts, data/mods/gen6/random-teams.ts, data/mods/gen7/random-teams.ts, data/mods/letsgo/random-teams.ts, data/random-teams.ts
This PR
- Brings all Random Battles code up to the standard 120-charaacter line length limit
- Improves readability for all Random Battles code
- Refactors current-gen Random Battles team generation to be more modular and readable
Ideas for the future:
- Further refactors (I'm waiting on this until I'm more familiar with the codebase)
- Possibly adding unit tests
- Ideally, properly divorcing code and data like Battle Factory has
cc @KrisXV @ACakeWearingAHat
=> Random Battles: Refactor for code standards and readability

server/chat-commands/info.ts, server/chat-plugins/usersearch.ts
approved by @HoeenCoder 
This was originally requested by OM as a way to easily click and forcerename problematic names, and I moved it into its own chat plugin in the process
=> Give usersearch a page

server/ladders-remote.ts
A user namechanging before the battle ended in any way would break this.
=> Ladders: Fix crash

server/chat-commands/admin.ts
fixes ``[17:49:59] Annika disabled the command /create.`` showing up when /disablecommand uno create (etc) is used.
=> Admin: Fix /disablecommand message

data/moves.ts, test/sim/moves/fakeout.js
As researched by @DaWoblefet.
Although you lose focus, you are never flinched, and can still move normally by way of Dancer, but on the other hand you lose out on the Steadfast boost.
=> Focus Punch can't be Flinched

server/chat-commands/moderation.ts, server/chat-plugins/usersearch.ts
(I also fixed the title @mia-pi-git yw)
approved/requested by aeonic
While this isn't the most optimal solution, it's probably the best at the moment because it a) solves the issue of all /forcerenames for users in Lobby being parsed from the usersearch pages log to Lobby (this isn't good because it clutters the Lobby's modlog and causes their roomstaff to see things they shouldn't have to) and all /forcerenames from staff not in Lobby being PMed to ~, which is annoying for different reasons such as unnecessarily opening a new pm, and b) allows people to run `/frinstaff` to tackle obscene names outside of Usersearch pages before roomstaff have to see those names while shaving off a few additional seconds that it would normally take to copy the name and switch to the Staff room.
=> Usersearch: Make page forcerenames log to staff

data/random-teams.ts
Patch notes (2/15/2021):
Prevent Air Slash from generating on Swords Dance Virizion by further specifying a line in move enforcement (credit to @AnnikaCodes for this one)
Prevent Scaldless Slowking
Make Darmanitan-Zen-Galar get Salac Berry instead of Sitrus Berry
Make Stone Edge more likely to generate in Random Doubles (formerly erroneously uncommon due to a singles rejection)
Fix RestTalk setup sweepers from rejecting the setup move erroneously (affects Type: Null, Throh, Suicune, etc.)
=> Random Battles Bugfixes

server/chat-commands/info.ts
Adds https://www.smogon.com/articles/getting-started to `/intro`. Requested by Help auth and seems fine to me.
=> Add another article to /intro

sim/pokemon.ts
This affects any cartridge-based formats (aka formats not using HP Percentage Mod), such as VGC in Gen 8 only. The current 48ths system was implementing to accurately simulate games where the HP bar was represented with 48 pixels. By Gen 7, we were already using different amounts (99 in SM and 86 in USUM), but I didn't really bother too much about it because the ability to fine-tune HP to such narrow percentages by looking at it would be very challenging and not very rewarding. However, with the Switch comes resolutions of ~267px for HP bars when docked. An attuned player can realistically tell the difference between, say, Sandstorm KO range in Dynamax and it missing the KO, [which 48ths do not let you do](https://replay.pokemonshowdown.com/gen8vgc2021-1276445737-826pswmft5tid0kyjn51ei1fls …
=> Use HP 100ths in Gen 8 formats

data/mods/megasforall/abilities.ts
Thanks to a poll that concluded this evening, Masquerade should no longer be able to inherit Huge Power or Pure Power.
=> Megas for All: Nerf Hawlucha's ability Masquerade

data/random-teams.ts
All Pokemon in Challenge Cup were spawning with 31 SpD IVs.
=> Fix typo in Challenge Cup team generator

sim/team-validator.ts
A ton of rooms would benefit from this; for example, Ruins of Alph is trying to do Gen 6 OU tours + [insert Gen 7 mon], and this would be much easier than adding `!Obtainable Moves` to the tour rules
=> Let "Allow Tradeback" operate for any generation

lib/process-manager.ts, server/chat-plugins/battlesearch.ts, server/chat-plugins/chatlog.ts, server/room-battle.ts
Fixes ``A simulator process crashed: TypeError: Monitor.slow is not a function``
=> ProcessManager: Handle Monitor#slow in subprocesses

data/formats-data.ts, data/mods/gen3/formats-data.ts, data/mods/gen3/random-teams.ts
-Fully fix issues with mono-solarbeam Pokemon and many Fire-types having two fire moves at once, using a combination of convoluted code and set adjustments.
-Stop Fighting-types from getting Reversal as their only STAB move, by just, like, removing reversal from them
-Prevent Water-types from getting RestTalk with Hydro Pump as the only attack by removing Hydro Pump from those affected.
-Prevent STABless Meganium
-Fix Salac Berry generation to be more specific and more helpful
-Allow Dragon Dance users to get Lum Berry
-Remove endure shenanigans from a bunch of stuff that can't really pull it off well
-give Breloom an actual fighting move that counts as STAB
-remove cb shiftry
-prevent mono-selfdestruct snorlax
-prevent headbutt dunsparce w/o any source of paralysis
-give substitute + …
=> Gen 3 Random Battle updates

server/index.ts
As far as I know, our documentation recommends using `node pokemon-showdown` to start PS, not `node build && node .server-dist/index.js`.
Thus, I don't think the latter is considered starting PS normally.
=> Update comment to reflect the build script

server/chat-plugins/poll.ts
Some staff have expressed confusion on the syntax of queueing HTML polls, since it is inconsistent with /poll htmlcreate, where html- comes before create (compared to queuehtml, where -html comes after). Instead of changing it entirely and causing additional confusion for people who got used to one command, this allows either command to be used. Further, the command for queuing HTML polls was not listed in the help for the command.
=> Add alias for /poll queuehtml

tsconfig.json
To me, this seems like a useful thing to check in linting, with no disadvantage that I can see (I found no measurable performance difference in running `tsc` after removing the `.tsbuildinfo` file).
=> Enable tsc warnings about unreachable code

data/formats-data.ts, data/random-teams.ts
All Gen 8 main formats:
-Fix a large bug regarding Grass-types and STAB enforcement, where Grass-types at or above base 100 Attack would reject every move in their movepool, while Grass-types below that threshold would have their Grass STAB forced erroneously.
-Fix a large bug regarding all Steel-types with Bullet Punch always enforcing another STAB, when usually this is not a great thing to do.
-Fix a bug where Pokemon with two equally viable abilities would get the second-listed ability 85% of the time.
Gen 8 Random Battle:
-Prevent mixed choice item victini by removing Trick.
-Prevent Dual Wingbeat + Roost on Scizor, now that that can actually exist.
Gen 8 Random Doubles Battle:
-Remove Dragon Dance and Phantom Force from Dragapult to prevent really, really bad sets like DD Wisp Shadow …
=> Random Battles bugfixes/minor updates

data/mods/gen5/formats-data.ts, data/mods/gen5/random-teams.ts
This patch updates Gen 5 Random Battle with many of the less controversial improvements proposed
- Superpower gone from the elemental monkeys bc setup + superp is not a fun time
- Swampert is now its usual supporty self
- fix the ability thing that apparently exists in every gen that makes equally rated abilities have unequal appearance rates
- focus blast nidos are a crime against nature
- things like wish chansey and flamethrower blissey just fully do not work in rands and it took way too long for anyone to realize this
- weak armor mandibuzz is bad
- intimidate staraptor is bad
- that one sceptile that should be unburden but isnt is gone
- quick feet is like, actually a thing again on mightyena sometimes
other misc move changes
=> Gen 5 Random Battle updates

server/chat-commands/room-settings.ts
Discussed in the Upper Staff discord.
I've hardcoded this within the `/modchat` command, similar to the hardcode added in 92bc1bdb2d46ce26f84b993121a4f2385890c35e to prevent users above the current modchat rank from turning it off. As far as I know, modchat is the only permission that should work like this. If, in the future, we desire more commands that apply only to ranks at and below the user's rank, we could make this a formal permission, but that seems overkill for now.
=> Don't allow setting modchat above one's rank

data/mods/megasforall/abilities.ts, data/mods/megasforall/conditions.ts
* Attribute Arena Rock to the proper source
* Don't always animate delayed moves used through Clairvoyance when the user is KOed
* Don't animate delayed moves through Long Whip when the user is off the field at all - it gets very weird if it tries when the user is absent, because most of the animations bring back the user and then it just hangs out indefinitely behind the other Pokémon and... it's very funny but also not correct
* Add visual indicator of which Pokémon currently has Gravitational Pull
* Damage the correct Pokémon with Stealth Rock and G-Max Steelsurge through Gravitational Pull
=> Megas for All: Minor Ability polish

config/formats.ts, data/rulesets.ts, sim/dex-formats.ts
Without a priority, the two event handlers run in random order, which is frustrating the OM mashup community, as Tier Shift Scalemons gives completely different results to Scalemons Tier Shift.
I also added priorities to Flipped and 350 Cup for consistency, although they're not mashed up enough for anyone to care that strongly about it.
=> Make Scalemons apply before Tier Shift when they are mashed up

data/mods/gen1stadium/scripts.ts, test/sim/misc/statuses.js
@PlagueVonKarma confirmed that burns are supposed to drop Atk to 50% and not 3%, but just in case I'm missing something obvious, we'll have a pull request about this.
=> Stadium: Apply BRN Atk drop once instead of 5x

server/chat-plugins/scavengers.ts
Currently, the code is meant to call ``!scav viewqueue`` when no parameters are passed, but the runBroadcast line was missing in that bit. Tested to confirm that it broadcasts !scav queue, and that it doesn't broadcast while queuing a hunt with !scav queue [format].
RO confirmation from @aQrator
=> Scavengers: Make !scav queue broadcastable

data/abilities.ts, test/sim/abilities/unnerve.js
https://github.com/smogon/pokemon-showdown/projects/3#card-18659708
The fix was also added to both "as one" abilities.
=> Allow berries to be eaten when a Pokémon with Unnerve switches out to another Pokémon with Unnerve

server/chat-plugins/chat-monitor.ts
This does two things. One, it abstracts filter loading into a function (which is run a tick after the module is done), and makes it so missing filter words don't throw, as to avoid leaking private into. Loading is done a tick after the module to allow for other files to be loaded (the crashes were because they weren't being loaded before the filter loading was done, afaict.)
=> Chat monitor: Refactor to handle private filters better

data/formats-data.ts
(Reversion of https://github.com/smogon/pokemon-showdown/commit/23cc9519bb2bec73b02af7d5d7bec6f6404cba4d)
Regular Venusaur should not have a doubles set, as it has no corresponding level.
=> Reremove accidentally readded removed line

data/abilities.ts, sim/pokemon.ts, test/sim/abilities/berserk.js
https://github.com/smogon/pokemon-showdown/projects/3#card-52059203
Here's a video of it working twice during the same turn in a double battle: https://imgur.com/a/AFVlZdY
The solution does hardcode in the eatItem function, but I don't believe there is another way to do it, since eatItem is called during onUpdate by the berries.
=> Check for berserk before eating item

server/README.md
It seems that Showdown now requires Node.js v12+ instead of 10+:
```
bash-4.4$ ./pokemon-showdown 
We require Node.js version 12 or later; you're using v10.24.0
child_process.js:669
throw err;
^
Error: Command failed: node build
at checkExecSyncError (child_process.js:629:11)
at Object.execSync (child_process.js:666:13)
at build (/srv/pokemon-showdown/pokemon-showdown:21:27)
at Object.<anonymous> (/srv/pokemon-showdown/pokemon-showdown:29:2)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Function.Module.runMain …
```
=> Update required version of Node.js

sim/pokemon.ts, sim/side.ts, test/sim/misc/hazards.js, test/sim/moves/stealthrock.js
The 4 player battle changes broke hazards in general, they wont set if the target side has no un-fainted pokemon. This is because no target is provided, unlike in the past. The issue appears to be a combination of changes in two commits https://github.com/smogon/pokemon-showdown/commit/956daf89b6eb73f16846690d032fb7f77052046d which made `foeSide` moves start using an array of targets, and this from the 4-player patch which is used to get that array of targets but ignores fainted pokemon https://github.com/smogon/pokemon-showdown/commit/3b5e8cbfc2546afb19a0abce9f14c48c4e63e315#diff-6c26dba8e16b8854c67b0fc13f79e9811908c5f36d673084e350c8b89252ac81R230 .
This is my proposed patch, there may be a better way though (eg: new methods getAllFoes getAllAllies or w/e). PRing because I'm looking for …
=> Fix hazards not applying if the target side is fainted

data/abilities.ts, test/sim/abilities/neutralizinggas.js
https://github.com/smogon/pokemon-showdown/projects/3#card-52059168
Simply adds checking ignoringAbility in the unburden condition code. Ran both Neutralizing Gas and Unburden tests and they all passed. This probably requires a change in the client tooltips code so unburden's speed boost is not shown when it is suppressed.
=> Negate Unburden boost when Neutralizing Gas is active.

server/chat-formatter.ts, test/server/chat.js
Mostly so A/M can say "spoilers work like Discord", instead of teaching them a new syntax.
Added a new span type `'|'` instead of reusing `'spoiler'` so as to avoid unwanted interactions in `popAllSpans`.
=> Chat: Implement Discord spoilers

data/rulesets.ts, test/sim/team-validator.js
Currently, when a user creates a Pokemon with multiple duplicate moves, the validator doesn't say anything is wrong and just removes the duplicated move from the user's moveset automatically. I've definitely made the mistake in the past where I quickly make a Pokemon's set, don't realize I really only have 3 moves, and don't figure it out until the battle. This also fixes an issue with automatic move changes (i.e. Iron Head -> Behemoth moves) where a user accidentally adds both Iron Head and the Behemoth move without realizing Iron Head becomes Behemoth Blade / Bash. This way, the mistake is exposed at the teambuilder level, so they don't think get confused about why a move is missing.
Sample:
Fixes https://github.com/smogon/pokemon-showdown/projects/3#card-51711810
=> Validator: Disallow duplicate moves

data/abilities.ts, data/formats-data.ts, data/random-teams.ts
A series of improvements for legibility, function, and code simplicity.
-Added comments to random-teams to indicate special cases and explain organization
-Organized many things
-Removed some unnecessary hardcodes
-Neutralizing Gas should really not be at the same rating as Moody, Shadow Tag, and Wonder Guard, especially when it necessitates a dumb hardcode for Weezings in rands. 4 is a much better fit by all logic.
-Separated the doubles Butterfree sets to actually accommodate for Quiver Dance being forced
-Nasty Plot PZ is free
-Speedsetup moves are now further clarified as a group, only referring to moves that *solely* boost Speed. This causes Extreme Speed + Shift Gear genesect to exist again and makes Thunder Wave + Shift Gear Klinklang happen in doubles, but those are acceptable …
=> Random Battles Improvements

data/random-teams.ts
happens when we remove stuff from speedsetup. as of last update shift gear's gotta be manually called whenever we want to do anything with it since it's not categorized as setupType or speedsetup now.
idea: define speedsetup as "all speed-boosting moves that are not otherwise categorized as setupType and would need to be called in the generator at any point specifically due to their speed boosting properties"
=> Random Battles: Fix Toxtricity

data/abilities.ts, data/items.ts, test/sim/abilities/magician.js
This was done to fix the timing of item activation for Magician, which currently steals these items before they can activate. The bug report for this Magician interaction stated this happening to Weakness Policy, but Magician should interact in the same way with the other items I have changed. Should I add additional tests for the other items like Snowball, Cell Battery etc.?
=> Use onAfterMoveSecondary for Magician effect

data/moves.ts
Approved suggestion by Aeonic: https://www.smogon.com/forums/threads/have-a-message-clarifying-plasma-fists-interactions.3680958/
Plasma Fists turning Normal-type moves into Electric-type moves is a somewhat common mistaken bug report.
=> Add Plasma Fists hint

sim/pokemon.ts, test/sim/moves/transform.js
Currently, when Transform sets the user's ability to that of the target's, it sends an ``-endability`` protocol message which leaks the Transform user's Ability. The way I approached this was by turning off that -endability message for all form changes. I'm _pretty_ sure this is fine, because it effectively was doing this anyway with requiring the source to be a move (I think we still need that check so Ability stuff doesn't start leaking all over the place, but I'm not super sure).
=> Fix Transform source Ability leak

data/mods/gen1/conditions.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8768936
This implements the above mechanic, where a pokemon that is frozen during its recharge turn can't do anything while it is still frozen, including switching out or actually recharging. I reimplemented the freeze move disabling in the `mustrecharge` condition because of the priority for onBeforeMove in `mustrecharge`.
=> Gen 1: Don't allow Pokemon to recharge if frozen

server/chat-commands/room-settings.ts, server/room-battle.ts, server/rooms.ts, server/users.ts
Requested here https://www.smogon.com/forums/threads/allow-for-auto-modchatting-on-a-prefix.3682737/#post-8829088.
Monkeypatches are here https://gist.github.com/mia-pi-git/61fc91671107113a252d9d39791bad87.
I was told it would be optimal to have this live on the server by the 25th, as there's a tour that'd benefit from this.
=> Support forcing modchat on ladder tour battles

server/chat-commands/info.ts, server/chat-plugins/helptickets.ts, server/chat-plugins/mafia.ts, server/chat-plugins/wifi.ts, server/punishments.ts, server/tournaments/index.ts
This adds a few useful things.
One, punishmentTypes now support callbacks (that are called when a user has the punishment they're set for and has just logged in.) This should make it easier to _do_ things with custom punishments without extra code for a loginfilter that also checks if they have the type.
It also adds support for adding more properties to punishment types.
Lastly, it ensures that when a user has a custom global punishment, it doesn't randomly lock them (as that is frequently undesired behavor) and instead just calls the callback.
=> Add more support for custom punishments

data/mods/gen3/random-teams.ts, data/mods/gen4/random-teams.ts, data/mods/gen5/random-teams.ts, data/mods/gen6/random-teams.ts, data/mods/gen7/random-teams.ts, data/random-teams.ts, lib/utils.ts, server/chat-commands/admin.ts, server/chat-commands/info.ts, server/chat-plugins/battlesearch.ts, server/chat-plugins/chatlog.ts, server/chat-plugins/datasearch.ts, server/chat-plugins/helptickets.ts, server/chat-plugins/hosts.ts, server/chat-plugins/mafia.ts, server/chat-plugins/room-events.ts, server/chat-plugins/room-faqs.ts, server/chat-plugins/scavenger-games.ts, server/chat-plugins/scavengers.ts, server/chat-plugins/trivia.ts, server/chat-plugins/uno.ts, server/chat-plugins/youtube.ts, server/ip-tools.ts, server/rooms.ts, server/tournaments/generator-round-robin.ts, test/server/ip-tools.js
A few uses of `array.sort()` have been left alone:
- `array.sort((a, b) => b - a)[0]` to get the max of an array (this can be refactored to `Math.max(...array)` but would crash on large arrays - thanks, JavaScript)
- sorting in `data/` because they aren't supposed to import anything
- `set-importer` because I still have no clue what that's for and what dependencies it is/isn't allowed to have
- `sort()` with no arguments used as a lexical sort (at which point `sortBy` offers no benefits)
All other cases have been replaced with `Utils.sortBy`, which should be a massive increase in readability.
Sort orders should be much more readable now, without needing to puzzle through sign issues. The order is always low-to-high, A-to-Z, true-to-false.
=> Refactor everything to use Utils.sortBy

data/mods/gen7/moves.ts, data/moves.ts, test/sim/moves/grassyterrain.js
It also doesn't weaken moves against semi-invulnerable targets, which means that users of Dig take regular doubled damage from Earthquake.
=> Grassy terrain only weakens moves against grounded targets

server/chat-plugins/calculator.ts
The calculator used to ignore extra `)`s but PR #8235 broke that. (Sorry about that.)
=> Handle extraneous parentheses again

config/formats.ts, data/mods/gen1jpn/rulesets.ts
I'm not sure if there was a misunderstanding/miscommunication somewhere, but I'm pretty sure something went wrong when implementing Japanese OU. There was some talk in the RBY Community Discord about it since it suddenly sprang up and a few people are interested. 
- It appears that Japanese OU was using an odd "standard" ruleset. I'm not sure what this was for or how it happened, as NC97 didn't use that standard. Due to this though, there wasn't an OHKO clause or anything, so in this edit, I propose changing it to fit with the [Gen 1] OU standard.
- The "Japanese Gen 1 Move Legality" is a misnomer; this bans moves from Pokemon Yellow and is meant to be used with Nintendo Cup 1997. Unless you want to make Japanese OU a "Red and Green OU", this shouldn't be applied to it at all. I changed …
=> Gen 1: Fix Japanese OU and Tradebacks OU legality

config/formats.ts, data/tags.ts, sim/dex-formats.ts, sim/team-validator.ts, test/sim/team-validator.js
Previously, the validator had its own hardcoded tag system. This removes the hardcoding and makes it so any pokemon tag in `tags.ts` can be banned or unbanned.
=> Use data/tags for validator

config/formats.ts
Approved by chemcoop. This should start May 1 (merging with the other tier changes is fine).
Also removes "VGC 2021" (Series 8), as it is also no longer needed for anything.
=> Rename VGC 2021 ladder and upgrade Battle Stadium Singles to Series 9

config/formats.ts
See https://github.com/smogon/pokemon-showdown/pull/8255#issuecomment-830629704
Going forward, we're trying to keep VGC Series named as such, because TPCi doesn't seem to want to deviate from the Series-style formats (drastically changing the format every 3 months). Having a new ladder each series accurately allows players to start fresh in what is definitely a new format. In addition, having the name of the series in the format name offers additional clarity for newer users.
In addition to THAT, I already have been telling everyone in both VGC's room intro and on Twitter since we launched Series 9 last month that ladder rankings from the Series 9 ladder will transfer over to the proper ladder.
=> Formats: Use the name VGC 2021 Series 9

data/items.ts, sim/battle-actions.ts, test/sim/items/redcard.js
Fixed by checking the faint queue between the end of a multi-hit move and recoil damage, causing the effects of Destiny Bond to be applied before the effects of Red Card are applied. I'm not sure if evaluating the faint queue first will cause incorrect behavior (like ordering shenanigans with something like Soul Heart in doubles), but it seems to pass all the tests.
bug report: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-23#post-8585749
mechanics bugs card: https://github.com/smogon/pokemon-showdown/projects/3#card-52058755
=> Fix interaction of Destiny Bond and Red Card

config/formats.ts, sim/battle.ts, sim/dex-formats.ts, sim/side.ts, sim/state.ts, test/sim/decisions.js
`maxTeamSize` is a bad variable name (not that `teamLength.battle` is any better, but that'll get fixed in a future refactor).
- Rename `maxTeamSize` to `chosenTeamSize`, to better indicate that this is the size after Team Preview, and that it is also the minimum size after Team Preview.
- Don't limit team sizes to 6 if `teamLength.battle` isn't specified. This removes an unnecessary `teamLength.battle` requirement in all Custom Game formats.
- Stop requiring `maxTeamSize` as a parameter for `battle.getRequests`. It's not even used except as a hint to the Preact client, and was never state in the first place.
- Stop supporting partial `side.chooseTeam`. This is an unused feature and removing it massively simplifies the code and fixes a bug in `cupLevelLimit` which definitely was not …
=> Rename and fix maxTeamSize

data/conditions.ts, data/mods/gen4/conditions.ts, data/mods/gen6/conditions.ts, sim/battle-actions.ts, test/sim/misc/confusion.js
See [battle mechanics research post](https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8843892) for more details; this behavior happens for sure in Gen 7/8 and almost certainly happens in Gen 5/6.
I'm not sure what I should do for Gens 3 and 4 (Gen 2 overrides the condition already). According to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Confusion_(status_condition)), if I had to guess it looks like confusion damage is using a regular damage calculation, but there's a ton of caveats for each gen. We definitely don't support all those caveats currently and I am not interested in properly researching it for Gens 3 and 4 to sort it out. For now I've just blindly copy-pasted Gen 6's old confusion condition into Gen 4.
=> Improve self-hit confusion damage

data/mods/fusionevolutionuu/rulesets.ts, data/mods/gen7/rulesets.ts, data/rulesets.ts, sim/battle.ts, sim/dex-formats.ts
In format events:
`onFieldTeamPreview` has been renamed back to `onTeamPreview`. It's now a custom event (like `onBegin`), rather than a field event.
Team Preview data has been entirely moved from `onBegin` into `onTeamPreview`.
`onFieldStart` for formats/rules now happens after Team Preview, rather than before. Use `onBegin` for things that happen before Team Preview.
=> Simplify Team Preview events

server/chat-plugins/scavengers.ts
The `<em>` being wrapped around each individual username and not the entire host string is intentional since it looks better  - and also allows parsing of hosts from the finishing message
Approval from LittEleven https://cdn.discordapp.com/attachments/762324232948023316/841056528491741214/littappr.png
=> Scavengers: Italicize host names on hunt end

sim/team-validator.ts
changes "does not exist in Ultra Sun/Moon" to "does not exist in this game", since Sword and Shield (and future games) are a thing.
=> Fix validator message for LGPE pokemon

server/chat-plugins/helptickets.ts
This should cover support for almost everything discussed here https://www.smogon.com/forums/threads/3673339/page-2#post-8677283.
I opted for a separate resolving command for text tickets to avoid cluttering up the other command, though /ht close will parse /ht resolve if the target ticket is a text ticket.
=> Helptickets: Refactor to support text-only tickets

server/chat-commands/admin.ts
Similar use as `/sendhtmlpage` for bots but for cases where the HTML is small or should be easier to reach from the chat room.
=> Implement /sendprivatehtmlbox

sim/battle-actions.ts, sim/battle.ts, test/sim/misc/faint-order.js
Only bother checking for a winner if the move's user is also fainted at the time, and check for a winner after the move completes.
=> Fix faint check mid-attack

data/abilities.ts, test/sim/abilities/neutralizinggas.js
Previously, if multiple Neutralizing Gas were active, switching one out would cause the Neutralizing Gas "The effects of the neutralizing gas wore off!" to play when it shouldn't. Ability events were being re-run too unnecessarily (they wouldn't do anything since it was still being negated). Note that it is unlike Primal weather, where Neutralizing Gas _does_ announce itself on switchin, even if the effect is already active.
=> Fix Neutralizing Gas ending if another is active

data/bss-factory-sets.json
https://www.smogon.com/forums/threads/3675374/#post-8853841 pointed out that we have bad HP numbers for Glutton Snorlax, so this fixes them.
=> BSS Factory: Fix Snorlax HP numbers

PROTOCOL.md, server/chat.ts, server/users.ts
Zarel description:
In the past, the client would send `|MESSAGE` as a shorthand for `lobby|MESSAGE`. The bandwidth savings are negligible nowadays and we've definitely had bugs arise from this behavior, so the client now consistently sends `lobby|MESSAGE` when sending to Lobby. The server will now always interpret `|MESSAGE` as a room-less command (in the past, it was considered a message to Lobby if you were in Lobby, and a room-less command otherwise).
-----
As per #sim-dev. I believe this should be everything, deployable with the client changes to explicitly send `lobby|message`.
=> Stop defaulting messages to Lobby in protocol

data/abilities.ts, data/conditions.ts, data/items.ts, data/mods/gen2/conditions.ts, data/mods/gen2/items.ts, data/mods/gen2/moves.ts, data/mods/gen3/abilities.ts, data/mods/gen3/items.ts, data/mods/gen3/moves.ts, data/mods/gen4/abilities.ts, data/mods/gen4/conditions.ts, data/mods/gen4/items.ts, data/mods/gen4/moves.ts, data/mods/gen5/moves.ts, data/mods/gen6/moves.ts, data/mods/gen7/moves.ts, data/moves.ts, test/sim/misc/weather.js, test/sim/moves/gmaxvolcalith.js
I noticed Grassy Terrain was happening before Volcalith because of it missing an ``onResidualSubOrder``, decided to audit the rest of the end-turn resolution order numbers and got to fix quite a few. List is partially based on my [post from October 2019](https://www.smogon.com/forums/threads/ultra-sun-ultra-moon-battle-mechanics-research-read-post-2.3620030/post-8264465) as well as notes from [new USUM research](https://github.com/smogon/pokemon-showdown/pull/8222#issuecomment-825941312). As far as new effects go:
- Octolock is sandwiched between binding moves and Taunt according to Zaggyo
- G-Max chip _technically_ doesn't have an ending message on cart, but there's no way it's anything but the same block as Pledge moves / screens etc. I just gave it values higher than Aurora Veil.
I did …
=> Fix the order of many end-turn resolution effects

data/moves.ts, test/sim/moves/encore.js
Counter/mirror coat target redirection carried over because of the decreased priority, this fix makes it so the target is not redirected if the move being used is not counter or mirror coat.
=> Fix Counter redirecting Encored self-target moves

data/mods/gen3/moves.ts, data/mods/gen4/moves.ts, test/sim/moves/sleeptalk.js, test/sim/moves/weatherball.js
Gen 3 weather ball no longer triggers mirror coat
Gen 4 trick fails when the target has multitype
Also added a test for sleep talk PP deduction in gen 4
=> Fix Gen 3 Weather Ball and Gen 4 Trick

data/mods/gen3/moves.ts, data/text/moves.ts, test/sim/moves/brickbreak.js
Wasn't mentioned as a past gen bug, but saw it while reading up on the other old gen Brick Break bug on Bulbapedia and noticed this behavior wasn't implemented.
=> Gen 3: Always break the opponents screens with Brick Break

data/mods/gen1/formats-data.ts
[So the new RBY OU VR is out](https://www.smogon.com/forums/threads/rby-ou-viability-ranking-mark-ii.3572352/page-16#post-8867170), and it's in a state where Lapras and Victreebel would drop.
However, a new policy is being instated by the RBY Council [where drops are delayed by 2 VR Revisions to increase tier stability](https://www.smogon.com/forums/threads/tiering-in-rby.3682580/post-8867192). I've been chatting with Hipmonlee about it, and to display the "held back" mons we want them put in OU by technicality for the duration. 
Here he is agreeing to the OU by technicality proposal and me remembering I can do this 😂
=> Gen 1: Move Victreebel and Lapras to OU by technicality

CODEOWNERS, server/chat-plugins/username-prefixes.ts, server/index.ts, test/server/chat-plugins/username-prefixes.js
This will allow any Upper Staff member to manage `Config.forcedprefixes`.
=> Add a chat plugin to manage username prefixes

data/moves.ts, test/sim/moves/skydrop.js
Checks to see if the current target is the one originally picked up by sky drop. I could also check for `this.effectState.target.fainted`, but I thought this would encompass more stuff.
=> Sky Drop: Fix message when target is fainted

server/chat-commands/info.ts, server/chat-commands/moderation.ts, server/chat-plugins/helptickets.ts, server/global-types.ts, server/punishments.ts
This refactors ticketbans (formerly associated with the Staff room), battlebans (formerly associated with the "battle" room), and groupchatbans (formerly associated with the "groupchat" room) to be global punishments since a user can have multiple now.
=> Use global punishments instead of fake rooms

config/formats.ts
Currently, in a battle with both Camomons and Bonus Type battle effects, Camomons will randomly activate last per-switch in, overwriting the Pokemon's typing in full and disabling its Bonus Type. This change makes Bonus Type always activate last so that it is compatible with Camomons.
Similar to https://github.com/smogon/pokemon-showdown/pull/8051
=> Make Bonus Type modify species after Camomons

config/formats.ts, data/rulesets.ts
I managed to replicate the Chimera crashes that appeared in the development room yesterday on a test server. Probably they were caused by users creating custom challenges similar to this:
`/challenge gen8randombattle@@@gen8chimera1v1,!!pickedteamsize=1`
It seems like Chimera's onValidateTeam is not called in that case. However, if the onValidateTeam were changed to onValidateRule, it seems like it wouldn't be called in cases where Chimera is the base format. So this change gives Chimera its own rule from which the onValidateRule is called in either case...it feels like it might be useful if base formats had onValidateRule (or something like it) called on them as well, but I don't think encapsulating the Chimera functionality in a rule is a bad thing regardless.
When I was testing things …
=> Fix crashes in Chimera 1v1 rule interactions

config/formats.ts
NC2000 was played using Stadium 2.
Src: http://pokemon.s20.xrea.com/2nd/rule.html#nintendo 
"対戦環境は「ポケモンスタジアム金銀」。"
This roughly translates to "the battle environment is stadium gold and silver".
There is also an official source here stating that RGBY can be used, which is only possible via Stadium 2
https://www.nintendo.co.jp/n01/n64/software/nus_p_np3j/league/
=> Gen 2: Nintendo Cup 2000 should use gen1stadium2

sim/battle.ts, sim/pokemon.ts
https://www.smogon.com/forums/threads/endless-battle-clause-enhancements-for-rby.3673455/
Note: Gen 1 stadium's unique transform restrictions are currently not implemented, but it's currently future-proofed when it happens.
=> Gen 1: Fix Transform and Endless Battle Clause

data/mods/gen5/pokedex.ts
Second bug on the post: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-59#post-8900393
While not confirmed on the post, I tested this myself by catching a Blue Basculin from the wild in Pokemon White, and it had Reckless. Don't know whether Rock Head or Reckless should be considered the "Special" ability.
Drafting for now, as I need someone to confirm if transferring the Basculin into Pokemon Bank actually changes Reckless to Rock Head.
=> Gen 5: Blue Basculin should be able to have Reckless

config/formats.ts
I talked with chemcoop about this and discussed a bit with Kris in PMs, but this is the general idea of what we (chemcoop and I) would prefer to do:
- VGC will run a Series 10 ladder concurrently with Series 9. At the end of the month, Series 9 will be converted to challenge-only.
- Battle Stadium Singles will have a challenge-only Series 10 option. At the end of the month, Series 10 will be renamed to Battle Stadium Singles, and Series 9 will be renamed and converted to challenge-only.
Both VGC and BSS have tournaments involving Series 9 after the format officially switches August 1. There is also a non-zero chance, imo, that they will switch back to Series 7/9-style again after Series 10 is over. The reason VGC is requesting a VGC Series 10 ladder so early is because there is …
=> Add VGC/BSS Series 10 support

server/chat-plugins/datasearch.ts
This fixes/changes a couple things:
a) Long dexsearch queries now reject with an error instead of blindly trimming and giving stuff like ``retur could not be found in any of the search categories``.
b) Maxgen now works properly (before this, the maxgen parameter only worked if it was either the first term or if there were no spaces after the preceding comma).
c) Mod now allows spaces around the equals sign (`mod = SSB`) instead of matching properly and failing on the split.
d) Gen0 no longer works in abilitysearch / itemsearch (not that relevant, but since current behaviour is to block Gen 1/2, seems a bit weird to allow 0).
e) Gen X and Maxgen X now work in abilitysearch / itemsearch (before this, they'd give a blank 'no results found').
f) Gen X and Maxgen X now support multi-digit …
=> Datasearch: Minor refactor

server/chat.ts, tools/build-utils.js
I feel like there should be a `.tools-dist` now.
Fixing this stuff got `.server-dist/index.js` to run, but there are still some more bugs with file paths, since the places where FS is called to access a file is not replaced like how something in `require` is. It would be quite cumbersome to account for sucrase in every part of the code that uses FS, so there has to be a better solution.
=> Fix bugs with Sucrase build process

server/chat-plugins/mafia.ts
Final removal of the word "lynch" from mafia.ts due to racial considerations. All uses of the word have been changed to "vote" and all future references to the action will use "vote" instead of "lynch".
=> Remove 'lynch' from mafia.ts 

config/formats.ts
It seems like there were some objects missing from the Mashups Megathread banlist (https://www.smogon.com/forums/threads/om-mashup-megathread.3657159/#post-8299984) that have now been updated. These are made effective in the format with this change:-
* Zacian-Crowned was meant to be Zacian (overlooked due to being grandfathered in from the base Mix and Mega ruleset)
* Clangorous Soul, a recently-restricted move had yet to be listed
Moreover, King's Rock was missing from the format's banlist and has now been added (Razor Fang has not been added to the format's bans and has been removed from the Megathread list, because the item does not exist in Gen 8).
=> STABmons Mix and Mega: Fix bans and restrictions

data/mods/gen1/formats-data.ts
The new RBY UU Viability Rankings were produced yesterday night, and these Pokemon moved up. The 2-revision policy for OU does not apply here. 
Update can be found here: 
https://www.smogon.com/forums/threads/rby-uu-viability-rankings.3647713/post-8935573
=> Gen 1: Move Aerodactyl and Dewgong to UU

server/chat.ts
As of [Chrome 86](https://www.chromestatus.com/feature/4926989725073408), Chrome attempts to automatically upgrade images with an http source to be https before displaying the image. If the image can't be loaded in https, it'll just fail to load. Unlike Chrome, Firefox currently just marks the whole site as insecure if it finds image mixed content, indicated by the padlock having a triangle warning sign in the address bar.
By disallowing http images, we prevent users from displaying images that may not work in every browser. Compare the Chrome behavior to the Firefox behavior, with an image that can be upgraded from http -> https and an image that cannot.
Chrome 92:
Firefox 90:
Images in question:
http://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/intermediary/f/578a8319-92b6-4d81-9d5f …
=> Chat: Disallow HTTP images

server/chat-plugins/modlog-viewer.ts
Very, very minor; fixes double spaces for a couple modlog queries when nothing was found.
Before:
After:
=> Modlog: Fix double spaces when no moderation found

data/items.ts, test/sim/items/metronome.js
Should fix https://github.com/smogon/pokemon-showdown/projects/3#card-61614782
Also adds a test for the case of a two-turn move that bypasses its charge turn and fixes the original broken test that was here.
=> Fix Metronome (Item) and two-turn moves interaction

CODEOWNERS, package.json, server/chat-plugins/github.ts
Useful feature, should be able to replace the bot in terms of stability (with the same functionality).
To set this up, one needs to add a webhook to post `push` and `pull_request` actions to `{our url}:{port}/github/callback`, and then set `Config.github` to the `port` to listen on and the secret set in the webhook.
=> Add a chat plugin for reporting GitHub actions

databases/schemas/chat-plugins.sql, server/chat.ts
As described in [the design proposal](https://gist.github.com/AnnikaCodes/afa36fc8b17791be812eebbb22182426), all chat plugins will share one SQL database.  Since I think it's overkill to spawn a process for every chat plugin (Trivia only needs to use the database during official games and when questions are edited), it makes sense to have one access wrapper in Chat. I want to convert Trivia to SQLite soon and this needs to happen first.
=> Chat: Support accessing the chat-plugin database

data/items.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8944777
- Added Marowak-Alola to Thick Club
- Added Farfetch'd-Galar to Leek
- Added all Pikachu formes to Light Ball
The bug report mentioned stuff like the base formes of things like Giratina and Zacian not having their forme specific items show up, but I didn't add them cause I feel like there was a reason this was done. If there isn't then I can do those too.
=> Update item users on some items

lib/sql.ts, server/chat-commands/admin.ts, server/chat-plugins/trivia/database.ts, server/chat.ts, server/modlog/index.ts, test/server/modlog.js
Mostly PRing so @AnnikaCodes can review and decide if she wants her consumers to fully use this (i left in a lot of `this.somethingQuery = await this.db.prepare(....)`.
This makes it so by default, the child process will no longer require you to call .prepare before you query the child again to use the statement. There's a new parameter, `noPrepare?`, added to all the functions (`get`, `run`, `all`) that use prepared statements. If this is passed, it will indeed require you to call `.prepare` before using it, and if it is not prepared, it will throw.
Otherwise, if this isn't passed, the child process will try to find the cached statement, and if not, prepare it and cache it.
=> SQL: Automatically prepare statements unless told otherwise

sim/battle-actions.ts, test/sim/abilities/emergencyexit.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8947695
Specifically, after recoil from moves like Flare Blitz and struggle. I've added tests for both types.
=> Fix Emergency Exit not activating after recoil damage

data/moves.ts, sim/SIM-PROTOCOL.md
Corresponding client change: smogon/pokemon-showdown-client#1783
Uses a new pline `-sideswitch`, which swaps side conditions between sides. Right now it only uses it for non ffa battles, mostly cause I don't really understand the ffa code rn, and was hoping I could get some help on that one.
https://user-images.githubusercontent.com/32044378/117557824-1cf54480-b045-11eb-9be0-e11c2e20ea69.mp4
=> Use |-swapsideconditions| for Court Change

config/formats.ts
https://www.smogon.com/forums/threads/inheritance.3656811/post-8967769
Fixes 2 Ability Clause not working for Inheritance due to how abilities are stored prior to the battle starting. I just reimplemented the code from 2 Ability Clause into Inheritance's `onValidateTeam` function. Should I just check if the format is Inheritance in 2 Ability Clause's code and correct the bug there instead?
I also want to note that I left 2 Ability Clause in `rulesets` for the message it sends in `onBegin`.
=> Inheritance: Manually implement 2 Ability Clause

server/chat-commands/info.ts
Only YOU can stop people from seeing GMax moves in Gen 1 games!
=> /details: Don't show G-Max moves in old gens

data/mods/gen1stadium/formats-data.ts
Talked to @KrisXV who said I just submit this tier file and he does the rest. This is based on the [2021 Stadium OU VR](https://www.smogon.com/forums/threads/stadium-ou-poster-viability-rankings-2021.3685877/), using Lutra's proposed cutoff between D4 and E rank. This aims to clean up the teambuilder a mite bit while being somewhat consistent with LGPE OU's stuff.
=> Gen 1: Implement Stadium Tiers

config/formats.ts
@KrisXV told me to make a Pull Request for this. For some reason, the Tradebacks OU challenge option never banned Dig/Fly due to using an archaic ruleset list. Because of this, some _naughty_ people have been using stuff like Fly Articuno on the ladder! I've changed it to use Gen 1 OU + Allow Tradeback, which should fix the problem and prevent more cropping up in the future. Besides, that's kinda what it's meant to be, y'know?
=> Gen 1 Tradebacks OU: Ban Dig/Fly

server/chat-commands/core.ts
```
[09:45:39] @PartMan: !h status
Could not find help for '/status ' - displaying help for '/status' instead
/status [note] - Sets a short note as your status, visible when users click your username.
Use /clearstatus to clear your status message.
```
=> Trim commands in /help

data/mods/gen1stadium/formats-data.ts
For some reason Poliwrath was listed as OU, not sure why or how it got there when I was writing it in. It's not even ranked at all. Sorry for the trouble!
Otherwise, everything seems correct.
=> Stadium OU: Move Poliwrath to StUU

data/formats-data.ts, data/mods/gen7/formats-data.ts, data/mods/gen7/random-teams.ts, data/random-teams.ts, test/random-battles/gen7.js, test/random-battles/gen8.js
Gen 8:
-Lucario: Stone Edge over Ice Punch, adjust corresponding hardcode to match
-Silvally-Fairy: Flame Charge over Fire Fang
-Zeraora: Blaze Kick over Fire Punch; the power is important for several KOs
-Fix Rillaboom and G-Max Rillaboom's level difference
-Eldegoss: -Charm
-Prevent Shift Gear + U-turn Genesect again
-Create new focus sash qualifications s.t. pokemon with 250 total bulk (ex. Mamoswine) and below will get sash with hazards in lead slot and Pokemon with 210 total bulk (ex. Indeedee-M) and below will get focus sash without hazards in the lead slot.
-Rewrite the Cinccino hardcode so it both is more explicitly about cinccino and prevents focus sash from generating
Gen 7:
-Stone Edge over Fire Punch on hitmonchan for better coverage
-remove Memento on dugtrio to prevent …
=> Random Battles updates

data/abilities.ts, test/sim/abilities/neutralizinggas.js
Ice Face should not reform when neutralizing gas leaves the field. Caused by triggering onStart for Ice Face in onEnd of Neutralizing Gas.
To fix the bug for Ice Face, the code now ignores abilities that are unaffected by Neutralizing Gas in the onEnd for Neutralizing Gas (using the isPermanent flag). 
I believe this also excludes other abilities unaffected by Neutralizing Gas (such as Schooling) from triggering onStart immediately when Neutralizing Gas leaves the field. Not sure if this is correct from a mechanics perspective; if not, I can change it to only exclude Ice Face! 
Corresponding bug report: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8949321
=> Fix Ice Face behavior

data/conditions.ts, data/mods/gen2/conditions.ts, data/mods/gen3/conditions.ts, test/sim/abilities/sheerforce.js, test/sim/misc/statuses.js
When using a move like Scald or Sacred Fire, the check for burn potential happens before the check for potentially thawing the target; that is, it is impossible to burn a frozen target after thawing it with something like Scald. Technically it should be its own event, but I think ``onDamagingHit`` works alright for this purpose in the meantime until research is completed on post-move success order.
In addition, the autothaw from Fire-type attacks and the autothaw from Scald, Steam Eruption, and Scorching Sands is at different timings. A Sheer Force-boosted Flamethrower would thaw its target, but a Sheer Force-boosted Scald would not.
I need to verify how this works in pastgens. I would not be super surprised if you _could_ burn a frozen target in Gens prior to 5.
=> Fix timing of freeze thaws

sim/team-validator.ts
Let's Go formats already disallow any non-Mega Stone items, this code has no purpose other than preventing the use of Mega Stones (not an intended part of Candy formats).
=> stop allowAVs from removing items

server/chat-commands/core.ts
You can't befriend yourself, so there's some bandwidth to be saved by not sending that info back from server
=> CRQ: Don't send friend status for yourself in userdetails

data/mods/gen1/random-teams.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9021489
Fixes the above bug, where Magikarp appeared on a forced mono bug team because shitmons get pushed into the rejected but not invalid pool before typing gets checked for monotype. I also cleaned up the code a bit by using stuff like `getPokemonPool` in `randomTeam` and `randomNPokemon` in `randomCCTeam`. If I shouldn't have done that I can revert those changes and just do a basic fix for the above bug.
=> Gen 1 Randbats: Fix Monotype

data/conditions.ts, data/mods/gen4/conditions.ts, data/mods/gen6/conditions.ts, sim/battle.ts, sim/pokemon.ts, test/sim/misc/statuses.js
Currently, paralysis is being treated as a Speed modifier, being chained together with other Speed modifiers like Tailwind or Choice Scarf. Paralysis is actually its own independent modifier, taking place outside of that traditional calculation; this can lead to some rounding errors such as outlined in this [bug report](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8979399).
This solution works for modern gens fine, but it doesn't work for past gens and mods since I'm hardcoding paralysis. I also don't in fact know for sure how paralysis is applied prior to Gen 6. In Gens 7 & 8, it's applied as a * 50/100 after other modifiers, and in Gen 6 it's the same but * 25 / 100. I assume BW is the same as Gen 6. But I don't know if it's done …
=> Fix paralysis modifier application

server/chat-commands/core.ts, server/chat-commands/moderation.ts, server/chat.ts, server/room-battle.ts, server/rooms.ts, server/users.ts
This is a PR basically only because it's not hotpatchable, so I want people to know about it. You _could_ monkeypatch it, but I'm planning to restart tonight, so I'm going to skip that.
This is partly to work around unnecessary "room not found" issues from race conditions, but this should also improve performance.
=> Refactor getIdentity not to take roomids

data/mods/gen7/factory-sets.json
On Liepard sets without Copycat, Prankster is useless and Limber is a situational improvement. However, Prankster is needed on Copycat sets to function properly (revenging sun boosted victreebel, for example)
=> Force Prankster on Liepard set with Copycat

data/rulesets.ts
BDSP can't import Pokemon from Home, so it shouldn't grant moves from archaic species types here, e.g. Clefable should not be able to learn Tackle via STABmons Move Legality in these formats because it could never have been a Normal type.
=> Fix BDSP interaction with STABmons Move Legality

data/mods/gen8bdsp/moves.ts
Deoxys is currently unobtainable, which should make psycho boost unobtainable as well.
=> BDSP: Make Psycho Boost Unobtainable

data/mods/gen8bdsp/items.ts
Psychic Seed had incorrect data in the BDSP mod due to its key being misspelled. This commit fixes it.
=> Fix typo of Psychic Seed in BDSP items.ts

data/moves.ts
Reported [here](https://www.smogon.com/forums/posts/9038286).
Although the first Smack Down correctly cancels Fly and Bounce, subsequent uses of Smack Down also need to remove the `twoturnmove` volatile.
=> Repeated Smack Down should still cancel Fly and Bounce each time

data/mods/gen2/formats-data.ts
Correcting oversights on octillery and azumarill movepools, who actually don't learn fire blast and charm, respectively.
=> Gen2 Random battles movesets

config/formats.ts
Revelationmons, the current OMotM, should have Sleep Moves Clause implement, and does not. Proof of the clause can be found here: https://www.smogon.com/forums/threads/revelationmons-omotm-for-december.3692297/
=> Add Sleep Moves Clause to Revelationmons

server/chat-commands/avatars.tsx
`canUse` was replacing `.` for the avatar id which all side server custom avatars have.
=> Fix setting avatars on side servers

data/abilities.ts, sim/pokemon.ts, test/sim/abilities/neutralizinggas.js
On cart, Transforming into Neutralizing Gas isn't enough to actually get it to work. It doesn't stay active at all.
Leaving as a PR for now because the behavior is pretty new and so I want to make sure nothing new crops up in tests that throws a wrench in this implementation.
=> Fix interaction of Transformed Neutralizing Gas

data/moves.ts
Thanks to new research from Anubis, we now know that Max Guard is treated more like a whitelist rather than a "allow all moves that bypass Protect except these" type of check. Because we're pulling this data from BDSP, though, our data doesn't include any of the DLC moves; however, empirical testing helps bridge that gap. This is the list from BDSP:
> 'acupressure', 'afteryou', 'allyswitch', 'aromatherapy', 'aromaticmist', 'confide', 'copycat', 'curse', 'decorate', 'feint', 'futuresight', 'healbell', 'holdhands', 'howl', 'lifedew', 'meanlook', 'perishsong', 'playnice', 'powertrick', 'roar', 'roleplay', 'tearfullook',
These are the additional moves known from empirical testing post-DLC that also bypass Max Guard:
> 'coaching', 'doomdesire', 'gmaxoneblow', 'gmaxrapidflow', 'junglehealing', …
=> Convert Max Guard to a whitelist

server/chat-plugins/repeats.ts
I did not test this code, but I did check to make sure I got the uhtml protocol right (which I did). The only way this could go wrong is if somehow the `repeat#id` property doesn't exist.
=> Use uhtml for repeats to prevent flooding

server/chat-plugins/repeats.ts
I figured instead of writing down all 6 command variations I'd just use regex for this one
=> Extend /repeat multiline pattern for all commands

sim/battle-actions.ts, test/sim/moves/memento.js
Z-Parting Shot and Z-Memento should succeed in healing their targets even if the move fails for some reason (e.g. Clear Body, Substitute). This change directly adds the side condition, rather than replacing it as the current active move (?) which could cause it to fail early and not use the Z-Power when it should always be doing that.
=> Fix interaction of failed Z heal replacements

config/formats.ts
[Details](https://twitter.com/VGCVictoryRoad/status/1477222934523564033)
Officially the series goes from Feb - August 2022, but we like to get the new formats up early. Since this will be the main format throughout the year, VGC is dropping the [Series] prefix for this one and just going with VGC 2022. Once the current format expires in January (Series 11), Series 9 will be namechanged to "VGC 2021" and that will be our permanent legacy format.
I haven't had a chance to talk with the BSS guys about what they want done yet.
=> Implement VGC 2022

data/mods/gen4/moves.ts, test/sim/moves/snatch.js
According to Bulbapedia and the long description of the move here on showdown, Snatch should be able to steal moves that were called by another user of Snatch.
=> Gen 3-4: Fix Snatch when used by multiple pokemon

data/mods/gen1/moves.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9067020
Haze uses `setStatus('')` to clear the status of the opponent. Doing that by itself does not send a message to the client that the status was cleared. This is not a problem for most other places `setStatus('')` is used since they send other client messages that handle removing the status, but it is an issue for Haze (see bug report above).
The way I chose to fix this was to create a new client message `-clearstatus`, which handles silently removing the status of a pokemon. I've changed some occurrences of `clearStatus()` to `setStatus('')` since those moves don't need the extra client message to be sent.
=> Gen 1: Fix visual bug with Haze

data/mods/gen7/moves.ts, data/moves.ts, test/sim/moves/stompingtantrum.js
Mostly, what this PR does is use healing failure messages on moves that don't have straightforward healing (Floral Healing, Heal Pulse, Moonlight, Morning Sun, Shore Up, Swallow, and Synthesis). Instead of giving "But it failed!" it'll show "[POKEMON]'s HP is full!" which matters a bit for revealing Heal Pulse / Floral Healing's target in doubles. Pollen Puff and Jungle Healing also have nonstandard healing failure messages but they were already accounted for.
Since we're talking about healing failure messages, the healing move failures themselves shouldn't double Stomping Tantrum (except for Rest because it wants to be special). Although all of the particular healing edge cases can be set to ``this.NOT_FAIL`` pretty easily, I don't know how to set the general healing cases, like Slack …
=> Fix healing moves to use healing failure messages

lib/sql.ts, server/modlog/index.ts, test/server/modlog.js
This propagates errors to the parent process so promises properly reject. 
In doing so, it also fixes an issue with modlog creating tables several times accidentally in tests (which failed them).
=> SQL: Propagate errors to the parent process

server/chat-plugins/abuse-monitor.ts
Feature requested by Aeonic to handle longer battles (since they can hit few false positives over many turns and cause accidental flags).
=> Abuse-monitor: Support scaling thresholds per-room

server/chat-plugins/daily-spotlight.ts
Prevents an undefined variable from being showcased in source if there is no image being used for the daily.
Before:
After:
=> Spotlights: Don't give an image parameter in source if no image was used

data/mods/gen8bdsp/formats-data.ts
This update is mainly made to tone down the impact of stealth rocks in bdsp rands, most notably by adding defog to all the pokémon who can and want to use it. We're also fixing Registeel in the process and changing Dustox and Tropius completely.
=> BD/SP Random Battle: Update movepools

sim/battle-actions.ts, test/sim/abilities/serencegrace.js, test/sim/abilities/serenegrace.js
For stat increases, and plausibly stat drops, secondaries will overflow when both Serene Grace and Pledge Rainbow are simultaneously active. This is because the variable that stores the value is an unsigned 8-bit integer. The only move this affects is Charge Beam. See the [battle mechanics research thread](https://www.smogon.com/forums/posts/9076566/) for more details on its discovery.
In battle-actions, in addition to the ``secondaries`` function, there's another function called ``selfDrops`` that also checks for secondary chances as far as I can tell, but it seems to be unused throughout the codebase. I have no idea what it does but don't think it needs to be touched here.
=> Implement secondaries stat chance overflow

server/chat-commands/core.ts, server/chat-plugins/helptickets.ts, server/chat.ts, server/global-types.ts, server/room-battle.ts, server/rooms.ts, server/users.ts
This means we shouldn't have more unpleasant issues with changing the types of handlers & missing old uses/runHandler calls.
=> Chat: Properly typecheck Chat.runHandlers arguments

data/mods/sharedpower/scripts.ts
Shared Power currently does not share Cloud Nine or Air Lock's weather suppression, so this should properly fix it.
=> Shared Power: Fix sharing weather suppression

data/mods/ssb/abilities.ts, data/rulesets.ts
Bird-type has caused two recent independent crashes - one with Revelationmons, and one with some unholy combination of Shared Power + Super Staff Bros 4. Both crashes are fixed by not allowing the Bird-type to be set in those scenarios. I also fixed a typo in Revelationmons message at the start of the battle.
=> Fix Bird-type crashes

server/rooms.ts
This seems like a leftover from when bots were ranked above moderators, and nobody ever noticed that that piece of functionality changed. If this is intended then disregard my PR :)
=> Allow bots to receive private mod actions

config/formats.ts
Godly Gift has banned Mantine, King's Rock, Quick Claw, Bright Powder, Lax Incense, and Focus Band. Proof of the bans can be found here: https://www.smogon.com/forums/threads/godly-gift.3660461/post-9106404
=> Godly Gift: Ban Mantine and luck items

server/room-battle.ts
I'm trying to fix the bug where if a user has ticked the "automatically start timer" box, it will display that the timer has started after the battle has ended. To approach this, I want to do the following:
1. When attempting to set timer manually after the battle has ended, fail loudly to only the user.
2. When Config.timer is set to true but the battle has ended, don't send a start timer request at all.
The issue with 1) is apparently when calling ``sendRoom``, in that function, it thinks the user object is ``null`` after a game completes, despite the user existing just fine in the ``playerTable``. The issue with 2) is that the timer is set way before the ``.ended`` state of the battle is updated. So it'll always be false by the end of the constructor and you can't use it to check if …
=> Prevent setting timer after a game has ended

config/formats.ts
Trademarked has recently banned Marowak-Alola and restricted Memento, and the format on Main needs to be updated to reflect this. Proof of bans can be found below:
Marowak-Alola: https://www.smogon.com/forums/threads/trademarked.3656980/post-9107882
Memento: https://www.smogon.com/forums/threads/trademarked.3656980/post-9108680
=> Ban Maro-A, Restrict Memento in TM

config/formats.ts
Trademarked has recently banned Spectrier and Neutralizing Gas, and the ladder format needs to be updated accordingly. Proof of the ban can be found here: https://www.smogon.com/forums/threads/trademarked.3656980/page-8#post-9110545
=> Update Trademarked and Linked Banlists

config/formats.ts
Godly Gift has banned Swift Swim and unbanned Mantine and the server banlist needs to be updated. Proof of the banlist update can be found here: https://www.smogon.com/forums/threads/godly-gift.3660461/post-9115961
=> Godly Gift: Update bans

CODEOWNERS, server/artemis/README.md, server/artemis/index.ts, server/artemis/install, server/artemis/local.ts, server/artemis/model.py, server/artemis/remote.ts, server/artemis/requirements.txt, server/chat-plugins/abuse-monitor.ts, server/chat.ts
This PR both adds a local message classifier, and moves the code for the remote classifier using Perspective to a directory in server/. The local classifier is in server/artemis/local.ts, the remote is in server/artemis/remote.ts. The local classifier uses a python dependency to classify messages - the TS file uses `child_process.spawn` to wrap the script. It is kept in a StreamProcessManager, where each stream spawns an instance of the python process. This is done so the spawning isn't done in the main process, since that causes noticeable lag. The remote code was just copy/pasted from the abuse-monitor chat plugin.
=> Support classifying message toxicity locally

config/formats.ts, sim/team-validator.ts
Allows one to ban abilities without having to go through every single pokemon who has said ability. This also eases complex banning in pokebilities which makes tournament codes exponentially more condensed.
=> Pokebilities: Streamline ability bans

data/mods/gen2/moves.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9116008
Return and Frustration should be able to deal 0 damage (see bug report above for in game footage)
=> Gen 2: Fix Return/Frustration min damage

server/tournaments/index.ts
Requested by tournaments staff and is already used in other rooms with bots. I also fixed the settings permissions because they were never supposed to be accessible to non-ROs
=> Tournaments: Add /recenttours

server/chat-commands/room-settings.ts
This fixes a bug where if Player 1 sets modjoin and turns it off, Player 2 still can't turn it back on.
This doesn't fix everything wrong with modjoin in battles; for example, if Player 1 sets it to +, Player 2 can't set it higher. This is quite minor and requires more reworking than is probably worth for a kinda-deprecated feature.
=> Fix /modjoin in battles

CODEOWNERS, server/artemis/local.ts, server/chat-plugins/helptickets-auto.ts, server/chat-plugins/helptickets.ts, server/chat.ts
This adds a new plugin file, `/chat-plugins/helptickets-auto.ts`, that hooks into the submission functions for text tickets, and attempts to make determinations on the action once submitted. It runs the ticket through a checker function for that type, which determines who to punish & what punishment to make (also attaches proof, a reason, etc). The result of the checker is passed to an action function, which essentially just reimplements certain punishments. It can be toggled to either deal out the punishments itself, or just make recommendations to staff. For a trial period, it will solely make recommendations.
I also added a `Chat.parseArguments` function to parse command targets (formatted like `key1=val1, key2=val2, etc`) into an object for easy usage.
=> Support automatically handling helptickets

config/formats.ts
The retest has concluded, and Fur Coat remains banned while Fluffy goes free.
https://www.smogon.com/forums/threads/metronome-battle-fluffy-fur-coat-retest-voting.3698121/
=> Metronome Battle: Retain Fur Coat Ban

server/chat-plugins/uno.ts
The bug: The turn is always passed to the first in the player list when a user is disqualified from UNO
=> UNO: Fix the turn sequence when a user is disqualified

data/random-teams.ts
This fixes two bugs when using a custom ruleset for Hackmons Cup:
- Pokemon with multiple formes weren't being added to the pool when whitelisted except for formes that *did* have a different `isNonstandard` value (e.g. a ruleset of `-allpokemon, +mewtwo` would *only* add the megas in Gen 8)
- For Pokemon with multiple formes, only the first forme was being added to the pool (e.g. a ruleset of `-allpokemon, +zapdos` would only allow Zapdos instead of having an equal chance to pick Zapdos or Zapdos-Galar)
=> Hackmons Cup: Fix custom un/bans with formes

server/chat-plugins/daily-spotlight.ts
This fixes a bug where the "Refresh" button in the default `/viewspotlights` page would open another tab instead of refreshing the current tab. (e.g. clicking it on `view-spotlights-lobby` would open another tab `view-spotlights-lobby-`)
=> Spotlights: Fix "Refresh" button opening another tab

server/chat-plugins/blackjack.ts, server/chat-plugins/hangman.ts, server/chat-plugins/helptickets.ts, server/chat-plugins/jeopardy.ts, server/chat-plugins/mafia.ts, server/chat-plugins/rock-paper-scissors.tsx, server/chat-plugins/scavengers.ts, server/chat-plugins/trivia/trivia.ts, server/chat-plugins/uno.ts, server/chat-plugins/wifi.tsx, server/chat-plugins/youtube.ts, server/room-battle.ts, server/room-game.ts, server/rooms.ts, server/tournaments/index.ts
Redux of #7716 apparently.
`RoomGame` is now an abstract class with a type parameter for the player class. Because the `makePlayer` method must call the player constructor method directly, it is now an abstract method. Games without their own player class now extend `SimpleRoomGame` which has a default `makePlayer` implementation.
This makes RoomGame subclasses ever so slightly neater: for example, they no longer need to override `players` and `playerTable`.
=> Refactor room games to use generic typing

config/formats.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9154734
[VGC 2012 Rules](http://assets.pokemon.com/assets/cms/pdf/op/tournaments/2012/pokemon_official_tournament_formats.pdf) | [VGC 2013 Rules](https://assets.pokemon.com/assets/cms/pdf/op/tournaments/2013/Play_Pokemon_VG_Rules_and_Formats.pdf)
The bug report claimed that Chatot should not be allowed in 2012 & 2013 but these official rules docs show that it should only be banned in 2013
=> VGC 2013: Ban Chatot

data/abilities.ts, data/conditions.ts, data/items.ts, data/moves.ts
For instance, if you have a Drizzle team in Shared Power, team members sharing Drizzle will show `[object Object]` instead of Drizzle as the ability. Regular formats are unaffected.
=> Fix some ability interactions with OMs

server/chat-plugins/scavenger-games.ts
@Zarel can you patch this after it goes in? since it's used daily by scavs
I think mia got the sort direction wrong when she made the suggestion
=> Scavengers: fix sorting direction

server/chat-plugins/mafia.ts
- Notify players to submit an action or idle upon night start.
- `/mafia prod` reminds players who have yet to submit to submit an action or idle.
- `/mafia action [details]` now records action details. These details may also be inputted in the HTML page.
=> Mafia: Allow action submission details and add /mafia prod

config/formats.ts
https://web.archive.org/web/20090412160033/http://origin.pokemonvgc.com/en/rules/rrg.html
Found the official rules doc, here are the specific things that are getting fixed
- All Rotom formes, including the base, should be banned (previously the formes were banned but not the base)
- Judgment should be banned (rules say that Sketch can only use moves learned by dex numbers 1-492. Arceus is 493 so Judgment can't be used)
- I also explicitly banned Tyranitar even though it's implicitly banned due to `Max Level` being set to 50 so that the validator message could be clearer ("Tyranitar is banned" instead of "Tyranitar must be at least level 55 to be evolved")
=> Fix VGC 2009 bans

data/items.ts, data/mods/gen2/items.ts, data/mods/gen3/items.ts, data/mods/gen4/items.ts, data/mods/gen5/items.ts, data/mods/gen6/items.ts, data/mods/gen7/items.ts, data/mods/gen8bdsp/items.ts, test/sim/dex.js
Various Poke Balls have only been available at one point or another as held items:
- Cherish Ball and Park Ball have never been available
- Dream Ball and Safari Ball are only available as of Gen 8
- Beast Ball, Dream Ball, and Safari Ball aren't available in BDSP
- The Apricorn balls (Fast, Heavy, Level, Love, Lure, and Moon) are only available in Gens 2, 4, and 7-onwards
- Sport Ball is only available in Gens 2, 4, and 8
For Gems, Fairy Gem should be marked as ``Unobtainable``, while everything but Normal Gem should presumably be marked as ``Past``. Fairy Gem was added in Gen 6 but never released, whereas all the other Gems used to be in Gen 5. I know there's a test saying otherwise but I'm pretty sure they should be semantically marked as ``Past`` and the test itself is wrong (checking …
=> Implement held Poke Ball legality

data/items.ts
Manually tested with odd interactions with Red Card and Life Orb/Shell Bell, including the use of ingrain or if the attacking pokemon is the last remaining pokemon on its side. Removed import from npm test in my previous pull request.
=> Fix Red Card's interaction with Life Orb and Shell Bell

data/mods/gen4/abilities.ts, data/mods/gen4/moves.ts, sim/pokemon.ts, test/sim/moves/knockoff.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9056030
Draft for now as I still have to write tests.
Also, I was wondering if a new client message should be created for this. Modifying `-enditem` to make it keep the item for Gen 3-4 knock off would probably break some older replays, which is why I think creating a new client message that specifically handles Gen 3-4 knock off could be a good idea.
=> Gen 3-4: Fix Knock Off mechanics

server/chat-plugins/friends.ts
99% of people will just use the GUI to do the things under the cut, and `!help friends` is something that's broadcasted quite frequently to introduce people to the feature, so this will be far more user-friendly.
=> Friends: Hide advanced commands in help broadcast

data/mods/gen7/moves.ts, data/moves.ts
See cart footage: https://twitter.com/DaWoblefet/status/1370401423377137665
I've restricted this to doubles because the target leak is irrelevant in singles and we don't know how it'd interact in FFA or whatever other formats that don't exist in Gen 8.
=> Gen VIII: Implement Fly animation target leak

data/abilities.ts, data/mods/gen7/abilities.ts, test/sim/abilities/slowstart.js
> If the user holds a typed Z-Crystal and uses a Z-Move based on a special move, Slow Start will also reduce the Special Attack stat for the duration of that move only.
This comes from Bulbapedia and it sounds like I should also be checking `isZOrMaxPowered` but I wasn't sure so I didn't add that check.
=> Fix Slow Start not halving Sp. Atk for special Z-Moves

PROTOCOL.md
The previously shown URL (https://sim.smogon.com/showdown/websocket), along with sim3.smogon.com or sim.psim.us, doesn't work, since it serves a certificate that's only valid for sim3.psim.us, which is also the default domain currently used by the client.
=> Change wss URL in PROTOCOL.md

server/tournaments/index.ts
It's possible that there is an intended reason not to allow this that I don't understand, but the current behavior that disallows directly substituting alts of the same user is overly aggressive and seems like an oversight. If only alts of the same user can be exchanged, there should still be at most one entry per user in a tour after the transaction completes, since their previous alt must also be removed from the tour.
Use case/current problem: sometimes when a user is briefly disconnected after a tour they have entered starts, their tour entry is turned into that of a Guest account which has the same IP as them, preventing them from being able to enter battles. When they request a driver to perform a replacement of the Guest with their real account, the operation is currently blocked …
=> Tours: Enable /tour replace to directly exchange alts

package.json
Now that [`lint` and `full-lint` use the same configuration](https://github.com/smogon/pokemon-showdown/commit/c57fcf25c69454bc8c9a21e183c75cfe75ed68a9), the only difference between them is the `--max-warnings` flag.
This separation causes some problems:
- In small terminal windows, warnings can be obscured by terminal scroll due to the large volume of unit tests. These warnings in turn cause CI failures since GitHub Actions runs `full-lint`.
- When changes to the linting script need to be made, **three** scripts need to be updated. This can lead to oversights such as `full-lint` not being updated for `.tsx` files when JSX support was added.
I've made this a PR in case anyone else has opinions.
=> Combine `lint` and `full-lint` NPM scripts

sim/battle.ts, test/sim/misc/dynamax.js
Talked to @DaWoblefet about this and he felt like the solution I used shouldn't need to be done (manually checking if `runDynamax` is the next action). If someone has input on how speed should be updated for the `runDynamax` action that would be cool.
=> Fix Dynamax not starting in order of most recent speed

config/formats.ts
Kyurem is not banned even though it should definitely be banned.
=> Crazyhouse: Fix banlist

server/tournaments/index.ts
Hi, I'm sure the PR name doesn't really make sense. This fixes the bug I posted here:
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9210558
Basically, prior to this fix, this.fullFormat would get set, and THEN it would check if it would work with formats with generated teams. What happens is, if it doesn't work with those formats, then it throws an error, but this.fullFormat remains, and all players get a "team generator (random) failed using these rules and seed (6503,27336,63804,42074)" error.
This fix holds off on setting this.fullFormat until after generated team formats are checked.
=> Validate tour rules in generator before setting it

config/formats.ts, data/items.ts, data/learnsets.ts, data/mods/gen4/rulesets.ts, data/mods/gen5/rulesets.ts, data/mods/gen7/rulesets.ts, data/mods/gen8dlc1/rulesets.ts, data/pokedex.ts, data/rulesets.ts, sim/battle.ts, sim/team-validator.ts, test/sim/misc/teampreview.js
- Crowned formes will now use `battleOnly` instead of `changesFrom`, which means the validator will handle them similarly to other battle-only formes.
- Before the first switch-ins, base forme Zacian/Zamazenta holding Rusted Sword/Shield will have their species changed to their Crowned formes, abilities changed to Intrepid Sword/Dauntless Shield, and Iron Head changed to Behemoth Blade/Bash.
- This also fixes issue that Zacian/Zamazenta had with Team Preview in Hackmons. Now only the base forme Zacian/Zamazenta will have `-*` appended to their name at Team Preview, while Crowned forme will be shown normally, as you can no longer have Crowned forme at Team Preview unless `Obtainable Formes` is not in the ruleset.
- Most importantly, the convenience feature of being able to select Crowned …
=> Properly handle Zacian/Zamazenta Crowned formes

data/mods/pokebilities/abilities.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-76#post-9207294
Shoutouts to mathfreak for the detailed analysis.
~~This change makes Sheer Force take priority deterministically. Although we can't know for certain how SF 'should' interact with abilities that add secondary effects, it seems logical that affected moves would function like regular SF-compatible moves.~~
I changed my mind after looking into this further:-
https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/page-62#post-8905424
Based on this, it seems that we _can_ know that Stench would activate after Sheer Force on cart if you could somehow have both. Poison Touch still seems to be undetermined behavior but given the above, I think it is …
=> Pokebilities AAA: Fix Sheer Force interaction with abilities that add secondaries

data/mods/pokebilities/abilities.ts
Bug report: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-76#post-9206202
I found some issues, though slightly different to what was reported:-
* The problem is not showing the activation message
* The problem only occurs if Mummy ISN'T the real ability of the target
* The problem only occurs if the random ability chosen to removed from the source is not its real ability
* It can occur regardless of whether the contact move is a pivot or not
This PR also applies the changes from https://github.com/smogon/pokemon-showdown/pull/8207 to the Pokebilities mod.
=> Pokebilities: Fix Mummy

data/mods/pokebilities/scripts.ts, sim/global-types.ts
Bug report: https://www.smogon.com/forums/threads/om-mashup-megathread-pokeaaa-is-leaders-choice.3657159/page-35#post-9212722
---
pokemon.ts
```
formeChange(
speciesId: string | Species, source: Effect = this.battle.effect,
isPermanent?: boolean, message?: string
) {
```
=>
pokebilities/scripts.ts
```
formeChange(speciesId, source, isPermanent?, message?) {
if (!source) source = this.battle.effect;
```
I don't know if there's a better way to deal with "An outer value of 'this' is shadowed by this container."
=> Pokebilities AAA: Fix Ice Face activation timing

data/conditions.ts, data/items.ts, data/mods/gen4/moves.ts, data/mods/gennext/moves.ts, data/mods/ssb/conditions.ts, data/moves.ts, sim/battle-actions.ts, sim/battle.ts, sim/dex-conditions.ts, test/sim/misc/hazards.js
https://github.com/smogon/pokemon-showdown/projects/3#card-23557574
Entry hazards now use a new `EntryHazard` event, which is run immediately after `SwitchIn` and uses a stable sort for its resolution. (String keys in objects are guaranteed to remain in insertion order, and `Array#sort` is guaranteed stable.)
=> Proc hazards in the order they were set

data/pokedex.ts
- Alter Lycanroc-Midnight's evo condition wording to be consistent with other night-time evolutions.
- Add time-based evoCondition to `Raticate-Alola`, `Marowak-Alola`, `Weavile`, `Tyrantrum`, `Aurorus`, `Gumshoos`, `Sneasler`
Some evos already had these, all friendship-based evolutions seemed to have them, and Obstagoon had a time-based evoCondition even though it evolves simply through level.
=> Add missing time-based evoConditions

data/mods/gen1/moves.ts
Jump Kick/High Jump Kick should deal 1 HP recoil upon fail regardless of the target
=> Gen 1: Fix (High) Jump Kick interaction with Ghost-types

config/formats.ts
Adding this clause to these formats can allow Rayquaza to run Dragon Ascent.
=> Add Mega Rayquaza Clause to Gen 6 and 7 Random Battles

server/chat-plugins/datasearch.ts
Some minor changes:
- Add periods to the end of "The parameter '...' cannot have alternative parameters" error messages for consistency with other error messages
- Add error message for using alternative parameters for `monotype` and `natdex` in dexsearch, and `all` and `natdex` in movesearch (as orGroup.skip is set to true for those, similar to the other cases)
- Add "A search cannot include and exclude 'monotype'." error message as it works similarly to the other parameters with that message (just setting a flag rather than adding another orGroup; currently, `/nds mono, !mono` is the same as `/nds !mono` but `/nds !mono, mono` is the same as `/nds mono`)
It might also be helpful to add an error message if the parameter `natdex` or `all` is negated (as e.g. `!natdex` is functionally …
=> Add/modify error messages in dexsearch, movesearch

server/chat-commands/core.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9240009
- Allows anyone to use the command without consent of all players in random battles.
- Now actually sends the button for the other users to consent to the battle log being shared. Previously `battle.players` was being used to loop through all the players, which is empty after the battle has ended. Now `battle.playerTable` is the object that gets iterated over and `Users.get` is called directly instead of `player.getUser`, as `player.getUser` will return null after the battle has ended.
=> Fix /exportinputlog

sim/battle.ts
As far as I know, chainModify() would have never needed to take the ceiling rather than the floor of some modifier like this. I can't think of any particular reason why we would need it; it's pretty old according to git blame, maybe before we understood chaining modifiers well? It's not used anywhere else and I can't find any other history on it besides the [initial commit](https://github.com/smogon/pokemon-showdown/commit/84f983ca06c8f39985e290664a098208c7fad3be) for it, so it may have gone completely unused. Making a PR instead of pushing in case I'm wrong on that.
=> Remove unused ceilModifier event property

config/formats.ts, data/rulesets.ts
https://www.smogon.com/forums/threads/rby-uu-agility-partial-trapping-apt-voting.3703325/page-2#post-9249504
This is going to affect a tournament coming up within the next few days!
I added a rule to rulesets.ts under the assumption this ban may be repeated in other lower tiers. I've seen some groans about it in NU. Technically, only Wrap and Fire Spin are possible alongside Agility; even with Tradebacks, the only new user of this combination is Arcanine with Fire Spin. However, in the spirit of the ban and potential use in something like STABmons room tours, I slapped Bind and Clamp in there as well. Inefficient, but we may as well future-proof.
If the clause name is too long, "APT Clause" is possible, which I think would be understandable at its core. Not sure if I did that …
=> Gen 1 UU: Ban Agility + Partial Trapping

data/mods/gen1jpn/rulesets.ts
Fixing what I reported here: https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/post-9235903
Marty said to just copy the banlist from gen2 and add to it, so here I am!
Details on what's up;
- Before Yellow came out, Nidoran-M learned Double Kick at L42, so Nidoking can never get it alongside Thrash.
- Metapod doesn't learn Harden if evolving from Caterpie prior to Yellow, you have to catch a wild Metapod to have it. Ergo, Tackle and String Shot can't be on the same set.
Extremely minor, but that's most of my pull requests. Thank you for your time!
=> Gen 1: Add incompatibilities to NC97 Move Legality

data/mods/gen1/conditions.ts
sleep checking occurs before burn, poison, and leech seed in game, and the former two are 2 priority where the latter is 1
=> Gen 1: Fix sleep cure priority

data/mods/gen1/conditions.ts, data/mods/gen1/moves.ts, data/mods/gen1stadium/conditions.ts
This resolves two bugs reported here;
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/post-8616259
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-17#post-9252475
If a Pokemon flinches after using Hyper Beam, it should be able to move as normal thereafter. This is a mechanic seen in the disassembly as Enigami points out in the link above. Now, implementing this with the client removing the "mustrecharge" tag would be bad, but luckily, it seems my implementation method keeps it up on the client end, preventing a potential info leak. I've added an empty command in gen1stadium to prevent this from being inherited there, as from what I can tell it doesn't happen. Let me know if that's wrong.
This mechanic should rarely come up …
=> Gen 1: Fix flinch interaction & Mist

data/mods/gen1/formats-data.ts, data/mods/gen1/random-teams.ts
TLDR; Victreebel UU, Slowbro/Lapras UUBL
This is important for the upcoming UU Open and UU Snake Draft! 
https://www.smogon.com/forums/threads/rby-ou-viability-rankings.3685861/page-5#post-9254185
The new 2022 RBY OU VR was just released, and some tier shifts have occurred;
- Lapras and Victreebel are dropping to UU properly now. 
- Slowbro is...being Slowbro.
Slowbro is in its own rank on the VR, but it's juuust slim enough for it to drop to UU, according to phoopes and vapicuno, at least by the quantitative metrics we're using. There's a deep-seated tradition of "The Slowbro Standard" but it's finally crumbled. 
**However, the RBY UU Council has quickbanned Lapras and Slowbro** because, well, yeah...they're very meta-warping, so on, blah blah. Victreebel lives though! There'll be a post …
=> Gen 1: 2022 OU tier shift

server/chat-commands/info.ts
"inverse" is a format so it was getting removed by splitFormat. Now /weak will work even while Inverse is OMotM.
=> Fix "inverse" argument in /weakness

data/mods/gen2/learnsets.ts
Didn't think my weird rabbit hole would bring me here. ANYWAY!
So for starters, here's the source of the information: 
https://projectpokemon.org/home/forums/topic/41541-information-about-japanese-pm1-pm2-event-pok%C3%A9mon/?do=findComment&comment=258412
I would frankly trust this person with my life, they've done a lot for documenting Gen 1 events in the past. 
Because it's level 15, it can't have Tackle without a move relearner. It seems that this Magikarp is designed to have Dragon Rage be incompatible with Tackle, being "stronger than normal", so to speak. This makes sense, it lines up with the way the anime describes it among other things. 
Another incredibly minor fix that will only impact the memesters who want to use joke Pokemon in a very obscure format!
=> Gen 1: Fix Tamamushi Magikarp details

server/chat-commands/avatars.tsx
The Gen 3 avatars are hidden as well
=> /avatars: Fix minor error in the description

config/formats.ts, sim/side.ts
https://www.smogon.com/forums/threads/jump-magikarp.3704588/
This isn't complete, because we don't really have a way of enforcing "you must bring Magikarp" - or any "you must bring [Pokemon]" logic at all. I think we should just use standard PS timer and ignore the complications of implementing the VGC timeout logic at Team Preview with this, but that still doesn't solve the issue with forcing a player to bring Magikarp. I'm not even sure where to put the hardcode if we want to go that route.
=> Add Jump! Magikarp format

data/mods/gen1/moves.ts, data/mods/gen1stadium/moves.ts
This resolves one of the bug reports from years ago [here](https://www.smogon.com/forums/threads/stadium-bug-report-thread.3526616/#post-6144617).
In RBY, when you're at exactly 25% HP and use Substitute, your Pokemon faints. This is implemented, but [in a very strange way](https://replay.pokemonshowdown.com/gen1stadiumou-1616377078) that causes the Pokemon to faint before the Substitute is put in. I found this by accident while testing and realised it was due to a (presumably) unnecessary check, so I removed it, as the second line would faint the user in a much funnier fashion anyway. 
Here's the code working, using only the second line and thus having the Substitute animate, which from what I know is accurate to the cartridge in the first place; …
=> Gen 1: Fix RBY & Stadium Substitute @ 25%

data/mods/gen7/factory-sets.json
Jumpluff has 252 spdef EVs that should be speed. https://www.smogon.com/dex/sm/pokemon/jumpluff/
- Wigglytuff
=> Fix Jumpluff EVs

data/mods/gen1/formats-data.ts
https://www.smogon.com/forums/threads/slowbro-and-the-ou-uu-cutoff.3704191/post-9278948
The "situation" was resolved and Slowbro is being maintained as OU. What a bother...
=> Gen 1: Move Slowbro to OU

data/mods/gen8bdsp/formats-data.ts, server/chat-plugins/datasearch.ts
Currently, running any of `/nds !pivot`, `/nds !recovery`, `/nds !zrecovery`, and `/nds !priority` results in "No Pokémon found.". This is because they are adding an empty DexOrGroup
```js
{
abilities: {},
tiers: {},
doublesTiers: {},
colors: {},
'egg groups': {},
formes: {},
gens: {},
moves: {},
types: {},
resists: {},
weak: {},
stats: {},
skip: false
}
```
to `searches`, which naturally no Pokémon can satisfy and therefore eliminates all possibilities. This change sets `skip` to `true` for these empty DexOrGroups so that they will be ignored when finding possibilities.
=> Fix !pivot, !recovery, !zrecovery, !priority in dexsearch

data/moves.ts, sim/battle-actions.ts, sim/battle.ts, sim/dex-moves.ts, test/sim/moves/futuresight.js
[https://github.com/smogon/pokemon-showdown/projects/3#card-70965392](https://github.com/smogon/pokemon-showdown/projects/3#card-70965392)
This adds a new attribute ```recentForme``` to ```ActiveMove```, letting it store the forme of the Pokemon which used the move. This variable is updated with the latest form if the future attack's user is still on the field. The code now passes the previously skipped unit test in futuresight.js.
=> Fix damage from future attacks

config/formats.ts
After a recent definition change, BDSP PH is being replaced with Sw/Sh PH. This commit is to remove BDSP PH from the challengeable list and replace it with Sw/Sh PH. Announcement can be found here: https://www.smogon.com/forums/threads/pure-hackmons.3656851/post-9279060
=> Replace BDSP PH with Sw/Sh PH

server/chat.ts
This is so subfolders with similarly named files (like `trivia/database.ts` and a `plugin/database.ts`, any `index.ts`, etc) won't get overridden in `Chat.plugins`.
=> Chat: Properly handle subfolders when assigning plugin names

server/chat-commands/info.ts, server/chat-plugins/abuse-monitor.ts, server/chat.ts
This allows people to select a format and toggle clauses/rules/bans/value rules easily, rather than just having to _know_ the syntax offhand. I couldn't simplify bans any further, so I put an explanation of the syntax on there. For the rest, I added checkboxes for clauses and checkboxes/input tags for value rules.
This was suggested [here](https://www.smogon.com/forums/threads/ability-to-create-custom-formats-via-a-format-builder-tool.3704660/).
Some screenshots:
Base page where one selects a format: https://user-images.githubusercontent.com/49593536/179430289-20b58323-99e3-4aee-b74c-e0efaff7cab8.png
Main page: https://user-images.githubusercontent.com/49593536/179430297-72228ac7-4fea-4478-9afd-d662abed4582.png
A snippet of the clause editor: …
=> Add a GUI for using custom rules

data/mods/gen7/factory-sets.json
Quagsire remains banned after an initial ban and subsequent retest (https://www.smogon.com/forums/threads/sm-uu-quagsire-revote.3702984/page-2). It should stay banned for the foreseeable future so I'm removing it from the UU tier of BF.
\- Wigglytuff
=> Gen 7 Battle Factory: Remove Quagsire from UU

config/formats.ts
Bug report: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-76#post-9205832
Replays: https://replay.pokemonshowdown.com/gen8pokebilities-1566499155-msrutjsdz77jinmo32cqlmy1swgaajspw
https://replay.pokemonshowdown.com/gen8pokebilitiesaaa-1573974793-fg5n05q18nzvsxk8ky8mfdibsww7558pw
Intimidate can activate from one side's onSwitchIn before the other side has received its counter-ability volatile from its own onSwitchIn, so it seems like at least some abilities need to be applied before this. However, just moving all addVolatiles to onBeforeSwitchIn would make the timing of abilities that are announced on switch-in incorrect.
It would be good if there is a less janky way to address this, especially since it's possible that there might be an …
=> Pokebilities: Fix Intimidate counters

config/formats.ts
The latest series allows all Pokemon from Sword/Shield, including Mythicals. There is no limit on how many "restricted" or "mythical" Pokemon you can bring.
Don't merge yet; currently debating the format name for VGC because:
- This would technically be the 2023 format for the circuit
- It assumes this actually will be what we play for VGC (we might continue with standard VGC 2022 [i.e. Series 12] for the rest of our in-person competition)
=> VGC/BSS: Add Series 13 support

server/room-battle.ts
The message "You cannot join this battle, as you were not originally playing in it" should display if and only if the battle was restored from a reset and hasn't already resumed. Adding players for reasons such as /leavegame substitution and /importinputlog will work again.
=> Fix adding players in 2-player battles

server/chat-commands/moderation.ts
This fixes a bug where subrooms would cause the "Names in **bold** are online" message to appear twice (or potentially more for nested subrooms). Additionally, I moved the message to a separate line for clarity.
=> `/roomauth`: Fix duplicate "names in bold" message

server/chat-plugins/scavengers.ts
Apparently the clamp was [1, N], not [0, N-1]
=> Scavengers: Fix startrecycled/queuerecycled index

data/mods/gen1jpn/rulesets.ts, data/mods/gen2/rulesets.ts
So I realised that #8821 missed out on actually making the combination of Tackle and Dragon Rage illegal on Magikarp, which was kind of the point of what I was doing, so that was pretty dumb. Anyway, I also looked into the [Fan Club Chairman stuff](https://bulbapedia.bulbagarden.net/wiki/List_of_Japanese_event_Pok%C3%A9mon_distributions_(Generation_I)#Pok.C3.A9mon_Stamp_Pok.C3.A9mon) and realised they have similar issues, so let's sort this out.
- Rapidash is given at L40 with the moveset of Ember, Fire Spin, Stomp, and Pay Day. This means Growl and Tail Whip are impossible.
- Fearow is given at L25 with the moveset of Growl, Leer, Fury Attack, and Pay Day. This means Mirror Move(!) and Peck are impossible.
- Magikarp is given at L15 with Splash and Dragon Rage, with Tackle purposefully …
=> Gen 1 JPN: Japanese event move incompatibilities

data/rulesets.ts
Battles with both Team Preview and Team Type Preview send the teams twice, which causes duplicated Pokemon to appear. While it may be desirable to have some sort of exclusivity with different types of Team Preview, adding a `clearpoke` fixes the bug on our client. Replay demonstrating the bug: https://replay.pokemonshowdown.com/gen81v1-1643744004
=> Fix duplicated team display with Team Type Preview

server/chat-plugins/datasearch.ts, test/server/chat-plugins/datasearch.js
Steam Engine's ability having 'Fire/Water' meant '/as water' was not returning the ability.
=> Fix abilitysearch for special char separators

config/formats.ts
This can be merged September 1 with any other tier/format changes.
We have found out from TPCi that in fact, no official VGC events will occur between now and January 1. The VGC community has sort of been looking for its identity in the meantime and seems to have settled on Spikemuth Cup as its primary format of choice. Several of the major VGC platforms (e.g. Victory Road, Smogon, and Desafío LATAM) have decided to adopt Spikemuth Cup for their tournaments. This is doubles, unlike the singles online cart tourney. Spikemuth Cup was a popular in-person side event at some of our recent majors ([NAIC](https://www.pokemon.com/us/play-pokemon/internationals/2022/north-america/side-events/#pokemon-sword-and-pokemon-shield-side-events), …
=> VGC/BSS: Enable Series 13 ladders, add Spikemuth Cup

data/mods/gen1/formats-data.ts, data/mods/gen1/random-teams.ts
Remove shitmons (magikarp/caterpie/metapod/weedle/kakuna) from gen1 randbats, and consequently remove all special rules relating to them.
https://discord.com/channels/294651453279174656/809413397840920586/1015676792763322378
=> Gen1 Random Battles: Remove shitmons

config/formats.ts, data/rulesets.ts
My friend daiginjou brought up the realisation to me that this was a problem with the simulation, so I am putting this in.
Back in the day, Stadium Sleep Clause was the "correct" Sleep Clause, counting Rest. Thus, it makes no sense not to count Rest here, as Smogon (which popularised the change) didn't exist yet, NC2000 runs the Stadium version, all context shows otherwise, and the Japanese scene prefers it done this way. 
I changed the wording on the activation of the clause which should remain un-confusing while being inclusive towards NC97.
=> NC97: Run the correct Sleep Clause

server/chat-formatter.ts
Typing something like "spiderman.jpg" is very often used to reference a meme or other image without actually linking or embedding it. However the link regex treats these like .jp links which is never intended.
=> Chat: Don't hyperlink parts of words with common TLDs
