- server/chat-plugins/scavenger-games.ts
- server/chat-plugins/scavengers.ts
- server/rooms.ts
> Scavengers: initialize all settings as null

- server/chat-plugins/scavengers.ts
I have no excuses for this blatant mistake that happened in the place where I tried to bypass typescript.
~~meow please dont punish me~~
> Initialize scavSettings properly

- server/chat-commands/moderation.ts
Per https://www.smogon.com/forums/threads/increase-chatroom-autojoin-limit.3657450 and mc56556's conversations with dev staff
> Increase autojoin limit to 15

- server/chat-plugins/trivia.js
This new mode was requested by the Trivia staff + approved by ROs.
> Trivia: add Triumvirate mode

- server/chat-plugins/trivia.js
Weakest Link is no longer played in the Trivia room and the ROs agreed that it'd be ok to remove it.
> Trivia: remove Weakest Link

- data/formats-data.ts
- data/learnsets.ts
> Gmax Meowth is available from raids

- server/chat-plugins/youtube.ts
> Youtube: Error out if there are no channels in the database

- config/formats.js
Doubles OU: https://www.smogon.com/forums/threads/np-ss-dou-stage-2-out-of-my-league.3664997/
National Dex: https://www.smogon.com/forums/threads/national-dex-mega-metagross-suspect-voting.3664720/page-3#post-8478583
> Update suspect notices

- data/formats-data.ts
- data/random-teams.ts
thanks to the doubles community for most of these suggestions.
> Random Doubles Update

- server/chat-plugins/trivia.js
Requested change by Trivia ROs
> Trivia: improve help and allow changing answers in Triumvirate

- server/chat-plugins/datasearch.ts
As per [this suggestion](https://www.smogon.com/forums/threads/ability-search-command.3665079/). I didn't implement Pokémon searching because, as said in the thread, one can just `/dt` the Pokémon to see its abilities.
> Datasearch: add /abilitysearch command

- server/chat-plugins/datasearch.ts
This was suggested [here](https://www.smogon.com/forums/threads/add-targets-as-a-parameter-on-ms.3665018/).
> Datasearch: support searching for moves by target and use sendReplyBox for movesearchhelp

- data/formats-data.ts
- data/random-teams.ts
prevent Whirlpool-less Azumarill by rejecting Toxic if Rest & Fairy
> Random Singles & Doubles Fixes

- server/chat-plugins/trivia.ts
room.getGame always returned null, since trivia games have different constructor names, so no one could join and no games could be ended.
> Trivia: Fix bug in getting the game

- server/chat-plugins/room-events.ts
- server/rooms.ts
As per [this suggestion](https://www.smogon.com/forums/threads/support-renaming-events-in-roomevents.3663574/).
> Room events: Support aliases and renaming

- server/chat-plugins/calculator.ts
I felt this might be useful for doing math with memory addresses in hex (which I have seen some people do occasionally) or maybe doing some bit shuffling for whatever reason. Since JS supports binary, octal, decimal and hex literals, that's the ones I allowed as outputs.
> Support different output number formats in /math

- config/formats.ts
https://www.smogon.com/forums/threads/camomons.3656413/page-4#post-8486823
> Camomons: Ban Dracovish

- data/formats-data.ts
Libero is gonna be fun.
Edit: source: https://twitter.com/SerebiiNet/status/1267810302713671680?s=19
(Thanks, xJoelituh)
> Hidden Ability Starters

- server/chat.ts
Currently, they just don't do anything, and it's difficult to tell if it's crashed for some.
> Chat: Make HTML pages display an error on crash

- server/chat-commands/info.ts
- server/chat-plugins/room-events.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8488586 Might not work but it's worth a shot.
I literally just looked at all the html bits and edited it, i still don't know how events are stored or anything, please feel free to edit if I'm being stupid, UwU.
> Remove event aliases if none exist.

- server/chat-plugins/scavenger-games.ts
- server/chat-plugins/scavengers.ts
Add Team Scavs as well as the necessary supporting commands.
This has Meicoo-chan's seal of approval!
> Scavengers: new game mode

- server/chat-plugins/room-events.ts
Fixes the bug seen in the screenshot, where aliases are displayed for some events but not others, and thus descriptions are shown as aliases (and dates as descriptions).
> Roomevents: Fix bug with not displaying aliases

- data/mods/gen5/formats-data.ts
- data/mods/gen5/random-teams.ts
movepool edits made by deliberation with randbats staff experienced in gen 5
this is the last time i'm not using vscode i s2g
> Update Gen 5 Random Battle

- config/formats.js
- server/chat-commands/room-settings.ts
Per the suggestion [here](https://www.smogon.com/forums/threads/minimize-roomintro-code.3664984/).
> Support minimizing roomintro/staffintro source code

- lib/net.ts
- lib/streams.ts
- server/chat-plugins/tcgtabletop.ts
- server/ladders-remote.ts
- server/loginserver.ts
Config setting name is tentative.
Loginserver error handling might be done a little bit better, so if anyone has a better idea let me know ig. 
It functions normally, however.
Fixes #6691
> Add a library for making HTTP/S requests 

- server/chat-plugins/scavenger-games.ts
- server/chat-plugins/scavengers.ts
- Improve display + fix minor bugs + fixing a possible crash that could happen if staff remove people halfway through team scavs.
> Scavengers - minor fixes

- server/chat-commands/core.ts
The comment was already fixed in PR #6484.
> Remove last vestige of Pokebank

- config/formats.ts
as per https://www.smogon.com/forums/threads/tier-shift-om-of-the-month.3662165/page-2#post-8490625
<sub>(salty i lost like 5 minutes on a scavenger hunt that asked about the banlists but i referred to the server code instead of smogon thread)</sub>
> Tier shift: Ban Eviolite

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-pu-stage-1-la-devotee-golurk-and-gapidash-banned.3661966/page-4#post-8494713
> Move Galarian Rapidash and Golurk to PUBL

- config/formats.ts
- data/formats-data.ts
https://www.smogon.com/forums/threads/ss-dou-melmetal-voting.3665737/post-8495347
> Move Melmetal to DUber and remove suspect notice

- server/chat-commands/info.ts
I wasn't really sure how to word the commit message for this, but I did my best.
> Add /dt(gen) as an alias to use /details for a gen

- server/chat-plugins/scavengers.ts
> Scavengers: fix /scavtop error due to auth/settings refactor

- config/formats.ts
As approved by Doubles OU tier leader MajorBowman: https://www.smogon.com/forums/threads/bw-doubles-ou.3606719/post-8498509
> BW DOU: Unban Sky Drop, ban Gravity

- server/chat-plugins/datasearch.ts
Fixes [this bug](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-3#post-8469484). Supersedes #6774 since the author of that didn't want to work on it anymore.
> Datasearch: Fix maxgen and learnset interaction

- server/chat-plugins/modlog.ts
> Modlog: Escape search terms

- server/chat-plugins/scavengers.ts
Was missing the showHints parameter.
> Show given hints on /scav hint

- server/chat-commands/info.ts
> Fix minor issues with /show commands

- data/formats-data.ts
HA Galarian Slowpoke line is obtainable (confirmed by @Lusamine)
> Fix Zarude-Dada, Galarian Slowpoke, and Galarian Slowbro

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-nu-stage-1-criminal-drought-banned.3660646/page-3#post-8507589
> Move Chansey to NUBL

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-ru-stage-1-i-lost-something-in-the-hills-isle-of-armor-out-chansey-quickbanned-see-post-146.3659533/page-6#post-8507682
> Move Chansey to RUBL

- data/pokedex.ts
See datamine: https://gist.githubusercontent.com/SciresM/71a38bcdd4717771afa8948532aabc0c/raw/3cb6be3fbdfda4453dcd6c2809c9bf92afa3a405/Pokemon%2520-%2520Sword%25201.2.0.txt
> Fix Kubfu Base Stats

- data/moves.ts
Steel Roller currently can be used even when there's no terrain
> Fix Steel Roller

- config/formats.ts
https://www.smogon.com/forums/threads/the-bunny-is-gone-cinderace-quickbanned.3666206/#post-8508622
> 1v1: Ban Cinderace

- config/formats.ts
https://www.smogon.com/forums/threads/national-dex-uu-metagame-discussion-alakazam-banned-110.3660920/page-5#post-8508751
> National Dex UU: Ban Alakazam

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-ss-uu-stage-5-change-is-gonna-come-chansey-banned.3666248/#post-8510094
> Move Chansey to UUBL

- config/formats.ts
https://www.smogon.com/forums/threads/almost-any-ability.3656414/page-4#post-8511383
> AAA: Ban Urshifu and Urshifu-Rapid-Strike

- data/moves.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-12#post-8510904
> Rising Voltage boost applies if target is grounded

- config/formats.ts
https://www.smogon.com/forums/threads/stabmons.3656429/page-3#post-8512574
> STABmons: Ban Gengar

- config/formats.ts
https://www.smogon.com/forums/threads/national-dex-uu-metagame-discussion-thundurus-therian-scolipede-banned-115.3660920/page-5#post-8512603
> National Dex UU: Ban Scolipede and Thundurus-Therian

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-nu-stage-1-criminal-indeedee-f-and-porygon2-banned.3660646/page-3#post-8512853
> Update tiers for various Pokemon

- config/formats.ts
https://www.smogon.com/forums/threads/the-bunnies-are-gone-cinderace-magearna-quickbanned.3666206/#post-8512897
> 1v1: Ban Magearna

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-ru-stage-1-i-lost-something-in-the-hills-indeedee-m-banned.3659533/page-6#post-8513573
> Ban Indeedee-M from RU

- config/formats.ts
https://www.smogon.com/forums/threads/2v2-doubles-leaders-choice.3656321/page-14#post-8514784
> Add 2v2 Doubles suspect notice

- config/formats.ts
https://www.smogon.com/forums/threads/stabmons.3656429/page-4#post-8516124
> STABmons: Ban Porygon-Z

- config/formats.ts
- data/formats-data.ts
https://www.smogon.com/forums/threads/lc-tiering-info.3658274/#post-8516017
> LC: Unban Vulpix

- server/chat-commands/info.ts
suggested at https://www.smogon.com/forums/threads/abbreviate-servertime.3666028/ seems simple and harmless
> Add st as servertime alias

- server/roomlogs.ts
Fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8469316 turns out it was simple enough for me to fix myself
> changeuhtml should send /uhtmlchange not /uhtml

- data/mods/gen3/items.ts
Reported [here](https://www.smogon.com/forums/posts/8517563).
> Fix Gen 3 Metal Coat's description

- server/chat-plugins/datasearch.ts
also piggybacked a fix for /as in here
> Datasearch: support 'monotype' parameter in /ds

- data/formats-data.ts
https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/#post-8520811
> Move Thievul to PUBL

- config/formats.ts
https://www.smogon.com/forums/threads/1v1-old-gens.3646875/post-8518470
> DPP 1v1: Ban Snorlax

- data/abilities.ts
- data/items.ts
PR #6928:
> I also assumed that Custap Berry, should it ever be released, will activate in preference to Quick Draw.
Me and my big mouth... Anubis later proved me wrong again. This backs out the changes to Quick Draw and applies them to Custap Berry instead.
> Adjust fractional priority for very latest research

- server/chat-plugins/youtube.ts
> Youtube: Allow drivers to use /youtube update

- server/chat-commands/info.ts
> Fix /viewapprovals

- config/formats.ts
- data/formats-data.ts
https://www.smogon.com/forums/threads/usage-based-tier-update-for-july-2020.3666712/
> July tier shifts

- config/formats.ts
https://www.smogon.com/forums/threads/national-dex-uu-metagame-discussion-thundurus-therian-scolipede-banned-115.3660920/page-5#post-8523718
> Fix National Dex tiering (again)

- config/formats.ts
https://www.smogon.com/forums/threads/stabmons.3656429/page-4#post-8524793
> STABmons: Restrict Wicked Blow

- config/formats.ts
https://www.smogon.com/forums/threads/linked-leaders-choice.3660421/#post-8375585
> Linked: Fix banlist

- config/formats.ts
- data/aliases.ts
- data/mods/megamax/abilities.ts
- data/mods/optimons/abilities.ts
- data/mods/optimons/pokedex.ts
- data/mods/optimons/scripts.ts
https://www.smogon.com/forums/threads/more-balanced-hackmons-now-has-a-perma-ladder-leaders-choice-challenge-format.3666443/#post-8525450
> Add the other Pet Mod formats

- config/formats.ts
https://www.smogon.com/forums/threads/1v1-old-gens.3646875/page-7#post-8525975
> BW 1v1: Ban Cottonee

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-ss-uu-stage-5-change-is-gonna-come-drops-unbans-see-post-30-bans-in-post-93.3666248/page-4#post-8528610
https://www.smogon.com/forums/threads/np-ru-stage-2-lights-out.3666733/#post-8528629
> Update UUBL and RUBL

- server/chat-plugins/othermetas.ts
> Add command for cross evo

- data/mods/megamax/scripts.ts
https://www.smogon.com/forums/threads/megamax-pet-mod-of-the-season.3658623/page-11#post-8525900
> Megamax: Add Hone Claws to Grimmsnarl

- server/chat-plugins/trivia.ts
This will make it so that creating a Trivia game in a random category won't select the same category as the last game. (And if the last game was in the All "category", it's free to select any category.)
> Trivia: Changes to the random category selector

- server/chat-plugins/mafia.ts
> Mafia: Make CS indication more obvious for hosts

- server/chat-plugins/daily-spotlight.ts
As per the suggestion [here](https://www.smogon.com/forums/threads/allow-one-queued-daily-to-be-swapped-out-for-another.3666432/).
> Daily spotlights: Add queue management commands

- data/formats-data.ts
https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/#post-8530565
> Move Orbeetle and Rotom-Frost to PUBL

- config/formats.ts
https://www.smogon.com/forums/threads/cross-evolution-om-of-the-month.3657562/page-4#post-8530150
> Cross Evolution: Update bans

- server/chat-plugins/uno.ts
- test/server/rooms.js
This includes:
- adding timestamps to all playerlogged actions
- changing the background color from green to blue
- adding proper CSS to the buttons
- adding a "Join as a Spectator" button to the signups
- fixing grammatical errors and redundancies
- making the height of the "UNO!" button taller so players can click it more easily when chat scrolls
- increasing the default playercap from 6 to 12
- adding an `/uno setcap` command so people can adjust the playercap without having to end the game and create a new one (or use eval like Hoeen)
> Make improvements to the UNO game

- server/chat-plugins/room-events.ts
This should fix the crashes currently occurring on PS!
> Roomevents: Delete events fully

- data/moves.ts
- data/scripts.ts
- sim/battle.ts
- test/sim/misc/fusion-combo.js
Fixes https://github.com/smogon/pokemon-showdown/projects/3#card-25870231
> Fix Fusion Bolt + Fusion Flare interaction when the first move fails.

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-nu-stage-2-dont-start-now-gallade-banned.3666717/#post-8533561
> Move Gallade to NUBL

- data/formats-data.ts
https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/#post-8535959
> Move Butterfree and Kangaskhan to PUBL

- config/formats.ts
- data/mods/mixandmega7/items.ts
- data/mods/mixandmega7/scripts.ts
> Add SM Mix and Mega

- server/chat-commands/core.ts
- server/chat-commands/info.ts
- server/chat-commands/moderation.ts
- server/chat-commands/room-settings.ts
- server/chat-plugins/announcements.ts
- server/chat-plugins/blackjack.ts
- server/chat-plugins/hangman.ts
- server/chat-plugins/helptickets.ts
- server/chat-plugins/poll.ts
- server/chat-plugins/room-events.ts
- server/chat-plugins/room-faqs.ts
- server/chat-plugins/scavengers.ts
- server/chat-plugins/thing-of-the-day.ts
- server/chat-plugins/trivia.ts
- server/chat-plugins/uno.ts
- server/chat-plugins/wifi.ts
- server/chat-plugins/youtube.ts
- server/chat.ts
- server/tournaments/index.ts
Removes the extra parentheses in global demote message and adds a missing space in modlog.
> Minor cleanup of global demotion messages

- config/formats.ts
https://www.smogon.com/forums/threads/national-dex-uu-metagame-discussion-thundurus-therian-scolipede-banned-115.3660920/page-6#post-8539348
> National Dex UU: Ban Kyurem and Gengar

- data/moves.ts
This will accurately mirror how Max Moves called by Multi-Attack work in the S/S games.
> NatDex: Correct Hidden Power/Judgment Max Power

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-ss-uu-stage-5-change-is-gonna-come-mamoswine-unbanned.3666248/page-8#post-8542265
> Move Durant to UUBL

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-ru-stage-2-lights-out-machamp-banned.3666733/page-2#post-8542624
> Move Machamp to RUBL

- data/mods/optimons/abilities.ts
- data/mods/optimons/moves.ts
- data/mods/optimons/pokedex.ts
- data/mods/optimons/scripts.ts
https://www.smogon.com/forums/threads/gen-8-optimons-dlc-slate-1.3657509/page-10#post-8537829
> Optimons: Add new optimizations

- data/formats-data.ts
https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/#post-8543010
> Move Exeggutor, Ninjask, and Perrserker to PUBL

- config/formats.ts
- data/rulesets.ts
Adds Armor Beginnings: https://www.smogon.com/forums/threads/3667440/
> Add Armor Beginnings Online Competition

- config/formats.ts
https://www.smogon.com/forums/threads/linked-leaders-choice.3660421/page-4#post-8542921
> Linked: Restrict Trick Room

- config/formats.ts
https://www.smogon.com/forums/threads/ss-ubers-stage-2-baton-pass-voting.3667563/page-3#post-8543640
> Ubers: Ban Baton Pass

- config/formats.ts
https://www.smogon.com/forums/threads/np-ss-ou-suspect-process-round-5-switching-gears.3667669/
> Add OU suspect notice

- data/aliases.ts
I use this a lot, figured there was no harm in adding it
> Add bde alias for Baby-Doll Eyes

- server/chat-commands/admin.ts
https://www.smogon.com/forums/threads/add-a-command-for-bots-to-send-users-html-rooms.3666630/#post-8521882
> Add a command for bots to send HTML pages

- server/chat-commands/admin.ts
suuuuuper minor but inaccurate thing.
> Remove mention of chat.commands.js from /hotpatch's help

- data/conditions.ts
- sim/pokemon.ts
> Fix Gigantamaxing

- server/chat-plugins/trivia.ts
Also, now that we track the user who created a game, we can conform better to modlog conventions!
> Trivia: Show creator in /trivia history

- config/formats.ts
https://www.smogon.com/forums/threads/gen-8-more-balanced-hackmons-v2-natdex-bh.3658587/page-5#post-8548472
> National Dex BH: Ban Shell Smash

- server/chat-commands/moderation.ts
Minor QOL thing that's slightly annoying.
> /hidetext: Don't highlight the user

- config/formats.ts
This fixes an issue with Inheritance's validation and removes a crash that occurs when Shared Power is added to randomized formats.
> Fix Inheritance and Shared Power

- data/mods/mixandmega7/scripts.ts
- data/scripts.ts
- server/chat-commands/core.ts
- server/chat-commands/info.ts
- server/chat-formatter.ts
- server/chat-plugins/chatlog.ts
- server/chat-plugins/hosts.ts
- server/tournaments/index.ts
- sim/battle.ts
- sim/pokemon.ts
Basically I went through the warnings at https://lgtm.com/projects/g/smogon/pokemon-showdown/alerts (which is linked in our README.md), and fixed the ones that weren't extraneous.
> Minor code quality improvements based on LGTM

- config/formats.ts
https://www.smogon.com/forums/threads/np-ss-dou-stage-3-awful-ever-after.3668046/
> Add Doubles OU suspect notice

- server/chat-plugins/scavengers.ts
- Add new command to directly stuff a hunt back into the queue
- Better queue response
- Fix extra spaces in teamscav team names
- Get rid of some old code tidbits that were neccessary when roomlogs were still bork
> Scavengers: general improvements

- config/formats.ts
as per https://www.smogon.com/forums/threads/2v2-doubles.3656321/post-8553113
> Detach 2v2 banlist from doubles tiering

- server/room-battle.ts
Merges stuff from #7005 and #7068 by @Zarel's request.
> Room-Battle: Improve API

- data/mods/megamax/items.ts
- data/mods/megamax/pokedex.ts
- data/mods/megamax/scripts.ts
- data/mods/optimons/scripts.ts
This will make future client support more compatible
> Add some QoL improvements for Pet Mods

- data/formats-data.ts
https://www.smogon.com/forums/threads/usage-based-tier-update-for-august-2020.3668113/
> Mamoswine should be RU

- config/formats.ts
https://www.smogon.com/forums/threads/godly-gift-om-of-the-month.3660461/
> Moody should be banned from Godly Gift

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-ru-stage-2-lights-out-rubl-drops-see-post-73.3666733/page-3#post-8555438
> Drop Pokemon down to RU from RUBL

- data/formats-data.ts
https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/#post-8555593
> Move Flapple/Thievul to PUBL, Gourgeist-XL to PU

- test/main.js
- test/server/chat-plugins/hosts.js
- test/server/chat-plugins/trivia.js
This solves issues like https://github.com/smogon/pokemon-showdown/pull/7100#discussion_r463922425 and makes it easier to test chat plugins.
> Tests: Support requiring Config at the top level

- server/rooms.ts
due to my recent, um, mishap, pre thought this would be a good idea and it was relatively easy to do.
> Support forcing a crash to be private with configurable terms

- config/formats.ts
- data/formats-data.ts
https://www.smogon.com/forums/threads/ss-ou-suspect-process-round-5-voting.3668286/page-7#post-8558727
https://www.smogon.com/forums/threads/cinderace-is-now-banned-from-ou.3668320/
> Move Magearna and Cinderace to Ubers

- data/moves.ts
This is getting cut off, as seen below
> Shorten the description of Steel Roller

- config/formats.ts
https://www.smogon.com/forums/threads/inverse-leaders-choice.3666858/page-2#post-8558749
> Inverse: Unban Cinderace

- CODEOWNERS
- server/chat-commands/room-settings.ts
- server/chat-plugins/help.ts
- server/chat-plugins/room-faqs.ts
- server/chat.ts
- test/server/chat-plugins/help.js
Approved by all of Help staff.
_Very_ loosely based on the work panpawn did in #3859, but I've since rewritten everything about it, so I'm unsure if that needs to be credited or not. Let me know, I guess.
> Add a filter for auto-answering questions in the Help room

- server/chat-plugins/youtube.ts
- test/server/chat-plugins/youtube.js
caught a few bugs with this so, that was nice.
> Youtube: Add tests

- config/formats.ts
https://www.smogon.com/forums/threads/godly-gift-om-of-the-month.3660461/page-3#post-8559643
> Godly Gift: Ban Toxapex

- server/chat-commands/admin.ts
- server/chat-plugins/helptickets.ts
- server/chat.ts
- server/modlog.ts
- server/rooms.ts
- test/server/modlog.js
Hotpatching `chat` and then hotpatching `modlog` should fix the modlog issues without requiring a restart!
> Modlog: Fix bugs and support hotpatching

- server/rooms.ts
Fixes issues with translations like this one.
> Fix BasicRoom#tr

- data/mods/ssb/abilities.ts
- data/mods/ssb/conditions.ts
- data/mods/ssb/moves.ts
- data/mods/ssb/random-teams.ts
This is not a batch update given the nature of the removal.
> SSB: Remove Flare

- server/chat-plugins/helptickets.ts
- server/chat-plugins/poll.ts
- server/chat-plugins/scavengers.ts
- server/chat-plugins/trivia.ts
- server/chat-plugins/wifi.ts
- server/punishments.ts
> Fix modlog formatting

- .eslintrc-no-types.json
- .eslintrc-types.json
- server/chat-plugins/trivia.ts
This also exempts `tr` from `eslint`'s line length checking, just like `Utils.html`.
> Trivia: Fix translation formatting

- server/chat-commands/core.ts
Requested by... a lot of people.
> Support opting in/out of blocking pms/chals  with /busy

- server/chat-plugins/datasearch.ts
Fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8468209.
> Datasearch: Allow sorting by stat order and all only

- data/random-teams.ts
also removed a protect rejection for doubles
> Random Doubles: fix Lopunny

- config/formats.ts
https://www.smogon.com/forums/threads/inverse-leaders-choice.3666858/page-2#post-8561585
> Inverse: Ban Rillaboom

- server/chat-commands/admin.ts
- server/monitor.ts
> Support updating private code in /updateserver

- config/formats.ts
https://www.smogon.com/forums/threads/megamax-pet-mod-of-the-season-retooling-slate-2.3658623/page-16#post-8558755
> Megamax: Unban Cinderace

- server/chat-plugins/poll.ts
https://i.imgur.com/iSqMMgV.png
Typo I assume?
> Poll: missing < in opening tag

- config/formats.ts
https://www.smogon.com/forums/threads/stabmons-v-create-suspect.3668395/
https://www.smogon.com/forums/threads/national-dex-uu-metagame-discussion-grimmsnarl-retest-160.3660920/page-7#post-8566347
> Add National Dex UU and STABmons suspect notices

- server/chat-commands/info.ts
- server/chat-commands/moderation.ts
- server/chat-plugins/hosts.ts
- server/ip-tools.ts
- server/punishments.ts
Requested by Aeonic in the Staff room and approved by him, asgdf, and Anubis
> Add /nomarkshared

- config/formats.ts
- data/formats-data.ts
(I also fixed Cinderace-Gmax's tier)
https://www.smogon.com/forums/threads/np-ss-dou-stage-3-awful-ever-after.3668046/#post-8567687
> Move Urshifu to DUber

- server/chat-plugins/datasearch.ts
Apparently this is something people want.
> Datasearch: Support excluding monotype Pokemon

- data/pokedex.ts
- server/chat-commands/info.ts
Fixes this https://www.smogon.com/forums/threads/show-g-max-pokemons-signature-moves-in-their-dt-descriptions.3668136/.
> Display G-Max moves properly in /details

- server/chat.ts
https://www.smogon.com/forums/threads/rank-not-showing-on-both-sides-and-in-replays.3668496/#post-8565216
> Show error when using ! on a non-broadcastable command

- server/ip-tools.ts
- test/server/ip-tools.js
This is needed for private code.
> IPTools: Support wildcards in string ranges

- server/chat-commands/info.ts
> Add support for inverse in /weak

- server/rooms.ts
- server/users.ts
Fixes [this bug](https://www.smogon.com/forums/threads/staff-suggestions-bugs.3514540/page-15#post-8572439).
> Display whitelist correctly in demotion messages

- server/chat-commands/info.ts
- server/rooms.ts
> Rooms: Clean formatting for pending approval display on join

- config/formats.ts
https://www.smogon.com/forums/threads/ss-stabmons-v-create-voting.3669286/#post-8577943
> STABmons: Restrict V-create

- server/chat-plugins/help.ts
> Help: Allow regular users to suggest regexes

- server/chat.ts
This is why helptickets aren't being translated currently.
> Chat: Make pages translatable

- server/chat.ts
This will make things that are translated before the translations JSONs are loaded just be English (untranslated) instead of crashing PS!
> Chat: Make translations not crash after hotpatching

- server/chat-plugins/scavenger-games.ts
- server/chat-plugins/scavengers.ts
I guess this has been in since the multiple hosts update... which was a long time ago... oops i guess?
Nyaaa~ :3
> Scavengers: fix display bugs

- server/chat-commands/moderation.ts
https://www.smogon.com/forums/threads/staff-suggestions-bugs.3514540/page-15#post-8576576
> Fix /unlockip's interaction with namelocks

- server/chat-plugins/help.ts
> Help: Fix HTML error in regex page

- server/chat-plugins/help.ts
> Help: Fix crash with approvals

- config/formats.ts
https://www.smogon.com/forums/threads/np-zu-stage-2-turn-it-again-swoobat-quick-banned-42.3668115/page-2#post-8584032
> ZU: Ban Swoobat

- server/chat-plugins/chatlog.ts
Currently, the escaping isn't actually taken into account properly by either ripgrep or child process (not sure which), but this escapes them for a proper fix.
(also fixes a error with date searching)
> Searchlogs: Fix crash

- server/chat-commands/info.ts
I wasn't sure whether to put SS or SwSh, there's no precedent I can find
> Update CAP samples link to gen 8

- data/formats-data.ts
https://www.smogon.com/forums/threads/ss-uu-suspect-process-stage-6-jirachi.3669684/page-2#post-8585110
> Move Jirachi to UUBL

- config/formats.ts
https://www.smogon.com/forums/threads/350-cup-leaders-choice.3656554/#post-8585930
> 350 Cup: Ban Abra and Gastly

- config/formats.ts
https://www.smogon.com/forums/threads/national-dex-uu-metagame-discussion-grimmsnarl-unbanned-181.3660920/page-8#post-8585887 - also mega gardevoir was banned
> National Dex usage updates

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-ru-stage-2-lights-out-september-shifts-heracross-banned.3666733/page-5#post-8586090
> RU: Ban Heracross

- server/chat-commands/moderation.ts
https://www.smogon.com/forums/threads/remove-forcehidelines.3669531/
> Remove trusted user check in /hidetext

- server/chat-plugins/trivia.ts
This uses `<details>` and `<li>` rather than a scroll bar:
> Trivia: Reformat help and don't use module.exports

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-ss-uu-stage-6-lucky-star-jirachi-banned-chansey-unbanned.3668911/page-3#post-8586804
> Move Chansey to UU

- config/formats.ts
https://www.smogon.com/forums/threads/ss-almost-any-ability-magearna-voting.3669814/#post-8588305
> AAA: Ban Magearna

- config/formats.ts
https://www.smogon.com/forums/threads/old-gen-2v2-doubles-megathread.3663858/page-3#post-8588275
> Gen 5 2v2 Doubles: Add Accuracy Moves Clause

- server/chat-commands/moderation.ts
https://www.smogon.com/forums/threads/implement-a-weekban-command.3669889/#post-8588113
> Support week-long roombans

- server/chat-plugins/trivia.ts
This is all xfix, I just TypeScripted it, implemented Zarel's suggestions from #6420, and fixed the merge conflicts.
Fixes #6420.
> Trivia: Support specifying case sensitivity in searches

- config/formats.ts
https://www.smogon.com/forums/threads/350-cup-leaders-choice.3656554/page-2#post-8589091
> 350 Cup: Ban Woobat

- config/formats.ts
https://www.smogon.com/forums/threads/trademarked.3656980/page-4#post-8589098
complex bans arent supported for restrictions currently, so this is the best alternative
> Trademarked: Update bans

- server/chat-plugins/modlog-viewer.ts
> Modlog viewer: Fix more button for shared modlogs

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-nu-stage-3-rain-on-me-bans-post-30.3669764/page-2#post-8589192
> Move Tauros, Exeggutor-Alola, and Haunter to NUBL

- server/chat-plugins/trivia.ts
Requested by Question Workshop staff.
> Trivia: Add short alias for casesensitivesearch

- server/punishments.ts
> PunishmentMonitor: Include punishments on alts

- server/chat-commands/room-settings.ts
- server/modlog.ts
- server/room-battle.ts
- server/rooms.ts
Incorporates [these changes](https://github.com/smogon/pokemon-showdown/issues/6950#issuecomment-653822792) and also kicks guests out of battles while hiding them.
Also, I'm pretty sure this fixes #6950.
> Improve privacy for hidden battles

- data/formats-data.ts
https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/#post-8590185
> Move Silvally-Water to PUBL

- server/chat-commands/core.ts
- server/chat.ts
> Fix visual bug with /hiderank in PMs

- config/config-example.js
As per [this suggestion](https://www.smogon.com/forums/threads/allow-room-owners-to-promote-to-%E2%9C%A9.3669018/#post-8577989). This will obviously necessitate a change to main's `config.js` as well.
> Add a Room Prize Winner rank

- config/config-example.js
I figured this is probably supposed to exist, feel free to reject PR if intentional
> Let admins addhtml by default

- server/chat-plugins/help.ts
https://github.com/smogon/pokemon-showdown/commit/a8e860496796d606e96ea944e564a0582ad84b5a
> Help: Fix issue with approvals

- server/chat.ts
> Chat: Update AnnotateCommands regexes to account for refactors

- data/text/items.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-17#post-8525605
I don't own the games but if every source I could find says they're like this then they're probably like this
> Fix gen 8 fossil descriptions

- README.md
I made this cuz people, myself included, were complaining about documentation being hard to find, so I added a section under "Community" so people could easily find what they need. If there are other documentation that I'm not aware of, please add it.
> Add more documentation to README

- server/chat-commands/moderation.ts
Suggested [here](https://www.smogon.com/forums/threads/allow-multiple-arguments-for-promotions-and-demotions.3670212/#post-8592616).
> Support promoting multiple users at once in rooms

- server/chat-plugins/helptickets.ts
> Helpticket list: Respect ignoring tickets

- server/chat-commands/admin.ts
- server/chat.ts
This will make it easier to debug chat plugins. I also added state to some of the plugins that I felt could use it.
> Chat plugins: Support exporting plugin state

- server/chat-commands/info.ts
- server/rooms.ts
This is a thing a lot of people liked with Kid A, and since it's gone i figured it would be nice to migrate and not too much work.
> Support adding quotes in rooms

- server/chat.ts
- server/punishments.ts
(This will help simplify private code.)
> Add a filter to run code after global punishments

- data/formats-data.ts
- data/mods/gen5/random-teams.ts
- data/mods/gen6/random-teams.ts
- data/mods/gen7/random-teams.ts
- data/random-teams.ts
tried to make Liquid Voice Hyper Voice count as STAB—please double-check.
> Random Battles Updates

- server/tournaments/index.ts
ಠ_ಠ
(this is so perms can be toggled properly and so metadata can be properly accessed)
> Tournaments: Refactor commands

- server/chat-plugins/chatlog.ts
Fixes an issue where the more buttons would throw the requireRoom error, but this doesn't actually need a room, necessarily. Also updates the commands the buttons send.
> Searchlogs: Don't require a room

- server/chat-commands/core.ts
(see Discord for context on this PR)
> Call this.checkChat() later on in /invite

- server/chat-plugins/helptickets.ts
Requested by @DaWoblefet. This will need a private code change too which I can make if this is merged.
> Helptickets: Display user language and remove prefix

- server/chat-commands/info.ts
> Improve the /faq command

- data/pokedex.ts
https://bulbapedia.bulbagarden.net/wiki/Electirizer
Other entries are correct, even on PS.
> Fix Typo in Electirizer

- server/chat-commands/admin.ts
https://www.smogon.com/forums/threads/add-highlights-to-bot-pages.3669880/
Command name is tentative. Didn't like it, but couldn't think of a better one.
> Add a command to highlight users in bot html pages

- server/chat-commands/info.ts
> Add weekban to /punishments

- server/chat-plugins/chat-monitor.ts
- server/chat.ts
- server/global-types.ts
Requested by @DaWoblefet.
I also refactored the `FilterWord` type because I think that an Object is better than an Array here.
> Chat filters: Support custom redtext messages

- server/room-game.ts
- server/rooms.ts
I feel like there's something more to do here but I can't think of what it would be.
> RoomGame: Support a second game in room.subGame

- server/punishments.ts
- server/users.ts
This is currently causing Staff room to be spammed.
> Punishmentfilter: Don't activate for permalocks

- server/chat-commands/core.ts
- server/chat-plugins/hangman.ts
- server/chat-plugins/scavengers.ts
- server/room-game.ts
A lot of roomgames that should be using `/choose` or `/guess` but aren't. I'm going to unify them.
Would appreciate input from whoever's maintaining Trivia right now. @sparkychildcharlie?
> Unify /guess and /choose

- server/chat-commands/room-settings.ts
- server/modlog.ts
- server/room-battle.ts
- server/rooms.ts
This prevents "while searching, room ... expired" errors.
> Fix renaming battle rooms

- server/chat-plugins/modlog-viewer.ts
Minor changes to grammar and so forth.
> Battlesearch: Improve phrasing and UI

- server/chat-plugins/trivia.ts
- test/server/chat-plugins/trivia.js
Requested by several Trivia moderators and ROs
>  Trivia: Add leaderboard management commands

- server/chat-plugins/chatlog.ts
This PR (as the title states) now runs chatlog searches in a subprocess, so it doesn't, say, take down all of PS as easily.
It also makes a bunch of minor improvements to the code in the name of readability.
> Chatlog: Use ProcessManager for searches

- data/learnsets.ts
This was the only "thudnerpunch" occurrence in the repo.
> Fix typo in thunderpunch

- server/chat-commands/info.ts
I removed the "/" from the first tag, so it will be displayed as bold.
> Make Prize Winner bold in Room Ranks

- server/chat-commands/info.ts
https://www.smogon.com/forums/threads/profile-command.3666431/ as per this.
> Add the alias /profile to /whois

- CODEOWNERS
- server/chat-commands/info.ts
- server/chat-plugins/quotes.ts
- server/rooms.ts
> Quotes: Move to a chat plugin

- server/chat-plugins/quotes.ts
While no one on main is dumb enough to put HTML in a room title, we can't guarantee the same for other servers.
> Quotes: escape some HTML

- server/chat-commands/room-settings.ts
Was messing around with HTML injection for quotes in room titles and noticed this one
> makegroupchat - prevent HTML injection

- translations/portuguese.json
A typo slipped through, my bad
> Fixing a typo

- server/chat-commands/info.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8607763
I've used ~~ instead of Math.floor for performance reasons, but it shouldn't be much of a difference either way.
> Fix Flooring in /statcalc

- server/chat-plugins/trivia.ts
This PR:
- sorts the player list by points
- fixes the logic for picking finalists
- adds a command to let you leave the game
- randomizes question order
> Trivia: Improve Mastermind

- translations/german.json
I added the german translation for the newly added Prize Winner rank.
> Update German translation for /groups

- translations/portuguese.json
I added the portuguese translation for the newly added Prize Winner Rank; courtesy of Mitsuki :D
> Update Portuguese translation for /groups

- server/chat-plugins/scavenger-games.ts
New Twist: Bonus Round
(This also fixes a tiny oversight in a past twist as well.)
It would be purrrrfect if we can get this merged and patched in by the end of tomorrow :3
> ScavGames - add October twist

- server/chat-commands/moderation.ts
- test/server/chat-commands/moderation.js
As per https://github.com/smogon/pokemon-showdown/pull/7344#issuecomment-690748979.
> Moderation: Refactor room promotions to a function

- server/chat-plugins/chatlog.ts
> Chatlog: Handle ErrorMessage properly

- server/chat-plugins/modlog-viewer.ts
- server/modlog.ts
Requires hotpatching modlog and chat
> Modlog: Support exact user searches

- server/chat-commands/moderation.ts
- server/chat-plugins/hosts.ts
- server/chat.ts
- test/tools/modlog/converter.js
- tools/modlog/converter.ts
I swear I handled this in #7403, but I guess not. Anyway, IP addresses without a username are a thing, and I also fixed some formatting issues with locks.
> Modlog: Fix entries with an IP address and no user

- server/chat-plugins/modlog-viewer.ts
- server/modlog.ts
As per [this suggestion](https://www.smogon.com/forums/threads/regarding-the-recent-modlog-update.3671232/). Requires hotpatching both modlog and chat.
> Modlog: Default to searching all fields 

- server/chat-plugins/quotes.ts
https://www.smogon.com/forums/threads/remove-the-broadcast-cooldown-for-the-randquote-command.3670913/
> Quotes: Remove the broadcast cooldown for /randquote

- server/chat-plugins/datasearch.ts
```[00:14:16] Lunala Taxel: if not weak bug then what?
[00:14:35] Lunala Taxel: (for the type matchup)
[00:14:55] Lunala Taxel: hello?
[00:15:05] One Boo Knock Off: was just replying to you
[00:15:16] One Boo Knock Off: the key is rotom-mow
[00:15:19] One Boo Knock Off: and past tense
[00:15:43] Lunala Taxel: but the question specifies /nds and not /ds4 or something
[00:16:21] One Boo Knock Off: there is a way to make it /ds4, if you dunno how to, tell me the other two params, tell my why they would work, and i will give you the way
[00:17:41] Lunala Taxel: weak ghost and leafstorm
[00:17:48] One Boo Knock Off: maxgen4
[00:18:03] Lunala Taxel: it's not documented
[00:18:12] One Boo Knock Off: rip
[00:18:18] One Boo Knock Off: but it works
[00:18:29] Lunala Taxel: please open a pull …
```
> Add documentation on maxgen parameter to /ds

- data/formats-data.ts
https://www.smogon.com/forums/threads/sword-and-shield-tiering-announcements.3657492/page-4#post-8614913
> PU: update banlist

- server/chat-commands/info.ts
- server/chat-plugins/helptickets.ts
[Requested by global staff](https://www.smogon.com/forums/threads/improving-help-tickets.3642984/page-6#post-8607392).
> Helptickets: Display shared battles in staffintro

- server/chat-plugins/chatlog.ts
> Chatlog: Update permission checks

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-nu-stage-3-rain-on-me-bans-post-87.3669764/page-4#post-8616977
> NU: Ban Sneasel and Snorlax

- CODEOWNERS
- server/chat-plugins/repeats.ts
- server/rooms.ts
- test/server/chat-plugins/repeats.js
- translations/dutch.json
- translations/english.json
- translations/french.json
- translations/german.json
- translations/hindi.json
- translations/italian.json
- translations/japanese.json
- translations/portuguese.json
- translations/simplifiedchinese.json
- translations/spanish.json
- translations/traditionalchinese.json
This is a very common functionality used by room staff to disseminate information, and I think that given the recent issues caused by losing Kid A, making this into a chat plugin makes sense.
> Add a plugin to repeat phrases in chatrooms

- server/chat-plugins/modlog-viewer.ts
> Battlesearch: Make turn limit optional

- server/chat-plugins/chatlog.ts
Adds some more opts that /roomlog also has. Thought this might be useful.
> Chatlog: Add more opts

- server/chat-commands/info.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-27#post-8587300
> Chat commands: make /addrankuhtml multiline

- CODEOWNERS
- server/chat-plugins/rock-paper-scissors.ts
Per https://www.smogon.com/forums/threads/rock-paper-scissors-lizard-spock-in-pms.3670873/
> Support playing Rock Paper Scissors 

- server/chat-commands/core.ts
Pr for https://www.smogon.com/forums/threads/allow-showteam-to-be-broadcasted-with-no-cooldown.3671496/
> Remove the broadcast cooldown for !showteam

- server/chat-commands/moderation.ts
[17:17:15] &The Immortal: now that i think about it
[17:17:31] &The Immortal: we should probably have ro promote notices here
> Moderation: Notify Staff for RO promos

- README.md
- lib/fs.ts
- package.json
- server/chat-commands/admin.ts
- server/chat-plugins/hangman.ts
- server/chat-plugins/jeopardy.ts
- server/chat-plugins/scavenger-games.ts
- server/chat-plugins/scavengers.ts
- server/chat-plugins/uno.ts
- server/chat-plugins/wifi.ts
- sim/dex.ts
Making a PR so everyone knows that Jeopardy has a type issue that TS 4.0 caught.
> Update to TypeScript 4.0

- server/chat-plugins/scavengers.ts
https://cdn.discordapp.com/attachments/467865863240810516/761475882904584212/Screenshot_2020-10-02_Showdown_.png
Gotten RO confirmation from Pants.
https://cdn.discordapp.com/attachments/762324232948023316/764693429711929344/Screenshot_2020-10-11_Showdown_.png
> Remove background from /scav queue

- server/chat-plugins/helptickets.ts
As per [this suggestion](https://www.smogon.com/forums/threads/improving-help-tickets.3642984/page-6#post-8623599).
> Helptickets: Display common battles in more ticket types

- server/chat-plugins/youtube.ts
> Youtube: Support channel categories

- config/formats.ts
- data/mods/gen4/formats-data.ts
- data/mods/gen4/random-teams.ts
https://www.smogon.com/forums/threads/dpp-ubers-arceus-voting.3671545/#post-8623889
> Gen 4: Move Arceus to AG

- data/aliases.ts
Adds Side Shell Arm as an alias for Shell Side Arm as per https://www.smogon.com/forums/threads/make-searching-side-shell-arm-bring-back-shell-side-arm.3671775/
> Add alias for Shell Side Arm

- server/chat-plugins/youtube.ts
Requested by @KrisXV for a plugin they're doing.
> Youtube: Support searching for videos

- server/chat-plugins/chat-monitor.ts
This fixes the bug where public reasons are converted to replacements.
> Chatfilters: Fix wordfilter storage

- data/formats-data.ts
https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/page-2#post-8629532
> PU: Ban Exeggcutor

- server/chat-plugins/helptickets.ts
> Helptickets: Don't show battles for self-reports

- server/chat-commands/room-settings.ts
For https://www.smogon.com/forums/threads/make-mgc-shorthand-for-makegroupchat.3671952/
>  Add alias for /makegroupchat and /deletegroupchat

- server/chat-plugins/room-events.ts
Suggested [here](https://www.smogon.com/forums/threads/add-the-ability-to-view-categories-to-roomevents.3671887/#post-8626771).
> Room events: Add a command to view categories

- server/chat-commands/moderation.ts
For consistency with `/weeklock`.
> Moderation: Make weekbans override 2-day roombans

- server/chat-commands/info.ts
- server/chat-plugins/youtube.ts
Requested by Kris for their plugin for the Studio. Partial credit to them for re-writing some of the code.
> Youtube: Move video data fetching to a different function

- server/chat-plugins/thing-of-the-day.ts
- server/chat-plugins/youtube.ts
I'm not a _huge_ fan of the approach of making the handlers held in a top-level const, but it simplifies some code, and makes it the least messy.
> COTW: Support saving channel data of winning channels

- server/chat-plugins/chatlog.ts
Useful feature from several bots that PS can do better.
> Chatlog: Support viewing log stats for a room

- server/chat-commands/info.ts
> Remove /roomwhitelist from /roomhelp

- server/chat-plugins/tcgtabletop.ts
- server/chat-plugins/thecafe.ts
- server/chat-plugins/trivia.ts
- server/chat-plugins/wifi.ts
- server/chat-plugins/youtube.ts
- server/chat.ts
This was discussed in #7542, i believe, but since it doesn't exist i thought it would be useful to support this.
> CommandContext: Make requireRoom support specifying a room

- data/pokedex.ts
apparently they got overwritten with galars counterpart
> Fix Vanilla moltres's stats

- data/mods/gen7/moves.ts
- data/moves.ts
As reported [here](https://www.smogon.com/forums/posts/8637536).
> Update Lunar Dance to Gen 8 mechanics

- server/global-variables.d.ts
- server/index.ts
As discussed in #sim-dev with Zarel.
> Move global variable declarations out of index.ts

- server/chat-commands/moderation.ts
- server/chat.ts
- server/users.ts
> Connections: Track current chat page

- config/formats.ts
https://www.smogon.com/forums/threads/metronome-battles.3632075/post-8630458
> Metronome Battle: Update ability banlist

- server/chat-plugins/chat-monitor.ts
- server/chat.ts
> Chatfilters: Fix reasons displaying as undefined

- server/chat-plugins/blackjack.ts
- server/chat-plugins/hangman.ts
- server/chat-plugins/jeopardy.ts
- server/chat-plugins/rock-paper-scissors.ts
- server/chat-plugins/uno.ts
- server/chat.ts
> CommandContext: Add a method for getting roomgames

- server/punishments.ts
This solves the issue with yearlocks disappearing.
> Punishments: Make rangelocks persistent

- data/abilities.ts
- test/sim/abilities/neutralizinggas.js
I don't know if this is the best approach to this but it's currently the only way I've tried that works.
> Fix Slow Start's interaction with Neutralizing Gas

- data/moves.ts
holdhands should be 607 (615 is thousandwaves)
> Fix holdhands' num

- server/chat-plugins/announcements.ts
Pr for https://www.smogon.com/forums/threads/make-announcement-pull-up-the-current-announcement.3672606/#post-8643571
> Display the announcement with /announcement

- server/chat-plugins/chat-monitor.ts
https://www.smogon.com/forums/threads/staff-suggestions-bugs.3514540/page-17#post-8642512
> Don't allow forcerenamed usernames to be reused

- server/chat-plugins/daily-spotlight.ts
https://www.smogon.com/forums/threads/vsl-for-viewspotlights.3672561/
> Add /vsl alias to viewspotlights

- server/chat-plugins/announcements.ts
- server/chat-plugins/poll.ts
https://www.smogon.com/forums/threads/allow-non-html-polls-to-have-basic-formatting.3653845/
> Support basic text formatting in polls/announcements

- server/tournaments/index.ts
https://www.smogon.com/forums/threads/turn-on-timer-in-all-existing-tour-battles-if-forcetimer-is-turned-on-mid-tour.3655471/
> Tournaments: Start timer in all battles when forcetimer is activated

- server/chat-plugins/chatlog.ts
> Chatlog: Support searching for a user

- config/formats.ts
Ban Zekrom.  Ban it!  Send it to the shadow realm!!
> NatDex Mono:  Fix an oversight

- config/config-example.js
- server/chat-plugins/helptickets.ts
- server/chat-plugins/lottery.ts
- server/chat-plugins/poll.ts
- server/chat-plugins/scavengers.ts
- server/chat-plugins/the-studio.ts
- server/chat-plugins/thing-of-the-day.ts
- server/chat-plugins/trivia.ts
- server/chat-plugins/wifi.ts
- server/ladders.ts
- server/monitor.ts
- server/tournaments/index.ts
See https://github.com/smogon/pokemon-showdown/pull/7618#issuecomment-720556024.
> Introduce Config.noipchecks

- config/config-example.js
- server/chat.ts
- server/ladders.ts
- server/monitor.ts
- server/users.ts
As per #7618. Think i got everything related to this.
> Support Config.nothrottle

- config/config-example.js
- server/chat-commands/core.ts
- server/user-groups.ts
- server/users.ts
This Config option, intended purely for development test servers, allows users to log in without a signed token, by using `/trn [USERNAME]`. This allows logins without a login server.
The rest of the server has been changed to make sure unregistered users never have any powers they shouldn't have.
> Support Config.noguestsecurity

- server/chat-plugins/helptickets.ts
- translations/english/helptickets.ts
- translations/german/helptickets.ts
- translations/italian/helptickets.ts
- translations/portuguese/helptickets.ts
- translations/spanish/helptickets.ts
https://www.smogon.com/forums/threads/improving-help-tickets.3642984/page-6#post-8633561
> Helptickets: Display message in unclaimed tickets

- data/abilities.ts
Accidentally over-ignored by PR #7574.
> Restore As One boost activation

- data/mods/gen2/random-teams.ts
Intention: Make Spikes unrejectable to Fix Haze + Curse Qwilfish
> Gen 2 Random Battle Improvements

- server/chat-commands/moderation.ts
- server/punishments.ts
- server/users.ts
Credit for the idea goes to HoeenHero.
> Punishments: Make locks expire on their own

- server/chat-commands/admin.ts
- server/chat.ts
Requested by.. many people now, it feels like.
> Add a command to disable commands

- server/chat-commands/admin.ts
Not sure if this should make /hotpatch require force. Personally, i think it should, but i'll leave it up for debate.
> Admin: Warn the user of disabled commands on hotpatch/lockdown

- config/formats.ts
Freeing the once-banned Sword and Shield Mon once more!  
https://www.smogon.com/forums/threads/monotype-om-mega-thread.3660464/post-8652440
> National Dex Monotype: Unban Aegislash

- config/formats.ts
Retest has shown that it is ideal to leave this banned. 
https://www.smogon.com/forums/threads/metronome-battles.3632075/post-8652836
> Metronome Battle: Re-ban Sturdy Shedinja

- server/chat-plugins/thecafe.ts
This causes crashes if the room doesn't exist.
> The Cafe: Stop holding a reference to the room long-term

- server/chat-plugins/chatlog.ts
Fixes the current crash in Dev.
> Chatlog: Properly format search regexes in result rendering

- server/chat-plugins/datasearch.ts
> Datasearch: Disallow 'all' search broadcasting in battles

- server/chat-plugins/scavengers.ts
> Remove ^ from staff list in /scav top

- server/chat-commands/info.ts
- server/chat-plugins/helptickets.ts
https://www.smogon.com/forums/threads/improving-help-tickets.3642984/page-6#post-8653020
Super easy to do and there's really no downside.
> /sharedbattles: Upload replays of shared battles

- server/chat-plugins/modlog-viewer.ts
> Modlog viewer: Search global modlog when used in adminlog

- server/chat-plugins/youtube.ts
> Youtube: Update category command permissions

- server/chat-commands/admin.ts
- server/chat-commands/core.ts
- server/chat-commands/room-settings.ts
- server/chat.ts
This is useful logic that would be nice to have elsewhere (not needing a command context).
> CommandContext: Move parseCommand into Chat

- server/chat-commands/room-settings.ts
- server/room-battle.ts
- server/rooms.ts
As per https://github.com/smogon/pokemon-showdown/pull/7687#issuecomment-725795911.
> Rooms: Merge privacy setting code into setPrivate

- server/chat-plugins/helptickets.ts
As per https://www.smogon.com/forums/threads/3642984/page-6#post-8648367
> Helptickets: Mark tickets with offline users separately

- lib/fs.ts
- lib/streams.ts
- server/chat-plugins/hosts.ts
- server/chat-plugins/scavengers.ts
- server/ip-tools.ts
This fixes several things that TypeScript has been complaining about lately.
> Properly type Promises

- server/chat-plugins/datasearch.ts
I borrowed some code from the `/effectiveness` command, so this one should now support searches such as `/ds resists freeze dry`, `/ds resists flying press`, and `/ds !weak thousand arrows`.
> Dexsearch: support resists move and weak move

- server/chat-commands/info.ts
> Add a command to search usernames

- server/chat-plugins/datasearch.ts
> Fix type immunity check in /ds weak and resists and disallow status moves

- config/formats.ts
Reported [here](https://www.smogon.com/forums/posts/8646471).
> Update BST after changing stats to allow Scalemons Mod mashup

- server/chat-commands/info.ts
> /usersearch: Sort users by offline/online status

- server/chat-plugins/scavengers.ts
Adjust the _/scav timer_ function to allow for turning off the timer, and to enable fractional times once again.
> Scavengers: Expand the functionality of /scav timer

- server/chat-plugins/daily-spotlight.ts
Doesn't really matter since it gets automatically added, but doesn't feel right without it. 'o.o
> Add missing </details>

- server/chat-commands/info.ts
Changed help of "/show" to "!show" and added help for "/show".
> Improve help for !show and /show

- server/chat-plugins/youtube.ts
> Youtube: Add support for watching videos as a group

- server/chat-commands/moderation.ts
- server/chat-plugins/chat-monitor.ts
- server/punishments.ts
https://www.smogon.com/forums/threads/3673524/#post-8662678
> Punishments: Show users a warn message on login for offline warns

- server/users.ts
(We already monkeypatched this on the server and it works, just PR'ing over pushing to be safe)
> Users: Properly assign isStaff to staff roomauth

- server/chat-commands/info.ts
Forgot to do this with the /weakness change.
> Make `/cover type1/type2` work

- server/README.md
deleted an identical duplicate paragraph
> deleted duplicate paragraph

- translations/italian/repeats.ts
> Add Italian translations for repeats

- server/chat-plugins/chatlog.ts
Few things here.
A) Supports viewing battle logs / searching old battle logs.
B) Abstracts LogSearcher out into an two base classes that extend an abstract class, one tailored for Ripgrep support and the other for FS.
> Chatlog: Refactor FS/ripgrep handling and support battle logs

- .gitignore
- tsconfig.json
> Enable incremental compilation in `tsc`

- server/chat-plugins/trivia.ts
This will make future features (like custom categories) much simpler, and eliminate odd behaviors, like the `ALL_CATEGORIES` object requiring alphabetically-sorted keys.
> Trivia: Use an Object for questions instead of a sorted array

- lib/fs.ts
- lib/utils.ts
Seems to be unused anyway (has been since it was added?) but it fits utils better anyway.
> Move FSPath#waitUntil to Utils

- server/chat-plugins/mafia.ts
-Allows hosts to take idles through the script.
-/mafia takeidles on/off toggles between taking idles or not taking idles.
-/mafia action or /mafia idle allows players to submit their intent to idle or send an action when takeidles is on. There are also buttons usable on the mafia page.
> Implement /mafia takeidles

- data/mods/gen3/scripts.ts
[Report](https://www.smogon.com/forums/posts/8686455).
Regression from PR #7768.
> Fix Snatch in Gen 3

- server/chat-plugins/suspect-tests.ts
- server/room-battle.ts
- sim/battle.ts
This ensures that we will not need a formats hotpatch to make suspect declarations work anymore.
> Suspect tests: Move functionality out of sim/

- server/chat-commands/info.ts
because they're intuitive and I keep thinking they already exist
> Add two simple aliases for /suggestions

- server/chat.ts
Suggestion: https://www.smogon.com/forums/threads/allow-users-to-chat-themselves-with-blockpms-active.3672227/
> Allow users to pm themselves while /blockpms is active

- server/chat-plugins/poll.ts
Hey ! PR for https://www.smogon.com/forums/threads/missing-command-from-h-poll.3674791/
> Add missing command in /h poll

- server/chat-plugins/youtube.ts
> Youtube: Fix crash in interval

- server/chat-commands/room-settings.ts
Adding a simple alias "srgc" for commands /subroomgroupchat.
> Alias /srgc to /subroomgroupchat

- pokemon-showdown
- server/config-loader.ts
- server/index.ts
Not sure if i like how the start script handles this.
> Add a --no-security flag

- server/chat-commands/admin.ts
Now, `/updateserver` updates both public and private code, and `/updateserver private` only updates private code.
> Refactor /updateserver

- translations/hindi/main.ts
Idk why it is código lol cuz it is a Spanish word.
> Fix typo in hindi /htmlbox translation

- server/chat-plugins/datasearch.ts
- test/server/chat-plugins/datasearch.js
https://www.smogon.com/forums/threads/make-pivot-moves-a-ms-category.3672772/
> Feature: Make Pivot moves a /ms category

- server/chat-commands/moderation.ts
> Throttle how many rooms a user can join at once

- config/formats.ts
https://www.smogon.com/forums/threads/ss-1v1-victini-voting.3675330/post-8698022
> 1v1: Ban Victini

- data/mods/ssb/abilities.ts
- data/mods/ssb/conditions.ts
QC discuessed that -6 is too much to reduce speed by, so this will be able to get outsped by things that should outspeed it
> SSB: Nerf Forever Winter Nights

- lib/utils.ts
This is nice so that we can see the output of Maps / Sets without having to use Array.from or [...thing].
> Utils: Visualize Maps/Sets in a cleaner fashion

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-ss-uu-stage-8-1-this-hearts-on-fire.3674927/#post-8699102
> UU: Ban Blaziken

- server/chat-plugins/youtube.ts
This is a bandage solution. 
Ideally, we will "revert" this once we can find a suitable solution with the tag that complies with Google's API ToS.
> Youtube: Modify uses of youtube tag to comply with API ToS

- server/chat-commands/moderation.ts
> Moderation: Support spoiler: use in /namelock

- data/mods/ssb/abilities.ts
- data/mods/ssb/conditions.ts
- data/mods/ssb/moves.ts
- data/mods/ssb/pokedex.ts
- lib/utils.ts
Nerfs: Annika, Marshmallon, Naziel, HoeenHero
Bugfixes: brouha not removing terrains, frostyicelad boosting sometimes, description edits, etc.
> SSB4: Balance changes and bugfixes

- data/abilities.ts
- test/sim/abilities/neutralizinggas.js
> Neutralizing Gas wearing off should cause entrance Abilities to reactivate in order of Speed
> Neutralizing Gas should not wear off twice after suppression
neutralizinggas test from #7857
> Bug Fix: Neutralizing Gas Ending Issues

- server/chat.ts
Similar to command support - should be useful rather than having to do user.can + this.errorReply('page doesn't exist') etc.
> Chat: add support for private pages

- server/chat-commands/moderation.ts
Pr for https://www.smogon.com/forums/threads/add-a-short-alias-for-hidetext-hidelines-and-cleartext.3673226/#post-8700023
> Add alias for /cleartext

- data/abilities.ts
- data/items.ts
- data/mods/gen1/scripts.ts
- data/mods/gen2/scripts.ts
- data/mods/stadium/scripts.ts
- data/moves.ts
- data/scripts.ts
- sim/battle.ts
- sim/dex-moves.ts
- sim/pokemon.ts
- test/sim/abilities/cursedbody.js
- test/sim/abilities/pressure.js
- test/sim/abilities/sturdy.js
- test/sim/items/shellbell.js
- test/sim/misc/arceus.js
- Cursed Body should be able to disable Z-moves
- Pressure should not deduct additional PP from Sticky Web
- Pressure should deduct additional PP from Z-moves and Max moves
- Sturdy should trigger before Focus Sash but after False Swipe
- Revelation Dance should use Arceus's real type
- Shell Bell should heal from all damage
You might want to review each commit separately.
> Various mechanics fixes

- data/aliases.ts
> Fix capitalization in Charizard-Mega-Y

- server/chat.ts
- server/roomlogs.ts
As discussed in PMs with Zarel
> Roomlog: Support getting total linecount

- data/conditions.ts
- data/items.ts
- data/moves.ts
- data/scripts.ts
- sim/battle.ts
- sim/global-types.ts
- sim/pokemon.ts
- test/sim/moves/futuresight.js
Four separate issues. The commits are pretty tidy so you can view each individually for details.
> Bugfix: Various Future Sight / Doom Desire Fixes

- server/chat-plugins/room-events.ts
Pr for imrove help events, same https://github.com/smogon/pokemon-showdown/pull/7828
> Improve /help events

- server/chat-plugins/modlog-viewer.ts
Requested by a bunch of people.
> Modlog: Support shorthand commands for different parameters

- data/mods/megasforall/scripts.ts
Okay, this worked when I tried it locally and it also appeared to pass npm test on my end!
This is necessary for Mega Delibird's Ability like I noted on the Discord. C:
> Megas for All: Fix Delibird's ability

- server/chat-plugins/poll.ts
Pr for http://prntscr.com/wkcrvq
I did not find how to fix the "undefined"
> Poll: Fix viewqueue

- server/chat-plugins/chatlog.ts
See https://www.smogon.com/forums/threads/3514540/page-18#post-8709906.
> Add a command for searching groupchats

- server/chat-commands/room-settings.ts
https://www.smogon.com/forums/threads/add-roomevents-as-a-group-permission-in-permissions.3676240/#post-8714596.
> Permissions: Fix bug in adding namespaces

- server/chat-plugins/thing-of-the-day.ts
Pr for https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8710248
> thing-of-the-day: Fix minor bug

- server/chat-plugins/helptickets.ts
> Help Tickets: Improve roomintro CSS

- data/formats-data.ts
Roserade quick ban https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/page-2#post-8718644
> PU: Ban Roserade

- server/chat-commands/moderation.ts
discussed with @AeonicX7 - seemed useful enough and easy enough to be added.
> Moderation: Support week namelocks

- server/chat-plugins/hosts.ts
- server/punishments.ts
approved by Aeo - useful feature for ranges with bad users.
> Punishments: Support blacklisting ranges from being marked as shared

- server/user-groups.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-45#post-8713401
> Usergroups: Fix atLeast whitelist handling

- server/chat-commands/admin.ts
figured this was fine given Zarel's comment on https://www.smogon.com/forums/posts/8687858
> Default sendhtmlpage to all connections

- server/chat-plugins/room-events.ts
Discussions https://github.com/smogon/pokemon-showdown/pull/7928
I had to redo a PR because I can't do it on the other pr
> Room Events: Imrove raw text in /events view

- server/chat-plugins/room-faqs.ts
Pr for https://www.smogon.com/forums/threads/add-editdaily-and-editfaq-commands.3676502/
> Room FAQs: Display raw text in /rfaq

- server/chat-plugins/daily-spotlight.ts
Pr for https://www.smogon.com/forums/threads/add-editdaily-and-editfaq-commands.3676502/
> Daily: Display raw text in /daily

- server/chat-commands/moderation.ts
https://www.smogon.com/forums/threads/3514540/page-18#post-8725105
> Moderation: Log Owner forcepromotes to Staff/Upper Staff

- sim/pokemon.ts
- test/sim/misc/inversebattle.js
Also Telekinesis's ungroundedness with a Ring Target holder etc.
> Make Magnet Rise work in Inverse Battles

- server/chat-commands/core.ts
Pr for https://www.smogon.com/forums/threads/include-more-info-in-the-h-offertie-description.3677103/
> Improve /offertiehelp

- server/chat-commands/info.ts
> Improve /usersearch

- lib/utils.ts
- server/chat-plugins/hangman.ts
> Hangman: Support saving hangman entries

- server/chat-plugins/helptickets.ts
Should fix the bug mentioned in #private-dev.
> Helptickets: Fix bugs with unbanning

- lib/process-manager.ts
Better subprocess query system for #7937.
I mentioned in #7937 that it should be a regular `child_process`, but Mia's not _wrong_ that PM has some useful features that make it more convenient than `child_process`. This change allows a `QueryProcessManager` to easily run a query in a new child process.
> PM: Support querying in a new process

- server/chat.ts
- server/modlog.ts
- server/monitor.ts
- server/room-battle.ts
Now that we have <<slowlog>>, it would be useful to have slow logging standardize. LMK if i missed other places.
> Monitor: Standardize slow logging

- server/chat-plugins/youtube.ts
> Youtube: Add a command to list groupwatches

- server/chat-commands/info.ts
> Info: Add a /faq for pages/proxyhelp

- server/chat-plugins/poll.ts
- server/rooms.ts
> Minor activities: Don't re-display on hotpatch

- server/chat-plugins/net-filters.ts
Few bug fixes:
- checks if a save exists when copying to a backup
- saves replays of the battle if it alerts US to suspicious behavior (if it's a battle)
- /netfilter train now ignores blank lines
- child process has proper error handling.
> NN filters: Fix error handling and make improvements

- data/mods/ssb/conditions.ts
> Properly display gimmick's innate ability in /ssb

- data/mods/ssb/abilities.ts
- data/mods/ssb/moves.ts
> SSB4: Clarifications and Description Edits

- server/chat-plugins/youtube.ts
> Youtube: Notify room of starting groupwatches

- server/chat-commands/info.ts
Requested by CAP room leadership
> Add CAP project forum link

- server/chat-plugins/daily-spotlight.ts
Should improve the performance when rendering (not having to request for each spotlight is less laggy!)
> Spotlights: Store image data

- server/chat-plugins/net-filters.ts
Easier to mass train this way.
> NN Filters: Add a command to train on logs from a room

- server/chat-plugins/net-filters.ts
this is something i totally forgot about
> NN filters: Parse /me properly

- server/chat-plugins/uno.ts
Fix this bug : https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8727895
> UNO: Fix turn order after a disqualification

- data/mods/megasforall/pokedex.ts
Mega Orbeetle ability fix in Megas for All was incomplete
> Megas for All: Mega Orbeetle fix

- data/mods/ssb/abilities.ts
- data/mods/ssb/moves.ts
- data/mods/ssb/pokedex.ts
Update description to match this, and fixes a different thing
> SSB4: Bugfixes

- server/ladders-local.ts
- server/ladders-remote.ts
Reverts smogon/pokemon-showdown#7960
This is causing crashes on PS.
> Revert "Calculate and display Elo change on server"

- data/mods/ssb/random-teams.ts
- data/mods/ssb/scripts.ts
Approved by myself.
Although this will deviate the ratio of deviation between the most generated set vs the least generated set, i think this will be a welcome change that helps fix how ssb teams fair against each other.
> SSB: Change set generation to rely on weaknesses against types

- server/chat-commands/moderation.ts
- server/chat.ts
Requested feature, plus this makes it easier to do the `spoilers` thing on other commands.
> Moderation: Add  `spoilers` support to more commands

- server/chat-commands/info.ts
- server/chat-commands/moderation.ts
> Deprecate /groupchatban

- config/formats.ts
- data/mods/gen3/rulesets.ts
- data/rulesets.ts
- sim/team-validator.ts
- test/sim/team-validator.js
Talked in dev room. "Do nothing clause" idea from Wob
> Gen 3: Add Deoxys Forme Clause and Deoxys Camouflage Mod

- server/chat-plugins/youtube.ts
Various features requested by YT staff.
> Youtube: Support watching Twitch streams and showing Twitch channels

- server/chat-plugins/uno.ts
Pr for https://www.smogon.com/forums/threads/uno-cards-command.3668755/
> UNO: Add /uno cards command

- config/formats.ts
Because I got it wrong in PR #7698.
> Really fix BST calculation for Tier Shift

- server/chat-plugins/suspect-tests.ts
Annika said this was cool but that I should make a pull request in case Zarel or someone has a different opinion
> Suspect Tests: Add a whitelist

- server/chat-commands/admin.ts
Zarel mentioned that we should do this a while ago (iirc? thought it was brought up), and it's a useful enough tool for debugging it couldn't hurt to have it here.
> Add 'ps' output to /processes

- data/scripts.ts
- test/sim/moves/struggle.js
No more invincible Shedinja!
I assume the way I did it was fine, but figured I'd have proper review instead of pushing directly.
> Gen IV: Fix Struggle's interaction with Shedinja

- data/aliases.ts
This has been used by both the UU community and the sim in general as the colloquial term for kommo-o for years at this point. Ask Estarossa, Lilburr, and other UU community members for confirmation if needed.
> Add Clanger as an Alias for Kommo-o

- data/mods/gen1/random-teams.ts
- data/mods/gen2/random-teams.ts
- data/mods/gen3/random-teams.ts
- data/mods/letsgo/random-teams.ts
- data/random-teams.ts
I found no changes in a sample of 10,000 teams/format so this should be fairly regression-free.
@ACakeWearingAHat if you're planning to stay involved with maintaining Gen 2 development, you should probably review this/familiarize yourself with the changes. (You don't have to, though; I don't mind doing all of the programming for Gen 2.)
> Random Battles: Refactor LGPE and Gens 1-3

- config/formats.ts
Just assuming this was an accident.
> CC1v1: Reban Dynamax

- server/chat-commands/moderation.ts
https://www.smogon.com/forums/threads/3514540/page-19#post-8763488
> Moderation: Don't hidetext for locks in tickets

- server/chat-plugins/mafia.ts
Added unwin and unwinfaction for the mafia plugin.
> Mafia: Add /unwin command

- data/text/moves.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8765067
> Descriptions: Fix Recycle

- server/chat-plugins/mafia.ts
Add a vote alias for most lynch commands and change wording to exclude the word "lynch".
> Mafia: change "lynch" to "vote".

- data/formats-data.ts
https://www.smogon.com/forums/threads/mienshao-is-now-banned-from-ss-nu.3679135/
> NU: Ban Mienshao

- data/formats-data.ts
https://www.smogon.com/forums/threads/np-ru-stage-5-electric-feel-slowbro-g-banned-see-post-27.3676870/page-2#post-8768767
> RU: Ban Slowbro-Galar

- server/chat-plugins/helptickets.ts
> Help tickets: Refresh ticket list in 'more tickets' button on click

- server/chat-plugins/scavengers.ts
Have received confirmation from LittEleven, the kinda-sus Scavengers RO.
> Scavengers: Display host's username when hunt ends

- data/mods/gen4/random-teams.ts
- data/random-teams.ts
Unfortunately Gen 4 is a bit more complex than the previous generations; I had hoped to get to Gen 5 this weekend, but I guess that won't be happening. I'll see if I can get some more done with this during the week, but for now I've gotten Gen 4 broken out into several methods, making it more maintainable. I also verified that there was no difference in the teams generated from 10,000 seeds, so this shouldn't have any major regressions.
> Random Battles: Refactor Generation 4

- server/chat-plugins/random-battles.ts
Was caused by the mon not having a learnset for this gen.
> Fix crash in /randset

- server/chat-commands/admin.ts
It's in `admin.ts` because i was unsure of where else to put it, and admin already has the ProcessManager import. (plus it's console only so...)
> Restore /potd

- data/mods/gen2/random-teams.ts
- data/mods/gen3/random-teams.ts
- data/mods/gen4/random-teams.ts
- data/mods/letsgo/random-teams.ts
- data/random-teams.ts
(and also fix gen 3 STAB enforcement, since i've already finished it)
intent: use more thorough commenting and easier-to-understand names in order to make move enforcement code less cryptic to people who don't know code that well
> Random Battles: Improve documentation

- data/formats-data.ts
Pr for https://www.smogon.com/forums/threads/ss-uu-suspect-process-stage-8-3-terrakion.3679532/page-2#post-8774766
> UU: Ban Terrakion

- lib/process-manager.ts
- lib/utils.ts
- server/chat-commands/admin.ts
- test/server/room-battle.js
Should make some stuff a lot easier. 
I removed the duplicated `if (lock[patch])` stuff since it's rather annoyingly duplicated with no real point.
> Admin: Support hotpatching User / Room / ProcessManager prototypes

- data/mods/gen4/random-teams.ts
- data/mods/gen5/random-teams.ts
- data/mods/gen6/random-teams.ts
- data/mods/gen7/random-teams.ts
- data/random-teams.ts
As usual, no change in teams from 10,000 different seeds
> Random Battles: Refactor Gen 5-7

- server/chat-plugins/chatlog.ts
> Roomstats: Display total stats and handle empty logfiles better

- data/mods/ssb/conditions.ts
Requested
If you are wondering why this isn't in my current batch PR, I am sick as shit and the less headaches the better
> SSB: Remove Easter Egg

- config/formats.ts
https://www.smogon.com/forums/threads/ss-almost-any-ability-poison-heal-voting.3680043/#post-8786344
> AAA: Ban Poison Heal

- server/chat-plugins/helptickets.ts
> Helptickets: Automatically saved replays linked in tickets

- server/chat-commands/admin.ts
Didn't remember this would get included.
> Admin: Ignore the current 'ps' process in /processes

- server/chat-plugins/thing-of-the-day.ts
I don't like the LEGACY_DATA hardcode, but I can't really think of a better way to migrate it. We should be able to remove that eventually.
This should make it so other rooms can use OTDs without having to make a code change, and also merges it so all OTDs are stored in a singular file (with settings), which _should_ make it easier to migrate in the future.
> Thing of the Day: Refactor storage / remove hardcodes

- server/chat-plugins/thing-of-the-day.ts
https://github.com/smogon/pokemon-showdown/commit/5a3d6067b22fc9f30e9c0f96f65631a458e84d97#r48405899
> TOTD: Fix legacy loading

- server/tournaments/index.ts
Pr for https://www.smogon.com/forums/threads/tour-getrules-tour-viewrules-codes.3673252/
> Tournaments: Add readmore for /tour rules

- server/chat-commands/moderation.ts
> Support temporarily disallowing names with no user object

- server/chat-plugins/helptickets.ts
> Help tickets: Refresh /ht list on ticket update

- data/moves.ts
- test/sim/moves/uproar.js
SadisticMystic confirmed that the user of Uproar simply calms down at the end of the current turn.
> Uproar should end if the user is under the effect of Throat Chop

- data/mods/ssb/moves.ts
> SSB: Fix description

- server/chat-plugins/hangman.ts
https://www.smogon.com/forums/threads/hangman-groups-tags.3680445/#post-8793303
> Hangman: Support tagging premade phrases

- data/mods/ssb/moves.ts
- data/mods/ssb/random-teams.ts
Boat's move should bypass mbounce. Perish gets meme text.
> SSB: Small tweaks

- data/random-teams.ts
some minor hardcodes to account for abilities and items
> Rands AFD patches

- server/chat-commands/room-settings.ts
- server/chat-plugins/daily-spotlight.ts
- server/chat-plugins/quotes.ts
- server/chat-plugins/responder.ts
- server/chat-plugins/room-faqs.ts
- server/chat-plugins/thing-of-the-day.ts
- server/chat.ts
- server/global-types.ts
- server/rooms.ts
> Add infrastructure to rename chat plugin data with rooms

- config/formats.ts
Fix Zamazenta ban (base forme only)
> Pokébilities: update banlist

- config/formats.ts
> Update ZU threads

- server/tournaments/index.ts
Pr for https://www.smogon.com/forums/threads/allow-voiceds-and-regulars-to-check-tour-rules.3681028/
> Tournaments: Allow regular users to check tour rules

- server/chat-plugins/mafia.ts
Changed lynches to vote in the votebox
smallworldz
> Changed lynches to vote in the votebox

- server/chat-plugins/helptickets.ts
> Helptickets: Notify users of /faq proxy when opening an IP-appeal ticket

- config/formats.ts
- data/formats-data.ts
PR for https://www.smogon.com/forums/threads/ss-lc-suspect-process-woobat-voting.3681457/post-8808892
> LC: Ban Woobat

- server/ip-tools.ts
> IPTools: Automatically add Tor IPs to the proxy list

- server/chat-plugins/helptickets.ts
See https://www.smogon.com/forums/threads/3642984/page-7#post-8814179 for context. What's the proper way to go about working around the line-length issue on some of the strings? A bunch of ``// eslint-disable-next-line max-len``, or something else?
Some screenshots for reference:
> Help Tickets: Add cheating report type

- server/chat-plugins/announcements.ts
PR for https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8817595
> Announcements: Fix /announcement htmlcreate

- translations/french/main.ts
> French Translations: Fix typo in /groups

- server/sockets.ts
Instead of using a mega-switch, instead use a dispatch system for the sockets protocol.
A big advantage is that we don't need to be weird about variable declarations using this method. We can use `const`s!
> Use a dispatch system for sockets

- config/formats.ts
Update of different links.
VGC links are removed (approuved by DaWoblefet)
> Update of format threads

- server/chat-plugins/scavengers.ts
In particular, just on the huntmaker's name; the rest works already.
> Scavengers: Escape usernames in /scav status

- data/moves.ts
- data/text/moves.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8759139
> Add fail text for Corrosive Gas

- data/formats-data.ts
Pr for https://www.smogon.com/forums/threads/pu-general-rules-tiering-and-announcements-thread.3660650/post-8826858
> PU: Ban Clawitzer, Kingler and Omastar

- data/mods/ssb/random-teams.ts
Approved by ~~corrupt project head~~ myself
> SSB4: Support Same Type Clause

- config/formats.ts
> ZU: Add sample thread

- data/moves.ts
Fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8833264
> Fix Shell Side Arm information leak

- server/chat-plugins/calculator.ts
Reported [here](https://www.smogon.com/forums/posts/8835883). I also gave `(` a precedence to simplify the loop.
> Give the negative operator a precedence

- server/chat-commands/info.ts
- server/chat-commands/room-settings.ts
- server/chat-plugins/datasearch.ts
- server/chat.ts
- server/rooms.ts
Affected commands: `/data`, `/coverage`, `/effectiveness`, `/weakness`, `/learn`
Supersedes #7965
> Support setting a default format/mod for commands in rooms

- server/chat-commands/admin.ts
- server/chat.ts
> Implement /botmsg

- data/cap-1v1-sets.json
https://www.smogon.com/forums/threads/cap-1v1-moveset-submissions-mrdollsteak-promoted-to-co-lead.3663533/post-8835037
> CAP 1v1: Add Chromera

- data/moves.ts
- test/sim/moves/mefirst.js
for some reason a test in room-battle.js times out and I have zero clue why
It fails even with the one line i added commented out
> Fix Me First's interaction with recharge moves

- server/chat-commands/admin.ts
This command restores the ability for bots to close their HTML pages. Prior to 0e0389bdc89e3e5b7d5ad9ef237fc9ee30a07477, this was achieved by sending `/sendhtmlpage user, pageid, |deinit|`.
> Implement /closehtmlpage

- data/mods/gen7/moves.ts
Fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8842643
> Backport Psychic Terrain hint for priority on non-grounded targets

- data/abilities.ts
- test/sim/misc/target-resolution.js
- test/sim/moves/counter.js
I don't know what to say here....
> Mirror Coat stalwart doubles target fix

- config/formats.ts
[22:39] @ OM~!: if ur not busy, could I borrow some of ur time to do that?
[22:39] +Instruct: yeah sure
[22:39] +Instruct: whats up?
[22:42] @ OM~!: am in need of
[22:43] @ OM~!: Shadow Tag / Moody / Power Construct / Arena Trap / Lando-I / Genesect / Zamazenta / Baton Pass
[22:43] @ OM~!: banned on the inverse ladder
[22:43] @ OM~!: as I am a goof
[22:43] +Instruct: yeah i can do that
[22:43] @ OM~!: thank you very much :)
> Sketchmons and Inverse: Update banlists

- data/rulesets.ts
Pr for https://www.smogon.com/forums/threads/no-switch-rule.3653057/
For this rule, pokemon cannot switch normally.
But he can switch with an attack (teleport, baton pass)...
> Rule: Add No Switch

- data/tags.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8845100
Fix to the current NatDex UU banlist.
> Ban Mega Latios and Thundurus-T in NatDex UU

- config/formats.ts
- lib/utils.ts
- server/chat-commands/moderation.ts
- server/monitor.ts
If you grep the codebase for `|| 0) + 1` you get a lot of results, all of which would be better implemented with a multiset.
> Implement Utils.Multiset

- config/CUSTOM-RULES.md
- config/formats.ts
- data/mods/gen7/rulesets.ts
- data/random-teams.ts
- data/rulesets.ts
- server/rooms.ts
- sim/battle.ts
- sim/dex-formats.ts
- sim/pokemon.ts
- sim/side.ts
- sim/team-validator.ts
- test/sim/data.js
- test/sim/team-validator.js
- tools/set-import/importer.ts
Custom rules can now have values! So you can now use custom rules like `Max Level = 5` or `Max Team Size = 24`, and have them as subrules of other rules, and define your own rules with custom values.
Here's an example rule:
```ts
forcemonotype: {
effectType: 'ValidatorRule',
name: 'Force Monotype',
hasValue: true,
onValidateRule(value) {
if (!this.dex.types.get(value).exists) throw new Error(`Misspelled type "${value}"`);
if (!this.dex.types.isName(value)) throw new Error(`Incorrectly capitalized type "${value}"`);
},
onValidateSet(set) {
const species = this.dex.species.get(set.species);
const type = this.ruleTable.valueRules.get('forcemonotype')!;
if (!species.types.includes(type)) {
return [`${set.species} must have type ${type}`];
}
},
},
```
You would use this rule like this: `Force …
> Support value rules

- server/chat-commands/moderation.ts
[Requested](https://www.smogon.com/forums/threads/staff-suggestions-bugs.3514540/page-20#post-8847713).
> Hide lines from locked/banned users' alts

- server/chat-plugins/scavengers.ts
Changed all occurrences of monthly to a standardized `current`
> Scavengers: Ladder isn't monthly

- data/mods/gen2/learnsets.ts
- sim/team-validator.ts
- test/sim/team-validator.js
> Validator: Improve Gen 1 level validation

- data/mods/gen8dlc1/rulesets.ts
- data/moves.ts
- data/rulesets.ts
I'm waiting on a test from Anubis to see if the pre-1.3.2 functionality for Trick/Switcheroo on Kyogre/Groudon was in DLC1.
> Update to Sw/Sh 1.3.2 mechanics

- data/moves.ts
Uses Sludge Bomb for special, Poison Jab for physical. I left the hints in for accessibility reasons, but I can remove it if you guys want me to.
> Use different animation depending on Shell Side Arm category.

- sim/battle.ts
- test/sim/moves/sunsteelstrike.js
Not sure if this was the correct place or not, but it does seem to work!
> Gen VII: Ignore user's Ability with Mold Breaker moves

- sim/pokemon.ts
Fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8749031
Yellow disassembly: https://github.com/pret/pokeyellow/blob/0cbd5acb76d0f5df35ebf529bd227c201e0b3115/engine/items/item_effects.asm#L2689
Crystal disassembly: https://github.com/pret/pokecrystal/blob/2fe0cbbb19df504723934f39473064033c64ef6f/engine/items/item_effects.asm#L2799
No idea how any of this behaves in Stadium etc.
> Gen I-II: Cap initial max PP at 61

- data/abilities.ts
- data/moves.ts
- test/sim/moves/disable.js
I bet you could think of some epic endless battle strats with this if we left it alone though!
> Fix Struggle to be unaffected by Disable

- config/formats.ts
- sim/dex-formats.ts
I am bad at writing words so if the comment needs fixing feel free to edit it.
> Gen 6 Hackmons: Fix EV limit and comment

- server/chat-commands/info.ts
Is a bit awkward that !punishments Global fails
> !punishments: Use toID

- server/chat-plugins/usersearch.ts
DaWob said this was fine to PR.
(requested by some staff several times now)
> Usersearch: Support setting a list of most-searched names

- server/chat-commands/admin.ts
> Admin: Support /eval in PMs

- config/formats.ts
https://www.smogon.com/forums/threads/ss-nfe-pikachu-voting.3684954/#post-8867850
> NFE: Ban Pikachu

- server/chat-plugins/datasearch.ts
…& /randmove
PR for https://www.smogon.com/forums/threads/expand-number-of-mons-moves-that-can-be-generated-in-randpoke-or-randmove.3684529/
> Datasearch: Increase in the number of pokemon generated in /randpoke

- data/mods/ssb/abilities.ts
- data/mods/ssb/conditions.ts
- data/mods/ssb/moves.ts
- data/mods/ssb/random-teams.ts
TODO:
Averardo -> Lunala
SectoniaServant -> Sectonia
other stuff i might have forgotten
> SSB: Bugfixes and Cosmetic Updates

- server/chat-plugins/modlog-viewer.ts
Convenient feature. Aeonic said this was fine to do.
> Add modlog stats page

- server/chat-plugins/daily-spotlight.ts
- server/chat-plugins/helptickets.ts
- server/chat-plugins/quotes.ts
- server/chat-plugins/responder.ts
- server/chat-plugins/room-faqs.ts
- server/chat-plugins/thing-of-the-day.ts
- server/chat.ts
- server/global-types.ts
- server/rooms.ts
> Chat: Support exporting custom handlers from plugins

- server/chat-plugins/chat-monitor.ts
- test/server/chat-plugins/chat-monitor.js
I centralized the code to make it easier to use, but the main purpose of this PR is to move to safer loading code (see comment at 130) and to a safer loading format (JSON) to prevent current issues. More details on the issue in #private-dev.
> Chat-monitor: Centralize functions and migrate to JSON

- config/formats.ts
Pr for https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8874126
> Formats: Fix typo

- server/chat-commands/info.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-44#post-8709275
> Info: Fix /show and /requestshow interaction error

- data/mods/gen5/pokedex.ts
- data/mods/gen6/pokedex.ts
- data/mods/gen7/pokedex.ts
> [01:44] #Zarel: it should definitely set unreleasedHidden to true
[01:44] #Zarel: rather than literally nuking the HA
Welp, here I go on doing this. Will be a bit busy in a bit so just want this off the ground.
> Gen 5: Refactor to use unreleasedHidden

- server/chat-plugins/helptickets.ts
> Helptickets: Change password reset link

- server/chat-plugins/datasearch.ts
Added Magic Coat/Magic Bounce since those are intuitive terms to use while searching
~~Also can we talk about how the move is Magic Coat but the flag is Reflect and shown as Bounce~~
> Movesearch: Add defrost and reflectable aliases

- data/mods/gen5/rulesets.ts
- data/mods/gen7/rulesets.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-58#post-8882546
Client Side: smogon/pokemon-showdown-client#1825
> Gen 5: Reveal Mail in team preview

- data/formats-data.ts
Pr for https://www.smogon.com/forums/threads/ss-ubers-zacian-hero-voting.3686145/#post-8887642
> Ubers: Ban Zacian

- server/chat-commands/room-settings.ts
- server/chat-plugins/random-battles.ts
I also made `/roomdefaultformat off` actually work.
> Support default format for randbats commands

- server/chat-commands/admin.ts
Bots face some rather inconvenient issues in subroomgroupchats.
> /botmsg: Permit ROs

- server/chat-plugins/repeats.ts
- server/chat-plugins/responder.ts
- server/chat-plugins/room-faqs.ts
https://www.smogon.com/forums/threads/show-full-size-images-html-support-within-rfaq.3683406/
> Support HTML in roomfaqs

- server/chat-commands/info.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8905671
> Show "Bypasses Protect" flag in /dt for ally-targeting moves

- lib/utils.ts
- server/chat-plugins/hosts.ts
- server/ip-tools.ts
- server/punishments.ts
- server/users.ts
- test/server/ip-tools.js
> IPTools: Add sanity checks

- server/chat-plugins/chatlog.ts
> Support viewing stats on the activity of rooms

- sim/pokemon.ts
https://www.smogon.com/forums/threads/change-custom-game-speed-mechanics.3686665/
> Ignore 10000 speed upper limit in Custom Game

- server/chat-plugins/datasearch.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8917371
> Remove LC Uber as a valid tier in /ds help text

- server/chat-plugins/scavengers.ts
> Scavengers: Notify users on hint addition

- server/chat-commands/moderation.ts
See [here](https://www.smogon.com/forums/threads/only-modnote-notifyrank-if-it-highlights-everyone.3687633/).
> Add /notifyuser

- config/config-example.js
- server/chat-commands/moderation.ts
- server/rooms.ts
- server/user-groups.ts
https://www.smogon.com/forums/threads/section-leader-updates-proposal.3687279/
> Make adjustments to Section Leaders

- data/mods/gen2/items.ts
- data/mods/gen2stadium2/items.ts
- data/mods/gen3/items.ts
- test/sim/abilities/thickfat.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-60#post-8917932
https://github.com/pret/pokeemerald/blob/9358ab33a5eacf7fb7aa573a59d26ebabe889058/src/pokemon.c#L3125
> Gen 3: Type boosting items should boost the attacking stat

- data/mods/gen2stadium2/scripts.ts
Third bug in this list https://www.smogon.com/forums/threads/pok%C3%A9mon-stadium-2-simulators-bugs-glitches-and-other-mistakes.3685286/
> Stadium 2: Send -unboost for stat drops

- lib/sql.ts
- server/chat-commands/admin.ts
- server/chat-commands/core.ts
- server/chat.ts
> Add a command for evaluating SQLite

- data/rulesets.ts
https://www.smogon.com/forums/threads/stabmons.3656429/page-8#post-8931262
Kris said he was busy and asked me to do this.
I will implement the client side changes in my existing PR for STABmons here: smogon/pokemon-showdown-client#1846
I manually checked that everything was working as it should. Do I have to write some tests in the team-validator tests file?
> Implement new STABmons policy

- data/items.ts
As reported [here](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-62#post-8938129)
> Refactor Berserk Gene to use useItem

- data/items.ts
- test/sim/moves/skydrop.js
Fixes https://github.com/smogon/pokemon-showdown/projects/3#card-61614927
> Fix Skydrop + Eject Button interaction

- lib/sql.ts
- package.json
- server/chat-commands/admin.ts
- server/modlog/index.ts
- server/modlog/transactions.ts
- server/rooms.ts
- test/lib/sql.js
Draft because there's a critical bug in this code that causes the subprocesses to crash when started. No idea why. No errors are logged.
> SQL: Use a QueryProcessManager subclass

- data/abilities.ts
- data/moves.ts
as referenced here https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8954294
> Fix Water Shuriken interaction with Pokemon transformed into Ash-Greninja

- data/abilities.ts
- data/items.ts
- data/mods/gen3/moves.ts
- data/mods/gen4/items.ts
- data/mods/gen4/moves.ts
- data/mods/gen5/moves.ts
- data/mods/gennext/moves.ts
- data/mods/ssb/abilities.ts
- data/mods/ssb/moves.ts
- data/moves.ts
- data/tags.ts
- server/chat-commands/info.ts
- server/chat-plugins/datasearch.ts
- server/chat-plugins/random-battles.ts
- sim/dex-moves.ts
This PR changes the 'Mystery' flag and the 'Authentic' flag so they better represent what the flag actually means
> Rename the "mystery" and "authentic" move flags

- server/chat-commands/info.ts
- translations/french/main.ts
- translations/portuguese/main.ts
- translations/simplifiedchinese/main.ts
- translations/spanish/main.ts
- translations/traditionalchinese/main.ts
> Add Section Leaders to !groups

- data/mods/gen3/moves.ts
- data/mods/gen4/moves.ts
- data/text/moves.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8959754
I just made the duration get randomly set in `onStart`. Is that correct or should I be using `effectState.time` like sleep and confusion do?
> Gen III-IV: Fix Uproar duration

- data/pokedex.ts
It only evolves during the day
> Add evolution condition for Lurantis

- sim/team-validator.ts
- test/sim/team-validator.js
Thanks to @PlagueVonKarma and [Beelzemon 2003](https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-15#post-8967007) for pointing this out!
> Gen 1: Correct minimum level validator logic

- data/mods/gen4/abilities.ts
- test/sim/abilities/liquidooze.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8972096
I used `target.lastMoveUsed` to make this work, I feel like there's a better option.
> Gen III-IV: Fix interaction between Liquid Ooze and Dream Eater

- data/mods/gen1/moves.ts
- data/mods/gen2/moves.ts
- data/text/moves.ts
Client Side: smogon/pokemon-showdown-client#1861
> Gen I-II: Fix Mist & Haze behavior

- data/random-teams.ts
Fixes a crash introduced in https://github.com/smogon/pokemon-showdown/commit/a9cff320d8aad6676140179d1f8d52d3c5f0c07d
> Random Battle: Fix crash with Force Monotype

- data/learnsets.ts
multiple sources have toxicroak not learning the move
> Learnsets: Remove Covet from Toxicroak

- CODEOWNERS
- server/chat-plugins/wifi.ts
- server/chat.ts
- server/rooms.ts
- sim/teams.ts
I've been working with Wi-Fi's roomstaff for the past month or so to make a new UI and submission system for making/submitting/hosting giveaways to prepare for BDSP's release.
> Wi-Fi: Refactor giveaways

- config/formats.ts
Requested by HeatEdgeSword:-
https://www.smogon.com/forums/threads/om-mashup-megathread-aaa-doubles-is-leaders-choice-for-november.3657159/page-27#post-9024416
> Update AAA Doubles bans

- config/formats.ts
Requested by HeatEdgeSword:-
https://www.smogon.com/forums/threads/om-mashup-megathread-aaa-doubles-is-leaders-choice-for-november.3657159/page-27#post-9036186
> AAA Doubles: Ban Dancer

- config/formats.ts
- data/mods/gen8bdsp/formats-data.ts
- data/mods/gen8bdsp/random-teams.ts
- data/random-teams.ts
While there is a TON of room for improvement, this removes the issue of nonexistent items being assigned to sets and makes the format playable.
> BDSP Random Battle: Fix set generation

- config/formats.ts
https://www.smogon.com/forums/threads/3694047/
> Add Tiny Tourney Online Competition

- data/mods/gen3/formats-data.ts
Removing water spout from kyogre to prevent some bad set from happening
> Gen3 Random battle update

- server/chat-commands/moderation.ts
PR for https://www.smogon.com/forums/threads/enable-htmldeclare-for-room-owners.3694127/
> Moderation: Enable /htmldeclare for Room Owners

- data/mods/gen4/items.ts
- sim/team-validator.ts
Only Giratina can hold the Griseous Orb without hacking.
> Gen 4: Fix Griseous Orb Validation

- server/chat-plugins/wifi.ts
> Wifi: Limit the page tabs non-staff can see

- server/chat-plugins/wifi.ts
Requested by Wi-Fi staff.
Those who review before Kris, please just approve - he said he wanted to be able to review. If you review after Kris, merge away.
> Wifi: Support claiming submitted giveaways

- databases/migrations/chat-plugins/v5.sql
- server/chat-plugins/abuse-monitor.ts
> Abuse-monitor: Support tracking stats

- data/mods/gen8bdsp/rulesets.ts
See these posts:
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9059693
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9059817
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9060150
> BDSP: Update orphaned egg move list

- data/mods/gen1/scripts.ts
- sim/global-types.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8973699
I'm not completely sure this is correct, since gen 1 code is confusing af, but it seemed to work fine when I tested the scenario given in the bug report.
> Gen 1: Fix Haze

- data/mods/gen8bdsp/formats-data.ts
Update donphan and rampardos movepools as well
> BD/SP Random Battle: Add missing pokemons

- server/chat-plugins/helptickets.ts
> Helptickets: Support adding custom response buttons to text tickets

- server/chat.ts
> Chat: Require registration to talk in non-persistent rooms

- server/chat-commands/moderation.ts
Pr for https://www.smogon.com/forums/threads/add-a-line-in-roomauth-that-explicitly-says-bolded-names-are-online.3695449/
> Roomauth: Add a line says bolded names are online

- config/formats.ts
https://www.smogon.com/forums/threads/ss-1v1-power-construct-voting.3695860/post-9075953
> 1v1: Ban Power Construct

- server/chat-jsx.ts
- server/chat-plugins/wifi.ts
Reverts smogon/pokemon-showdown#8581.
This is crashing hotpatches right now and needs a restart to fix it. No one can do that right now, so we're reverting for safety.
> Revert "Wi-Fi: Convert to TSX"

- config/formats.ts
Ban King's Rock, Conkeldurr, Dracozolt
https://www.smogon.com/forums/threads/pok%C3%A9bilities-om-of-the-month.3679692/post-9081096
> Pokébilities: Update bans

- data/text/moves.ts
This could save hackmons players some confusion. Wasn't sure if it's 'non-dynamax' or 'without a base move' specifically. Both seem ambiguous in their own way, Also not even sure if 0 power is accurate.
> Describe how non-dynamax max-moves work

- data/mods/gen6/formats-data.ts
Removing stealth rock from rhyperior to differentiate them better.
> Gen 6 Random Battle: Add Rhydon

- data/mods/gen7/formats-data.ts
Remove stealth rock from rhyperior as well to differentiate them better.
> Gen7 Random Battle: Add Rhydon

- server/chat-plugins/abuse-monitor.ts
Convenience for staff members, so they can see who got which recommendation. Mostly a PR since this involves a migration.
> Abuse-monitor: Sort recommendations by user

- config/formats.ts
https://www.smogon.com/forums/threads/linked-leaders-choice.3660421/post-9117607
> Linked: Ban Speed Boost

- config/formats.ts
https://www.smogon.com/forums/threads/metronome-battles.3632075/post-9118221
Sticking to the main ladder, since this is a meme format that isn't worth the effort of a suspect ladder!
> Metronome Battle: Fluffy/Fur Coat retest

- config/formats.ts
https://www.smogon.com/forums/threads/linked-leaders-choice.3660421/post-9122908
> Linked: Ban Volcarona

- data/mods/gen2/moves.ts
- data/mods/gen4/moves.ts
- data/mods/gen5/moves.ts
- data/mods/gen7/moves.ts
- data/moves.ts
- test/sim/moves/healbell.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9127908
> Fix Heal Bell/Aromatherapy in Multi Battles

- server/chat-plugins/abuse-monitor.ts
- server/chat-plugins/helptickets.ts
Mostly QoL. Alex said this was OK to do.
Would be nice if this could be merged quickly - it is needed.
> Abuse-monitor: Add a staff feedback system

- sim/battle.ts
Fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9152590
> Fix battle not ending after faint from future move

- sim/battle.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9116974
> Gen 1: Fix Endless Battle Clause

- data/mods/gen3/formats-data.ts
https://discord.com/channels/294651453279174656/763038340664524840/953056846715969578
> Gen3 Random Battle: Update Azumarill's movepool

- server/chat-plugins/mafia.ts
No longer decrements number of players when someone transitions between death states, and no longer allows a certain type of kill to be used on a player already in that death state.
> Mafia: Fix transitions between deathstates

- server/chat-commands/info.ts
- Uses the right format id for anything goes (https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9161077)
- Fixes link for pokemon with a forme in its name (https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9161082)
> /analysis fixes

- data/conditions.ts
Client Side: smogon/pokemon-showdown-client#1946
> Stop sending -formechange for Gmax

- sim/team-validator.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9155317
> Gen 1: Allow underleveled pokemon in Custom Game

- server/room-battle.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9175609
> Don't show /offertie hint in tour battles

- data/conditions.ts
- sim/battle.ts
- test/sim/misc/dynamax.js
https://github.com/smogon/pokemon-showdown/projects/3#card-52058688
> End Dynamax before start of 4th turn

- data/mods/gen2/moves.ts
- data/moves.ts
- test/sim/abilities/protean.js
https://github.com/smogon/pokemon-showdown/projects/3#card-71347448
Supersedes #8572
> Fix Counter/Mirror Coat/Metal Burst failure timing

- data/mods/gen1/scripts.ts
- sim/pokemon.ts
- test/sim/moves/transform.js
- Fix copying stat boosts (https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8843431)
- Fix crit rate not using base species for speed stat (https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/post-6283457)
> Gen 1: Fix Transform bugs

- data/cap-1v1-sets.json
https://www.smogon.com/forums/posts/9163192/
> CAP 1v1: Fix Pyroak set

- data/moves.ts
- sim/dex-conditions.ts
https://github.com/smogon/pokemon-showdown/projects/3#card-69826019
for Defense Curl and Rest+Uproar
Test:
> Fix extraneous failure messages

- server/chat-plugins/wifi.tsx
Because https://imgur.com/a/A0NbABG reads funny
WigglyTree (WiFi @) said this was ok
> Wifi: Fix GA results grammar when only one entrant

- data/mods/gen4/moves.ts
- data/moves.ts
- sim/battle-queue.ts
- sim/battle.ts
- sim/dex-moves.ts
- test/sim/moves/focuspunch.js
https://github.com/smogon/pokemon-showdown/projects/3#card-61383963
> Fix Focus Punch/Beak Blast/Shell Trap charge timing

- data/moves.ts
- test/sim/moves/pursuit.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9117672
> Fix Pursuit activating on non-adjacent foes in Triples

- data/mods/gen8bdsp/formats-data.ts
https://discord.com/channels/294651453279174656/908560260753657888/968529669597048862
> BD/SP Random Battle: Udpate movepools

- data/mods/gen1/random-teams.ts
https://discord.com/channels/294651453279174656/809413397840920586/963086002942001203
> Gen1 Random Battle: Give PU mon level 77

- config/formats.ts
> Update ORAS Pure Hackmons link

- sim/battle.ts
- test/sim/misc/target-resolution.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8973895
> Fix normal move target resolution in Triple Battles

- data/mods/gen4/moves.ts
- test/sim/moves/knockoff.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9201883
> Gen 4: Fix Knock Off interaction with Sticky Hold and Multitype

- data/mods/ssb/moves.ts
- data/mods/ssb/scripts.ts
- data/moves.ts
- sim/battle-actions.ts
- sim/dex-moves.ts
- test/sim/moves/healingwish.js
- test/sim/moves/memento.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9203131
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9205781
I'm not sure if what I did is 100% correct but it fixes both bugs and the rest of the tests pass.
> Fix self ko timing for Memento/Healing Wish/Lunar Dance

- config/formats.ts
https://www.smogon.com/forums/threads/crazyhouse-om-of-the-month.3699268/page-2#post-9209489
> OMoTM: Ban Hawlucha and Self-KO moves

- config/formats.ts
I'm bad, sorry
https://www.smogon.com/forums/threads/om-mashup-megathread-pokeaaa-is-leaders-choice.3657159/page-34#post-9207734
> Fix build and restrict Stench in Pokebilities AAA

- sim/battle-actions.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9208445
> Fix Burning Jealousy burning Pokemon that just switched in

- data/mods/gen7/formats-data.ts
https://discord.com/channels/294651453279174656/763039843654565941/971799289040891934
> Gen7 Random Battle: Update movepools

- sim/battle.ts
> Properly replace Iron Head with Behemoth moves

- data/mods/gen3/moves.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8816441
> Gen 3: Fix Sleep Talk not deducting pp when locked by Encore/Choice Item

- config/formats.ts
Bug reported in several places:-
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-76#post-9208581
https://replay.pokemonshowdown.com/gen8pokebilitiesaaa-1570487910
> Pokebilities AAA: Fix Traced Primal weather not ending

- config/formats.ts
https://www.smogon.com/forums/threads/om-mashup-megathread-pokeaaa-is-leaders-choice.3657159/page-35#post-9213966
Yes this is all my fault
> PokeAAA: Restrict Evasion and Ban Gengar

- sim/team-validator.ts
- test/sim/team-validator.js
Urgent for AAA
Follows the precedence set here: https://www.smogon.com/forums/threads/how-should-zamazenta-c-be-tiered-resolved.3673325/#post-8659168
If that tiering policy is ever changed then feel free to close this PR.
> Separate Zacian/Zamazenta forms in banlists

- config/formats.ts
Change request: https://www.smogon.com/forums/threads/om-mashup-megathread-pokeaaa-is-leaders-choice.3657159/page-36#post-9221423
Eggs clarified that Quick Draw is a restriction on Discord (https://discord.com/channels/449412583015841793/449424946901417984/977401307272990750).
> Pokebilities AAA: Update bans (Alakazam, etc)

- data/mods/ssb/moves.ts
- data/moves.ts
- test/sim/moves/healingwish.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9220431
@DaWoblefet are you sure healing wish/lunar dance should fail during `onHit`? This fix requires a pretty awful hardcode.
> Fix Healing Wish setting up slot condition on failure

- data/mods/gen1stadium/conditions.ts
- data/mods/gen1stadium/moves.ts
- data/mods/gen1stadium/scripts.ts
- Shows confusion message after Thrash ends
- Makes Toxic actually work like Toxic
- Makes Leech seed stack with Toxic
- Fixes client messages sent by Haze
> Fix multiple Gen 1 Stadium bugs

- server/rooms.ts
Context: https://www.smogon.com/forums/threads/allow-room-owners-to-join-invite-only-subrooms.3702238/
> Check parent roomauth for modjoin

- data/mods/ssb/moves.ts
https://replay.pokemonshowdown.com/gen8superstaffbros4-1594487295
> SSB: Fix Bane Terrain crash

- data/mods/gen2/moves.ts
- data/mods/gen2/scripts.ts
- data/mods/gen2stadium2/scripts.ts
Just fixing the bug I reported as below:
(https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-74#post-9187155)
Double commit to remove the compiler warning on line length for line 255
> fix Spikes missing against flying/digging semi-invulnerable opponent (gen 2)

- data/mods/gen7letsgo/formats-data.ts
LGPE has been given the go-ahead to do VR-based tiering, more info here https://www.smogon.com/forums/threads/3659882/#post-9265133
> Implement LGPE tier shifts

- config/formats.ts
https://www.smogon.com/forums/threads/broken-record-om-of-the-month.3701270/page-3#post-9268189
> Broken Record: Update bans

- data/tags.ts
https://www.smogon.com/forums/threads/national-dex-uu-suspect-12-rock-you-like-a-hurricane.3704903/
> National Dex UU Thundurus-T Suspect

- data/mods/gen6/formats-data.ts
https://discord.com/channels/294651453279174656/809413252517462026/998181879322787881
> Gen 6 Random Battle: Update movepools

- data/mods/gen3/formats-data.ts
https://discord.com/channels/294651453279174656/763038340664524840/997818637480112148
> Gen 3 Random Battles: Update movepools

- config/formats.ts
Fixes a bug where Fling is usable if the user is holding a TR when it shouldn't.
> Broken Record: Fix Fling

- databases/migrations/storedbattles/v2.sql
- lib/postgres.ts
- server/room-battle.ts
- server/rooms.ts
This ensures battle rating is saved, properly persists timer, and ensures people join correctly. It also adds a notification telling people their battles will be restored shortly (since battle reloading can take a bit), which is removed when they have a battle restored.
> Rooms: Ensure battles save all data correctly

- config/formats.ts
- data/rulesets.ts
The special casing is needed to make certain moves follow the OM rule correctly. Rulification is just to support mashups better and to future-proof mechanics support in case the format is removed after LCotM.
> Category Swap: Fix special cases and rulify

- server/chat-plugins/scavengers.ts
> Scavengers: Fix queuerecycled [index]

- lib/utils.ts
- server/chat-plugins/scavenger-games.ts
- server/chat-plugins/scavengers.ts
PR drafted for two reasons:
a) Twist name is subject to change
b) Pushed with --no-verify since linting wouldn't execute within 15 min
> Scavengers: Add Speedrun Twist

- server/chat-commands/info.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9297815
> Fix /analysis for Zygarde-10%

- server/chat-commands/info.ts
- translations/english/main.ts
Bots got nerfed 2 years ago but nobody updated /groups
> Update Bot description in /groups

- data/mods/gen8bdsp/formats-data.ts
https://discord.com/channels/294651453279174656/908560260753657888/1008122447163293726
> BD/SP Random Battles: Update movepools

- server/chat-commands/info.ts
https://www.smogon.com/forums/threads/deny-notification-on-requestshow.3705738/
> Media approvals: Notify user on denial

- config/formats.ts
Many people want to play this format in the downtime between now and Scarlet & Violet VGC
> BDSP: Reintroduce Battle Festival Doubles as a challenge format

- sim/team-validator.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9316707
> Fix Sinistea-Antique learnset validation

- data/aliases.ts
Added alias 'umbrella' -> 'Utility Umbrella' to make it easier to find via /dt
> Add umbrella item alias

- data/mods/gen6/formats-data.ts
https://discord.com/channels/294651453279174656/809413252517462026/1012063068534095953
> Gen6 Random Battles: Update movepools

- sim/team-validator.ts
- test/sim/team-validator.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9313225
> Properly invalidate underleveled third-stage Pokemon

- server/chat-plugins/scavenger-games.ts
- server/chat-plugins/scavengers.ts
Should be approved by room owners nyaa
> Scavengers Twist: Scavengers Feud

- server/chat-plugins/scavenger-games.ts
- revert a requested change
- fix name of the game mode
> Scav Feud fixes

- data/factory-sets.json
Fix some bugs and improve RU a little.
> Battle Factory updates

- data/factory-sets.json
> Battle Factory: Fix Magneton

- sim/team-validator.ts
- test/sim/team-validator.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9335136
Edit: also closes https://github.com/smogon/pokemon-showdown/issues/6281
> Validator: Fix Shedinja Egg move inheritance

- sim/team-validator.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9340232
> Allow ability + move incompatibilities in custom games

- server/chat-plugins/youtube.ts
at the request of Arsenal, they have an event planned to watch a Hindi movie using it
> Add Hindi to the youtube groupwatch whitelist

- data/mods/gen5/formats-data.ts
Removing Baton pass from the format and updating movepools
https://discord.com/channels/294651453279174656/763039178211721236/1022152942733770883
> Gen 5 Random Battles: Update movepools

- server/chat-plugins/datasearch.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9361698
> Fix /ms boosts/lowers missing some moves

- server/chat-commands/info.ts
these ' are making it not work lol
> Fix Custom Avatar faq

- data/mods/gen2/random-teams.ts
This change right now should only affect Steelix, but the general rule is valid.
https://discord.com/channels/294651453279174656/809413306854932510/1030858745858756658
> Gen2 Random Battles: cull explosion and selfdestruct on sleeptalk

- config/formats.ts
- data/mods/gen1/rulesets.ts
- data/mods/gen7mixandmega/scripts.ts
- data/mods/mixandmega/scripts.ts
- data/rulesets.ts
- lib/utils.ts
- server/chat-plugins/datasearch.ts
- server/chat-plugins/othermetas.ts
- sim/dex.ts
- sim/global-types.ts
Reverts smogon/pokemon-showdown#8919. This broke certain mods and needs further testing.
> Revert "Improved typing for `utils.ts`, and for iterating over base stats"

- server/chat-plugins/scavengers.ts
Very minor fix
idenitfy -> identify
dont -> don't
> Fix typo in comment

- data/mods/gen7/random-teams.ts
- test/random-battles/gen7.js
`https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9342873
> Gen 7 Randdubs: Fix Manectric pre-mega ability

- server/users.ts
This was brought up recently on Discord
> Users: lower chat throttle for public bots

- server/chat-commands/info.ts
> Make `!calc` properly broadcast as a `!math` alias

- test/sim/moves/transform.js
This cleans up the transform.js test as discussed in https://github.com/smogon/pokemon-showdown/pull/8952#pullrequestreview-1159420343.
> Clean up transform.js test

- data/items.ts
- sim/dex-conditions.ts
- sim/field.ts
- test/sim/items/roomservice.js
Room Service currently uses onUpdate(), but it should use onStart() (same timing as Air Balloon), and some sort of event that is callable after a pseudoWeather is set (picked ``onAnyPseudoWeatherStart``).
> Correct Room Service event timing

- sim/team-validator.ts
- test/sim/team-validator.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9373659
> Fix events having access to past-gen exclusive moves

- sim/team-validator.ts
- test/sim/team-validator.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9378018
> Gen 8: Fix events with HA and oldgen tutor moves being illegal

- data/mods/gen1/scripts.ts
- data/mods/gen1stadium/scripts.ts
- data/mods/gen2/scripts.ts
- data/mods/gen2stadium2/scripts.ts
Just some minor comment typos in old gens scripts.ts that are annoying me.
> Fixing some typos

- config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3706080/page-6#post-9360080
> Partners in Crime: Update bans

- data/pokedex.ts
- sim/dex-species.ts
- sim/team-validator.ts
- test/sim/team-validator.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8811572
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8833356
> Validator: Correctly enforce per-game evolution restrictions

- data/mods/gen1/moves.ts
- data/mods/gen1jpn/moves.ts
- data/mods/gen1stadium/moves.ts
This fixes some inaccuracies with Transform and Bide against semi-invulnerable enemies (Dig/Fly):
Transform can now hit semi-invulnerable foes in Gen 1, including Japanese (mechanics confirmed in dev discord).
https://discord.com/channels/630837856075513856/630845310033330206/1038788797837615137
https://discord.com/channels/630837856075513856/630845310033330206/1038974718516137994
Bide can no longer hit semi-invulnerable foes in Gen 1 Stadium.
https://www.smogon.com/forums/threads/stadium-bug-report-thread.3526616/page-2#post-8503442
> Gen 1: Fix Transform and Bide accuracy

- server/chat-plugins/random-battles.ts
> `/randbats`: Show doubles sets in FFA battles

- data/rulesets.ts
> Add Ability Clause

- sim/battle-actions.ts
ensures 2x terastab requires move type to match tera type
> Fix terastal multiplier

- data/moves.ts
- test/sim/moves/shedtail.js
Had 2 people confirm for me: it simply fails
> Fix Shed Tail with no switches

- server/chat-commands/info.ts
* Add slicing and wind
* Hide more flags before gens where they're relevant
> /details: Update move flags
