config/formats.ts
data/factory-sets.json
data/random-teams.ts

After a long, long wait, Gen 8 Battle Factory is done. The room staff are comfortable releasing the format as soon as possible.
Credits:
The vast majority of the sets are transcribed from on-site and in-progress analyses.
Most of LC's sets: Wiggleetuff, Merritt
Consultants:
Ubers: fc, Minority
OU: TPP
UU: Estarossa, Hilomilo
RU: Mac3
NU: Ho3nConfirm3d, Rabia
PU avarice, Chloe
LC: Fiend, Acehunter1
Code problems: Kris, Instruct, Annika
Randbats team consultants: Javitu, Roginald, platinumCheesecake, heroicTobias

Implement Battle Factory for Gen 8

---

server/chat-plugins/scavenger-games.ts

I have no idea what inspired me to use .trim() here when it obviously should have been toID().

ScavFeud: Fix Matching bug

---

data/mods/gen8dlc1/moves.ts
data/text/moves.ts

The rollout storage glitch should only be mentioned in the dlc1 mod for gen 8.

Fix Rollout/Ice Ball description

---

server/chat-commands/info.ts

these are very frequently asked questions across the sim and having global FAQs for them rather than relying on room FAQs is just simplifying and uniformising things.

Add FAQs for custom avatars and the privacy policy

---

server/chat-plugins/datasearch.ts

Re-creation of https://github.com/smogon/pokemon-showdown/pull/8917
The code for /movesearch in past gens would add a move for a Pokemon without regards to if it could learn the move in a given generation; this change will check a move's source generations and add moves only if the move can be learned in a current or past generation.
This fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8608692

Movesearch: Search past gen learnsets

---

data/abilities.ts
test/sim/abilities/neutralizinggas.js

Neutralizing gas now negates strong weather abilities and restores them on exit.
As suggested on [this Mechanics Bugs card](https://github.com/smogon/pokemon-showdown/projects/3#card-85843136)

Fix Neutralizing Gas Primal weather interaction

---

data/random-teams.ts

Meditate was not listed as a physical setup move, making it so that Primeape and Hitmonlee could not roll it in gen2 rands.
https://discord.com/channels/294651453279174656/809413306854932510/1030479956762963999

Random battles: Add meditate to PhysicalSetup moveslist

---

data/mods/gen2/formats-data.ts

Just a small sets change.
https://discord.com/channels/294651453279174656/809413306854932510/1030479956762963999

Gen2 Random Battles: HP grass instead of Giga Drain on celebi and vileplume

---

server/chat-plugins/hangman.ts

Fixes 3 issues with hangman:
1. When a letter is already successfully guessed, other impossible guesses can be submitted that don't take into account the current letters revealed.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
2. Words with HTML will break formatting, typically hiding or otherwise obscuring the message. Here's an example with `</div>`.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
3. Hint length just said "too long" and didn't clarify the number of characters. I refactored all of the length requirements to be constants at the top of the file.

Hangman: Prevent impossible guesses and fix HTML escape

---

server/chat-plugins/friends.ts
server/friends.ts

Fixed an issue where if you are blocking incoming friend requests, you cannot cancel sent friend requests:
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9323392
Clarified the response of an error message where sending friend requests would be rejected if both incoming+outgoing requests are greater than max requests:
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9334011

Fix minor friends bugs

---

data/mods/joltemons/abilities.ts

context: https://replay.pokemonshowdown.com/gen8joltemonsrandombattle-1691444095
Joltemons was using a wrong or outdated way to report Wandering Spirit

Joltemons: Fix Wandering Spirit client crash

---

sim/team-validator.ts

Currently, when validating events that fail because of "either/or" reasons, the validator just picks the first event it can find and claims incompatibility with that event. For example, consider a Shiny Eternatus with 0 Atk IVs. Compare before and after:
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
So I think it's much clearer to list all possible events and their incompatibility with each. This does have the downside of Pokemon with many events making the problems it gives back a bit longer, but I think it's a fine trade-off. This doesn't happen with _every_ event Pokemon incompatibility edge case though; Pokemon that can't be Shiny are a common example of ones affected:
<details>
<summary>Example with Shiny Victini</summary>
</details>

Validator: Push problems for all failed events

---

data/formats-data.ts
data/random-teams.ts

-So many movesets have changed. In general, movesets have been trimmed to remove unnecessary coverage, unnecessary instances of Protect, and most instances of Ally Switch.
-The total bulk minimum for Assault Vest in Doubles has been lowered to 275, rather than 280. This allows Incineroar to have an Assault Vest, primarily.
-Pheromosa and frail Regenerator Pokemon will no longer get a Sitrus Berry in Doubles; in cases where they used to get a Sitrus Berry, they will now get a Life Orb.
-In Doubles, Protect will no longer be generated alongside reliable recovery moves.
-Muddy Water will not be on sets with Liquidation.
-Galarian Mr. Mime will no longer appear in Random Doubles.

Random Doubles updates

---

server/chat-plugins/sample-teams.ts

The sanitizeFormat method now follows aliases even for temporary formats that were taken down, and does so before checking the whitelist. Also it no longer tries to print out nonexistent whitelists

Sample Teams: Fix aliases & checking whitelist

---

data/mods/gen1/scripts.ts
data/mods/partnersincrime/scripts.ts
server/chat-plugins/helptickets.ts
sim/pokemon.ts
test/sim/moves/transform.js

This patch fixes multiple Transform bugs in Gen 1:
* Fix critical hits not using base stats for damage calculation (https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-84#post-9371041)
* Fix Transform not copying stats correctly when the two Pokemon have different levels (https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-52#post-8843431)
* Fix Transform not copying stats correctly when at least one of the Pokemon are paralyzed or burned (https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-9#post-6373537)

Gen 1: Fix multiple Transform bugs

---

data/moves.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9376335
Specified gen 8 since the fail message already shows in gen 7 due to Purifiy's `onHit` event in that gen returning `false` instead of `NOT_FAIL`.

Gen 8: Fix failure message not showing for Purify

---

data/mods/gen1/moves.ts

This fixes Ground-types not being affected by Thunder Wave in Gen 1 with Inverse Mod.
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-15#post-8801689
Ground-types are still immune to Thunder Wave in regular battles, since Thunder Wave does not ignore type immunities.

Gen 1: Fix Thunder Wave not affecting Ground-types with Inverse Mod

---

data/mods/gen2/moves.ts

Mimic accuracy fixed, changed from can't miss to 100% for gens 1 and 2. 100% is the correct accuracy.
Reported as a bug (for gen 1): 
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-14#post-8558474
Mimic's accuracy: https://bulbapedia.bulbagarden.net/wiki/Mimic_(move)

Fix Mimic accuracy in gens 1 and 2

---

data/mods/gen1/scripts.ts
data/mods/gen1stadium/scripts.ts

Twineedle should only be able to poison on its second hit in gen 1. Currently it can poison on both hits.
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-15#post-8757544
The patch is done in an identical way to gen 2.

Gen 1: Fix Twineedle poison chance

---

data/mods/gen1/scripts.ts
test/sim/moves/hyperbeam.js

This patch fixes the bug "Hyper Beam should only skip recharge turns when KOing a Substitute, not every time", listed here:
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/#post-5933177
Previously, Hyper Beam would skip recharge turns when hitting a Substitute, regardless of whether the Substitute was KOd.

Gen 1: Fix Hyper Beam unbroken Substitute interaction

---

data/mods/gen1/scripts.ts
data/mods/gen1stadium/scripts.ts
test/sim/moves/mirrormove.js

This patch fixes the interaction between Mirror Move and Hyper Beam. When Mirror Move calls Hyper Beam and KO's the enemy, the Mirror Move user should not need to recharge. 
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-16#post-9004208
Partial trapping and charging moves called by Mirror Move are still messed up, but I think that's also an issue with the implementation of those moves themselves.

Gen 1: Fix Mirror Move Hyper Beam interaction

---

data/mods/gen6/random-teams.ts
data/mods/gen7/random-teams.ts
data/random-teams.ts

Discussed with @ACakeWearingAHat 
This raises the number of attempts taken by the Battle Factory algorithm to generate a team with the desired parameters, such as having exactly 1 Stealth Rocker and having exactly one hazard remover.
This should be considered only a temporary migitation; a better solution for the future would be to rewrite the generator around guaranteeing teammates with certain features
This won't badly tank performance; time and space complexity are both O(n) with the number of attempts, which is distributed geometrically

Battle Factory: Raise max generation attempts

---

data/mods/gen1/moves.ts
data/mods/gen1/scripts.ts
data/mods/gen1jpn/moves.ts
data/mods/gen1stadium/moves.ts
data/mods/gen1stadium/scripts.ts
test/sim/moves/counter.js

This patch fixes Counter so that it can counter attacks that hit a substitute. Previously, Counter could not counter attacks that hit a substitute, even if they are 'counterable' in Gen 1. The damage that is countered is the 'uncapped' damage (for non-Stadium), which can be important if the attack breaks the substitute.
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-16#post-8973042
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-30#post-8645108
Also fixes the same Counter/Substitute issue in Gen 1 Stadium, listed here:
https://www.smogon.com/forums/threads/stadium-bug-report-thread.3526616/page-3#post-8644615
(Does NOT fix the same issue with Bide: probably not working on that move for a while)

Gen 1: Fix Counter interaction with Substitute

---

sim/battle-queue.ts
test/sim/moves/counter.js

This patch fixes Counter so that it will always fail when the opponent's last selected move is Counter, including when both Counters are selected on the same turn.
Mentioned here and confirmed in many other places:
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/#post-5933177

Gen 1: Fix simultaneous Counters so that they both fail

---

data/mods/gen2/moves.ts
data/mods/gen3/moves.ts
data/mods/gen4/moves.ts
data/mods/gen5/moves.ts
data/moves.ts

Adds base power debugging messages (see [Discord discussion](https://discord.com/channels/630837856075513856/630845310033330206/1031028616458407976)). All the moves with custom base power should be covered now (save ones that are immediately obvious, e.g. Pledge moves or Magnitude).
In addition, this fixes Flail / Reversal's ratio calculation in Gen 5+. @Marty-D can you verify if they floor or not in Gen 4?
I've also removed an unnecessary piece of inheritance for Hidden Power in Gen III.

Add more debug messages for moves with custom base power

---

data/random-teams.ts

Keeps a counter with weaknesses and rejects mons when their typing would put one of them above 3 (or above half the team's size for larger teams).
This was attempted earlier and abandoned. I found the bug in the original implementation and fixed it.
https://discord.com/channels/294651453279174656/809406358654681168/1041802698112122951

Gen8 Random Battles: Limit the amount of pokemon weak to any type to three

---

data/abilities.ts
data/conditions.ts
data/mods/gen7/abilities.ts
data/mods/gen8dlc1/abilities.ts
data/moves.ts
test/sim/moves/rollout.js

This is ticketed [here](https://github.com/smogon/pokemon-showdown/projects/3#card-61615000)
Want to practise some web-dev. Hence, why I'm picking up a slightly obscure ticket. 
Some notes:
* I'm not sure I've correctly used (or abused) some of the event hooks - for example, `onAfterMove` for checking if we need to store the multiplier for the next non-rollout move. 
* The ticket also specifies that this bug was present pre-patch in Gen 8, though I'm not sure how to check for this (some `gen` attributes need to be ints, so "8 DLC1" wouldn't work).

Adding Rollout storage glitch

---

server/chat-plugins/mafia.ts

/mafia resetgame resets the game to night 0,removes all action data from the html tab,redistributes the roles and clears all deadlines.Players who died or were kicked are not added,players who subbed in or were added are not removed and no other setting set by the host is changed. (Copied some of the night commands because the other option included a lot of spaghetti).
Return to day X button removed when x = 0 (it couldn't possibly work in any way and would always throw an error message).
Nightstart is now default,/mafia daystart can be used instead to start at day.Actions from night 0 are not tracked.

Mafia: Add /mafia resetgame command and some other minor stuff.

---

sim/battle-actions.ts

This fixes a bug where dual-type Pokemon Terastallizing into one of their own types wouldn't receive STAB on their non-Tera type

Fix STAB while Terastallized

---

sim/battle.ts
test/sim/misc/trapmoves.js

This patch fixes the interaction of wrapping moves with residual damage (brn, psn, etc) KOs. Currently on Showdown, partial trapping does not end when either Pokemon faints to residual damage (or switches to a Pokemon that faints to residual damage). 
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-14#post-8442413
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-15#post-8707376
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-16#post-9061756

Gen 1: Fix Wrap interaction with residual damage KOs

---

test/common.js
test/sim/abilities/emergencyexit.js
test/sim/abilities/flowergift.js
test/sim/abilities/iceface.js
test/sim/abilities/illusion.js
test/sim/abilities/pressure.js
test/sim/abilities/protean.js
test/sim/abilities/rockhead.js
test/sim/abilities/stormdrain.js
test/sim/abilities/wanderingspirit.js
test/sim/choice-parser.js
test/sim/items/choiceitem.js
test/sim/misc/dynamax.js
test/sim/misc/pledgemoves.js
test/sim/misc/target-resolution.js
test/sim/misc/terastal.js
test/sim/misc/weather.js
test/sim/moves/focuspunch.js
test/sim/moves/gmaxchistrike.js
test/sim/moves/gmaxsteelsurge.js
test/sim/moves/gmaxvolcalith.js
test/sim/moves/gmaxwildfire.js
test/sim/moves/maxguard.js
test/sim/moves/painsplit.js
test/sim/moves/photongeyser.js
test/sim/moves/shelltrap.js
test/sim/moves/spite.js

* Default gen is now Gen 9
* Tests specifically for Dynamax and other legacy mechanics were kept Gen 8
* FFA/Multi will continue to target Gen 8
* A couple tests I wasn't sure how to transition so I left a TODO notice

Unit Tests: Transition to Gen 9

---

data/pokedex.ts

Current evoConditions imply that the Malicious and Auspicious Armors need to be used within Zapapico.
This is not the case in my own experience and I can't find this info reflected anywhere else either.

Fix Charcadet evoConditions

---

data/mods/gen1/moves.ts
data/mods/gen1/scripts.ts
data/mods/gen1jpn/moves.ts
data/mods/gen1stadium/moves.ts
data/mods/gen1stadium/scripts.ts

This patch fixes the behavior of Wrap when it hits a substitute. Previously, a faster target with substitute up would be able to attack every second turn when being wrapped, and there were some other inaccurate behaviors as well.
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-11#post-6893249
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-14#post-8442413
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-15#post-8622471
https://www.smogon.com/forums/threads/rby-tradebacks-bug-report-thread.3524844/page-16#post-8999638
scripts.ts: By resetting the duration of the target's partial trapping every time Wrap hits the target's substitute, we ensure that the target will remain partially …

Gen 1: Fix Wrap when hitting a substitute

---

server/chat-plugins/datasearch.ts

This fixes gen 9 not working as a param in some commands, and prevents the same from happening in the future

Datasearch: Don't hardcode max gen numbers

---

data/text/abilities.ts

Specify physical attacks, special attacks don't trigger Toxic Debris. Moves do not need to make contact.  
It functions correctly but the description is vague and might confuse people.

Clean Toxic Debris desc

---

data/abilities.ts
data/text/abilities.ts
sim/global-types.ts

- Allow Mold Breaker to bypass Earth Eater and Good as Gold
- Make Guard Dog boost attack after Intimidate
- Remove all mentions of Hail from ability descriptions
- Add priorities to Protosynthesis/Quark Drive stat boosting events, and silently end those abilities in the `onEnd` event

Fix various Ability related issues

---

data/mods/gen1/moves.ts

In Gen 1, Sonic Boom can hit Ghost-types, which is not currently implemented. Mentioned here and in many other places, and confirmed with in-game testing:
https://www.smogon.com/forums/threads/mechanics-differences-between-generations.3668073/post-8553244

Gen 1: Sonic Boom can hit Ghost-types

---

data/pokedex.ts

All the new gen 9 evolution methods require a level up after satisfying the conditions; it's not an automatic evolve like Galarian Farfetch'd. Not sure where else this ought to be added.
Demo that Bisharp can evolve without Leader's Crest: https://twitter.com/Sibuna_Switch/status/1594022357030551556

Update Bisharp/Primeape evolution conditions

---

data/pokedex.ts

Ting-Lu's day 1 patch nerf was only partially implemented: -10 HP, **-5 Def, +5 SpA**.

Correct Ting-Lu's stats

---

data/formats-data.ts

This change prevents these forms from being used in formats that ban nonexistent Pokemon but don't validate obtainable forms, such as Gen 9 Hackmons.
Reported here: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9403024

Mark several forms as past gen only

---

sim/dex-moves.ts
test/sim/dex.js

In https://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts#L6756 G-Max moves are classified as `isNonstandard: "Gigantamax"` but after the gen 9 update they are now reporting `gen: 9` and as a consequence `isNonstandard: "Future"`.
I added 3 tests to illustrate the problem and the last two fail in master right now.
```js
assert.equal(Dex.forGen(8).moves.get('G-Max Befuddle').gen, 8); // is 9
assert.equal(Dex.forGen(8).moves.get('G-Max Befuddle').isNonstandard, "Gigantamax"); // is "Future"
```
The reason is in https://github.com/smogon/pokemon-showdown/blob/master/sim/dex-moves.ts#L568 where all moves with num >= 827 are assumed to be gen 9. But since all gmax moves have a dummy num of 1000 they are considered to be gen 9.
I added a quick fix to work around that. This will …

sim/dex: G-Max Move Handling Changed Unexpectedly With Gen 9 Update

---

data/moves.ts
data/text/moves.ts

Left a TODO comment to implement the "preparing to tell a bad joke" message, because that requires an event before `onBeforeMove` which we don't currently have.

Fix Chilly Reception failing with no switches left

---

data/moves.ts
data/text/moves.ts

Returning `NOT_FAIL` is just an assumption based on the fact that the regular substitute's failures don't double Stomping Tantrum's power.

Fix Shed Tail messages and return value for fails

---

data/mods/gen1/scripts.ts
data/mods/gen1stadium/scripts.ts
test/sim/moves/explosion.js

This patch fixes Selfdestruct/Explosion when used against semi-invulnerable (Dig/Fly) enemies. Using Explosion should faint the user, but currently on Showdown it doesn't.
Also, adding a hint for the Disable/Explosion-Rage interaction.

Gen 1: Fix Explosion not fainting user when target is semi-invulnerable

---

data/mods/gen1/moves.ts
data/mods/gen1/scripts.ts
test/sim/moves/substitute.js

In Gen 1, Confusion/Psybeam's secondary effect should be able to confuse enemies behind a substitute, as long as the substitute is unbroken. Also, the confusion chance should be 25/256, not 26/256. This is in contrast to other moves with '10%' chance of a secondary effect, like Flamethrower, which have a 26/256 chance.
https://github.com/pkmn/engine/blob/main/src/lib/gen1/README.md
https://github.com/pret/pokered/blob/master/engine/battle/effects.asm (lines 1112-1116)

Gen 1: Fix Confusion/Psybeam confusion chance and substitute interaction

---

data/mods/gen1stadium/scripts.ts

This patch fixes an omission with a previous Wrap-related fix that could cause Stadium battles to crash when a wrapping move KOs an enemy.
Previous change: https://github.com/smogon/pokemon-showdown/pull/9007
Crash: https://replay.pokemonshowdown.com/gen1stadiumou-1717693225-ea0vym1qnuplwtvfsf9780bo9pcg4uipw

Gen 1 Stadium: fix battle crashing when Wrap KOs an enemy

---

config/formats.ts

Also corrects BSS's Min Source Gen. Neither has an official ladder right now, but uses the "Official Rules 1" challengeable format available in-game currently. The ladder will be officially revealed December 1, but as expected with a new generation, there is pretty insane demand for Showdown practice. It's unclear if these Battle Stadium Doubles will mirror VGC rules (there's talk of Regional Dex-only or Paradox bans), so if VGC actually gets its ruleset we'll probably rename and nuke this ladder.

Add Battle Stadium Doubles

---

data/mods/gen1/scripts.ts
data/mods/gen1stadium/scripts.ts

Gen 1 treats Reflect/Light Screen as volatiles, not side conditions, so there is no reason to have these lines of code. This won't actually change any mechanics, just clean up some unnecessary code.

Gen 1: remove code referring to screens as side conditions

---

test/sim/items/punchingglove.js

Just added some basic unit tests based on known behavior & what has been confirmed by others on the research thread, e.g [here](https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9406865), for the sake of documentation. The tests pass with the current implementation.
Noteworthy difference to Protective Pads in gen 8; Punching Glove seems to bypass Pickpocket based on testing done in the research thread. Perhaps it would be interesting to retest Protective Pads against some abilities in-game as well at some point, although there are likely more important mechanics to study at the moment.
Feel free to close if anything feels off!

Punching Glove: Add basic unit tests

---

data/mods/gen1/scripts.ts
data/mods/gen1stadium/scripts.ts

This patch removes useless RNG rolls for Gen 1 secondary effects (e.g. Ice Beam's chance to freeze) when the move hits a substitute or the target has already fainted. The code will now first check if the target is available before rolling RNG to see if the secondary effect will be applied.

Gen 1: Remove unnecessary RNG rolls for secondaries

---

data/mods/gen1/scripts.ts
data/mods/gen1stadium/scripts.ts

This patches fixes a couple of inaccuracies in damage calculation:
- The damage should be clamped between 0 and 997 (i.e. only clamped from above), not 1 and 997.
- Type effectiveness should be applied individually against each of the target's types. For example, Ice attacks against Articuno are not very effective against the first type, and super effective against the second, and this affects the damage calculation.
https://www.smogon.com/forums/threads/past-gens-research-thread.3506992/#post-5878612

Gen 1: Fix inaccuracies in damage calculation

---

data/moves.ts
sim/battle.ts
sim/dex-moves.ts
sim/pokemon.ts

This allows moves to define their own onDisableMove callback, which replaces the hardcoded cases in Battle#nextTurn.

Refactor self-disabling moves

---

test/sim/items/abilityshield.js

I have commented a link to the particular post for tests that were based on results from the SV mechanics research thread! Not all of them pass with the current implementation; the failing tests are suppressed with `.skip` for the time being.
The first three tests were based on my understanding and are technically not confirmed in the thread, but I believe they document the general consensus of how the item works.

Ability Shield: Add tests based on SV research thread

---

test/sim/items/abilityshield.js

Now that the updated implementation by pyuk has been merged into master, the previously failing tests can be unskipped

Ability Shield: Unskip tests that pass

---

data/mods/gen1/conditions.ts
data/mods/gen1/scripts.ts
test/sim/misc/statdownoverflow.js

This patches implements the stat down modifier overflow glitch (division by zero not implemented for obvious reasons):
https://www.youtube.com/watch?v=y2AOm7r39Jg
- Stats are no longer automatically clamped from above by 999. This clamping is applied only when stats are being raised by boosting.
- When a stat is boosted at 999 or unboosted at 1, the boost/unboost is followed by an unboost/boost of -/+1 to the stat, respectively. The stat remains at 999 or 1. For example, if a Mewtwo is at +4 Special with 999 Special and uses Amnesia, the final stat stage is +5, and the Special remains at 999. A hint message will display for the first time this occurs in a battle.
- When a stat is unboosted, the stat is no longer clamped at 999, which can cause the stat down modifier overflow glitch if the …

Gen 1: Fix stat modification, implement stat overflow glitch

---

data/mods/gen1/moves.ts
test/sim/moves/haze.js

This patches fixes the interaction between Toxic and Haze. After Haze is used, on cart, the previous Toxic counter is never referred to again. I simulate this behavior by making Haze remove the Toxic counter. While this is different to cart in implementation, it should be identical in result.

Gen 1: Fix Toxic-Haze interaction

---

data/mods/gen1/moves.ts
data/mods/gen1/scripts.ts
data/mods/gen1stadium/moves.ts
data/mods/gen1stadium/scripts.ts
data/moves.ts
sim/battle.ts
test/sim/moves/counter.js

This patch fixes some Counter inaccuracies:
- Draining, (Hi) Jump Kick recoil, and confusion damage update Battle.lastDamage (i.e. the healing/damage can be countered).
- Counter CAN work against counterable moves called by Metronome or Mirror Move.
Also, fixes rounding recoil/drain against substitutes, they should be rounded down.

Gen 1: Fix some more Counter inaccuracies

---

databases/migrations/chat-plugins/v7.sql
server/chat-commands/info.ts

Approved by US.
This PR infrastructure to record namechanges server-side. It's meant to be a native integration of Officer Jenny's `~alts` command that's used frequently among staff, but one that has a better data source than just watching join/leave messages. The renames will be stored in a fairly simple database table that's primary keyed on `oldID, newID` to cut down on data use. Each pair will also have the latest IP stored, updated whenever that rename happens.
Unlike `~alts`, this is gated to global staff for privacy reasons (and related IP data is restricted to moderators and up).

Info: Support accessing a log of alternate accounts

---

config/formats.ts

Shared Power no longer use the mod, it banned sleep moves instead.

Shared Power: Update bans

---

data/mods/gen1/scripts.ts
test/sim/misc/statdownoverflow.js

Fixes a couple little issues with the stat down overflow patch:
- Adds a space to the hint regarding div by 0
- Removes an unremoved console.log from the test
- Remove clamping for Reflect / Light Screen

Gen 1: Minor corrections for stat down overflow

---

data/moves.ts

- Glaive Rush now properly applies its effect when used 2 turns in a row
- Fixed the event used to modify accuracy (was setting Baxcalibur's moves to never miss instead of incoming moves)
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9418954

Fix Glaive Rush bugs

---

lib/crashlogger.ts
server/room-battle.ts

Doing this per Wob's approval. This is mostly a PR to see if anyone has a preference on how we do this or not. I chose to just send a `error` message back to the parent process (since that crashlogging is handled in the child) with the details of the error for logging if a restart is necessary, since I felt that was the simplest option.
Will merge in a day or so if no one has any opinions.

Rooms: Only lockdown after restarts when battles crash

---

data/abilities.ts
data/items.ts
test/sim/abilities/neutralizinggas.js

As suggested by: [Neutralizing Gas & Gluttony](https://github.com/smogon/pokemon-showdown/projects/3#card-52059175)
Code is mostly from [Karthik's fix](https://github.com/smogon/pokemon-showdown/pull/8250), I just fixed the bug that caused the rollback

Wait for damage to activate Gluttony after Neutralizing Gas end

---

data/abilities.ts
data/items.ts
test/sim/abilities/commander.js

Also added some basic tests for Commander. Apparently Toxic is done in a janky way (maybe it was changed because of the sure-hit Toxic glitch stuff?), so that currently fails but it has to do with Toxic, not Commander, so I think it's outside the scope of this PR.

Fix Commander vs Transform and Eject items

---

data/mods/gen2/moves.ts
data/mods/gen3/moves.ts

This patch fixes the accuracy of some moves for Gen 2-3:
It is important to list moves that don't check for accuracy as having true accuracy, even if they are listed in-game as having 100% accuracy. Otherwise other effects that can cause moves to miss (like BrightPowder) can come into play when they shouldn't. https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-84#post-9373204
Gen 2:
- Lock-On and Pain Split should have 100% accuracy (not true)
- Nightmare should have true accuracy (not 100%)
https://www.smogon.com/forums/threads/gen-2-ps-development-post-bugs-here.3524926/post-8557865
Gen 3:
- Block, Mean Look, Mimic, Pain Split, Role Play, Skill Swap, Spider Web, Vital Throw, and Yawn bypass accuracy checks, even though they are listed …

Gens 2-3: Fix accuracy of moves

---

data/mods/gen1/moves.ts
data/mods/gen1/scripts.ts
data/mods/gen1jpn/moves.ts
data/mods/gen1stadium/moves.ts
data/mods/gen1stadium/scripts.ts
test/sim/moves/counter.js

This patch fixes many counter bugs:
- Sonic Boom can now be countered (previously it couldn't).
- OHKO moves do 65535 damage (matters if OHKO move hits a sub and gets Countered).
- Reducing damage to target.hp when damage > target.hp is now done outside getDamage: this ensures that moves that return early in getDamage, like Seismic Toss, OHKO moves, etc., still get their damage reduced when they OHKO a lower HP enemy, hence ensuring that Counter in the future doesn't do more damage than it should.
- Metronome calling Counter will always fail, as it should. This is done by zeroing battle.lastDamage for most moves (including Metronome) before calling tryMoveHit. For regular damaging moves, this makes no difference, since we would previously zero it after tryMoveHit only if the move …

Gen 1: Fix more Counter bugs

---

data/random-teams.ts

In unmodded gen9 HC there are 355 legal items, more than a third of which are Balls or TRs. That makes them annoyingly common as they do nothing, and are also generally uninteresting (especially the TRs). We do want to retain the possibility of rolling any item, but we also want to dramatically scale back their relative probability. Hence, these are now rejected with 95% probability (subject to having enough items in the pool in HC).
Link to relevant discussion in Rands Auth Discord: https://discord.com/channels/294651453279174656/1041098998624288990/1050162709448110091

Hackmons Cup and Challenge Cup: Make TRs and Balls much less likely

---

data/rulesets.ts

VGC has announced open team sheets as the standard for in-person play. Open team sheet = all information about the Pokemon, except stats. ``Teams.export()`` can already do this with an optional ``hideStats`` argument (thanks past me!).
I am not sure about the Teams import at the top of the file, or if it should be done inside the rule.
Opinions on design are also appreciated:

Implement Open Team Sheets rule

---

config/formats.ts

A piece of code always increments the donor's value after it gets initialized to 1, making it always reject. This should be able to fix it.

Inheritance: Fix Donor Clause

---

sim/battle-actions.ts
test/sim/abilities/dancer.js

Previously, when copycat selected a dance move, a dancer would then target the pokemon that used copycat instead of copycat's inner move's target.
Correct interaction verified in game: https://twitter.com/WeedleTwineedle/status/1601925296898592770

Fix copycat dancer interaction

---

server/chat.ts
sim/pokemon.ts
test/sim/moves/transform.js

This pull request is in response to [this card](https://github.com/smogon/pokemon-showdown/projects/3#card-85843016). 
> In Gen 5+, Transforming with an entrance Ability (e.g. Intimidate) into a Pokemon with the same entrance Ability will not reactivate the Ability.
This behavior has been implemented through an additional check in setAbility. The corresponding test in `test/sim/moves/transform.js` is now passing.

Transforming into Pokemon with the same ability (Gen 5+)

---

server/chat-plugins/random-battles.ts

* Update /setodds to gen 9. Uses Gen 9 Random Battle as the default format and adds a new possible parameter "tera" (or "teratype" if you prefer).
* Minor QoL improvement to /randbats: It now counts the total number of *movepools*; they will all be collapsed iff there are 3 or more.
* * In a similar vein, gen 1 sets no longer use \<details>
* Some minor code cleanup here and there

Update /setodds and /randbats

---

data/random-sets.json
data/random-teams.ts

- prevent Battle Bond Greninja
- Prevent Flash Fire on a lot of Fire-types
- Remove Pain Split from Rotom-W
- Prevent Life Orb Trailblaze, Rapid Spin, and Flame Charge

Random Battle fixes

---

data/moves.ts
test/sim/moves/orderup.js

Fixes Sheer Force-boosted Order Up behavior (should increase BP and not actually negate the stat boost lol) and fixes the behavior with failures (failing at roughly the same timing as Steel Beam would set its 50% HP flag or later will still give Dondozo the boost).

Fix Order Up failure and Sheer Force mechanics

---

data/moves.ts

Bug report: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9434692
Target of the `Accuracy` event is the target of the move.
Hopefully this replay with the new code is convincing enough: https://cdn.discordapp.com/attachments/411893360911974413/1052442904175587419/Gen9AnythingGoes-2022-12-13-shellyfan0845-mathy.html

Fix Glaive Rush accuracy effect

---

data/mods/gen8/abilities.ts

Adds a rating to every ability in gen8, taken from the final commit before the gen9 implementation.
With gen9 random battles in development, ability scores are being changed resulting in changes in past-gen set generation. This is especially prevalent because the set generation system will behave differently in gen9. 
The cognitive load of having to take into account the effects on all previous gens when changing an ability rating is now too large, so things are starting to fall through the cracks. This is compounded by the non-programmers who do the bulk of randbats upkeep not being familiar with inheritance as a concept. As a specific example: the rating of guts was raised by 0.5 in preparation for gen9, leading to Machamp in gens 4 and 6 (and others?) rolling Dynamic Punch without No …

Add rating for every ability in gen 8

---

test/random-battles/gen9.js

This adds two tests for Gen 9 Random Battle:
1. Checks that every Pokemon gets a moveset with 4 moves (except Ditto). 
2. Checks that every move on every set is obtainable. Some moves are only obtainable with a non-default teamDetails (for example, Cryogonal only gets Haze if the team has a hazard remover), so we consider all possible relevant teamDetails. This looks like it would take a long time, but the move is usually obtained after only a few moveset generations, and as soon as we obtain the move, we can stop and move on to the next move. On my local machine this test took about 500ms, though I've marked it as slow to future-proof.

Add tests for Gen 9 Random Battle

---

data/cg-teams.ts

The weakness counter to prevent having 4+ mons weak to the same type is currently incrementing while still checking. This can cause types to be already incremented before the species is rejected because of another type, thus incorrectly increasing the counter. In the worst (rare!) case this leads to teams being generated with too many weaknesses as there is no more room to reject any.

Computer-Generated Teams: Fix weakness counter incrementing too soon

---

sim/battle-actions.ts
test/sim/moves/pollenpuff.js
test/sim/moves/ragefist.js

Instead of checking if the move is a status move, check if the move actually dealt damage (that is, it's actually a number and not a boolean like Pollen Puff is here). I also cleaned up the Rage Fist test formatting and snuck in an additional Rage Fist test for Substitute, in addition to a test for Pollen Puff's interaction with type immunities.

Fix interaction of Pollen Puff and Rage Fist

---

data/random-sets.json
data/random-teams.ts

This Pull Request perfoms the following changes:
-Add Shuca Berry Liquidation Pincurchin
-Add Acrobatics as an option for Hawlucha; can coincide with Brave Bird
-Prevent Heavy-Duty Boots Sandy Shocks
-Transform Palafin into a Bulky Attacker, replacing Life Orb with Leftovers and guaranteeing Jet Punch
-Harvest is forced with Substitute, preventing Solar Power Tropius on teams with Sun and simplifying other Harvest-related code.
-Luvdisc will no longer get Focus Sash
-Shell Side Arm will no longer reduce Glowbro's Attack
-Breloom will now always get Mach Punch and no longer always get Close Combat
-Black Sludge is removed
-A large number of Tera Type pools have been updated to be, hopefully, better.
This change will be reviewed by Random Battles room staff, and I will post when it is …

Random Battles fixes and updates

---

data/random-teams.ts
test/random-battles/gen9.js

This copies over some code from gen 8 random battles for checking the types of 'battle only' species, that was previously omitted from the gen 9 code.

Fix Gen 9 Monotype Random Battle type check

---

data/random-sets.json
data/random-teams.ts
test/random-battles/all-gens.js

* Tests the new rands file for validity/formatting
* Some Pokemon had moves illegal in Gen 9, this was fixed
* A few extra changes as a bonus

Random Battle fixes and updates

---

config/formats.ts
data/mods/gen1/moves.ts
data/mods/gen1stadium/moves.ts
data/mods/gen2stadium2/scripts.ts
data/rulesets.ts
sim/battle.ts
test/sim/moves/bide.js

This patch fixes many issues with the current implementation of Bide:
- Bide's damage accumulation is now done correctly: the stored damage is incremented (by battle.lastDamage) every time the Bide user 'moves', not when the Bide user gets hit. This includes just before unleashing Bide, and does not include the turn that Bide is used. This means the stored damage can increase if the opponent switches or uses a move that doesn't reset lastDamage (e.g. Teleport).
- Bide's duration is paused if the user is asleep, frozen, partially trapped or flinching (and Bide's damage does not accumulate in that turn).
- Bide can now hit an enemy Substitute.
- Bide's stored damage will be reset to 0 if an enemy faints. This situation can result in a desync on cart, so we invoke Desync Clause Mod.
- Bide …

Gen 1: Fix Bide's implementation

---

data/mods/gen8/moves.ts
data/moves.ts
test/sim/moves/curse.js

In Gen 9, Ghost-type Curse can now be targeted at either opponent or an ally. However, if Curse is targeted at an ally, it instead selects either opponent randomly instead. I used the ``ModifyTarget`` handler to accomplish this, but I'm not sure if I've done everything quite right with it, so reviews are appreciated.

Gen IX: Fix Curse targeting behavior

---

sim/battle-queue.ts
sim/battle.ts
sim/side.ts
test/sim/moves/revivalblessing.js

* Pokemon revived in an active slot in Doubles should run a switch immediately
* Pokemon should not be able to make a move the same turn they fainted and were revived
* Fixes Revival Blessing choices not exporting to input log correctly

Refactor Revival Blessing to be an action + fixes

---

data/moves.ts

- Stat boosts are now applied after hazards and subs are cleared.
- "But it failed!" will appear when there are no hazards to remove and the user is at +6 Atk/Spe.
- "POKEMON's STAT won't go any higher!" will never appear. For example, if the user is at +6 Attack but not +6 Speed, only the speed boost is mentioned.

Tidy Up fixes

---

data/items.ts
data/mods/gen8/items.ts
data/mods/gen8/pokedex.ts
data/pokedex.ts
data/text/items.ts

- Added the Adamant Crystal, Lustrous Globe, and Griseous Core, which are all required to be held by their respective Origin formes
- The Griseous Orb is now Identical to the other Orbs, providing a power boost to base Giratina and is able to be knocked off
This definitely would affect metagames like randbats, which currently has the origin formes holding items like Choice Specs and Choice Scarf, so this would be a pretty big nerf to them. ~~This is also a direct nerf to Giratina Origin, as it can no longer get the power boost from Griseous Orb while still being locked to one item.~~ I don't think there's much of an argument to not implement this since we usually try to follow cart mechanics as much as possible, but I just thought that some might not want this change with it affecting …

Implement proper Origin forme mechanics

---

data/mods/gen4/rulesets.ts
data/mods/gen5/rulesets.ts
data/mods/gen7/rulesets.ts
data/rulesets.ts

~~I know this literally does not matter~~
The Dudunsparce formes share a menu sprite, so you shouldn't be able to tell which one the opponent brought.

Don't reveal Dudunsparce forme on Team Preview

---

data/mods/gen8/moves.ts
data/moves.ts
test/sim/moves/curse.js

I am like, 90% sure the only reason this was crashing was because of the restart (restarts load saved battles with new mechanics), but in the meantime Karthik pointed out it's better to put the target change in ``onModifyMove`` anyway.

Gen IX: Really fix Curse targeting behavior

---

data/items.ts
data/mods/gen7/items.ts
data/mods/gen8/items.ts
data/mods/gen8bdsp/items.ts
data/text/items.ts

The following items are now correctly marked as unobtainable:
Safari Ball
Sport Ball
Galarica Cuff
Galarica Wreath
Strange Ball
The following items are now correctly marked as past:
Bluk Berry
Pinap Berry
Macho Brace
Sea Incense
Lax Incense
Metal Powder
Quick Powder
Odd Incense
Rock Incense
Full Incense
Wave Incense
Rose Incense
Magmarizer
Strawberry Sweet
Love Sweet
Berry Sweet
Clover Sweet
Flower Sweet
Star Sweet
Ribbon Sweet
In addition, I added the new Strange Ball item (consistent with us having other unobtainable Poke Balls) and removed Energy Powder. I don't see why we had Energy Powder and no other healing items; it doesn't have a unique Fling BP like Rare Bone or some sort of "special significance" like Bottle Cap. If we still want it I can add it back, but idk why we would need …

Fix more SV item legality

---

data/text/abilities.ts

Dauntless Shield and Intrepid Sword only activate once per game, and Libero/Protean activate once per switch-in. Battle Bond changed entirely.

Update some ability descriptions for Gen 9

---

test/random-battles/gen9.js

This improves the moves test for gen 9 random battle:
- iterate over rounds in the outer loop, and different teamDetails in the inner loop. This should speed up the test for situations where a move can only be obtained with non-default teamDetails.
- Add a set generation for leads, future-proofing for situations where a move can only be obtained in the lead slot.

Gen 9 Random Battle: improve moves test

---

.mocharc.json
data/mods/gen1/conditions.ts
data/mods/gen1/moves.ts
data/mods/gen1/scripts.ts
data/mods/gen1jpn/conditions.ts
data/mods/gen1jpn/moves.ts
data/mods/gen1stadium/conditions.ts
sim/battle-actions.ts
test/sim/misc/twoturnmoves.js
test/sim/moves/mirrormove.js

This patch does a few things:
- pokemon.lastMove is reset to null whenever a switch is made. This ensures that Mirror Move fails when used by a newly switched in Pokemon, against an enemy that has not attacked since the switch.
- The charging turn of a two-turn move does not update pokemon.lastMove. In particular, Mirror Move will use the previous move made by the enemy (or fail if there was no previous move). If the enemy's Metronome calls a two-turn move, Mirror Move will call Metronome.
- Two-turn moves are paused if the Pokemon using the two-turn move is put to sleep, frozen, flinched, or partially trapped. The Pokemon cannot switch.
- Two-turn moves end if they fail because they are disabled.
- Two-turn moves only use PP in the attacking turn, not the charging turn.
- If a two-turn …

Gen 1: Implement Dig/Fly invulnerability glitch, partially fix charging moves and Mirror Move

---

test/main.js

Adding quotes around the path in a command line command make it work with whitespace in the path.
I thought "User Files" was a default directory in Windows, but now I'm thinking I may have put the whitespace there myself which would make me very silly. Regardless, this fix should help some people (including me).

Fix mocha for paths with whitespace

---

tools/build-utils.js

This is needed for debuggers to work
LMK if this should be made optional via environment variable

Build: Generate sourcemaps

---

data/mods/gen8/factory-sets.json

Magby has been banned from LC, so removing it from BF.

Gen 8 Battle Factory: Remove banned Pokemon

---

data/mods/gen6/factory-sets.json
data/mods/gen7/factory-sets.json

It turns out there were many pokemon banned from tiers since BF has been updated:
Gen7:
- kommoo UU
- feraligatr RU
- froslass RU
- quagsire RU
- diancie NU
- quagsire NU
- slowbro NU
- vileplume NU
- mesprit PU
- weezing PU
- lilligant PU
- pyroar PU
- togedemaru PU
- froslass PU
gen6:
- Azelf UU

Gen 6/7 Battle Factory: Remove more illegal pokemon

---

data/mods/gen3/random-teams.ts

The new gen3 PU tier made the now-PU mons level 80, as that's the default. Created a new level tier for PU at level 90, and while there upped Ditto and Unown from 99 to 100, as we don't actually have a policy of no lvl100 mons.

Gen 3 Random Battle: Add levels for new PU tier

---

data/mods/gen8/random-teams.ts

To preserve Zoroark's illusion in randbats, its level is set to the level of the last Pokemon in the team. This feels bad when that Pokemon is particularly low level, so we reject those with level<72 in the last slot if we have a Zoroark in the team.
Discussed in randscord here: https://discord.com/channels/294651453279174656/809406358654681168/1059265000545452032

Gen 8 Random Battle: Set a minimum level for Zoroark

---

server/chat-commands/info.ts
server/tournaments/index.ts

* Add a link to the battlerules page
* Remove "banlist" from help as it's deprecated
* Bonus typo fix in /battlerules

Tournaments: Update `rules` help

---

data/conditions.ts

Apologies if this is too opinionated of a change, but I'm *fairly* certain this is the only usage of `-activate`  that doesn't provide the target of the effect being activated. The target isn't actively used in rendering on the client, but this should improve the sim protocol's consistency.
~~Also if it matters, Power Construct is an example of an `-activate` message that provides the target without using it to render anything on the client. (see: [Power Construct's protocol message](https://github.com/smogon/pokemon-showdown/blob/b37e8b2499d6940200e5026dc06c1f760feeb4e1/data/abilities.ts#L3049) and [its text not making use of the target](https://github.com/smogon/pokemon-showdown/blob/b57c75bf5431ef8032ba851125b116af83a9074b/data/text/abilities.ts#L1228)).~~ Actually the target is still …

Change Delta Stream's effectiveness activation to use `-fieldactivate` instead of `-activate`

---

data/mods/gen8/random-teams.ts
test/random-battles/gen8.js
test/random-battles/tools.js

This pull request improves unit testing by including the Pokemon in the lead slot sometimes when isLead is not explicitly set. This revealed 2 bugs (heh), that are fixed as follows:
* Shuckle was not rolling Sticky Web in the lead slot as it was getting rejected in favor of Stealth Rock.
* Now, Shuckle *always* runs *both* hazards.
* Scyther was jntended to run Heavy-Duty Boots if it had 3 attacks. However, in the lead position it was still being given Eviolite.
* This was in fact intended; the test was assuming Scyther would never be the lead. However if it has U-Turn it should run Boots even if it's the lead, so the code and test were updated to reflect that.

Gen 8 Random Battle: Fix lead bugs

---

data/mods/gen1/scripts.ts

This fixes the battle log so that the second turn of a two-turn move will include "[from]<move>", e.g. "[from]Skull Bash". This was unintentionally removed in https://github.com/smogon/pokemon-showdown/pull/9243.
Edit: also adds a hint for stat overflow in Gen 1

Gen 1: Fix battle log for charging moves, add hint for stat overflow

---

data/mods/gen1/moves.ts
test/sim/moves/bide.js

This patch fixes Bide so that it restricts the choices of the Pokemon using it, by disabling the Pokemon's other choices. If a Bide user is disabled, its only choice will be Struggle.

Gen 1: Fix Bide selections

---

data/abilities.ts

- Make sure it doesn't work on a Palafin that transformed
- Make it a permanent ability
- Fixed timing of Hero message (tested in-game, switching in Palafin-Hero and a faster intimidate Pokemon after a double KO had Intimidate activate first)

Fix Zero to Hero

---

config/formats.ts
data/pokedex.ts

Also refactors Paradox Pokemon to not count as Sub-Legendary, since we have the tag for Paradox Pokemon now and it was just an assumption they were classified as Sub-Legendary.

VGC/BSS: Add Series 2

---

config/formats.ts
data/rulesets.ts
server/chat-commands/core.ts
server/room-battle.ts
server/rooms.ts

WIP with major help from Karthik.
The announcement of open team sheets in VGC play was met with mixed reception. For various reasons, some players prefer closed team sheets, and some prefer open team sheets. It is undesirable to make two ladders, however, as that is likely to fracture the playerbase and probably be lopsided in favor of closed team sheets. The current solution is to make opting into OTS very easy, while also not being forced to reveal the player's OTS to spectators or in replays. Players can then choose to agree or not to agree to OTS.
The main issue with current implementation is that player-specific information (e.g. specific player damage, or in this case, uhtml with team sheet information) is not retained if a player happens to refresh during a game because of e.g. a …

Implement opt-in Open Team Sheets

---

data/mods/gen5/formats-data.ts
data/mods/gen5/random-teams.ts
data/mods/gen6/formats-data.ts
data/mods/gen6/random-teams.ts
data/mods/gen7/formats-data.ts
data/mods/gen7/random-teams.ts

Approved by Random Battles staff. Many of these changes span multiple gens, so doing them together.
Cross-generation changes:
Gens 5-7: Guarantee Moonlight on Cresselia and (non-Trick Room) Musharna
Gens 5-6: Guarantee Milk Drink on Miltank
Gens 5-6: Guarantee Natural Cure ability on Altaria
Gens 6-7: Reflect/Light Screen should be equally likely and (almost always) appear together
Gens 6-7: give Sunflora Specs set instead of Sunny Day
Also, some minor set changes and guaranteeing recovery on support/defensive mons in Gen 6.
https://discord.com/channels/294651453279174656/763039843654565941/1062108771893133502
https://discord.com/channels/294651453279174656/809413252517462026/1061458046829731952
https://discord.com/channels/294651453279174656/763039178211721236/1062110683048722555

Gens 5-7 Random Battles updates

---

data/mods/gen1/conditions.ts
data/mods/gen1/moves.ts
data/mods/gen1/scripts.ts
data/mods/gen1stadium/moves.ts
test/sim/moves/rage.js
test/sim/moves/thrash.js

This patch fixes thrashing moves' mechanics in Gen 1:
- Thrash will now lock the player in no matter what. Previously it would not lock the player if the move hits and breaks a substitute.
- Thrash is now paused when the user is asleep, frozen, flinching, or partially trapped.
- Thrash is now paused when the user has Thrash disabled.
It also implements the Thrash and Rage accuracy bug: https://www.youtube.com/watch?v=NC5gbJeExbs

Gen 1: Fix Thrash and Rage mechanics

---

data/text/moves.ts

Corrects the description of Mirror Move in Gens 1-2. Mirror Move's behavior was fixed in the PR: https://github.com/smogon/pokemon-showdown/pull/9243

Gen 1-2: Fix Mirror Move description

---

data/mods/gen3/random-teams.ts
data/mods/gen5/random-teams.ts
data/mods/gen7/random-teams.ts

Adds the limit of 3 Pokemon per team weak to a single type to Gens 2-7. The limit is already present in Gens 8 and 9. Several million teams have been generated for each gen with no issue.
https://discord.com/channels/294651453279174656/763039178211721236/1063173009399091210

Gen 2-7 Random Battles: add limit of 3 Pokemon weak to each type

---

data/abilities.ts
test/sim/abilities/swordofruin.js

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-104#post-9468014

Fix interaction of Ruin Abilities with themselves

---

data/mods/gen6/random-teams.ts
data/mods/gen7/random-teams.ts

Approved by Random Battles staff.
This patch guarantees Quiver Dance on any Pokemon that has it in its moveset and doesn't have Defog, Sticky Web, or U-turn in its movepool, or currently have a choiced set (4 Special attacks).
It also guarantees Bug Buzz on Butterfree and Venomoth in Gens 6-7, and Eruption on Typhlosion in Gen 6. Also prevents Moody on Bibarel in Gen 6.
https://discord.com/channels/294651453279174656/763039843654565941/1064260276616171671
https://discord.com/channels/294651453279174656/809413252517462026/1064245841071710299

Gen 6-7 Random Battles updates

---

config/formats.ts

Electrify is not in gen9 and should not be on the banlist

Remove dexited mechanics from OM banlists

---

config/formats.ts

`singleEvent` shouldn't be used here because it overrides the `event` property and thus breaks `chainModify`.
Didn't commit the test but here is what I used:
```js
it("should apply base power modifiers from the forte", function () {
battle = common.createBattle({formatid: 'gen9fortemons'}, [[
{species: 'ampharos', ability: 'static', item: 'facade', moves: ['tackle']},
], [
{species: 'grafaiai', ability: 'prankster', moves: ['toxic']},
]]);
battle.makeChoices(); // team preview
battle.makeChoices();
const grafaiai = battle.p2.active[0];
assert.bounded(grafaiai.maxhp - grafaiai.hp, [65, 77]);
});
```

Fortemons: Fix base power and type modifiers

---

server/chat-commands/info.ts

`/dt9` is not quite the same as `/dt`, as `/dt` defaults to the gen of the game you're in. Also, `/help dt` indicates that `/dt9` should be supported.

Chat commands: Add support for /dt9

---

data/mods/gen1/scripts.ts
test/sim/moves/thrash.js

Confusion due to fatigue (after thrashing) was incorrectly and unintentionally made non-silent in the previous PR linked below. This fixes it, so that the confusion is once again silent.
https://github.com/smogon/pokemon-showdown/pull/9315

Gen 1 Thrash: Confusion from thrashing should be silently added

---

config/formats.ts

Flinch moves, Fury Cutter and Flame Charge restricted, Houndstone banned.

Fortemons: Update banlist

---

config/formats.ts

It is currently impossible to play any Let's Go Doubles formats on Pokemon Showdown. Adding this format resolves this. Placement in the format list replicates [BDSP] Doubles OU's.

Add [Let's Go] Doubles OU format

---

data/mods/gen1/formats-data.ts
data/mods/gen2/formats-data.ts
data/mods/gen2/random-teams.ts
data/mods/gen3/formats-data.ts
data/mods/gen3/random-teams.ts
data/mods/gen5/formats-data.ts
data/mods/gen5/random-teams.ts
data/mods/gen6/random-teams.ts
data/mods/gen7/random-teams.ts

Gen 1: Fix Tangela's set so that it has guaranteed sleep powder
Gen 2: 
- some moveset changes
- Rapid Spin can no longer generate on the same set as Curse
Gen 3: some minor moveset changes. Latias can get a mono-attacking Refresh set, and Aipom can now get Thunder Wave.
Gen 5: 
- Some moveset changes
- Reflect and Light Screen now usually generates together
- guarantee Icicle Spear on Shell Smash Cloyster
- Banette can get a Choice Band set with Trick
- Kyogre and Typhlosion can now get Choice Specs as their item
- Calm Mind mono-Psychic types shouldn't have Shadow Ball as their only coverage
Gen 6-7: Fix Expert Belt condition
https://discord.com/channels/294651453279174656/809413397840920586/1066465152758730863 …

Old Gens Random Battles updates

---

data/mods/gen4/formats-data.ts
data/mods/gen4/random-teams.ts

- Adds Pikachu, with Light Ball
- many set changes
- Light Screen and Reflect should usually appear together, if they are both in a Pokemon's movepool
- Force Dark STAB on Drapion (Poison Jab has been added)
- fix Wish/Toxic interaction with Protect: they should usually appear together
- Fix Yanmega getting Protect with Leftovers and Tinted Lens
- Farfetch'd will get choiced item with 4 attacks
- Fix an issue that was preventing Hitmonlee and Hitmonchan from getting Mach Punch
https://discord.com/channels/294651453279174656/765617449202352208/1066780492285882529

Gen 4 Random Battles updates

---

config/formats.ts

Removed too much of the absolute trademark bans that I forgot that damaging moves shouldn't be trademarks.

Trademarked: Restrict nonstatus moves

---

server/chat-plugins/mafia.ts

A new theme includes a role that can change someone's alignment to Town when discarded.

Mafia: Prevent incorrect alignment.

---

data/mods/gen2/random-teams.ts
data/mods/gen4/formats-data.ts
data/mods/gen4/random-teams.ts
data/mods/gen8/random-teams.ts

Gen 2 changes: Ditto will always get Metal Powder as its item
Gen 2-4 changes: Allow setup moves to appear with fewer attacks if Baton Pass is in the set
Gen 4 changes:
Many movepool and set generation tweaks, outlined in the two links below from Random Battles Auth:
https://discord.com/channels/294651453279174656/765617449202352208/1068574416675557460
https://discord.com/channels/294651453279174656/765617449202352208/1068864345888530532

Gen 2-4 Random Battles updates

---

data/mods/gen5/formats-data.ts
data/mods/gen5/random-teams.ts
data/mods/gen6/formats-data.ts
data/mods/gen6/random-teams.ts
data/mods/gen7/formats-data.ts
data/mods/gen7/random-teams.ts

Gen 5-6: Castform is set to level 100
Gen 5:
- Sceptile is changed to get a more consistent Swords Dance set
- Pokemon with 3 Dark attacks will get Black Glasses as their item
- Remove mentions of Baton Pass in the code, BP doesn't exist in rands
- Castform will appear at a normal rate in Gen 4, where it does not have multiple formes with sets (technically an update for Gen 4, but it is done in the gen 5 file)
- Actually remove Cherrim-Sunshine
Gen 6-7:
- some set tweaks
- Pinsir-Mega won't get Close Combat and Earthquake together
- Wish/Protect will usually appear together
Changes discussed in rands auth discord, including:
https://discord.com/channels/294651453279174656/763039178211721236/1068949519007494315 …

Gen 5-7 Random Battles updates

---

data/random-sets.json
data/random-teams.ts

- Some minor tera type and movepool updates, including giving all Pokemon with Last Respects a fixed Choice Scarf set
- Salt Cure now counts as STAB, and is an enforced move
- Created a list of Pokemon called PriorityPokemon, which have STAB priority enforced, and the STAB priority counts as regular (and tera, if appropriate) STAB even if it is in the noSTAB list. (For example, Breloom has Mach Punch enforced, and this counts as Fighting STAB, so Close Combat is not required).
https://discord.com/channels/294651453279174656/1041098998624288990/1052446471615684689

Gen 9 Random Battles update

---

data/mods/gen8/factory-sets.json

Credentials: https://cdn.discordapp.com/attachments/1042959218208157696/1067534457160089731/image.png (i am "lost wind's elegy")
Darm-G's firepower is just fine with scarf; there aren't many (if any?) relevant 1hkos or 2hkos you miss out on compared to band. The only one I can think of is missing out on the OHKO vs Sp. Def Necrozma Dusk Mane, and nobody's leaving their NDM in anyway + you probably have like 12 other things to deal with it.
Without scarf, however, you miss out on really good source of offensive checking and revenge killing potential. Scarf outspeeds huge threats like non scarf Yveltal, Eternatus, Calyrex-Shadow, etc. 
What sparks had to say about band darm in proper SS Ubers: sparks — Today at 1:53 PM
not really but with band building needs to be more focused cos the speed …

Gen 8 Battle Factory: Remove Darmanitan-Galar's Choice Band set

---

data/mods/gen8/random-teams.ts
data/mods/gen8bdsp/formats-data.ts
data/mods/gen8bdsp/random-teams.ts

This makes the following changes to BDSP rands:
- Floatzel gets Water Veil as its ability if the team doesn't has rain
- Milotic always gets Rest and Sleep Talk
- Dugtrio gets Uber levelling
- Yanmega can roll Tinted Lens, not just Speed Boost
- Raticate and Ursaring can get Protect to activate their abilities
- Ursaring can get Quick Feet as its ability, and always has Quick Feet if it has Swords Dance
- Masquerain can get Sticky Web
- Heracross and Hariyama can get Stone Edge
- removes Stealth Rock from Wormadam-Trash since it is incompatible with Quiver Dance
- Pokemon with 3 Special attacks + U-Turn get Choice Specs/Scarf as their item
- Tauros gets Life Orb and Sheer Force to complement its moveset …

BDSP Random Battles updates

---

server/chat-plugins/randombattles/winrates.ts

In /rwr, Small errors in the html make the previous month/next month button not appear and break the sort-order button.

Winrates: Fix month buttons

---

sim/battle-actions.ts
sim/dex-formats.ts
sim/team-validator.ts
test/sim/misc/megaevolution.js

* Rayquaza's ability to Mega Evolve post-gen 7 now checks for "+Past" in the ruleset instead of "Standard NatDex". There are probably other cases of this hardcode that should be changed, but leave that for another PR.
* NatDex Draft is now able to Mega Evolve Rayquaza
* Banning Rayquaza-Mega no longer implicitly bans Rayquaza + Dragon Ascent; the new behavior is to add an implicit Mega Rayquaza Clause
* While this change is significant to many formats, tiering folk apparently prefer this if I understand correctly. If it becomes problematic in the future I am more than willing to make a Policy Review thread
* This fixes Rayquaza validity in National Dex Ubers

Fix ruleset interactions with Rayquaza-Mega

---

sim/battle.ts

Old behavior: Pursuit would proc on a mon using Revival Blessing, if that mon had any unfainted allies
New behavior: Pursuit will not proc on Revival Blessing
I believe this is sensible, as Revival Blessing is not actually a switch.

NatDex: Fix Revival Blessing + Pursuit interaction

---

data/learnsets.ts

The SV Fly Pikachu event was updated a couple days ago. Used to be male only and now can be female as well.
https://projectpokemon.org/home/files/file/4861-early-purchase-bonus-pikachu/

Update SV Fly Pikachu to allow both genders

---

data/moves.ts

One of the things from DarkFE's recent Commander mechanics post in the research thread. I am not sure how many other moves (Teleport, Chilly Reception, etc.) this applies to.

Prevent Commanded Dondozo from switching out through Baton Pass

---

server/sockets.ts
sim/battle-stream.ts
sim/battle.ts
test/server/sockets.js

Fixes an issue where privileged information via `split` is leaked to spectators. Only observed occurneces happen in gen 3 due to Pressure's mechanics being the only message that doesn't have shared information and the data-stripping regex not handling it well.
```
Moltres @ Leftovers  
Ability: Pressure  
EVs: 48 HP  
IVs: 0 Atk  
- Agility  
Claydol @ Choice Band  
Ability: Levitate  
EVs: 56 HP / 252 Spe  
- Protect  
- Facade
```
You need to separate clients. Two players and one spectator. When all clients are connected, one player should switch to Moltres and one should switch to Claydol.
Un-processed message before `ServerStream#extractChannel` is applied:
```
|
|t:|1673213422
|split|p2
|switch|p2a: Moltres|Moltres|333/333
|switch|p2a: Moltres|Moltres|100/100
|split|p2
|-ability|p2a: …
```

Update regex for extracting privileged messages

---

data/mods/gen4/random-teams.ts
data/mods/gen5/random-teams.ts
data/mods/gen6/random-teams.ts
data/mods/gen7/random-teams.ts
data/mods/gen8bdsp/formats-data.ts

Do not hotpatch until Sunday
Gen 4: Persian will get Return instead of Swift on sets without Nasty Plot.
Gen 5: 
- enforce Wood Hammer on Grass-types (Abomasnow and Torterra),
- non-choiced Palkia will get Lustrous Orb if it has Draco Meteor or Spacial Rend.
Gens 4, 6, 7: Improve Wish/Protect enforcement. Most Pokemon with Wish and Protect in their movepool won't get Protect without Wish, and Wish will generally appear more often on them.
Gen 6: Diancie-Mega will always get Moonblast, and Malamar will always get Superpower.
Gens 6-7: 
- Gyarados and Mega-Gyarados won't get Substitute unless they also have Dragon Dance,
- Normal-types with Fake Out and another Normal-type attack will get Silk Scarf.
BDSP: Change Jirachi's set
This shouldn't cause any merge conflicts with …

Gens 4-7 and BDSP Random Battles tweaks

---

data/mods/gen8/bss-factory-sets.json
data/mods/gen8/factory-sets.json

Some very minor IV/EV fixes in BSSF, mostly adding/removing Attack IVs for sets with(out) physical attacks.
Also fixes two wrong sets in BF, one of which is an illegal set with 100 to many EVs presumably made because of a silly error.
Changes mosly proposed by longhiep, briefly discussed by rands auth: https://discord.com/channels/294651453279174656/1018980144146292770/1075470786997014668

Gen8 BF/BSSF updates

---

server/chat-plugins/chatlog.ts

Since the command just parses input and then redirects to a page, no validation is needed here

Chatlog: Remove file check from /sl

---

data/random-teams.ts
test/random-battles/gen9.js

This allows more than one STAB move to be added if necessary. Most notably this makes Freeze Dry correctly forced on mons that have it and another Ice move.

Gen 9 Random Battle: Fix STAB enforcement

---

server/chat-plugins/scavengers.ts

Did this use a function.toString().includes call before?

Scavengers: Make /scav queue broadcastable

---

config/formats.ts

I would like to add a new online competition: "Paldea Prologue" to our format. The official tournament outline is as follows.
https://sv-news.pokemon.co.jp/en/page/39.html
This is the first revision I am implementing, so please point out any bad parts.

Add New Online Competition : Paldea Prologue

---

data/moves.ts
sim/dex-moves.ts
test/sim/moves/orderup.js

https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9525866
While this is not a perfect implementation as this makes the boost not occur if the user has Sheer Force even though in game the boost happens no matter what, it should be good enough for now as it's more important to not have the boost happen when missing/hitting into a protect.

Implement new Order Up mechanics

---

data/random-teams.ts

Fixes an issue that could cause random battles set generation to crash if `maxMoveCount` is lowered.

Gen 9 Random Battles: fix bug

---

data/mods/gen8/random-teams.ts
data/random-teams.ts

Currently when generating a team for hackmonscup with any sort of custom ban, all natures get banned. This is because of a weird typo(?) that has persisted for a long time and affects all gens. The code checked the same condition twice in a row: `if (!hasCustomBans)` and the `else` was misplaced.
With the introduction of brokencup in  #9427 the check for custom bans changed so that the default gen9HC now has custom bans (specifically, it bans `'Nonexistent'`), so natures were accidentally removed from default HC. The bug always existed but was never noticed before.

Hackmons Cup: Stop banning all natures when there are custom bans

---

CODEOWNERS

That _one_ line being out of alphabetical order irked me

Codeowners: Fix alphabetical order in chat-plugins

---

config/formats.ts

Also updates [thread link](https://www.smogon.com/forums/threads/dpp-doubles-ou.3717286/post-9528605). Doubles OU tier leaders have signed off on the changes.
- Removes Sleep Clause (and bans Dark Void)
- Removes Sand Veil / Snow Cloak bans
- Removes Arena Trap ban
- Removes Baton Pass ban
- Removes Explosion ban

DPP DOU: Update ruleset

---

config/formats.ts

This if statement would always be true because the actual rule corresponding to isNonstandard properties has a `pokemontag:` prefix
e.g. +CAP is read as +pokemontag:cap

Mix and Mega: Fix custom validation

---

data/rulesets.ts

Currently Rayquaza cannot Terastal while knowing Dragon Ascent in National Dex Ubers, even though it cannot Mega Evolve thanks to Mega Rayquaza Clause. 
Because Terastal is handled through a field rather than a method, MRC's failure to update it caused inconsistent behavior. This resolves the inconsistency with gen 8 implementation behavior (Rayquaza was able to dynamax under MRC); as such, Rayquaza should be able to use Terastal when using Dragon Ascent under MRC.
This resolves https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9441141

National Dex Ubers: Fix Dragon Ascent preventing Rayquaza from using Terastal

---

sim/team-validator.ts
test/sim/team-validator/misc.js

Previous logic caused Necturna to learn Shell Smash in previous gens without restriction because sources had a value, and thus any moves Necturna learned in future generations also passed the validator as "naturally learned" in previous generations. This seems to fix it but unsure if there is a better way.

Validator: Identify moves learned only in a later gen as sketched in previous gens

---

data/abilities.ts
data/conditions.ts
data/text/abilities.ts

This took way longer than it should have
Karthik has corresponding client change. Commander's annoying because it prints Dondozo's name twice.

Add Commander activation text

---

data/mods/gen1/scripts.ts

If a Pokemon has a stat of 1 and it is the target of a stat drop, the stat should not be recalculated.

Gen 1: Fix stat dropping at 1

---

data/mods/mixandmega/scripts.ts

The crash was because when an ability such as Protosynthesis, Quark Drive, or Slow Start ends, the pokemon tries to delete a volatile, showing a client error in the process (probably because the pokemon wasn't out?)

Mix and Mega: Fix error message

---

server/chat-plugins/uno.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8882521
In addition to the bug report, I noticed that the description for /uno cards seems to be missing a word, and also a period (all the other Uno command descriptions end with a period) so I updated that too.

Allow Uno player to see hand and color selection

---

data/random-sets.json
data/random-teams.ts

-Remove Moody from the format, effective April 1. Glalie will be a bad Spikes set at level 97, and Scovillain will be either subseed or Choice item at random at level 90.
-Balance the levels of Zoroark and Hisuian Zoroark further by adding a maximum level for the sixth slot when a Zoroark is generated. In addition, level balance the Zoroarks separately from each other.
This is part 1 of this week's update - part 2 will consist of monthly level balancing and will be done by Chains of Markov.

Gen 9 Randbats: Council Decisions

---

server/chat-commands/info.ts

When a link to the login server source code was added to `/git`, a linebreak was forgotten

/git: Add newline between Dex and Login server links

---

config/formats.ts

Pokebilities is missing the minsourcegen; also updating link from gen8 to gen9

Pokebilities: Add Source Gen and update link

---

data/random-teams.ts

This fixes a bug that could cause a different Pokemon to be given the level of the last Pokemon in the team, rather than the Zoroark.
passes tests locally

Gen 9 Random Battle: fix Zoroark level bug

---

data/mods/gen1/random-data.json
data/mods/gen1/random-teams.ts

Now that Gen 1 Random Battles is collecting winrates (https://github.com/smogon/pokemon-showdown/commit/3c8a1135d0953b87338bb0740237b84ef94d7139), this prepares for level balancing by listing all levels in `random-data.json`. 
This has no effect on functionality. It does ensure that levels will no longer change with tier shifts, which is helpful for accurate winrate collection.

Gen 1 Random Battles: prepare for level balancing

---

data/mods/gen8/random-teams.ts

Fixes a bug which prevented battle-only formes from generating in pre-gen 9 Monotype Random Battles, even if both formes have the required type. Most notably, Megas couldn't generate in gens 6-7.

Fix battle only formes in Old Gens Monotype Random Battles

---

data/mods/gen1/rulesets.ts
data/mods/gen1jpn/rulesets.ts
data/mods/gen1stadium/rulesets.ts
data/mods/gen2/rulesets.ts
data/mods/gen2stadium2/rulesets.ts

I don't know if there is a reason for the Nickname Clause not being active in these generations. Although it is not compulsory, its implementation simplifies development by enabling a straightforward selection of a Pokémon by its nickname.

Gen 1 and Gen 2: Nickname Clause

---

.github/workflows/publish.yml

As requested by @Zarel over Discord I've opened a PR to add a check for the token
[Secrets cannot be referenced directly inside if conditionals](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow:~:text=Secrets%20cannot%20be%20directly%20referenced%20in%20if%3A%20conditionals.), so I had to create a job output

Github Actions: Add conditional check to fix fork publishes

---

sim/pokemon.ts

This fixes a bug in gens 1-4. If Pokemon 1 Transformed into another Pokemon with different IVs, switches out, and switches back in, it would incorrectly calculate its stats based on the second Pokemon's IVs, rather than its own IVs.
The intention of copying IVs is for Hidden Power typing and power, but those are copied separately already.
This fixes the issue raised here: https://github.com/smogon/pokemon-showdown/issues/9531

Gens 1-4: fix bug where Transform users' stats get permanently altered

---

data/items.ts
test/sim/abilities/myceliummight.js

Quick claw can no longer boost status moves that had lower priority because of mycelium might.
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-108#post-9509334
Added some tests too with a fixed seed

Fix Mycelium Might and Quick Claw interaction

---

server/chat-commands/info.ts

At first, `user.can('showmedia', null, room, '/show')` return the user has a rank which voice or higher. if `!show` disallowed for some rank and the rank was voice and higher, they could not use  both of `!show` and `/requestshow`.
By using `Chat.checkCan('show', null, room)`, we could solve this problem. if the user could not use `!show`, they could use `/requestshow`.
If the comment starts/ends with spaces, the comment was caught by `Chat.checkChat()`. Solved this by triming spaces.

`/requestshow`: Fix comments

---

.github/workflows/test.yml
package.json

A few potential optimizations to the Github Actions job that could be worth trying out, if desired
1. Use [actions/cache@v3](https://github.com/actions/cache) to create a Github-hosted, immutable cache entry that stores a specified directory (in this case, `node_modules`). A new entry is created whenever `package-lock.json` is updated or a new `node-version` is specified in the action itself. Old entries are auto-evicted from the cache after a few days of inactivity or due to lack of space. Similar to what is done [here](https://github.com/prettier/eslint-config-prettier/blob/main/.github/workflows/check.yml), saves about a minute in the `npm install` step once cached
2. Use [tj-actions/changed-files@v35](https://github.com/tj-actions/changed-files) to fetch all changed/modified js, ts & …

Github Actions: Perform selective eslint & testing for PRs

---

server/chat-commands/info.ts

`[link, comment]` ignores latter comments splited by comma if the comment includes. Use `[link, ...comments]` to allow it.
Also fix #9541, comment should be trimed and stored to variable, not just checking

/requestshow: Allow using comma in comments

---

data/mods/gen8/random-teams.ts
data/random-teams.ts

This implements a Random Battles Development Council decision to remove tier limits from formats that are sufficiently level balanced.
For now, this means removing them from Gen 8 Random Battles, and not applying them to Gen 9 Random Battles.
Approved by Random Battles staff, ready to be merged

Gen 8/9 Random Battle: Remove tier limits

---

server/chat-commands/room-settings.ts
server/rooms.ts

Allow changing the title of a room thru /renameroom if it would not change the room ID (e.g. testroom -> Test Room)
Also fixes a bug where "g" gets added to the room ID with /renamegroupchat

Rooms: Support changing case/spaces of room title

---

server/ladders-local.ts

Caused by #4516 where the behavior of skipping the first line of the tsv ladder file was accidentally removed.

Fix local ladders inputing bad entries on load

---

data/mods/gen1/random-data.json
data/mods/gen3/random-data.json
data/mods/gen4/random-data.json
data/mods/gen5/random-data.json
data/mods/gen6/random-data.json
data/mods/gen7/random-data.json
data/random-sets.json
data/random-teams.ts

Winrate-based level balancing for this month, documented in a smogpost [here](https://www.smogon.com/forums/threads/random-battles-level-balancing.3721211/).
For the first time this month, Gen 1 is included.
As always, preferably merge this close to the month rollover so that June's stats are based on these new levels. Thank you!

Random Battles: Level balancing 2023-05

---

config/formats.ts

The move is not supposed to be allowed at all, and despite being banned it was still validating in the Item slot.

Fortemons: Restrict Last Respects

---

config/formats.ts

To go live June 15th 11:59:59 pm. See https://www.smogon.com/forums/threads/1000-ladder-tour-freedom-cup-playing-competitive-pokemon-how-the-pokemon-company-intended.3722982/
The only thing left for the format is debating where we want it to live. Currently, it's in Pet Mods, but doesn't mod any actual game mechanics. SV Singles or Other Metagames would be the other candidates.

Add Freedom Cup

---

data/random-doubles-sets.json
data/random-sets.json
data/random-teams.ts

**Gen 9 Random Battle:**
-Oranguru: -Trick Room, +Nasty Plot
-Luvdisc: +Icy Wind; Luvdisc will only roll one of Icy Wind/Charm/Ice Beam at a time.
-Fast Support Garchomp: -Draco Meteor, +Outrage; Outrage will get a Rocky Helmet in this situation.
-Setup Sweeper Charizard: -Thunder Punch, -Tera Fire, +Outrage, +Tera Dragon
-Swords Dance Iron Hands: +Thunder Punch
-Calyrex-Shadow: +Tera Dark
-Blissey: -Shadow Ball, +Stealth Rock (it was worth a shot)
-Blissey and Chansey will now always have Thunder Wave. Code has been cleaned up involving Blissey, as well.
-Basculins will now always have Aqua Jet.
-Tera Blast Inteleon and Floatzel were removed.
-Floatzel still has a Bulk Up set, which now runs Wave Crash, Low Kick, and Crunch over Liquidation and Tera Blast, with Leftovers and Tera …

Gen 9 randomized format set updates

---

server/chat-plugins/chatlog.ts

/searchlogs is now only accesible by admins, so I'm updating the docs.

Update /help searchlogs

---

sim/pokemon.ts
sim/tools/exhaustive-runner.ts

Currently, exhaustive runner looks at the species as defined by details information provided in pokemon.ts#getSwitchRequestData. However, Greninja-Bond (and any later edits to Zygarde or Rockruff) can't send its form in details, because it's visually indistinguishable from regular Greninja. There are a few solutions to this:
- Hardcode exceptions to skip over Greninja-Bond, etc.
- Add species name to pokemon.ts#getSwitchRequestData
This approach goes with the latter. I assume you would always know your own species at all times. Maybe there's an argument that you wouldn't always know your ally's species in a Multi Battle, but 1) we don't support multi battle hackmons where you could even theoretically bring a regular Greninja with Battle Bond, 2) I think it's a reasonable assumption that …

Fix Greninja-Bond with exhaustive runner

---

data/mods/gen1/moves.ts

I was digging into the decomp and discovered this absolutely *meta shaking* oversight for Gen 1.
There is a known bug which causes Rest, Recover, etc. to fail to heal when the user's current HP is exactly 255 or 511 less than its max HP. Smogon accounts for this and checks for that condition for the Gen 1 moves Rest, Recover, and Softboiled, and shows a nice warning.
I was trying to understand the reason for this being 255 and not 256, so I dug into the assembly and figured it out (StackOverflow investigation [here](https://stackoverflow.com/questions/69195926/trying-to-figure-out-why-a-certain-pokemon-red-blue-glitch-occurs-why-do-the-pr/76470195#76470195)). The how isn't important here, though. The important thing is that the subtraction will NOT produce an erroneous "failed" result if …

Gen 1: Recovery moves *do* work in some cases when HP is 255 below Max HP

---

server/tournaments/generator-round-robin.ts
server/tournaments/index.ts

This PR has 2 changes:
・ Hide toolbox when eliminated players reconnected
・ Hide toolbox if the player have ended all battles in Round Robin

Tournaments: Hide toolbox for players who has ended all battle

---

data/mods/gen2/random-data.json
data/mods/gen2/random-teams.ts

Thanks MrSoup for your suggestions! This is ready to merge.
-Make Spikes forced, unless the team already has it
-Magneton: Rest / Sleep Talk / Thunderbolt / HP Ice
-Hypno: -Reflect, -Light Screen, -Hypnosis, +Rest, +Sleep Talk, +Toxic 
-Ninetales: -Confuse Ray, -Hypnosis, -Sunny Day, +Rest, +Sleep Talk, +Toxic 
-Slowtwins: -Toxic, -Fire Blast, +Flamethrower, +Ice Beam
-Heracross: -Seismic Toss
-Stantler: -Confuse Ray
-Suicune: -HP Electric
-Dewgong: -Body Slam
-Lapras: -Sing -Thunder
-Quagsire: -Body Slam, +HP Rock, +Sleep Talk, Belly Drum incompatible with Sleep Talk
-Piloswine: -Body Slam
-Rhydon: -Zap Cannon, -Fire Blast
-Jumpluff: -HP Ice, -HP Water, +Encore, +HP Flying 
-Flareon: -Zap Cannon
-Togetic: Rest / Sleep Talk / Curse / Double-Edge
-Aerodactyl: -Reflect, +Rest
-Bellossom: …

Gen 2 Random Battles updates

---

data/mods/gen1/random-data.json
data/mods/gen3/random-data.json
data/mods/gen4/random-data.json
data/mods/gen5/random-data.json
data/mods/gen6/random-data.json
data/mods/gen7/random-data.json
data/random-sets.json
server/chat-plugins/randombattles/winrates.ts

Monthly balance patch for Random Battles, ideally merged before the month rolls over but I understand that may be difficult with how late I am.
Includes harmonization of Greninja formes for gathering purposes, which is needed for gen7.
Also harmonizes Keldeo(-Resolute) and Zarude(-Dada), which are new with the gathering of gen8 data.
Lowers Elo threshold for randdubs winrates because the ladder is still very low right now and we'd prefer to start balancing ASAP.

Random Battles: June 2023 level balancing

---

data/mods/gen1/scripts.ts

My previous patch https://github.com/smogon/pokemon-showdown/pull/9054 inadvertently caused Inverse Mod to no longer work in Generation 1. This PR will fix that.

Gen 1: Fix Inverse Mod

---

config/formats.ts

This ensures that Sleep Clause is always active in Random Roulette. 
There are some other issues with the format, but this is the most pressing currently.

Randomized Format Spotlight: fix Sleep Clause

---

config/formats.ts
data/mods/randomroulette/scripts.ts

This fixes some bugs with Random Roulette:
- Sleep and Freeze Clauses will now be applied depending on the format (specifically, Gen 1 and 2 Random Battles will now have Freeze Clause, and all formats have Sleep Clause). This replaces the emergency measure yesterday which blanket applied Sleep Clause but did not fix Freeze Clause https://github.com/smogon/pokemon-showdown/pull/9628.
- Gen 1 had some visual bugs where boosts did not appear on the Pokemon, this should fix them.
(This is ready to merge)

Randomized Format Spotlight: fix clauses and visual bugs

---

server/chat-plugins/helptickets.ts

Add ```/ticketban``` and ```/unticketban``` as an alias of``` /helpticket ban``` and ```/helpticket unban``` respectively.   
This was [suggested by Kennedy around a month ago](https://www.smogon.com/forums/threads/staff-suggestions-bugs.3514540/post-9649827) and it seemed like a fairly popular one since a number of staff members have mentioned that they have used ```/ticketban``` in place of ```/helpticket``` ban before. It would be convenient to have these aliases.

Helptickets: Add /ticketban and /unticketban

---

data/mods/gen5/random-data.json

Set updates:
-Venomoth: -Substitute (ensures Quiver Dance)
-Sableye: -Night Shade, +Seismic Toss
-Illumise: -Substitute
-Luvdisc: -Surf, +Scald
-Gliscor: -Ice Fang, +Facade
-Giratina: -Dragon Tail
-Liepard: -HP Fire, +HP Fighting
-Cryogonal: -HP Fire, +HP Ground

Gen 5 Random Battles updates

---

data/mods/gen3/random-teams.ts
data/mods/gen4/random-teams.ts
data/mods/gen5/random-teams.ts
data/mods/gen6/random-teams.ts
data/mods/gen7/random-teams.ts
data/mods/gen8/random-teams.ts
data/mods/gen8bdsp/random-teams.ts
data/random-teams.ts

This update improves and fixes some bugs with ability generation in Random Battles:
- In Gen 9, abilities rated 0 can no longer be randomly selected over abilities rated 0.5. This currently has no effect on functionality; it is for future-proofing and code accuracy.
- In Gens 3-8, this fixes a bug where higher rated abilities are sometimes generated less commonly than lower rated abilities. Now, higher rated abilities will be preferred by default. 
- In Gens 3-8, ability generation has been refactored into a `getAbility()` function to improve code readability. Some unnecessary ability rejections have been removed. This has no effect on functionality.
The update also makes some minor ability adjustments, outlined below:
- In Gens 3-4, Ludicolo will get Swift Swim rather than Rain Dish on …

Random Battles: Improve ability generation

---

data/mods/gen2/scripts.ts
data/mods/gen2stadium2/scripts.ts
data/mods/gen3/scripts.ts
data/mods/gen4/moves.ts
data/mods/gen5/moves.ts
data/mods/ssb/scripts.ts
data/moves.ts
sim/battle-actions.ts
sim/global-types.ts
test/sim/moves/chloroblast.js

And by properly I mean the dumb way GF implemented this.
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9699207
https://twitter.com/zakocky/status/1663886466525827072

Properly implement Chloroblast recoil

---

data/mods/gen5/random-teams.ts
data/mods/gen7/random-teams.ts
data/mods/gen8/random-teams.ts
data/random-teams.ts

In Gens 4-5, this fully removes the type combination limit for Monotype Random Battles, since some types have very few possible type combinations. This should fix the infrequent crash that can occur while generating teams.
In Gens 6-9, the type combination limit has been increased from 2 to 3. The previous limit of 2 was too restrictive and could lead to problems with team generation.

Monotype Random Battles: adjust type combination limit

---

tools/set-import/importer.ts

All CAP mons have a gen property in pokedex,ts, so we should use that.
The ranges were inaccurate, certainly because of a typo (-8 instead of -18 on line 157) but also otherwise. I think the reason is that the numbering for CAP changed at some point, though I can find no evidence in the history.
Anyway, hopefully this resolves it.

Set Importer: Fix CAP Pokemon gens

---

data/mods/gen1/random-data.json
data/mods/gen3/random-data.json
data/mods/gen4/random-data.json
data/mods/gen5/random-data.json
data/mods/gen6/random-data.json
data/mods/gen7/random-data.json
data/mods/gen8/random-data.json
data/random-sets.json

Monthly level balancing. For the first time includes Gen 8. Doubles is also generally included but will be in another merge request together with a general patch to avoid merge conflicts.
If possible, please merge and patch soonish to the month rollover.
Thank you :)

Random Battles: July 2023 level balancing

---

data/random-doubles-sets.json
data/random-teams.ts

This update contains the first Gen 9 Random Doubles level balancing patch, based on the winrates visible in "/rwr gen9randomdoublesbattle". As a result, please have this merged and patched before the rollover of the month, if possible.
This update also contains the following changes:
-Hisuian Qwilfish is being added at level 86. It will have Crunch, Gunk Shot, Icy Wind, and Toxic Spikes, with Tera Flying. (council decision)
-Spiritomb has gained a set split:
--The pre-existing set but minus Trick Room and Snarl
--Doubles Bulky Attacker, with Foul Play, Trick Room, Snarl, and Will-O-Wisp.
-Altaria has gained a set split:
--The pre-existing set but minus Protect
--Bulky Protect, with Brave Bird, Roost, Protect, and Will-O-Wisp.
-Choice Scarf Gothitelle (and therefore Hypnosis Gothitelle) …

Gen 9 Random Doubles Battle updates

---

data/moves.ts
sim/battle-actions.ts

The sequel to #9387 
As seen here: https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-31#post-9538928
This also fixes the slight mechanics error regarding Baton Pass used to implement the previous Baton Pass with Commander failure.

Prevent Commanded Dondozo from switching out through pivot moves

---

data/abilities.ts
sim/pokemon.ts

No longer allows Imposter/Skill Swap to infinitely get Intrepid Sword/Dauntless Shield boosts.

Improve tracking Intrepid Sword and Dauntless Shield boosts

---

server/chat-plugins/datasearch.ts

This allows to run ``/ms sheer force``, same as how magic bounce works

Movesearch: Remove empty spaces from 'sheer force' before validating

---

data/random-sets.json
data/random-teams.ts

Please merge this swiftly so the Gen 7 revamp can fix the one conflict this'll make.
-Espeon's Tera Blast user set was removed due to it underperforming in winrates.
-Cryogonal is gaining a Tera Blast user set. It will be Heavy-Duty Boots with Rapid Spin, Tera Blast Electric, Ice Beam, and Recover.
-Houndoom can get Sucker Punch + Nasty Plot again because the set's removal caused Houndoom's winrate to drop.
-Chesnaught: -Spiky Shield
-Wo-chien: -Energy Ball, +Giga Drain
-Scovillain: -Giga Drain, +Energy Ball
-Sudowoodo: -Spikes
-Cryogonal set 1: +Tera Poison
-Curse Garganacl: +Earthquake, -Tera Fighting
-Protect and Support Garganacl: +Tera Dragon

Gen 9 Random Battle updates

---

data/rulesets.ts
sim/team-validator.ts

Automatically including !obtainable abilities seems to be a source of the errors, but also Nickname Clause doesn't turn "off" when removed in a part of the hardcode, allowing nickname clause to be removed fixes that issue about nicknaming pokemon in ruleset mods

Frantic Fusions: Fix validation errors

---

sim/team-validator.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9727878 This was happening as a result of move sources being generated for all formats rather than only ones that check for move legality.
In addition, I noticed that my implementation allowed Gen 6+ legendaries to get away with illegal moves if their only Pokemon GO identifier was having less than three perfect IVs; now the code should be performing legality checks only after all identifiers are checked.

Fix Go legality in formats without obtainablemoves

---

config/formats.ts
sim/team-validator.ts
test/sim/team-validator/breeding.js

https://www.smogon.com/forums/threads/past-gens-research-thread.3506992/page-11#post-9688927
Handles various situations where low level female only Pokemon have access to level up egg moves they shouldn't have access to. I tested all legality problems mentioned in the post, and everything that should be illegal is properly identified as such.
This makes the Tinkatink complex ban in LC obsolete, but I would prefer to have the permission of TLs to remove the ban rather than simply doing it myself.

Fix low level egg move legality

---

data/mods/gen1/random-teams.ts
data/mods/gen3/random-teams.ts
data/mods/gen5/random-teams.ts
data/mods/gen6/random-data.json
data/mods/gen7/random-doubles-teams.ts
data/mods/gen7/random-teams.ts
data/mods/gen8/random-teams.ts

This implements, for past gens, a Random Battles development council decision to unify and adjust the appearance rate of species with multiple formes. Gen 9's adjustment will be implemented in its own PR, along with other changes to Gen 9 Random Battles. A description of the decision is presented below.
Across all gens, adjust forme appearance rate to the following:
18 formes => 1/6 appearance rate per forme (3x conglomerate appearance rate)
6 formes => 1/3 (2x)
4 formes => 1/2 (2x)
3 formes => 1/3 (1x)
2 formes => 1/2 (1x)
This will unify appearance rate code across all gens (currently not in place), make extremely limited formes like Tauros, Arceus, Silvally, and Rotom appear at an actually appreciable rate instead of being once-in-a-blue-moon easter egg, and gives better stats for …

Past Gens Random Battles: Fix appearance rate of Pokemon with multiple formes

---

server/chat-plugins/othermetas.ts

The arg parsing ended up a bit weird after #9700, this is simpler and doesn't break on `/fuse pokemon, gen`
Current version
Fix

`/fuse`: Fix argument parsing

---

.github/workflows/test.yml
data/learnsets.ts

We're currently getting this warning when changing lint-excluded files, because we were explicitly marking that file to be linted. This fix is working locally with [act](https://github.com/nektos/act), hopefully also works on the real CI too
```
/home/runner/work/pokemon-showdown/pokemon-showdown/data/learnsets.ts
0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override
```
The files specified on the CI workflow come from `.eslintrc.json`

Don't try to lint excluded files

---

config/formats.ts

After much trial and error, I want to say it's because of the method not passing the arguments correctly, causing move to be undefined.

Fortemons: Fix crash

---

config/formats.ts

Tornadus-T is incorrectly banned in 2v2 Doubles:
https://www.smogon.com/forums/threads/2v2-doubles.3710849/

2v2 Doubles: Unban Tornadus-T

---

data/rulesets.ts

This is to avoid confusion when someone uses an alias, like smogonbird to access to Talonflame.

Frantic Fusions Mod: Replace alias with species name

---

sim/pokemon.ts
test/sim/items/abilityshield.js

Research post: https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9635572
Bug report: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9720115
For now this probably breaks the ng glitch mentioned in both posts, but I could look into fixing that too

Fix Ability Shield interaction w/ Transform

---

sim/battle.ts

Was caused by the `skipBeforeSwitchOutEventFlag` never being reset for fainted Pokemon. It shouldn't be set in the first place.
Bug report: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9751247
Inputs I used for testing:
```
>start {"formatid":"gen9customgame","seed":[58110,65317,35427,37487]}
>player p1 {"name":"Mathy","avatar":"#psstaffm","team":"Pawmot|||VoltAbsorb|RevivalBlessing,SleepTalk||1,,,,,||,0,,,,|||,,,,,Electric]Gholdengo|||GoodasGold|Memento,SleepTalk||1,,,,,||,0,,,,|||,,,,,Steel","rating":0}
>player p2 {"name":"Furret","avatar":"101","team":"Zigzagoon|||Pickup|Pursuit,SleepTalk||1,,,,,|||||,,,,,Normal","rating":0}
>p1 team 2, 1
>p2 team 1
>p1 move memento
>p2 move sleeptalk
>p1 switch 2
>p1 move revivalblessing
>p2 move …
```

Fix Pursuit not triggering on revived Pokemon

---

config/formats.ts

Currently it has the wrong sleep clause https://www.smogon.com/forums/threads/frantic-fusions-omotm-ladder-live-unbans-post-73.3725593/

Frantic Fusions: Sleep Moves Clause

---

config/formats.ts

This re-adds Random Roulette as a challenge format as mentioned here: https://github.com/smogon/pokemon-showdown/pull/9739#pullrequestreview-1606184042.
I kept it in the same section (Randomized Format Spotlight). If you'd prefer it somewhere else, or for the format to not show while challenging, I'd be fine with that.

Keep Random Roulette as a challenge only format

---

config/formats.ts

Because apparently, everyone is chat believes this is like pokebilities.

Frantic Fusions: Change description

---

sim/team-validator.ts

(only if the pokemon is named after another mon obviously)

Frantic Fusions: Don't hide nicknames when locked

---

data/mods/gen6/random-sets.json
data/mods/gen6/random-teams.ts
data/mods/gen7/random-sets.json
data/mods/gen7/random-teams.ts

All instances of "PT" refer to the "preferred type" system; a Pokemon with a preferred type will always generate with a move of that type. It will be referred to by the aforementioned "PT" shorthand in the rest of this pull request.
These changes are largely to align Gen 7's set optimization with that of the newly-revamped Gen 6 Random Battle when reasonable. After this update, the only differences between generations 6 and 7 of Random Battle will involve actual generational mechanic, movepool, and stat changes.
**Role additions/changes/removals:**
-Steelix now has three sets: 
--Wallbreaker, which is the Sheer Force Life Orb set unchanged
--Staller, which is Sturdy Leftovers with Earthquake, Heavy Slam, Toxic, and Protect
--Bulky Support, which is Sturdy Leftovers with Earthquake and any …

Gen 6+7 Random Battle updates

---

data/moves.ts
sim/pokemon.ts
sim/side.ts
test/sim/moves/pollenpuff.js

Currently, Pollen Puff and Heal Block don't always interact correctly. Here's what it should do:
If the _user_ has Heal Block:
At move selection: cannot target ally with Pollen Puff
At move execution: "[POKEMON] can't use Pollen Puff because of Heal Block!", timing failure is around that of Primal weather causing Fire/Water moves to fail
If the _target_ has Heal Block:
At move selection: no restriction
At move execution: "[POKEMON] was prevented from healing due to Heal Block!", timing failure is after the full HP check
Right now, we don't support the generic "[POKEMON] was prevented from healing due to Heal Block!" message at all, and implementation looks difficult, so I may forgo that for now and save it for a future PR. It's relevant for things like Heal Pulse, Grassy Terrain recovery, …

Fix interaction of Pollen Puff and Heal Block

---

data/mods/gen8/random-teams.ts

Implements proper weighted sampling to prevent infinite loops. Now, forcing a monotype rock team will instead of crashing provide a team, albeit possibly with fewer than 6 mons.
Removes weakness constraints on team generation under monotype rules as they are essentially impossible, forcing generation to always go to the maximum depth.
Finally, removes some unused code relating to required moves (which was an empty list of moves).

Gen 8 BSS Factory: Implement proper sampling

---

data/moves.ts

There are 7 moves in Pokemon that sacrifice the user.
Each one has a `selfdestruct` property that is either `always` or `ifHit` except Final Gambit.
Final Gambit does not need the `selfdestruct` property to work, but with it, it is much more consistent to check if a move sacrifices its user.
If you want to know if a random move sacrifices its user you have to use
```javascript
if(move.selfdestruct == "always" || (move.selfdestruct == "ifHit" || move.name == "finalgambit") && move.hit))
```
Forgetting to implement an extra check for Final Gambit is easy.  
---
Giving Final Gambit the `selfdestruct` property solves this problem
```javascript
if(move.selfdestruct == "always" || move.selfdestruct == "ifHit" && move.hit)
```

Add selfdestruct property to Final Gambit

---

data/mods/gen8/random-teams.ts

The softcap on 2 mon of the same type was active for monotype, as well as the hard cap of 1 mon with a particular type combo. That's probably not a good idea. With this fix at least monorock can usually find 6 mons. Monobug cannot, as I think there's only 5 sets in total. 
BSSF team generation also allows for a custom teamsize, and this implements a scaling limit roughly the same as in Random Battles.

Gen 8 BSS Factory: Remove type limits in monotype

---

data/abilities.ts
data/mods/gen7pokebilities/abilities.ts
data/mods/pokebilities/abilities.ts
test/sim/abilities/poisontouch.js

Previously, Poison Touch was being treated as adding a secondary effect; it does not actually do that. If the target has Substitute or is protected by Covert Cloak / Shield Dust, it won't trigger which is similar, but it is not doubled by Pledge Rainbow.
This changes behavior in some mods that allowed multiple Abilities (?), but if you had both Sheer Force and Poison Touch somehow, Poison Touch would still activate.

Fix Poison Touch's interaction with Pledge Rainbow

---

data/mods/gen2/random-data.json
data/mods/gen2/random-teams.ts
data/mods/gen3/random-data.json
data/mods/gen3/random-teams.ts
data/mods/gen4/random-data.json
data/mods/gen4/random-teams.ts
data/mods/gen8/abilities.ts
data/mods/gen8/random-data.json

Gen 2:
-Enforce Psychic on Jynx
-Noctowl -Reflect
-Forretress -Reflect
-Raikou -Reflect
-Pidgeot -Reflect
-Electrode -Light Screen, -Reflect
-Ampharos -Light Screen, -Reflect
-Dragonite -Ice Beam, -Reflect, -Light Screen, +Surf
-Vaporeon Surf / ResTalk / Growth
-Politoed Surf / ResTalk / Growth
-Crobat -Whirlwind, +Toxic
-Meganium Body Slam / Synthesis / Swords Dance / Earthquake
Gen 3:
-Castform: +return
-Fix Girafarig being able to generate without Psychic
-Dustox: -lightscreen
-Ninjask: -hiddenpowerrock
-Gyarados: -taunt
-Rayquaza: -overheat
-Seviper: -doubleedge
-Noctowl: +hiddenpowerfire
-Murkrow: -meanlook, -perishsong, -protect
Gen 4:
-Hippowdon: -icefang
-Dusknoir: -icebeam, +icepunch
-Bronzong and Steelix: -gyroball, +ironhead
-Wormadam-Trash: -gyroball, +flashcannon
-Prevent …

Gen 2-4 and Gen 8 Random Battles updates

---

data/random-sets.json
data/random-teams.ts

This is untested. Please do not merge without reviewing.
Changes are too numerous to list in a timely manner, but I will do so as quickly as possible.
**Technical:**
-Gen 9 Pokemon were reordered into dex order, aside from a couple stragglers here and there. They were not even remotely in dex order before and it bothered me.
-Luvdisc hardcode removed due to no longer being necessary.
-Persian Bite incompatibility rmeoved due to no longer being necessary.
-Ivy Cudgel is recognized as the type it is.
**Generation rules:**
-Poison Heal grants a Toxic Orb.
-Reckless will generate with HJK on mienshao and Regenerator will generate otherwise
-Unaware will only generate on 50% of Bulky support clefables
-Flip turn and Aqua Jet will not generate together, unless you're Basculin
-Wallbreaker role …

Gen 9 Random Battle Teal Mask update

---

data/formats-data.ts

This was mistakenly changed in the DLC update from what I can see, it should be in NDRU according to their council + usage update.
https://www.smogon.com/forums/threads/usage-based-tier-update-for-september-2023.3727155/

National Dex: Move Politoed to RU

---

data/random-sets.json
data/random-teams.ts

-Galvanize and Magnet Pull are now split by set on Golem-Alola.
-Illumise will always get Prankster.
-Jirachi can now get Healing Wish and U-turn together, and will no longer get Life Orb since it is now Bulky Support.
-Ninetales will always get Drought.
-Politoed will always get Drizzle.
-Weezing-Galar will no longer get Misty Surge, and hence always get Levitate.
-Setup Revavroom is now Fast Attacker, so that it gets Life Orb.
-Uxie is now Bulky Support, to prevent Life Orb.
-Gurdurr will now get Eviolite, not Flame Orb
-Ogerpon-Wellspring's non-support set is now Setup Sweeper, to enforce Swords Dance.
-Empoleon will always be Competitive
-Infernape's mixed Wallbreaker set is now Fast Attacker so that Mach Punch is not enforced; the physical set's role is now Fast Support, which is …

Gen 9 Random Battles fixes

---

config/formats.ts

They didn't ban Bloodmoon, but is not being allowed because base Ursaluna was banned before DLC.

Frantic Fusions and STABmons: Unban Ursaluna-Bloodmoon

---

data/random-sets.json
data/random-teams.ts

These will slow down soon. Sorry for the update flood.
-Arbok now always has Intimidate and doesn't get Shed Skin. Whoops!
-Third Sandaconda set: Fast Bulky Setup with Loaded Dice Scale Shot + Rock Blast and Tera Dragon.
-Dipplin: -Leaf Storm
-Politoed: -Focus Blast, +Haze; Politoed now always gets Ice Beam
-Weezing and Galarian Weezing: -Sludge Bomb, +Gunk Shot (they have higher Attack)

Gen 9 Random Battles updates

---

data/mods/gen4/random-data.json

This reverts a change that was unintentionally included in the previous update https://github.com/smogon/pokemon-showdown/pull/9758 and resulted in some issues with set generation.

Gen 4 Random Battles hotfix

---

server/chat-plugins/chatlog.ts

Currently, `Total lines: {total}` shows up with the {total} template still remaining when viewing linecounts of a specific user, with a separate `Total linecount: X` actually displaying the total. This change will now use the bolded text at the top to display the total to be uniform with the other total line display, and also gets rid of an extra iteration that was previously used to get the total lines for a user.

Linecount: Fix displaying total lines for user pages

---

data/rulesets.ts
server/chat-commands/core.ts
server/global-types.ts
server/room-battle.ts
server/room-game.ts
server/rooms.ts
server/tournaments/index.ts

Very rough inspiration from Zarel's original implementation [here](https://github.com/smogon/pokemon-showdown/pull/4076).
Thanks to DaWoblefet for the in-depth design spec and extensive help testing!
This implements best of three as a challengeable value rule, so it can be applied to any single or doubles format. 
Some notes:
- Minimum of 3 battles, maximum of 9. User can specify it in challenge.
- After each battle ends, a timer starts, waiting on both users to acknowledge that they want the next battle to start. Battle starts after 60 seconds regardless, but clicking the buttons will speed it up.
- A main room is used to control and keep track of the parent games. This was pretty much non-negotiable, unfortunately, every other approach would have been hacky. 
- This is supported on …

Implement Bo3

---

data/mods/gen6/random-sets.json
data/mods/gen6/random-teams.ts
data/mods/gen7/random-sets.json
data/random-doubles-sets.json
data/random-sets.json
data/random-teams.ts

Gen 9 Random Battle:
-Gothitelle now has a set split: one Bulky Setup Calm Mind set, and one Choice Scarf Trick Fast Attacker set. Newly, both have Focus Blast.
-Tinted Lens Yanmega now actually gets Choice Specs.
-Choice Scarf Dragon Energy Regidrago now exists as a third set.
-Ogerpon-Cornerstone: -Wood Hammer, +Power Whip (because of Sturdy)
-Zapdos: +Tera Steel, -Thunderbolt, +Discharge, role changed to Bulky Attacker (now always gets Roost; no more Specs)
-Komala: +Tera Dark, no longer gets Choice Scarf.
-Ursaluna-Bloodmoon no longer gets Silk Scarf. That was an accident.
-Support Alolan Sandslash: -Swords Dance, +Knock Off
-Cosmic Power Clefable was removed.
-Even if the team already has a hazard remover, Cyclizar will get Heavy-Duty Boots.
-Rillaboom: -Tera Flying
-Torkoal's role …

Randomized format set updates

---

sim/team-validator.ts
test/sim/team-validator/breeding.js

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9789995
This also fixes a test for a set that was assumed to be illegal but should pass as legal, as well as updating a test for a set that is now legal thanks to DLC.

Fix egg move validation for female-only Pokemon

---

.github/workflows/test.yml

The CI pipeline for PRs only triggers on the latest pushed commit. With the old selective linting, only changes in _that_ commit would be linted. 
Fetching the 100 most recent commits (at most) _on the PR branch_ ensures selective linting and testing takes all PR commits into account.
The change does not impact merge/push-to-master, since testing/linting is not selective in that case and performance impact is minimal (added ~0-1s to the checkout step).

CI: Ensure that selective linting takes all PR commits into consideration

---

data/abilities.ts
data/mods/gen9predlc/abilities.ts
data/moves.ts
test/sim/abilities/commander.js

As of DLC1, Commander can now be suppressed by Gastro Acid, Neutralizing Gas, etc. If a Pokemon with Neutralizing Gas switches in while the Tatsugiri and Dondozo are combined, they don't split apart. In addition, various other means of replacing Commander now work, though methods of giving Commander to something else do not. I've implemented all of these except Doodle, because apparently we don't implement additional banned Abilities for Doodle at all right now, so I'll want to do research to verify the full list (though it's almost certainly the same as the Role Play list).
Role Play (user) - works
Role Play (target) - fails
Skill Swap - fails
Entrainment (user) - fails
Entrainment (target) - works
Simple Beam - works
Worry Seed - works
Doodle (user) - works
Doodle (ally) - works
Doodle …

Fix Commander's interaction with Ability suppression

---

server/room-battle.ts

Fixes a bug of timer imprecision where it would occasionally say a player had 10n+1 seconds remaining instead of just 10n; I bet there are smarter ways of actually fixing it, but this should improve the margin of error when rounding.
Also adjusts the set indicators to be a table, and drops the pipe. It looks meh imo when there's a big discrepancy in name length as it is currently. I think it's cleaner for the indicators to always line up.
Before:
After:

Bo3: More design tweaks

---

config/formats.ts

- Removes Reg C formats
- Removes Reg D ladders
- Enables Reg E ladder for BSS
- Adds new best-of-three ladder for VGC with forced open team sheets
Edit: this can be merged at any time now.

Update VGC/BSS ladders

---

data/formats-data.ts

Vikavolt should be DUU as per https://www.smogon.com/forums/threads/usage-based-tier-update-for-october-2023.3728796/post-9803994 and is currently erroneously listed as DOU
(edit to add Arcticblast requested this change)

Move Vikavolt to DUU

---

data/abilities.ts
data/items.ts
data/moves.ts
test/sim/moves/syrupbomb.js

- Fix duration (was only dropping speed for 2 turns)
- End the volatile silently on client
- Remove Clear Amulet (and similar effects) messages when blocking the speed drop

Syrup Bomb fixes

---

sim/team-validator.ts

Mainly for #9832
~~Currently, the battle rng is advanced when randomly selecting genders when it is not specified by the set. This is being changed mainly due to the fact that logically, the battle rng shouldn't be advanced just for picking genders, but also so that `set.gender` can be changed to match the gender while not affecting rng if the battle gets reserialized.~~

Randomize gender in team validator instead of battle

---

data/rulesets.ts
server/chat-commands/core.ts
server/rooms.ts
sim/battle-stream.ts
sim/battle.ts
sim/team-validator.ts

Meant to supersede #9605
This is meant to do the same thing as the previous behavior but with a much cleaner (imo) implementation. Instead of modifying `poke`, this uses a new `showteam` protocol that sends the OTS in a packed format to the client. The client will then unpack the given team, handle clearing/readding the pokemon, populate the tooltips, and display the paste in the battle chat.

Send Open Team Sheets to client in packed format

---

data/moves.ts

According to datamined move data, Secret Sword has the Slicing move flag, even though it isn't implemented in SV.
This reflects that here.

Give Secret Sword the Slicing move flag

---

config/formats.ts

I find myself explaining what challenge cup means more than I'd like, this should allow for `/om challengecup1v1` and such to work.

Formats: Add descriptions to Challenge Cup formats

---

data/abilities.ts
data/items.ts

Apparently the messages do show up for syrup bomb. Should've tested in game before changing that lol

Fix Syrup Bomb messages with stat drop blocking effects

---

server/chat-plugins/repeats.ts
server/chat-plugins/room-faqs.ts

https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9451198 I tested this on a local server running the most recent version of Pokemon Showdown, so while I never caused a crash on the main server, the bug still exists there.
- Removed /rfaq alias check when setting a topic to repeat. If a /rfaq alias is set to repeat, the text of the topic the alias is set for is displayed, rather than the topic's ID.
- If a /rfaq is deleted, repeats linked to it or one of its aliases will also be deleted, preventing a crash caused by trying to display a nonexistent topic. Originally supported for just topics, but support for aliases was added, which the lack of support for is what caused crashes.
- A separate problem, but the ability to set a topic as an …

Improvements to room FAQs and repeats

---

server/rooms.ts

Currently we restart the timer every time we check for automodchat, which means that any regular user could stop automodchat just by joining and leaving more often than the time designed to trigger it.

Automodchat: Don't reset timer on disconnections

---

tools/set-import/index.js

The `package.json` links to `build/` in various properties even though all of those files are in the same flat directory and not in `build/`

Fix package.json gen in tools/set-import/index.js

---

config/formats.ts
data/abilities.ts
data/rulesets.ts
sim/pokemon.ts

Approved by rands council after receiving Zarel's blessing (heh) and direct recommendation
This adds a new clause called Illusion Level Mod. It causes an Illusion Pokemon to disguise its level as the level of its illusion. This rule is being added to gens 5-9 Random Battles to prevent Zoroark from being unbalanced while still solving the issue of its level being leaked. The fixing of Zoro's level will be done in a different pull request.
There was another change here but it was shelved, I guess

Add Illusion Level Mod

---

data/mods/gen2/random-data.json
server/chat-plugins/randombattles/winrates.ts

-Jolteon: -thunderwave
-Snorlax: -fireblast
Also reduces the rating threshold for winrate collection to 1150, since the Gen 2 Random Battle ladder is less active.

Gen 2 Random Battle updates

---

data/random-teams.ts

Since Pokemon share moves in Partners in Crime, Pokemon can use physical moves even if their original set is all special.
Ready to merge at any time.

Randomized Format Spotlight: don't lower Attack EVs/IVs

---

config/formats.ts

fixes an oversight in https://github.com/smogon/pokemon-showdown/pull/9859

Add Illusion Level Mod to Gen 9 Random Doubles

---

config/formats.ts

Gen 9
OU - Updated Metagame Discussion and VR Links
Ubers - Updated Metagame Discussion and VR links
UU - Updated metagame discussion and VR, added samples link
RU - Updated metagame discussion and changed old VR link to new viability list link. added samples
NU - Updated VR, added samples, ask NU staff about metagame discussion
PU - Added VR and Samples, ask PU staff about metagame discussion
LC - No changes.
Monotype - Updated metagame discussion, sample teams, VR
1v1 - No changes
AG - Updated metagame discussion, VR
NFE - No changes
ZU - No changes
national dex ou - added VR and samples
national dex ubers - changed viability list to viability rankings
national dex uu - added VR and samples
national dex ru - added resources thread
national dex monotype - added samples and viability …

Update various format threads

---

data/mods/gen1/random-data.json
data/mods/gen2/random-teams.ts

Gen 1:
-Venusaur is now Body Slam + Razor Leaf + 2/3 of Hyper Beam, Sleep Powder, and Swords Dance. Its overall rate of Sleep Powder increases from 50% to 66%.
-Beedrill will always roll Swords Dance, and its 4th move is a roll between Agility and Mega Drain. It will no longer get Double-Edge.
-Diglett and Dugtrio will now obtain Substitute 50% of the time, up from 33%.
-Ghosts and Lapras will no longer get Confuse Ray, since they have better alternative options.
-Jolteon will always roll Body Slam.
-Mewtwo will no longer get sets without Recover.
Gen 2:
-PU mons are now level 77, and PUBL are level 75. This is to accommodate the recent addition of GSC PU. (https://github.com/smogon/pokemon-showdown/commit/ed81f3c8ced678a9b33b064b115819ed8fd4ee32)

Gen 1-2 Random Battles update

---

COMMANDLINE.md

The `sim/RADME.md` text have a hyperlink directing to the root `README.md` instead of the simulation one.
This PR fixes the embedded hyperlink.

fix sim/README.md hyperlink

---

server/chat-commands/admin.ts

I pretty frequently run an eval from Mia that does this to check if there's any private rated ladder games going on, so I figured I'd formalize it into a proper command.

Add command to view remaining battles during lockdown

---

server/chat-commands/admin.ts

Currently when hotpatching, you don't get self-highlighted, but when doing updateclient (and presumably updateloginserver, since it's set up the same way) it'll highlight yourself. Mirrors the hotpatch implementation with ``user.getIdentity()``.

Don't highlight on updateclient/loginserver commands

---

package-lock.json
package.json

This fixes a bug detailed here: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9796082 that causes the set import buttons for some tiers (gen9ru, gen3lc are examples) to not appear.

Update Smogon package version

---

config/formats.ts

Added base LC bans on top of Mono LC specific bans, since LC rule just sets levels to 5 without adding the LC banlist

Monotype LC: Update bans

---

data/mods/partnersincrime/abilities.ts
data/mods/partnersincrime/scripts.ts

Fixes a bug where Encore can force a pokemon to get locked into a move it no longer has, and fixes a bug where innates do not get applied before abilities starting up again in Neutralizing Gas.

Partners in Crime: Fix bugs

---

config/formats.ts
data/mods/sharingiscaring/scripts.ts

To prevent refactoring every item in existence, I discovered sourceEffect takes the item it wants to proc, so I used that to provide a less time consuming and/or more elegant solution.

Sharing is Caring: Fix bugs

---

config/formats.ts
data/abilities.ts

Does the following:
> 6. Fainting a Pokemon removes an item from play
- This mechanic is now honored, which was mistakenly left out.
- Fixes a bug where a shared Booster Energy was not being properly registered as an item boost, which causes any weather/terrain change for a mon to lose its booster energy.

Sharing is Caring: Fix Mechanics and Booster Energy

---

data/mods/gen1/random-teams.ts

After the addition of pre-evo movesets the movepool was not deduplicated leading to double moves (and an uneven weighting of moves though that's harder to notice and thus got no complaints).
This fix deduplicates after making the complete pool instead of checking whether each added move is a duplicate before adding it because that's a lot faster.

Gen 1 Challenge Cup: Fix pokemon getting the same move twice

---

server/room-battle.ts

This fixes a very minor issue where usernames with a ``<`` character would cause some areas to be interpreted as HTML (the "won game x" text and the link to the specific game). I didn't take a screenshot, but also fixes the prompt where the player is asked if they're ready for the next game from being double escaped.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

Fix some HTML escaping in best-of rooms

---

data/cg-teams.ts
data/mods/gen1/random-teams.ts
data/mods/gen2/random-teams.ts
data/mods/gen2/rulesets.ts
data/mods/gen3/random-teams.ts
data/mods/gen7/random-doubles-teams.ts
data/mods/gen7letsgo/random-teams.ts
data/mods/gen8/random-teams.ts
data/mods/mixandmega/random-teams.ts
data/random-teams.ts
data/rulesets.ts
server/chat-commands/admin.ts
server/chat-plugins/datasearch.ts
sim/dex-species.ts
sim/team-validator.ts
test/sim/dex.js

After seeing fifty different ways we use `getLearnset`, most of which are just "haphazardly assemble a movepool", I decided to write `getFullLearnset` and `getMovePool`, which centralizes the implementations and prevents weird bugs like https://github.com/smogon/pokemon-showdown/commit/9713dc6db5c040a7abdf3dd088675543ae7e2827 which we spent two years trying to figure out.

Refactor learnset checking

---

data/abilities.ts
data/random-sets.json
data/random-teams.ts

Too much to say in a description. This is untested. I will fix things as I am made aware of them.
Adds Indigo Disk Pokemon, moves, and assorted code.
Knock Off is now forced on pure Normal and Fighting types.
Bug STAB is now forced on Bug/Electrics.
Psychic STAB is now forced on Grass/Psychics.
Kommo-o is now Soundproof.
Alluring Voice has replaced most instances of Dazzling Gleam.
Psychic Noise has been added to many bulky Psychics
Throat Chop has replaced nearly every instance of Crunch.
Double-Edge has replaced or become a roll with Body Slam on most offensive Normals.
Terapagos counts as a Tera Blast user.

Random Battles: Indigo Disk update

---

data/formats-data.ts

Isn't this simpler? The data from Terapagos propagates to its Terastal and Stellar forms. Since both are battle-only (and moveset independent), it doesn't make sense to separate them. This is the same case as Palafin and Palafin-Hero.

Remove Terapago-Terastal and -Stellar forms from formats-data

---

data/mods/moderngen1/formats-data.ts
data/mods/vaporemons/formats-data.ts

Adds tiering data for new Pokemon so the mods aren't effected by tiering changes to OU

VaporeMons & MG1: Add tiering data for new Pokemon

---

data/mods/gen8/random-teams.ts
data/random-teams.ts

Two changes:
1. Removes the hardcoded gen boundaries for dex numbers. I know this was rejected earlier in #9940, but I believe that to be in error, presumably because there was an active bug and so there was some rush. The only line it was used in was 559 (in the gen8 file), and that never triggered. Any Pokemon that are from a future gen already have the `isNonstandard` property `future`, and thus get filtered out in line 550. Furthermore, you would also not want it to trigger because the Pokemon are not guaranteed to come in dexnumber order. Indeed, generating a gen2CC team gives me 201, 350 and 479 first though I have no idea why. The break never triggers, but if it would team generation would fail entirely. The reason to remove it is that it requires an easy-to-forget edit when new …

Challenge Cup: Fix monotype and recurring bug with new Pokemon

---

config/formats.ts

Banning Baton Pass and Substitute in ADV ZU.
I was told to implement this by Zpice, runner up in last ADV ZU tourney.
Proof on smogon thread: https://www.smogon.com/forums/threads/roa-spotlight-tournament-adv-zu-finals-won-by-pokology.3730648/post-9881068

Ban Baton Pass and Substitute in ADV ZU

---

data/items.ts
data/pokedex.ts

I don't know if this will be fixed in a future patch, but the new Paradox Pokémon can lose Booster Energy through Knock Off, Trick, etc.
https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-49#post-9900134
We could also remove the Paradox tag from the Pokémon (this is how is coded in the cartridge), but I'm not sure if it will have other consequences.

Fix Booster Energy interaction with the DLC2 Paradox Pokémon

---

data/formats-data.ts

https://www.smogon.com/forums/threads/usage-based-tier-update-for-december-2023.3732046/post-9878673
Mega Gyarados should have dropped from OU in National Dex with 3.281% usage.

Move Gyarados-Mega to NatDex UUBL

---

data/mods/gen4/random-sets.json
data/mods/gen4/random-teams.ts
data/mods/gen5/random-sets.json
data/mods/gen5/random-teams.ts
data/mods/gen6/random-sets.json
data/mods/gen6/random-teams.ts
data/mods/gen7/random-sets.json
data/mods/gen7/random-teams.ts
data/mods/gen8/random-data.json
data/mods/gen8/random-teams.ts

**Gen 4:**
-Sableye now runs a second set with Recover, Payback, Seismic Toss, and Toxic/Will-O-Wisp,.
-Alakazam now has Calm Mind.
**Gens 4-7:**
-Floatzel now always gets Ice Punch on its Choice Band sets, and no longer has Low Kick enforced in gens 6-7.
-Pokemon that have Guts as a possible ability can no longer get Protect and Swords Dance together.
-Most Pokemon with Sniper no longer get the ability, since other abilities are superior. 
-Swarm is now allowed with U-turn, even if the set has no other Bug-type attacks. This ensures that Beedrill will always get Swarm and not Sniper.
-Bronzong no longer gets screens.
**Gens 5-7:**
-Raticate now runs Crunch and always gets it.
-Wailord now gets Water Veil, instead of Pressure.
-Volbeat no longer gets Toxic and Illumise no longer gets …

Gen 4-8 Random Battles updates

---

data/rulesets.ts

Fixed a typo in which the Evasion Items Clause description stated that it banned moves

Update Evasion Items Clause description

---

config/formats.ts

https://www.smogon.com/forums/threads/finisher-shed-tail-banned-in-national-dex-monotype.3733321/

National Dex Monotype: Ban Shed Tail

---

config/formats.ts

- Replaced all of SS OU's links since they were from when SS was current gen
- Replaced SM and ORAS OU's banlist links with Metagame Discussion threads since the banlists are already listed when you type /tier
- Updated SM and ORAS OU's sample team links to resources that are actually currently maintained
- Added Metagame Discussion links to BW, ADV, GSC, and RBY OU

Clean up oldgen OU resource links

---

config/formats.ts

As I was going through the PS source code to copy/paste 1v1 banlists, I found out that the banlists for old gens have been linked to the OU rulesets of their respective gens for Gen 5 and older. This PR removes that link and gives 1v1 standalone banlists. 
Functionally, very little changes aside from the following:
- No more unbanlists and removed rules are needed
- A bunch of gen-specific Baton Pass complex bans are removed, since they don't affect 1v1 anyway
- Evasion Abilities are unbanned from Gen 4 1v1
- Quick Claw is unbanned from Gen 4 1v1
- Arena Trap is unbanned from Gen 4 1v1
All of these changes were made by Gen 4 OU without 1v1 community realising it. I've talked to 1v1 TL Clerica about all of them

Unlink old-gen 1v1 banlists from OU

---

data/mods/sharingiscaring/scripts.ts

this.ignoringItem() getting called early seemed to have lead to a rather strange infinite recursion path.

Sharing is Caring: Fix crash with Klutz

---

config/formats.ts

Most of these haven't been updated since SS was current gen, relinked to actively maintained resource hubs.
Also updated a couple of SV OU/Ubers links for DLC 2.

Update more outdated links

---

server/chat-plugins/datasearch.ts

https://www.smogon.com/forums/threads/randpoke-pokemon-not-found-in-old-gen-battles.3733420/
Mathy's fix basically

Fix /randpoke and /randmove not finding newer moves in old rooms

---

config/formats.ts

Tera Blast is bugged and changes the BP of moves even when you dont tera, so lets restrict the move for now, terastal clause is in effect anyway, so there is no need to fix this right now  https://www.smogon.com/forums/threads/fortemons.3713983/page-15#post-9917618 replay https://replay.pokemonshowdown.com/gen9fortemons-2025537671

Fortemons: Restrict Tera Blast

---

data/moves.ts

While not a bug per se, certain moves are hardcoded to return a value equal to move.basePower in basePowerCallback, which does not causes issues up until there is a discrepancy in move.basePower (e.g. https://www.smogon.com/forums/threads/fortemons.3713983/page-15#post-9917618) where moves are called at a base power its not.

Refactor certain basePowerCallback default returns

---

config/formats.ts

https://www.smogon.com/forums/threads/zekrom-is-now-banned-from-ubers-uu.3733747/

Ubers UU: Ban Zekrom

---

data/formats-data.ts

https://www.smogon.com/forums/threads/iron-hands-latias-and-blaziken-are-banned-from-sv-uu.3733861/

UU: Update bans

---

data/mods/gen1/random-teams.ts
data/mods/gen5/random-teams.ts
data/mods/gen7/random-teams.ts
data/mods/gen8/random-teams.ts
data/random-teams.ts

This implements several changes to team generation.
-Removes the limit of one Pokemon per unique type combination in gens 4-9. (They were removed for gens 2-3 in https://github.com/smogon/pokemon-showdown/pull/10056). This means it is now possible to get, for example, Kyogre and Barraskewda on the same team. Monotype will still have a limit of three Pokemon of a type combination in gens 6-9.
-Implements a limit of four Pokemon weak to Freeze-Dry in gens 6-9. Testing has shown that its effect on team generation is negligible.
-Removes tier limits from gens 5, 6, and 7, since they no longer have Pokemon consistently attaining a winrate over 53%.
-Removes tier limits and the soft type cap from gen 1.

Randomized format team generation updates

---

server/chat-plugins/randombattles/winrates.ts

upon further inspection, toID(p) apparently just returned an empty string. ``p.name`` accurately gives us a username we can compare to.
It is strongly suggested the data for January's randbats stats gets wiped when this is implemented.

Randbats Stats: Properly check for winner

---

server/chat-plugins/hangman.ts
server/chat-plugins/helptickets.ts
server/chat-plugins/mafia.ts
server/chat-plugins/scavengers.ts
server/chat-plugins/trivia/trivia.ts
server/chat-plugins/uno.ts
server/chat-plugins/wifi.tsx
server/chat-plugins/youtube.ts
server/room-battle.ts
server/room-game.ts
server/rooms.ts
server/tournaments/generator-elimination.ts
server/tournaments/generator-round-robin.ts
server/tournaments/index.ts
server/users.ts
tsconfig.json

This refactor removes `player.unlinkUser()` which was used for several unrelated use cases.
These have been split apart into:
- at the end of a game, `game.setEnded()` now clears `user.games`, while leaving `player.id` untouched
- when trying to change the user associated with the player, we now consistently use the higher-level `game.updatePlayer()`
There's a good chance this fixes the lagspikes currently affecting PS.

Remove unlinkUser

---

server/room-battle.ts

Fixes a bug where players can still forfeit after a Best of X set has ended, probably due to the setEnded function not being called. Also added an extra safeguard to forfeiting in a Best of X set.

Bo3: Properly end sets

---

data/mods/gen7/random-teams.ts
data/mods/gen8/random-teams.ts

In both gen 7 and 8 the specifications for sets in BF allow for arrays of possible items, but the code partially dealt with them as though they were strings of single items like in gen 6, because the code has been mostly copied over. This never crashes because it's JS so the various `undefined`s just propogate, with the effect that the restrictions on items and abilities (not more than 1 scarf, not 2 weather setters, etc) were never applied.

Battle Factory: Fix item and ability restrictions

---

config/formats.ts
data/abilities.ts
data/conditions.ts
data/mods/gen3/scripts.ts
data/mods/gen4/scripts.ts
data/mods/gennext/abilities.ts
data/mods/ssb/abilities.ts
data/mods/vaporemons/abilities.ts
sim/battle-actions.ts
sim/dex-conditions.ts
sim/dex-moves.ts

Originally was just trying to fix a bug with the pledge moves and tera stellar (combined pledge moves should always be boosted to 2x by tera stellar), but may have gotten a little carried away. Anyway, this changes the STAB code to much more closely resemble the actual STAB code from the games, and introduces a new `ModifySTAB` event to further improve the separation and readability of the Adaptability logic.

Refactor STAB (again)

---

server/chat-plugins/datasearch.ts

https://www.smogon.com/forums/threads/itemsearch-behavior-with-generation-arguments.3734394/
Appending maxgen to the end meant ``all`` wasn't being parsed correctly, and itemsearch was looking for the literal string "all"

Fix itemsearch when specifying both gen and show all

---

data/mods/gen1/random-data.json
data/mods/gen1/random-teams.ts
data/mods/gen2/random-data.json
data/mods/gen2/random-teams.ts
data/mods/gen3/random-sets.json
data/mods/gen3/random-teams.ts
data/mods/gen4/random-sets.json
data/mods/gen4/random-teams.ts
data/mods/gen5/random-sets.json
data/mods/gen5/random-teams.ts
data/mods/gen6/random-sets.json
data/mods/gen6/random-teams.ts
data/mods/gen7/random-sets.json
data/mods/gen7/random-teams.ts
data/mods/gen8/random-teams.ts
data/random-doubles-sets.json
data/random-teams.ts

Implements a limit of one level 100 Pokemon per team in all generations. Council decision. Also, set updates for doubles and old gens.
**Gen 9 Random Doubles**:
-Smeargle now runs Fake Out + Follow Me + two of Decorate/Pollen Puff/Tailwind, split into two sets since Pollen Puff is enforced by default. It also now gets Technician as its ability. The incompatibility between protect moves is no longer needed, so it has been removed.
-Pelipper: +Tera Steel
-Cinccino is now Loaded Dice and Technician as intended.
-Flapple now gets Ripen and Sitrus Berry on its non-Tera Blast user set, and gets Hustle and Clear Amulet on its Tera Blast user set.
**Old Gens**:
-Butterfree and Venonat no longer run Psywave. Butterfree can now get Double-Edge. (Gen 1)
-Mewtwo no longer runs Fire Blast and Thunder …

Randomized format updates

---

data/rulesets.ts

credit to hidin for the fix. Someday I think we should deprecate using "standardnatdex" as the check for battles having natdex behavior but that's for another time

STABMons: Fix NatDex validation

---

server/room-game.ts

Using `/tour sub player1, player2` in a room with a room tour gives player2 the room player rank in said room when it really shouldn't.

Don't give substituted players rank in room tournaments

---

config/formats.ts

Adding some OU bans, bringing back bans for DLC mons, and removing redundant formes that are covered by the base forme alone i.e. Dialga https://www.smogon.com/forums/threads/pok%C3%A9bilities.3712725/post-9950359

Pokébilities: Update bans

---

config/formats.ts
data/mods/vaporemons/formats-data.ts
data/mods/vaporemons/items.ts
data/mods/vaporemons/moves.ts
data/mods/vaporemons/scripts.ts

New VaporeMons updates from [this post](https://www.smogon.com/forums/threads/vaporemons-slate-10-dlc2-vr-update-pet-mod-of-the-season.3722917/post-9949279), including the following:
- Unban of Baxcalibur for its Suspect Test
- Nerfs to Meloetta-Pirouette
- Removal of Sleep Clause and addition of Sleep Moves Clause
- Some Sleep-related nerf reversions
- Bugfix for Diancite Stone Fragment
- Updated tiering

VaporeMons: Open Baxcalibur Suspect Test, Nerf Meloetta-P, Ban Sleep, and Bugfixes

---

data/mods/gen6/abilities.ts

* Removes BP Boost on Normalize in gen 6 and earlier

Remove BP Boost on normalize in gen 6 and earlier

---

config/formats.ts

Mentioned in Smogcord by someone, confirmed by Aislinn, was seemingly unbanned due to the change in DPP OU's tiering

DPP UU: Re-Ban Baton Pass

---

data/mods/gen1/random-teams.ts
data/mods/gen3/random-teams.ts
data/mods/gen5/random-teams.ts
data/mods/gen7/random-doubles-teams.ts
data/mods/gen7/random-teams.ts
data/mods/gen8/random-teams.ts
data/mods/potd/random-teams.ts
data/random-teams.ts

This refactors species selection in Random Battles to be more efficient. 
Previously, after selecting a base species, it goes through the entire array of species to record the ones with the corresponding base species, then chooses one of them randomly.
Now, `getPokemonPool()` outputs an object `pokemonPool` which records, for each base species, the list of species with that base species. Instead of checking every species, it now just samples from the list corresponding to the base species.
This approach is significantly faster and keeps the appearance rates standardization from https://github.com/smogon/pokemon-showdown/pull/9708.
My local testing shows that this speeds up overall team generation by around 20% for Gen 9 Random Battle and 50% for Gen 7 Random Battle.

Speed up Random Battles species selection

---

server/chat-plugins/randombattles/winrates.ts

Messing around with winrates I found that they were consistently slightly below 50% on average. @livid-washed then pointed out that that could be due to ties.
With this fix, ties should no longer appear in the winrates. This is surprisingly important, as for example gen 4 winrates averaged around 49.6% for some months. This does not seem like a lot, but causes significant upward pressure to the levels in balancing, which is highly undesirable.

Randbats Stats: Properly deal with ties

---

data/mods/gen8/random-teams.ts
data/random-teams.ts

Fixes the bug that can cause crashes with Monotype Random Battles, that was inadvertently introduced in https://github.com/smogon/pokemon-showdown/pull/10138.

Fix crash in Monotype Random Battles

---

config/formats.ts

Since Inheritance is a permaladder OM, it has a bit of trouble with stat collection as a result of the Donor data being shoved into the ability slot. So, using a less important slot like the currently unused pokeball slot allows the donor information to be stored elsewhere so it does not interfere with the usage stats script.

Inheritance: Refactor donor information storage

---

data/mods/gen3/abilities.ts

Approved by DaWob, this fixes HP electric being redirected by LightningRod. 
Freeze defrosting is also handled in this way.

Gen 3 - Fix Hidden Power Electric + LightningRod interaction

---

data/abilities.ts

Tera Shift does not update Terapagos to its correct HP stat on transforming. It should jump from 90 base HP as the base form to 95 HP as Terastal form. We have similar behavior in place for Stellar Terapagos and Zygarde-Complete.
This fix works, but I'm not sure why we have to do it in the first place. Wouldn't it be better to have the stat update happen in the formeChange function? We'd run into the same problem the next time another form change that modifies base HP happens.

Fix Tera Shift not updating Terapagos's HP

---

data/mods/gen3/abilities.ts

Recognizing that keeping `move.category === 'Physical'` MIGHT be redundant.
https://www.smogon.com/forums/threads/gen-3-hustle-should-affect-status-moves-accuracy.3735326/
In Gen 3, Hustle reduces the accuracy of physical-typed Status category moves.

[Gen 3] Hustle reduces accuracy of moves by type

---

data/random-sets.json

by removing tspikes, which aren't great on it anyway

Random Battles hotfix: prevent balloon toxtricity

---

server/chat-commands/info.ts

Changed requires % @ # & > &
https://www.smogon.com/forums/threads/wrong-help-text-in-approvallog.3736518/

Fix help text in approvallog

---

config/formats.ts

Battle Bond was banned as a temporary fix to an issue where Battle Bond Greninja was able to circumvent Greninja's ban with no way to fix it other than this. Greninja is unbanned so this point is now moot.

Unban Battle Bond from Gen 9 National Dex UU

---

server/rooms.ts

A regression(?) was caused in the commit 6b42b4f6b2d6369b19a265f36bdd9061734407d5, which started sending `'0'` instead of `''` for public replays. This would get evaluated as a truthy value on the loginserver side, which caused all public replays to become private upon uploading.

Fix uploading public replays on side servers

---

data/mods/gen7letsgo/scripts.ts
sim/battle-actions.ts
sim/battle-queue.ts
sim/battle.ts
sim/dex-items.ts
sim/global-types.ts
sim/pokemon.ts
sim/side.ts
sim/team-validator.ts

Got inspired after seeing this thread https://www.smogon.com/forums/threads/lgpe-vgc-kickoff-60-prize.3738930/
Supersedes #8914
Took a similar approach to the other PR, but also separated the X form into its own thing as well, instead of trying to combine it with the regular mega evo stuff. Also got rid of the hacky logic that still allowed the mega stones as items.
Also @DaWoblefet I saw your concern in the other PR about refactoring and old replays, but I don't think that really matters unless I am missing something. Only the input log would get affected but input logs should only be rerun on their specific version number so we can refactor any time and in any way we want.

Let's Go: Implement itemless megas

---

data/mods/gen7letsgo/scripts.ts

Forgot to account for tags. Right now if you were to challenge someone with `gen7letsgoou @@@ -ou` you would still be able to mega evolve into Zard X.

Fix species validation check for Let's Go Megas

---

server/chat-plugins/randombattles/index.ts

/randsnodmax was removed after gen9 randbats was created, so I'm updating the /help command for it

Remove /randsnodmax command from /help

---

config/formats.ts

One restricted legendary format: https://sv-news.pokemon.co.jp/en/page/226.html
Once all major Regulation F events end (April 21), we'll remove the Regulation F best-of-3 ladder. Then May 1 we'll remove the best-of-1 VGC and BSS ladder.
This can be merged whenever (probably alongside April tier shifts / other formats stuff).

VGC/BSS: Add Regulation G

---

config/formats.ts

https://www.smogon.com/forums/threads/shaymin-sky-necrozma-dawn-wings-and-arceus-ghost-have-all-been-unbanned.3740378/

Ubers UU: Update bans

---

data/pokedex.ts
data/tags.ts
sim/dex-species.ts

SV added a Ultra Beast tag just for Ultra Beasts, which began to be used instead of the Sub-Legendary tag. I reflected that here and gave it to every Ultra Beast.
Also fixed some other Pokemon tags that were missing or didn't need to be given.

Add Ultra Beast Pokemon tag + fix tag mistakes

---

server/chat-plugins/calculator.ts

https://www.smogon.com/forums/threads/floating-point-imprecision-in-math.3740559/
The limit can be lowered if it looks better, but I selected 15 because it's the highest amount that generally doesn't allow for precision errors to slip through.

Limit sigfigs in /math

---

config/formats.ts
data/mods/moderngen2/scripts.ts

One last validation fix for Modern Gen 2, making moves that were illegal in the gen they were introduced legal (namely Double Iron Bash, Thousand Waves, and Thousand Arrows).

Modern Gen 2: Fix Move Validation + Do Not Use: Unban Capsakid & Snorunt

---

sim/dex-formats.ts

I was doing a mod with 0 EVs and found this bug.
The old code would convert 0 to null, allowing infinite EVs instead of zero.
There are many ways to do this, feel free to change it.

Fix rule EV Limit = 0

---

data/mods/gen5/random-teams.ts
data/mods/gen6/random-teams.ts
data/mods/gen7/random-teams.ts

Fixes some minor oversights/bugs in the most recent Random Battles update:
-In Gen 5-7, Pokemon with no physical attacks, or Foul Play as its only physical attack, will get min Attack EVs/IVs
-In Gen 6, Recycle now counts as a recovery move as intended (affects Dedenne)
-In Gen 7, Sawsbuck will always get Serene Grace with Headbutt

Random Battles minor bug fixes

---

config/formats.ts

https://www.smogon.com/forums/threads/lunala-arceus-ghost-and-shaymin-sky-have-been-quickbanned-from-ubers-uu.3741515/

Ubers UU: Ban Arceus-Ghost, Lunala, and Shaymin-Sky

---

data/mods/gen8bdsp/formats-data.ts

https://www.smogon.com/forums/threads/bdsp-uu-tier-shifts-post-107.3694307/post-10053514
I forgot to make this change when I initially moved the tiering of the other BDSP Pokemon, mostly because it was edited in after the inital post was made.

BDSP: Move Celebi to OU

---

config/formats.ts

Banning Damp Rock in SS ZU in accordance with 
[https://www.smogon.com/dex/ss/formats/zu/](https://www.smogon.com/dex/ss/formats/zu/)

Ban Damp Rock in SS ZU

---

config/formats.ts

https://www.smogon.com/forums/threads/gen-9-do-not-use-diglett-alola-suspect-pet-mod-of-the-season.3734326/post-10085589

Do Not Use: Ban Diglett-Alola

---

sim/team-validator.ts

Honestly `set.ability` should probably be changed for every `battleOnly` forme but I didn't want to mess with too much of that code. I also "fixed" Ultra Necrozma, since it wasn't mapping the moves to IDs and also needs to change the ability on the set to properly validate (though no one would use it in the builder anyway because the learnset is bugged and only shows Moongeist Beam and Sunsteel Strike :D).

Allow using Terapagos formes in teambuilder

---

data/mods/gen9ssb/random-teams.ts

The weakness limit of 3 was still enforced under forcemonotype. This harmonizes the @@@monotype and @@@forcemonotype=<type> mods.

SSBU: Disable weakness counter on forcemonotype

---

config/formats.ts

https://www.smogon.com/forums/threads/adv-doubles-quick-claw-banned.3666831/page-3#post-10114012

ADV Doubles OU: Ban Quick Claw

---

translations/french/main.ts

I made an inversion error in the translation of my last PR https://github.com/smogon/pokemon-showdown/pull/10256

French: Fix Bot description in /group

---

data/moves.ts
test/sim/misc/endlessbattleclause.js

As defined, a Pokemon is only stale if affected by the *opponent's* Skill Swap. Using Skill Swap yourself means you changed your ability of your own volition and shouldn't be considered stale anymore.
Thanks to Geneku2 who came across this in a battle (unfortunately in his opponent's favor) and reported it https://replay.pokemonshowdown.com/gen9balancedhackmons-2125311602-f9fdiydceby4d10qylt0bu0itj0zuo2pw

Endless Battle Clause: Skill Swap should remove the user's staleness

---

data/moves.ts
test/sim/moves/syrupbomb.js

* Syrup Bomb ends if the source leaves the field https://www.youtube.com/watch?v=QUk_cWJKw4Y
* Mirror Armor reflects the stat boosts from Syrup Bomb https://www.smogon.com/forums/threads/syrup-bomb-mirror-armor.3742869/post-10130871

Fix Syrup Bomb interactions with source

---

data/random-battles/gen6/factory-sets.json

Modest Probopass with no Special Attack EVs and max Special Defense EVs is a suboptimal stat spread; this changes its nature to Calm.

Gen 6 Battle Factory: fix suboptimal Probopass set

---

data/random-battles/gen9baby/sets.json
data/random-battles/gen9baby/teams.ts

One of the sets is not correctly formatted causing a non-existent teratype.

Baby Random Battle: Quick bugfix

---

data/mods/gen4/rulesets.ts
data/mods/gen5/rulesets.ts
data/mods/gen7/rulesets.ts

Currently in Gen 7 Hackmons, if a player is using a directly hacked Greninja-Ash, it would not appear at Team Preview. We need to hide the Greninja form in non-hackmons metagames to not leak if the Greninja is Greninja-Bond or not, so I mirrored the way Karthik did it for Zacian/Zamazenta. Not sure if the regex would be better combined or separated like I did it.

Reveal Greninja-Ash in Team Preview

---

data/abilities.ts
test/sim/abilities/asone.js

Fixes https://www.smogon.com/forums/threads/transformed-as-one-not-applying-unnerve.3744177/
The issue is that ``onPreStart`` correctly runs before ``onStart``, and Transform correctly only triggers Abilities that happen at ``onStart`` timing, so As One misses the timing. We have a similar implementation for Unnerve itself.

Fix interaction of As One and Transform

---

data/random-battles/gen9baby/sets.json
data/random-battles/gen9baby/teams.ts

Removes some undesirable/bugged sets found now that a lot of people are playing. Also slightly refactors the HP ev/iv thing for optimal HP, given that there's now multiple scenarios where that's applicable (belly drum and life orb).

Baby Random Battle: First set patch

---

sim/team-validator.ts
test/sim/team-validator/events.js

https://www.smogon.com/forums/threads/shiny-jirachi-validation.3733786/ The validator assumes that the Jirachi is from an event that actually does have HP Fighting; while this assumption isn't wrong, what's wrong is that the validator thinks the Jirachi is from Gen 9 due to move sources having to be from Gen 9. This change makes it so that the minimum source gen of an event-only Pokemon is separately identified when needed.
This also causes a different set to be illegal (https://pokepast.es/2a73208c20ed5503 in Gen 7 OU), which from my understanding should be the intended behavior.

Add min source gen for event-only Pokemon

---

data/abilities.ts
test/sim/abilities/slowstart.js

Based on the bug report at https://www.smogon.com/forums/threads/slow-start-turn-count-on-switches.3741527/.
Changed slowstart configuration to not decrement duration during an inactive turn, and made new test cases in slowstart to reflect changes.

Fix Slow Start duration on switch in

---

config/formats.ts

Regressed in 89128dee97060b57d4d4b9d265cf377a255b579a
Apparently it could be undefined in the past too, but JS accepts
iterating undefined with for..in just fine

Fix trademarks team validator crash

---

data/random-battles/gen9baby/sets.json
data/random-battles/gen9baby/teams.ts
test/random-battles/gen9.js

Has a bunch of simple set changes.
Apart from that, someone noticed that "rookiedee" had a typo because of which it couldn't appear. I've added a check for mon/move names in the gen9 tests to prevent this in the future, and in doing so found that "snubble" was also incorrect.

Baby Random Battle: Set updates and bug fixes

---

data/mods/gen9ssb/abilities.ts
data/mods/gen9ssb/moves.ts

-Added descriptions for End Round and Shatter & Scatter
-Adjusted TatsuGlare shortdesc to make more face-value sense
-Applied missing quality control changes (Grassy over Misty terrain on Pastor Gigas, 90 acc/65 BP on the Iron Thorns)

SSB: Add missing QC changes and update descriptions

---

server/room-game.ts
server/rooms.ts

Once a user finished a hunt, upon refresh, they would get the scavenger hunt added back to their games list since they're present in the playerTable. Adding a check during RejoinGames to ignore players who're in scavengers and have completed the current game/hunt.
PS. I'm TheAura on Showdown, a driver in scavengers, for clarity.

Scavenger Hunt Bug fix

---

server/chat-plugins/randombattles/index.ts

set.ability is an array, formatAbility expects a string.
Before: 
After:

/bssfactory: Fix ability display

---

data/items.ts
data/moves.ts
sim/dex-moves.ts
test/sim/items/metronome.js

https://www.smogon.com/forums/threads/metronome-item-and-called-moves.3745535/
This determines Metronome bonus using the called move only, as in Bulbapedia. List of moves that call other moves from here: https://bulbapedia.bulbagarden.net/wiki/Category:Moves_that_call_other_moves
This does not fix the Magic Bounce interaction.

Fix Metronome (item) with calling moves

---

config/formats.ts

…calibur and Chien-Pao
Right this got messy
Previous tiering actions commited here (banning ZacC, restricting Chien-Pao and Bax) were taken in the middle of a suspect test, and have since been reversed: https://www.smogon.com/forums/threads/godly-gift.3710734/post-10160970. There has been no post since then regarding any further action on these.
Furthermore, Kyurem-Black was banned by suspect vote: https://www.smogon.com/forums/threads/sv-godly-gift-kyurem-black.3745750/post-10164343

SV Godly Gift: Update bans

---

server/chat-plugins/chatlog.ts

Missing space, seems like a regression from
82ed9b0d2b2e15af54d30de4a1adec20c52be970
Should fix these crashes

Chatlog: Fix broken query

---

data/aliases.ts

New alias: `hhp` -> "High Horsepower" in teambuilder

Create alias for High Horsepower

---

config/formats.ts

https://www.smogon.com/forums/threads/bw1-overused.3744853/
In the original version of the OP, Baton Pass was completely unrestricted. However, since then, Baton Pass Stat Clause has since been implemented, but was never done on my fork.
King's Rock and Razor Fang have never been banned in BW1 OU.

[Gen 5] BW1 OU: Update bans

---

config/formats.ts

https://www.smogon.com/forums/threads/bw1-ou-open-signups.3745159/
Acupressure and Assist were never banned in BW1 OU.
<details>
<summary>Relevant screenshots</summary>
</details>

[Gen 5] BW1 OU: Unban Acupressure and Assist

---

config/formats.ts

https://www.smogon.com/forums/threads/bw1-overused.3744853/#post-10176942
(I don't know why the TL had me unban KR if they knew that this would happen, but oh well)
(Also BPSC was implemented in a prior PR)

[Gen 5] BW1 OU: Ban King's Rock

---

data/mods/gen1/formats-data.ts

https://www.smogon.com/forums/threads/rby-zu-hub.3732499/post-10076662 Ponyta, Tentacool, and Rhyhorn are all tiered B2 or higher on the ZU VR and should be tiered ZU as a result.

RBY: Move Ponyta, Tentacool, and Rhyhorn to ZU

---

data/mods/gen5bw1/formats-data.ts

Move Hydreigon and Toxicroak out of OU by technicality, since that is a distinction given to OU Pokemon after the generation had ended. It is the same reason why other Pokemon that are OU by technicality in Gen 5 OU are not listed as such in this mod.

[Gen 5] BW1: Update tiers

---

data/mods/gen5bw1/pokedex.ts

These Pokemon only gained access to their Hidden Abilities during the release of Pokemon Dream Radar, which never released before the release of Pokemon Black and White 2.

[Gen 5] BW1: Remove Dream World abilities of gen 2 and 4 cover legendaries

---

server/chat-plugins/auction.ts

- Sorts names in draft pool alphabetically
- Adds additional dropdown to main display that shows current auction settings
- Adds a uhtml infobox under every highest bid to more clearly convey current bid info (taken from Scrappie)
- Adds `/overpay` command, basically an alias for `/announce OVERPAY!` that regular users can use (Scrappie command port)
- Ensures that "Guest" usernames don't appear as managers if a manager uses `/logout`

Auctions: Formatting changes and QoL additions

---

data/mods/partnersincrime/scripts.ts
data/mods/trademarked/scripts.ts
sim/battle.ts

Fixes https://www.smogon.com/forums/threads/unescaped-usernames-in-crazyhouse.3746267/
PRing because it feels kinda dumb to have to import Utils here - does the Crazyhouse implementation actually need to exist in PiC and Trademarked?

Crazyhouse: Properly escape usernames

---

data/random-battles/gen2/teams.ts
data/random-battles/gen3/sets.json
data/random-battles/gen3/teams.ts
data/random-battles/gen4/sets.json
data/random-battles/gen4/teams.ts
data/random-battles/gen5/sets.json
data/random-battles/gen5/teams.ts
data/random-battles/gen6/sets.json
data/random-battles/gen6/teams.ts
data/random-battles/gen7/sets.json
data/random-battles/gen7/teams.ts
data/random-battles/gen7letsgo/teams.ts
data/random-battles/gen8/teams.ts
data/random-battles/gen8bdsp/teams.ts
data/random-battles/gen9/doubles-sets.json
data/random-battles/gen9/sets.json
data/random-battles/gen9/teams.ts
data/random-battles/gen9baby/sets.json
data/random-battles/gen9baby/teams.ts
data/random-battles/gen9cap/sets.json
data/random-battles/gen9cap/teams.ts
server/chat-plugins/randombattles/index.ts
sim/global-types.ts
test/random-battles/all-gens.js

This reworks ability generation in revamped Random Battles formats (Gens 3-7, Gen 9, Gen 9 doubles, Gen 9 baby, Gen 9 CAP spotlight), as follows:
- Each set now has an `abilities` section which lists the possible abilities that can be generated. The vast majority of sets only have one possible ability, so that ability will be selected. Many species have multiple sets with different abilities. For example, Yanmega has two sets, one with Tinted Lens and the other with Speed Boost.
- For sets with multiple abilities, the system determines which abilities are "allowed" based on the set of four moves generated. If there are multiple allowed abilities, it selects randomly and uniformly from them. For example, Infernape will always obtain Blaze if it has no punching moves (since Iron Fist is …

Rework ability generation in Random Battles

---

config/formats.ts

Before, the thread that was linked was for the RBY PU Hub. It has been replaced by the thread for the RBY ZU Hub.

RBY ZU: Fix threads

---

data/mods/gen5bw1/pokedex.ts

Impostor Ditto is only available from Hidden Grottoes in the Giant Chasm, which are only available in Black and White 2.

Gen 5 BW1: Ditto's Dream World ability is unreleased

---

data/mods/gen2/moves.ts
data/mods/gen3/moves.ts
data/mods/gen4/moves.ts
data/mods/gen5/moves.ts
data/mods/gen8/moves.ts
data/mods/gen9dlc1/moves.ts
data/mods/gen9ssb/moves.ts
data/mods/gennext/moves.ts
data/moves.ts
data/text/moves.ts
server/chat-plugins/datasearch.ts
sim/dex-moves.ts
sim/dex-species.ts
sim/team-validator.ts

As of DLC2, Scarlet/Violet have a proper move flag for moves that can't be Sketched. This converts the old flag we were using to a standard move flag.
I also corrected a very minor bug of Chatter being flagged as not Sketchable in 9, as well as updated Sketch's descriptions.

Convert noSketch to move flag

---

data/abilities.ts
data/mods/gen7pokebilities/scripts.ts
data/mods/partnersincrime/scripts.ts
data/mods/pokebilities/scripts.ts
data/mods/trademarked/scripts.ts
data/moves.ts
sim/pokemon.ts
test/sim/moves/dragoncheer.js

Fixes https://www.smogon.com/forums/threads/dragon-cheer-and-psych-up.3735685/
It also fixes the interaction of Transform with Dragon Cheer so that Transform / Psych Up are copying the current Dragon Cheer crit boost level (before, I'm pretty sure they were defaulting to whatever type the user of Transform / Psych Up was).
I also removed a pointless test for checking if Dragon Cheer was a sound move.

Fix interaction of Psych Up and Transform with Dragon Cheer

---

server/chat-plugins/auction.ts

Fixes a desync that can happen with the players array for a team if you undo a nomination right after manually removing the last nominated player from their team.

Auctions: Fix edge case for removing players after an undo

---

server/chat-plugins/mafia.ts
server/room-game.ts

This is going to be a large refactor with several commits, I'm PRing this in draft form to allow reviews as I complete portions of the refactor.
The overall goal is to stop directly accessing, iterating over, and modifying the playerTable from RoomGame which is causing all sorts of issues for mafia players.
Expect this to take a while to complete.

Mafia: Refactor plugin to stop misusing the playerTable

---

data/random-battles/gen3/sets.json
data/random-battles/gen4/sets.json
data/random-battles/gen5/sets.json
data/random-battles/gen6/sets.json
data/random-battles/gen7/sets.json
data/random-battles/gen8/data.json
data/random-battles/gen9/doubles-sets.json
data/random-battles/gen9/sets.json
server/chat-plugins/randombattles/winrates.ts

Monthly balance patch, thanks as always.
In addition to the level changes, the Elo threshold for winrate gathering is lowered to 1150 for baby random battle, and raised to 1400 for doubles, to align with their ladder activity.

Random Battles: July 2024 balance patch

---

config/formats.ts

https://sv-news.pokemon.co.jp/en/page/245.html
Bans all sub-legendary, legendary, restricted legendary, and mythical Pokemon, in addition to the DLC2 Paradoxes. Giving everyone a ladder like we did in Reg F. This can go live with August's tier shifts.

VGC/BSS: Add Regulation H

---

config/formats.ts

Darkrai is already in the banlist, so it being also restricted was messing things up a bit.
Palafin-Hero being restricted was redundant as Palafin is banned as a whole.

Pokemoves: Fix validation

---

config/formats.ts

https://www.smogon.com/forums/threads/national-dex-doubles-4-zygarde.3748231/page-2#post-10214135
Bans Zygarde and fixes teambuilder filtering for Ultra Necrozma and Zyg-C who are otherwise banned. If there's a different preferred way to do the second part, please let me know/feel free to adjust, but I figured this would be suitable.

National Dex Doubles: Update Bans

---

config/formats.ts

Because the Pokemove will get removed before calling the parent set validation, you can get away with running 5 moves lol. So its best to catch any attempts early.

Pokemoves: Prevent 5 move sets

---

config/formats.ts

Kingambit banned via suspect for Gen 9 Monotype - https://www.smogon.com/forums/threads/sv-monotype-suspect-8-kingambit.3749700/post-10241975

Monotype: Ban Kingambit

---

data/mods/gen6megasrevisited/abilities.ts

Parental Bond bugfix, now it doesn't work on set damage moves
(...which is the entire reason why Mega Kangaskhan is even legal in MRV and I somehow forgot to code it in because I'm dumb and somehow no one caught it in 2 years of MRV existing on our side server...)

Megas Revisited: Fix Parental Bond

---

sim/battle.ts
sim/side.ts

If you have a Tatsugiri on the left and a Dondozo on the right, and you run the command `/move 1 1, pass` in the chat, the move will be registered. However, it will not execute `Battle.commitChoices()`. If you enter that command before the opponent acts, the opponent's action will trigger the `Battle.commitChoices()` method, and everything will work fine. But if you run it after the opponent has acted, the turn will never finish. If either player tries to perform another action, the server will respond with `[Invalid choice] Sorry, too late to make a different move; the next turn has already started`.
Regarding the specific issue with the trailing `pass`, I can either throw an error as it is now or change it to simply ignore it by returning `true`. Let me know which you prefer.
In case …

Bug: desynchronization between the Battle and RoomBattle

---

config/formats.ts

Mewtwo and its mega evolutions are already marked as DUber.

Refactor Let's Go Doubles banlist

---

data/random-battles/gen9/teams.ts

Because rands code moved from considering all legal abilities to explicitly enumerated abilities, the vast majority of sets only have 1 and therefore the set generation for FFA never reached the intended hardcoded abilities.

FFA Random Battles: Fix ability hardcodes

---

server/rooms.ts

https://www.smogon.com/forums/threads/battle-roomlist-does-not-properly-account-for-private-battle-urls.3750415/

Run `updatesearch` after changing privacy of game room

---

config/formats.ts

Putting "Random Battle" in its name ensures that the speed ranges on mouseover are accurate by calculating its max speed with 85 EVs and a neutral nature, instead of 252 EVs and a positive nature.
Having "Random Battle" at the beginning ensures that the spotlight format is compatible with +cap.

Rename Randomized Format Spotlight

---

server/chat-plugins/auction.ts

Every draft is snake of course, that's just the name for creditless drafts. Nominating a player will instantly draft them, and a team's draft will be over once they reach the specified player count (uses the existing min player count setting). Snake drafts have a default nom timer of 60s, after which their turn will be skipped if they fail to nominate a player.

Auctions: Add support for snake draft

---

config/formats.ts
data/mods/gen7letsgo/rulesets.ts

It basically just adds 'Adjust Level = 50' to [Gen 7 Let's Go] Doubles OU.

Refactor LetsGo rulesets

---

sim/team-validator.ts
test/sim/team-validator/events.js
test/sim/team-validator/misc.js

https://www.smogon.com/forums/threads/underleveled-evolved-pokemon-events.3747655/
If underleveled encounters are implemented as events, as suggested in [this thread](https://www.smogon.com/forums/threads/low-level-staravia-and-bibarel.3737100/), then this code will be able to allow such Pokemon as well. Currently, they're implemented in learnsets.ts without any usage due to being separate from eventData.
This also fixes an oversight from #10444 which allowed egg Pokemon under level 5 if they were a species with an associated incense and not hatched from an incense (Marill and Wobbuffet).

Allow underleveled event Pokemon

---

data/moves.ts

https://www.smogon.com/forums/threads/showdown-dex-non-cap-moves-appearing-as-cap.3750874/
The above bug happens because the client expects the moves to be at the bottom, since it doesn't do any sorting of the moves itself.

Move CAP moves to bottom of main move data table

---

data/mods/gen7letsgo/formats-data.ts

Charizard-Mega-Y quickbanned to RUBL.
https://www.smogon.com/forums/threads/lgpe-ru-zard-y-quickbanned.3696384/#post-10258917

LGPE: Update Tier for Charizard-Mega-Y to RUBL

---

server/chat-plugins/datasearch.ts
sim/team-validator.ts

In short, dexsearch ~is~ was abnormally slow. A simple query like `/nds fire` took **~2 seconds** and `/nds pivot` **~4 seconds** on the prod server and my decent laptop.
This PR applies a few extremely simple fixes that address ~99% of the performance problems. **The aforementioned queries now take ~5 milliseconds and 30 milliseconds**, respectively. Far more optimizations are possible, but won't be as simple or impactful.
Below are the (very scarce) performance stats for `npm test`, running on an `i7-9750h`.
These are cheaper than `/nds`. The first test is especially slow because of the nature of JITs.
<details>
<summary>Initial</summary>
```
Before
now executing: pivot|batonpass, mod=gen8
query prep:	 54.37550900131464 ms
dex size: 804
filters total:	 129.14655699953437 ms
stat …
```

Dexsearch optimization

---

server/chat-plugins/datasearch.ts
sim/team-validator.ts
test/sim/team-validator/misc.js

https://www.smogon.com/forums/threads/slowking-counter-slack-off.3751437/
The idea I had with this change is to find all the possible "evolution paths" a Pokemon can have through generations (eg. if a Slowpoke evolved to Slowking in Gen 4, it can have all Slowpoke moves from Gen 4 and earlier, and all Slowking moves from Gen 4 and later). So for the Slowking in the bug report, if it knows Slack Off, then all of the possible evolution paths includes anything that doesn't have Slowking in Gen 3, and conversely, having Counter would include all evolution paths that don't have Slowpoke in Gen 4 and later. Since having one of the two moves would exclude the other move from their "learnset domains", having both Counter and Slack Off means there is no possible evolution path that includes both …

Fix prevo/evo move incompatibilities

---

data/pokedex.ts

Rockruff with Own Tempo can only evolve during the evening which currently is not reflected in it's `evoCondition`.

Clarify Special Rockruff evo time of day

---

data/mods/gen6megasrevisited/abilities.ts
data/mods/gen6megasrevisited/pokedex.ts
data/mods/gen6megasrevisited/scripts.ts

Balance Patch seen in [this post](https://www.smogon.com/forums/threads/gen-6-megas-revisited-ladder-challenge-post-469-balance-patch-post-480-pet-mod-of-the-season.3713949/post-10281040), with the following changes:
- Nerfs Parental Bond to Gen 7 effects
- Removes Icicle Crash from Tyranitar
- Stat nerfs to Mega Kangaskhan and Mega Altaria

Megas Revisited: Post-PMPL Balance Patch

---

data/mods/gen1/moves.ts
data/mods/gen1/scripts.ts
test/sim/moves/hyperbeam.js

Partial trapping moves negate the recharge turn of Hyper Beam, regardless of whether they hit or miss. 
Also implements the [Hyper Beam automatic selection glitch](https://glitchcity.wiki/wiki/Hyper_Beam_automatic_selection_glitch): if a faster partial trapping move misses against a recharging Pokemon, the recharging Pokemon will automatically use Hyper Beam (and if Hyper Beam has 0 PP, it will underflow to 63 PP).

Gen 1: fix Hyper Beam recharge interactions with partial trapping moves

---

data/abilities.ts
data/mods/gen7pokebilities/scripts.ts
data/mods/partnersincrime/scripts.ts
data/mods/pokebilities/scripts.ts
data/mods/trademarked/scripts.ts
data/moves.ts
sim/pokemon.ts
test/sim/abilities/costar.js
test/sim/moves/dragoncheer.js

If a pokemon under the effect of `focus energy` tries to copy the `dragon cheer` effect, the server crashes. Removing the possible crit stage modifiers first protects against `dragon cheer` trying to set the property of a volatile that was never successfully added.
I didn't test this for faithfulness against the in-game behavior.
Replication instructions:
start a local server.
create two doubles teams. One must have a mon that can use both `focus energy` and `psych up`, e.g. hydreigon. The other must have a pokemon that can use `dragon cheer`. Challenge yourself with the two teams.
Turn 1: use `dragon cheer` and `focus energy`
Turn 2: use `psych up` from the mon under `focus energy`, targeting the opposing mon under the effect of `dragon cheer`
Sample crash log/replay below:
```
CRASH: …
```

Fix crash with Psych Up, Focus Energy, and Dragon Cheer

---

data/mods/gen6megasrevisited/pokedex.ts

Extremely minor bug fix for Megas Revisited, Mega Sceptile has +5 HP which it's not supposed to have and Mega Ampharos has +5 SpD that it wasn't supposed to have, resulting in BSTs that were above +100.

Megas Revisited: Fix Mega BSTs over +100

---

data/mods/gen2/formats-data.ts

https://www.smogon.com/forums/threads/zu-old-gens-hub-gsc-quickban-slate-359.3646944/post-10274326

GSC ZU: Ban Eevee, Beedrill, and Staryu

---

data/mods/sharedpower/moves.ts
data/moves.ts

Fixes this bug report on Smogon: https://www.smogon.com/forums/threads/using-rest-with-multiple-abilities-attributes-wrong-ability.3752098/
Splits the insomnia/vital spirit check for rest into two checks for shared power, which negates the need to get the ability for the building of the protocol message.
Tested on both constructed SP and on random battles SP. The mod works differently between them, but both use this data so it works for both.

Shared Power: Fix source for Rest failure message

---

sim/dex-species.ts
sim/team-validator.ts
test/sim/team-validator/misc.js

https://www.smogon.com/forums/threads/shellos-east-has-weird-incompatible-moves-in-gen-9-natdex-draft.3752399/
Using the same logic that getFullLearnset uses.
Also fixes getMovePool so that the two different places that change eggMovesOnly do not override each other.

Properly validate cosmetic forms in learnsetDomain

---

data/rulesets.ts
test/sim/misc/inversebattle.js

https://www.smogon.com/forums/threads/3752389/

Allow Tera Shell to work in Inverse battles

---

sim/dex-species.ts
sim/team-validator.ts

https://www.smogon.com/forums/threads/impossible-hm-moves-in-movesearch.3735989/

Exclude unobtainable HM moves from movesearch

---

config/formats.ts

Gen 3 draft format is needed for a Smogon Draft League tournament.
https://www.smogon.com/forums/threads/adv-cup-signups.3752743/

Add Gen 3 Draft

---

config/formats.ts

* Giratina-Origin: Ubers -> Ubers UU
* Lugia, Deoxys-Speed: Ubers UU -> Ubers
* Rayquaza: Ubers -> Ubers UU BL
* Arceus-Fire: Ubers UU -> Ubers UU BL
Source: https://www.smogon.com/forums/threads/national-dex-ubers-uu.3742166/post-10297985

National Dex Ubers UU: Tier Shifts and Bans

---

sim/dex-abilities.ts
sim/dex-conditions.ts
sim/dex-data.ts
sim/dex-items.ts
sim/dex-moves.ts
sim/dex-species.ts

Use cached, deep frozen instances for lookups with empty IDs.
For me, `npm test` went from 16s to 10s.
Spun off from [this](https://github.com/smogon/pokemon-showdown/pull/10549#issuecomment-2403851844)
I also tried `./sim/dex-formats', but got this error.
```
2116 passing (10s)
87 pending
1 failing
1) Simulator abstraction layer features
Battle
should not get players out of sync in rated battles on rename:
TypeError: Cannot assign to read only property 'ruleTable' of object '[object Object]'
at DexFormats.getRuleTable (sim/dex-formats.ts:899:24)
at Object.createBattle (server/rooms.ts:2188:32)
at Context.<anonymous> (test/server/room-battle.js:27:17)
at processImmediate (node:internal/timers:476:21)
```
And empty names are rarely passed to DexFormats.get(), at least during `npm run …

Dex*: Cache empty objects

---

data/mods/gen1/scripts.ts
sim/dex.ts

The only issue came from `gen1`'s `init` not using `modData`. After fixing that, everything just works. You can test this by deepFreezing dataCache right after running `Scripts.init` and then loading all the species for all the mods and running the test suite.

Dex: Don't `deepClone` Pokedex during load

---

data/mods/gen8linked/moves.ts
data/moves.ts

Bugfix for `gen8linked`, minor optimization for `base` and `gen8linked`.

Data: Use types.all() in conversion2.onHit

---

sim/dex-species.ts

About 25% for `npm run full-test`.
We know that the `species` variable is constant, the `Species` object is deepFrozen, and the `id` parameter is not reassigned in the function. Also, `.eggMovesOnly` is not a state-ful function.
Perf bug originates in d10187162b8f6876642fec94071dbc91a6378390

DexSpecies: Fix major perf bug in getMovePool

---

sim/dex.ts

Spinoff of https://github.com/smogon/pokemon-showdown/pull/10549
Yet another simple change. Saves about 9 MB. That number could also be BS. Heap snapshot soon (TM).
Benchmark: 
```ts
console.log(process.memoryUsage());
const start = performance.now();
Dex.includeMods();
Dex.includeModData();
console.log(performance.now() - start);
console.log(process.memoryUsage());
```
Before:
```
{
rss: 72876032,
heapTotal: 21819392,
heapUsed: 14359032,
external: 2136062,
arrayBuffers: 379495
}
1201.6942330002785
{
rss: 343375872,
heapTotal: 253513728,
heapUsed: 227047504,     <--------
external: 2141831,
arrayBuffers: 341063
}
```
After:
```
{
rss: 72695808,
heapTotal: 22081536,
heapUsed: 14419336,
external: 2143886,
arrayBuffers: 387319
}
1196.5219890028238
{
rss: 325799936,
heapTotal: 251940864, …
```

Dex: share dataCache entries when possible

---

sim/dex.ts

New line 522 is the same as old line 518 but git likes to show it as being moved rather than lines 528-529/519-520.
PR #10611 means that we don't need to check for Pokedex in line 527/518 any more.

Simplify reuse of parent data cache when child gen has no override file

---

data/moves.ts
test/sim/moves/pursuit.js

Currently, when triggering on a target switching out, Pursuit will go first and THEN the user will Terastallize, which is counterintuitive at the very least.

Fix Pursuit's interaction with Terastal in NatDex formats.

---

test/random-battles/tools.js

While working on #10616 , I've observed that several seconds are spent building strings in `assertSetValidity` from `./test/random-battles/tools.js`.
Stats:
249K calls
| stage | time (ms) |
| --- | --- |
| Baseline | 6858 |
| Pull out `JSON.stringify` | **3673** |
| Replace all strings with `''` | 2770 |
So, you can save up to another 1s by lazily constructing the strings. I decided to pass on that.
3 seconds doesn't seem like a lot right now, but with my local copy of #10616, I'm at ~135 seconds total. So, it adds up. And it's an easy change.
I could not produce similar gains for the other functions in that file, so I left them alone.

Test: Remove repeated `JSON.stringify`s in `assertSetValidity`

---

data/mods/gen5bw1/pokedex.ts
data/mods/gen9ssb/pokedex.ts

Discovered while working on #10608
2 in `gen5bw1`, 1 in `gen9ssb`.
---
There are also two entries with `inherit: true` whose parent mods don't actually have a matching entry:
* `embodyaspect` in `gen9predlc`
* `flygonite` in `gen9ssb`
TBC, the inherit field sticks around at run-time - it never gets removed by `loadData` in `sim/dex.ts` because the parent mod has no such entry so you never reach that part of the code.
I couldn't just remove the `inherit` field because then Typescript complains. I think someone more familiar with `sim/` needs to put appropriate values for the fields of those two items. Or maybe they're working as intended. IDK. Just thought I'd let you know.

Data: Fix misspelled pokedex IDs

---

sim/dex.ts

Results in fewer object shapes.
Similar to #10608. Smaller effect, but very easy change.
`loadData` and `construct all` are in milliseconds.
`heap 1` is MB after loading data for all mods (`after`)
`heap 2` is MB after constructing objects for all mods (`aftest`)
| Stage            | loadData | construct all | heap 1 | heap 2 |
| ---------------- | -------- | ------------- | ------ | ------ |
| Baseline         |     1261 |          3421 |    174 |    277 |
| just loadData (this PR)    |     1265 |          3052 |    171 |    268 |
| just field order (other PR) |     1274 |          2197 |    174 |    263 |
| both PRs            |     1264 |          2064 |    171 |    260 |
---
<details><summary>Benchmark code</summary>
Inserted at bottom of `./sim/dex.ts`
```ts
const v8 = require('v8'); …
```

Dex/`loadData`: Merge objects w/ spread syntax

---

sim/team-validator.ts
test/common.js
test/random-battles/all-gens.js
test/sim/misc/megaevolution.js
test/sim/team-validator/basic.js

Found some instances where formats were being created w/ exists=false.
I made changes for the cases where a correct ID seemed obvious.
Those were:
* `gen6uber` -> `gen6ubers`
* `gen7uber` -> `gen7ubers`
* `gen9battlestadiumsingles` -> `gen9bssfactory` (test label mentions factory)
* `gen5anythinggoes` -> `gen4anythinggoes` (gen5 AG DNE)
---
<details><summary>Code for finding these</summary>
```ts
// top-level decls in ./sim/dex-formats.ts
const uniq_id = new Set();
const uniq_stack = new Set();
// ...
// inserted at bottom of Format constructor in ./sim/dex-formats.ts
if (!this.exists) {
const stack = new Error().stack;
if (!uniq_id.has(this.id) || !uniq_stack.has(stack)) {
uniq_id.add(this.id);
uniq_stack.add(stack);
const ms = stack!.replace(/put-your-repo-path-here-or-comment-out/g, …
```

Test: Correct several format IDs

---

data/text/items.ts

I think this is the only item that doesn't have a description? Was adding types for ps-client and found this
https://bulbapedia.bulbagarden.net/wiki/Strange_Ball for reference

Items: Add descriptions for Strange Ball

---

sim/dex.ts
test/sim/dex.js

With the initial introduction fo TypeScript at 3716f36, ``Dex.mod``, and ``Dex.format`` (nowadays ``Dex.forFormat``) no longer ensured that the data cache has been filled.
Newer lazy-loading getter APIs were introduced, which were intended to be used as a replacement for direct access to the loaded data (``dataCache``).
However, these APIs were either not effective or not properly used., as reflected by 43ef4d9, which reverted ``Dex.forFormat`` to its full capabilities.
Nevertheless, ``Dex.mod`` was left untouched, which results in a footgun where ``Dex.forFormat('gen1randbats').gen == 1``, but ``Dex.mod('gen1').gen == 9`` - when ran from different processes.
This commit brings back ``Dex.mod`` to its original behavior, so that gen information is always there when it's needed.
Thanks to …

Preload data when using Dex.mod

---

server/chat-commands/info.ts
server/chat-commands/room-settings.ts
server/chat-plugins/datasearch.ts
server/chat-plugins/randombattles/index.ts
server/chat-plugins/sample-teams.ts
server/chat-plugins/suspect-tests.ts
server/chat-plugins/teams.ts
server/chat.ts
sim/dex-formats.ts
tools/set-import/importer.ts

- Fixes crash in ``/learn``
- Fixes checks in various plugins.
- ``DexFormats#validate()`` now rejects rules, and other pseudoformats.
- Adds extra parameter to ``ChatContext#splitFormat``, ``ChatContext#extractFormat`` to preserve ``/dt 350cupmod, eevee``

Fix bugs connected to format.exists

---

server/chat-plugins/daily-spotlight.ts
server/chat-plugins/seasons.ts
server/private-messages/index.ts
server/roomlogs.ts

`server/chat-plugins/daily-spotlight.ts` shows how to correctly find next midnight, although it uses `valueOf` instead of `getTime` which I assume would be preferred, so I updated that.
`server/chat-plugins/seasons.ts` doesn't make use of all four arguments to `setHours` when it could, so I fixed that while I was checking for misuses of `setHours`.
`server/private-messages/index.ts` and `server/roomlogs.ts` both try to find next midnight by adding 86400 seconds and then rewinding to 00:00:01, but this doesn't work in days with DST transitions as they don't have 24 hours, so I ported the code from `server/chat-plugins/daily-spotlight.ts`.

Handle 25 hour days correctly

---

config/formats.ts

Oricorio-Baille and Overqwil Banned via Council Vote, Replaced by Galvantula and Gorebyss.

35 Pokes: Update bans

---

config/formats.ts

Note: Beat Up should not be restricted per https://www.smogon.com/forums/threads/foresighters.3735969/
Tested on input log:
```
>version 2425f1364de080346313a8917b8af0a0670d3b0a
>start {"formatid":"gen9challengecup6v6@@@foresighters,!terastalclause","seed":[48563,14448,799,11852],"rated":"Tournament battle"}
>player p1 {"name":"WooperLeTrooper","avatar":"ingo","rating":0,"seed":[55809,21582,33203,21290]}
>player p2 {"name":"articoo ☾","avatar":"#rbtt6teamchienpao","rating":0,"seed":[37796,6425,56933,50247]}
>chat ☆articoo ☾|glhf
>chat ☆WooperLeTrooper|hai articoo~
>chat ☆WooperLeTrooper|u2
>chat  Grimora|Yay wooper won
>chat  Grimora|Wooper you better clutch up this entire tourney
>chat ☆WooperLeTrooper|Nah
>chat ☆WooperLeTrooper|I'd lose
>p1 team 6, 2, 3, 4, 5, 1
>p2 team 1, 2, 3, 4, 5, …
```

Foresighters: Fix Beat Up crash

---

config/formats.ts

There shouldn't have been any bugs since things should run it through `toID` first, but it seems better to be consistent.
I didn't find any similar typos in the rest of the file.

Formats: Remove leading space in ' ND LC'

---

sim/battle-actions.ts

so it tells the client the right forme when it's sent out again

Fix Morpeko form permanence

---

test/random-battles/tools.js

Use `setSeed` instead of constructing a new generator where only the seed differs.
Saves about 50 / 324 seconds during `npm run full-test`.
Cherry-picked from #10616

Test: Refactor `testTeam` and `testSet`

---

server/chat-commands/info.ts

https://www.smogon.com/forums/threads/dt-wrong-target-shown-for-aromatherapy-heal-bell.3752924/

`/dt`: Differentiate "User's Team" target moves

---

data/mods/gen1rbycap/moves.ts

Quickfix, Icicle was accidentally made physical when it should be Special like all other Ice moves

RBY CAP: Give Probosicle's signature move the right category

---

sim/dex-moves.ts

Dedup for `DataMove`.
`ret size`: Retained Size column in Chrome dev tools memory tab. "Size of the object plus the graph it retains"
| stage | `DexMoves` ret size | `DataMove` ret size | `allMods.moves.all()` | total heap size |
| --- | ---- | ----- | --- | --- |
| Baseline | 24.345 MB | 22.747 MB | 475 ms | 260 MB |
| dedup moves | 3.3 MB | 3.0 MB | 402 ms | 240 MB |
36344 -> 4968 instances of `DataMove`.
I was really shocked to find that it loads faster - it's running **more** code.
I'm guessing the 86% dedup rate means that so much less memory (which now never leaves the 'young gen') had to be copied by the GC, so maybe that's where the time savings come from? 
The first couple paragraphs of [this v8 blogpost](https://v8.dev/blog/orinoco-parallel-scavenger) explain the role of the …

Sim/`DexMoves`: Deduplicate `DataMove` against parent mod

---

server/chat-plugins/suspect-tests.ts

`setbvalue` makes more sense than `setcoil` since the property being adjusted is the b value, and the COIL threshold is set separately in `/suspects add` (perhaps support can also be added to the latter command to require the b value as an argument if coil is specified?). I also called `Dex.formats.get` earlier on in the command because the formatting of using a format's name is more fitting with the rest of the design of `/suspects`.

`/suspects`: Rename `setcoil`

---

server/chat-commands/info.ts

Certain moves in Staff Bros (and maybe potentially in pet mods but im not sure) have unique Flying Press-like effectiveness so a crash is triggered when trying to `/coverage all` because some moves go over/under the arbitrary stages set out from the original logic.

Coverage: Don't crash on uncommon multipliers

---

server/chat-formatter.ts

Fixes https://www.smogon.com/forums/threads/urls-within-square-brackets-freeze-client.3755215/
This still allows for cases where e.g. brackets are used in url params (`https://example.com/?test[]=1&amp;test[]=2`)
Also removed an extra backslash in one of the character classes -- it seemed to be an error because `[\\s]` matches the backslash or the lowercase letter "s", rather than whitespace like the other ones
Seeing the change requires full client rebuild.

Chat: Don't allow unmatched square brackets in hyperlinks

---

server/rooms.ts

As per PROTOCOL.md, users without a rank should have a space in place of where the rank should usually be:
> `USER` = a user, the first character being their rank (users with no rank are
> represented by a space), and the rest of the string being their username.
When the user logs out (via either /logout or clicking the "Log out" button), there is currently no space in the leave message sent.
As far as I can tell, this bug was [introduced in 2015 during a refactor](https://github.com/smogon/pokemon-showdown/commit/404520b5e1892ff66b2bea87222935279ced2ab6#diff-e8d83303f9dcd49b0865ba7f08d8b798e3b35b92d00e25eb86c257e5945feb25L1651).

Fix invalid leave messages being sent on logout

---

sim/dex-items.ts

Dedup for `Items`.
Very similar to #10658.
|   stage  | \`DexItems\` ret size | \`Items\` ret size | \`allMods.items.all()\` | total heap size |
| -------- | --------------------: | -----------------: | ----------------------: | --------------: |
| baseline | 8714 KB | 7485 KB | 125 ms | 256 MB |
| w/ dedup | 1445 KB |  830 KB | 102 ms | 250 MB |
19876 -> 2173 instances of \`Item\`, 6MB peak savings.

Sim/`DexItems`: Deduplicate `Item` against parent mod

---

sim/battle.ts
test/sim/moves/acupressure.js

https://www.smogon.com/forums/threads/acupressure-targeting.3733779/
Technically not 100% accurate, as targetting a fainted slot in gen 4 should be disabled completely, but I think this is fine because there shouldn't be any way to revive an ally between choosing and using the move

Fix Acupressure target resolution

---

server/chat-plugins/scavengers.ts

Add the ability to forcequeue hunts, which disregard empty answers and short hunts.
As requested by Room Owner Computerwizard8800

Scavs: Add a command to forcibly queue hunts 

---

config/formats.ts
data/random-battles/gen8/factory-sets.json
data/random-battles/gen9/factory-sets.json
data/random-battles/gen9/teams.ts
server/chat-plugins/randombattles/index.ts
test/random-battles/all-gens.js

This implements [Gen 9] Battle Factory. The /battlefactory chat command has been update for Gen 9. We are releasing it without LC, but it will be added as soon as practicable. 
The PR also updates the tests to include the [Gen 9] and [Gen 8] Battle Factory data files.
Credits:
Project Leader: Cake
Code and proof-checking sets: livid washed
Consultants:
Ubers: Lasen, OreoSpeedruns, SBPC
OU: Marnie
UU: Lily, haxlolo
RU: Rarelyme
NU: Stories, Lucario
PU: Bella, gulch
Typo checks: Atlas

Implement [Gen 9] Battle Factory

---

data/random-battles/gen9/factory-sets.json

-Choice Scarf Eternatus now actually runs Choice Scarf instead of Power Herb.
-Bulk Up Arceus (Normal) no longer runs Taunt and now always has Recover.
-UU Araquanid no longer runs Trailblaze.
-Amoonguss now has a Bold nature, instead of Timid
-NU Choice item Porygon-Z now no longer runs Agility and instead has the option of Ice Beam (on both Tera Blast and non-Tera Blast) or Thunderbolt (on non-Tera Blast)
-Pokemon with equal Defense and Special Defense now run 4 Special Defense EVs when feasible in RU and NU due to the existence of Download Porygon-Z.

Gen 9 Battle Factory set updates

---

data/mods/gen4/abilities.ts
data/mods/gen5/abilities.ts

Fixes https://www.smogon.com/forums/threads/gen-4-5-frisk-pokemon-is-wrongly-given-as-holder-of-identified-item.3755568/
Client support requires https://github.com/smogon/pokemon-showdown-client/pull/2302

Gen 4-5: Fix target in Frisk message

---

server/chat-plugins/datasearch.ts

Errors are sent as regular text messages, so there's no point in escaping them in HTML.
Also there were two declarations of `escapeHTML`; this yeets one. The only difference was that the one in datasearch (which was just removed) didn't replace `\n` with `<br />`; but I couldn't find a case where this mattered.
```
/nds abc<b>Test</b>
/nds SpD < 100
```
Before:
After:
Thanks @Slayer95 for raising this <3

Datasearch: Don't escape HTML for regular text messages

---

data/random-battles/gen9/teams.ts

BF teamgen restrictions were too lax, allowing for arbitrary number of shared weaknesses if there was a resistance to that type on the team. Now the resistance check only occurs for triple weakness, and more than that simply gets rejected. 
This allows for during-generation rejection, which will remove most instances of failed teamgen, thus not reach maximum depth as often, and making it all faster.

Gen 9 Battle Factory: Enhance team generation restrictions

---

sim/dex-species.ts

Dedup for `Species`.
Similar to #10658. `Species` is a little more complicated so I had to change the checks a bit. 
Draft until we settle on an approach to `deepEquals`.
---
`ret size` == "Retained Size", includes the "graph it retains". So, deep size.
| stage | `DexSpecies` ret size | `Species` ret size | `allMods.species.all()` | total heap size |
| --- | --- | --- | --- | --- |
| baseline | 45325 | 42574 | 670 ms | 256 |
| dedup species | 7038 | 10822 | 1426 ms | 224 |
| use utils.isDeepStrictEqual | 7038 | 10822 | 944 ms | 224 |
52584 -> 13278 instances of `Species`, 32MB peak savings.
It is a little curious how the post-dedup snapshot attributes more of the graph to `Species` than the enclosing `DexSpecies`.
The time to create all species in all mods increased by almost 300 ms.
It …

Sim/`DexSpecies`: Deduplicate `Species` against parent mod

---

config/formats.ts

It'll run from January - April: https://sv-news.pokemon.co.jp/en/page/245.html
This can go live with December's tier shifts.

VGC/BSS: Readd Regulation G

---

sim/team-validator.ts

https://www.smogon.com/forums/threads/bug-report-validator.3754044/
In #9646, I added support for validating Pokemon from Pokemon GO, and with this I decided to move the validateStats check lower to allow for IVs to be altered if needed, but this inadvertently caused the event-related check for Hidden Power type to not work properly. This change fixes this problem by returning validateStats back to where it originally was and remove all non-move related checks of the isFromPokemonGo flag (the stat-related validations, which were moved to validatePokemonGo. The auto-adjusting of IVs for Pokemon with even IVs is removed as a result of this, but I doubt this will have much impact considering how niche this is.

Properly validate Hidden Power type for events

---

data/conditions.ts
data/moves.ts
sim/battle.ts
test/sim/moves/futuresight.js
test/sim/moves/wish.js

Big credit to Anubis for assisting in research and Karthik for help in implementation.
One implementation quirk Showdown has is that we treat Team Preview and everything before the first move selection as "turn 0", instead of everything up to the second move selection as "turn 0" (i.e. the first turn). If that was implemented correctly, we probably wouldn't need the hardcodes we have for things like Burning Jealousy vs Download. However, there's a lot of stuff that looks like it depends on the current turn count implementation, so I didn't touch that and just tossed in some -1s where appropriate.
See discussion of this mechanic starting at this post: https://www.smogon.com/forums/threads/10350377

Implement turn counter overflow with Wish / Future moves

---

data/learnsets.ts
data/random-battles/gen9cap/sets.json

Flamethrower is being removed from Chuggalong per [1]. I have edited learnsets.ts and the random battle set for Chuggalong. I believe these are the only places where Flamethrower is referenced currently, however I could be wrong. I have not changed the tera type for the random-battles set as I believe that goes beyond the scope of this pull request. 
https://www.smogon.com/forums/threads/np-sv-cap-stage-4-fuel-rage-fist-ban-chuggalong-nerf.3755238/#post-10359001

Chuggalong nerf 2

---

config/formats.ts

Bans haven't been publicly announced yet, but I was told to implement this by GSC Doubles' council directly.

GSC Doubles: Ban Bright Powder, Quick Claw, and King's Rock

---

data/mods/gen4/moves.ts

#10734 accidentally overwrote the whole of onPrepareHit for fling in Gen 4, which is necessary for it to function.
Bug report: https://www.smogon.com/forums/threads/bug-report-mechanics.3756216/

Gen 4: Fix fling not working

---

config/formats.ts

Okidogi banned by suspect vote (Proof on 35 Pokes Discord) Rerolled Lokix

Natdex 35 Pokes: Ban Okidogi, unban Lokix

---

config/formats.ts

Jolteon quickbanned by council vote; replaced by Carracosta

Natdex 35 Pokes: Jolteon Ban, Replaced by Carracosta

---

config/formats.ts
data/random-battles/gen1/data.json
data/random-battles/gen2/sets.json
data/random-battles/gen3/sets.json
data/random-battles/gen4/sets.json
data/random-battles/gen5/sets.json
data/random-battles/gen6/sets.json
data/random-battles/gen7/sets.json
data/random-battles/gen7/teams.ts
data/random-battles/gen9/bss-factory-sets.json
data/random-battles/gen9/doubles-sets.json
data/random-battles/gen9/factory-sets.json
data/random-battles/gen9/sets.json
data/random-battles/gen9/teams.ts

Ladder updates discussed with and approved by @KrisXV 
-adds three new ladders: Pick-Your-Team Random Battle (B12P6), Broken Cup, and Random Roulette.
-Removes several old ladders: Gen 8 Hackmons Cup, Gen 7 Hackmons Cup, Gen 8 Battle Factory, Gen 7 Battle Factory, Gen 8 Random Doubles, Gen 8 Free-For-All Rands
-Gen 7 Hackmons Cup is now exclusive to the /challenge command and room tournaments
-Gen 8 Metronome Battle no longer exists (consulted with Ivy)
------- Set changes below this line -------
**Gen 9 Random Battle:**
-Clodsire's sets have been split such that it always has either Toxic or a Poison STAB attack.
-Leavanny now has a second set of Fast Attacker with Sticky Web, Bullet Seed, Knock Off, and Triple Axel with Loaded Dice. Runs Swords Dance if the team already has Sticky Web. …

Randomized format set & ladder updates

---

server/chat-plugins/battlesearch.ts

PCRE lookahead was causing the regex to be pathologically slow.
The lookahead was introduced by #7801 , the purpose of which I (eventually) inferred to be to handle out-of-order player IDs.
I.e., you do `/battlesearch alice, bob` and also want to match battles where p1 was bob and p2 was alice.
---
Cases I've tested: `files with no matches`, and `search 1 ID w/ matches in either slot`, and `search 2 ID w/ matches in either order`.
---
Measured perf on directory with 500K files, 8GB, all non-matches.
Low-end cacheless NVMe SSD.
File cache was cleared each run with `echo 3 | sudo tee /proc/sys/vm/drop_caches`.  
Before: 100% CPU usage, 1MB/s disk read.  
After: 20% CPU usage, 500MB/s disk read.
```
$ rg --version
ripgrep 14.1.1 (rev 4649aa9700)
features:+pcre2 …
```

BattleSearch: Fix pathological regex

---

config/formats.ts

Lokix banned via suspect test (Discord); replaced by Toxicroak.

Natdex 35 Pokes: Update Bans

---

data/rulesets.ts
sim/battle-stream.ts
sim/battle.ts

https://www.smogon.com/forums/threads/make-vgc-bo3-ladder-games-ots-in-replays.3756582/

Always show OTS to spectators

---

config/formats.ts

https://www.smogon.com/forums/threads/sand-veil-in-dpp-lc.3752834/#post-10373970
Implementing Evasion Abilities Clause is functionally the same thing as the bans of Sand Veil and Snow Cloak, so I thought that this would be an equivalent solution that informs battlers in the future.

Gen 4 LC: Add Evasion Abilities Clause

---

server/roomlogs.ts

**Problem**:
Previously, any unexpected DB connection termination resulted in lost logs, since we only retried on `42P01` (table not found). Other transient failures (e.g., “Connection terminated unexpectedly”) were crashlogged without a retry, causing data loss.
**Solution**:
Introduce a bounded retry mechanism (3 attempts) specifically for transient “Connection terminated unexpectedly” errors. After a brief wait, the query is re-run. If retries are exhausted, or if `ignoreFailure` is `true`, the function skips retries and relies on crashlogs as before.
**Benefits**:
- **Preserves Logs**: Prevents loss of log entries due to DB connection drops by retrying the insert.
- **Consistent Recovery Logic**: Extends existing table recreation and retry logic to handle additional transient errors. …

Implement Retries on Transient Roomlog DB Connection Errors

---

config/formats.ts

Recent discoveries have made this clause inaccurate to how the format was played in the IRL tournaments. This should make it accurate??? Confirmed with Shellnuts

Remove "Nintendo Cup 2000 Move Legality" from [Gen 2] Nintendo Cup 2000

---

data/formats-data.ts

These were moved to ND UU in https://github.com/smogon/pokemon-showdown/commit/7d14bef733c8bc42bf67999676668549dab18a35 when they were already banned from ND UU.
Garganacl: https://www.smogon.com/forums/threads/sv-national-dex-uu-stage-2-solar-power-garganacl-manaphy-and-xurkitree-quickbanned.3716024/
Ceruledge: https://www.smogon.com/forums/threads/sv-national-dex-uu-stage-6-1-poltergeist-ceruledge-banned.3734851/

National Dex UU: Update Bans

---

server/chat-plugins/calculator.ts

Previously, `/calculate` would fail to include the correct base prefix (`0x`, `0b`, `0o`) when the result was `0` because the code used a falsy check (`if (result)`). This commit replaces that condition with `if (Number.isFinite(result))`, ensuring zero is properly displayed in the requested base.

Calculator: Fix base prefix logic for zero results

---

server/chat-plugins/datasearch.ts
sim/tools/exhaustive-runner.ts
test/common.js

As of PR #10641, these are no longer necessary - `Dex.mod` and `Dex.forFormat` already call `.includeData()` on the dex.

Remove dead code for Dex initialization

---

server/chat-plugins/trivia/trivia.ts

Discussed with Trivia auth.
Fixes an issue in Number mode where the game fails to end after a specified amount of questions, and fixes a crash caused by ending a game with no participation

Trivia: Fix crash and Number mode game cap

---

server/tournaments/generator-round-robin.ts

This PR fixes a problem where a toolbox was displayed when the remaining opponents were disqualified.
Tested and worked well
Improve #9595

Tournaments: Hide toolbox if opponents got disqualified

---

data/mods/gen4/moves.ts
data/moves.ts
test/TESTS.md
test/sim/moves/assist.js

In Gen 4, Assist, Copycat, and Metronome should never attempt to call moves that would fail due to Gravity or Heal Block being active. More info here: https://www.smogon.com/forums/threads/gen-4-metronome-copycat-assist-pools-should-adjust-based-on-gravity-and-heal-block.3756047/
Since the Metronome code is now modded in gen 4, I cleaned up unnecessary lines from the modern gen code. Also there were characters missing from TESTS.md that bothered me so i added them here too.

Gen 4: Fix Assist/Copycat/Metronome under Gravity/Heal Block

---

tools/team-generation-benchmark.js

This PR addresses [#10644](https://github.com/smogon/pokemon-showdown/issues/10644).
Developers just need to run `node build` to rebuild the `dist` folder whenever the `.ts` files in `sim/` change.
- Add a watch script to rebuild when ``.ts``  files change.
- ``npx tsc --watch`` 
- Convert the script itself to TypeScript & compile it with ``tsc``.
- Convert the script itself to TypeScript & use ``ts-node``  + ``nodemon``.

Tools: reference dist in team-gen-benchmark script

---

sim/battle-actions.ts
test/sim/misc/terastal.js

https://www.smogon.com/forums/threads/tera-bp-bump-and-encore.3757856/
"Using a move with priority (like Bullet Punch) forced via Encore will give the move a Tera BP bump to 60 when it should not. This is presumably because Encore is updating the move's priority mid-turn, but Tera BP should be checking the move's priority in move data, not what the move's current priority is."
I don't believe this introduces any collateral bugs.

Fix Terastallization base power buff for priority moves called by Encore

---

data/abilities.ts
data/mods/gen9dlc1/abilities.ts
test/sim/abilities/protosynthesis.js

Fixes #9469 
Fixes #10155 
Fixes https://www.smogon.com/forums/threads/protosynthesis-should-be-deactiviated-by-cloud-nine.3742163/
I believe this interaction was resolved alongside the Protosynthesis + Neutralizing Gas interaction. In older videos, Cloud Nine wouldn’t suppress Protosynthesis, but now it does.

Fix: Protosynthesis + Cloud Nine interaction

---

sim/battle.ts
test/sim/moves/substitute.js

Fixes #9511
"In Gen 1, if a Pokemon with a Substitute hurts itself due to confusion or Jump Kick/Hi Jump Kick recoil and the target does not have a Substitute there is no damage dealt."
"In Gen 1, if a Pokemon with a Substitute hurts itself due to confusion or Jump Kick/Hi Jump Kick recoil and the target has a Substitute, the target's Substitute takes the damage."
There was a bug because if the confused Pokémon used a self-targeting move, the source was itself, so it always attacked its own substitute. This never happened with crash damage because those moves target the opponent.

Fix: [Gen 1] Substitute + Confusion interaction

---

data/abilities.ts
data/mods/gen8/abilities.ts
test/sim/abilities/protean.js

["If a Protean/Libero Pokemon activates its ability once, switches out, then switches back in while a Neutralizing Gas Pokemon is active, Protean/Libero won't activate even after Neutralizing Gas stops working. This is because Protean/Libero use an event callback to reset the flag, which Neutralizing Gas suppresses."](https://www.smogon.com/forums/threads/protean-libero-switching-in-on-neutralizing-gas-causes-ability-flag-not-to-be-reset.3755469/)

Fix: Protean + Neutralizing Gas interaction

---

data/cg-teams.ts
data/random-battles/gen8/teams.ts
data/random-battles/gen9/teams.ts
pokemon-showdown
sim/battle-stream.ts
sim/prng.ts
sim/tools/exhaustive-runner.ts
sim/tools/multi-random-runner.ts
sim/tools/random-player-ai.ts
sim/tools/runner.ts
test/common.js
test/random-battles/tools.js
test/sim/misc/prng.js
test/sim/misc/state.js
test/sim/moves/thrash.js

This makes it so we no longer need to ad-hoc convert seeds from strings to arrays when we get them from text protocols like the command line or BattleStream's `reseed` command.
It also has the side benefit of making inputlogs very slightly smaller.

PRNGSeed is now a string

---

data/mods/gen9ssb/abilities.ts

Fixed a crash caused by a `TypeError` when the `defender` is `null` in the `Drifting` ability.
**Stack Trace:**
```TS
A battle crashed: TypeError: Cannot read properties of null (reading 'activeTurns')
at Battle.onModifyAtk (/home/ps/main/data/mods/gen9ssb/abilities.ts:1725:18)
at Battle.runEvent (/home/ps/main/sim/battle.ts:845:34)
at Pokemon.getStat (/home/ps/main/sim/pokemon.ts:602:23)
at Battle.onModifyMove (/home/ps/main/data/mods/gen9ssb/moves.ts:6018:16)
at Battle.singleEvent (/home/ps/main/sim/battle.ts:585:25)
at BattleActions.useMoveInner (/home/ps/main/data/mods/gen9ssb/scripts.ts:1308:16)
at BattleActions.useMove (/home/ps/main/sim/battle-actions.ts:386:27)
at BattleActions.runMove (/home/ps/main/data/mods/gen9ssb/scripts.ts:1216:34)
at Battle.runAction …
```

SSB: Fix null reference error in 'Drifting' ability

---

data/mods/gen1/scripts.ts
data/mods/gen7letsgo/scripts.ts
data/mods/gen8bdsp/scripts.ts
sim/global-types.ts

We were modifying some scripts for `gen4` when we noticed that the changes were not propagating to `gen1`. I don't think it makes sense for in-game mods not to inherit on a method-by-method basis (since they are basically a [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph)), and I confirmed that there were no conflicts with `gen1`. Override table:
`gen7letsgo` didn't have any problems because the scripts don't change between `gen9` and `gen7`. However, if a future generation requires overriding some scripts, it will break `gen7letsgo`.

Fix inherit for in-game mods

---

sim/prng.ts

The alternative big-endian read impl is indeed slower. (if you're curious, in a loop it was about 4x slower).
Also, PRNG code currently accounts for very, very little of the execution time for a battle.

PRNG: Remove 'TODO: benchmark' comment

---

sim/team-validator.ts

https://www.smogon.com/forums/threads/bug-report-validator.3759104/
This is something that should've always been in #10574. Setting setSources.babyOnly becomes useless here because it eventually gets set after validating a move is complete.

Fix weird Dream World incompatibilities

---

data/mods/partnersincrime/scripts.ts

Fixes a bug where neutralizing gas doesn't properly suppress shared abilities as seen here https://replay.pokemonshowdown.com/gen9partnersincrime-2293157852

Partners in Crime: Don't activate innates while Neutralizing Gas is up

---

data/abilities.ts

My previous solution https://github.com/smogon/pokemon-showdown/pull/10889 won't work if Terapagos switches out after being hit by Future Sight—for example, if it has an Eject Pack and an Intimidate foe switches in.

Fix Tera Shell + future moves + mid turn switches

---

sim/battle.ts
test/sim/abilities/emergencyexit.js
test/sim/abilities/soulheart.js

In the test `Emergency Exit should request switchout between residual damage`, Volcalith should activate before Sea of Fire. However, `effectOrder` for `Residual` events is not currently implemented. This fix adds `effectOrder` to Slot, Side, and Field conditions for `Residual` events. The test is fixed and unskipped in this PR https://github.com/smogon/pokemon-showdown/pull/10902. That PR applies the same changes to `resolvePriority`.

Fix incorrect tests

---

data/abilities.ts
data/conditions.ts
data/mods/gen9ssb/abilities.ts
data/mods/gen9ssb/conditions.ts
data/mods/gen9ssb/moves.ts
data/mods/littlecolosseum/abilities.ts
data/mods/thecardgame/moves.ts
data/moves.ts
data/text/default.ts

While working on client, I noticed a hardcode for "Snow" as a weather name:
https://github.com/smogon/pokemon-showdown-client/pull/2049/files
PS names condition IDs after the move that inflicts them, with only a few exceptions for conditions not associated with a single move. Weather is not an exception.
PRing in the hope that people remember this in the future. Would be awkward if someone did a `if (weather === 'snow')` or something after this; TypeScript wouldn't catch that.

Snowscape was incorrectly named Snow

---

config/formats.ts

https://www.smogon.com/forums/threads/alphabet-cup.3713049/post-10448662
ban Sceptile
ban Urshifu-Single-Strike
ban Ursaluna
ban Light Clay
unban Regieleki
unban Terapagos
unban Zamazenta
i also reformatted some pokemon to be in alphabetical order:
Deoxys-Attack, Deoxys-Normal, Dialga, Dialga-Origin
Meowscarada, Mewtwo
i also attempted to make the lines be as close to equal length as possible

SV Alphabet Cup bans

---

config/formats.ts

Removed the sandstorm ++ sand rush ban and added -unreleased to the ruleset to disallow hidden abilities that were never released in gen 5

BW Draft: Fix bans

---

config/CUSTOM-RULES.md
config/formats.ts
data/rulesets.ts
sim/dex-formats.ts
test/assert.js
test/common.js
test/random-battles/all-gens.js
test/sim/team-validator/custom-rules.js
test/sim/team-validator/misc.js

Previously, "+All Pokemon" did nothing except override "-All Pokemon", which switched from a default-allow to default-deny system.
They still do that, but they now also override all previous pokemon bans/unbans. This makes it easier to replace a banlist/whitelist from an inherited ruleset without needing to reverse every previous ban/unban.
This also adds an error if you use `+All Pokemon` in a ruleset where it doesn't do anything.
Fixes #10772

Make "All Pokemon" rules more convenient

---

config/formats.ts
data/mods/gen8/rulesets.ts
data/rulesets.ts
server/chat-plugins/datasearch.ts
sim/dex-formats.ts

"Standard NatDex" is very weird compared to how OMs usually work.
See "TierShift Mod" and "Godly Gift Mod". NatDex now gets its own mod, which can be mixed into any other format, instead of needing to start with NatDex.
This would make Min Source Gen overriding annoying, so it now defaults to the current gen in Gen 9+, if Obtainable is set and +Past isn't. So now you don't need to manually set Min Source Gen to enforce Obtainable in Gen 9.

Introduce "NatDex Mod"

---

data/mods/gen1/conditions.ts
data/mods/gen1/moves.ts
data/mods/gen9ssb/scripts.ts
sim/pokemon.ts
sim/side.ts

Supersedes #10924
There's no need for complicated Fight button mechanics, we have to deal with the same thing in newer generations and `maybeDisabled` fully covers it.
Changes:
- `maybeDisabled` (move choices can't be cancelled) is in effect for all turns except the last of a 5-turn Wrap
- Wrap no longer leaks when it's ended
- Wrap no longer misses or consumes PP on turns after the first
- Wrap does the same damage on all turns as the first
- If the foe switches, Wrap ends but the attacker is forced into using Wrap again (with miss chance and deducting PP)
- The text shown is now accurate (no "move failed" and no "pokemon used Wrap" on subsequent Wrap turns)

Fix Gen 1 Wrap

---

server/chat-plugins/datasearch.ts

Implements https://www.smogon.com/forums/threads/add-aliases-for-learn-to-match-up-with-ds-for-past-gen-searches.3667766/
Adds new generation aliases to /learn to bring it in line with other datasearch commands. Retains support for old generation prefix aliases.

Add Number Generation Aliases to /learn

---

server/chat-plugins/datasearch.ts

Implemented the duplicate suggestions: https://www.smogon.com/forums/threads/allow-ds-to-search-for-pokemon-above-below-a-tier.3675711/ and https://www.smogon.com/forums/threads/allow-use-of-for-tiers-in-dexsearch.3679995/
A user can use `/ds tier > ou` to see all mons in singles formats higher than OU. Similarly a user can use `/ds tier <= duu` to see all mons in doubles formats DUU or lower. 
CAP is treated as part of the singles tiering structure as equivalent to OU, CAP NFE to NFE, and CAP LC to LC. CAP mons will be excluded from results unless a CAP tier is specified in the inequality such as in `/ds tier <= capnfe` which will show all mons available in CAP NFE or lower (CAP NFE, NFE, CAP LC, and LC).

Implement searching for tiers by inequality to /ds

---

server/chat-plugins/datasearch.ts

Implements the suggestion: https://www.smogon.com/forums/threads/ms-trap.3674078/
Adds `trapped` as a volatilestatus option which shows all of the non-`partiallytrapped` trapping moves which users would expect to find. The parameter `trap` or `trapping` will join the two together to show all moves which inflict either `trapped` or `partiallytrapped`. This also fixes G-Max Sandblast and G-Max Centiferno not showing up alongside the other `partiallytrapped` moves.

Movesearch Trap

---

sim/battle.ts
sim/pokemon.ts
test/sim/misc/statuses.js

In Gens 2-4, if a pokemon with the freeze condition faints when switching out from pursuit, the status condition remains and freeze clause is triggered by subsequent freezes.
https://www.smogon.com/forums/threads/pursuit-and-freeze-clause-mod.3759630/
I added a simple clearing of a pokemon's status condition upon fainting from pursuit when switching out. Namely, `action.pokemon.status = '';`. The `clearStatus` and `setStatus` methods were not used due to their requirement of a pokemon having HP, which was not applicable in this case.

Fix freeze lingering after fainting from  pursuit on switch out

---

config/formats.ts

Should allow Floette-E, Berserk Gene, Eternatus-Emax, and the like into the Draft formats

Allow Illegal Pokemon into National Dex Draft formats

---

server/chat-commands/avatars.tsx

Depends on https://github.com/smogon/pokemon-showdown-client/pull/2335
Server end of implementing the suggestion: https://www.smogon.com/forums/threads/avatar-avatar-to-be-broadcastable-showing-the-avatar-sprite-and-the-credit.3759095/
Allows users to broadcast with the avatar command with '!' which will display the corresponding avatar in the chat with credits if applicable. This will not set the user's avatar, only using the command with the '/' prefix will do such.

Allow Users to Broadcast !avatar

---

server/chat-plugins/datasearch.ts
test/server/chat-plugins/datasearch.js

Implements the suggestion [Add (metagame) rule functionality to /ds](https://www.smogon.com/forums/threads/add-metagame-rule-functionality-to-ds.3761436/) which I was asked about a few days ago.
Provides support for most applicable metagame rules except for convergence. Users can use the command as `/ds rule=alphabetcupmovelegality, v-create` and recieve a list of Pokemon which learn V-Create under that format. Similarily users can use other rule parameters to sort mons by their modified stats in a given metagame, or to see the list of mons provided by the format block lists/allow lists.

/ds: Add rule functionality

---

config/formats.ts

Finalized Gen5 Draft rulset will include a ban on Sand Stream with Sand Rush on the same team.

[Gen 5] Draft: Ban Sand Stream ++ Sand Rush

---

config/formats.ts

- Added a 'Baton Pass + Salac Berry' ban, which was always intended to be included but was missed
- Unbanned Sand Veil and Soundproof, which are bans carried over from OU which should not apply to UUBL

ADV UUBL: Update bans

---

data/learnsets.ts

Added:
- Keldeo https://projectpokemon.org/home/files/file/5605-swsh-dex-completion-shiny-keldeo/
- Meltan: https://projectpokemon.org/home/files/file/5606-lgpe-dex-completion-shiny-meltan/
~~Updated:~~
~~- Enamorus (missing Crunch): https://projectpokemon.org/home/files/file/5579-pla-dex-completion-shiny-enamorus/~~
Should be an easy change but sanity check my work please.

Add missing HOME dex completion gifts

---

config/formats.ts

Update to the national dex 35 pokes format to include the pokemon which will be usable for the month of April 2025. The graphic containing the pokemon list is attached as proof, and will be posted to [this]( https://www.smogon.com/forums/threads/35-pokes-march-2025.3749375/) Smogon thread at midnight GMT+0 on April 1st.

April 2025 35 Pokes Update

---

server/chat-plugins/datasearch.ts

Alpha order is a sensible default but I think ppl should have this option too

Dexsearch: Allow sorting by Pokedex number

---

data/formats-data.ts

Ursaring and Gurdurr did not see an average of 4.52% usage in ZU across January, February, and March. Hattrem did. 
Ursaring: (2.02 + 3.21 + 6.36) / 3 = 3.87 < 4.52
Gurdurr: (1.77 + 6.52 + 4.56) / 3 = 4.26 < 4.52
Hattrem: (8.22 + 9.41 + 2.91) / 3 = 6.85 > 4.52
https://www.smogon.com/stats/2025-01/gen9zu-1630.txt https://www.smogon.com/stats/2025-02/gen9zu-1630.txt https://www.smogon.com/stats/2025-03/gen9zu-1630.txt

ZU NFE fixes.ts

---

data/mods/gen9ssb/scripts.ts
sim/side.ts

https://www.smogon.com/forums/threads/megax-megay-choice-options-dont-reflect-in-input-log.3762703/

Ensure `megax` and `megay` actions show up in inputlog

---

server/chat-plugins/datasearch.ts

Implements [Improve how !ds all displays](https://www.smogon.com/forums/threads/improve-how-ds-all-displays.3654308/)
Requires the client-side changes from [this PR](https://github.com/smogon/pokemon-showdown-client/pull/2338) 
Replaces the `all` parameter and the restriction on broadcasting datasearches with the ability to expand and collapse the results of a datasearch over the 30 item limit by clicking it. Subtle button text and the pointer cursor while hovering the results are to make it clear to users that they can interact with the results. The results will not expand or collapse when clicking a link in the results. This would have been implemented using the existing readmore option which uses the `<details><summary>` tags with an inline display, but Chrome creates a linebreak after …

Collapsible Datasearches

---

data/formats-data.ts

Hattrem ended up there as a result of https://github.com/smogon/pokemon-showdown/pull/11009

Remove Hattrem from nd zu and doubles zu

---

server/chat-plugins/datasearch.ts
test/server/chat-plugins/datasearch.js

https://www.smogon.com/forums/threads/please-keep-the-dexsearch-or-ds-search-parameter-all-as-it-was.3762947/
Updates the behaviour of the collapsible datasearch results when using `/` commands to allow for the `all` parameter to expand it by default rather than always starting collapsed. When broadcast with `!`, the results will remain collapsed by default even when using `all` as a parameter.
Removes the `canAll` param from tests and adds tests for ensuring the results are properly collapsed/expanded when broadcast with `all` and when used as a `/` command with `all`.
This PR also fixes the bug with `randpoke` so I will be closing https://github.com/smogon/pokemon-showdown/pull/11019

/ds: Param to expand collapsible datasearches by default

---

server/chat-plugins/room-faqs.ts

_Accidentally closed this last time_
refer https://www.smogon.com/forums/threads/increase-the-htmlfaq-character-limit-currently-8-192.3761841/
Felucia mentioned for most html commands the limit is 100000,
i think 100000 is too much for /addhtmlfaq, i dont know if they mistyped an extra 0 or they actually meant to keep 100000 limit for /addhtmlfaq as well
anyways, i kept it 10000 we can change it to 100000 anytime we want

Change /addhtmlfaq character limit (currently 8,192) to 10000

---

server/chat-plugins/mafia.ts

Let hosts be able to change the playercap after closing signups, to ensure they can add players. 
Give hosts a warning when adding players while the playercap is reached.

Mafia: Update playercap

---

data/mods/gen5/conditions.ts

https://www.smogon.com/forums/threads/old-gens-partial-trapping-status-doesnt-disappear-when-user-switches-out.3756824/

Old gens: Fix partial trapping status not disappearing

---

data/mods/gen2/scripts.ts
test/sim/moves/lockon.js

Addresses #10983 
I shifted the code that compared Pokémon levels for OHKO moves to be before checking for accuracy, so now OHKO moves should fail regardless of Lock-On.

Fix bug letting Gen-2 OHKO moves skip level check

---

server/chat-commands/moderation.ts

https://www.smogon.com/forums/threads/clarification-on-how-long-a-ban-lasts.3761482/ 
2 day bans do not say the amount of time which can be confusing to new users as they think a room ban is permanent. This commit does so without influencing week room ban text logs which already do note the 1 week time limit. This is an approved suggestion on the forums as well.

Moderation: Clarify duration of default roombans

---

server/chat-commands/info.ts

Replace outdated (like, since XY outdated) links with current links.
I don't *love* dumping users at the Smogon Metagames forum, but there is no where else I am aware of that has all of our formats listed out.
Also updated the description to explain how /tier works and explain what type of information it contains.

Info: Update /tier Command

---

config/formats.ts

Dexited Pokemon were not allowed for some reason, this is a work around.

NatDex BH: Fix Legalities

---

server/chat-plugins/teams.ts

Teams will OK any nickname that passes the OM filter, which means you can put fun things as unicode as the check will ignore it as long as there's a valid pokemon/item/ability/etc. in the nickname
~~<sub>Yes I already put the entire bee movie script in there as a result of this exploit</sub>~~

Teams: Sanitize OM Nicknames

---

data/mods/gen8bdsp/formats-data.ts

I had forgotten to move Sandslash and Torkoal to PU in my other PR.

BDSP: Fix NU-PU banlist

---

data/mods/gen3rs/learnsets.ts

It seems as though we forgot to do this in the first PR.

[Gen 3] ADV 200: Re-add Wish Bagon event

---

config/formats.ts

Added at request of PS user FrankMarley and other players who play ADV 200 and mirrors the same Baton Pass regulations as in Gen 3 OU

[Gen 3] ADV 200: Implement One Boost Passer Clause

---

data/random-battles/gen9/teams.ts

This rewrites the item generation code to refer to `moves.size` instead of assuming the set has 4 moves, ensuring that more appropriate items are generated when the max moveset size is modified.
Also, removes a couple sections of code rendered obsolete due to set updates.

 Improve Random Battles handing of >4 moves

---

sim/battle.ts
sim/side.ts
test/server/room-battle.js

Fixes #8546
Requests are currently sent before the turn update is sent. Specifically, you might expect something like:
|move|SCIZOR|U-turn
|request|switch|SCIZOR
but instead it's
|request|switch|SCIZOR
|move|SCIZOR|U-turn
Which is pretty annoying for many consumers. So this fixes that.
Another nice consequence of delaying sending requests, is that redundant requests are not sent if you send in an inputlog all at once; only the most recent request (that the inputlog doesn't already choose for) will get sent out.

Sim: Emit requests after updates

---

config/formats.ts
data/mods/ccapm2024/formats-data.ts
data/mods/ccapm2024/pokedex.ts
data/rulesets.ts

Pet Mods requested the 'Data Mod' that automatically shows information for formats that have many custom changes (currently CCAPM2024 Random Battle). This would help people get acquainted to new Pokemon in formats that introduce many changes. Tagging @Yoshiblaze for confirmation
The rule displays basic Pokemon information on switch-in and upon an Illusion being broken.
Additionally, it fixes a small error where Pokemon from CCAPM2024 did not show up in "/ds" due to it not having a format-data.ts file. This has now been added, with all normal Pokemon (that cannot show up) as illegal, such that "/randpoke mod=ccapm2024" will always show a Pokemon from this format.

Add rule to automatically display Pokemon information

---

server/chat-commands/info.ts

https://www.smogon.com/forums/threads/clean-up-update-error-message-for-faq.3764560/  !faq fails no longer send the failed message message in chat, this is very helpful for room auth who are the users of broadcast commands For whatever reason '!faq all' fails used a replybox? I can't think of a single non dev command that uses visible replyboxes in chat for fails, so changed this for an errorReply. I cleaned up the wording of the /help faq, and I added some topics that were not there previously. Run Broadcast is called for later in the code to fix the issue of !faq sending messages regardless of it being valid or invalid, since fails aren't checked properly before the broadcast is actually sent.

Commands: Update help FAQ and improve !faq fails

---

server/chat-plugins/helptickets.ts

Nitpick; the button to check out a text ticket shows as "Claim" when someone else is already looking at the ticket or it is already closed, which doesn't really make sense.

Fix claim button text for text tickets

---

server/chat-commands/info.ts
sim/dex-abilities.ts
sim/dex-data.ts
sim/dex-formats.ts
sim/dex-items.ts
sim/dex-moves.ts
sim/dex-species.ts
sim/dex.ts
test/sim/data.js

The teambuilder is already good at fuzzy matching, but a lot of users are requesting aliases that the teambuilder's fuzzy matches already support. I assume this is for `/dt` and similar commands, so I'm just going to bring the teambuilder's fuzzy matching into `/dt`.
Note that this is still stricter than teambuilder, because teambuilder is a prefix search, while this is a full match. This can match `tt`, `ttar`, and `tar`, but teambuilder will also match `ty`, `tyr`, `tyra` etc.

Support fuzzy searching /dt etc

---

data/items.ts
sim/dex-conditions.ts
test/sim/items/whiteherb.js

Fixes https://www.smogon.com/forums/threads/bug-report-ladder.3765412/
White Herb shouldn't activate on boost changes; it should activate based on negative boosts. This fixes issues with effects like Costar, Topsy-Turvy and Psych Up. I'll just check whether Eject Pack activates with Coaster or not.
Edit: Eject Pack does **_NOT_** activate after Costar copies negative boosts. This is ready for review.

Refactor White Herb activation

---

server/chat-commands/moderation.ts

Sends an event to the bot of a bot HTML page when a user closes it. Follows the same syntax as `|requestpage|`, which is run when reconnecting to one.
Smogon Suggestion (Approved): https://www.smogon.com/forums/threads/send-an-event-on-bot-created-htmlroom-close.3694884/

Pages: Notify bots when a user leaves a bot page

---

server/room-battle.ts

This reverts to the old behavior for mid-turn requests.
See: https://www.smogon.com/forums/threads/change-pokemon-fainting-end-of-turn-timer-mechanics.3765251/

Fix timer for mid-turn requests

---

data/mods/gen4/abilities.ts
data/mods/gen5/moves.ts
test/sim/moves/chatter.js

https://www.smogon.com/forums/threads/old-gen-chatter-secondary-effect-weirdness.3753441/
> - [Gen 4] Chatter's confusion chance should not be boosted by Serene Grace
> - [Gen 5] Chatter should still be boosted by Sheer Force when used by a Pokemon other than Chatot, even though there is a 0% confusion chance

Fix Chatter's old gen mechanics

---

config/formats.ts
data/mods/gen8dlc1/formats-data.ts

Current implementation of the format is just DLC 2 NDAG, this PR removes the DLC 2 changes:

Fix [Gen 8 DLC 1] National Dex AG Legalities

---

data/random-battles/gen1/data.json
data/random-battles/gen4/teams.ts
data/random-battles/gen9baby/sets.json

This updates a few sets in Gen 1 Random Battle:
- Pikachu no longer has Thunder as a possible 4th move
- Nidoking will always have Thunderbolt
- Tentacool no longer rolls Barrier and can now obtain Substitute
- Gastly, Haunter, and Gengar will always have Psychic
- Tangela no longer runs Growth
- Seadra can now roll Rest as a possible 4th move
- Starmie will always have Thunder Wave
Also, fixes two small oversights in https://github.com/smogon/pokemon-showdown/pull/11156: Wooper-Paldea will always have Poison STAB in Gen 9 Baby Random Battle, and Honchkrow no longer gets Choice Band in Gen 4 Random Battle.

Gen 1 Random Battle updates

---

data/abilities.ts
data/mods/gen5/abilities.ts
sim/battle.ts
test/sim/abilities/magicbounce.js

https://www.smogon.com/forums/threads/multiple-magic-bounce-with-hazards-in-ffa.3751449/
~Activation based on unmodified speed is still not implemented, but I've left a skipped test for it. This will require an overhaul of the events that use unmodified speed.~

Fix Magic Bounce in Free-For-All battles

---

data/mods/gen9ssb/abilities.ts

Fixes a crash in the gen9ssb mod where the Hot Pursuit ability would throw a TypeError when trying to access properties of an undefined Pokémon.

SSB: Fix crash when Hot Pursuit triggers with no foes

---

config/formats.ts
data/mods/gen9fe/scripts.ts

Type signature of runImmunity was different than it should be, causing variables to have unexpected types.

Fix Fusion Evolution Random Battle

---

server/chat-plugins/othermetas.ts

Adds a `/bnb` command in othermetas.ts to show a Pokemon's Bad 'n Boosted stats, now that Bad 'n Boosted is in the Challengeable OMs section / is an OM. The command is comparable to many other OM commands, such as `/scale`, `/ts`, `/350`, and `/reevo`.

Bad 'n Boosted Data Command

---

data/mods/thecardgame/scripts.ts
sim/dex-data.ts
test/sim/dex.js

This PR fixes a crash that occurs during battles in The Card Game mod when checking type immunities.

Dex-Data: Prevent isName crash on non-string args

---

server/chat-plugins/chatlog.ts

Currently crashes with `Invalid date`, my PR makes it crash with `This functionality is currently disabled.`
@mia-pi-git any chance you could implement searchlogs at some point? The people crave knowledge (the people being me)

Return the right error on /searchlog

---

data/mods/gen9fe/abilities.ts

Fixes a DataCloneError that caused battles to crash when moves with `onHit` functions (like Anchor Shot) were used against Pokémon with the Serene Sync ability.
The Serene Sync ability tries to copy secondary effects to also apply to the attacker. However, it was using `structuredClone()` which cannot clone functions, causing a DataCloneError when moves had `onHit` callbacks.
Replaced `structuredClone()` with manual property copying that preserves functions by reference. The ability now explicitly copies effect properties (onHit, boosts, status, etc.) while excluding meta properties like 'self' and 'chance'.
Tested with various moves including:
- Anchor Shot (onHit that adds trapped volatile) - previously crashed, now works
- Moves with stat drops, status effects, and self-boosts - all …

Gen9FE: Fix Serene Sync crash with onHit effects

---

server/chat-plugins/mafia.ts

This happened because the code used `roles.shift()!` with a non-null assertion operator, assuming there would always be enough roles. When the roles array was exhausted, `shift()` would return `undefined`, causing the crash when trying to access `role.safeName`.
Added validation to ensure there are enough roles for all players before attempting distribution. The fix:
1. Checks if `roles.length < this.players.length` and throws a clear error message if insufficient
2. Removes the unsafe non-null assertion operator from `roles.shift()!`
3. Adds a runtime check to handle the edge case where `shift()` returns undefined

Mafia: Fix crash when distributing roles with insufficient roles

---

server/chat-plugins/mafia.ts

Today, a bug was found where using revealas on a long role crashed PS!
I alleviated this by adding a maximum role length (instead of having it be uncapped, as currently people could spam PS using unlimited length roles) and moving the 'infinite loop' check to not be triggered by long roles.
This was implemented in both setroles and revealas.

Mafia: add maximum role length.

---

server/chat-plugins/datasearch.ts

Adds an option to sort by (doubles) tier in `/ds`.
Adds tiers for LC/NFE in doubles and Illegal as a whole so those Pokemon can be sorted.
Change approved from suggestions forum: https://www.smogon.com/forums/threads/sorting-by-tier-in-ds.3765667/

/ds: add sorting by (doubles) tier

---

config/formats.ts
sim/pokemon.ts

Client PR: https://github.com/smogon/pokemon-showdown-client/pull/2463
___
The change to `Math.ceil(100 * this.hp / this.maxhp)` fixes [HP Percentage mod inaccuracies](https://www.smogon.com/forums/threads/hp-percentage-mod-inaccuracies.3746113/) caused by floating-point imprecision.
___
In Generations 1–4, pixels are used to determine the HP bar color. Only in Generations 5 and later is the actual HP value used.
While in Gen 2, 24 pixels should be green (and in Gen 1, the bar should be yellow until 27 pixels), these details do not reveal additional information and could therefore be implemented on the client side if there is motivation to do so.
Gen 5 original post: https://www.smogon.com/forums/threads/hp-bar-colours.3481364/
@Marty-D 's work (can be confirmed in the projects by this …

Fix HP bar percentages and colours

---

server/chat-plugins/permalocks.ts

The notice "x submitted a perma nomination for y" is added to the room but doesn't show up right away. Adding an `update()` fixes this.

Permalock plugin: Fix room not updating after notice

---

data/formats-data.ts

Hisuian Sneasel had >4.52% average usage in ZU in the last three months just like Dipplin, Hattrem, Magneton, and Primeape. Porygon2 also had >4.52% average usage in ZU and was ZU before it moved to NU, so it moves back to ZU. 
Hisuian Sneasel stats
https://www.smogon.com/stats/2025-04/gen9zu-1630.txt - 5.14% https://www.smogon.com/stats/2025-05/gen9zu-1630.txt - 8.72% https://www.smogon.com/stats/2025-06/gen9zu-1630.txt - 8.57% Average: 7.48%
Porygon2 stats
https://www.smogon.com/stats/2025-01/gen9zu-1630.txt - 10.03% https://www.smogon.com/stats/2025-02/gen9zu-1630.txt - 9.35% https://www.smogon.com/stats/2025-03/gen9zu-1630.txt - 13.80% Average: 11.15%

Fix ZU NFEs

---

data/mods/gen2/formats-data.ts

https://www.smogon.com/forums/threads/zu-old-gens-hub-oras-bans-379.3646944/post-10502838 Both Diglett and Slowpoke are D rank on the most recent ZU viability list, the same as other Pokemon tiered as LC like Smoochum, Snubbull, Mankey, etc, so they should be tiered the same.

Corrections for low-rank GSC ZU NFEs/LCs (Diglett + Slowpoke)

---

data/formats-data.ts
test/sim/team-validator/misc.js

Sneasel-Hisui is erroneously legal after a recent tiering change, which has happened before (Hattrem).
I propose a test that would prevent this from happening.
I will add the fix for Sneasel-Hisui in a bit, after seeing that the test catches it.

Add test for 35 Pokes banlist

---

build
package.json

- Errors in the node build script will no longer cause a false perception that dependencies cannot be installed.
- Simplifies 1cea3f39cbb41c2a06838580c47450d8d76b9e99

Remove build on postinstall

---

server/chat-plugins/datasearch.ts

Removed parameters that do nothing (instruct, mimic), changed ssb examples (they were obsolete), added a couple more things. Would love to make the wall of mods you can use with both ds and ms smaller, since a lot of those don't actually change their behaviour, like randomroulette, but I'm not sure how to approach it. A hardcoded list of mods that change things is an option.

Minor changes to the help boxes of /ds and /ms

---

test/sim/items/sitrusberry.js

This stems from a potentially incorrect bug report https://www.smogon.com/forums/threads/bug-report-mechanics.3763858/
I would like someone to confirm whether the current behavior is correct. The change was implemented here https://github.com/smogon/pokemon-showdown/pull/8307

Add test for Gen 3 berries

---

server/chat-commands/info.ts

Fixes a crash in the `/makecustomchallenge` command that occurs when the command is invoked manually without all expected parameters.

Info: Prevent crash in makecustomchallenge when user parameter is mis… 

---

data/mods/gen7/moves.ts

https://github.com/smogon/pokemon-showdown/pull/10766#issuecomment-2606193048
> Healing Wish and Lunar Dance need their onSwitchInPriority updated in the Gen 7 mod to match Gen 9

Fix Healing Wish and Lunar Dance switch in priority in Gen 7

---

server/chat.ts

On preact client
- if an user uses `/idle` it updates the user's state client side and on every user state update it is made to send `/cmd rooms` to server which then immediately marks the user as active
On old client
- when roomslist page is **opened**, it sends '/cmd rooms' command every 20 seconds which also marks the user active
To fix this, we prevent '/cmd rooms' from updating the user's away/unaway status.

Don't consider user active on '/cmd rooms'

---

data/mods/gen1/conditions.ts
data/mods/gen1/scripts.ts
test/sim/moves/hyperbeam.js

Fixes a bug from #10967 that was brought to my attention by a user.
Unfortunately, we have to manually restore PP in the case of a two-turn move. We can't deduct PP after the move is used, or moves that change your move slots—like Transform or Mimic—will never have their PP deducted.
And yeah, I keep moving logic from `scripts.ts` into each effect with every Gen 1 PR.

Fix Transform and Mimic PP in Gen 1

---

server/room-battle.ts
server/rooms.ts

The same password is now used across all `/savereplay`s in a battle so replay links now don't get broken just because someone saved the replay after you.

/savereplay: Stop re-generating passwords

---

config/config-example.js
server/artemis/local.ts
server/artemis/remote.ts
server/chat-plugins/battlesearch.ts
server/chat-plugins/datasearch.ts
server/chat.ts
server/config-loader.ts
server/friends.ts
server/index.ts
server/modlog/index.ts
server/private-messages/index.ts
server/room-battle.ts
server/sockets.ts
server/team-validator-async.ts
server/verifier.ts

- ``Config.validatorprocesses = 0;`` and ``Config.verifierprocesses = 0;`` were broken due to redundant spawn in ``server/index.ts``.
- The following config keys were using default semantics based on OR-short-circuiting, which prevented ``0`` from being used:
```js
Config.localartemisprocesses;
Config.remoteartemisprocesses;
Config.chatdbprocesses;
Config.friendsprocesses;
Config.modlogprocesses;
Config.pmprocesses;
```

Support running PS in a single process again

---

sim/team-validator.ts
test/sim/team-validator/misc.js

Implements mechanics based on the following bug reports: [1](https://www.smogon.com/forums/threads/home-move-relearner.3736649/) [2](https://www.smogon.com/forums/threads/sv-should-allow-low-level-move-learns-from-past-gens.3737265/)
This should allow Pokemon transferred from SM/USUM or SWSH to retain their moves when transferred to SV, as long as it can learn the moves in some way in SV. This does not fully implement relearner mechanics, as doing so would also require moves from BDSP and LA, the latter of which is currently not in PS's data at all.

Allow past gen moves to be learned via HOME relearner

---

data/mods/gen8bdsp/items.ts

https://github.com/smogon/pokemon-showdown/commit/e8ec5d2c61ff4142f7b82d7912774d3cdbed2dd8
Is there a reason to have this code?

Remove BDSP Eject Button inheritance

---

config/formats.ts

https://www.smogon.com/forums/threads/stabmons.3710577/post-10689783
Restricts:
Torch Song
Esper Wing
While the post itself says Torch Song and Esper Wing are "banned", I have confirmed with pannu on Discord in the Other Metagames server that they actually meant "restricted".
https://discord.com/channels/262990512636559362/542135729686577153/1411797389769052181

STABmons: Update restrictions

---

data/mods/gen3/moves.ts
data/mods/gen4/moves.ts
test/sim/moves/conversion2.js

https://www.smogon.com/forums/threads/conversion2-should-treat-struggle-as-a-normal-type-move-in-gens-2-4.3769245/
In Gen 2-4, Conversion2 treated Struggle as a Normal-type move.
In Gen 2-3, Conversion2 could select a type that the user already had.

Fix Conversion2 in Gens 3 and 4

---

server/ip-tools.ts
test/server/ip-tools.js

A CIDR range should accept any IP in the range and mask the same bits. For example, the range `10.69.42.0/8` should be exactly equivalent to `10.0.0.0/8`. It was instead being incorrectly parsed as `10.69.42.0-11.69.42.0`.

IPTools: Fix CIDR implementation

---

data/mods/gen1/conditions.ts

Credits to a user (who I'm not sure wants to remain private).
> partially trapped pokemon cannot be fully paralyzed/suffer from confusion self hit etc
> binding has high priority and is the 3rd thing checked after sleep and freeze status
> and the trapped pokemons turn ends immediately so no further checks of para/confusion/etc apply
> https://github.com/pret/pokered/blob/master/engine/battle/core.asm#L3326

Fix the priority of the Partial Trapping check in Gen 1

---

config/formats.ts
data/rulesets.ts
sim/dex-formats.ts
sim/side.ts

Fixes Terastal Crescendo, and also adds support for VGC 2010's bring 4 pick 2 restricteds. Similar to `checkCanLearn`, only one `onChooseTeam` can be active at a time to prevent conflicts on auto choose.

Add onChooseTeam event for formats

---

config/formats.ts
data/abilities.ts
data/mods/gen8/abilities.ts
data/mods/gen9ssb/scripts.ts
sim/battle-actions.ts
sim/pokemon.ts
test/sim/abilities/trace.js
test/sim/misc/fainted-forme-regression.js

https://www.smogon.com/forums/threads/trace-triggers-new-ability-twice.3772080/
I know this specific bug could be fixed by adding a condition to Trace's `Update`, but this is a refactor I did in another PR for Neutralizing Gas. This refactor clears the ability and item states when the Pokémon switches out. From what I've seen, the only ability that needs to retain its state is Zero to Hero.
The logic is all in `sim/battle-actions.ts`, the rest are tests and code that we can simplify.
Also tagging @pyuk-bot

Fix Trace activating twice
