smogon/pokemon-showdown

sim/team-validator.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9404465
I only found one place where this change is relevant but there could be more that I am missing.
=> Implement new Ability Patch mechanic

data/pokedex.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9407257
=> Fix Brute Bonnet base HP stat

sim/battle-actions.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9407215
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9407637
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9407717
=> Fix sourceEffect for switches not getting passed to user

sim/pokemon.ts, test/sim/moves/shedtail.js, test/sim/moves/transform.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9409227
=> Fix Transform copying Terastallization

data/abilities.ts, data/items.ts, data/mods/gen7/abilities.ts, data/mods/joltemons/abilities.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9409414
=> Fix Moody stat drops being blocked by Clear Amulet

sim/team-validator.ts, test/sim/team-validator.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9410059
=> Gen 2: Fix traded-back events for Gen 2 evos

data/conditions.ts, data/moves.ts, sim/battle-actions.ts, sim/pokemon.ts, test/sim/moves/ragefist.js
[Bug Report](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9407560)
Rage Fist:
*  Status moves now do not increase Rage Fist BP
*  Capping BP at 350
* Should now work with transform (`timesAttacked` should be inherited)
=> Fix Rage Fist bugs

data/moves.ts, sim/pokemon.ts, test/sim/moves/roost.js
https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9403448
=> Fix Flying Tera Type Pokemon using Roost

sim/team-validator.ts, test/sim/team-validator.js
https://github.com/smogon/pokemon-showdown/projects/3#card-85718928
=> Fix Dream World move exclusivity

data/conditions.ts, sim/battle-actions.ts, sim/pokemon.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9409834
=> Fix types sent when a Terastallized Pokemon switches in

data/abilities.ts, sim/pokemon.ts
- Factor in stat boosts/drops when determining stat to boost
- Mark abilities as Permanent
=> Protosynthesis/Quark Drive fixes

data/rulesets.ts, server/chat-plugins/othermetas.ts
Re-evolution mod, /showevo and /reevo now check for the base species to not lose track of the pre-evolution after changing forms, /showevo now also shows the stats changes a battle form gives.
=> Re-Evolution: Add functionality for battle-only formes

data/abilities.ts, package.json
Ability rankings were updated to provide actual more-than-provisional ratings for new abilities and also to assist in the intended function of the upcoming Gen 9 Random Battle.
=> Ability ranking updates

sim/battle.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9420655
=> Remove Terastallization on faint

data/moves.ts, data/text/moves.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9416940
=> Fix descriptions of crit moves from PLA

data/moves.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9418556
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9417534
=> Salt Cure's effect should be a Secondary effect

data/abilities.ts, data/mods/gen8/moves.ts, data/moves.ts, data/text/abilities.ts, data/text/moves.ts
- Implements the new charge mechanic of only wearing off for Electric moves
- Activates Wind Rider on switch in (should supersede #9112, as I also fixed that Wind Rider didn't show the ability activation message)
=> Fixes for Charge/Wind abilities

sim/battle-actions.ts, test/sim/abilities/berserk.js
As suggested by: [Dragon Darts and Berserk](https://github.com/smogon/pokemon-showdown/projects/3#card-61614678)
Wow, this one was quite tricky to find.
=> Fix interaction of Dragon Darts and Berserk

server/chat-plugins/poll.ts
This commit allows users to escape separators in polls. Approved [on the forums](https://www.smogon.com/forums/threads/allow-users-to-escape-separators-in-polls.3709730/#post-9412630)
=> Polls: Allow escaping separators

server/chat-commands/info.ts
Reported here: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9408443
=> /statcalc: Check for Pokemon before IVs

data/mods/gen1/scripts.ts, data/mods/gen1stadium/scripts.ts, test/sim/moves/counter.js
A bit of an oopsie with the last Counter patch, now Metronome calling Counter should fail for real.
https://github.com/smogon/pokemon-showdown/pull/9136 was the previous patch
=> Gen 1: Actually fix Metronome calling Counter

config/formats.ts
Approved by Smogon Doubles tier leaders
=> Add Doubles Ubers ladder

sim/battle-actions.ts, test/sim/abilities/dancer.js
This seems to be causing problems worse than what it was trying to fix. I recommend reverting while I come up with a better fix.
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-98
This reverts commit 95d1b924274b1c619de582447edb9847670359f1.
=> Revert "Fix Copycat Dancer interaction (#9155)"

data/random-sets.json, data/random-teams.ts
straight up people will not stop complaining about it after one day of existing even though it's not actually bad
=> Random Battles: Reduce Corrosion Glimmora

data/moves.ts, data/text/moves.ts
The amount of damage the user of Shed Tail takes is 50% of its max hp rounded up.
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9436537
=> Fix Shed Tail rounding down

server/chat-plugins/datasearch.ts, test/server/chat-plugins/datasearch.js
https://www.smogon.com/forums/threads/dexsearch-should-show-extra-forms-if-a-sort-is-used.3709971/
=> Datasearch: Show formes if sorted

sim/pokemon.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9436414
=> Fix Abilities not reactivating after a forme change

data/mods/gen3/formats-data.ts
https://discord.com/channels/294651453279174656/763038340664524840/1051853737418817676
=> Gen3 Random Battles: Update movepools

data/mods/gen7/formats-data.ts, data/mods/gen7/random-teams.ts
-Various move updates
-Fix Pheromosa not getting U-Turn
Approved by Rands Staff, all the changes here had 1 or fewer "no" votes
=> Gen 7 Random Battle Updates

data/mods/gen1/random-teams.ts
https://discord.com/channels/294651453279174656/809413397840920586/1037052464865755197
=> Gen1 Random Battles: Make Ditto level 100

config/formats.ts
=> Update Challenge Cup rulesets

data/mods/gen4/moves.ts, test/sim/moves/brickbreak.js
https://github.com/smogon/pokemon-showdown/projects/3#card-61615516
This is my first time contributing to an open source project, please let me know if I've made any mistakes
=> Gen 4: Ensure Brick Break breaks screens of immune targets

sim/battle-actions.ts, sim/battle.ts, sim/pokemon.ts
Client Side: smogon/pokemon-showdown-client#2053
=> Stop sending -typechange for Terastallization

sim/battle-actions.ts, test/sim/abilities/serenegrace.js
https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9438575
=> Gen IX: Remove secondary stat chance overflow

data/moves.ts, data/text/moves.ts
[Based on DaWoblefet's research](https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9438575). Apparently the description in game is pretty misleading.
=> Fix Glaive Rush not staying active until end of next turn

data/abilities.ts, data/items.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9441694
=> Fix Booster Energy activating under Sun/Electric Terrain

sim/battle.ts, test/sim/moves/revivalblessing.js
=> Fix Revival Blessing

data/rulesets.ts
=> Fix Sleep Clause hint

data/moves.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9439330
=> Fix Hyper Drill breaking protect instead of ignoring it

data/items.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9444222
=> Fix Punching Glove boost ratio

data/abilities.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9444108
=> Make Commander a permanent ability

config/formats.ts
=> fix RBY 1v1 link

sim/SIM-PROTOCOL.md, sim/pokemon.ts
=> Show Terastallization in switch details

config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3710997/#post-9446151
=> Partners in Crime: Improve innate timing and update bans

config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3710997/#post-9449844
=> Partners in Crime: Ban Baton Pass

data/mods/gen6/random-teams.ts, data/mods/gen7/random-teams.ts
Culls lightning rod in favor of swift swim when the team has rain.
Rands Discord here: https://discord.com/channels/294651453279174656/763039843654565941/1057775549034008596
=> Gen 6/7 Random Battle: Give Seaking Swift Swim with Rain Dance

data/mods/gen6/formats-data.ts, data/mods/gen6/random-teams.ts, data/mods/gen7/formats-data.ts, data/mods/gen7/random-teams.ts, data/mods/gen8/formats-data.ts, test/random-battles/gen6.js, test/random-battles/gen7.js, test/random-battles/gen8.js
discussed w/ randbats team, will get final review here
=> Gen 6-8 Random Battles: Fix unused moves

data/mods/gen5/formats-data.ts, data/mods/gen5/random-teams.ts
Changes approved by Random Battles staff
https://discord.com/channels/294651453279174656/763039178211721236/985507088937664592
=> Gen 5 Random Battles update

data/mods/gen3/random-teams.ts
Approved by rands staff
https://discord.com/channels/294651453279174656/763038340664524840/1051853737418817676
=> Gen 3 Random Battle update: White Herb for non-band Deo (-A)

data/mods/gen1/random-teams.ts
Change approved by Random Battles staff
https://discord.com/channels/294651453279174656/809413397840920586/1057675198666657862
=> Gen 1 Random Battles update

data/items.ts, test/sim/items/roomservice.js
Probably would be better to refactor the pseudo weather event to use `eachEvent` but I'm lazy
=> Fix Room Service boost source

data/abilities.ts
=> Random Battles: Pressure hotfix

data/moves.ts, data/text/moves.ts, test/sim/moves/glaiverush.js
Hopefully this is the last time we fix this
=> Fix Glaive Rush again

data/aliases.ts
funny meme name for it in mono community
=> Add Iron Bundle Alias

data/moves.ts
- Doodle's failures should never double Stomping Tantrum.
- If one of Doodle's failures is due to Ability Shield, the "But it failed!" message never appears, even if both Pokemon's abilities cannot be changed. The animation should still not play in this scenario, however.
- Doodle should not change the ability of an ally if it is the same as its current ability (so doodling intimidate should not reactivate an ally Arcanine's intimidate)
=> Fix Doodle fail conditions & messages

server/chat-plugins/friends.ts
https://www.smogon.com/forums/threads/friends-settings-allow-friends-to-message-you-when-you-block-pms-optional.3713439/
=> Friends: Allow users to toggle /blockpms friends etc. in settings

data/mods/gen2/formats-data.ts, data/mods/gen2/random-teams.ts
https://discord.com/channels/294651453279174656/809413306854932510/1060582882898358402
=> Gen 2 Random Battles updates

sim/pokemon.ts
Context: https://replay.pokemonshowdown.com/gen9uu-1763210376 Mimikyu should have tera in the -detailschange
=> Fix Tera details in forme change

config/formats.ts
https://www.smogon.com/forums/threads/metronome-battles.3632075/post-9463080
=> Metronome Battle: Ban Opportunist (suspect)

server/chat-plugins/mafia.ts
Cohosting someone on sublist didnt remove them from sublist.
Also added a comment to help with a potential issue with testing locally.
=> Mafia: Fix a bug with cohosts and sublist.

server/chat-commands/info.ts
https://www.smogon.com/forums/threads/requestshow-should-include-description-of-the-image-asked-to-be-shown.3708938/
=> Media approvals: Filter comment and show to staff

config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3710997/page-2#post-9465900
=> Partners in Crime: Ban Dancer

sim/battle-actions.ts, test/sim/moves/copycat.js
It should not copy called moves.
=> Gen 4: Fix Copycat

data/text/moves.ts
Fix latter part of [this](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-85#post-9380156) bug.
=> Fix/override cant protocol text for Disable

data/abilities.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9472173
=> Fix Anger Shell/Berserk boost source

data/mods/ssb/moves.ts, data/moves.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9472240
=> Use onTryImmunity event for Attract failure

server/chat-commands/info.ts
stolen from help room, would be useful to have site-wide now password resets are open again.
=> Add an FAQ for the Password Reset form

config/formats.ts
https://www.smogon.com/forums/threads/camomons-terastal-clause-implemented-28.3711340/post-9476770
=> Camomons: Add Terastal Clause

data/abilities.ts, sim/battle.ts, test/sim/abilities/opportunist.js
sorry about the duplicate, i tried to reopen the old one but github machine broke
=> Make Opportunist/Mirror Herb copy Anger Point

config/formats.ts
Using the default ability prevents Magnezone from validating correctly, woops. 
https://www.smogon.com/forums/threads/trademarked.3714688/#post-9482981
=> Trademarked: Restrict Shell Smash and fix validation

config/formats.ts
Banned by suspect test vote here: https://www.smogon.com/forums/threads/sv-aaa-suspect-2-fur-coat-and-ice-scales.3714908/post-9482960
=> AAA: Ban Fur Coat and Ice Scales

config/formats.ts
Specifically Dragapult, Iron Bundle, and Iron Valiant
https://www.smogon.com/forums/threads/almost-any-ability-furscales-banned.3710568/post-9484716
=> AAA: Update bans

data/abilities.ts
Confirmed by PS description and research thread
=> Cure burns when Thermal Exchange is obtained

data/rulesets.ts
for use by https://github.com/smogon/pokemon-showdown-client/pull/2095
=> Implement tera type preview

data/abilities.ts, test/sim/abilities/mirrorarmor.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9474372
=> Silence Mirror Armor if the source has fainted

config/formats.ts
https://www.smogon.com/forums/threads/pok%C3%A9bilities.3712725/post-9487523
=> Pokébilities: Ban Chi-Yu

server/chat-plugins/randombattles/winrates.ts
This fuses together some identical Pokemon formes, and separates formes that are sufficiently different.
Fuses together: Dudunsparce, Maushold, Tatsugiri, Squawkabilly-Blue with Squawkabilly, Squawkabilly-White with Squawkabilly-Yellow.
Separates: Gourgeist, Zacian, Zamazenta, Kyogre/Groudon, megas.
=> Random Battles winrates: Fine-tune collection

data/random-sets.json
-Winrates are collected by Mia's server feature.
-Winrates are processed and transformed into levels through complicated statistics done by Chains of Markov, with some help from Irpachuza
-i typed this stuff in manually
this is all objective and doesn't require approval from the room
=> Random Battles level balancing

config/formats.ts
As specified here https://www.smogon.com/forums/threads/almost-any-ability-sample-teams-post-337-iron-hands-ban-354.3710568/post-9490667
=> Almost Any Ability: Ban Iron Hands

config/formats.ts, data/mods/potd/random-teams.ts
Implements the new Random Battles monthly spotlight: POTD
The POTD will always generate in slot 2, unless maxTeamSize is 1, in which case it generates in slot 1.
https://www.smogon.com/forums/threads/random-battles-monthly-spotlight-cycle-5-voting.3715058/#post-9491679
=> Random Battles Monthly Spotlight: POTD

server/chat-plugins/datasearch.ts
Implements https://www.smogon.com/forums/threads/add-unreleased-to-ds.3713144/
Also fixes https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9493133
=> Datasearch: Allow searching unreleased Pokemon

config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3710997/page-2#post-9501002
Requires #9387 to be merged before or alongside this.
=> Partners in Crime: Unban Baton Pass

config/formats.ts
https://www.smogon.com/forums/threads/almost-any-ability-tiering-survey-376.3710568/post-9512610
=> AAA: Ban Orichalcum Pulse and Noivern

data/mods/gen8bdsp/formats-data.ts
https://www.smogon.com/forums/threads/bdsp-uu-celebi-banned-post-103.3694307/post-9514184
=> BDSP: Move Celebi to UUBL

config/formats.ts
Quickbanned by council vote: https://www.smogon.com/forums/threads/almost-any-ability-palkia-beard-ban-post-445.3710568/post-9525994
=> AAA: Ban Walking Wake

data/conditions.ts, data/moves.ts, data/text/moves.ts, test/sim/moves/hydrosteam.js
https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9527435
=> Apply Hydro Steam boost in Sunny Day damage modifier

data/rulesets.ts
Adds some compatibility with NatDex and CAP formats
=> Convergence: Allow custom validation

config/formats.ts
Post: https://www.smogon.com/forums/threads/almost-any-ability-several-bans-at-post-485-good-as-gold-ban-518.3710568/post-9539286
=> Almost Any Ability: Ban Good as Gold

CODEOWNERS
(Bad user) PartMan got RO perms for this (screenshots on Disc)
=> CODEOWNERS: Add PartMan to Scavengers

sim/battle-actions.ts, sim/pokemon.ts
https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-30#post-9530995
=> Remove added type upon Terastallization

data/text/abilities.ts
=> Abilities: Update Sheer Force's description to include Gen9

config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3710997/page-2#post-9544395
=> Partners in Crime: Ban Annihilape and Chi-Yu

data/mods/mixandmega/scripts.ts
I made a mistake in my previous PR. This fixes that one, the ability should be an ID in this case.
=> Mix and Mega: Fix bug with certain abilities not activating properly

server/chat-commands/info.ts
Add repo to ``/git`` command.
Thanks for the huge effort to port and open source it!
=> Add login server source to /git

config/formats.ts
Added Metagame Discussion to Gen 9 OU
Added Sample Teams to Gen 9 OU
Added Viability Rankings to Gen 9 OU, UU, RU, NU
=> Update Gen 9 format URLs

config/formats.ts
https://www.smogon.com/forums/threads/sv-aaa-suspect-4-dragonite.3719295/post-9570210
=> Almost Any Ability: Ban Dragonite

config/formats.ts
Adds Terastal Clause to Mix and Mega per the suspect test results (thread: https://www.smogon.com/forums/threads/sv-mnm-suspect-2-terastallization.3719258/#post-9570568)
=> Mix and Mega: Add Terastal Clause

config/formats.ts
First of likely more bans to adjust the metagame closer to OU standard: https://www.smogon.com/forums/threads/pok%C3%A9bilities-om-of-the-month.3712725/post-9570051
=> Pokébilities: Ban Espathra

server/chat-plugins/scavenger-games.ts
(I'll strongly type Scavs at a later date)
=> Scavengers: Fix minesweeper crashing if someone leaves

config/formats.ts, data/formats-data.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9575526
Proposed fix
=> National Dex UU: Properly ban Ash-Greninja

data/mods/gen8bdsp/formats-data.ts
https://www.smogon.com/forums/threads/bdsp-lc-new-bans-unbans-post-33.3696004/post-9571384
=> BDSP: Unban Munchlax from LC

server/chat-plugins/helptickets.ts
=> Help tickets: Add a button to mark IP as shared

data/mods/gen3/random-data.json, data/mods/gen3/random-teams.ts, data/mods/gen4/random-data.json, data/mods/gen4/random-teams.ts, data/mods/gen5/random-data.json, data/mods/gen5/random-teams.ts, data/mods/gen6/random-data.json, data/mods/gen6/random-teams.ts, data/mods/gen7/random-data.json, data/random-sets.json
April monthly randbats balance. Ideally is merged as soon as possible so the May stats are based on the new levels.
=> Random Battles: 2023-04 End-of-month changes

config/formats.ts
=> Battle Factory: Announce tier at battle start

config/formats.ts, data/mods/mixandmega/random-teams.ts
- Adds Mix and Mega Cup as the new Randomized Format Spotlight
- Moves Broken Cup under Doubles Hackmons Cup as a challenge-only format
=> Add May 2023 Randomized Format Spotlight

config/formats.ts
https://www.smogon.com/forums/threads/sv-aaa-suspect-5-gengar-and-zoroark-h.3721165/post-9614304
=> AAA: Ban Gengar and Hisuian Zoroark

data/rulesets.ts
It works on some example challenges on a local repository, i got spooked once by node telling me its a slow battle so .has _maybe_ could be made faster
=> Make Natdex Tier Shift work

config/formats.ts
this was supposed to happen more than 2 months ago
=> National Dex BH: Ban Berserk Gene

server/chat-plugins/scavenger-games.ts, server/chat-plugins/scavengers.ts
Non-urgent; updating the description with the how-to for the future. Have tested the twist itself on main; everything's working swimmingly!
=> Scavengers: Update the Minesweeper twist description

server/chat-commands/room-settings.ts
Two different small bugs, unrelated
=> Update modchat help

server/chat-plugins/datasearch.ts
Added additional commands for randitem, randability, and randtype. 
Based on forum post: https://www.smogon.com/forums/threads/more-commands-like-randpoke-and-randmove.3668708/
=> Add additional random commands

config/formats.ts
In case there is a hotpatch before the format is removed until it gets OMotM again.
=> Tier Shift: Update bans

server/chat-plugins/abuse-monitor.ts
I keep forgetting about this command's name and having it there is going to be very intuitive
=> Add /am edithistory to /help am

config/formats.ts
Updating for challenges and daily tours.
=> Pokebilities: Initial HOME bans

data/abilities.ts
https://www.smogon.com/forums/posts/9647546
=> Use correct modifier for Transistor

config/formats.ts
Pending verification on if transfer mechanics are correct here
=> BSS/VGC: Add Regulation D

config/formats.ts
https://www.smogon.com/forums/threads/trademarked.3714688/page-2#post-9652278
=> Trademarked and Shared Power: Update bans

config/formats.ts
Ability is bugged and isn't sharing.
=> Shared Power: Illusion ban

config/formats.ts
Format leaders had forgotten to include it in their original request.
https://www.smogon.com/forums/threads/generation-9-free-for-all.3711724/page-3#post-9643961
=> FFA: Ban Eternatus

data/mods/gen8/rulesets.ts, data/rulesets.ts, test/sim/misc/teampreview.js
https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9667999
=> Gen 9: Reveal Arceus forme in Team Preview

config/formats.ts
I'm the TL and I figured it's easier if I just submit this myself. I mentioned this to Kris so hopefully it's correct and fine to do.
https://www.smogon.com/forums/threads/national-dex-doubles-ou-vr-now-on-post-2.3720802/#post-9658131
https://www.smogon.com/forums/threads/national-dex-doubles-ou-vr-now-on-post-2.3720802/page-2#post-9679751
urshifu and ape respectively. posted by council members
=> National Dex Doubles: Update Bans

config/formats.ts, data/mods/randomroulette/random-teams.ts, data/mods/randomroulette/scripts.ts
This implements Random Roulette, which is the next Randomized Format Spotlight, replacing Mix and Mega Cup. https://www.smogon.com/forums/threads/randbats-spotlight-cycle-8-voting.3723432/
It chooses a random number between 1-9 inclusive and becomes a Random Battle in that gen.
=> Add July 2023 Randomized Format Spotlight

translations/german/helptickets.ts
per https://www.smogon.com/forums/threads/rules-commands-translations.3645723/post-9679162
=> Adding more German translations

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-doubles-ou-ladder-now-open.3720802/post-9691575
=> National Dex Doubles: Ban Assist

config/formats.ts
https://www.smogon.com/forums/threads/inheritance.3712296/post-9692938
=> Inheritance: Ban Torkoal

config/formats.ts
Implementing the banlist changes: 
https://www.smogon.com/forums/threads/force-of-the-fallen-july-om-of-the-month.3722355/page-3#post-9690291
https://www.smogon.com/forums/threads/cross-evolution.3710953/page-11#post-9693932
https://www.smogon.com/forums/threads/shared-power.3711011/page-5#post-9694209
=> Force of the Fallen, Cross Evolution and Shared Power: Update bans

config/formats.ts
This should fix the problem that prevents the passing of moves with Self-KO moves at times.
=> Force of the Fallen: Fixing double KO bug

config/formats.ts
Limit to one of each equiped move implemented:
https://www.smogon.com/forums/threads/fortemons.3713983/page-14#post-9689903 Also fixed a problem that prevented Last Respect from being fully banned.
=> Fortemons: Add Forte Clause

data/pokedex.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9693395
=> Fix Farfetch'd-Galar weight

sim/pokemon.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9694181
=> Fix Illusion leak when disguised as Greninja-Bond

config/formats.ts
Forgot about this one in the last update https://www.smogon.com/forums/threads/shared-power.3711011/page-5#post-9694209
=> Shared Power: Add Terastal Clause

config/formats.ts
https://www.smogon.com/forums/threads/force-of-the-fallen-july-om-of-the-month.3722355/page-4#post-9700618
=> Force of the Fallen: Update bans

config/formats.ts, data/formats-data.ts
Requested update in ND Discord. 
https://www.smogon.com/forums/threads/sv-national-dex-uu-stage-4-duet.3724375/
=> National Dex UU: Update Bans

config/formats.ts
Requested by Voltix/Acehunter1 in DLC Discord
https://www.smogon.com/forums/threads/doubles-little-cup-circuit-schedule-at-post-22.3710957/page-2#post-9649601
=> Doubles Little Cup: Ban Basculin-White-Striped

config/formats.ts
Let's try that again!
https://www.smogon.com/forums/threads/doubles-little-cup-circuit-schedule-at-post-22.3710957/page-2#post-9706038
=> Doubles Little Cup: Ban Tinkatink + Knock Off

data/items.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9707269
=> Add Fling BP for Gen 9 items

config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3710997/page-2#post-9709991
Should be done with haste as this is in preparation for an upcoming team tour with this format included.
=> Partners in Crime: Ban Urshifu-R and Enamorus

config/formats.ts
https://www.smogon.com/forums/threads/inheritance.3712296/page-5#post-9710379
=> Inheritance: Update bans

translations/portuguese/main.ts
per https://www.smogon.com/forums/threads/rules-commands-translations.3645723/post-9684568
=> Add missing Portuguese main translation

translations/portuguese/repeats.ts
per https://www.smogon.com/forums/threads/rules-commands-translations.3645723/post-9684568
=> Add Portuguese repeats translations

translations/portuguese/core-commands.ts
per https://www.smogon.com/forums/threads/rules-commands-translations.3645723/post-9684568
=> Add missing Portuguese core commands translation

server/tournaments/index.ts
Testing for my previous PR was not enough, sorry
Fix #9595
=> Tournaments: Show toolbox for reconnected players if the tournament was not started

data/moves.ts, test/sim/moves/icespinner.js
As per https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9716181.
=> Fix Ice Spinner removing terrain when fainting of recoil

config/formats.ts, data/rulesets.ts, test/sim/team-validator/misc.js
https://www.smogon.com/forums/posts/9713378
https://www.smogon.com/forums/posts/9716092/
=> Fix Gen 9 Hackmons legality

data/mods/gen8bdsp/formats-data.ts
https://www.smogon.com/forums/threads/bdsp-pu-magneton-and-rotom-frost-ban-post-62.3700009/post-9724275
=> BDSP: Ban Grumpig from PU

sim/team-validator.ts, test/sim/team-validator/misc.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9714058
=> Allow Alolan formes to learn Gen 9 egg moves from non-Alolan prevos

server/chat-plugins/othermetas.ts
Let you check the stats/abilities each Pokémon gives.
=> `/fuse`: Allow providing one argument

config/formats.ts
https://www.smogon.com/forums/threads/350-cup-we-got-omotm.3724198/page-3#post-9732859
=> 350 Cup: Update bans

sim/team-validator.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9735980
=> Fix Tatsugiri-Strechy move legality

config/formats.ts
https://www.smogon.com/forums/threads/fortemons.3713983/page-14#post-9732769
=> Fortemons: Update bans.

data/mods/gen8bdsp/formats-data.ts
https://www.smogon.com/forums/threads/bdsp-nu-mesprit-ban-post-111.3697080/post-9740922
=> Ban Jynx from BDSP NU

config/formats.ts
idk how any of this works but it was banned this time yesterday and isn't in yet
=> adding mega mewtwo y ban to gen 9 bh

config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3710997/page-3#post-9748018
=> Partners in Crime: Ban Cresselia

config/formats.ts
https://www.smogon.com/forums/threads/balanced-hackmons-deo-a-ban-423.3710859/post-9752495
=> BH: Ban Deoxys-Attack

data/rulesets.ts
https://www.smogon.com/forums/threads/protean-palace.3726834/
Code works.
=> Add Protean Palace Mod

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-uu-terastallization.3726737/page-2#post-9752279
=> National Dex UU: Ban Terastallization

data/mods/gen1/random-data.json, data/mods/gen3/random-data.json, data/mods/gen4/random-data.json, data/mods/gen5/random-data.json, data/mods/gen6/random-data.json, data/mods/gen7/random-sets.json, data/mods/gen8/random-data.json, data/random-doubles-sets.json, data/random-sets.json
Monthly level balance patch for Random Battles. If possible, please merge and patch close to the month rollover.
Thank you :)
=> Random Battles: August 2023 level balancing

config/formats.ts, data/mods/gen7pokebilities/abilities.ts, data/mods/gen7pokebilities/moves.ts, data/mods/gen7pokebilities/random-teams.ts, data/mods/gen7pokebilities/scripts.ts
Implements [Gen 7] Pokebilities Random Battle. 
https://www.smogon.com/forums/threads/randbats-spotlight-cycle-9-gen-7-pokebilities-random-battle.3726746/
=> Add September 2023 Randomized Format Spotlight

config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3710997/page-3#post-9765727
=> Partners in Crime: Ban King's Rock and Bright Powder

data/moves.ts, server/chat-plugins/datasearch.ts, sim/battle-actions.ts, sim/battle.ts, sim/dex-moves.ts, test/sim/moves/gigatonhammer.js
Just in case we happen to get another move in the DLC with the flag.
=> Implement cantusetwice move flag

data/text/moves.ts
https://www.smogon.com/forums/threads/.3726631/
=> Update Bleakwind, Sandsear, Wildbolt Storm Descriptions

sim/team-validator.ts, test/sim/team-validator/misc.js
Bug report: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9743043
=> Past gens: Fix old move/new Ability compatibility

server/chat-commands/moderation.ts
On GUI that was fixed but visible on bot client
=> Roomban: Remove a duplicated space

data/items.ts, data/mods/gen9predlc/items.ts
See [bug report](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/page-127#post-9780619) for proof that these berries are now obtainable
=> Fix berries legality in Teal Mask

data/items.ts
Research thread here: https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9780649
=> Implement power increase for STAB moves on Ogerpon masks

data/abilities.ts, data/mods/gen8/abilities.ts
New information courtesy of Anubis.
=> Fix Heatproof's modifier location

data/abilities.ts, data/items.ts, data/text/abilities.ts
- Add Fling BPs to masks
- Add `boost` flavor text
- Ensure only tera formes can use Embody Aspect (https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9781849)
=> More Ogerpon fixes

config/formats.ts
https://www.smogon.com/forums/threads/frantic-fusions-omotm-ladder-live-dlc-slate-post-221.3725593/page-9#post-9781616
=> Frantic Fusions: Update bans

config/formats.ts
https://www.smogon.com/forums/threads/cross-evolution.3710953/page-13#post-9782111
=> Cross Evolution: Terastal Clause

server/room-battle.ts
- Use set wins for `score`
- Flip left side avatar
- Send username instead of userid for `|win`
=> Bo3: Design nitpicks

config/formats.ts
https://www.smogon.com/forums/threads/fortemons.3713983/page-14#post-9796019
=> Fortemons: Ban Skeledirge

server/tournaments/index.ts
This reverts commit 3d1790fab9ec966d59de0d3db4de49aba04232ea.
=> Revert "Tours: Don't allow pipes in names set by /tour create"

data/mods/gen1/random-data.json, data/mods/gen3/random-data.json, data/mods/gen4/random-data.json, data/mods/gen5/random-data.json, data/mods/gen6/random-sets.json, data/mods/gen7/random-sets.json, data/mods/gen8/random-data.json, data/random-doubles-sets.json, data/random-sets.json
Monthly level balancing, nothing spectacular.
If possible, please merge and patch soonish to the month rollover.
Thank you as always
=> Random Battles: September 2023 level balancing

config/formats.ts
https://www.smogon.com/forums/threads/tera-donation-dlc1-bans-in-post-34.3715801/page-2#post-9781157
=> Tera Donation: Update bans

config/formats.ts
https://www.smogon.com/forums/threads/convergence-new-bans-276-om-of-the-month.3714048/page-12#post-9811375
=> Convergence: Update bans

config/formats.ts
https://www.smogon.com/forums/threads/dpp-dou-latios.3728827/#post-9805697
=> Gen 4 Doubles OU: Ban Latios

data/formats-data.ts
https://www.smogon.com/forums/threads/national-dex-ubers-2-koraidon.3729390/post-9818448
Doing this properly (thanks for the feedback @KrisXV)
=> Properly ban Koraidon from Gen 9 NatDex Ubers

config/formats.ts
https://www.smogon.com/forums/threads/cross-evolution.3710953/post-9809308
=> Cross Evolution: Ban Kyogre

sim/team-validator.ts
Accidentally put the code in `validateStats` not `validateSet` lol
=> Fix location of gender randomization from #9839

sim/battle.ts
- Always send proper gender
- Now hides nickname, happiness, dynamax level, and poke ball
=> Fix information sent in OTS

server/chat-plugins/responder.ts
PR for : https://www.smogon.com/forums/threads/make-the-modlog-entry-for-autofilter-remove-actually-helpful.3729617/
=> Autoresponder: Improve Modlog

config/formats.ts, data/mods/partnersincrime/random-teams.ts
https://www.smogon.com/forums/threads/random-battles-spotlight-cycle-9-voting-best-of-the-rest.3730142/
=> Add November 2023 Randomized Format Spotlight

server/chat-plugins/datasearch.ts
https://www.smogon.com/forums/threads/make-learn-clearer-about-moves-that-can-no-longer-be-learned-in-gen-9.3730552/
=> Default to min source gen 9 for /learn

data/mods/gen1/random-data.json, data/mods/gen3/random-data.json, data/mods/gen4/random-data.json, data/mods/gen5/random-sets.json, data/mods/gen6/random-sets.json, data/mods/gen7/random-sets.json, data/mods/gen8/random-data.json, data/random-doubles-sets.json, data/random-sets.json
Last month's rands balance patch, unfortunately delayed due to illness.
=> Random Battles: October 2023 level balancing

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-national-dex-uu-stage-5-leviathan.3730331/
=> National Dex UU: Ban Gyarados

data/text/abilities.ts
https://replay.pokemonshowdown.com/gen9anythinggoes-1985788285-fp3ijzw9kvy16wb96oewh2srsrqx2utpw
=> Update Neutralizing Gas's description

config/formats.ts
Will announce the tiering changes later and then edit this to add the new bans/unbans/restrictions.
=> Shared Power update

data/mods/partnersincrime/scripts.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9854751
The above bug was caused since basically none of the new gen 9 stuff were in `transformInto`.
=> Partners in Crime: Fix Transform

config/formats.ts
https://www.smogon.com/forums/threads/protean-palace.3726834/#post-9853809
=> Protean Palace: Ban Iron Valiant

config/formats.ts
Too many people have been confused by this by now.
=> Full Potential: Change description

config/formats.ts
https://sv-news.pokemon.co.jp/ja/page/144.html
https://sv-news.pokemon.co.jp/ja/page/145.html
=> Add Dragon King Cup online competition

server/tournaments/index.ts
=> Tournaments: readmore only when custom rules are defined

server/chat-plugins/friends.ts
The control flow here is quite hard to follow, there are probably other broken tags but I've only found this one
=> Fix HTML tag in /friends

config/formats.ts
Ice Scales and Psychic Surge are not supposed to be restricted.
=> Shared Power: Fix restrictions

config/formats.ts
https://www.smogon.com/forums/threads/camomons-tiering-actions-s-83-85.3711340/post-9850724
=> Camomons: Ban Manaphy and Iron Valiant

server/chat-plugins/randombattles/index.ts
I added support for fuzzy matching on the pokemon name when using the /randbats command, precisely how the /dt command does it.
-Quazizata
=> Add fuzzy searching to the /randbats command

data/learnsets.ts
replace wonderrroom--> wonderroom
=> Learnsets: Fix typo

data/random-teams.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9884052
=> Fix Force Monotype rule on Challenge/Hackmons Cup formats

config/formats.ts
Adding Gholdengo and Razor Fang to the sketchmons gen9 banlist
https://www.smogon.com/forums/threads/sketchmons.3715183/post-9883456
=> Sketchmons: Ban Gholdengo and Razor Fang

server/chat-plugins/friends.ts
=> Friends: Add class for the 'add friend' input

config/formats.ts
Correct Diglett's forme (Diglett-Base)
=> Update Monotype LC (Fix Diglett unban)

server/chat-plugins/quotes.ts
This way you don't have to find whatever you just quoted in order to show it in the room
=> Implement /viewquote last

config/formats.ts
https://www.smogon.com/forums/threads/shared-power.3711011/page-14#post-9894518
=> Shared Power: Ban Terapagos

data/abilities.ts, data/text/abilities.ts
Client: smogon/pokemon-showdown-client#2197
=> Show messages for Tera Shift

config/formats.ts
replace outdated + locked thread with the current thread
=> Update [Gen 3] LC thread link

sim/pokemon.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9886869
=> Fix Stomping Tantrum doubling bp after being forced out

data/formats-data.ts
https://www.smogon.com/forums/threads/np-sv-dou-stage-9-violet-hill.3732423/post-9897789
=> DOU: Ban Terapagos

config/formats.ts
Was in the original DLC ban post
https://www.smogon.com/forums/threads/inheritance.3712296/page-8#post-9895430
=> Inheritance: Ban Ho-Oh

data/formats-data.ts
https://www.smogon.com/forums/threads/pu-council-updates.3718204/page-2#post-9897746
=> PU: Ban Indeedee-M and Duraludon

data/mods/vaporemons/abilities.ts, data/mods/vaporemons/moves.ts
Changes decided in [this post](https://www.smogon.com/forums/threads/vaporemons-slate-10-dlc2-distribution-phase-pet-mod-of-the-season.3722917/page-27#post-9897618). One bug fix is also included.
=> VaporeMons: Nerf Rekindle & Justified

config/formats.ts
Was in the DLC2 initial bans.
https://www.smogon.com/forums/threads/the-card-game-dlc-2-bans-at-post-74.3716838/page-3#post-9894915
=> The Card Game: Ban Gouging Fire

server/chat-plugins/announcements.ts
https://www.smogon.com/forums/threads/allow-roomstaff-to-edit-room-announcements-without-having-to-ping-the-entire-room-every-time.3732092/
=> Allow Announcements to be edited

config/formats.ts
Doexys-Speed was banned instead of Attack.
=> Fortemons: Fix bans

config/formats.ts
https://www.smogon.com/forums/threads/camomons-indigo-disk-dlc-additions-95-new-tiering-decisions-97.3711340/page-4#post-9899773
=> Camomons: Update bans

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-doubles-ou-metagame-discussion-terapagos-banned.3720802/page-4#post-9899525
=> National Dex Doubles: Ban Terapagos

config/formats.ts
Last one missing, I think  https://www.smogon.com/forums/threads/inheritance.3712296/page-8#post-9895430
=> Inheritance: Ban Water Bubble

config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3710997/page-4#post-9898674
=> Parters in Crime: Update bans

data/formats-data.ts
https://www.smogon.com/forums/threads/np-stage-8-coming-down-inteleon-snorlax-banned.3732068/page-2#post-9903022
=> NU: Ban Inteleon and Snorlax

config/formats.ts, data/formats-data.ts
https://www.smogon.com/forums/threads/metagame-discussion.3710868/post-9904159
=> LC: Ban Scraggy

config/formats.ts
https://www.smogon.com/forums/threads/cross-evolution.3710953/page-15#post-9906257
=> Cross Evolution: Ban Duraludon

test/sim/moves/terablast.js
Reproduces #9381 in a unit test.
If this change looks good, I can open a separate pull request to investigate a fix for the issue.
=> Add unit tests for Tera Blast to reproduce issue #9381.

config/formats.ts
https://www.smogon.com/forums/threads/fortemons.3713983/page-14#post-9900313
=> Fortemons: Update bans

data/moves.ts
https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9904403
> If a Flying-type Terastallizes into the Stellar-type and then Roosts while damaged, it does not lose its Flying-type and thus [retains its Ground-type immunity for the turn](https://www.youtube.com/watch?v=rGIUfEdH2Nc).
=> Fix Roost and Stellar Terastallization interaction

config/formats.ts
https://www.smogon.com/forums/threads/balanced-hackmons-mmx-and-deo-a-ban-606.3710859/page-25#post-9908582
=> Balanced Hackmons: Ban Mega Mewtwo X and Deoxys-Attack

config/formats.ts
Water bubble and Triage were missing in FF https://www.smogon.com/forums/threads/frantic-fusions.3725593/page-12#post-9895555 Base Kyurem hasnt been banned in inh https://www.smogon.com/forums/threads/inheritance.3712296/
=> Frantic Fusions and Inheritance: Fix bans

data/abilities.ts, test/sim/abilities/terashell.js
https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-48#post-9898594
=> Lock Tera Shell effect to Terapagos

server/chat-commands/info.ts
Updating it so it's in sync with <\<help\>>'s ``/rfaq customavatar``
=> Update /faq customavatars

data/rulesets.ts
https://www.smogon.com/forums/threads/protean-palace.3726834/post-9909685
=> Rework Protean Palace

sim/team-validator.ts, test/sim/team-validator/formes.js
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9907946
=> Fix Unown forme validation in Gen 2

data/mods/vaporemons/pokedex.ts
Change made in [this post](https://www.smogon.com/forums/threads/vaporemons-slate-10-dlc2-distribution-phase-results-pet-mod-of-the-season.3722917/post-9911458).
=> VaporeMons: Nerf Terrakion

data/mods/gen1/random-data.json, data/mods/gen3/random-data.json, data/mods/gen4/random-sets.json, data/mods/gen5/random-sets.json, data/mods/gen6/random-sets.json, data/mods/gen7/random-sets.json, data/mods/gen8/random-data.json, data/random-doubles-sets.json, data/random-sets.json
Monthly balance patch, first one for the new DLC mons.
Thank you as always, and happy holidays!
=> Random Battles: December 2023 balance patch

config/formats.ts
https://www.smogon.com/forums/threads/1v1-old-gens.3646875/page-24#post-9912515
=> ADV 1v1: Unban Ingrain

config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3710997/page-4#post-9913948
=> Partners in Crime: Ban Kyurem-Black

config/formats.ts
[Gen 6] First Blood Random Battle won the vote, barely.
https://www.smogon.com/forums/threads/randbats-spotlight-cycle-11-voting.3733215/
=> Add January 2024 Randomized Format Spotlight

config/formats.ts
https://www.smogon.com/forums/threads/sharing-is-caring.3727118/page-3#post-9916053
=> Sharing Is Caring: Ban Scope Lens

data/rulesets.ts
https://www.smogon.com/forums/threads/bug-report-validator.3733627/
=> Fix Event Moves Clause banning Hidden Power types

server/chat-plugins/randombattles/index.ts
=> `/randbats`: Show the Pokemon's level

sim/pokemon.ts, test/sim/moves/transform.js
If you're Tera Stellar, Transform will fail.
=> Fix interaction of Tera Stellar and Transform

config/formats.ts
https://www.smogon.com/forums/threads/fortemons.3713983/page-15#post-9917631
=> Fortemons: Restrict Tera Blast

sim/battle-actions.ts, test/sim/abilities/prankster.js
https://www.smogon.com/forums/threads/prankster-hint-causes-info-leak.3733467/
=> Fix Prankster info leak

data/mods/trademarked/scripts.ts
Also updates the modded transformInto method
=> Trademarked: Fix Crash

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-national-dex-uu-stage-6-empty-pockets-meowscarada-banned.3733769/#post-9920000
=> National Dex UU: Ban Meowscarada

config/formats.ts
https://www.smogon.com/forums/threads/adv-doubles.3666831/page-3#post-9920986
=> ADV Doubles OU: Ban Latias

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-dou-2-coaching.3733993/#post-9924564
=> National Dex Doubles: Ban Coaching

data/formats-data.ts
https://www.smogon.com/forums/threads/pu-council-updates.3718204/page-2#post-9925409
=> PU: Update bans

config/formats.ts
https://www.smogon.com/forums/threads/meloetta-cinderace-and-necrozma-are-quickbanned.3734011/
=> 1v1: Update bans

server/chat-plugins/datasearch.ts
https://www.smogon.com/forums/threads/bug-report-chat.3734233/
=> Show Unobtainable moves in /nms

data/mods/thecardgame/moves.ts
https://www.smogon.com/forums/threads/bug-report-om.3734398/
=> The Card Game: Fix Ivy Cudgel type for Ogerpon-Cornerstone

config/formats.ts
=> Support CAP and NatDex Inheritance

config/formats.ts
https://www.smogon.com/forums/threads/adv-ubers-baton-pass.3734511/#post-9941169
=> ADV Ubers: Ban Baton Pass

config/formats.ts
https://www.smogon.com/forums/threads/sv-stabmons-suspect-3-weavile.3734820/#post-9942305
=> STABmons: Ban Weavile

config/formats.ts
https://www.smogon.com/forums/threads/2v2-doubles.3710849/page-2#post-9946822 Ban Deoxys-Attack and unban Tornadus-Base
=> 2v2 Doubles: Update bans

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-uu-suspect-process-round-4-ceruledge.3735462/page-2#post-9956437
=> UU: Ceruledge

data/mods/gen1/random-data.json, data/mods/gen3/random-sets.json, data/mods/gen4/random-sets.json, data/mods/gen5/random-sets.json, data/mods/gen6/random-sets.json, data/mods/gen7/random-sets.json, data/mods/gen8/random-data.json, data/random-doubles-sets.json, data/random-sets.json
Balance patch for this month, thanks in advance!
=> Random Battles: January 2024 balance patch

data/conditions.ts, sim/battle-actions.ts, test/sim/abilities/commander.js
https://www.smogon.com/forums/threads/sure-hit-toxic-on-commanding-tatsugiri.3735245/
=> Fix Commander invulnerability check

data/mods/gen7/random-doubles-data.json, data/mods/gen7/random-sets.json, data/mods/gen8/random-data.json
We'll investigate into the "why" later, but for now this fixes the crash.
=> Gen 7-8 Random Battles: Fix crash

data/formats-data.ts
https://www.smogon.com/forums/threads/national-dex-ru-metagame-discussion.3713801/page-6#post-9959794
=> National Dex RU: Ban Quaquaval

data/conditions.ts
https://www.smogon.com/forums/threads/perish-song-and-commander.3735791/
=> Fix Perish Song and Commander interaction

server/chat-plugins/helptickets.ts
User 3321st brought it to my attention, this had not been updated as we resumed resetting passwords.
=> Help tickets: Link to password reset form

config/formats.ts
https://www.smogon.com/forums/threads/re-evolution-leaders-choice.3710983/page-4#post-9971347
=> Re-Evolution: Update bans

config/formats.ts
Updated links to actively maintained resource hubs
=> Update RU, NU, and PU oldgen links

data/rulesets.ts
Change approved by Isaiah
https://www.smogon.com/forums/threads/change-the-chimera-description-pls.3732837/
=> Update Chimera 1v1 Mod Description

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-doubles-ou-metagame-discussion-urshifu-r-banned.3720802/page-4#post-9992331
=> National Dex Doubles: Ban Urshifu-Rapid-Strike

data/abilities.ts, data/moves.ts, test/sim/abilities/terashell.js, test/sim/misc/terapagos.js, test/sim/moves/terastarstorm.js
- Tera Starstorm now properly has the Photon Geyser effect if the user is Terapagos-Stellar
- Tera Shell now correctly activates if the user's current species is Terapagos-Terastal
- Adds some more tests for various Terapagos mechanics
=> Fix some more Terapagos mechanics

sim/battle-actions.ts, sim/dex-moves.ts, test/sim/misc/terastellar.js
https://www.smogon.com/forums/threads/tera-stellar-and-multihit-moves.3737292/
=> Fix Tera Stellar interaction with multihit moves

data/mods/gen1/random-data.json, data/mods/gen3/random-sets.json, data/mods/gen4/random-sets.json, data/mods/gen5/random-sets.json, data/mods/gen6/random-sets.json, data/mods/gen7/random-sets.json, data/mods/gen8/random-data.json, data/random-doubles-sets.json, data/random-sets.json
=> Random Battles: February 2024 balance patch

config/formats.ts
https://www.smogon.com/forums/threads/sv-doubles-little-cup.3710957/page-2#post-9900353
=> Doubles LC: Ban Duraludon

config/formats.ts
https://www.smogon.com/forums/threads/foresighters-om-of-the-month-for-march.3735969/page-3#post-10018009
=> Foresighters: Update bans

data/formats-data.ts
Both were already banned, NDRU Banlist found here - https://www.smogon.com/forums/threads/national-dex-ru-metagame-discussion.3713801/
=> NatDex RU: Ban Mega Altaria & Mega Gallade

server/rooms.ts
https://www.smogon.com/forums/threads/redirect-private-battle-links-to-public-battles.3738545/
=> Allow redirects from private battle ids to public ids

data/formats-data.ts
https://www.smogon.com/forums/threads/np-stage-10-i-must-apologise-post-41-armarouge-gyarados-necrozma-banned.3737924/page-2#post-10030763
=> NU: Ban Armarouge, Gyarados, and Necrozma

data/abilities.ts, test/sim/abilities/rattled.js
https://www.smogon.com/forums/threads/bug-report-mechanics.3739063/
=> Fix Rattled boosting speed when Intimidate fails

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-ru-suspect-process-round-6-voting-zarude.3739156/page-2#post-10035395
=> RU: Ban Zarude

data/mods/vaporemons/scripts.ts
Change in accordance with [this post](https://www.smogon.com/forums/threads/vaporemons-slate-10-baxcalibur-suspect-test-pet-mod-of-the-season.3722917/post-10026408)
=> VaporeMons: Nerf Gouging Fire

config/formats.ts
https://www.smogon.com/forums/threads/inheritance-drought-banned.3712296/post-10027021
=> Inheritance: Ban Drought, unban Torkoal

data/formats-data.ts
https://www.smogon.com/forums/threads/national-dex-ubers-3-xerneas.3739283/post-10037450
=> National Dex Ubers: Ban Xerneas

server/chat-commands/room-settings.ts, server/room-battle-bestof.ts, server/rooms.ts
~~Only issue right now is that the links between the battles and best of room don't update properly when /hideroom is used (/publicroom is fine because of the recent redirect thing I added).~~
=> Allow BestOfGames to be private

server/chat-commands/info.ts
Implements [this](https://www.smogon.com/forums/threads/calc-in-battles-should-open-the-calc-for-the-associated-gen.3738535/) suggestion.
=> Calc command: Get gen from room format

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-national-dex-uu-stage-6-4-thunderstruck.3739955/
=> National Dex UU: Ban Latios and Thundurus-Therian

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-ru-metagame-discussion-hoopa-unbound-banned-see-post-188.3733547/page-8#post-10048925
=> RU: Ban Hoopa-Unbound

data/mods/gen1/random-data.json, data/mods/gen3/random-sets.json, data/mods/gen4/random-sets.json, data/mods/gen5/random-sets.json, data/mods/gen6/random-sets.json, data/mods/gen7/random-sets.json, data/mods/gen8/random-data.json, data/random-doubles-sets.json, data/random-sets.json
Monthly balance patch, thank you and happy easter!
=> Random Battles: March 2024 balance patch

data/mods/gen8bdsp/formats-data.ts
https://www.smogon.com/forums/threads/bdsp-uu-tier-shifts-post-107.3694307/page-5#post-10053514
=> BDSP UU Tier Shifts

server/chat-plugins/seasons.ts, server/chat.ts, server/room-battle.ts
Needs to be ready for merge by April 1. Spec: https://www.smogon.com/forums/threads/ps-ladder-seasons.3739299/
=> Add a plugin for ladder seasons

data/mods/gen4/random-teams.ts, data/mods/gen5/random-teams.ts, data/mods/gen6/random-teams.ts, data/mods/gen7/random-teams.ts
Arbok without Rest will always be Intimidate, as intended.
Please merge as soon as possible.
=> Hotfix Shed Skin Arbok in Gen 4-7 Random Battle

config/formats.ts
So this was banned last year and no one noticed until now... https://www.smogon.com/forums/threads/full-potential.3711127/page-3#post-9778935
=> Full Potential: Ban Speed Boost

config/formats.ts
=> Remove Type Split ladder

data/mods/gen4/abilities.ts
quick fix as described by marty in https://www.smogon.com/forums/threads/air-lock-in-pastgens.3740028/
=> Fix Air Lock/Cloud Nine in Gen 4 and below

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-dou-3-mega-metagross.3741586/page-2#post-10082275
=> National Dex Doubles: Ban Metagross-Mega

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-ou-suspect-process-round-12-voting.3742100/post-10090923
=> OU: Ban Volcarona

config/formats.ts
https://www.smogon.com/forums/threads/pok%C3%A9bilities-meta-poll-page-9-post-216.3712725/post-10090617
=> Pokébilities: Ban Basculegion, Braviary-H, Chien-Pao

data/mods/gen3/random-sets.json, data/mods/gen4/random-sets.json, data/mods/gen5/random-sets.json, data/mods/gen6/random-sets.json, data/mods/gen7/random-sets.json, data/mods/gen8/random-data.json, data/random-doubles-sets.json, data/random-sets.json
Level balancing for this month, thanks as always!
=> Random Battles: April 2024 balance patch

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-ubers-uu-spotlight-ladder-for-may.3742166/post-10099153
=> National Dex Ubers UU: Ban Light Clay, Flutter Mane, Kyurem-Black

data/mods/gen5/formats-data.ts
https://www.smogon.com/forums/threads/bw-ou-cloyster.3742769/page-2#post-10105940
=> BW: Ban Cloyster from OU

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-doubles-ou-metagame-discussion-zamazenta-banned.3720802/page-5#post-10106941
=> National Dex Doubles: Ban Zamazenta

config/formats.ts
Hatterene is banned under March usage stats.
https://www.smogon.com/stats/2024-03/gen9nationaldexubers-1630.txt
=> National Dex Ubers UU: Ban Hatterene

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-ru-metagame-discussion-april-shifts-see-post-191.3733547/page-10#post-10118120
=> RU: Ban Iron Leaves

data/mods/gen9ssb/abilities.ts, data/mods/gen9ssb/conditions.ts, data/mods/gen9ssb/moves.ts, data/mods/gen9ssb/pokedex.ts, data/mods/gen9ssb/random-teams.ts, data/mods/gen9ssb/scripts.ts, sim/battle-actions.ts, sim/global-types.ts
Still waiting on Tico's buffs to be QC approved
=> SSB: Implement balance changes

data/mods/gen3/moves.ts, data/mods/gen4/moves.ts, data/moves.ts
https://www.smogon.com/forums/threads/gen-3-reversal-flail.3743660/
=> Fix Flail/Reversal BP modifier in Gen 2-3

config/formats.ts
Reported at https://www.smogon.com/forums/threads/bug-report-validator.3742270/
=> ADV Ubers: Fix Wynaut complex ban

server/tournaments/index.ts
https://www.smogon.com/forums/threads/help-tour-settings-does-not-work.3733805/
https://github.com/smogon/pokemon-showdown/issues/9877#issuecomment-1792948097 Did this
=> Fix tour settings help

config/formats.ts
https://www.smogon.com/forums/threads/sv-mix-and-mega-suspect-9-gouging-fire.3743571/#post-10122561
=> MnM - Restrict Gouging Fire

server/chat-commands/core.ts
Fixing verbiage of /offlinepms error message
=> Improve error message for /offlinepms

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
Another month, another balance patch.
Data for the first half of this month is unfortunately lost, but the statistics remain valid. In addition some data from previous months is used in the system, but thankfully I have all of that saved locally (and should really be working on getting everything git-ready so it's properly backed up)!
Thanks as always
=> Random Battles: May 2024 balance patch

server/chat-plugins/randombattles/index.ts
Depends on #10180 
(Pretend IVs are working properly, I had the same issue with EVs and just forgot to fix IVs when I took the screenshot)
=> `/bssfactory`: Update to gen 9

data/mods/gen4/abilities.ts, test/sim/abilities/download.js
https://www.smogon.com/forums/threads/gen-4-download-does-not-activate-if-foe-is-behind-substitute.3734079/
=> Gen 4: Download ignores foes behind Substitute

config/formats.ts
https://www.smogon.com/forums/threads/fervent-impersonation.3740523/page-3#post-10137191
So Cramorant, Mimikyu and Eiscue have a weird interaction that may be unintended and is breaking the game, so they are being banned for now.
=> Fervent Impersonation: Update bans

server/chat-plugins/scavenger-games.ts
The only real change is line 558; the other stuff is just me looking at my old code and crying
Making another PR to actually add types to twists
=> Scavengers: Stop crashes on Minesweeper ending

config/formats.ts
https://www.smogon.com/forums/threads/sv-mix-and-mega-suspect-9-red-orb.3745030/post-10147227
=> MnM: Ban Red Orb

config/formats.ts
https://www.smogon.com/forums/threads/mix-and-mega.3710921/page-11#post-10149179
=> MnM: Unrestrict Jolteon and Enamorus

data/formats-data.ts
https://www.smogon.com/forums/threads/np-zu-stage-9-march-of-the-pigs-uxie-ban-and-vulpix-unban-18.3743382/
=> ZU: Update bans

config/formats.ts, data/formats-data.ts
Drought ban: https://www.smogon.com/forums/threads/np-stage-11-calm-down-drought-banned-17-mew-banned-18.3743606/#post-10148995
Mew ban: https://www.smogon.com/forums/threads/np-stage-11-calm-down-drought-banned-17-mew-banned-18.3743606/#post-10150714
=> NU: Ban Mew and Drought

config/formats.ts
https://www.smogon.com/forums/threads/partners-in-crime.3710997/page-4#post-10135434
Fashionably late to the party, as usual
=> Partners in Crime: Ban Evasion Abilities, Stench

data/learnsets.ts
Removing Dkiss from chuggalong; hope I did this right. Just removed the line where dkiss was in the learnsets.ts file. Let me know if I messed up anything.
=> Chuggalong Draining Kiss Removal

data/formats-data.ts
Banned via council vote: https://www.smogon.com/forums/threads/national-dex-ru-metagame-discussion.3713801/post-10162141
=> NDRU: Ban Pecharunt

config/formats.ts
https://www.smogon.com/forums/threads/full-potential.3711127/page-3#post-10087574
=> Full Potential: Update bans

config/formats.ts
Banned via suspect test: https://www.smogon.com/forums/threads/adv-lc-thunder-wave.3745721/#post-10166159
=> ADV LC: Ban Thunder Wave

server/chat-plugins/seasons.ts
Logged battles will now include:
- relevant badge of the players
- format of the battle
- floored Elo
- usernames instead of IDs
=> Seasons: Improve logging

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-zu-4-kingdra.3745999/#post-10168753
=> ZU: Ban Kingdra

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
Another month, another patch. Thank you as always!
=> Random Battles: June 2024 balance patch

config/formats.ts
https://www.smogon.com/forums/threads/mix-and-mega.3710921/page-11#post-10172629
=> Mix and Mega: Restrict Solgaleo

config/formats.ts
https://www.smogon.com/forums/threads/godly-gift.3710734/page-9#post-10171968
=> Godly Gift: Restrict Baxcalibur and Chien-Pao

config/formats.ts, data/mods/gen5bw1/formats-data.ts
BW1 OU has been selected as an RoA spotlight ladder for July 2024:
https://www.smogon.com/forums/threads/roa-spotlights-tournaments-bw1-ou.3746126/
=> Add [Gen 5] BW1 OU

config/formats.ts, data/random-battles/gen9/teams.ts, data/random-battles/gen9cap/sets.json, data/random-battles/gen9cap/teams.ts, sim/teams.ts, test/random-battles/all-gens.js
A CAP Pokemon will always generate in slot 2, and can randomly generate in the rest of the team.
Please do not merge until https://github.com/smogon/pokemon-showdown/pull/10376 is merged.
=> Add July 2024 Randomized Format Spotlight

data/mods/gen9ssb/moves.ts, data/mods/mixandmega/scripts.ts, data/mods/partnersincrime/scripts.ts, data/mods/randomroulette/scripts.ts, data/mods/trademarked/scripts.ts, sim/battle.ts, sim/global-types.ts, test/sim/decisions.js, test/sim/misc/endlessbattleclause.js
This is just a bunch of random changes to improve code readability.
The biggest change is `battle.go` → `battle.turnLoop` and `battle.commitDecisions` → `battle.commitChoices`.
PRing on the off chance someone hooks into these functions.
=> Improve code readability

sim/pokemon.ts
https://www.smogon.com/forums/threads/target-selection-of-tera-starstorm.3746261/
=> Remove option to select target for Tera Starstorm when Terastallized

config/formats.ts
https://www.smogon.com/forums/threads/stabmons.3710577/post-10176820
=> STABmons: Ban Gouging Fire, Kyurem, and Lilligant-Hisui

server/chat-plugins/auction.ts, server/rooms.ts
https://www.smogon.com/forums/threads/lets-move-more-bot-features-onto-the-sim.3725535/post-9981132
=> Add auctions as a chat plugin

config/formats.ts
https://www.smogon.com/forums/threads/bw1-overused.3744853/
Yes, I banned King's Rock without banning Razor Fang, though in my defense, so did the TL.
=> [Gen 5] BW1 OU: Ban Razor Fang

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-balanced-hackmons-spotlight-ladder-of-july.3711099/post-10179375
=> National Dex BH: Ban Ceaseless Edge

data/formats-data.ts
Banned via council vote: https://www.smogon.com/forums/threads/pu-council-updates.3718204/post-10181057
=> SV PU: Ban Raikou 

data/formats-data.ts
https://www.smogon.com/forums/threads/national-dex-ru-metagame-discussion.3713801/post-10180952
=> National Dex RU: Ban Haxorus

server/chat-plugins/auction.ts
Forgot to actually empty out the object that keeps track of the bids placed
=> Auctions: Fix blind mode

server/replays.ts
https://www.smogon.com/forums/threads/hidereplays-url-after-battle-end.3746872/
=> Fix /hidereplay sending public url

server/chat-plugins/datasearch.ts
https://www.smogon.com/forums/threads/nds-with-lgpe-and-eternal-floette.3746876/
=> Fix /nds showing certain illegal Pokemon

config/formats.ts
https://www.smogon.com/forums/threads/category-swap-lcotm-lugia-is-banned.3711668/page-2#post-10183278
=> Category Swap: Ban Lugia

data/mods/gen1/formats-data.ts
A couple of days ago I requested to have some mons to ZU, and I completely missed that Wartortle should have also been moved! Sorry about that!
=> Move Wartortle to ZU

config/formats.ts, data/mods/gen8/formats-data.ts
https://www.smogon.com/forums/threads/ss-lc-vullaby.3746447/page-2#post-10185057
=> SS LC: Unban Vullaby

config/formats.ts
https://www.smogon.com/forums/threads/inheritance-quiver-dance-suspect-see-post-344.3712296/page-14#post-10188650
=> SV Inheritance: Update bans

server/chat-plugins/auction.ts
- Preserves draft order for a team's player list
- Uses html for nom/bid messages to have username colors, should make them stand out more (depends on smogon/pokemon-showdown-client#2263)
- Switches to using Maps instead of objects. Mostly did this for personal preference but also Maps just make more sense here.
=> Auctions: Refactors + Formatting suggestions

server/chat-plugins/auction.ts
Did not realize that Scrappie did this until now.
=> Auctions: Show all bids placed during blind mode

config/formats.ts
Banned via council vote:
https://www.smogon.com/forums/threads/nfe.3710638/page-5#post-10185995
=> SV NFE: Ban Gligar

data/formats-data.ts
https://www.smogon.com/forums/threads/np-stage-12-bitter-sweet-symphony-lycanroc-d-banned.3746231/page-2#post-10191971
=> SV NU: Ban Lycanroc-Dusk

server/chat-plugins/suspect-tests.ts, server/room-battle.ts
This way tier leaders can more easily get their suspects added.
=> Suspects: Refactor whitelisting

config/formats.ts
Unbanned via council vote.
https://www.smogon.com/forums/threads/mix-and-mega.3710921/page-11#post-10195615
=> SV MnM: Unrestricted Kilowattrel

config/formats.ts
https://www.smogon.com/forums/threads/sv-1v1-suspect-8-ogerpon-hearthflame.3747349/post-10196239
=> 1v1: Ban Ogerpon-Hearthflame

config/formats.ts
https://www.smogon.com/forums/threads/metronome-battle.3632075/post-10193521
=> Metronome Battle: Ban Toxic Chain

config/formats.ts
https://www.smogon.com/forums/threads/stabmons-suspect-6-electro-shot.3747526/#post-10199878
=> SV STAB: Restrict Electro Shot

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-ubers-uu.3742166/post-10138498
* Blaziken-Mega, Kyogre, and Zekrom to NDUUUBL
https://www.smogon.com/forums/threads/national-dex-ubers-uu.3742166/post-10176759
* Hatterene, Deoxys-Speed to ND Ubers UU
* Chansey, Dondozo, Smeargle to ND Ubers
=> National Dex Ubers UU: Tiering

data/mods/gen8linked/scripts.ts, data/mods/gen9ssb/scripts.ts, sim/battle-actions.ts, test/sim/moves/encore.js
https://www.smogon.com/forums/threads/encore-boosted-priority-vs-priority-protection-effects.3740004/
=> Fix interaction between Encore and priority-blocking effects

data/moves.ts
https://www.smogon.com/forums/threads/typeless-revelation-dance-behavior.3747595/
=> Use secondary/added type for Revelation Dance if primary type is ???

data/mods/gen1/formats-data.ts
https://www.smogon.com/forums/threads/rby-uu-articuno-voting.3747617/#post-10201454
=> RBY: Move Articuno to UUBL

server/chat-commands/info.ts
I took over the rfaq from room help.
=> Update /faq lostpassword

data/formats-data.ts
https://www.smogon.com/forums/threads/national-dex-ru-metagame-discussion.3713801/post-10202214
=> National Dex RU: Ban Mienshao to RUBL

sim/team-validator.ts, test/sim/team-validator/breeding.js
https://www.smogon.com/forums/threads/low-level-hatched-pokemon-in-gens-2-3.3747600/
=> Prevent Gen 2 and 3 eggs from being under level 5

config/formats.ts
https://www.smogon.com/forums/threads/category-swap-lcotm-check-post-56.3711668/post-10202923
=> Category Swap: Update bans

data/formats-data.ts
https://www.smogon.com/forums/threads/np-stage-12-bitter-sweet-symphony-deo-d-feraligatr-banned.3746231/page-2#post-10202956
=> SV NU: Ban Feraligatr and Deoxys-Defense

data/mods/gen8bdsp/formats-data.ts
https://www.smogon.com/forums/threads/bdsp-pu-grumpig-ban-post-71.3700009/page-4#post-10211874
=> BDSP: Unban Chimecho from PU

config/formats.ts
https://www.smogon.com/forums/threads/stabmons.3710577/post-10210932
=> STABmons: Update bans

config/formats.ts
https://www.smogon.com/forums/threads/sv-inheritance-suspect-2-quiver-dance.3747927/post-10210902
=> Inheritance: Ban Quiver Dance

data/abilities.ts, data/mods/gen4/abilities.ts, data/mods/gen5/abilities.ts
https://www.smogon.com/forums/threads/frisk-in-gen-4-5-doubles.3747894/#post-10209608
=> Fix Frisk text in Gens 4-5

config/formats.ts, sim/pokemon.ts, test/sim/moves/roost.js
https://www.smogon.com/forums/threads/pure-flying-type-roost-and-forests-curse-trick-or-treat.3748082/
=> Fix Roost on pure Flying types not keeping Normal type with added type

config/formats.ts
Someone smarter than me may want to double-check it, but this fixed it for me.
=> Pokemoves: Fix ability target

config/formats.ts
https://www.smogon.com/forums/threads/flipped-lcotm-for-august.3711301/#post-10212555
=> Flipped: Update bans

config/formats.ts
Magearna was in both banned and restricted, so it was being allowed.
=> Pokemoves: Fix validation

data/formats-data.ts
https://www.smogon.com/forums/threads/national-dex-ru-metagame-discussion.3713801/post-9924236
=> Move Buzzwole to ND RUBL

server/chat-commands/core.ts
Server-side for https://github.com/smogon/pokemon-showdown-client/pull/2272
=> Add a /crq for command tab-completion

server/chat-plugins/quotes.ts
=> Add support to /removequote last

server/private-messages/database.ts
Small change but hopefully useful in the future
=> Improve types for offline pms module

server/chat-commands/info.ts
=> /calc: Add Randoms calc support for Random Doubles

config/formats.ts
https://www.smogon.com/forums/threads/pokemoves-august-omotm.3747537/page-5#post-10220949
=> Pokemoves: Ban Damp Rock

server/chat-plugins/suspect-tests.ts
=> COIL: Fix help text

data/mods/gen8bdsp/formats-data.ts
https://www.smogon.com/forums/threads/bdsp-ru-ru-tier-shifts-post-128.3695563/post-10224243
=> BDSP: Update tiering for UU and RU Pokemon

config/formats.ts
A bit over a week for anyone to remember that Muk and Grimer have other forms.
=> Pokemoves: Fix banlist

data/mods/gen9ssb/abilities.ts, data/mods/gen9ssb/conditions.ts, data/mods/gen9ssb/moves.ts, data/mods/gen9ssb/pokedex.ts, data/mods/gen9ssb/random-teams.ts, data/mods/gen9ssb/rulesets.ts, data/mods/gen9ssb/scripts.ts, server/chat-plugins/randombattles/ssb.ts, server/chat-plugins/suspect-tests.ts
=> Super Staff Bros: Implement bugfixes and balance updates

config/formats.ts
https://www.smogon.com/forums/threads/pokemoves-august-omotm.3747537/page-6#post-10225767
=> Pokemoves: Update bans

data/mods/gen9ssb/moves.ts
Fixes a crash when Fennekin rolls plagiarism and some other oddities here and there.
=> SSB: Fix some move interactions

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-ru-suspect-process-round-10-voting-blastoise.3749307/page-2#post-10232816
=> SV RU: Ban Blastoise

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-zu-5-bruxish.3749282/#post-10231984
=> SV ZU: Ban Bruxish

config/formats.ts, server/rooms.ts, sim/dex-formats.ts
Sets and exports which formats will have the tera preview checkbox appear.
=> Server-Side Compatibility for the Tera Type Preview Checkbox

server/chat-plugins/auction.ts
- Allows bid timer to be modified from the default 10 seconds (30 on blind mode). Values between 7 and 120 seconds are allowed.
- Displays a running timer alongside the text notifications, which now use the error class for formatting
=> Auctions: Allow bid timer to be changed + display running timer

config/formats.ts
https://www.smogon.com/forums/threads/the-card-game-new-bans-at-post-77.3716838/page-4#post-10220872
=> The Card Game: Update bans

data/formats-data.ts
Banned via suspect test:
https://www.smogon.com/forums/threads/sv-nu-stage-13-suspect-process-gallade.3749710/#post-10239976
=> SVNU: Gallade Ban

sim/team-validator.ts
=> Remove Tera Type property in past gens

data/formats-data.ts
https://www.smogon.com/forums/threads/national-dex-uu-11-zapdos-galar.3749969/post-10245160
=> NatDex UU: Ban Zapdos-Galar

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
Monthly balance patch, nothing special, thanks as always!
=> Random Battles: August 2024 balance patch

config/formats.ts, sim/teams.ts
https://www.smogon.com/forums/threads/randbats-spotlight-cycle-15-gen-9-bring-12-pick-6-shared-power-discussion-thread.3749797
=> Add September 2024 Randomized Format Spotlight

data/text/moves.ts
Updating First Impressions Description to be consistent with Extreme Speed. >> https://www.smogon.com/forums/threads/text-change-for-first-impression.3748022/
=> Update First Impression Description

config/formats.ts
https://www.smogon.com/forums/threads/triples.3748081/page-2#post-10250613
=> Triples: Update banlist

config/formats.ts
removed via council vote https://www.smogon.com/forums/threads/necrozma-dawn-wings-has-been-quickbanned-from-ubers-uu.3750627/
=> Ubers UU: Ban Necrozma-DW

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-ubers-uu.3742166/post-10257348
=> National Dex Ubers UU: Ban Arceus-Water

config/formats.ts
https://www.smogon.com/forums/threads/stabmons-suspect-7-ceaseless-edge.3750943/#post-10264373
=> STABmons: Restrict Ceaseless Edge

config/formats.ts
https://www.smogon.com/forums/threads/adv-doubles.3666831/page-4#post-10262820
=> Gen 3 Doubles OU: Update bans

server/chat-commands/moderation.ts, server/private-messages/index.ts
Someone reported one of these to me, found two more, I have no idea what else to name the PR.
=> Random typo fixes

config/formats.ts
Quickbanned via council vote: https://www.smogon.com/forums/threads/adv-lc.3722418/post-10269132
=> ADV LC: Ban Porygon

config/formats.ts
https://www.smogon.com/forums/threads/triples.3748081/page-2#post-10268521
=> Triples: Ban Indeedee

server/chat-commands/core.ts
https://www.smogon.com/forums/threads/add-multiple-groupchat-invites-in-one-line.3745918/
Although the suggestion was specifically made for groupchats, this code allows mass-inviting to any room, which shouldn't be too big of a deal as only trusted users are allowed to mass-invite as suggested in the thread.
=> Add mass invites

config/formats.ts
Banned via council vote: https://www.smogon.com/forums/threads/nfe.3710638/page-5#post-10273221
=> SV NFE: Ban Combusken and Electabuzz

config/formats.ts
https://www.smogon.com/forums/threads/oras-1v1-suspect-mega-charizard-x.3751475/post-10275122
=> ORAS 1v1: Ban Mega Charizard X

sim/team-validator.ts
https://www.smogon.com/forums/threads/extreme-speed-volt-tackle-raichu-reported-as-go-legality-issue.3751648/
=> Fix error message for event Pokemon

server/chat-commands/room-settings.ts
Includes % in available usergroups able to use command
=> Update slowchat help

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-doubles-ou-metagame-discussion-eevium-z-banned.3720802/page-5#post-10278169
=> National Dex Doubles: Ban Eevium Z

config/formats.ts
Unbanned for suspect test for the duration of UMPL: https://www.smogon.com/forums/threads/2v2-doubles.3710849/post-10280144
=> SV 2v2: Unban Iron Hands

config/formats.ts
https://www.smogon.com/forums/threads/bug-report-validator.3751908/
https://www.smogon.com/forums/threads/inheritance-quiver-dance-banned.3712296/page-15#post-10232145
=> Inheritance: Unban Oricorio

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-balanced-hackmons.3711099/post-10220021 
I'm aware that NDBH is getting support removed soon but this is still relevant for the ongoing NDOTSL tour
=> NDBH: Ban Hadron Engine and Terapagos-Terastal

sim/team-validator.ts, test/sim/team-validator/basic.js, test/sim/team-validator/misc.js
https://www.smogon.com/forums/threads/oldgen-moves-egg-moves-in-swsh.3752047/
=> Fix Gen 8+ egg move legality

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
Monthly rands balance patch time, thanks as always for merging.
~~If possible I'd prefer it merged early next week to avoid interfering with the ongoing world cup finals, but the effects should be very minor so it's not very important if it's more effort.~~ nevermind, world cup has finished
=> Random Battles: September 2024 balance patch

config/formats.ts
https://www.smogon.com/forums/threads/bw-1v1-suspect-thundurus.3751942/post-10283104
=> BW 1v1: Ban Thundurus

data/mods/gen9ssb/moves.ts
Also an extra nerf to artemis will be added
=> SSB: Nerf Artemis

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-ou-suspect-process-round-14-voting.3752053/post-10285235
=> SV OU: Ban Kyurem

config/formats.ts, data/rulesets.ts, server/room-battle.ts, sim/dex-formats.ts
https://www.smogon.com/forums/threads/new-battle-rules-implementation.3734680/
I could've just added the two suggested rules but I figured it would be silly to only support those two rules and not the rest, plus it makes it easier to code. Drafting until I (or someone else) figures out the upper limits for the number based rules.
=> Use value rules for timer

config/formats.ts
I made a mistake in my last PR and didn't realise banning Thundurus would ban both... This corrects that mistake
=> BW 1v1: Unban Thundurus-Therian

data/random-battles/gen7/sets.json
=> Hotfix setup Deoxys-Speed in Gen 7 Random Battle

config/formats.ts
implemented the shifts from the 3months
=> Ubers UU Tier Shifts

data/formats-data.ts
https://www.smogon.com/forums/threads/np-zu-stage-11-jaws-october-shifts-12.3748500/#post-10293116
=> ZU: Ban Delphox and Hariyama

data/formats-data.ts
https://www.smogon.com/forums/threads/pu-council-updates.3718204/page-2#post-10294774
=> PU: Ban Indeedee

config/formats.ts
Trap Pass: Spider Web + Baton Pass, Mean Look + Baton Pass
https://www.smogon.com/forums/threads/gsc-pu-trap-pass.3749188/post-10230974
=> Gen 2 PU: Ban Trap Pass

data/formats-data.ts
https://www.smogon.com/forums/threads/np-stage-14-the-phoenix-cresselia-iron-thorns-banned.3752378/#post-10302863
=> NU: Ban Cresselia and Iron Thorns

data/formats-data.ts
https://www.smogon.com/forums/threads/pu-council-updates.3718204/page-2#post-10303646
=> PU: Ban Duraludon and Flamigo

config/formats.ts
https://www.smogon.com/forums/threads/balanced-hackmons.3710859/post-10304038
=> BH: Ban Clangorous Soul & No Retreat

server/chat-plugins/scavenger-games.ts, server/chat-plugins/scavengers.ts
(eg: Pokémon -> pokemon)
cc @aQrator @Snaquaza @someonewhoneedstosleep
=> Scavengers: Normalize answers before checking

config/formats.ts, data/mods/passiveaggressive/abilities.ts, data/mods/passiveaggressive/conditions.ts, data/mods/passiveaggressive/items.ts, data/mods/passiveaggressive/moves.ts, data/mods/passiveaggressive/scripts.ts
https://www.smogon.com/forums/threads/passive-aggressive.3753270/
=> Add new Passive Aggressive OM

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-ubers-suspect-process-round-4-voting-miraidon.3753462/page-5#post-10311363
=> Ubers: Ban Miraidon

config/formats.ts
https://www.smogon.com/forums/threads/almost-any-ability.3710568/post-10316784
=> AAA: Unban Revival Blessing

data/formats-data.ts
https://www.smogon.com/forums/threads/np-stage-14-the-phoenix-oricorio-pom-pom-banned-post-45.3752378/post-10319244
=> NU: Ban Oricorio-Pom-Pom

config/formats.ts
Thank goodness we already had Force Select logic from that Magikarp tournament.
https://sv-news.pokemon.co.jp/en/page/273.html
=> Add Team Star Challenge online competition

config/formats.ts
https://www.smogon.com/forums/threads/arceus-dragon-suspect-ubers-uu.3754161/
=> Ubers UU bans Arceus-Dragon via suspect

config/formats.ts
https://www.smogon.com/forums/threads/randbats-spotlight-cycle-16-gen-6-challenge-cup-triple-battles.3753678/
=> Add November 2024 Randomized Format Spotlight

sim/battle-actions.ts, test/sim/abilities/hungerswitch.js
https://www.smogon.com/forums/threads/hunger-switch-terastallization-mechanics.3735480/
=> Keep Morpeko's form while Terastallized

server/room-battle.ts
https://www.smogon.com/forums/threads/forced-public-games-on-suspect-alts-in-challenged-battles.3735329/
=> Never force challenge battles public

package-lock.json, package.json, server/README.md
Highlighted in #10535 
The changes includes updating the node version in the following files:
- `package.json` : `engines.node`
- `package-lock.json`
- `server/readme.md`
=> upgrade node version readme and package.json

data/mods/gen9ssb/moves.ts
Could potentially update the `shortDesc` if that is desired.
=> SSB: Update `desc` for Clementine

server/chat-plugins/abuse-monitor.ts, server/chat-plugins/permalocks.ts, server/chat-plugins/quotes.ts
Changes documentation of several commands to reflect the actual groups that can use the command.
=> Update documentation of several commands

data/rulesets.ts
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9879478
=> Fix interaction between Mega Rayquaza/Terastal Clauses

data/moves.ts
https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-55#post-10346635
Supercell Slam functions the same way as Body Slam in interacting with Minimize
=> Add Supercell Slam to Minimize checks

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-balanced-hackmons.3711099/post-10220021
(Wrong forme banned)
=> NDBH: Fixing Terapagos forme

data/text/moves.ts
From https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-55#post-10346635
=> Update Descriptions to Match Supercell Slam/Minimize Interaction

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-ru-suspect-process-round-12-gotta-go-fast-yanmega-banned.3754663/page-2#post-10349908
=> RU: Ban Yanmega

server/chat-formatter.ts
=> Chat: Actually prevent unmatched square brackets in URLs

data/abilities.ts, data/items.ts, sim/dex-conditions.ts
Fixes https://www.smogon.com/forums/threads/guard-dog-mirror-armor-clear-amulet-intimidate-race-condition.3739062/
Someone should test all the other TryBoost abilities with Clear Amulet at some point
=> Fix Guard Dog / Mirror Armor / Clear Amulet event order

data/mods/gen4/moves.ts, data/moves.ts, test/sim/moves/snatch.js
https://www.smogon.com/forums/threads/gen-5-7-snatch-stockpile-interaction.3754716/
=> Gen 5-7: Fix Snatch + Swallow interaction

data/rulesets.ts, sim/team-validator.ts
This makes the code in `data/rulesets.ts` very slightly more readable.
=> Improve signature of getValidationSpecies

data/random-battles/gen1/data.json, data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
=> Random Battles: November 2024 balance patch

data/formats-data.ts
https://www.smogon.com/forums/threads/np-zu-stage-12-ddu-du-ddu-du-dudunsparce-banned-14.3755027/#post-10355932
=> ZU: Ban Dudunsparce

config/formats.ts
https://www.smogon.com/forums/threads/roa-community-choice-ladder-2024-adv-format-vote.3755632/post-10356777
=> Add December 2024 Ruins of Alph spotlight ladders

data/random-battles/gen9cap/sets.json
I tried to add this to Spammernoob's PR but he didn't see it
=> CAP Random Battle: add Shox

data/text/abilities.ts
Fixes https://www.smogon.com/forums/threads/toxic-chain-update-description.3731624/
=> Edit description of Toxic Chain

data/text/items.ts, data/text/moves.ts
https://www.smogon.com/forums/threads/rock-blast-bullet-seed-et-al-missing-reference-to-loaded-dice.3755657/
=> Update 2-5 hit moves with Loaded Dice interaction

data/mods/gen3/scripts.ts, sim/pokemon.ts
Fixes a logic short circuit where using Trick Room does nothing in twisted dimension
=> Twisted Dimension: fix Trick Room interaction

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-ubers-uu-december-spotlight-ladder.3742166/post-10361551
=> National Dex Ubers UU: Ban Arceus-Dragon

data/mods/gen4/items.ts, data/mods/gen4/moves.ts
https://www.smogon.com/forums/threads/gen-4-arceus-without-multitype-should-be-able-to-gain-lose-plates.3756056/
=> Gen 4: Fix Non-Multitype Arceus Gain/Loss of Plates Interaction

config/formats.ts
https://www.smogon.com/forums/threads/twisted-dimension-omotm-december-balance-changes-page-5.3754264/page-5#post-10361682
=> Twisted Dimension: Update bans

data/mods/gen9ssb/abilities.ts, data/mods/gen9ssb/conditions.ts, data/mods/gen9ssb/moves.ts, data/mods/gen9ssb/pokedex.ts, data/mods/gen9ssb/random-teams.ts
=> All instances of string 'B/breadStycks' -> 'B/breadey'

data/conditions.ts, test/sim/moves/futuresight.js
https://www.smogon.com/forums/threads/future-attacks-affecting-wrong-slots-in-doubles.3756592/
=> Fix Future Sight slot targeting in doubles

config/formats.ts
The Smogon Draft League will be playing DPP Draft in January next and needs a format for the tournament.
https://www.smogon.com/forums/threads/draft-league-calendar-2025.3753354/post-10373914
=> Add Gen 4 Draft

data/formats-data.ts
https://www.smogon.com/forums/threads/national-dex-ru-metagame-discussion.3713801/post-10373879
=> National Dex RU: Unban Deoxys-Defense

sim/team-validator.ts
https://www.smogon.com/forums/threads/level-undefined-in-evolution-level-error.3756053/
=> Fix illegality message for underleveled Pokemon

config/formats.ts
Dry pass clause misses this one
=> 35 Pokes: Ban Baton Pass + Rapid Spin

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
Last one of the year! No big rush on this one, it's alright if the holidays prevent it for a couple days
Thanks as always and happy new year!
=> Random Battles: December 2024 balance patch

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-ubers-uu-december-spotlight-ladder.3742166/post-10387425
=> National Dex Ubers UU: Tier Shifts

data/formats-data.ts
Same deal as #10782, except with NDRU instead.
Alakazam: https://www.smogon.com/forums/threads/national-dex-ru-metagame-discussion.3713801/post-9618120
Blacephalon: https://www.smogon.com/forums/threads/national-dex-ru-metagame-discussion.3713801/post-9924236
Sableye-Mega: https://www.smogon.com/forums/threads/national-dex-ru-metagame-discussion.3713801/post-9845399
=> National Dex RU: Update bans

config/formats.ts, data/mods/gen7apex/scripts.ts, data/random-battles/gen7apex/teams.ts
https://www.smogon.com/forums/threads/randbats-spotlight-cycle-17-votes-are-open.3757107/
=> Add January 2025 Randomized Format Spotlight

config/formats.ts
=> National Dex Ubers UU: Quickban Groudon

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-almost-any-ability.3726510/post-10077505 - This happened a while back, but was never actually banned. This is my first pull request so please dm me if something went wrong!!!
=> SV National Dex AAA: Ban Light Clay

config/formats.ts
Araquanid and Zamazenta aren't supposed to be banned.
https://www.smogon.com/forums/threads/nature-swap.3757190/
=> Nature Swap: Fix bans

server/chat-plugins/auction.ts
https://www.smogon.com/forums/threads/goodbye-scrappie-its-time-for-a-change.3746287/post-10385578
- /bid is removed in order to support showing failed bid attempts
- You can now bid both with and without having a period at the beginning of your number (`.5` and `5` are the same thing)
=> Auctions: Add Tiers Not Played + changes to bidding

sim/battle-actions.ts
I think this is the only place that doesn't have a space.
=> Fix [from] message

sim/battle-actions.ts
Reverts smogon/pokemon-showdown#10796
=> Revert "Fix [from] message"

config/formats.ts
Unban Machamp in DPP DOU; was accidentally banned with the DPP OU ban
=> Unban Machamp in DPP DOU

sim/battle-actions.ts
=> Redo: Fix [from] message

data/mods/gen8bdsp/formats-data.ts
https://www.smogon.com/forums/threads/bdsp-nu-mesprit-ban-post-111.3697080/page-6#post-10400130
=> BDSP: Update tiering for RU and NU Pokemon

config/formats.ts
https://www.smogon.com/forums/threads/1v1-old-gens.3646875/post-10398391
=> ORAS 1v1: Unban Mega Blaziken

config/formats.ts
https://www.smogon.com/forums/threads/sv-monotype-suspect-10-who-let-the-dogs-out-zamazenta-suspect-test.3757205/#post-10401637
=> Monotype: Ban Zamazenta

data/mods/gen2doubles/formats-data.ts
Unban was privately communicated to me from GSCD's council, public post likely coming soon.
=> GSC Doubles: Unban Celebi

data/formats-data.ts
https://www.smogon.com/forums/threads/np-stage-15-labyrinth-mienshao-banned.3757540/post-10408604
Mienshao has been banned from NU following a suspect test.
=> SV NU: Ban Mienshao

data/mods/gen5/formats-data.ts
https://www.smogon.com/forums/threads/bw-pu-suspect-swanna.3757900/post-10406518
=> BW PU: Ban Swanna

config/formats.ts
Add Sleep Move Clause to Gen 4 Draft per the Battle Rules in https://www.smogon.com/forums/threads/dpp-i-signups.3758432/
=> add 'Sleep Move Clause' to Gen 4 Draft

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-ubers-uu-update-76.3742166/post-10417902
=> National Dex Ubers UU: Ban Arceus-Flying

config/formats.ts
https://www.smogon.com/forums/threads/nfe.3710638/post-10416144
=> SV NFE: Ban Moody

data/abilities.ts, sim/pokemon.ts, test/sim/abilities/terashell.js
Closes #10674
Research: https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-10398768
The effectiveness must be calculated at the end using the final `typeMod`.
=> Tera Shell doesn't activate if the move is already resisted

data/mods/partnersincrime/scripts.ts, data/mods/trademarked/scripts.ts, data/rulesets.ts, sim/battle.ts
Causes too many problems/crashes when mashed up
Discussed with dhelmise beforehand
=> Remove Crazyhouse Rule

config/formats.ts
Fixes a bug where abilities like Intimidate can double proc in OMs like Shared Power
=> OMs: Refactor when extra abilities and items are applied to use #10844

data/mods/gen9ssb/conditions.ts, data/mods/gen9ssb/pokedex.ts, data/mods/thecardgame/items.ts, data/pokemongo.ts, data/text/moves.ts, data/text/pokedex.ts, test/sim/moves/roost.js, test/sim/team-validator/formes.js
Narrowed it down to user-observable typos. There's several in test error messages but those don't really affect anything.
=> Data & Test: Fix several typos

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
=> Random Battles: January 2025 balance patch

config/formats.ts
[19:45:34] Elly: its supposed to have sleep moves clause
=> Alphabet Cup: Add proper sleep clause

data/mods/gen4/moves.ts, data/mods/gen7/moves.ts, data/moves.ts
https://www.smogon.com/forums/threads/bug-report-mechanics.3759273/
=> Heal Bell should not affect Good as Gold users

data/abilities.ts
=> Don't activate Perish Body if either Pokémon has a perish count

data/formats-data.ts
Cetitan banned from NU https://www.smogon.com/forums/threads/np-stage-15-labyrinth-cetitan-quickbanned.3757540/post-10432456
=> Cetitan_NUBL.ts

data/mods/gen3/formats-data.ts
https://www.smogon.com/forums/threads/adv-zu-metagame-discussion-vr-update-samples.3730430/#post-9839941
=> ADV ZU: VR Update

data/abilities.ts, data/mods/gen5/abilities.ts, data/mods/gen5/moves.ts, data/moves.ts, test/sim/abilities/magicbounce.js
https://www.smogon.com/forums/threads/bug-report-mechanics.3759245/
=> Disable Magic Bounce during semi-invulnerability

data/mods/gen5/abilities.ts, data/mods/gen5/moves.ts, test/sim/abilities/magicbounce.js
Simplify #10862
Thanks to @urkerab 
I have a test if you’d like. I’m not sure if having too many tests is a problem for you.
=> Simplify Gen 5 Magic Bounce inheritance

config/formats.ts
https://www.smogon.com/forums/threads/sv-aaa-suspect-15-feral-amalgamation-ceruledge.3758828/#post-10438108
=> AAA: Ban Ceruledge

config/formats.ts
Add a format for Gen5 Draft in preparation for the Gen5 draft tournament [happening in July](https://www.smogon.com/forums/threads/draft-league-calendar-2025.3753354/).
=> Add Gen5 Draft

data/mods/gen7/moves.ts
https://www.smogon.com/forums/threads/bug-report-mechanics.3760024/
The original PR https://github.com/smogon/pokemon-showdown/pull/10698 didn't fix the gen7 mod
=> Gen 7: Fix Snatch + Swallow interaction

config/formats.ts
https://www.smogon.com/forums/threads/np-brick-by-boring-brick-sv-nd-dou-suspect-process-5-stakataka.3759710/#post-10454128
=> National Dex Doubles: Ban Stakataka

sim/team-validator.ts
[Missing reasons for invalid event origin](https://www.smogon.com/forums/threads/bug-report-validator.3760253/)
[Egg Pokemon bypassing evolution level requirements](https://www.smogon.com/forums/threads/bug-report-validator.3760172/)
=> Fix underleveled egg Pokemon and validation message error

sim/battle.ts
https://www.smogon.com/forums/threads/bug-report-client.3760657/
=> Don't send 'upkeep' if the battle ended

lib/net.ts
Added missing error event handler
=> Fix uncaught exceptions in net library

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-godly-gift.3748640/#post-10460861
=> National Dex Godly Gift: Ban Mega Rayquaza

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
Another bunch of changes as every month! (not a lot though)
=> Random Battles: February 2025 balance patch

config/formats.ts
hey so species clause was never added to ndgg despite being on the main page and chall codes presumably due to an oversight
https://www.smogon.com/forums/threads/national-dex-godly-gift.3748640/
=> National Dex Godly Gift: Add Species Clause

data/formats-data.ts
https://www.smogon.com/forums/threads/np-zu-stage-14-firestarter-venomoth-ban-11.3759085/#post-10455380
=> Ban Venomoth from ZU

data/rulesets.ts
Adding those at the request of the BW forum staff, as they are the ones who noticed they were missing.
=> Add boosting effects to Baton Pass Stat Clause

config/formats.ts
https://www.smogon.com/forums/threads/sv-monotype-suspect-11-dirty-dancer-gouging-fire-suspect-test.3760390/post-10470291
=> Monotype: Ban Gouging Fire

server/chat-plugins/datasearch.ts
Implements the suggestion: https://www.smogon.com/forums/threads/add-restricted-as-a-ds-parameter.3676873/
Allows users to search by the 'Restricted Legendary' tag to help for formats like VGC or BSS.
=> Add Restricted as a /ds Parameter

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-uu-suspect-process-round-13-the-duck-song.3760500/page-2#post-10475920
=> UU: Ban Quaquaval

data/mods/gen1/scripts.ts
Fixes the Gen 1 Underflow bug not proccing
=> Fix Gen 1 PP underflow

data/moves.ts
https://www.smogon.com/forums/threads/psychic-noise-sometimes-reports-wrong-source-of-blocked-healing.3761420/
=> Fix Heal Block messages

config/formats.ts
https://www.smogon.com/forums/threads/sv-ubers-uu-suspect-process-round-5-dogs-zacian-suspect.3760662/page-2#post-10478558
=> Ubers UU: Ban Zacian

config/formats.ts
https://www.smogon.com/forums/threads/second-chance-regidrago-suspect.3760726/post-10478814
=> 1v1: Ban Regidrago

data/mods/gen1/formats-data.ts
https://www.smogon.com/forums/threads/rby-zu-hub.3732499/page-4#post-10479767
=> RBY ZU VL Update: Ponyta LC + Wartortle NFE

config/formats.ts
https://www.smogon.com/forums/threads/secrets-your-fire-magby-suspect-test.3760876/post-10485326
=> Little Cup: Ban Magby

config/formats.ts
https://www.smogon.com/forums/threads/rby-nu-hub.3679758/post-10496208
=> RBY NU and below: Make APT Clause transitive

data/abilities.ts, data/mods/gen8/abilities.ts
https://www.smogon.com/forums/threads/bug-report-mechanics.3762317/
=> Fix Water Shuriken's interaction with Battle Bond Greninja-Ash in Gen 9

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
Another month another patch! Not much changing, will explode again once gen10 hits of course
=> Random Battles: March 2025 balance patch

config/formats.ts
there are 7/8 votes in council discord in favor of ban for this month only, and the last vote can't change the result
=> 35Pokes: Ban Shed Tail

config/formats.ts
https://www.smogon.com/forums/threads/1v1-old-gens.3646875/post-10506727
=> GSC 1v1: Ban confusion moves

data/mods/gen5bw1/formats-data.ts
Source of tiers: https://www.smogon.com/forums/threads/smogon-university-po-statistics-%E2%80%94-march-2012.3464495/ (They did tier shifts every 3 months even then)
=> Gen 5 BW1: Use May 2012 tiers

config/formats.ts
Ban Acupressure in Relay Race OM, per VannAccessible, format leader
=> Relay Race: Ban Acupressure

config/formats.ts
Fixed https://www.smogon.com/forums/threads/pokemoves-several-bugs.3748564/ issues 2 and 3.
Fixed https://www.smogon.com/forums/threads/allowed-pokemoves-validator-rule.3750045/.
=> Fix Pokemoves Bugs: Category, Validator, and Hitting Substitute

PROTOCOL.md, config/formats.ts, data/mods/gen1/README.md, data/mods/gen3/rulesets.ts, data/mods/gen9dlc1/abilities.ts, data/rulesets.ts, lib/repl.ts, server/chat-commands/core.ts, server/chat-plugins/COMMANDS.md, server/chat-plugins/datasearch.ts, server/chat-plugins/helptickets.ts, server/chat-plugins/mafia.ts, server/chat-plugins/suspect-tests.ts, sim/SIM-PROTOCOL.md, sim/side.ts, sim/state.ts, sim/team-validator.ts, sim/tools/exhaustive-runner.ts, test/server/punishments.js, test/sim/abilities/neutralizinggas.js, test/sim/decisions.js, test/sim/misc/hazards.js, test/sim/misc/ogerpon.js, test/sim/misc/prng.js, test/sim/moves/acupressure.js, test/sim/moves/curse.js, test/sim/moves/followme.js, test/sim/moves/healblock.js, test/sim/moves/substitute.js, tools/simulate/README.md
Some are user facing, some are comments, some are code
=> Fix random typos

data/formats-data.ts
Garganacl unbanned from ND UU: https://www.smogon.com/forums/threads/gen-9-sv-national-dex-uu-metagame-discussion.3711752/page-8#post-10517849
Azumarill banned from ND RU: https://www.smogon.com/forums/threads/national-dex-ru-metagame-discussion.3713801/page-8#post-10518769
=> National Dex: Update bans

config/formats.ts
Ban Espeon: https://www.smogon.com/forums/threads/bad-n-boosted-espeon-banned.3760233/page-4#post-10523653
=> Bad 'n Boosted: ban Espeon

server/chat-plugins/datasearch.ts, test/server/chat-plugins/datasearch.js
Updates the datasearch collapsibles to use the new `.details` styling option. Reduced duplicate code for formatting datasearch outputs.
=> /ds: Collapsibles New Styling

config/formats.ts
https://www.smogon.com/forums/threads/balanced-hackmons.3710859/page-39#post-10529187
=> BH: Ban King's Rock and Razor Fang

data/abilities.ts
Suggestion https://github.com/smogon/pokemon-showdown/commit/6b3d0eefbdcd810cd3f4f0d060c71d859242581e#commitcomment-155801903
=> Refactor Magician code

config/formats.ts
https://www.smogon.com/forums/threads/mix-and-mega-suspect-14-walking-wake.3762856/post-10533623
=> Walking Wake Restricted in MnM

server/chat-commands/info.ts
Removed outdated links in /smogonintro and replaced them with up to date ones:
https://www.smogon.com/forums/threads/introduction-to-smogon.3710821/ https://www.smogon.com/forums/threads/smogon-discord-server-directory.3652546/
=> Info: Update /smogonintro links

data/mods/mixandmega/scripts.ts, data/mods/randomroulette/scripts.ts, sim/battle.ts
Requested by TDs (I think)
The blue was deemed the best display for it
=> Battles: Show custom rules in log

data/text/moves.ts
=> Fix Gen 1 Leech Seed description

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
Another month! Nothing particularly exciting inside.
Thanks as ever!
=> Random Battles: April 2025 balance patch

data/mods/gen8bdsp/formats-data.ts
https://www.smogon.com/forums/threads/bdsp-pu-grumpig-ban-post-71.3700009/page-4#post-10538113
=> BDSP: Update banlist

config/formats.ts
Announcement: https://discord.com/channels/1128016691138412604/1142247283363151872/1366318334051749999
=> 35Pokes: Ban Tangled Feet

config/formats.ts, data/random-battles/partnersincrime/teams.ts
https://www.smogon.com/forums/threads/randbats-spotlight-cycle-19-6-max-move-slots-partners-in-crime-random-doubles.3763687/
=> Add May 2025 Randomized Format Spotlight

config/formats.ts
Quickbanned by council:
https://www.smogon.com/forums/threads/sv-lc-uu-metagame-resource-and-discussion-thread.3711750/post-10535740
=> LC UU: Ban Minccino

config/formats.ts
https://www.smogon.com/forums/threads/35-pokes-april-2025.3749375/
=> 35 Pokes: May 2025 allowed list update

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-godly-gift.3748640/post-10498888
=> NatDex Godly Gift: Ban Power Construct

config/formats.ts
forgot one of the protect clones.
=> Trademarked: Updates bans

server/chat-plugins/auction.ts
https://www.smogon.com/forums/posts/10542128
=> Auctions: Auto create players when using `assignplayer`

data/mods/gen2/formats-data.ts
https://www.smogon.com/forums/threads/gsc-pu-viability-rankings-furret-less-post-16.3673353/post-10539134
=> Update GSC PU/ZU tiering

config/formats.ts
https://www.smogon.com/forums/threads/sv-bh-suspect-5-power-trip.3763405/post-10546843
=> Balanced Hackmons: Ban Power Trip

server/chat-plugins/uno.ts
Code was taken and altered from the `Chat.Commands.uno.pass` function from later in that file (line 795 of this PR, line 784 of the master branch)
=> UNO: Notify player if drawn card cannot be played

config/formats.ts
… confusion moves, Toxic)
https://www.smogon.com/forums/threads/trademarked.3714688/post-10550469
=> Trademarked: Update bans (Mew, Zamazenta-Hero, Confusion Moves, Switcheroo, Toxic)

.github/workflows/publish.yml, .github/workflows/test.yml, .github/workflows/update_version.yml
=> Github Actions: Fix linter issues and bump old actions

config/formats.ts
https://www.smogon.com/forums/threads/1v1-old-gens.3646875/post-10554192
=> ORAS 1v1: Ban Mew

data/random-battles/gen9/teams.ts
@Zarel  Fixes https://github.com/smogon/pokemon-showdown/commit/d25aba9aff5ffc510c5b0ca13807a1bd1807c0f7
=> Fix requiredTeraType

data/mods/gen3rs/rulesets.ts, sim/team-validator.ts
Volbeat cannot learn both Trick and Baton Pass.
The Seedot line cannot learn both Leech Seed and Quick Attack.
The Spheal line cannot learn both Rock Slide and Curse.
=> Validator: Only use Smeargle for egg moves if it is not Unreleased

sim/team-validator.ts
=> Validator: Check if Smeargle is nonstandard instead of its tier

config/formats.ts
https://www.smogon.com/forums/threads/trademarked.3714688/post-10559892
=> Trademarked: Ban Wish

data/abilities.ts, data/mods/gen7/abilities.ts, data/mods/gen7letsgo/scripts.ts, data/mods/gen8/abilities.ts, data/mods/gen9dlc1/scripts.ts, sim/battle-actions.ts, sim/battle.ts, sim/pokemon.ts
I regret giving it that name and never changing it.
=> Send detailschange after forme regression

config/formats.ts
https://www.smogon.com/forums/threads/trademarked.3714688/post-10562311
=> Trademarked: Restrict Skill Swap

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-ru-suspect-process-14-dance-dance-oricorio-pom-pom-suspect-test.3764185/post-10562255
=> RU: Ban Oricorio-Pom-Pom

server/chat-plugins/scavenger-games.ts
As requested by ROs, the Pointless twist announces which players submitted the least-used (but used at least once) answers, along with which answer this was.
=> Scavengers: add Pointless twist

config/formats.ts
https://www.smogon.com/forums/threads/metronome-battle.3632075/post-10567306
=> Metronome Battle: Ban Pecharunt

config/formats.ts
https://www.smogon.com/forums/threads/trademarked.3714688/post-10564464
Trademarked Restrictions:
Poison Gas
Poison Powder
Toxic Thread
I also reordered a few Pokemon:
Deoxys-Attack, Deoxys-Base
Koraidon, Kyogre, Kyurem-Black, Kyurem-White
=> Trademarked Restricts

data/pokedex.ts
https://www.smogon.com/forums/threads/bug-report-teambuilder.3765384/
=> Reorder the forms of Flabébé's evolution line

config/formats.ts
if your confused, SSNDDOU stands for Sword Shield National Dex Doubles OU
https://www.smogon.com/forums/threads/new-generation-8-national-dex-doubles-metagame-discussion-resources.3764717/post-10569613 ally switch ban
https://www.smogon.com/forums/threads/new-generation-8-national-dex-doubles-metagame-discussion-resources.3764717/post-10558240 venusaur ban
=> SSNDDOU: Ban Venusaur & Ally Switch

test/sim/abilities/magician.js
https://www.smogon.com/forums/threads/throat-spray-and-magician.3736298/
=> Add test for Magician + Throat Spray

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
=> Random Battles: May 2025 balance patch

server/chat-commands/core.ts
With preact renaming PMs to DMs this seems appropriate
=> Add /dm as a /pm alias

data/moves.ts, test/sim/moves/echoedvoice.js
https://www.smogon.com/forums/threads/echoed-voices-bp-should-raise-even-if-no-target.3753859/
=> Fix Echoed Voice's BP raise when there is no target

data/abilities.ts, data/mods/fullpotential/scripts.ts, data/mods/gen1/scripts.ts, data/mods/gen1stadium/scripts.ts, data/mods/gen2/scripts.ts, data/mods/gen2stadium2/scripts.ts, data/mods/gen3/scripts.ts, data/mods/gen4/abilities.ts, data/mods/gen9ssb/abilities.ts, data/mods/passiveaggressive/abilities.ts, data/mods/passiveaggressive/conditions.ts, data/mods/passiveaggressive/items.ts, data/mods/passiveaggressive/moves.ts, data/mods/passiveaggressive/scripts.ts, sim/battle-actions.ts, sim/pokemon.ts, test/sim/abilities/wonderguard.js
https://www.smogon.com/forums/threads/bug-report-mechanics.3765379/
=> Activate Wonder Guard if the target is immune

data/mods/gen2/formats-data.ts
https://www.smogon.com/forums/threads/zu-old-gens-hub-gsc-shifts-375.3646944/post-10561800
=> GSC ZU: Ban Poliwag and legalize Ariados

config/formats.ts
https://www.smogon.com/forums/threads/35-pokes-may-2025.3749375/
=> 35 Pokes: Update list of allowed Pokemon for June 2025

sim/pokemon.ts, test/sim/moves/wish.js
https://www.smogon.com/forums/threads/hacked-genders-across-generations.3747140/
=> Implement genderless Pokemon in Hackmons

server/chat-plugins/chatlog.ts
=> Improve chatlog error message when disabled

test/sim/misc/terastal.js
> 0 Atk Tera Steel Cufant Bullet Punch vs. 0 HP / 0 Def Mew: 48-58 (14 - 17%) -- possible 6HKO
=> Fix Terastallization test

data/mods/gen3/formats-data.ts
https://www.smogon.com/forums/threads/adv-ou-tiering-changes.3652636/post-10590571
=> ADV: Move Medicham to OU

data/mods/gen7letsgo/formats-data.ts
https://www.smogon.com/forums/threads/lgpe-ou-viability-rankings-update-post-66.3656868/page-3#post-10603359
=> LGPE: Implement OU tier changes

data/mods/gen3/abilities.ts, sim/dex-conditions.ts, test/sim/abilities/magnetpull.js
https://www.smogon.com/forums/threads/magnet-pull-vs-steel-type-allies-in-gen-3.3758269/
=> Magnet Pull should pull allies in Gen 3

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-national-dex-uu-stage-8-1-hombre-religioso.3765890/#post-10596244
=> National Dex UU: Ban Hawlucha

config/formats.ts
https://www.smogon.com/forums/threads/sv-ubers-uu-suspect-process-round-6-a-horse-with-no-name-spectrier.3766279/post-10607517
=> Ubers UU: Ban Spectrier

config/formats.ts, data/mods/gen6/formats-data.ts
https://www.smogon.com/forums/threads/light-clay-and-huntail-in-oras-zu.3765744/#post-10603874
=> ORAS ZU: Ban Huntail and Light Clay

config/formats.ts
40 Pokes this time (commemorating 2nd anniversary of the format's beginning)
https://www.smogon.com/forums/threads/35-pokes-june-2025.3749375/
=> 35 Pokes: Update list of allowed Pokemon for July 2025

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json
Same old, same old. Thanks as always.
=> Random Battles: June 2025 balance patch

data/mods/gen4/moves.ts, data/moves.ts, sim/pokemon.ts, test/sim/abilities/klutz.js
Fixes one of the three bugs from https://www.smogon.com/forums/threads/klutz-and-synchronize-bugs-in-gen-4.3748310/
The Gen 4 part is reported in the thread above.
For the modern generations, I tested using Fling with Ability Shield and Power Band, and both failed.
=> Fix Klutz's interaction with Fling

data/formats-data.ts
https://www.smogon.com/forums/threads/np-sv-ru-stage-18-kings-queens-july-2025-shifts-ogerpon-quickbanned.3767219/
=> RU: Ban Ogerpon

data/formats-data.ts
https://www.smogon.com/forums/threads/np-stage-17-barracuda-politoed-banned-tier-shift.3767218/#post-10610897
=> NU: Ban Politoed

config/CUSTOM-RULES.md
=> Deprecate "Custom" group bans

config/formats.ts
https://www.smogon.com/forums/threads/sv-nfe-metagame-discussion-vigoroth-ban-post-146.3710638/post-10618590
=> SV NFE: Ban Vigoroth

config/formats.ts
https://www.smogon.com/forums/threads/godly-gift.3710734/post-10580585
=> Godly Gift: Evasion Abilities Clause

data/mods/gen8bdsp/formats-data.ts
https://www.smogon.com/forums/threads/bdsp-pu-tier-shifts-post-79.3700009/page-4#post-10626194
=> BDSP: Ban Chatot and Drifblim from PU

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-ubers-uu-shifts-84.3742166/post-10610952
=> National Dex Ubers UU: Implement Tier Shifts

server/room-battle.ts, sim/side.ts, test/sim/decisions.js
This was brought to my attention in #11208
=> Don't update the timer when an updated request is sent

data/random-battles/gen9cap/sets.json
this thing more broken than cawm y'all
=> CAP Random Battle - Add Ramnarok

config/formats.ts
https://www.smogon.com/forums/threads/rby-uu-hub.3647713/page-10#post-10630807
=> Gen 1: Ban all partial trapping moves from UU

data/formats-data.ts
https://www.smogon.com/forums/threads/sv-national-dex-uu-stage-8-2-king-without-a-crown.3768238/
=> NatDex UU: Ban Iron Crown

data/formats-data.ts
https://www.smogon.com/forums/threads/np-zu-stage-16-duckworth-porygon2-banned-11.3767770/post-10648299
=> ZU: Ban Porygon2

data/conditions.ts, data/moves.ts, test/sim/moves/burnup.js
https://www.smogon.com/forums/threads/bug-report-mechanics.3768556/
=> Burn Up shouldn't thaw the user if it isn't a Fire type

config/formats.ts
Requested by randbats staff
https://discord.com/channels/294651453279174656/1012049648472559656/1401573244028453049
=> Advertise Ladder Achievements Project for the Randomized Spotlight

config/formats.ts
https://www.smogon.com/forums/threads/35-pokes-august-2025.3749375/page-8#post-10660401
=> 35 Pokes: Ban Toxapex and unban Scizor

config/formats.ts
it's illegal already, but showing up in the teambuilder
=> 35 Pokes: Ban Scizor-Mega

config/formats.ts, data/abilities.ts, data/mods/gen3/abilities.ts, data/mods/gen4/abilities.ts, data/mods/gen7pokebilities/scripts.ts, data/mods/gen8linked/scripts.ts, data/mods/gen9dlc1/scripts.ts, data/mods/gen9ssb/abilities.ts, data/mods/gen9ssb/scripts.ts, data/mods/monkeyspaw/scripts.ts, data/mods/partnersincrime/scripts.ts, data/mods/pokebilities/scripts.ts, data/mods/trademarked/scripts.ts, data/moves.ts, sim/battle.ts, sim/global-types.ts, sim/pokemon.ts
https://www.smogon.com/forums/threads/traces-activation-timing.3737078/
The only relevant changes are in:
* `data/abilities.ts`
* `data/moves.ts`
* `sim/pokemon.ts`
The rest of the changes are due to me shifting the arguments of `Pokemon#setAbility`.
=> Fix Trace message timing

config/formats.ts
https://www.smogon.com/forums/threads/uu-om-megathread.3735355/page-3#post-10681015
=> AAA UU: Ban Archaludon and Mamoswine

config/formats.ts
https://www.smogon.com/forums/threads/1v1-other-tiers.3726778/#post-10671271
=> National Dex 1v1: Ban Melmetal

config/formats.ts
https://www.smogon.com/forums/threads/bw-doubles-ou-shadow-tag-suspect-post-79.3606719/post-10684817
=> BW Doubles OU: Ban Shadow Tag

data/mods/gen3/formats-data.ts
https://www.smogon.com/forums/threads/revisiting-adv-nu.3749245/post-10685090
=> ADV NU: Ban Glalie

test/sim/items/lumberry.js
=> Add test for Poison Puppeteer and Lum Berry interaction

config/formats.ts
https://www.smogon.com/forums/threads/national-dex-godly-gift.3748640/post-10688437
=> National Dex Godly Gift: Update bans

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json, data/random-battles/gen9/sets.json, pokemon-showdown
Another month, another patch, thanks as always!
Nothing major this time
=> Random Battles: August 2025 balance patch

test/sim/abilities/fairyaura.js
https://www.smogon.com/forums/threads/past-gens-research-thread.3506992/page-12#post-10679073
=> Add tests for Fairy Aura and Mold Breaker interaction

config/formats.ts, data/rulesets.ts, test/sim/team-validator/misc.js
https://www.smogon.com/forums/threads/speedpass-in-adv-ou.3769223/page-3#post-10692421
=> ADV: Add Speed Pass Clause

data/abilities.ts, data/mods/gen4/moves.ts, data/mods/gen7/abilities.ts, data/moves.ts, sim/dex-conditions.ts, sim/pokemon.ts, test/sim/abilities/cudchew.js, test/sim/abilities/neutralizinggas.js
https://www.smogon.com/forums/threads/cud-chew-behavior.3736886/
Most of these interactions were documented in the bug report by DaWoblefet, but I still tested all of them myself.
=> Correctly implement Cud Chew and Slow Start

config/formats.ts
https://www.smogon.com/forums/threads/almost-any-ability-uu.3770034/#post-10701164
=> AAA UU: Ban Hydreigon, Slither Wing​ and Zamazenta-Crowned

data/mods/gen3/formats-data.ts
https://www.smogon.com/forums/threads/clamperl-in-adv-zu.3771014/ Clamperl is being quickbanned with an immediate suspect test
=> Quickban Clamperl from ADV ZU

config/formats.ts
https://www.smogon.com/forums/threads/rby-uu-hub.3647713/post-10714681
=> RBY UU: Ban Confuse Ray and Supersonic

sim/team-validator.ts
https://www.smogon.com/forums/threads/gender-validation-skipped.3771139/
Residual problem from one of my previous PRs.
=> Fix gender validation skip

config/formats.ts, data/mods/gen7/formats-data.ts
https://www.smogon.com/forums/threads/vulpix-alola-in-sm-lc.3771276/#post-10718757
=> SM LC: Ban Vulpix-Alola

data/mods/gen7letsgo/formats-data.ts
https://www.smogon.com/forums/threads/lgpe-ru-major-tier-shifts.3696384/#post-10719817
15 drops, 1 rise
=> LGPE: UU/RU tier changes

config/formats.ts
https://www.smogon.com/forums/threads/35-pokes-september-2025.3749375/
=> 35 Pokes: Update list of allowed Pokemon for October 2025

data/random-battles/gen3/sets.json, data/random-battles/gen4/sets.json, data/random-battles/gen5/sets.json, data/random-battles/gen6/sets.json, data/random-battles/gen7/sets.json, data/random-battles/gen8/data.json, data/random-battles/gen9/doubles-sets.json
Good day, another month another patch.
Very little movement is happening anymore as equilibrium is essentially achieved, save for the occasional set change or noise. I'm considering scaling back the frequency of these patches. Please let me know if there's something I need to keep in mind wrt the technical side for that, though I can't imagine what that would be.
=> Random Battles: September 2025 balance patch

config/formats.ts, data/rulesets.ts, sim/side.ts
https://battle-lp1.pokemon-home.com/scvi/regulation/anrjjyxlbddu5utuqycn/en-s
=> Add Terastal Crescendo online competition

data/mods/blankcanvas/rulesets.ts, data/random-battles/blankcanvas/random-sets.json, data/random-battles/blankcanvas/teams.ts
Fix for the new sprite viewer code to get the sprites to appear again. A good number of mons in the mod don't have sprites so they'll still fail to load but the ones that do will hopefully show up again now.
=> Blank Canvas: Fix New Sprite Viewer Code

config/formats.ts
https://www.smogon.com/forums/threads/35-pokes-september-2025.3749375/post-10724031
=> 35 Pokes: Ban Spinda, unban Moltres

data/formats-data.ts
https://www.smogon.com/forums/threads/np-stage-17-azelf-terrakion-banned.3767218/post-10728227
=> NU: Ban Azelf
